### ISSUE TITLE
Server connection failed

### ISSUE THREAD

**Issue by biezhihua** [jellyfin/jellyfin-androidtv#1025]
**Describe the bug**
Enter the server address and click OK. Unable to connect successfully.

**To Reproduce**
1. Lunch TV App
2. Input server address and port: 192.168.10.27:8097
3. click OK

**Expected behavior**
Go to the media information page.

**Logs**
```
07-18 13:06:22.275 14835 14835 I Jellyfin-AndroidTV: Application object created
07-18 13:06:22.350 14835 14835 I Jellyfin-AndroidTV: Basic network permissions are granted
07-18 13:06:22.512 14835 14835 D Jellyfin-AndroidTV: Entering initial connection workflow
07-18 13:06:22.513 14835 14835 D Jellyfin-AndroidTV: Getting saved servers via credential provider
07-18 13:06:22.517 14835 14835 D Jellyfin-AndroidTV: Scanning network for local servers
07-18 13:06:22.519 14835 15280 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Request packet sent to: 255.255.255.255 (DEFAULT)
07-18 13:06:22.522 14835 15280 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Request packet sent to: 192.168.10.255; Interface: wlan0
07-18 13:06:22.524 14835 15280 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Done looping over all network interfaces. Now waiting for a reply!
07-18 13:06:23.525 14835 15280 D Jellyfin-AndroidTV: Server discovery timed out waiting for response.
07-18 13:06:23.525 14835 15280 D Jellyfin-AndroidTV: Found 0 servers
07-18 13:06:23.535 14835 15280 D Jellyfin-AndroidTV: Looping through server list
07-18 13:06:23.535 14835 15280 D Jellyfin-AndroidTV: No saved authentication
07-18 13:06:23.535 14835 15280 D Jellyfin-AndroidTV: Select A server
07-18 13:06:23.535 14835 15280 D Jellyfin-AndroidTV: Getting saved servers via credential provider
07-18 13:06:23.535 14835 15280 D Jellyfin-AndroidTV: Scanning network for local servers
07-18 13:06:23.537 14835 15289 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Request packet sent to: 255.255.255.255 (DEFAULT)
07-18 13:06:23.539 14835 15289 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Request packet sent to: 192.168.10.255; Interface: wlan0
07-18 13:06:23.541 14835 15289 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Done looping over all network interfaces. Now waiting for a reply!
07-18 13:06:24.018 14835 14835 I Jellyfin-AndroidTV: Basic network permissions are granted
07-18 13:06:24.050 14835 14835 D Jellyfin-AndroidTV: Entering initial connection workflow
07-18 13:06:24.050 14835 14835 D Jellyfin-AndroidTV: Getting saved servers via credential provider
07-18 13:06:24.051 14835 14835 D Jellyfin-AndroidTV: Scanning network for local servers
07-18 13:06:24.053 14835 15299 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Request packet sent to: 255.255.255.255 (DEFAULT)
07-18 13:06:24.056 14835 15299 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Request packet sent to: 192.168.10.255; Interface: wlan0
07-18 13:06:24.061 14835 15299 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Done looping over all network interfaces. Now waiting for a reply!
07-18 13:06:24.543 14835 15289 D Jellyfin-AndroidTV: Server discovery timed out waiting for response.
07-18 13:06:24.544 14835 15289 D Jellyfin-AndroidTV: Found 0 servers
07-18 13:06:25.062 14835 15299 D Jellyfin-AndroidTV: Server discovery timed out waiting for response.
07-18 13:06:25.063 14835 15299 D Jellyfin-AndroidTV: Found 0 servers
07-18 13:06:25.063 14835 15299 D Jellyfin-AndroidTV: Looping through server list
07-18 13:06:25.063 14835 15299 D Jellyfin-AndroidTV: No saved authentication
07-18 13:06:25.063 14835 15299 D Jellyfin-AndroidTV: Select A server
07-18 13:06:25.063 14835 15299 D Jellyfin-AndroidTV: Getting saved servers via credential provider
07-18 13:06:25.063 14835 15299 D Jellyfin-AndroidTV: Scanning network for local servers
07-18 13:06:25.066 14835 15310 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Request packet sent to: 255.255.255.255 (DEFAULT)
07-18 13:06:25.069 14835 15310 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Request packet sent to: 192.168.10.255; Interface: wlan0
07-18 13:06:25.072 14835 15310 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Done looping over all network interfaces. Now waiting for a reply!
07-18 13:06:26.078 14835 15310 D Jellyfin-AndroidTV: Server discovery timed out waiting for response.
07-18 13:06:26.081 14835 15310 D Jellyfin-AndroidTV: Found 0 servers
07-18 13:06:44.879 14835 14835 D Jellyfin-AndroidTV: Entered address: 192.168.19.27:8097
07-18 13:06:44.883 14835 14835 D Jellyfin-AndroidTV: Attempting to connect to server at https://192.168.19.27:8097
07-18 13:06:44.893 14835 14835 D Jellyfin-AndroidTV: Adding request to queue: https://192.168.19.27:8097/system/info/public?format=json
07-18 13:06:52.987 14835 14835 E Jellyfin-AndroidTV: VolleyError com.android.volley.TimeoutError: null
07-18 13:06:52.987 14835 14835 E Jellyfin-AndroidTV: com.android.volley.TimeoutError
07-18 13:06:52.987 14835 14835 E Jellyfin-AndroidTV: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:173)
07-18 13:06:52.987 14835 14835 E Jellyfin-AndroidTV: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
07-18 13:06:52.987 14835 14835 E Jellyfin-AndroidTV: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
07-18 13:06:52.987 14835 14835 E Jellyfin-AndroidTV: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
07-18 13:06:52.988 14835 14835 D Jellyfin-AndroidTV: No server available
07-18 13:06:52.989 14835 14835 D Jellyfin-AndroidTV: Attempting to connect to server at http://192.168.19.27:8097
07-18 13:06:52.992 14835 14835 D Jellyfin-AndroidTV: Adding request to queue: http://192.168.19.27:8097/system/info/public?format=json
07-18 13:07:01.055 14835 14835 E Jellyfin-AndroidTV: VolleyError com.android.volley.TimeoutError: null
07-18 13:07:01.055 14835 14835 E Jellyfin-AndroidTV: com.android.volley.TimeoutError
07-18 13:07:01.055 14835 14835 E Jellyfin-AndroidTV: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:173)
07-18 13:07:01.055 14835 14835 E Jellyfin-AndroidTV: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
07-18 13:07:01.055 14835 14835 E Jellyfin-AndroidTV: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
07-18 13:07:01.055 14835 14835 E Jellyfin-AndroidTV: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
07-18 13:07:01.056 14835 14835 D Jellyfin-AndroidTV: No server available
07-18 13:07:27.745 14835 14835 D Jellyfin-AndroidTV: Entered address: 192.168.10.27:8097
07-18 13:07:27.746 14835 14835 D Jellyfin-AndroidTV: Attempting to connect to server at https://192.168.10.27:8097
07-18 13:07:27.748 14835 14835 D Jellyfin-AndroidTV: Adding request to queue: https://192.168.10.27:8097/system/info/public?format=json
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: VolleyError com.android.volley.NoConnectionError: javax.net.ssl.SSLHandshakeException: Handshake failed
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: com.android.volley.NoConnectionError: javax.net.ssl.SSLHandshakeException: Handshake failed
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:181)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:288)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.volley.toolbox.HurlStack.executeRequest(HurlStack.java:96)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:123)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	... 3 more
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x7713e94c08: Failure in SSL library, usually a protocol error
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (external/boringssl/src/ssl/tls_record.cc:242 0x7762c23e6b:0x00000000)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
07-18 13:07:27.812 14835 14835 E Jellyfin-AndroidTV: 	... 18 more
07-18 13:07:27.812 14835 14835 D Jellyfin-AndroidTV: No server available
07-18 13:07:27.812 14835 14835 D Jellyfin-AndroidTV: Attempting to connect to server at http://192.168.10.27:8097
07-18 13:07:27.813 14835 14835 D Jellyfin-AndroidTV: Adding request to queue: http://192.168.10.27:8097/system/info/public?format=json
07-18 13:07:27.838 14835 14835 I Jellyfin-AndroidTV: Response received from: http://192.168.10.27:8097/system/info/public?format=json
07-18 13:07:27.898 14835 14835 D Jellyfin-AndroidTV: Adding request to queue: http://192.168.10.27:8097/Users/Public?format=json
07-18 13:07:28.020 14835 14835 I Jellyfin-AndroidTV: Response received from: http://192.168.10.27:8097/Users/Public?format=json



07-18 13:07:44.009 14835 14835 D Jellyfin-AndroidTV: Getting saved servers via credential provider
07-18 13:07:44.022 14835 14835 D Jellyfin-AndroidTV: Scanning network for local servers
07-18 13:07:44.029 14835 15707 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Request packet sent to: 255.255.255.255 (DEFAULT)
07-18 13:07:44.041 14835 15707 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Request packet sent to: 192.168.10.255; Interface: wlan0
07-18 13:07:44.047 14835 15707 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Done looping over all network interfaces. Now waiting for a reply!
07-18 13:07:44.167 14835 14835 D Jellyfin-AndroidTV: Getting saved servers via credential provider
07-18 13:07:44.168 14835 14835 D Jellyfin-AndroidTV: Scanning network for local servers
07-18 13:07:44.170 14835 15711 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Request packet sent to: 255.255.255.255 (DEFAULT)
07-18 13:07:44.175 14835 15711 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Request packet sent to: 192.168.10.255; Interface: wlan0
07-18 13:07:44.180 14835 15711 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Done looping over all network interfaces. Now waiting for a reply!
07-18 13:07:45.049 14835 15707 D Jellyfin-AndroidTV: Server discovery timed out waiting for response.
07-18 13:07:45.051 14835 15707 D Jellyfin-AndroidTV: Found 0 servers
07-18 13:07:45.140 14835 14835 D Jellyfin-AndroidTV: Loading more items starting at 1
07-18 13:07:45.180 14835 15711 D Jellyfin-AndroidTV: Server discovery timed out waiting for response.
07-18 13:07:45.181 14835 15711 D Jellyfin-AndroidTV: Found 0 servers
07-18 13:07:45.292 14835 14835 D Jellyfin-AndroidTV: Loading more items starting at 1
07-18 13:07:50.185 14835 14835 D Jellyfin-AndroidTV: Attempting to connect to server at http://192.168.10.27:8097
07-18 13:07:50.186 14835 14835 D Jellyfin-AndroidTV: Adding request to queue: http://192.168.10.27:8097/system/info/public?format=json
07-18 13:07:50.221 14835 14835 I Jellyfin-AndroidTV: Response received from: http://192.168.10.27:8097/system/info/public?format=json
07-18 13:07:50.274 14835 14835 D Jellyfin-AndroidTV: Adding request to queue: http://192.168.10.27:8097/Users/Public?format=json
07-18 13:07:50.365 14835 14835 I Jellyfin-AndroidTV: Response received from: http://192.168.10.27:8097/Users/Public?format=json
07-18 13:07:52.781 14835 14835 D Jellyfin-AndroidTV: Getting saved servers via credential provider
07-18 13:07:52.783 14835 14835 D Jellyfin-AndroidTV: Scanning network for local servers
07-18 13:07:52.787 14835 15763 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Request packet sent to: 255.255.255.255 (DEFAULT)
07-18 13:07:52.794 14835 15763 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Request packet sent to: 192.168.10.255; Interface: wlan0
07-18 13:07:52.799 14835 15763 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Done looping over all network interfaces. Now waiting for a reply!
07-18 13:07:52.958 14835 14835 D Jellyfin-AndroidTV: Getting saved servers via credential provider
07-18 13:07:52.961 14835 14835 D Jellyfin-AndroidTV: Scanning network for local servers
07-18 13:07:52.964 14835 15767 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Request packet sent to: 255.255.255.255 (DEFAULT)
07-18 13:07:52.970 14835 15767 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Request packet sent to: 192.168.10.255; Interface: wlan0
07-18 13:07:52.976 14835 15767 D Jellyfin-AndroidTV: org.jellyfin.apiclient.interaction.discovery.ServerLocator >>> Done looping over all network interfaces. Now waiting for a reply!
07-18 13:07:53.802 14835 15763 D Jellyfin-AndroidTV: Server discovery timed out waiting for response.
07-18 13:07:53.803 14835 15763 D Jellyfin-AndroidTV: Found 0 servers
07-18 13:07:53.880 14835 14835 D Jellyfin-AndroidTV: Loading more items starting at 1
07-18 13:07:53.977 14835 15767 D Jellyfin-AndroidTV: Server discovery timed out waiting for response.
07-18 13:07:53.978 14835 15767 D Jellyfin-AndroidTV: Found 0 servers
07-18 13:07:54.045 14835 14835 D Jellyfin-AndroidTV: Loading more items starting at 1
```

**Screenshots**
no

**System (please complete the following information):**
 - Android TV
 - Device manufacturer: Sony
 - Device model: []
 - Jellyfin server version: 10.7.5

**Additional context**

**Comment by nielsvanvelzen** [comment]
The default Jellyfin ports are 8096 for HTTP or 8920 for HTTPS. Are you sure 8097 is the correct port for you?

**Comment by brianjmurrell** [comment]
Are 8096 and 8920 hard coded in the app or are the ports that the server is configured to use supposed to be included in the auto-discovery mechanism?
