### ISSUE TITLE
Cannot connect to jellyfin server using nightlies 

### ISSUE THREAD

**Issue by romainrbr** [jellyfin/jellyfin-androidtv#1026]
Can't connect using latest debug-build, and latest Jellyfin version (tested with both `10.7.6-1` and `20210717.3-unstable`.
Wiped main Jellyfin app beforehand (alongside with settings).

I can see logs through adb on the Android TV device, but nothing on the server side (neither on Jellyfin or on the reverse proxy)

**To Reproduce**
1. Install Jellyfin debug APK
2. Try to connect to server, using either :
- Internal IP (with 8096 port)
- External IP going through Nginx
3. Connection failed

**Expected behavior**
Connection to the server working

**Logs**
```
07-18 14:48:34.234  2290  2290 E o.j.s.a.c.KtorClient: Unknown error occurred!
07-18 14:48:34.234  2290  2290 E o.j.s.a.c.KtorClient: java.lang.IllegalArgumentException: Unexpected char 0xa0 at 101 in Authorization value: MediaBrowser Client="Android TV", Version="0.0.0-dev.1", DeviceId="6dcd472cebc54050", Device="Android TV"
07-18 14:48:34.234  2290  2290 E o.j.s.a.c.KtorClient: 	at okhttp3.Headers$Companion.checkValue(Headers.kt:434)
07-18 14:48:34.234  2290  2290 E o.j.s.a.c.KtorClient: 	at okhttp3.Headers$Companion.access$checkValue(Headers.kt:346)
07-18 14:48:34.234  2290  2290 E o.j.s.a.c.KtorClient: 	at okhttp3.Headers$Builder.add(Headers.kt:245)
07-18 14:48:34.234  2290  2290 E o.j.s.a.c.KtorClient: 	at okhttp3.Request$Builder.addHeader(Request.kt:210)
07-18 14:48:34.234  2290  2290 E o.j.s.a.c.KtorClient: 	at io.ktor.client.engine.okhttp.OkHttpEngineKt$convertToOkHttpRequest$1$1.invoke(OkHttpEngine.kt:189)
07-18 14:48:34.234  2290  2290 E o.j.s.a.c.KtorClient: 	at io.ktor.client.engine.okhttp.OkHttpEngineKt$convertToOkHttpRequest$1$1.invoke(OkHttpEngine.kt:186)
07-18 14:48:34.234  2290  2290 E o.j.s.a.c.KtorClient: 	at io.ktor.client.engine.UtilsKt$mergeHeaders$2.invoke(Utils.kt:37)
07-18 14:48:34.234  2290  2290 E o.j.s.a.c.KtorClient: 	at io.ktor.client.engine.UtilsKt$mergeHeaders$2.invoke(Utils.kt:32)
07-18 14:48:34.234  2290  2290 E o.j.s.a.c.KtorClient: 	at io.ktor.util.StringValuesImpl.forEach(StringValues.kt:146)
07-18 14:48:34.234  2290  2290 E o.j.s.a.c.KtorClient: 	at io.ktor.client.engine.UtilsKt.mergeHeaders(Utils.kt:32)
07-18 14:48:34.234  2290  2290 E o.j.s.a.c.KtorClient: 	at io.ktor.client.engine.okhttp.OkHttpEngineKt.convertToOkHttpRequest(OkHttpEngine.kt:186)
07-18 14:48:34.234  2290  2290 E o.j.s.a.c.KtorClient: 	at io.ktor.client.engine.okhttp.OkHttpEngineKt.access$convertToOkHttpRequest(OkHttpEngine.kt:1)
07-18 14:48:34.234  2290  2290 E o.j.s.a.c.KtorClient: 	at io.ktor.client.engine.okhttp.OkHttpEngine.execute(OkHttpEngine.kt:72)
07-18 14:48:34.234  2290  2290 E o.j.s.a.c.KtorClient: 	at io.ktor.client.engine.HttpClientEngine$executeWithinCallContext$2.invokeSuspend(HttpClientEngine.kt:85)
07-18 14:48:34.234  2290  2290 E o.j.s.a.c.KtorClient: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07-18 14:48:34.234  2290  2290 E o.j.s.a.c.KtorClient: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
07-18 14:48:34.234  2290  2290 E o.j.s.a.c.KtorClient: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
07-18 14:48:34.234  2290  2290 E o.j.s.a.c.KtorClient: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
07-18 14:48:34.234  2290  2290 E o.j.s.a.c.KtorClient: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
07-18 14:48:34.234  2290  2290 E o.j.s.a.c.KtorClient: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
07-18 14:48:34.239  2290  2290 E RecommendedServerDiscov: Could not retrieve public system info for https://192.168.1.203:8096
07-18 14:48:34.239  2290  2290 E RecommendedServerDiscov: java.lang.IllegalArgumentException: Unexpected char 0xa0 at 101 in Authorization value: MediaBrowser Client="Android TV", Version="0.0.0-dev.1", DeviceId="6dcd472cebc54050", Device="Android TV"
07-18 14:48:34.239  2290  2290 E RecommendedServerDiscov: 	at okhttp3.Headers$Companion.checkValue(Headers.kt:434)
07-18 14:48:34.239  2290  2290 E RecommendedServerDiscov: 	at okhttp3.Headers$Companion.access$checkValue(Headers.kt:346)
07-18 14:48:34.239  2290  2290 E RecommendedServerDiscov: 	at okhttp3.Headers$Builder.add(Headers.kt:245)
07-18 14:48:34.239  2290  2290 E RecommendedServerDiscov: 	at okhttp3.Request$Builder.addHeader(Request.kt:210)
07-18 14:48:34.239  2290  2290 E RecommendedServerDiscov: 	at io.ktor.client.engine.okhttp.OkHttpEngineKt$convertToOkHttpRequest$1$1.invoke(OkHttpEngine.kt:189)
07-18 14:48:34.239  2290  2290 E RecommendedServerDiscov: 	at io.ktor.client.engine.okhttp.OkHttpEngineKt$convertToOkHttpRequest$1$1.invoke(OkHttpEngine.kt:186)
07-18 14:48:34.239  2290  2290 E RecommendedServerDiscov: 	at io.ktor.client.engine.UtilsKt$mergeHeaders$2.invoke(Utils.kt:37)
07-18 14:48:34.239  2290  2290 E RecommendedServerDiscov: 	at io.ktor.client.engine.UtilsKt$mergeHeaders$2.invoke(Utils.kt:32)
07-18 14:48:34.239  2290  2290 E RecommendedServerDiscov: 	at io.ktor.util.StringValuesImpl.forEach(StringValues.kt:146)
07-18 14:48:34.239  2290  2290 E RecommendedServerDiscov: 	at io.ktor.client.engine.UtilsKt.mergeHeaders(Utils.kt:32)
07-18 14:48:34.239  2290  2290 E RecommendedServerDiscov: 	at io.ktor.client.engine.okhttp.OkHttpEngineKt.convertToOkHttpRequest(OkHttpEngine.kt:186)
07-18 14:48:34.239  2290  2290 E RecommendedServerDiscov: 	at io.ktor.client.engine.okhttp.OkHttpEngineKt.access$convertToOkHttpRequest(OkHttpEngine.kt:1)
07-18 14:48:34.239  2290  2290 E RecommendedServerDiscov: 	at io.ktor.client.engine.okhttp.OkHttpEngine.execute(OkHttpEngine.kt:72)
07-18 14:48:34.239  2290  2290 E RecommendedServerDiscov: 	at io.ktor.client.engine.HttpClientEngine$executeWithinCallContext$2.invokeSuspend(HttpClientEngine.kt:85)
07-18 14:48:34.239  2290  2290 E RecommendedServerDiscov: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07-18 14:48:34.239  2290  2290 E RecommendedServerDiscov: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
07-18 14:48:34.239  2290  2290 E RecommendedServerDiscov: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
07-18 14:48:34.239  2290  2290 E RecommendedServerDiscov: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
07-18 14:48:34.239  2290  2290 E RecommendedServerDiscov: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
07-18 14:48:34.239  2290  2290 E RecommendedServerDiscov: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
07-18 14:48:34.251  2290  2290 I RecommendedServerDiscov: Requesting public system info for http://192.168.1.203:8096
07-18 14:48:34.278  2290  2290 I o.j.s.a.c.KtorClient: HttpMethod(value=GET) http://192.168.1.203:8096/System/Info/Public
07-18 14:48:34.330  2290  2290 E o.j.s.a.c.KtorClient: Unknown error occurred!
07-18 14:48:34.330  2290  2290 E o.j.s.a.c.KtorClient: java.lang.IllegalArgumentException: Unexpected char 0xa0 at 101 in Authorization value: MediaBrowser Client="Android TV", Version="0.0.0-dev.1", DeviceId="6dcd472cebc54050", Device="Android TV"
07-18 14:48:34.330  2290  2290 E o.j.s.a.c.KtorClient: 	at okhttp3.Headers$Companion.checkValue(Headers.kt:434)
07-18 14:48:34.330  2290  2290 E o.j.s.a.c.KtorClient: 	at okhttp3.Headers$Companion.access$checkValue(Headers.kt:346)
07-18 14:48:34.330  2290  2290 E o.j.s.a.c.KtorClient: 	at okhttp3.Headers$Builder.add(Headers.kt:245)
07-18 14:48:34.330  2290  2290 E o.j.s.a.c.KtorClient: 	at okhttp3.Request$Builder.addHeader(Request.kt:210)
07-18 14:48:34.330  2290  2290 E o.j.s.a.c.KtorClient: 	at io.ktor.client.engine.okhttp.OkHttpEngineKt$convertToOkHttpRequest$1$1.invoke(OkHttpEngine.kt:189)
07-18 14:48:34.330  2290  2290 E o.j.s.a.c.KtorClient: 	at io.ktor.client.engine.okhttp.OkHttpEngineKt$convertToOkHttpRequest$1$1.invoke(OkHttpEngine.kt:186)
07-18 14:48:34.330  2290  2290 E o.j.s.a.c.KtorClient: 	at io.ktor.client.engine.UtilsKt$mergeHeaders$2.invoke(Utils.kt:37)
07-18 14:48:34.330  2290  2290 E o.j.s.a.c.KtorClient: 	at io.ktor.client.engine.UtilsKt$mergeHeaders$2.invoke(Utils.kt:32)
07-18 14:48:34.330  2290  2290 E o.j.s.a.c.KtorClient: 	at io.ktor.util.StringValuesImpl.forEach(StringValues.kt:146)
07-18 14:48:34.330  2290  2290 E o.j.s.a.c.KtorClient: 	at io.ktor.client.engine.UtilsKt.mergeHeaders(Utils.kt:32)
07-18 14:48:34.330  2290  2290 E o.j.s.a.c.KtorClient: 	at io.ktor.client.engine.okhttp.OkHttpEngineKt.convertToOkHttpRequest(OkHttpEngine.kt:186)
07-18 14:48:34.330  2290  2290 E o.j.s.a.c.KtorClient: 	at io.ktor.client.engine.okhttp.OkHttpEngineKt.access$convertToOkHttpRequest(OkHttpEngine.kt:1)
07-18 14:48:34.330  2290  2290 E o.j.s.a.c.KtorClient: 	at io.ktor.client.engine.okhttp.OkHttpEngine.execute(OkHttpEngine.kt:72)
07-18 14:48:34.330  2290  2290 E o.j.s.a.c.KtorClient: 	at io.ktor.client.engine.HttpClientEngine$executeWithinCallContext$2.invokeSuspend(HttpClientEngine.kt:85)
07-18 14:48:34.330  2290  2290 E o.j.s.a.c.KtorClient: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07-18 14:48:34.330  2290  2290 E o.j.s.a.c.KtorClient: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
07-18 14:48:34.330  2290  2290 E o.j.s.a.c.KtorClient: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
07-18 14:48:34.330  2290  2290 E o.j.s.a.c.KtorClient: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
07-18 14:48:34.330  2290  2290 E o.j.s.a.c.KtorClient: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
07-18 14:48:34.330  2290  2290 E o.j.s.a.c.KtorClient: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
07-18 14:48:34.334  2290  2290 E RecommendedServerDiscov: Could not retrieve public system info for http://192.168.1.203:8096
07-18 14:48:34.334  2290  2290 E RecommendedServerDiscov: java.lang.IllegalArgumentException: Unexpected char 0xa0 at 101 in Authorization value: MediaBrowser Client="Android TV", Version="0.0.0-dev.1", DeviceId="6dcd472cebc54050", Device="Android TV"
07-18 14:48:34.334  2290  2290 E RecommendedServerDiscov: 	at okhttp3.Headers$Companion.checkValue(Headers.kt:434)
07-18 14:48:34.334  2290  2290 E RecommendedServerDiscov: 	at okhttp3.Headers$Companion.access$checkValue(Headers.kt:346)
07-18 14:48:34.334  2290  2290 E RecommendedServerDiscov: 	at okhttp3.Headers$Builder.add(Headers.kt:245)
07-18 14:48:34.334  2290  2290 E RecommendedServerDiscov: 	at okhttp3.Request$Builder.addHeader(Request.kt:210)
07-18 14:48:34.334  2290  2290 E RecommendedServerDiscov: 	at io.ktor.client.engine.okhttp.OkHttpEngineKt$convertToOkHttpRequest$1$1.invoke(OkHttpEngine.kt:189)
07-18 14:48:34.334  2290  2290 E RecommendedServerDiscov: 	at io.ktor.client.engine.okhttp.OkHttpEngineKt$convertToOkHttpRequest$1$1.invoke(OkHttpEngine.kt:186)
07-18 14:48:34.334  2290  2290 E RecommendedServerDiscov: 	at io.ktor.client.engine.UtilsKt$mergeHeaders$2.invoke(Utils.kt:37)
07-18 14:48:34.334  2290  2290 E RecommendedServerDiscov: 	at io.ktor.client.engine.UtilsKt$mergeHeaders$2.invoke(Utils.kt:32)
07-18 14:48:34.334  2290  2290 E RecommendedServerDiscov: 	at io.ktor.util.StringValuesImpl.forEach(StringValues.kt:146)
07-18 14:48:34.334  2290  2290 E RecommendedServerDiscov: 	at io.ktor.client.engine.UtilsKt.mergeHeaders(Utils.kt:32)
07-18 14:48:34.334  2290  2290 E RecommendedServerDiscov: 	at io.ktor.client.engine.okhttp.OkHttpEngineKt.convertToOkHttpRequest(OkHttpEngine.kt:186)
07-18 14:48:34.334  2290  2290 E RecommendedServerDiscov: 	at io.ktor.client.engine.okhttp.OkHttpEngineKt.access$convertToOkHttpRequest(OkHttpEngine.kt:1)
07-18 14:48:34.334  2290  2290 E RecommendedServerDiscov: 	at io.ktor.client.engine.okhttp.OkHttpEngine.execute(OkHttpEngine.kt:72)
07-18 14:48:34.334  2290  2290 E RecommendedServerDiscov: 	at io.ktor.client.engine.HttpClientEngine$executeWithinCallContext$2.invokeSuspend(HttpClientEngine.kt:85)
07-18 14:48:34.334  2290  2290 E RecommendedServerDiscov: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07-18 14:48:34.334  2290  2290 E RecommendedServerDiscov: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
07-18 14:48:34.334  2290  2290 E RecommendedServerDiscov: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
07-18 14:48:34.334  2290  2290 E RecommendedServerDiscov: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
07-18 14:48:34.334  2290  2290 E RecommendedServerDiscov: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
07-18 14:48:34.334  2290  2290 E RecommendedServerDiscov: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
07-18 14:48:34.337  2290  2290 D ServerRepositoryImpl$addServer: Recommendations: 0 great, 0 good, 2 bad
07-18 14:48:34.583   304   456 W MapperHal: buffer descriptor with invalid usage bits 0x400
07-18 14:48:36.014  1669  1689 E TVNotifService: getConnectedInstanceBlockingWithTimeout - Exited on timeout
07-18 14:48:36.015  1669  1689 E TVNotifService.NotifMgr: Cannot get notification service while fetching tray notifications
07-18 14:48:37.181   633   739 E WifiVendorHal: getWifiLinkLayerStats(l.937) failed {.code = ERROR_NOT_AVAILABLE, .description = }
07-18 14:48:37.888   633  1524 W NotificationService: Toast already killed. pkg=org.jellyfin.androidtv.debug callback=android.app.ITransientNotification$Stub$Proxy@579236f
07-18 14:48:38.177  1800  3933 E WatchDog: 2021-07-18 14:48:38.177 1800:3933 E/WatchDog:   Hang detected for process: MainThread
```

**System (please complete the following information):**
 - Android TV Android 9
 - Device manufacturer: TCL (same error using a Mi Box 3)
 - Device model: BeyondTV2
 - Jellyfin server version: 10.7.6
 - Jellyfin client version: Tried 5 or 6 different nightlies from the last few weeks

**Comment by nielsvanvelzen** [comment]
What is the commit hash of the build you used?

**Comment by romainrbr** [comment]
Sorry for the false positive, I just downloaded and installed `a1e7eb7f63d07d4107ad5ade038afaf34edb95e8` (latest master commit) and it now works.

Thanks for the quick response and the work on this project !
