### ISSUE TITLE
FireTV media playback fails when connecting through IPv6

### ISSUE THREAD

**Issue by dkambersky** [jellyfin/jellyfin-androidtv#1027]
**Describe the bug**
When connecting to a Jellyfin server through its IPv6 address, the app loads fine into the 'library' view, but crashes when trying to play any file .

**To Reproduce**
1. Connect from a fireTV (likely any androidTV) app to a server through its ipv6 address
2. Log in, get into library, observe things working there
3. Attempt to open a file to watch it.
4. Observe it crashing.

**Expected behavior**
The app playing back the media without crashing.

**Logs**
(server address redacted)
```
[..]
2021-07-19 13:21:42.145 9425-9425/? D/Jellyfin-AndroidTV: Adding request to queue: http://[xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:8096/Users/<userhash>/Items/<itemhash>?format=json
[..]
2021-07-19 13:21:42.174 9425-9425/? D/Jellyfin-AndroidTV: Added event listener.  Total listeners: 3
[..]
2021-07-19 13:21:42.253 9425-9425/? I/Jellyfin-AndroidTV: Response received from: http://[xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:8096/Users/<userhash>/Items/<itemhash>?format=json
[..]
2021-07-19 13:21:42.313 9425-9790/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #7
    Process: org.jellyfin.androidtv, PID: 9425
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalArgumentException: unexpected host: xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx
        at com.squareup.okhttp.HttpUrl$Builder.host(HttpUrl.java:705)
        at com.squareup.okhttp.Address.<init>(Address.java:57)
        at com.squareup.okhttp.internal.http.HttpEngine.createAddress(HttpEngine.java:985)
        at com.squareup.okhttp.internal.http.HttpEngine.<init>(HttpEngine.java:182)
        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.newHttpEngine(HttpURLConnectionImpl.java:377)
        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.initHttpEngine(HttpURLConnectionImpl.java:324)
        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:392)
        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:527)
        at com.squareup.picasso.OkHttpDownloader.load(OkHttpDownloader.java:105)
        at com.squareup.picasso.NetworkBitmapHunter.decode(NetworkBitmapHunter.java:46)
        at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:144)
        at com.squareup.picasso.RequestCreator.get(RequestCreator.java:280)
        at org.jellyfin.androidtv.details.FullDetailsActivity$BuildDorTask.doInBackground(FullDetailsActivity.java:433)
        at org.jellyfin.androidtv.details.FullDetailsActivity$BuildDorTask.doInBackground(FullDetailsActivity.java:381)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2021-07-19 13:21:42.313 9425-9790/? E/ACRA: ACRA caught a RuntimeException for org.jellyfin.androidtv
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalArgumentException: unexpected host: xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx
        at com.squareup.okhttp.HttpUrl$Builder.host(HttpUrl.java:705)
        at com.squareup.okhttp.Address.<init>(Address.java:57)
        at com.squareup.okhttp.internal.http.HttpEngine.createAddress(HttpEngine.java:985)
        at com.squareup.okhttp.internal.http.HttpEngine.<init>(HttpEngine.java:182)
        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.newHttpEngine(HttpURLConnectionImpl.java:377)
        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.initHttpEngine(HttpURLConnectionImpl.java:324)
        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:392)
        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:527)
        at com.squareup.picasso.OkHttpDownloader.load(OkHttpDownloader.java:105)
        at com.squareup.picasso.NetworkBitmapHunter.decode(NetworkBitmapHunter.java:46)
        at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:144)
        at com.squareup.picasso.RequestCreator.get(RequestCreator.java:280)
        at org.jellyfin.androidtv.details.FullDetailsActivity$BuildDorTask.doInBackground(FullDetailsActivity.java:433)
        at org.jellyfin.androidtv.details.FullDetailsActivity$BuildDorTask.doInBackground(FullDetailsActivity.java:381)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)
```

**System (please complete the following information):**
 - Android TV or Fire TV version: Fire OS 7
 - Device manufacturer: JVC
 - Device model: JVC Fire TV
 - Jellyfin server version: 10.7.6

**Comment by dkambersky** [comment]
Can confirm playback works normally over ipv6 with the new beta release - v0.12.0-beta.2.
