### ISSUE TITLE
0.12.x beta 2: Significant stuttering/dropping frames playback of content after 15-30 minutes of play

### ISSUE THREAD

**Issue by Hukuma1** [jellyfin/jellyfin-androidtv#1035]
**Checks**
- [x] Issue does not happen in the browser (jellyfin-web)

**Media Info of the file**
```
Video
Title1080p HEVC SDR
CodecHEVC
Codec taghev1
ProfileMain 10
Level120
Resolution1914x816
Aspect ratio2.35:1
InterlacedNo
Framerate23.976215
Bitrate1999 kbps
Video rangeSDR
Pixel formatyuv420p10le
Ref frames1
```
```
Audio
TitleEnglish - AAC - 5.1 - Default
Languageeng
CodecAAC
Codec tagmp4a
ProfileLC
Layout5.1
Channels6 ch
Bitrate224 kbps
Sample rate48000 Hz
DefaultYes
```

**Logs**
```
[2021-07-24 22:15:09.665 -07:00] [INF] [112] Jellyfin.Api.Controllers.MediaInfoController: GetPostedPlaybackInfo profile: DeviceProfile { Name: "AndroidTV-libVLC", Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 20000000, MaxStaticBitrate: 100000000, MusicStreamingTranscodingBitrate: 128000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "m4v,3gp,ts,mpegts,mov,xvid,vob,mkv,wmv,asf,ogm,ogv,m2v,mpg,mpeg,mp4,webm,wtv", AudioCodec: "aac,mp3,mp2,ac3,wma,wmav2,dca,dts,pcm,PCM_S16LE,PCM_S24LE,opus,flac,truehd", VideoCodec: null, Type: Video }, DirectPlayProfile { Container: "flac,aac,mp3,mpa,wav,wma,mp2,ogg,oga,webma,ape", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "jpg,jpeg,png,gif,webp", AudioCodec: null, VideoCodec: null, Type: Photo }], TranscodingProfiles: [TranscodingProfile { Container: "mkv", Type: Video, VideoCodec: "h264", AudioCodec: "aac,mp3", Protocol: null, EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: True, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: null, EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: VideoProfile, Value: "none", IsRequired: False }], ApplyConditions: [], Codec: "hevc", Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "high|main|baseline|constrained baseline", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "51", IsRequired: False }], ApplyConditions: [], Codec: "h264", Container: null }, CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: LessThanEqual, Property: AudioChannels, Value: "8", IsRequired: False }], ApplyConditions: [], Codec: null, Container: null }], ResponseProfiles: [], SubtitleProfiles: [SubtitleProfile { Format: "srt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "srt", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "subrip", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgs", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pbssub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "dvdsub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "vtt", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "sub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "smi", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "idx", Method: Embed, DidlMode: null, Language: null, Container: null }] }
[2021-07-24 22:15:09.668 -07:00] [INF] [112] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "jellyfin". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2021-07-24 22:15:09.668 -07:00] [INF] [112] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "AndroidTV-libVLC", Path: "/data/movies/Media/Movies/MOVIENAME/MOVIENAME.mp4", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-07-24 22:15:09.668 -07:00] [INF] [112] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "AndroidTV-libVLC", Path: "/data/movies/Media/Movies/MOVIENAME/MOVIENAME.mp4", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-07-24 22:15:09.668 -07:00] [INF] [112] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "AndroidTV-libVLC", Path: "/data/movies/Media/Movies/MOVIENAME/MOVIENAME.mp4", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-07-24 22:15:09.700 -07:00] [INF] [112] Jellyfin.Api.Controllers.MediaInfoController: GetPostedPlaybackInfo profile: DeviceProfile { Name: "AndroidTV-ExoPlayer", Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 20000000, MaxStaticBitrate: 100000000, MusicStreamingTranscodingBitrate: 128000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "m4v,mov,xvid,vob,mkv,wmv,asf,ogm,ogv,mp4,webm", AudioCodec: "aac,ac3,eac3,aac_latm,mp3,mp2,dca,dts", VideoCodec: "h264,hevc,vp8,vp9,mpeg,mpeg2video", Type: Video }, DirectPlayProfile { Container: "aac,mp3,mpa,flac,wav,wma,mp2,ogg,oga,webma,ape,opus", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "jpg,jpeg,png,gif,webp", AudioCodec: null, VideoCodec: null, Type: Photo }], TranscodingProfiles: [TranscodingProfile { Container: "mkv", Type: Video, VideoCodec: "h264", AudioCodec: "ac3,aac,mp3", Protocol: null, EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: True, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: null, EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "high|main|baseline|constrained baseline", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "51", IsRequired: False }], ApplyConditions: [], Codec: "h264", Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: LessThanEqual, Property: RefFrames, Value: "12", IsRequired: False }], ApplyConditions: [ProfileCondition { Condition: GreaterThanEqual, Property: Width, Value: "1200", IsRequired: False }], Codec: "h264", Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: LessThanEqual, Property: RefFrames, Value: "4", IsRequired: False }], ApplyConditions: [ProfileCondition { Condition: GreaterThanEqual, Property: Width, Value: "1900", IsRequired: False }], Codec: "h264", Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: VideoProfile, Value: "none", IsRequired: False }], ApplyConditions: [], Codec: "hevc", Container: null }, CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: LessThanEqual, Property: AudioChannels, Value: "6", IsRequired: False }], ApplyConditions: [], Codec: null, Container: null }], ResponseProfiles: [], SubtitleProfiles: [SubtitleProfile { Format: "srt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "srt", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "subrip", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: Encode, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: Encode, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgs", Method: Encode, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pbssub", Method: Encode, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "dvdsub", Method: Encode, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "vtt", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "sub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "idx", Method: Embed, DidlMode: null, Language: null, Container: null }] }
[2021-07-24 22:15:09.703 -07:00] [INF] [112] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "jellyfin". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2021-07-24 22:15:09.703 -07:00] [INF] [112] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "AndroidTV-ExoPlayer", Path: "/data/movies/Media/Movies/MOVIENAME/MOVIENAME.mp4", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-07-24 22:15:09.703 -07:00] [INF] [112] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "AndroidTV-ExoPlayer", Path: "/data/movies/Media/Movies/MOVIENAME/MOVIENAME.mp4", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-07-24 22:15:09.703 -07:00] [INF] [112] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "AndroidTV-ExoPlayer", Path: "/data/movies/Media/Movies/MOVIENAME/MOVIENAME.mp4", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-07-24 22:52:32.113 -07:00] [INF] [56] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Android TV" "0.12.0-beta.2" playing "MOVIENAME". Stopped at "2177401" ms
[2021-07-24 22:52:35.959 -07:00] [ERR] [52] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Users/3e375b4b7cd349f48d123316ff3c9346/Images/Primary".
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Api.Controllers.ImageController.GetUserImage(Guid userId, ImageType imageType, String tag, Nullable`1 format, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 percentPlayed, Nullable`1 unplayedCount, Nullable`1 width, Nullable`1 height, Nullable`1 quality, Nullable`1 fillWidth, Nullable`1 fillHeight, Nullable`1 cropWhitespace, Nullable`1 addPlayedIndicator, Nullable`1 blur, String backgroundColor, String foregroundLayer, Nullable`1 imageIndex)
   at lambda_method1156(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**FFmpeg Logs**

**System (please complete the following information):**
 - Android TV or Fire TV version: [e.g. Android 9 or Fire OS 7]: Android 9
 - Device manufacturer: [e.g. Amazon, Nvidia, Sony] Nvidia
 - Device model: [e.g. Fire TV Stick (2nd Gen) or Shield TV]: Shield TV 2019
 - Jellyfin server version: [e.g. 10.5.4]: 10.7.6

**Additional context**
Does not exhibit this behavior with current app in playstore. (non beta). When it first happened I thought it was a 4K file issue, so I tried a very modest 1080p file and it still does the same. It's as if it runs out of memory and just starts chunking and dropping frames. The only workaround so far is to exit the movie and resume playback.

**Comment by Tezzlicious** [comment]
On my Shield TV it even goes further and crashes jellyfin after a while.

So the playback starts fine and several minutes into the video stuttering of both audio and video starts causing the whole player/app to crash after a while and display the pop-up it crashed. The app seems to restart itself after this.

It seems to happen for every file/sound format.

**Comment by nielsvanvelzen** [comment]
Is the video transcoding?

**Comment by Hukuma1** [comment]
Does not seem to be. I have no FFMPeg transcode logs for that title from above.

Could it be a memory leak? It seems too precise. Last night happened in 15 minute intervals.

**Comment by nielsvanvelzen** [comment]
Does the issue still happen if you change the "preferred media player" to ExoPlayer or LibVLC?

> Could it be a memory leak? It seems too precise. Last night happened in 15 minute intervals.

This could be possible, the code for video playback is not great.

**Comment by Hukuma1** [comment]
So it seems to be doing the skipping when using `LibVLC` for me. I tried the same exact clip using `ExoPlayer` it seemed to go fine. Can the other person with this issue confirm this as well?

I will try some giant 4K 50gb files and see if Exoplayer has any further issues next.

Is the "auto selection" random by any chance? Is it sometimes choosing exo vs libvlc? Or always will choose libvlc on Shield?

**Comment by nielsvanvelzen** [comment]
It _should_ make some smart choices although in my experience it never worked properly so I always use ExoPlayer.

**Comment by Hukuma1** [comment]
Alright, I see how it goes. So 4K giant remux media will not play in Exo. I believe it tries to transcode audio? It will error out. So I'm guessing the auto in this case will flip to libvlc and it will work. However, with libvlc 4K remux I experience some weird audio issues. In one instance the sync is off. In another video it has a weird boosted treble effect to the voices? Not sure if the picture stuttering happens as well as it does with the 1080p content from above.

Audio plays back just fine in the same files using Kodi (this means equipment is capable I guess)?

**Comment by nielsvanvelzen** [comment]
The shield is one of the most powerful android devices and should support pretty much all modern video/audio codecs. So yes your equipment is capable, it's just that the app doesn't handle it properly. Fixing the playback of audio and video is in the roadmap but I don't expect much is going to happen for 0.12.

**Comment by Hukuma1** [comment]
Is there a link to the road map? What could be higher priority than fixing video/audio playback? :O Do I mark this issue as closed then?

**Comment by nielsvanvelzen** [comment]
Small fixes to the current playback code may be includes but the code for playback is really messy and requires a lot of work to get fixed. A lot of work in 0.12 was to prepare for a rewrite of the playback code in a future update. This issue will stay open until we have it fixed so we can keep track of it.

**Comment by Hukuma1** [comment]
Gotcha. Okay, well if you need further logs or anything else to test in specific scenarios please let me know. Use Jellyfin as a daily driver so really want to get it fixed for all others to enjoy as well.

**Comment by Tezzlicious** [comment]
Selecting the player seems to make a difference. Both ExoPlayer as libVLC play the same file without stuttering.

**Comment by krutburken** [comment]
I have this problem when Audio downmixing is enabled in the app (both the beta and v0.11.5 behaves the same). If you have a file with a supported audio stream, use Direct, and force ExoPlayer, the crashing goes away. This is with 1080p media (I have no 4k media to test with)

This is the issue that has made me exclusively use Kodi instead of the ATV-app. Shame it's still there on the upcoming version

**Comment by jvoinot** [comment]
Hello,

I have the same problem (and traceback).
Not all videos are impacted.

I will try to upgrade the RAM on my NAS, i think it could be associated. I will keep you inform.

Best regards,

**Comment by jvoinot** [comment]
RAM upgrade didn't solved my issue.

Today i tried to configure an image into my profile because the traceback talk about [Jellyfin.Api.Controllers.ImageController.GetUserImage()](https://github.com/jellyfin/jellyfin/blob/b64d9bcd401d68e12b7e0ef2e2fdb55b895e211a/Jellyfin.Api/Controllers/ImageController.cs#L1524)

I didn't have any issue tonight.

**Comment by lyonelz96** [comment]
Similar thing has been happening to me when watching movies. It'll be fine for 80% of the movie and then it'll start being a bit stuttery and the movie won't look smooth anymore. It's barely there but noticeable. Exiting the movie and resuming it fixes this. This does seem to happen consistently as long as the media lasts long enough for it to happen.

On rare occasions this is accompanied by the audio cutting off/stutter. Sometimes it's just the audio stutter.

Since the fix is to simply exit and resume it's not the BIGGEST of deals, but I definitely would like to enjoy a movie night without that interruption haha. Looking forward for the player rewrite to be complete, it'll hopefully fix these weird issues.

**Comment by avionics75** [comment]
I'm having the same issue with the lastest 0.16.0 and 0.16.1 update and Live TV.
Since the MPEG layer has been removed, I'm not able to play live TV on direct play, it is always playing using remux, causing frame and audio drops after few minutes. Most of the time I end up with "an error on the player occured" after few minutes. I can't enjoy live TV like before anymore :(

**Comment by kingp0dd** [comment]
I thought I was the only one. Been experiencing this stuttering after playing a file for a few minutes. It's not heavy stutters but it's there and noticable, very noticable on long camera spans.

**Comment by energywave** [comment]
I can confirm the issue is still there, on FireTV 4K Max ethernet connected. All movies starts good but after some time (around 30 minutes but could vary) it begins to stutters and frame rate drops. I've never tried to continue as it becomes really bad to see. I generally exit from the app and reeneter but reading here maybe restarting could be enough (I'll try that).
I'm using Exoplayer as I've found LibVLC not so reliable on some files, Exoplayer seems more consistent (but maybe I'll do some tests).
I notices with certain files that changing audio/video sync msec can cause the stutters to begin, sorry to not have scientific data but only guesses.
However, in my opinion, this should be the main focus to improve, it's bad for usability. It's "good" as long as I'm using it. But I wanted to install on my daughter TV and me wife should use it alone too... I'll be in danger then :D

**Comment by henriklb** [comment]
I have similar problems with stuttering on my 2019 shield tube. Can’t really use this app due to this unfortunately
