### ISSUE TITLE
FireTV Sleep causing issues with Account Logins

### ISSUE THREAD

**Issue by ACR-Jeff** [jellyfin/jellyfin-androidtv#1141]
**Describe the bug**
After FireTV sleeps and wakes I can no longer login to any user account in Jellyfin, Clicking on an account on the login screen under "Who's watching" and entering the password, Clicking the "OK" button does nothing. I have to go in the jellyfin dashboard and delete the user account and start over with a fresh user account (with a totally different name). Happens with an account with auto login enabled also, An auto login account stops auto logging in and will not login even using the password. If I try to use a previous account user name in a new account that has previously already had this issue it will not login, I have to use a totally new user name in the newly created account. Also I can close jellyfin and open it again, And noticed user accounts are stuck on the login screen "Who's watching?" section even after they have been deleted in the Dashboard. The only way to clear the previously deleted accounts is by forcefully shutting down jellyfin client and clearing cache and data in Firetv app settings.

I hope the information I provided and logs below help. I tried to gather as much information as possible that maybe of some help in this case. If any other logs are needed I will be glad to provide.

**To Reproduce**

1. Allow FireTV to sleep and wake up
2. Start jellyfin
3. Select User
4. Enter User Password
4. Clicking "OK" button to Login
5. Nothing happens when clicking "OK"

**Expected behavior**

Start jellyfin client, Select user account and login to home screen or have it auto login to home screen

**Logs**

[2021-09-09 12:09:42.939 -07:00] [FTL] Error while starting server.
Full: SQLitePCL.pretty.SQLiteException: database or disk is full
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.GetConnection(Boolean _)
   at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize(SqliteUserDataRepository userDataRepo, IUserManager userManager)
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2021-09-09 12:09:42.950 -07:00] [INF] Disposing "CoreAppHost"
[2021-09-09 12:09:42.951 -07:00] [INF] Received a SIGTERM signal, shutting down
[2021-09-09 12:09:43.635 -07:00] [INF] Jellyfin version: "10.7.7"
[2021-09-09 12:09:43.659 -07:00] [INF] Environment Variables: ["[JELLYFIN_LOG_DIR, /var/log/jellyfin]", "[JELLYFIN_DATA_DIR, /var/lib/jellyfin]", "[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]", "[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin/web]", "[JELLYFIN_USER, jellyfin]", "[JELLYFIN_RESTART_OPT, --restartpath=/usr/lib/jellyfin/restart.sh]", "[JELLYFIN_FFMPEG_OPT, --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_ARGS, $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]"]
[2021-09-09 12:09:43.662 -07:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", ""]
[2021-09-09 12:09:43.663 -07:00] [INF] Operating system: "Linux"
[2021-09-09 12:09:43.663 -07:00] [INF] Architecture: X64
[2021-09-09 12:09:43.664 -07:00] [INF] 64-Bit Process: True
[2021-09-09 12:09:43.664 -07:00] [INF] User Interactive: True
[2021-09-09 12:09:43.664 -07:00] [INF] Processor count: 4
[2021-09-09 12:09:43.664 -07:00] [INF] Program data path: "/var/lib/jellyfin"
[2021-09-09 12:09:43.664 -07:00] [INF] Web resources path: "/usr/share/jellyfin/web"
[2021-09-09 12:09:43.664 -07:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2021-09-09 12:09:43.842 -07:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2021-09-09 12:09:43.878 -07:00] [ERR] No interfaces information available. Resolving DNS name.
[2021-09-09 12:09:43.893 -07:00] [INF] Defined LAN addresses : "[192.168.1.1/24,127.0.0.1/8]"
[2021-09-09 12:09:43.893 -07:00] [INF] Defined LAN exclusions : "[]"
[2021-09-09 12:09:43.894 -07:00] [INF] Using LAN addresses: "[192.168.1.0/24,127.0.0.1/8]"
[2021-09-09 12:09:43.899 -07:00] [INF] Using bind addresses: "[]"
[2021-09-09 12:09:43.899 -07:00] [INF] Using bind exclusions: "[]"
[2021-09-09 12:09:43.916 -07:00] [INF] Loading assemblies
[2021-09-09 12:09:45.682 -07:00] [FTL] Error while starting server.
Full: SQLitePCL.pretty.SQLiteException: database or disk is full
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.GetConnection(Boolean _)
   at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize(SqliteUserDataRepository userDataRepo, IUserManager userManager)
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2021-09-09 12:09:45.688 -07:00] [INF] Disposing "CoreAppHost"
[2021-09-09 12:09:46.267 -07:00] [INF] Jellyfin version: "10.7.7"
[2021-09-09 12:09:46.290 -07:00] [INF] Environment Variables: ["[JELLYFIN_FFMPEG_OPT, --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_ARGS, $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT]", "[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]", "[JELLYFIN_RESTART_OPT, --restartpath=/usr/lib/jellyfin/restart.sh]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]", "[JELLYFIN_USER, jellyfin]", "[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin/web]", "[JELLYFIN_DATA_DIR, /var/lib/jellyfin]", "[JELLYFIN_LOG_DIR, /var/log/jellyfin]"]
[2021-09-09 12:09:46.292 -07:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", ""]
[2021-09-09 12:09:46.293 -07:00] [INF] Operating system: "Linux"
[2021-09-09 12:09:46.293 -07:00] [INF] Architecture: X64
[2021-09-09 12:09:46.294 -07:00] [INF] 64-Bit Process: True
[2021-09-09 12:09:46.294 -07:00] [INF] User Interactive: True
[2021-09-09 12:09:46.294 -07:00] [INF] Processor count: 4
[2021-09-09 12:09:46.294 -07:00] [INF] Program data path: "/var/lib/jellyfin"
[2021-09-09 12:09:46.294 -07:00] [INF] Web resources path: "/usr/share/jellyfin/web"
[2021-09-09 12:09:46.294 -07:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2021-09-09 12:09:46.486 -07:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2021-09-09 12:09:46.534 -07:00] [INF] Defined LAN addresses : "[192.168.1.1/24,127.0.0.1/8]"
[2021-09-09 12:09:46.534 -07:00] [INF] Defined LAN exclusions : "[]"
[2021-09-09 12:09:46.535 -07:00] [INF] Using LAN addresses: "[192.168.1.0/24,127.0.0.1/8]"
[2021-09-09 12:09:46.539 -07:00] [INF] Using bind addresses: "[]"
[2021-09-09 12:09:46.539 -07:00] [INF] Using bind exclusions: "[]"
[2021-09-09 12:09:46.558 -07:00] [INF] Loading assemblies
[2021-09-09 12:09:48.298 -07:00] [FTL] Error while starting server.
Full: SQLitePCL.pretty.SQLiteException: database or disk is full
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.GetConnection(Boolean _)
   at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize(SqliteUserDataRepository userDataRepo, IUserManager userManager)
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2021-09-09 12:09:48.304 -07:00] [INF] Disposing "CoreAppHost"
[2021-09-09 12:09:48.305 -07:00] [INF] Received a SIGTERM signal, shutting down
[2021-09-09 12:09:48.860 -07:00] [INF] Jellyfin version: "10.7.7"
[2021-09-09 12:09:48.882 -07:00] [INF] Environment Variables: ["[JELLYFIN_USER, jellyfin]", "[JELLYFIN_ARGS, $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT]", "[JELLYFIN_DATA_DIR, /var/lib/jellyfin]", "[JELLYFIN_FFMPEG_OPT, --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_RESTART_OPT, --restartpath=/usr/lib/jellyfin/restart.sh]", "[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin/web]", "[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]", "[JELLYFIN_LOG_DIR, /var/log/jellyfin]"]
[2021-09-09 12:09:48.885 -07:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", ""]
[2021-09-09 12:09:48.886 -07:00] [INF] Operating system: "Linux"
[2021-09-09 12:09:48.886 -07:00] [INF] Architecture: X64
[2021-09-09 12:09:48.887 -07:00] [INF] 64-Bit Process: True
[2021-09-09 12:09:48.887 -07:00] [INF] User Interactive: True
[2021-09-09 12:09:48.887 -07:00] [INF] Processor count: 4
[2021-09-09 12:09:48.887 -07:00] [INF] Program data path: "/var/lib/jellyfin"
[2021-09-09 12:09:48.887 -07:00] [INF] Web resources path: "/usr/share/jellyfin/web"
[2021-09-09 12:09:48.887 -07:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2021-09-09 12:09:49.087 -07:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2021-09-09 12:09:49.133 -07:00] [INF] Defined LAN addresses : "[192.168.1.1/24,127.0.0.1/8]"
[2021-09-09 12:09:49.133 -07:00] [INF] Defined LAN exclusions : "[]"
[2021-09-09 12:09:49.134 -07:00] [INF] Using LAN addresses: "[192.168.1.0/24,127.0.0.1/8]"
[2021-09-09 12:09:49.139 -07:00] [INF] Using bind addresses: "[]"
[2021-09-09 12:09:49.139 -07:00] [INF] Using bind exclusions: "[]"
[2021-09-09 12:09:49.157 -07:00] [INF] Loading assemblies
[2021-09-09 12:09:50.821 -07:00] [FTL] Error while starting server.

[2021-09-09 02:52:31.679 -07:00] [ERR] Error in "ffprobe"
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeAudioInfo.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)

[2021-09-09 21:07:27.189 -07:00] [INF] Authentication request for "ACR-Jeff" has succeeded.
[2021-09-09 21:07:27.189 -07:00] [INF] Current/Max sessions for user "ACR-Jeff": 1/0
[2021-09-09 21:07:27.189 -07:00] [INF] Reissuing access token: "d38ea7a854c54aa38f372466bd2c8ece"
[2021-09-09 21:07:28.422 -07:00] [INF] Authentication request for "ACR-Jeff" has succeeded.
[2021-09-09 21:07:28.422 -07:00] [INF] Current/Max sessions for user "ACR-Jeff": 1/0
[2021-09-09 21:07:28.423 -07:00] [INF] Reissuing access token: "d38ea7a854c54aa38f372466bd2c8ece"
[2021-09-09 21:07:29.356 -07:00] [INF] Authentication request for "ACR-Jeff" has succeeded.
[2021-09-09 21:07:29.356 -07:00] [INF] Current/Max sessions for user "ACR-Jeff": 1/0
[2021-09-09 21:07:29.356 -07:00] [INF] Reissuing access token: "d38ea7a854c54aa38f372466bd2c8ece"
[2021-09-09 21:07:30.104 -07:00] [INF] Authentication request for "ACR-Jeff" has succeeded.
[2021-09-09 21:07:30.104 -07:00] [INF] Current/Max sessions for user "ACR-Jeff": 1/0
[2021-09-09 21:07:30.105 -07:00] [INF] Reissuing access token: "d38ea7a854c54aa38f372466bd2c8ece"
[2021-09-09 21:14:25.021 -07:00] [INF] Logging out access token "d38ea7a854c54aa38f372466bd2c8ece"
[2021-09-09 21:17:35.090 -07:00] [ERR] Invalid ViewType: ""
[2021-09-09 21:17:35.090 -07:00] [ERR] Invalid ViewType: ""
[2021-09-09 21:18:19.494 -07:00] [INF] Authentication request for "Jeff" has succeeded.
[2021-09-09 21:18:19.494 -07:00] [INF] Current/Max sessions for user "Jeff": 0/0
[2021-09-09 21:18:19.495 -07:00] [INF] Creating new access token for user 42fab53a-754a-4a21-8217-e975d016ef07
[2021-09-09 21:18:24.655 -07:00] [INF] Authentication request for "Jeff" has succeeded.
[2021-09-09 21:18:24.655 -07:00] [INF] Current/Max sessions for user "Jeff": 1/0
[2021-09-09 21:18:24.655 -07:00] [INF] Reissuing access token: "2e23945590314711819af2e54dd18ff9"
[2021-09-09 21:18:25.514 -07:00] [INF] Authentication request for "Jeff" has succeeded.
[2021-09-09 21:18:25.514 -07:00] [INF] Current/Max sessions for user "Jeff": 1/0
[2021-09-09 21:18:25.514 -07:00] [INF] Reissuing access token: "2e23945590314711819af2e54dd18ff9"
[2021-09-09 21:18:26.222 -07:00] [INF] Authentication request for "Jeff" has succeeded.
[2021-09-09 21:18:26.222 -07:00] [INF] Current/Max sessions for user "Jeff": 1/0
[2021-09-09 21:18:26.223 -07:00] [INF] Reissuing access token: "2e23945590314711819af2e54dd18ff9"
[2021-09-09 21:18:53.007 -07:00] [INF] Authentication request for "Jeff" has succeeded.
[2021-09-09 21:18:53.007 -07:00] [INF] Current/Max sessions for user "Jeff": 1/0
[2021-09-09 21:18:53.008 -07:00] [INF] Reissuing access token: "2e23945590314711819af2e54dd18ff9"
[2021-09-09 21:19:20.631 -07:00] [INF] Authentication request for "Jeff" has succeeded.
[2021-09-09 21:19:20.632 -07:00] [INF] Current/Max sessions for user "Jeff": 1/0
[2021-09-09 21:19:20.632 -07:00] [INF] Reissuing access token: "2e23945590314711819af2e54dd18ff9"
[2021-09-09 21:19:57.362 -07:00] [INF] Authentication request for "Jeff" has succeeded.
[2021-09-09 21:19:57.362 -07:00] [INF] Current/Max sessions for user "Jeff": 1/0
[2021-09-09 21:19:57.363 -07:00] [INF] Reissuing access token: "2e23945590314711819af2e54dd18ff9"
[2021-09-09 21:27:40.194 -07:00] [INF] Authentication request for "Jeff" has succeeded.
[2021-09-09 21:27:40.194 -07:00] [INF] Current/Max sessions for user "Jeff": 1/0
[2021-09-09 21:27:40.194 -07:00] [INF] Reissuing access token: "2e23945590314711819af2e54dd18ff9"
[2021-09-09 21:34:45.680 -07:00] [INF] Logging out access token "2e23945590314711819af2e54dd18ff9"
[2021-09-09 21:41:09.108 -07:00] [ERR] Invalid ViewType: ""
[2021-09-09 21:41:09.108 -07:00] [ERR] Invalid ViewType: ""
[2021-09-09 21:41:43.967 -07:00] [INF] Authentication request for "JeffF" has succeeded.
[2021-09-09 21:41:43.967 -07:00] [INF] Current/Max sessions for user "JeffF": 0/0
[2021-09-09 21:41:43.967 -07:00] [INF] Creating new access token for user fab2f138-9644-4aee-b4c6-69a48174a062
[2021-09-09 21:41:44.359 -07:00] [INF] WS "192.168.1.254" request

**Screenshots**

**System (please complete the following information):**
 - Fire TV with Fire OS 6.2.8.1
 - Device manufacturer: Amazon
 - Device model: Fire TV Pendant (3nd Gen)
 - Jellyfin android tv client version: v0.12.0-beta.6
 - Jellyfin server version: 10.7.7-1

**Additional context**

**Comment by nielsvanvelzen** [comment]
```
[2021-09-09 12:09:42.939 -07:00] [FTL] Error while starting server.
Full: SQLitePCL.pretty.SQLiteException: database or disk is full
```
The logins might fail because your server's storage is full,

**Comment by ACR-Jeff** [comment]
> ```
> [2021-09-09 12:09:42.939 -07:00] [FTL] Error while starting server.
> Full: SQLitePCL.pretty.SQLiteException: database or disk is full
> ```
> 
> The logins might fail because your server's storage is full,

I notice the error logs state that. Yet I have checked my server storage and it's no where near full. 
![Server Storage](https://user-images.githubusercontent.com/61212551/132815601-30aaa8a2-dc1d-4f44-aa03-7265524cce77.png)

**Comment by ACR-Jeff** [comment]
Ok I looked deeper into this and I am going to try to solve that error. I did some searching, It lead me to look at the dashboard on the server, It defaulted to my root drive for transcoding. I now changed that path to a more suitable partition with more space. Per this thread [https://github.com/jellyfin/jellyfin/issues/5665](url)
