### ISSUE TITLE
Sorted by Unknown is the default sorting

### ISSUE THREAD

**Issue by nathandorsey** [jellyfin/jellyfin-androidtv#1214]
### Describe the bug

1. Go to a video library (Movies, Television)
2. Observe message at the bottom left stating, "Showing all items from 'Movies' sorted by Unknown".
3. You can still change the sorting through the -AZ- button but if you go back to the home screen and then visit the library again, it is just back to 'sorted by Unknown'.

I would expect the Movies and TV Shows to be sorted by Name by default.

I have two Nvidia Shields and they are both affected now. This began happening a couple days ago. Both units previously always sorted by Name.  I actually cannot even decipher which method of sorting is used by looking at this list. My list of Movies/Shows displayed appears to be very random. Music is also affected at least under Artists and Albums.

I have cleared the cache/data of the Jellyfin Android TV app to no avail.

### Application version

0.12.1

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield

### Android version

Android 9

### Jellyfin server version

10.7.7

**Comment by nielsvanvelzen** [comment]
Please provide app logs so we can help out

**Comment by nathandorsey** [comment]
I've attached a log from a fresh start and then me selecting the Movies library, pressing back, and then selecting the Television library. So I want to say the relevant pieces are near the end (shown in the block).

```
11-04 12:18:52.617 15554 15554 D jellyfin-apiclient: Adding request to queue: http://192.168.24.170:8096/DisplayPreferences/f137a2dd21bbc1b99aa5c0f6bf02a805?client=ATV&userId=69bc4d6f1c354adbb1962b0fb1f83b8d&format=json
11-04 12:18:52.665 15554 15590 E Volley  : [15134] NetworkUtility.shouldRetryException: Unexpected response code 500 for http://192.168.24.170:8096/DisplayPreferences/f137a2dd21bbc1b99aa5c0f6bf02a805?client=ATV&userId=69bc4d6f1c354adbb1962b0fb1f83b8d&format=json
11-04 12:18:52.665 15554 15554 E jellyfin-apiclient: VolleyError com.android.volley.ServerError: null
11-04 12:18:52.665 15554 15554 E jellyfin-apiclient: com.android.volley.ServerError
11-04 12:18:52.665 15554 15554 E jellyfin-apiclient: 	at com.android.volley.toolbox.NetworkUtility.shouldRetryException(NetworkUtility.java:201)
11-04 12:18:52.665 15554 15554 E jellyfin-apiclient: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:145)
11-04 12:18:52.665 15554 15554 E jellyfin-apiclient: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
11-04 12:18:52.665 15554 15554 E jellyfin-apiclient: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
11-04 12:18:52.665 15554 15554 E jellyfin-apiclient: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
11-04 12:18:52.666 15554 15554 E TvApp   : Unable to load display prefs 
11-04 12:18:52.666 15554 15554 E TvApp   : org.jellyfin.apiclient.model.net.HttpException: VolleyError com.android.volley.ServerError: 
11-04 12:18:52.666 15554 15554 E TvApp   : 	at org.jellyfin.apiclient.interaction.VolleyErrorListener.onErrorResponse(VolleyErrorListener.java:25)
11-04 12:18:52.666 15554 15554 E TvApp   : 	at com.android.volley.Request.deliverError(Request.java:648)
11-04 12:18:52.666 15554 15554 E TvApp   : 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:104)
11-04 12:18:52.666 15554 15554 E TvApp   : 	at android.os.Handler.handleCallback(Handler.java:873)
11-04 12:18:52.666 15554 15554 E TvApp   : 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-04 12:18:52.666 15554 15554 E TvApp   : 	at android.os.Looper.loop(Looper.java:193)
11-04 12:18:52.666 15554 15554 E TvApp   : 	at android.app.ActivityThread.main(ActivityThread.java:6721)
11-04 12:18:52.666 15554 15554 E TvApp   : 	at java.lang.reflect.Method.invoke(Native Method)
11-04 12:18:52.666 15554 15554 E TvApp   : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
11-04 12:18:52.666 15554 15554 E TvApp   : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
11-04 12:18:52.666 15554 15554 E TvApp   : Caused by: com.android.volley.ServerError
11-04 12:18:52.666 15554 15554 E TvApp   : 	at com.android.volley.toolbox.NetworkUtility.shouldRetryException(NetworkUtility.java:201)
11-04 12:18:52.666 15554 15554 E TvApp   : 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:145)
11-04 12:18:52.666 15554 15554 E TvApp   : 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
11-04 12:18:52.666 15554 15554 E TvApp   : 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
11-04 12:18:52.666 15554 15554 E TvApp   : 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
11-04 12:18:52.666 15554 15554 D ItemLauncher: **** Collection type: movies
11-04 12:18:52.666 15554 15554 D ItemLauncher: **** View Type Pref: null
11-04 12:18:52.696 15554 15554 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@12e70b2
```

[logcat_output.log](https://github.com/jellyfin/jellyfin-androidtv/files/7476470/logcat_output.log)

**Comment by nielsvanvelzen** [comment]
The "Unexpected response code 500 for" part indicates an issue in the server.

**Comment by nathandorsey** [comment]
Thank you. There was something weird with the server portion. I just restored from a previous snapshot and started the Jellyfin server again. I don't really care about the data in there. It did resolve my sorting issue that I was seeing in the Shield clients (weirdly I didn't notice the problem in other clients or web though).

If anyone comes across this later, below is the output that occurred on the server when I clicked 'Movies' from the Android App.

```
Nov 04 14:34:08 tuxbox docker[19422]:    at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
Nov 04 14:34:25 tuxbox docker[19422]: [14:34:25] [ERR] [129] Microsoft.EntityFrameworkCore.Database.Command: Failed executing DbCommand (0ms) [Parameters=[@p0='?' (Size = 3), @p1='?', @p2='?' (Size = 13), @p3='?', @p4='?' (Size = 5)], CommandType='Text', CommandTimeout='30']
Nov 04 14:34:25 tuxbox docker[19422]: INSERT INTO "CustomItemDisplayPreferences" ("Client", "ItemId", "Key", "UserId", "Value")
Nov 04 14:34:25 tuxbox docker[19422]: VALUES (@p0, @p1, @p2, @p3, @p4);
Nov 04 14:34:25 tuxbox docker[19422]: SELECT "Id"
Nov 04 14:34:25 tuxbox docker[19422]: FROM "CustomItemDisplayPreferences"
Nov 04 14:34:25 tuxbox docker[19422]: WHERE changes() = 1 AND "rowid" = last_insert_rowid();
Nov 04 14:34:25 tuxbox docker[19422]: [14:34:25] [ERR] [129] Microsoft.EntityFrameworkCore.Update: An exception occurred in the database while saving changes for context type 'Jellyfin.Server.Implementations.JellyfinDb'.
Nov 04 14:34:25 tuxbox docker[19422]: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
Nov 04 14:34:25 tuxbox docker[19422]:  ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: CustomItemDisplayPreferences.UserId, CustomItemDisplayPreferences.ItemId, CustomItemDisplayPreferences.Client, CustomItemDisplayPreferences.Key'.
Nov 04 14:34:25 tuxbox docker[19422]:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
Nov 04 14:34:25 tuxbox docker[19422]:    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
Nov 04 14:34:25 tuxbox docker[19422]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
Nov 04 14:34:25 tuxbox docker[19422]:    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
Nov 04 14:34:25 tuxbox docker[19422]:    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
Nov 04 14:34:25 tuxbox docker[19422]:    --- End of inner exception stack trace ---
Nov 04 14:34:25 tuxbox docker[19422]:    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
Nov 04 14:34:25 tuxbox docker[19422]:    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
Nov 04 14:34:25 tuxbox docker[19422]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
Nov 04 14:34:25 tuxbox docker[19422]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
Nov 04 14:34:25 tuxbox docker[19422]:    at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nov 04 14:34:25 tuxbox docker[19422]: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
Nov 04 14:34:25 tuxbox docker[19422]:  ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: CustomItemDisplayPreferences.UserId, CustomItemDisplayPreferences.ItemId, CustomItemDisplayPreferences.Client, CustomItemDisplayPreferences.Key'.
```

I noticed a few references to CustomItemDisplayPreferences in the base jellyfin server repo. They seemed to deal with a migration in 10.7. 
Once again, Thanks, and I will mark this as closed now.
