### ISSUE TITLE
Maximum number of simultaneous user sessions

### ISSUE THREAD

**Issue by tomaswl1** [jellyfin/jellyfin-androidtv#1265]
### Describe the bug

Hi i am using the latest Jellyfin server 10.7.7 and the latest android tv app i noticed when setting up a new user there is a option to set the maximum number of simultaneous user sessions i tried setting this to 1 assuming that no more than 1 session to that user is allowed but now it wont even log the user account in not sure if this is a bug server side or android tv app side just wanted to flag it up just says invalid username and or password

### Logs

```shell
2021-11-23 13:53:11.878 29985-29985/org.jellyfin.androidtv.debug E/o.j.s.a.c.KtorClient: Unknown error occurred!
    org.jellyfin.sdk.api.client.exception.InvalidStatusException: Invalid HTTP status in response: 403
        at org.jellyfin.sdk.api.operations.UserApi.authenticateUserByName(UserApi.kt:376)
        at org.jellyfin.sdk.api.operations.UserApi$authenticateUserByName$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2021-11-23 13:53:11.878 29985-29985/org.jellyfin.androidtv.debug E/AuthenticationRepositoryImpl$login: Unable to sign in as
    org.jellyfin.sdk.api.client.exception.InvalidStatusException: Invalid HTTP status in response: 403
        at org.jellyfin.sdk.api.operations.UserApi.authenticateUserByName(UserApi.kt:376)
        at org.jellyfin.sdk.api.operations.UserApi$authenticateUserByName$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

### Application version

0.12.3

### Device information

Shield / Firestick

### Android version

Android 10

### Jellyfin server version

10.7.7

**Comment by nielsvanvelzen** [comment]
The app does not support this server feature because it's badly implemented. There is (currently) no way to detect if the maximum login count is exceeded from our side because we receive the same signal as a bad login from the server.
