### ISSUE TITLE
Crash: UserDto null in background thread

### ISSUE THREAD

**Issue by DavidFair** [jellyfin/jellyfin-androidtv#1367]
### Describe the bug

(Reported via a family member, I need to walk them through giving me various details, but I'm pretty sure I installed 0.12.3 last time I saw them)

This looks like #325 is reappearing. Apparently it's happened ~9 times in the last 2 days on a mid-end TV (likely memory constrained)

Step to reproduce:
1. Open Jellyfin Android App
2. Switch to another app, initiate playback
3. The ACRA report dialogue will briefly appear over the other app when Jellyfin crashes in the background

They're happy to side-load APKs / capture logcat if this would help developers to insert logging / test fixes.

### Logs

```shell
--------- beginning of crash
01-19 20:59:39.925 10686 10686 E AndroidRuntime: FATAL EXCEPTION: main
01-19 20:59:39.925 10686 10686 E AndroidRuntime: Process: org.jellyfin.androidtv, PID: 10686
01-19 20:59:39.925 10686 10686 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.jellyfin.androidtv/org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jellyfin.apiclient.model.dto.UserDto.getId()' on a null object reference
01-19 20:59:39.925 10686 10686 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
01-19 20:59:39.925 10686 10686 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
01-19 20:59:39.925 10686 10686 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
01-19 20:59:39.925 10686 10686 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
01-19 20:59:39.925 10686 10686 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
01-19 20:59:39.925 10686 10686 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
01-19 20:59:39.925 10686 10686 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
01-19 20:59:39.925 10686 10686 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
01-19 20:59:39.925 10686 10686 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6718)
01-19 20:59:39.925 10686 10686 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-19 20:59:39.925 10686 10686 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-19 20:59:39.925 10686 10686 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-19 20:59:39.925 10686 10686 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jellyfin.apiclient.model.dto.UserDto.getId()' on a null object reference
01-19 20:59:39.925 10686 10686 E AndroidRuntime:        at org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity.loadItem(FullDetailsActivity.java:374)
01-19 20:59:39.925 10686 10686 E AndroidRuntime:        at org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity.onCreate(FullDetailsActivity.java:212)
01-19 20:59:39.925 10686 10686 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7144)
01-19 20:59:39.925 10686 10686 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7135)
01-19 20:59:39.925 10686 10686 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
01-19 20:59:39.925 10686 10686 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
01-19 20:59:39.925 10686 10686 E AndroidRuntime:        ... 11 more
01-19 20:59:39.926 10686 10686 E ACRA    : ACRA caught a RuntimeException for org.jellyfin.androidtv
01-19 20:59:39.926 10686 10686 E ACRA    : java.lang.RuntimeException: Unable to start activity ComponentInfo{org.jellyfin.androidtv/org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jellyfin.apiclient.model.dto.UserDto.getId()' on a null object reference
01-19 20:59:39.926 10686 10686 E ACRA    :      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
01-19 20:59:39.926 10686 10686 E ACRA    :      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
01-19 20:59:39.926 10686 10686 E ACRA    :      at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
01-19 20:59:39.926 10686 10686 E ACRA    :      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
01-19 20:59:39.926 10686 10686 E ACRA    :      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
01-19 20:59:39.926 10686 10686 E ACRA    :      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
01-19 20:59:39.926 10686 10686 E ACRA    :      at android.os.Handler.dispatchMessage(Handler.java:106)
01-19 20:59:39.926 10686 10686 E ACRA    :      at android.os.Looper.loop(Looper.java:193)
01-19 20:59:39.926 10686 10686 E ACRA    :      at android.app.ActivityThread.main(ActivityThread.java:6718)
01-19 20:59:39.926 10686 10686 E ACRA    :      at java.lang.reflect.Method.invoke(Native Method)
01-19 20:59:39.926 10686 10686 E ACRA    :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-19 20:59:39.926 10686 10686 E ACRA    :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-19 20:59:39.926 10686 10686 E ACRA    : Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jellyfin.apiclient.model.dto.UserDto.getId()' on a null object reference
01-19 20:59:39.926 10686 10686 E ACRA    :      at org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity.loadItem(FullDetailsActivity.java:374)
01-19 20:59:39.926 10686 10686 E ACRA    :      at org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity.onCreate(FullDetailsActivity.java:212)
01-19 20:59:39.926 10686 10686 E ACRA    :      at android.app.Activity.performCreate(Activity.java:7144)
01-19 20:59:39.926 10686 10686 E ACRA    :      at android.app.Activity.performCreate(Activity.java:7135)
01-19 20:59:39.926 10686 10686 E ACRA    :      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
01-19 20:59:39.926 10686 10686 E ACRA    :      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
01-19 20:59:39.926 10686 10686 E ACRA    :      ... 11 more
01-19 20:59:39.984  2588  2588 D MTK_KL  : 4,34112,1450383518,-;[MI_AOUT_GetHandle:11957][2949] (11957)ePath:7
01-19 20:59:39.984  2588  2588 D MTK_KL  : 4,34113,1450383533,-;[MI_AOUT_GetHandle:11985][2949] (11985)phAout:0x17000004, eErrCode:0x0
01-19 20:59:39.988 10686 10698 I lyfin.androidt: Background concurrent copying GC freed 4095(646KB) AllocSpace objects, 0(0B) LOS objects, 25% free, 2MB/3MB, paused 1.108ms total 102.830ms
01-19 20:59:40.031  4805  4805 I chromium: [4805:4805:INFO:metrics_recorder.cc(188)] cast event: Cloud.Transport.Https.StatusChange.Out.Success
01-19 20:59:40.044  2588  2588 D MTK_KL  : 4,34114,1450443566,-;[MI_AOUT_GetHandle:11957][2949] (11957)ePath:7
01-19 20:59:40.044  2588  2588 D MTK_KL  : 4,34115,1450443581,-;[MI_AOUT_GetHandle:11985][2949] (11985)phAout:0x17000004, eErrCode:0x0
01-19 20:59:40.044  2588  2588 D MTK_KL  : 31,34116,1450444249,-;logd: logdr: UID=10085 GID=10085 PID=10833 n tail=100 logMask=19 pid=0 start=0ns timeout=0ns
01-19 20:59:40.057  2151  2151 E SELinux : avc:  denied  { find } for service=meminfo pid=10837 uid=10085 scontext=u:r:untrusted_app:s0:c85,c256,c512,c768 tcontext=u:object_r:meminfo_service:s0 tclass=service_manager permissive=0
01-19 20:59:40.086  3311  3638 D MonitorActivityController: ** Activity resuming: org.jellyfin.androidtv
01-19 20:59:40.086  3311  3638 D MonitorActivityController: ** setOTTSrc currentOttSrc: org.jellyfin.androidtv
01-19 20:59:40.087  2605 10405 W ActivityManager: Duplicate finish request for ActivityRecord{622f5b4 u0 org.jellyfin.androidtv/.ui.itemdetail.FullDetailsActivity t516 f}
01-19 20:59:40.088 10686 10686 I Process : Sending signal. PID: 10686 SIG: 9
01-19 20:59:40.105  2588  2588 D MTK_KL  : 4,34117,1450503532,-;[MI_AOUT_GetHandle:11957][2949] (11957)ePath:7
01-19 20:59:40.105  2588  2588 D MTK_KL  : 4,34118,1450503548,-;[MI_AOUT_GetHandle:11985][2949] (11985)phAout:0x17000004, eErrCode:0x0
01-19 20:59:40.166  2588  2588 D MTK_KL  : 4,34119,1450563502,-;[MI_AOUT_GetHandle:11957][2949] (11957)ePath:7
01-19 20:59:40.166  2588  2588 D MTK_KL  : 4,34120,1450563518,-;[MI_AOUT_GetHandle:11985][2949] (11985)phAout:0x17000004, eErrCode:0x0
01-19 20:59:40.167  2605  5987 I ActivityManager: Process org.jellyfin.androidtv (pid 10686) has died: fore TOP
01-19 20:59:40.167  2605  2704 W libprocessgroup: kill(-10686, 9) failed: No such process
01-19 20:59:40.172  2266  2266 I Zygote  : Process 10686 exited due to signal (9)
01-19 20:59:40.205  2605  2702 I ActivityManager: Start proc 10853:org.jellyfin.androidtv/u0a85 for activity org.jellyfin.androidtv/.ui.startup.StartupActivity
01-19 20:59:40.211  2605  2704 W libprocessgroup: kill(-10686, 9) failed: No such process
```

### Application version

0.12.3
### Where did you install the app from?

Google Play

### Device information
JVC-It-40ca890

### Jellyfin server version
10.8.0 Alpha 3

**Comment by mueslimak3r** [comment]
what does 0.12.3 (TBC) mean?
Can you build off main and see if that fixes it?

If I remember right from another user who reported UserDto null, the issue was caused earlier by a prior crash for a different reason, and that resulted in a null user when it restarted.

So for now, finding the cause of the original crash and fixing that is more viable than implementing app-wide handling of the kind of condition that occurs here with the null user.

**Comment by DavidFair** [comment]
> what does 0.12.3 (TBC) mean?

Basically I got an email with the logs and a reproducer as they were going to sleep. So I haven't been able to confirm anything with them yet, so I'm going off memory from when I helped setup the client until tomorrow. I'll edit my post once I manage to ask these various details.

> Can you build off main and see if that fixes it?

Yeah I'm happy to get them to sideload the latest main and see if that works...

> If I remember right from another user who reported UserDto null, the issue was caused earlier by a prior crash for a different reason, and that resulted in a null user when it restarted.

There could be something in this, they were watching something when it crashed playback. Unfortunately the crash was too old to be in the logs when they sent them to me. After switching to an unrelated app the crashes kept happening in the background until they force stopped the application

**Comment by mueslimak3r** [comment]
> on a mid-end TV (likely memory constrained)
If you build off main with my pending leak fixes PR merged, that might prevent OOM crashes on their memory constrained device.

**Comment by DavidFair** [comment]
So we've grabbed that APK and it's resolved 90% of the crashes we were seeing. But it's still happening 2-3 times instead of 8-9 now we're not leaking memory

Unfortunately it looks like we're still fighting Androids lifetimes:

> I have found if I watch 3 videos in another app and let them load and play for around 5-10 minutes
> then re-open jelly fin
> bam crash..

and

> Got another closing the app, then switching to Prime

Looks like it's the same thing in the logs again:

```shell
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jellyfin.apiclient.model.dto.UserDto.getId()' on a null object reference
01-20 11:13:58.833  1710  1710 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
01-20 11:13:58.833  1710  1710 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
01-20 11:13:58.833  1710  1710 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
01-20 11:13:58.833  1710  1710 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
01-20 11:13:58.833  1710  1710 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
01-20 11:13:58.833  1710  1710 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
01-20 11:13:58.833  1710  1710 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-20 11:13:58.833  1710  1710 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
01-20 11:13:58.833  1710  1710 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
01-20 11:13:58.833  1710  1710 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-20 11:13:58.833  1710  1710 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-20 11:13:58.833  1710  1710 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-20 11:13:58.833  1710  1710 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jellyfin.apiclient.model.dto.UserDto.getId()' on a null object reference
01-20 11:13:58.833  1710  1710 E AndroidRuntime: 	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity.loadItem(FullDetailsActivity.java:381)
01-20 11:13:58.833  1710  1710 E AndroidRuntime: 	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity.onCreate(FullDetailsActivity.java:217)
01-20 11:13:58.833  1710  1710 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7144)
01-20 11:13:58.833  1710  1710 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7135)
01-20 11:13:58.833  1710  1710 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
01-20 11:13:58.833  1710  1710 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
01-20 11:13:58.833  1710  1710 E AndroidRuntime: 	... 11 more
```

**Comment by nielsvanvelzen** [comment]
The NullPointerException for the UserDto is a long standing issue that will take a while before it gets properly fixed. Various efforts are in progress to fix it. This includes migrating to the new SDK, migrating to MVVM-ish architecture and migrating to Kotlin.

For now we just need to fix the actual crash that caused the app to recover (and fail).

**Comment by mueslimak3r** [comment]
> > I have found if I watch 3 videos in another app and let them load and play for around 5-10 minutes
> > then re-open jelly fin
> > bam crash..

If you attach a debugger (and make sure it's logging correctly. Often after crashes timber stops logging stuff for me) and repeat those steps, you might catch the cause of the crash.
Perhaps the device is killing jellyfin due to memory constraints and jellyfin isn't handing that properly.
