### ISSUE TITLE
Unable to play Videos with Dolby 5.1 Audio

### ISSUE THREAD

**Issue by Gr3q** [jellyfin/jellyfin-androidtv#142]
Edit: Can't play any of my Videos with 5.1 Audio. maybe I'm doing something wrong?

### Issue: 
Video does not play, exits with errors. Jellyfin Web interface can play the video from other devices.

Tried all combinations of the Audio Settings in the App, they don't make a difference.

### Device: 
* Amazon Fire TV Stick - Stereo Downmixing enabled in the Stick Settings
* Stereo TV

### Video: 
_(maybe there is non-relevant info in it too, sorry)_
```
The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264.mkv

General
File: /run/user/1000/gvfs/smb-share:server=192.168.0.50,share=hdd/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264.mkv
Size: 1040036 KB (1015 MB)
Length: 00:46:24
Demuxer: mkv

Clip info
Name: The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264.mkv

Initial Video Stream
Resolution: 1280 x 720
Aspect ratio: 1.77778
Format: h264
Bitrate: 1775 kbps
Frames per second: 23.976025
Selected codec: h264

Video Streams
Track 0
Language: eng
Name: 720p / 23.976 FPS / x264
ID: 1

Initial Audio Stream
Format: ac3
Bitrate: 384 kbps
Rate: 48000 Hz
Channels: 6
Selected codec: ac3

Audio Streams
Track 0
Language: eng
Name: Dolby Digital 5.1 AC3 (384 Kbps)
ID: 1

```

### Jellyfin Server Log:
 _from selecting play to the error upon playing the video:_
```
[2019-08-23 19:43:34.461 +01:00] [INF] User policy for "Greg". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2019-08-23 19:43:34.521 +01:00] [INF] Profile: "Android-VLC", Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-08-23 19:43:34.575 +01:00] [INF] Profile: "VideoCodecProfile", DirectPlay=false. Reason="Android-VLC".RefFrames Condition: GreaterThanEqual. ConditionValue: "2". IsRequired: False. Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv"
[2019-08-23 19:43:34.718 +01:00] [INF] Profile: "Android-VLC", Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-08-23 19:43:34.719 +01:00] [INF] Profile: "VideoCodecProfile", DirectPlay=false. Reason="Android-VLC".RefFrames Condition: GreaterThanEqual. ConditionValue: "2". IsRequired: False. Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv"
[2019-08-23 19:43:34.719 +01:00] [INF] Profile: "Android-VLC", Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-08-23 19:43:34.720 +01:00] [INF] Profile: "VideoCodecProfile", DirectPlay=false. Reason="Android-VLC".RefFrames Condition: GreaterThanEqual. ConditionValue: "2". IsRequired: False. Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv"
[2019-08-23 19:43:34.827 +01:00] [WRN] HTTP Response 200 to "192.168.0.17". Time (slow): 0:00:00.7292956. "http://192.168.0.50:8096/emby/Items/1ff9bd191d39f00a821738322bf058a5/PlaybackInfo?format=json"
[2019-08-23 19:43:35.022 +01:00] [INF] User policy for "Greg". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2019-08-23 19:43:35.022 +01:00] [INF] Profile: "Android-Exo", Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-08-23 19:43:35.023 +01:00] [INF] Profile: "Android-Exo", No direct play profiles found for Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv"
[2019-08-23 19:43:35.031 +01:00] [INF] Profile: "Android-Exo", Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-08-23 19:43:35.031 +01:00] [INF] Profile: "Android-Exo", No direct play profiles found for Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv"
[2019-08-23 19:43:35.032 +01:00] [INF] Profile: "Android-Exo", Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-08-23 19:43:35.032 +01:00] [INF] Profile: "Android-Exo", No direct play profiles found for Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv"
[2019-08-23 19:43:35.574 +01:00] [ERR] Error processing request
System.ArgumentException: Invalid type
Parameter name: type
   at MediaBrowser.Api.BaseApiService.GetItemByName(String name, String type, ILibraryManager libraryManager, DtoOptions dtoOptions) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.Api/BaseApiService.cs:line 358
   at MediaBrowser.Api.Images.ImageService.Get(GetItemByNameImage request) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.Api/Images/ImageService.cs:line 406
   at lambda_method(Closure , Object , Object )
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/Services/ServiceExec.cs:line 88
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/Services/ServiceController.cs:line 177
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/Services/ServiceHandler.cs:line 95
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 576
[2019-08-23 19:43:36.305 +01:00] [INF] /usr/bin/ffmpeg -ss 00:05:10.196 -i file:"/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv" -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_omx -force_key_frames "expr:gte(t,n_forced*5)" -copyts -avoid_negative_ts disabled -start_at_zero -b:v 53439285 -maxrate 53439285 -bufsize 106878570 -vsync -1 -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 aac -strict experimental -ac 2 -ab 192000 -af "volume=2" -y "/var/lib/jellyfin/transcoding-temp/8f358216cd160a1155ac5444a5dc30f4.mkv"
[2019-08-23 19:43:42.549 +01:00] [INF] FFMpeg exited with code 1
[2019-08-23 19:43:45.459 +01:00] [WRN] HTTP Response 200 to "192.168.0.17". Time (slow): 0:00:09.6563256. "http://192.168.0.50:8096/emby/videos/1ff9bd19-1d39-f00a-8217-38322bf058a5/stream.mkv?DeviceId=4b60de95341e5b36&MediaSourceId=1ff9bd191d39f00a821738322bf058a5&VideoCodec=h264&AudioCodec=aac,mp3&AudioStreamIndex=1&VideoBitrate=53439285&AudioBitrate=192000&StartTimeTicks=3101960000&PlaySessionId=3295715530594f82a6bb95052e70f615&CopyTimestamps=true&RequireAvc=false&Tag=2f5b5ef67fb8a0f07ae2faddd8c812fb&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&h264-maxrefframes=12&aac-audiochannels=2&mp3-audiochannels=2&TranscodeReasons=AudioCodecNotSupported&allowVideoStreamCopy=false&allowAudioStreamCopy=false"
[2019-08-23 19:43:45.872 +01:00] [WRN] HTTP Response 200 to "192.168.0.17". Time (slow): 0:00:02.0693108. "http://192.168.0.50:8096/emby/videos/1ff9bd19-1d39-f00a-8217-38322bf058a5/stream.mkv?DeviceId=4b60de95341e5b36&MediaSourceId=1ff9bd191d39f00a821738322bf058a5&VideoCodec=h264&AudioCodec=aac,mp3&AudioStreamIndex=1&VideoBitrate=53439285&AudioBitrate=192000&StartTimeTicks=3101960000&PlaySessionId=3295715530594f82a6bb95052e70f615&CopyTimestamps=true&RequireAvc=false&Tag=2f5b5ef67fb8a0f07ae2faddd8c812fb&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&h264-maxrefframes=12&aac-audiochannels=2&mp3-audiochannels=2&TranscodeReasons=AudioCodecNotSupported&allowVideoStreamCopy=false&allowAudioStreamCopy=false"
[2019-08-23 19:43:46.639 +01:00] [INF] Deleting partial stream file(s) "/var/lib/jellyfin/transcoding-temp/8f358216cd160a1155ac5444a5dc30f4.mkv"
```
I can provide the video in question if that helps debugging.
If you tell me how can I access the logs of the App (if there is any) I can provide them as well.

**Comment by JoaoPedroBelo** [comment]
Any news on this?

**Comment by Gr3q** [comment]
I can elaborate on this now.

The "Bitstream Dolby Digital audio" setting was on, so it make sense that videos with Dolby 5.1 do not play on my TV what only supports stereo.

The problem is that if I turn that option off in the app, I'm unable to play any videos at all. The loading animation shows for a minute, then giving up with too many errors. Server log shows that it starts playing, but stops after a minute. (retries twice) Audio Output setting does not affect it.

Should I close this and open another issue?

**Comment by JoaoPedroBelo** [comment]
same in mine.

**Comment by anthonylavado** [comment]
>Should I close those and open another issue?

@Gr3q If you don’t mind, that might be best here.
