### ISSUE TITLE
Exoplayer: Playback speed not respected on specifc TVs and Media

### ISSUE THREAD

**Issue by DavidFair** [jellyfin/jellyfin-androidtv#1517]
### Describe the bug

- Ensure Exoplayer is selected and play media (any will do)
- Set the playback speed to something obvious like 0.25
- Observe the speed does not change on some TVs (in this case a Bravia)

Interestingly, stepping through the debugger I can see that:
- `setPlaybackParameters` is called
- The async method is fired
- Calling `getPlaybackParameters` reflects the correct speed
- Adding a listener to `VideoManager:onPlaybackParametersChanged(PlaybackParameters p)` reflects the new value too.

LibVLC does work, so there's something specific going on with Exoplayer. 
At this point I'm throwing an issue up for ideas where to look next...

### Logs

```shell
Nothing really helpful here:

V/WebSocketImpl: matched frame: Framedata{ optcode:PONG, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:0], payload:}
V/WebSocketImpl: send frame: Framedata{ optcode:PING, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:0], payload:}
V/Draft_6455: afterEnconding(0): 
V/WebSocketImpl: write(6): ��{kO
V/WebSocketImpl: process(2): (���)
V/Draft_6455: afterDecoding(0): 
V/WebSocketImpl: matched frame: Framedata{ optcode:PONG, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:0], payload:}
I/Choreographer: Skipped 14806 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer: Davey! duration=246820ms; Flags=1, IntendedVsync=5805149327989, Vsync=6051915984785, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=6051922584306, AnimationStart=6051922685556, PerformTraversalsStart=6051923724640, DrawStart=6051954882390, SyncQueued=6051964320223, SyncStart=6051964569556, IssueDrawCommandsStart=6051965342890, SwapBuffers=6051969256973, FrameCompleted=6051970279806, DequeueBufferDuration=178000, QueueBufferDuration=300000, 
D/jellyfin-apiclient: Adding request to queue: https://<URL>/Sessions/Playing/Progress
I/Choreographer: Skipped 94 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer: Davey! duration=1582ms; Flags=0, IntendedVsync=6051935761751, Vsync=6053502428355, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=6053506300639, AnimationStart=6053506427639, PerformTraversalsStart=6053507441806, DrawStart=6053507979556, SyncQueued=6053512507889, SyncStart=6053512822973, IssueDrawCommandsStart=6053513025223, SwapBuffers=6053517419223, FrameCompleted=6053518081056, DequeueBufferDuration=178000, QueueBufferDuration=222000, 
I/jellyfin-apiclient: Response received from: https://<URL>/Sessions/Playing/Progress
W/libEGL: EGLNativeWindowType 0xe2119bc8 disconnect failed
D/jellyfin-apiclient: Adding request to queue: https://<URL>/Sessions/Playing/Progress
I/jellyfin-apiclient: Response received from: https://<URL>/Sessions/Playing/Progress
```

### Application version

master@7bf1f9b38bd1a78bcddbe35a362ba893679b058c

### Where did you install the app from?

Sideloaded APK

### Device information

Sony Bravia 4K VH2 (A80J)

### Android version

Android 10

### Jellyfin server version

10.8.0 Alpha 5

**Comment by nielsvanvelzen** [comment]
Does this happen for all media or just particular codecs?

**Comment by DavidFair** [comment]
So I've eliminated codec issues as h264/h265/vp8 are all working using the [Big Buck Bunny Demos](https://test-videos.co.uk/bigbuckbunny/mp4-h264)

I've also noticed it isn't all media, I just happened to have selected 5 completely different shows with the exact problem. It was only I randomly selected Avatar from the same library that it randomly slowed down to 0.25:

Here's a breakdown in-case you spot something which might help point us in the right direction:

Works:
```
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Big_Buck_Bunny_h264_10s_30MB.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : Big Buck Bunny, Sunflower version
    artist          : Blender Foundation 2008, Janus Bager Kristensen 2013
    composer        : Sacha Goedegebure
    encoder         : Lavf57.63.100
    comment         : Creative Commons Attribution 3.0 - http://bbb3d.renderfarming.net
    genre           : Animation
  Duration: 00:00:10.00, start: 0.000000, bitrate: 24563 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 24559 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
---------------------
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Big_Buck_Bunny_h265_10s_30MB.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    title           : Big Buck Bunny, Sunflower version
    artist          : Blender Foundation 2008, Janus Bager Kristensen 2013
    composer        : Sacha Goedegebure
    encoder         : Lavf58.10.100
    comment         : Creative Commons Attribution 3.0 - http://bbb3d.renderfarming.net
    genre           : Animation
  Duration: 00:00:10.00, start: 0.000000, bitrate: 25169 kb/s
    Stream #0:0(und): Video: hevc (Main) (hev1 / 0x31766568), yuv420p(tv, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 25163 kb/s, 30 fps, 30 tbr, 15360 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
--------------------
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
Input #0, matroska,webm, from 'Big_Buck_Bunny_webm_10s_30MB.webm':
  Metadata:
    title           : Big Buck Bunny, Sunflower version
    GENRE           : Animation
    MAJOR_BRAND     : isom
    MINOR_VERSION   : 1
    COMPATIBLE_BRANDS: isomavc1
    COMPOSER        : Sacha Goedegebure
    ARTIST          : Blender Foundation 2008, Janus Bager Kristensen 2013
    COMMENT         : Creative Commons Attribution 3.0 - http://bbb3d.renderfarming.net
    ENCODER         : Lavf58.13.102
  Duration: 00:00:10.00, start: 0.000000, bitrate: 25183 kb/s
    Stream #0:0: Video: vp8, yuv420p(progressive), 1920x1080, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 1k tbn, 1k tbc (default)
    Metadata:
      HANDLER_NAME    : GPAC ISO Video Handler
      ENCODER         : Lavc58.19.101 libvpx
      DURATION        : 00:00:10.000000000
------------------------
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
Input #0, matroska,webm, from 'Avatar - The Last Airbender S01E01.mkv':
  Metadata:
    title           : Avatar: The Last Airbender - S01E01 - The Boy in the Iceberg
    encoder         : libebml v1.3.10 + libmatroska v1.5.2
    creation_time   : 2020-04-05T11:45:22.000000Z
    TVDB            : 74852
    TMDB            : tv/246
    track           : 1
    TOTAL_PARTS     : 20
    IMDB            : tt0801470
  Duration: 00:23:40.51, start: 0.000000, bitrate: 28586 kb/s
    Chapter #0:0: start 0.000000, end 410.910000
    Metadata:
      title           : Chapter 1
    Chapter #0:1: start 410.910000, end 713.922000
    Metadata:
      title           : Chapter 2
    Chapter #0:2: start 713.922000, end 1039.497000
    Metadata:
      title           : Chapter 3
    Chapter #0:3: start 1039.497000, end 1372.955000
    Metadata:
      title           : Chapter 4
    Chapter #0:4: start 1372.955000, end 1420.512000
    Metadata:
      title           : Chapter 5
    Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      title           : MPEG-4 AVC Video / 27976 kbps / 1080p / 23.976 fps / 16:9 / High Profile 4.1
      BPS-eng         : 27785329
      DURATION-eng    : 00:23:40.503000000
      NUMBER_OF_FRAMES-eng: 34058
      NUMBER_OF_BYTES-eng: 4933643000
      _STATISTICS_WRITING_APP-eng: mkvmerge v45.0.0 ('Heaven in Pennies') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-05 11:45:22
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Audio: flac, 48000 Hz, stereo, s32 (24 bit) (default)
    Metadata:
      title           : FLAC Audio / 2.0 / 48 kHz / 760 kbps / 24-bit
      BPS-eng         : 759825
      DURATION-eng    : 00:23:40.512000000
      NUMBER_OF_FRAMES-eng: 16647
      NUMBER_OF_BYTES-eng: 134917692
      _STATISTICS_WRITING_APP-eng: mkvmerge v45.0.0 ('Heaven in Pennies') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-05 11:45:22
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Subtitle: hdmv_pgs_subtitle, 1920x1080
    Metadata:
      title           : SDH
      BPS-eng         : 40319
      DURATION-eng    : 00:22:54.705000000
      NUMBER_OF_FRAMES-eng: 768
      NUMBER_OF_BYTES-eng: 6928459
      _STATISTICS_WRITING_APP-eng: mkvmerge v45.0.0 ('Heaven in Pennies') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-05 11:45:22
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

```

Cannot change speed (faster or slower):
```
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
Input #0, matroska,webm, from 'The Apprentice (UK) S10E01.mkv':
  Metadata:
    ENCODER         : Stupid Ocelot
  Duration: 00:58:26.22, start: 0.080000, bitrate: 2178 kb/s
    Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1k tbn, 50 tbc (default)
    Stream #0:1: Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s (default)
----------------------
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
Input #0, matroska,webm, from 'Brooklyn Nine-Nine S01E01.mkv':
  Metadata:
    encoder         : libmakemkv v1.16.4 (1.3.10/1.5.2) win(x64-release)
  Duration: 00:22:48.66, start: 0.000000, bitrate: 27635 kb/s
    Chapter #0:0: start 0.000000, end 107.232125
    Metadata:
      title           : Chapter 01
    Chapter #0:1: start 107.232125, end 511.427583
    Metadata:
      title           : Chapter 02
    Chapter #0:2: start 511.427583, end 933.557625
    Metadata:
      title           : Chapter 03
    Chapter #0:3: start 933.557625, end 1324.156167
    Metadata:
      title           : Chapter 04
    Chapter #0:4: start 1324.156167, end 1368.658958
    Metadata:
      title           : Chapter 05
    Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc
    Metadata:
      BPS-eng         : 23937933
      DURATION-eng    : 00:22:48.658958333
      NUMBER_OF_FRAMES-eng: 32815
      NUMBER_OF_BYTES-eng: 4095355532
      SOURCE_ID-eng   : 001011
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.16.4 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2022-03-08 22:39:47
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:1(eng): Audio: dts (DTS-HD MA), 48000 Hz, 5.1(side), s32p (24 bit) (default)
    Metadata:
      title           : Surround 5.1
      BPS-eng         : 3624494
      DURATION-eng    : 00:22:48.000000000
      NUMBER_OF_FRAMES-eng: 128250
      NUMBER_OF_BYTES-eng: 619788644
      SOURCE_ID-eng   : 001100
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.16.4 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2022-03-08 22:39:47
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:2(eng): Subtitle: hdmv_pgs_subtitle, 1920x1080
    Metadata:
      title           : English PGS SDH
      BPS-eng         : 72644
      DURATION-eng    : 00:22:29.952770833
      NUMBER_OF_FRAMES-eng: 1216
      NUMBER_OF_BYTES-eng: 12258244
      SOURCE_ID-eng   : 001200
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.16.4 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2022-03-08 22:39:47
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
--------
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
[mpeg2video @ 0x55ed37d2f300] ignoring pic cod ext after 0
[matroska,webm @ 0x55ed37d27f00] Could not find codec parameters for stream 2 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size                                                                                                          
Consider increasing the value for the 'analyzeduration' and 'probesize' options                                         
Input #0, matroska,webm, from 'Black Mirror S01E01.mkv':
  Metadata:
    encoder         : libebml v1.3.5 + libmatroska v1.4.8
    creation_time   : 2018-04-09T15:32:59.000000Z
  Duration: 00:44:06.05, start: 0.000000, bitrate: 18170 kb/s
    Chapter #0:0: start 0.000000, end 79.800000
    Metadata:
      title           : Chapter 1
    Chapter #0:1: start 79.800000, end 687.280000
    Metadata:
      title           : Chapter 2
    Chapter #0:2: start 687.280000, end 1158.400000
    Metadata:
      title           : Chapter 3
    Chapter #0:3: start 1158.400000, end 1758.720000
    Metadata:
      title           : Chapter 4
    Chapter #0:4: start 1758.720000, end 2571.800000
    Metadata:
      title           : Chapter 5
    Chapter #0:5: start 2571.800000, end 2646.048000
    Metadata:
      title           : Chapter 6
    Stream #0:0(eng): Video: mpeg2video (Main), yuv420p(tv, top first), 1920x1080 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 1k tbn, 50 tbc (default)
    Metadata:
      title           : MPEG-2 Video / 15970 kbps / 1080i / 25 fps / 16:9
      BPS-eng         : 15969675
      DURATION-eng    : 00:44:06.040000000
      NUMBER_OF_FRAMES-eng: 66151
      NUMBER_OF_BYTES-eng: 5282049920
      _STATISTICS_WRITING_APP-eng: mkvmerge v22.0.0 ('At The End Of The World') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-04-09 15:32:59
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Audio: dts (DTS-HD MA), 48000 Hz, 5.1(side), s16p (default)
    Metadata:
      title           : DTS-HD Master Audio / 5.1 / 48 kHz / 2164 kbps / 16-bit
      BPS-eng         : 2163511
      DURATION-eng    : 00:44:06.048000000
      NUMBER_OF_FRAMES-eng: 248067
      NUMBER_OF_BYTES-eng: 715594456
      _STATISTICS_WRITING_APP-eng: mkvmerge v22.0.0 ('At The End Of The World') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-04-09 15:32:59
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(dut): Subtitle: hdmv_pgs_subtitle
    Metadata:
      BPS-eng         : 32978
      DURATION-eng    : 00:41:47.720000000
      NUMBER_OF_FRAMES-eng: 857
      NUMBER_OF_BYTES-eng: 10337520
      _STATISTICS_WRITING_APP-eng: mkvmerge v22.0.0 ('At The End Of The World') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-04-09 15:32:59
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
```

**Comment by DavidFair** [comment]
Additionally, I can't reproduce this with the same media on the emulator so it looks like some interaction between this model of TV and Exoplayer...

**Comment by nielsvanvelzen** [comment]
I did find this note stating that playback speed is not supported when tunneling audio. I'm not sure if/when the app does this though.

https://github.com/google/ExoPlayer/blob/8129675b065bc98330ec775fb7a538c139793070/library/core/src/main/java/com/google/android/exoplayer2/audio/DefaultAudioSink.java#L67-L70

**Comment by sourpatched** [comment]
Wasn't sure If I should open a new issues but on playback speed it doesn't reset on new item? 
i was playing around with it to test if it does recalculate ending time when you use playback speed (it does not), when I picked something else to watch, the same speed was already selected.

**Comment by DavidFair** [comment]
> Wasn't sure If I should open a new issues but on playback speed it doesn't reset on new item?

That's intentional, it preserves the selected playback speed for the session so we don't have to change it for each episode.
If you are seeing it go from your custom speed back to 1x between episodes without changing anything that would be useful, as it would indicate something different between two media files from the same series for example?

> i was playing around with it to test if it does recalculate ending time when you use playback speed (it does not)

This is encapsulated in #1509 , it's something I'd like to get round to but the classic ship something rather than nothing means it's on my (or anyone else who would like a crack at it :slightly_smiling_face: ) TODO list

**Comment by DavidFair** [comment]
> I did find this note stating that playback speed is not supported when tunneling audio. I'm not sure if/when the app does this though.

Good idea but no dice, we don't opt-in and the verbose logs show that it's non-tunnelling for an example which doesn't work correctly:
`03-13 17:16:41.190  2514 18512 D audio_hal: [start_output_stream_low_latency:388]Non-tunneling DTS: ps = 256, pc = 16, st = 32768`

**Comment by DavidFair** [comment]
I'm getting closer (and leaving this as a future note to myself):
- Enable native playback parameter handling in the app by adding the following in `VideoManager` (long-term it would be good to enable this too)
```kotlin
        defaultRendererFactory.setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_ON);
        +defaultRendererFactory.setEnableAudioTrackPlaybackParams(true);
        exoPlayerBuilder.setRenderersFactory(defaultRendererFactory);
```
- On a good media source 0.5x will hit this LOC and not fail: https://github.com/google/ExoPlayer/blob/8129675b065bc98330ec775fb7a538c139793070/library/core/src/main/java/com/google/android/exoplayer2/audio/DefaultAudioSink.java#L1522
- On a bad media source 0.5x will throw the following:
```
W/DefaultAudioSink: Failed to set playback params
      java.lang.IllegalArgumentException: arguments out of range
        at android.media.AudioTrack.native_set_playback_params(Native Method)
        at android.media.AudioTrack.setPlaybackParams(AudioTrack.java:2109)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.setAudioTrackPlaybackParametersV23(DefaultAudioSink.java:1319)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.setPlaybackParameters(DefaultAudioSink.java:1080)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.setPlaybackParameters(MediaCodecAudioRenderer.java:578)
        at com.google.android.exoplayer2.DefaultMediaClock.setPlaybackParameters(DefaultMediaClock.java:141)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.setPlaybackParametersInternal(ExoPlayerImplInternal.java:1316)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:492)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

I suspect this is the smoking gun, unfortunately I cannot debug this call as it's within the Android stdlib :thinking:

**Comment by sourpatched** [comment]
> > Wasn't sure If I should open a new issues but on playback speed it doesn't reset on new item?
> 
> That's intentional, it preserves the selected playback speed for the session so we don't have to change it for each episode. If you are seeing it go from your custom speed back to 1x between episodes without changing anything that would be useful, as it would indicate something different between two media files from the same series for example?

Makes sense. I wasn't sure if it was a bug since I picked someone else to watch therefore closing the video to select something else but as you said, it's intentional.

**Comment by DavidFair** [comment]
I'm going to close this, it's an Exoplayer issue (reproduced with their demo app) so we can't do anything on this side except update when the fix comes out.
