### ISSUE TITLE
Unable to play any videos if "Bitstream Dolby Digital audio" Option is not on in the Settings

### ISSUE THREAD

**Issue by Gr3q** [jellyfin/jellyfin-androidtv#158]
This issue is opened was opened because of this issue: https://github.com/jellyfin/jellyfin-androidtv/issues/142

Server version:  10.3.7
Client Device: Fire TV Stick 1st Gen (Downmix to Stereo On in Stick Settings), LG TV (Stereo)

Issue:

If the mentioned option is turned off, when starting to play any video the loading animation shows for a minute, then giving up with too many errors. Server log shows that it starts streaming just fine, but stops after a minute. (retries twice) Audio Output setting does not affect it.

When the "Bitstream Dolby Digital Audio" setting is on, videos with stereo audio play fine. _(I can't play videos with Dolby Audio (Instantly fails with errors) because my TV is only capable to play Stereo.)_

**Comment by JoaoPedroBelo** [comment]
same in android tv

**Comment by Gr3q** [comment]
More Information, **I built the app from the git repo this time**:

## "Bitstream Dolby Digital Audio" Enabled:
Videos with stereo audio work fine.

All Videos with Dolby Audio:
**Server Log:**
```bash
[2019-09-28 12:06:19.324 +01:00] [INF] User policy for "Greg". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2019-09-28 12:06:19.324 +01:00] [INF] Not eligible for DirectPlay due to unsupported subtitles
[2019-09-28 12:06:19.325 +01:00] [INF] Not eligible for DirectStream due to unsupported subtitles
[2019-09-28 12:06:19.325 +01:00] [INF] Profile: "Android-VLC", Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2019-09-28 12:06:19.326 +01:00] [INF] Not eligible for DirectPlay due to unsupported subtitles
[2019-09-28 12:06:19.326 +01:00] [INF] Not eligible for DirectStream due to unsupported subtitles
[2019-09-28 12:06:19.327 +01:00] [INF] Profile: "Android-VLC", Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2019-09-28 12:06:19.328 +01:00] [INF] Not eligible for DirectPlay due to unsupported subtitles
[2019-09-28 12:06:19.328 +01:00] [INF] Not eligible for DirectStream due to unsupported subtitles
[2019-09-28 12:06:19.328 +01:00] [INF] Profile: "Android-VLC", Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2019-09-28 12:06:19.526 +01:00] [INF] User policy for "Greg". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2019-09-28 12:06:19.526 +01:00] [INF] Not eligible for DirectPlay due to unsupported subtitles
[2019-09-28 12:06:19.527 +01:00] [INF] Not eligible for DirectStream due to unsupported subtitles
[2019-09-28 12:06:19.527 +01:00] [INF] Profile: "Android-Exo", Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2019-09-28 12:06:19.528 +01:00] [INF] Not eligible for DirectPlay due to unsupported subtitles
[2019-09-28 12:06:19.528 +01:00] [INF] Not eligible for DirectStream due to unsupported subtitles
[2019-09-28 12:06:19.529 +01:00] [INF] Profile: "Android-Exo", Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2019-09-28 12:06:19.529 +01:00] [INF] Not eligible for DirectPlay due to unsupported subtitles
[2019-09-28 12:06:19.530 +01:00] [INF] Not eligible for DirectStream due to unsupported subtitles
[2019-09-28 12:06:19.530 +01:00] [INF] Profile: "Android-Exo", Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2019-09-28 12:06:19.637 +01:00] [ERR] Error processing request
System.ArgumentException: Invalid type
Parameter name: type
   at MediaBrowser.Api.BaseApiService.GetItemByName(String name, String type, ILibraryManager libraryManager, DtoOptions dtoOptions) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.Api/BaseApiService.cs:line 358
   at MediaBrowser.Api.Images.ImageService.Get(GetItemByNameImage request) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.Api/Images/ImageService.cs:line 406
   at lambda_method(Closure , Object , Object )
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/Services/ServiceExec.cs:line 88
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/Services/ServiceController.cs:line 177
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/Services/ServiceHandler.cs:line 95
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 576
[2019-09-28 12:06:19.682 +01:00] [ERR] Error processing request
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at MediaBrowser.Controller.MediaEncoding.EncodingHelper.GetTextSubtitleParam(EncodingJobInfo state) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:line 576
   at MediaBrowser.Controller.MediaEncoding.EncodingHelper.GetOutputSizeParam(EncodingJobInfo state, EncodingOptions options, String outputVideoCodec, Boolean allowTimeStampCopy) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:line 1745
   at MediaBrowser.Controller.MediaEncoding.EncodingHelper.GetProgressiveVideoArguments(EncodingJobInfo state, EncodingOptions encodingOptions, String videoCodec, String defaultH264Preset) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:line 2463
   at MediaBrowser.Controller.MediaEncoding.EncodingHelper.GetProgressiveVideoFullCommandLine(EncodingJobInfo state, EncodingOptions encodingOptions, String outputPath, String defaultH264Preset) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:line 2398
   at MediaBrowser.Api.Playback.Progressive.VideoService.GetCommandLineArguments(String outputPath, EncodingOptions encodingOptions, StreamState state, Boolean isEncoding) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.Api/Playback/Progressive/VideoService.cs:line 123
   at MediaBrowser.Api.Playback.BaseStreamingService.GetOutputFilePath(StreamState state, EncodingOptions encodingOptions, String outputFileExtension) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.Api/Playback/BaseStreamingService.cs:line 138
   at MediaBrowser.Api.Playback.BaseStreamingService.GetState(StreamRequest request, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.Api/Playback/BaseStreamingService.cs:line 863
   at MediaBrowser.Api.Playback.Progressive.BaseProgressiveStreamingService.ProcessRequest(StreamRequest request, Boolean isHeadRequest) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.Api/Playback/Progressive/BaseProgressiveStreamingService.cs:line 140
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/Services/ServiceExec.cs:line 110
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/Services/ServiceHandler.cs:line 95
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 576
```

The Call:
```http://192.168.0.50:8096/videos/1ff9bd19-1d39-f00a-8217-38322bf058a5/stream.mkv?DeviceId=4b60de95341e5b36&MediaSourceId=1ff9bd191d39f00a821738322bf058a5&VideoCodec=mp4&AudioCodec=aac,mp3&AudioStreamIndex=1&SubtitleStreamIndex=2&VideoBitrate=20039823&AudioBitrate=192000&PlaySessionId=fceb79fc672149e88188b4114fbdccf3&api_key=c1e0a10fbabf43d1ac32ce3eadffdacf&SubtitleMethod=Encode&CopyTimestamps=true&RequireAvc=false&Tag=2f5b5ef67fb8a0f07ae2faddd8c812fb&aac-audiochannels=2&mp3-audiochannels=2&TranscodeReasons=SubtitleCodecNotSupported&allowVideoStreamCopy=false&allowAudioStreamCopy=false```

The Returned Error (Response code 500):
![image](https://user-images.githubusercontent.com/22377521/65815725-3dafb400-e1eb-11e9-8673-a053f2467b0a.png)

## When "Bitstream Dolby Audio" is off:
All videos have the same error, its a 404, not finding the transcoded file, what is ultimately caused by ffmpeg failing to transcode.

Server Log:
```
[2019-09-28 12:30:11.252 +01:00] [INF] User policy for "Greg". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2019-09-28 12:30:11.252 +01:00] [INF] Not eligible for DirectPlay due to unsupported subtitles
[2019-09-28 12:30:11.253 +01:00] [INF] Not eligible for DirectStream due to unsupported subtitles
[2019-09-28 12:30:11.253 +01:00] [INF] Profile: "Android-VLC", Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2019-09-28 12:30:11.254 +01:00] [INF] Not eligible for DirectPlay due to unsupported subtitles
[2019-09-28 12:30:11.254 +01:00] [INF] Not eligible for DirectStream due to unsupported subtitles
[2019-09-28 12:30:11.255 +01:00] [INF] Profile: "Android-VLC", Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2019-09-28 12:30:11.256 +01:00] [INF] Not eligible for DirectPlay due to unsupported subtitles
[2019-09-28 12:30:11.256 +01:00] [INF] Not eligible for DirectStream due to unsupported subtitles
[2019-09-28 12:30:11.257 +01:00] [INF] Profile: "Android-VLC", Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2019-09-28 12:30:11.416 +01:00] [INF] User policy for "Greg". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2019-09-28 12:30:11.417 +01:00] [INF] Profile: "Android", Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-09-28 12:30:11.417 +01:00] [INF] Profile: "Android", No direct play profiles found for Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv"
[2019-09-28 12:30:11.418 +01:00] [INF] Profile: "Android", Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-09-28 12:30:11.419 +01:00] [INF] Profile: "Android", No direct play profiles found for Path: "/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv"
[2019-09-28 12:30:11.541 +01:00] [ERR] Error processing request
System.ArgumentException: Invalid type
Parameter name: type
   at MediaBrowser.Api.BaseApiService.GetItemByName(String name, String type, ILibraryManager libraryManager, DtoOptions dtoOptions) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.Api/BaseApiService.cs:line 358
   at MediaBrowser.Api.Images.ImageService.Get(GetItemByNameImage request) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.Api/Images/ImageService.cs:line 406
   at lambda_method(Closure , Object , Object )
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/Services/ServiceExec.cs:line 88
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/Services/ServiceController.cs:line 177
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/Services/ServiceHandler.cs:line 95
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 576
[2019-09-28 12:30:11.559 +01:00] [INF] /usr/bin/ffmpeg -i file:"/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv" -map 0:0 -map 0:1 -map -0:s -codec:v:0 mp4 -force_key_frames "expr:gte(t,n_forced*5)" -vf "scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2" -copyts -avoid_negative_ts disabled -start_at_zero -pix_fmt yuv420p  -b:v 20039823 -maxrate 20039823 -bufsize 40079646 -vsync -1 -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 aac -strict experimental -ac 6 -ab 192000  -y "/var/lib/jellyfin/transcoding-temp/00f4b503c1fcf23b77772145ca67d8df.mkv"
[2019-09-28 12:30:11.886 +01:00] [INF] FFMpeg exited with code 1
[2019-09-28 12:30:11.963 +01:00] [INF] /usr/bin/ffmpeg -i file:"/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv" -map 0:0 -map 0:1 -map -0:s -codec:v:0 mp4 -force_key_frames "expr:gte(t,n_forced*5)" -vf "scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2" -copyts -avoid_negative_ts disabled -start_at_zero -pix_fmt yuv420p  -b:v 20039823 -maxrate 20039823 -bufsize 40079646 -vsync -1 -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 aac -strict experimental -ac 6 -ab 192000  -y "/var/lib/jellyfin/transcoding-temp/00f4b503c1fcf23b77772145ca67d8df.mkv"
[2019-09-28 12:30:12.276 +01:00] [WRN] "GetItemList" query time (slow): 104.528. Query: "select type,data,EndDate,ChannelId,CommunityRating,IndexNumber,Width,Height,Name,Path,PremiereDate,ParentIndexNumber,ProductionYear,OfficialRating,RunTimeTicks,Size,DateModified,guid,ParentId,Audio,IsInMixedFolder,PrimaryVersionId,Album,CriticRating,IsVirtualItem,SeriesName,SeasonName,SeasonId,SeriesId,ProviderIds,TotalBitrate,ExtraType,ExternalId,OwnerId from TypedBaseItems A where type=@type AND IsVirtualItem=@IsVirtualItem AND SeriesPresentationUniqueKey=@SeriesPresentationUniqueKey Group by PresentationUniqueKey ORDER BY SortName ASC"
[2019-09-28 12:30:12.293 +01:00] [INF] FFMpeg exited with code 1
[2019-09-28 12:30:12.686 +01:00] [INF] Playback stopped reported by app "AndroidTV" "0.9.1a" playing "Welcome to Republic City". Stopped at "0" ms
[2019-09-28 12:30:12.690 +01:00] [WRN] HTTP Response 204 to "192.168.0.17". Time (slow): 0:00:01.5167837. "http://192.168.0.50:8096/Sessions/Playing/Stopped"
[2019-09-28 12:30:13.377 +01:00] [INF] /usr/bin/ffmpeg -i file:"/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02.720p.HDTV.x264-HWE.mkv" -map 0:0 -map 0:1 -map -0:s -codec:v:0 mp4 -force_key_frames "expr:gte(t,n_forced*5)" -vf "scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2" -copyts -avoid_negative_ts disabled -start_at_zero -pix_fmt yuv420p  -b:v 20039823 -maxrate 20039823 -bufsize 40079646 -vsync -1 -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 aac -strict experimental -ac 6 -ab 192000  -y "/var/lib/jellyfin/transcoding-temp/00f4b503c1fcf23b77772145ca67d8df.mkv"
[2019-09-28 12:30:13.694 +01:00] [INF] FFMpeg exited with code 1
[2019-09-28 12:30:14.656 +01:00] [INF] Deleting partial stream file(s) "/var/lib/jellyfin/transcoding-temp/00f4b503c1fcf23b77772145ca67d8df.mkv"
[2019-09-28 12:30:14.657 +01:00] [INF] Deleting partial stream file(s) "/var/lib/jellyfin/transcoding-temp/00f4b503c1fcf23b77772145ca67d8df.mkv"
[2019-09-28 12:30:14.657 +01:00] [INF] Deleting partial stream file(s) "/var/lib/jellyfin/transcoding-temp/00f4b503c1fcf23b77772145ca67d8df.mkv"
[2019-09-28 12:30:16.170 +01:00] [INF] Playback stopped reported by app "AndroidTV" "0.9.1a" playing "Welcome to Republic City". Stopped at "0" ms
[2019-09-28 12:30:16.174 +01:00] [WRN] HTTP Response 204 to "192.168.0.17". Time (slow): 0:00:01.5214448. "http://192.168.0.50:8096/Sessions/Playing/Stopped"
```
ffmpeg call and error:
```
/usr/bin/ffmpeg -i file:"/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S
01E01-E02.720p.HDTV.x264-HWE.mkv" -map 0:0 -map 0:1 -map -0:s -codec:v:0 mp4 -force_key_frames "expr:gte(t,n_forced*5)"
 -vf "scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2" -copyts -avoid_negative_ts disabled -start_at_zero
 -pix_fmt yuv420p  -b:v 20039823 -maxrate 20039823 -bufsize 40079646 -vsync -1 -map_metadata -1 -map_chapters -1 -threa
ds 0 -codec:a:0 aac -strict experimental -ac 6 -ab 192000  -y "/var/lib/jellyfin/transcoding-temp/00f4b503c1fcf23b77772
145ca67d8df.mkv"                                                                                                       
ffmpeg version n4.2 Copyright (c) 2000-2019 the FFmpeg developers                                                      
  built with gcc 8.3.0 (GCC)                                                                                           
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --
enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enabl
e-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-li
bmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse 
--enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-lib
vorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-lib
xvid --enable-mmal --enable-omx --enable-omx-rpi --enable-shared --enable-version3 --host-cflags='"-fPIC"'             
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, matroska,webm, from 'file:/HDD/Sorozatok/Avatar - The Legend of Korra/Season 1/The.Legend.of.Korra.S01E01-E02
.720p.HDTV.x264-HWE.mkv':
  Metadata:
    encoder         : libebml v1.2.3 + libmatroska v1.3.0
    creation_time   : 2012-04-14T22:44:33.000000Z
  Duration: 00:46:24.91, start: 0.000000, bitrate: 3059 kb/s
    Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k t
bn, 47.95 tbc (default)
    Metadata:
      title           : 720p / 23.976 FPS / x264
    Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
    Metadata:
      title           : Dolby Digital 5.1 AC3 (384 Kbps)
Unknown encoder 'mp4'
```

**Comment by JoaoPedroBelo** [comment]
i fix my problem in settings audio change from direct to compatible.

**Comment by Gr3q** [comment]
Is the in you AndroidTV settings or in the app settings?

**Comment by JoaoPedroBelo** [comment]
In the app for Androidtv. But in the settings from jellyfin. By default the option in selected direct you have to change to compatible

**Comment by thornbill** [comment]
This looks like the same issue as #178. Should be fixed now.

**Comment by Gr3q** [comment]
It is indeed fixed,

Thank you so much!
