### ISSUE TITLE
Consistent Player Encountered Error - will retry

### ISSUE THREAD

**Issue by KyleSanderson** [jellyfin/jellyfin-androidtv#1703]
### Describe the bug

Doesn't seem to matter the media, it always fails on first play. Eventually it kicks into gear, but there's some bad code init that eventually sorts itself out. This seems to be the leadup to the error, looks like it may be related to mode switching into HDR / similar.

```
5-07 13:13:06.471 15247 15440 W StreamHAL: Error from HAL stream in function write: Function not implemented
05-07 13:13:06.471 15248 15263 E AudioStreamOutSink: Error while writing data to HAL: -38
05-07 13:13:06.472 15248 15657 D DolbyAudioHwDeviceProxy: getParameters(0xac85d000): avls_encodings
05-07 13:13:06.475   567   567 D AmazonAudioService-AudioCapabilities: updated system audio capabilities: {"audiocaps":{"continuousAudio":true,"uiAudioBufferDelayOffset":240,"pcm":{"mixing":true,"transition":"ease","highResMixing":"true"},"ddplus":{"mixing":true,"transition":"ease"},"atmos":{"enabled":false,"mixing":false,"transition":false}}}
05-07 13:13:06.475   567   567 D AmazonAudioService-AudioCapabilities: updated Netflix audio capabilities: {"audiocaps":{"continuousAudio":true,"uiAudioBufferDelayOffset":240,"pcm":{"mixing":true,"transition":"ease","highResMixing":"true"},"ddplus":{"mixing":true,"transition":"ease"},"atmos":{"enabled":false,"mixing":false,"transition":false}}}
05-07 13:13:06.476  9188  9188 I DeviceInfo: HDMI connection is now Unplugged
05-07 13:13:06.477   567   567 V SettingsProvider: Notifying for 0: content://settings/global/audio_platform_capabilities
05-07 13:13:06.479   567   567 V SettingsProvider: Notifying for 0: content://settings/global/nrdp_audio_platform_capabilities
05-07 13:13:06.479 15247 15440 W StreamHAL: Error from HAL stream in function write: Function not implemented
05-07 13:13:06.479 15248 15263 E AudioStreamOutSink: Error while writing data to HAL: -38
05-07 13:13:06.483 20671 20671 I DeviceInfo: HDMI connection is now Unplugged
05-07 13:13:06.485 21977 23056 E AudioTrack-JNI: Error -32 during AudioTrack native read
05-07 13:13:06.486 21977 23056 E DecoderAudioRenderer: Audio sink error
05-07 13:13:06.486 21977 23056 E DecoderAudioRenderer:   com.google.android.exoplayer2.audio.AudioSink$WriteException: AudioTrack write failed: -6
05-07 13:13:06.486 21977 23056 E DecoderAudioRenderer:       at com.google.android.exoplayer2.audio.DefaultAudioSink.writeBuffer(DefaultAudioSink.java:959)
05-07 13:13:06.486 21977 23056 E DecoderAudioRenderer:       at com.google.android.exoplayer2.audio.DefaultAudioSink.processBuffers(DefaultAudioSink.java:883)
05-07 13:13:06.486 21977 23056 E DecoderAudioRenderer:       at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:834)
05-07 13:13:06.486 21977 23056 E DecoderAudioRenderer:       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:639)
05-07 13:13:06.486 21977 23056 E DecoderAudioRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.bypassRender(MediaCodecRenderer.java:2124)
05-07 13:13:06.486 21977 23056 E DecoderAudioRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:773)
05-07 13:13:06.486 21977 23056 E DecoderAudioRenderer:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
05-07 13:13:06.486 21977 23056 E DecoderAudioRenderer:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
05-07 13:13:06.486 21977 23056 E DecoderAudioRenderer:       at android.os.Handler.dispatchMessage(Handler.java:102)
05-07 13:13:06.486 21977 23056 E DecoderAudioRenderer:       at android.os.Looper.loop(Looper.java:193)
05-07 13:13:06.486 21977 23056 E DecoderAudioRenderer:       at android.os.HandlerThread.run(HandlerThread.java:65)
05-07 13:13:06.488 15247 15440 W StreamHAL: Error from HAL stream in function write: Function not implemented
05-07 13:13:06.497 21977 21977 W ExoPlayer:Audio: type=1400 audit(0.0:772657): avc: denied { read } for name="u:object_r:media_prop:s0" dev="tmpfs" ino=8741 scontext=u:r:untrusted_app:s0:c188,c256,c512,c768 tcontext=u:object_r:media_prop:s0 tclass=file permissive=0
05-07 13:13:06.488 15248 15263 E AudioStreamOutSink: Error while writing data to HAL: -38
05-07 13:13:06.488 21977 23056 W ExoPlayerImplInternal: Recoverable renderer error
05-07 13:13:06.488 21977 23056 W ExoPlayerImplInternal:   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(2, null, null, audio/eac3, null, -1, en, [-1, -1, -1.0], [6, 48000]), format_supported=YES
05-07 13:13:06.488 21977 23056 W ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:562)
05-07 13:13:06.488 21977 23056 W ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
05-07 13:13:06.488 21977 23056 W ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:193)
05-07 13:13:06.488 21977 23056 W ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:65)
05-07 13:13:06.488 21977 23056 W ExoPlayerImplInternal:   Caused by: com.google.android.exoplayer2.audio.AudioSink$WriteException: AudioTrack write failed: -6
05-07 13:13:06.488 21977 23056 W ExoPlayerImplInternal:       at com.google.android.exoplayer2.audio.DefaultAudioSink.writeBuffer(DefaultAudioSink.java:959)
05-07 13:13:06.488 21977 23056 W ExoPlayerImplInternal:       at com.google.android.exoplayer2.audio.DefaultAudioSink.processBuffers(DefaultAudioSink.java:883)
05-07 13:13:06.488 21977 23056 W ExoPlayerImplInternal:       at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:834)
05-07 13:13:06.488 21977 23056 W ExoPlayerImplInternal:       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:639)
05-07 13:13:06.488 21977 23056 W ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.bypassRender(MediaCodecRenderer.java:2124)
05-07 13:13:06.488 21977 23056 W ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:773)
05-07 13:13:06.488 21977 23056 W ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
05-07 13:13:06.488 21977 23056 W ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
05-07 13:13:06.488 21977 23056 W ExoPlayerImplInternal:       ... 3 more
05-07 13:13:06.488 21977 23056 I MediaCodecLogger: Flushing: 21977.4K.HW.video.dolby-vision.framerate = 23.952 fps
05-07 13:13:06.489   428 23064 I MtkOmxVdecExV4L2: [0xaca83ac0] --- ETBQ: mNumPendingInput 5; mEmptyThisBufQ.size() 0
```

### Logs

```shell
05-07 13:13:06.621 21977 23056 I android.media.AudioTrack: AUDIOINFO: audio_input: format: 6 sample_rate: 48000 channels: 6 AudioAttributes: AudioAttributes: usage=USAGE_MEDIA content=CONTENT_TYPE_MUSIC flags=0x0 tags= bundle=null
05-07 13:13:06.622 15248 15657 I APM_AudioPolicyManager: getOutputForAttr() device 0x2, sampling rate 48000, format 0xa000000, channel mask 0x3f, flags 0x1 stream 0x3
05-07 13:13:06.622 15248 15657 W APM_AudioPolicyManager: getOutputForDevice() could not find output for stream 3, sampling rate 48000, format 0xa000000, channels 0x3f, flags 0x1
05-07 13:13:06.622 15248 15657 E AudioFlinger: createTrack() getOutputForAttr() return error -38 or invalid output handle
05-07 13:13:06.622 21977 23056 E IAudioFlinger: createTrack returned error -38
05-07 13:13:06.622 21977 23056 E AudioTrack: AudioFlinger could not create track, status: -38 output 0
05-07 13:13:06.623 21977 23056 E AudioTrack-JNI: Error -38 initializing AudioTrack
05-07 13:13:06.623 21977 23056 D AudioTrack: no metrics gathered, track status=-38
05-07 13:13:06.623 21977 23056 E android.media.AudioTrack: Error code -20 when initializing AudioTrack.
05-07 13:13:06.624 21977 23056 E DecoderAudioRenderer: Audio sink error
05-07 13:13:06.624 21977 23056 E DecoderAudioRenderer:   com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(48000, 252, 192000)
05-07 13:13:06.624 21977 23056 E DecoderAudioRenderer:       at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2052)
05-07 13:13:06.624 21977 23056 E DecoderAudioRenderer:       at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrack(DefaultAudioSink.java:854)
05-07 13:13:06.624 21977 23056 E DecoderAudioRenderer:       at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:660)
05-07 13:13:06.624 21977 23056 E DecoderAudioRenderer:       at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:736)
05-07 13:13:06.624 21977 23056 E DecoderAudioRenderer:       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:639)
05-07 13:13:06.624 21977 23056 E DecoderAudioRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.bypassRender(MediaCodecRenderer.java:2124)
05-07 13:13:06.624 21977 23056 E DecoderAudioRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:773)
05-07 13:13:06.624 21977 23056 E DecoderAudioRenderer:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
05-07 13:13:06.624 21977 23056 E DecoderAudioRenderer:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
05-07 13:13:06.624 21977 23056 E DecoderAudioRenderer:       at android.os.Handler.dispatchMessage(Handler.java:102)
05-07 13:13:06.624 21977 23056 E DecoderAudioRenderer:       at android.os.Looper.loop(Looper.java:193)
05-07 13:13:06.624 21977 23056 E DecoderAudioRenderer:       at android.os.HandlerThread.run(HandlerThread.java:65)
05-07 13:13:06.626 21977 23056 E ExoPlayerImplInternal: Playback error
05-07 13:13:06.626 21977 23056 E ExoPlayerImplInternal:   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(2, null, null, audio/eac3, null, -1, en, [-1, -1, -1.0], [6, 48000]), format_supported=YES
05-07 13:13:06.626 21977 23056 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:562)
05-07 13:13:06.626 21977 23056 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
05-07 13:13:06.626 21977 23056 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:193)
05-07 13:13:06.626 21977 23056 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:65)
05-07 13:13:06.626 21977 23056 E ExoPlayerImplInternal:   Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(48000, 252, 192000)
05-07 13:13:06.626 21977 23056 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2052)
05-07 13:13:06.626 21977 23056 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrack(DefaultAudioSink.java:854)
05-07 13:13:06.626 21977 23056 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:660)
05-07 13:13:06.626 21977 23056 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:736)
05-07 13:13:06.626 21977 23056 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:639)
05-07 13:13:06.626 21977 23056 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.bypassRender(MediaCodecRenderer.java:2124)
05-07 13:13:06.626 21977 23056 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:773)
05-07 13:13:06.626 21977 23056 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
05-07 13:13:06.626 21977 23056 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
05-07 13:13:06.626 21977 23056 E ExoPlayerImplInternal:       ... 3 more
05-07 13:13:06.626 21977 23056 E ExoPlayerImplInternal:       Suppressed: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(48000, 252, 192000)
05-07 13:13:06.626 21977 23056 E ExoPlayerImplInternal:           ... 12 more
05-07 13:13:06.626 21977 23056 I MediaCodecLogger: Flushing: 21977.4K.HW.video.dolby-vision.framerate = 27.397 fps
05-07 13:13:06.627   428 23064 I MtkOmxVdecExV4L2: [0xaca83ac0] --- ETBQ: mNumPendingInput 5; mEmptyThisBufQ.size() 0
05-07 13:13:06.627 15247 15440 W StreamHAL: Error from HAL stream in function write: Function not implemented
05-07 13:13:06.627 15248 15263 E AudioStreamOutSink: Error while writing data to HAL: -38
05-07 13:13:06.627   448   495 I VCodecDrv: phHandle->fgOutputEarly 0
05-07 13:13:06.627   448   495 I VdecLatCore: [eVLatSetDecodeType] set decode type 3
05-07 13:13:06.627   428 23065 I MtkV4L2Device: [0xaca83d1c] BSQFlushing(1), FBQFlushing(0), BSQFlushDone(0), FBQFlushDone(0)
05-07 13:13:06.627   428 23065 I chatty  : uid=1046(mediacodec) MtkOmxVdecDecod identical 2 lines
05-07 13:13:06.627   428 23065 I MtkV4L2Device: [0xaca83d1c] BSQFlushing(1), FBQFlushing(0), BSQFlushDone(0), FBQFlushDone(0)
05-07 13:13:06.628   428 23064 I MtkOmxVdecExV4L2: [0xaca83ac0] --- FTBQ: mNumPendingOutput 0; mFillThisBufQ.size() 0,  CCDst: 0, CCSrc: 0
05-07 13:13:06.629   428 23064 I MtkOmxVdecExV4L2: [0xaca83ac0] + Wait FB flush done, wait mFlushFrameBufferDoneSem, mDecoderInitCompleteFlag(1), queuedFrameBufferCount(0), mFlushFBInProcess(1)
05-07 13:13:06.629   448   495 I VCodecDrv: phHandle->fgOutputEarly 0
05-07 13:13:06.629   448   495 I VdecLatCore: [eVLatSetDecodeType] set decode type 3
05-07 13:13:06.630   428 23064 I MtkOmxVdecExV4L2: [0xaca83ac0] - Wait FB flush done, mFlushFrameBufferDoneSem 0
05-07 13:13:06.630   428 23064 I MtkOmxVdecExV4L2: [0xaca83ac0] -FlushOutputPort -> mNumPendingOutput(0)
05-07 13:13:06.632   567  2098 W BestClock: java.time.DateTimeException: Missing NTP fix
05-07 13:13:06.633   428 23064 I MtkOmxVdecExV4L2: [0xaca83ac0] --- ETBQ: mNumPendingInput 0; mEmptyThisBufQ.size() 0
05-07 13:13:06.633   448   495 I VCodecDrv: phHandle->fgOutputEarly 0
05-07 13:13:06.633   448   495 I VdecLatCore: [eVLatSetDecodeType] set decode type 3
05-07 13:13:06.634   428 23064 I MtkOmxVdecExV4L2: [0xaca83ac0] --- FTBQ: mNumPendingOutput 11; mFillThisBufQ.size() 10,  CCDst: 0, CCSrc: 0
05-07 13:13:06.634   428 23064 I MtkOmxVdecExV4L2: [0xaca83ac0] + Wait FB flush done, wait mFlushFrameBufferDoneSem, mDecoderInitCompleteFlag(1), queuedFrameBufferCount(1), mFlushFBInProcess(1)
05-07 13:13:06.634   448   495 I VCodecDrv: phHandle->fgOutputEarly 0
05-07 13:13:06.634   448   495 I VdecLatCore: [eVLatSetDecodeType] set decode type 3
05-07 13:13:06.635   428 23064 I MtkOmxVdecExV4L2: [0xaca83ac0] - Wait FB flush done, mFlushFrameBufferDoneSem 0
05-07 13:13:06.635   428 23064 I MtkOmxVdecExV4L2: [0xaca83ac0] -FlushOutputPort -> mNumPendingOutput(0)
05-07 13:13:06.635 15247 15440 W StreamHAL: Error from HAL stream in function write: Function not implemented
05-07 13:13:06.635 15248 15263 E AudioStreamOutSink: Error while writing data to HAL: -38
05-07 13:13:06.641   428  7481 I MtkOmxVdecExV4L2: [0xaca83ac0] MtkOmxVdec::FreeBuffer all output buffers have been freed!!! signal mOutPortFreeDoneSem(1)
05-07 13:13:06.642   428  7481 D MtkOmxCore: Mtk_OMX_FreeHandle
05-07 13:13:06.642   428  7481 I MtkOmxVdecExV4L2: [0xaca83ac0] +MtkOmxVdec::ComponentDeInit
05-07 13:13:06.642   428  7481 E MtkV4L2Device: [0xaca83d1c] [setDevicePollInterrupt] write sueeeed...
05-07 13:13:06.642   428 23067 E MtkOmxVdecExV4L2: [0xaca83ac0] MtkOmxVdecPollThread pVdec->mIsComponentAlive = FALSE. break
05-07 13:13:06.642   428 23064 E MtkOmxVdecExV4L2: [0xaca83ac0] [0xaca83ac0] MtkOmxVdecThread terminated. CmdSize:0
05-07 13:13:06.642   428 23067 E MtkOmxVdecExV4L2: [0xaca83ac0] [0xaca83ac0] MtkOmxVdecPollThread terminated pVdec=0xACA83AC0
05-07 13:13:06.642   428 23066 E MtkOmxVdecExV4L2: [0xaca83ac0] MtkOmxVdecConvertThread terminated. CmdSize:0
05-07 13:13:06.644 15247 15440 W StreamHAL: Error from HAL stream in function write: Function not implemented
05-07 13:13:06.644 15248 15263 E AudioStreamOutSink: Error while writing data to HAL: -38
05-07 13:13:06.647   428 23065 E MtkOmxVdecExV4L2: [0xaca83ac0] [0xaca83ac0] MtkOmxVdecDecodeThread terminated pVdec=0xACA83AC0
```
```


### FFmpeg logs

```shell
Played on device.
```

### Application version

0.13.4

### Device information

AMZN Firestick Max

### Android version

retail

### Jellyfin server version

retail

**Comment by mueslimak3r** [comment]
Please complete the issue template with the media info of one of the videos that this issue occurs with.

Please upload the entire app log as a file so it can be downloaded. The snippet you included is helpful but a full log is even more useful

Also, server logs + ffmpeg logs if applicable would be helpful

**Comment by KyleSanderson** [comment]
> Please complete the issue template with the media info of one of the videos that this issue occurs with.
> 
> Please upload the entire app log as a file so it can be downloaded. The snippet you included is helpful but a full log is even more useful
> 
> Also, server logs + ffmpeg logs if applicable would be helpful

It's 100% related to mode switching - it doesn't happen when it's disabled. Playback should kick off when the HDMI device is available to Android.

**Comment by mueslimak3r** [comment]
> > Please complete the issue template with the media info of one of the videos that this issue occurs with.
> > 
> > Please upload the entire app log as a file so it can be downloaded. The snippet you included is helpful but a full log is even more useful
> > 
> > Also, server logs + ffmpeg logs if applicable would be helpful
> 
> It's 100% related to mode switching - it doesn't happen when it's disabled. Playback should kick off when the HDMI device is available to Android.

If you'd like to fix this feel free to open a PR. Otherwise, the additional information mentioned above will be helpful

**Comment by mueslimak3r** [comment]
User provided some additional details on matrix:

> it's very obvious now that it's the panel mode switching (which is what is desired), which resets the HDMI connection and that's why Jellyfin is dropping out because it starts working on Audio immediately after Video. Why am I being asked for mediainfo dumps of files when that's not the STR. It's literally all media that's not the native resolution or refresh rate of the panel, and when that option is disabled, it does not happen. Kicking into HDR modes also triggers the reset on my specific panel.

**Comment by mueslimak3r** [comment]
In addition to what has already been mentioned, please update the issue with the jellyfin server version

**Comment by KyleSanderson** [comment]
> In addition to what has already been mentioned, please update the issue with the jellyfin server version

Can you provide complete quotes if you're only going to take snippets? This has nothing to do with transcoding, and as Jellyfin has hard coded versions it's compatible with it boxes the versions in as well.

Again, if I personally offended you with the other major regression I apologize but these are significant UX issues that reset playback completely / etc. If there's anything of value I can provide I'm beyond willing to help with value asks.

Are we able to have a real conversation?

**Comment by KyleSanderson** [comment]
cc @nielsvanvelzen

**Comment by thornbill** [comment]
@KyleSanderson you have a volunteer here going out of their way to try and help you with your issue. They requested information from you and you don't seem to be providing it.

I'm not entirely sure why you are pinging other maintainers or what you hope to accomplish by doing so, but it's completely unnecessary.

**Comment by KyleSanderson** [comment]
Last piece of missing information is this only happens with Exoplayer, libVLC does not show the error UX.

**Comment by baburam0007** [comment]
I am encountering the same issue.

**Comment by mueslimak3r** [comment]
> I am encountering the same issue.

Can you provide the missing details?

I'm waiting on some additional information before looking at the code.

**Comment by KyleSanderson** [comment]
Thank you for looking at this. I've returned to Kodi and will be unable to provide further information as my jellyfin instances have been spun down. I wish you great luck with making this a mature product and I'm sure our paths will cross in the future.
