### ISSUE TITLE
Intro skipper plugin incompatible with the API (plugin issue)

### ISSUE THREAD

**Issue by sourpatched** [jellyfin/jellyfin-androidtv#1853]
### Describe the bug

Item starts playing then the app crashes
item is AVI 

### Logs

---
client: Jellyfin for Android TV
client_version: 0.14.0-beta.1
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected 'null' when string was expected
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.asLiteral(TreeJsonDecoder.kt:161)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeTaggedString(TreeJsonDecoder.kt:151)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeTaggedString(TreeJsonDecoder.kt:35)
	at kotlinx.serialization.internal.TaggedDecoder.decodeString(Tagged.kt:231)
	at kotlinx.serialization.internal.StringSerializer.deserialize(Primitives.kt:142)
	at kotlinx.serialization.internal.StringSerializer.deserialize(Primitives.kt:138)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:537)
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:111)
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:84)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
	at org.jellyfin.sdk.model.socket.GeneralCommandMessage$$serializer.deserialize(GeneralCommandMessage.kt:12)
	at org.jellyfin.sdk.model.socket.GeneralCommandMessage$$serializer.deserialize(GeneralCommandMessage.kt:12)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
	at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:24)
	at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:119)
	at org.jellyfin.sdk.api.client.util.ApiSerializer.decodeSocketMessage(ApiSerializer.kt:94)
	at org.jellyfin.sdk.api.sockets.SocketInstance.forwardMessage(SocketInstance.kt:280)
	at org.jellyfin.sdk.api.sockets.SocketInstance.access$forwardMessage(SocketInstance.kt:35)
	at org.jellyfin.sdk.api.sockets.SocketInstance$connectAndBind$2.invokeSuspend(SocketInstance.kt:220)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b36ecf6, Dispatchers.Default]

  
***Logcat***: 
```log
--------- beginning of main
07-17 18:55:44.831 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 1 line
07-17 18:55:44.834 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 1 line
07-17 18:55:51.674 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 26 lines
07-17 18:55:51.758 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 10 lines
07-17 18:55:51.810 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 76 lines
07-17 18:55:52.182 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 2 lines
07-17 18:55:52.272 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 1 line
07-17 18:55:54.868 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 8 lines
07-17 18:55:54.870 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 10 lines
07-17 18:55:54.887 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 4 lines
07-17 18:55:54.898 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 3 lines
07-17 18:55:54.912 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 2 lines
07-17 18:56:01.900 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 10 lines
07-17 18:56:01.902 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 5 lines
07-17 18:56:01.902 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 4 lines
07-17 18:56:01.903 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 6 lines
07-17 18:56:01.971 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 6 lines
07-17 18:56:01.973 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 6 lines
07-17 18:56:01.974 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 4 lines
07-17 18:56:01.974 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 2 lines
07-17 18:56:01.978 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 2 lines
07-17 18:56:01.978 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 4 lines
07-17 18:56:02.031 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 8 lines
07-17 18:56:02.129 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 6 lines
07-17 18:56:02.137 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 4 lines
07-17 18:56:02.167 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 1 line
07-17 18:56:02.540 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 8 lines
07-17 18:56:02.566 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 5 lines
07-17 18:56:02.566 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 2 lines
07-17 18:56:02.567 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 8 lines
07-17 18:56:02.574 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 9 lines
07-17 18:56:04.819 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 1 line
07-17 18:56:05.931 I/chatty  ( 6754): uid=10102(org.jellyfin.androidtv) expire 16 lines
07-17 18:56:06.010 I/chatty  ( 7270): uid=10102 org.jellyfin.androidtv:acra expire 7 lines
07-17 18:56:06.078 I/chatty  ( 7270): uid=10102 org.jellyfin.androidtv:acra expire 12 lines
07-17 18:56:44.818 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) expire 51 lines
07-17 18:56:45.167 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) expire 3 lines
07-17 18:56:45.182 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) RenderThread expire 108 lines
07-17 18:56:45.378 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) expire 63 lines
07-17 18:56:45.582 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) DefaultDispatch expire 7 lines
07-17 18:56:45.591 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) DefaultDispatch expire 4 lines
07-17 18:56:45.606 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) .local:8096/... expire 3 lines
07-17 18:56:45.646 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) DefaultDispatch expire 5 lines
07-17 18:56:45.883 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) RenderThread expire 5 lines
07-17 18:56:45.940 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) DefaultDispatch expire 2 lines
07-17 18:56:46.914 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) FinalizerDaemon expire 4 lines
07-17 18:56:47.319 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) WM.task-3 expire 1 line
07-17 18:56:47.980 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) HeapTaskDaemon expire 1 line
07-17 18:56:48.135 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) expire 34 lines
07-17 18:56:50.199 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) RenderThread expire 4 lines
07-17 18:56:50.242 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) expire 112 lines
07-17 18:56:50.622 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) RenderThread expire 5 lines
07-17 18:56:51.980 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) HeapTaskDaemon expire 1 line
07-17 18:56:52.132 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) expire 7 lines
07-17 18:56:52.424 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) RenderThread expire 1 line
07-17 18:56:52.428 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) expire 2 lines
07-17 18:56:52.725 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) ExoPlayer:Playb expire 1 line
07-17 18:56:52.726 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) .local:8096/... expire 1 line
07-17 18:56:52.733 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) CodecLooper expire 1 line
07-17 18:56:52.738 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) ExoPlayer:Playb expire 3 lines
07-17 18:56:52.742 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) MediaCodec_loop expire 4 lines
07-17 18:56:52.754 I/ACodec  ( 7303): Enable timestamp filtering for Video Decoder
07-17 18:56:52.754 I/ACodec  ( 7303): Get OMX_IndexConfigScale: 0x10000/0x10000
07-17 18:56:52.754 I/ACodec  ( 7303): Scaled Width is 624, height is 352
07-17 18:56:52.765 D/SurfaceUtils( 7303): set up nativeWindow 0x45465c98 for 624x352, color 0x106, rotation 0, usage 0x2900
07-17 18:56:52.773 I/ACodec  ( 7303): Get OMX_IndexConfigScale: 0x10000/0x10000
07-17 18:56:52.773 I/ACodec  ( 7303): Scaled Width is 624, height is 352
07-17 18:56:52.773 I/android_os_HwBinder( 7303): HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
07-17 18:56:52.775 D/SurfaceUtils( 7303): set up nativeWindow 0x45465c98 for 624x352, color 0x146, rotation 0, usage 0x2900
07-17 18:56:52.776 I/OMXClient( 7303): IOmx service obtained
07-17 18:56:52.778 I/android_os_HwBinder( 7303): HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
07-17 18:56:52.780 I/chatty  ( 7303): uid=10102(org.jellyfin.androidtv) ExoPlayer:Playb identical 1 line
07-17 18:56:52.782 I/android_os_HwBinder( 7303): HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
07-17 18:56:52.784 I/ACodec  ( 7303): Get OMX_IndexConfigScale: 0x10000/0x10000
07-17 18:56:52.784 I/ACodec  ( 7303): Scaled Width is 624, height is 352
07-17 18:56:52.784 I/ACodec  ( 7303): codec does not support config priority (err -2147483648)
07-17 18:56:52.887 D/jellyfin-apiclient( 7303): Adding request to queue: http://Ip:8096/Sessions/Playing/Progress
07-17 18:56:52.888 I/PlaybackController( 7303): Play method: Trans
07-17 18:56:52.889 I/PlaybackController( 7303): Turning off subs
07-17 18:56:52.889 D/PlaybackController( 7303): Setting subtitle index to: -1
07-17 18:56:52.890 D/PlaybackController( 7303): trying to switch audio stream from 1 to 1
07-17 18:56:52.891 D/PlaybackController( 7303): skipping setting audio stream, already set to requested index 1
07-17 18:56:52.891 D/PlaybackController( 7303): setting mCurrentOptions audio stream index from null to 1
07-17 18:56:53.005 I/jellyfin-apiclient( 7303): Response received from: http://Ip:8096/Sessions/Playing/Progress
07-17 18:56:55.889 D/jellyfin-apiclient( 7303): Adding request to queue: http://Ip:8096/Sessions/Playing/Progress
07-17 18:56:55.995 I/jellyfin-apiclient( 7303): Response received from: http://Ip:8096/Sessions/Playing/Progress
07-17 18:56:58.894 D/jellyfin-apiclient( 7303): Adding request to queue: http://Ip:8096/Sessions/Playing/Progress
07-17 18:56:59.045 I/jellyfin-apiclient( 7303): Response received from: http://Ip:8096/Sessions/Playing/Progress
07-17 18:56:59.831 I/OkHttpWebsocketSession( 7303): Receiving (raw) message {"MessageType":"GeneralCommand","MessageId":"75595d22b20d402b9a7ff5e0e7d0cbdb","Data":{"Name":"DisplayMessage","ControllingUserId":"00000000000000000000000000000000","Arguments":{"Header":null,"Text":"Automatically skipped intro","TimeoutMs":"2000"}}}
07-17 18:56:59.832 I/OkHttpWebsocketSession( 7303): Receiving (raw) message {"MessageType":"Playstate","MessageId":"efe7b109bcb64319bc8fc34d0e57f8e8","Data":{"Command":"Seek","SeekPositionTicks":380000000,"ControllingUserId":"f0c73868f5a1416db050ef6e068677af"}}
07-17 18:56:59.838 E/ACRA    ( 7303): ACRA caught a JsonDecodingException for org.jellyfin.androidtv
07-17 18:56:59.838 E/ACRA    ( 7303): kotlinx.serialization.json.internal.JsonDecodingException: Unexpected 'null' when string was expected
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.asLiteral(TreeJsonDecoder.kt:161)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeTaggedString(TreeJsonDecoder.kt:151)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeTaggedString(TreeJsonDecoder.kt:35)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.internal.TaggedDecoder.decodeString(Tagged.kt:231)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.internal.StringSerializer.deserialize(Primitives.kt:142)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.internal.StringSerializer.deserialize(Primitives.kt:138)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:537)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:111)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:84)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at org.jellyfin.sdk.model.socket.GeneralCommandMessage$$serializer.deserialize(GeneralCommandMessage.kt:12)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at org.jellyfin.sdk.model.socket.GeneralCommandMessage$$serializer.deserialize(GeneralCommandMessage.kt:12)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:24)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:119)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at org.jellyfin.sdk.api.client.util.ApiSerializer.decodeSocketMessage(ApiSerializer.kt:94)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at org.jellyfin.sdk.api.sockets.SocketInstance.forwardMessage(SocketInstance.kt:280)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at org.jellyfin.sdk.api.sockets.SocketInstance.access$forwardMessage(SocketInstance.kt:35)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at org.jellyfin.sdk.api.sockets.SocketInstance$connectAndBind$2.invokeSuspend(SocketInstance.kt:220)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
07-17 18:56:59.838 E/ACRA    ( 7303): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
07-17 18:56:59.839 E/ACRA    ( 7303): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
07-17 18:56:59.839 E/ACRA    ( 7303): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b36ecf6, Dispatchers.Default]
07-17 18:56:59.839 D/ACRA    ( 7303): Building report
07-17 18:56:59.839 D/ACRA    ( 7303): Starting collectors with priority FIRST
07-17 18:56:59.840 D/ACRA    ( 7303): Calling collector org.acra.collector.DropBoxCollector
07-17 18:56:59.841 D/ACRA    ( 7303): Calling collector org.acra.collector.StacktraceCollector
07-17 18:56:59.841 D/ACRA    ( 7303): Collector org.acra.collector.DropBoxCollector completed
07-17 18:56:59.841 D/ACRA    ( 7303): Collector org.acra.collector.StacktraceCollector completed
07-17 18:56:59.841 D/ACRA    ( 7303): Calling collector org.acra.collector.LogCatCollector
07-17 18:56:59.844 D/ACRA    ( 7303): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.14.0-beta.1` (`140001`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"sif","BOOTLOADER":"32.00.2019.50-t210-69ebfcbe","BRAND":"NVIDIA","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"sif","DISPLAY":"RQ1A.210105.003.7094503_2971.7725","FINGERPRINT":"NVIDIA\/sif\/sif:11\/RQ1A.210105.003\/7094503_2971.7725:user\/release-keys","HARDWARE":"sif","HOST":"mobile-u64-5330-d8000","ID":"RQ1A.210105.003","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"NVIDIA","MODEL":"SHIELD Android TV","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"sif","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1644045918000,"TYPE":"user","UNKNOWN":"unknown","USER":"NVIDIA","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"7094503_2971.7725","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"11","RELEASE_OR_CODENAME":"11","SDK":"30","SDK_INT":30,"SECURITY_PATCH":"2022-01-05"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":140001,"VERSION_NAME":"0.14.0-beta.1"}
```  

### Device information

***Android version***: `11`  
***Device brand***: `NVIDIA`  
***Device product***: `sif`  
***Device model***: `SHIELD Android TV`  

### Crash information

***Start time***: `2022-07-17T18:56:44.923+8:00`  
***Crash time***: `2022-07-17T18:56:59.918+8:00`

### Application version

0.14

### Where did you install the app from?

Sideloaded APK

### Device information

SHIELD Android TV

### Android version

Android 11

### Jellyfin server version

10.8.1

**Comment by nielsvanvelzen** [comment]
Looks like a plugin you're using sends messages that are incompatible with the API. You should report this bug to the plugin that sends the "Automatically skipped intro" message.

The "header" argument is currently set to null but should be omitted.

**Comment by sourpatched** [comment]
That explains it as I've just played it on the web and it skipped intro but on the app it always crashes at the same point. I'll open the issue and link this one as well.

Thanks for another packed update.

**Comment by nielsvanvelzen** [comment]
Likely this issue: https://github.com/ConfusedPolarBear/intro-skipper/issues/15

**Comment by sourpatched** [comment]
> Likely this issue: [ConfusedPolarBear/intro-skipper#15](https://github.com/ConfusedPolarBear/intro-skipper/issues/15)

I am aware of that issue, The app was working with the plugin before update so one would think that something in the update changed.

**Comment by mueslimak3r** [comment]
This is fixed already in the intro skip plugin. There just hasn't been a new version released since it was fixed. See:

https://github.com/ConfusedPolarBear/intro-skipper/issues/15#issuecomment-1159441406

https://github.com/ConfusedPolarBear/intro-skipper/commit/1ca7a9ec863ab30f9b6a4b71b7019b166ebdf9c2

**Comment by sourpatched** [comment]
@mueslimak3r Your already on top of things, I'll leave this open in case others have the same issue and will close when that plugin is updated.

**Comment by sourpatched** [comment]
Plugin has been updated and is working now with this app.

**Comment by nielsvanvelzen** [comment]
I don't think any websocket code changed this time, is the app crashing again due to the plugin?

**Comment by nielsvanvelzen** [comment]
I'll need client logs to see what's happening. I can't do much with servers logs unfortunately.
