### ISSUE TITLE
AndroidTV client crashes immediately upon login

### ISSUE THREAD

**Issue by Bobechang** [jellyfin/jellyfin-androidtv#1889]
### Describe the bug

1. input id/pw, pressing login in client
2. client crashes in few sec.
3.  i see nothing

i have tested the client v0.12.0/0.12.3/0.13.0/0.13.7/0.14.0 beta1/beta2. they all crash.
the jellyfin server is from here https://www.qnapclub.eu/en/qpkg/693. if it's necessary, i can send you a copy.

### Logs

---
client: Jellyfin for Android TV
client_version: 0.14.0-beta.2
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.NoSuchMethodError: No interface method addListener(Ljava/lang/Runnable;Ljava/util/concurrent/Executor;)V in class Lcom/google/common/util/concurrent/ListenableFuture; or its super classes (declaration of 'com.google.common.util.concurrent.ListenableFuture' appears in /system/framework/libsetting.jar)
	at org.jellyfin.androidtv.JellyfinApplication$onSessionStart$2$1.invokeSuspend(JellyfinApplication.kt:120)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ba4bded, Dispatchers.Main.immediate]

```  
***Logcat***: 
```log
--------- beginning of main
07-24 00:47:08.199 E/KtorClient(24571): 	at io.ktor.client.HttpClient.execute(HttpClient.kt:191)
07-24 00:47:08.199 E/KtorClient(24571): 	at io.ktor.client.statement.HttpStatement.executeUnsafe(HttpStatement.kt:104)
07-24 00:47:08.199 E/KtorClient(24571): 	at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:43)
07-24 00:47:08.199 E/KtorClient(24571): 	at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:58)
07-24 00:47:08.199 E/KtorClient(24571): 	at org.jellyfin.sdk.api.client.KtorClient.request$suspendImpl(KtorClient.kt:149)
07-24 00:47:08.199 E/KtorClient(24571): 	at org.jellyfin.sdk.api.client.KtorClient.request(Unknown Source:0)
07-24 00:47:08.199 E/KtorClient(24571): 	at org.jellyfin.sdk.api.operations.SessionApi.postCapabilities(SessionApi.kt:514)
07-24 00:47:08.199 E/KtorClient(24571): 	at org.jellyfin.sdk.api.operations.SessionApi.postCapabilities$default(SessionApi.kt:179)
07-24 00:47:08.199 E/KtorClient(24571): 	at org.jellyfin.androidtv.data.eventhandling.SocketHandler.updateSession(SocketHandler.kt:46)
07-24 00:47:08.199 E/KtorClient(24571): 	at org.jellyfin.androidtv.JellyfinApplication$onSessionStart$2$2.invokeSuspend(JellyfinApplication.kt:88)
07-24 00:47:08.199 E/KtorClient(24571): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07-24 00:47:08.199 E/KtorClient(24571): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
07-24 00:47:08.199 E/KtorClient(24571): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
07-24 00:47:08.199 E/KtorClient(24571): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
07-24 00:47:08.199 E/KtorClient(24571): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
07-24 00:47:08.199 E/KtorClient(24571): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
07-24 00:47:08.199 E/KtorClient(24571): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
07-24 00:47:08.199 E/KtorClient(24571): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
07-24 00:47:08.211 E/SocketHandler(24571): Unable to update capabilities
07-24 00:47:08.211 E/SocketHandler(24571): org.jellyfin.sdk.api.client.exception.ApiClientException: Unknown error occurred!
07-24 00:47:08.211 E/SocketHandler(24571): 	at org.jellyfin.sdk.api.client.KtorClient.request$suspendImpl(KtorClient.kt:128)
07-24 00:47:08.211 E/SocketHandler(24571): 	at org.jellyfin.sdk.api.client.KtorClient$request$1.invokeSuspend(Unknown Source:19)
07-24 00:47:08.211 E/SocketHandler(24571): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07-24 00:47:08.211 E/SocketHandler(24571): 	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:194)
07-24 00:47:08.211 E/SocketHandler(24571): 	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:15)
07-24 00:47:08.211 E/SocketHandler(24571): 	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:89)
07-24 00:47:08.211 E/SocketHandler(24571): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
07-24 00:47:08.211 E/SocketHandler(24571): 	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:194)
07-24 00:47:08.211 E/SocketHandler(24571): 	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:15)
07-24 00:47:08.211 E/SocketHandler(24571): 	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:89)
07-24 00:47:08.212 E/SocketHandler(24571): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:194)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:15)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:89)
07-24 00:47:08.212 E/SocketHandler(24571): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:194)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:165)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:78)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.client.features.HttpSend$DefaultSender.execute(HttpSend.kt:128)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:89)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.client.features.HttpSend$Feature$install$1.invoke(Unknown Source:15)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.client.features.HttpSend$Feature$install$1.invoke(Unknown Source:4)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:126)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.client.features.HttpCallValidator$Companion$install$1.invokeSuspend(HttpCallValidator.kt:112)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.client.features.HttpCallValidator$Companion$install$1.invoke(Unknown Source:13)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.client.features.HttpCallValidator$Companion$install$1.invoke(Unknown Source:4)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.client.features.HttpRequestLifecycle$Feature$install$1.invokeSuspend(HttpRequestLifecycle.kt:37)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.client.features.HttpRequestLifecycle$Feature$install$1.invoke(Unknown Source:11)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.client.features.HttpRequestLifecycle$Feature$install$1.invoke(Unknown Source:4)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:78)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.client.HttpClient.execute(HttpClient.kt:191)
07-24 00:47:08.212 E/SocketHandler(24571): 	at io.ktor.client.statement.HttpStatement.executeUnsafe(HttpStatement.kt:104)
07-24 00:47:08.213 E/SocketHandler(24571): 	at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:43)
07-24 00:47:08.213 E/SocketHandler(24571): 	at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:58)
07-24 00:47:08.213 E/SocketHandler(24571): 	at org.jellyfin.sdk.api.client.KtorClient.request$suspendImpl(KtorClient.kt:149)
07-24 00:47:08.213 E/SocketHandler(24571): 	at org.jellyfin.sdk.api.client.KtorClient.request(Unknown Source:0)
07-24 00:47:08.213 E/SocketHandler(24571): 	at org.jellyfin.sdk.api.operations.SessionApi.postCapabilities(SessionApi.kt:514)
07-24 00:47:08.213 E/SocketHandler(24571): 	at org.jellyfin.sdk.api.operations.SessionApi.postCapabilities$default(SessionApi.kt:179)
07-24 00:47:08.213 E/SocketHandler(24571): 	at org.jellyfin.androidtv.data.eventhandling.SocketHandler.updateSession(SocketHandler.kt:46)
07-24 00:47:08.213 E/SocketHandler(24571): 	at org.jellyfin.androidtv.JellyfinApplication$onSessionStart$2$2.invokeSuspend(JellyfinApplication.kt:88)
07-24 00:47:08.213 E/SocketHandler(24571): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07-24 00:47:08.213 E/SocketHandler(24571): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
07-24 00:47:08.213 E/SocketHandler(24571): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
07-24 00:47:08.213 E/SocketHandler(24571): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
07-24 00:47:08.213 E/SocketHandler(24571): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
07-24 00:47:08.213 E/SocketHandler(24571): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
07-24 00:47:08.216 E/SocketHandler(24571): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
07-24 00:47:08.216 E/SocketHandler(24571): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
07-24 00:47:08.216 E/SocketHandler(24571): Caused by: java.util.concurrent.CancellationException: Parent job is Cancelling
07-24 00:47:08.216 E/SocketHandler(24571): 	at io.ktor.client.engine.UtilsKt$attachToUserJob$cleanupHandler$1.invoke(Utils.kt:78)
07-24 00:47:08.216 E/SocketHandler(24571): 	at io.ktor.client.engine.UtilsKt$attachToUserJob$cleanupHandler$1.invoke(Utils.kt:76)
07-24 00:47:08.217 E/SocketHandler(24571): 	at kotlinx.coroutines.JobSupport.invokeOnCompletion(JobSupport.kt:1548)
07-24 00:47:08.217 E/SocketHandler(24571): 	at kotlinx.coroutines.Job$DefaultImpls.invokeOnCompletion$default(Job.kt:341)
07-24 00:47:08.217 E/SocketHandler(24571): 	at io.ktor.client.engine.HttpClientEngineJvmKt.createCallContext(HttpClientEngineJvm.kt:26)
07-24 00:47:08.217 E/SocketHandler(24571): 	at io.ktor.client.engine.HttpClientEngine$DefaultImpls.executeWithinCallContext(HttpClientEngine.kt:76)
07-24 00:47:08.217 E/SocketHandler(24571): 	at io.ktor.client.engine.HttpClientEngine$DefaultImpls.access$executeWithinCallContext(HttpClientEngine.kt:25)
07-24 00:47:08.217 E/SocketHandler(24571): 	at io.ktor.client.engine.HttpClientEngine$install$1.invokeSuspend(HttpClientEngine.kt:65)
07-24 00:47:08.217 E/SocketHandler(24571): 	at io.ktor.client.engine.HttpClientEngine$install$1.invoke(Unknown Source:15)
07-24 00:47:08.217 E/SocketHandler(24571): 	at io.ktor.client.engine.HttpClientEngine$install$1.invoke(Unknown Source:4)
07-24 00:47:08.217 E/SocketHandler(24571): 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
07-24 00:47:08.217 E/SocketHandler(24571): 	... 40 more
07-24 00:47:08.285 E/ACRA    (24571): ACRA caught a NoSuchMethodError for org.jellyfin.androidtv.debug
07-24 00:47:08.285 E/ACRA    (24571): java.lang.NoSuchMethodError: No interface method addListener(Ljava/lang/Runnable;Ljava/util/concurrent/Executor;)V in class Lcom/google/common/util/concurrent/ListenableFuture; or its super classes (declaration of 'com.google.common.util.concurrent.ListenableFuture' appears in /system/framework/libsetting.jar)
07-24 00:47:08.285 E/ACRA    (24571): 	at org.jellyfin.androidtv.JellyfinApplication$onSessionStart$2$1.invokeSuspend(JellyfinApplication.kt:120)
07-24 00:47:08.285 E/ACRA    (24571): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07-24 00:47:08.285 E/ACRA    (24571): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
07-24 00:47:08.285 E/ACRA    (24571): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
07-24 00:47:08.285 E/ACRA    (24571): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
07-24 00:47:08.285 E/ACRA    (24571): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
07-24 00:47:08.285 E/ACRA    (24571): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
07-24 00:47:08.285 E/ACRA    (24571): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
07-24 00:47:08.285 E/ACRA    (24571): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
07-24 00:47:08.285 E/ACRA    (24571): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ba4bded, Dispatchers.Main.immediate]
07-24 00:47:08.286 D/ACRA    (24571): Building report
07-24 00:47:08.291 D/ACRA    (24571): Starting collectors with priority FIRST
07-24 00:47:08.294 D/ACRA    (24571): Calling collector org.acra.collector.DropBoxCollector
07-24 00:47:08.294 D/ACRA    (24571): Collector org.acra.collector.DropBoxCollector completed
07-24 00:47:08.294 D/ACRA    (24571): Calling collector org.acra.collector.LogCatCollector
07-24 00:47:08.295 D/ACRA    (24571): Calling collector org.acra.collector.StacktraceCollector
07-24 00:47:08.297 D/ACRA    (24571): Collector org.acra.collector.StacktraceCollector completed
07-24 00:47:08.299 D/ACRA    (24571): Retrieving logcat output (buffer:default)...
07-24 00:47:08.305 I/OkHttpWebsocketSession(24571): Receiving (raw) message {"MessageType":"ForceKeepAlive","MessageId":"00000000000000000000000000000000","Data":60}

```  

### App information

***App version***: `0.14.0-beta.2` (`140002`)  
***Package name***: `org.jellyfin.androidtv.debug`  
***Build***: 
```json
{"BOARD":"exdroid","BOOTLOADER":"unknown","BRAND":"MagicBox_M_30_E","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"MagicBox_M_30_E","DISPLAY":"QP1A.191105.004 test-keys","FINGERPRINT":"MagicBox_M_30_E\/MagicBox_M_30_E\/MagicBox_M_30_E:10.0.1-RS-20220401.2133\/QP1A.191105.004\/eng.admin.20220401.205803:user\/test-keys","HARDWARE":"sun50iw9p1","HOST":"78fc30a4c51d","ID":"QP1A.191105.004","IS_DEBUGGABLE":true,"IS_EMULATOR":false,"MANUFACTURER":"Tmall","MODEL":"MagicBox_M_30_E","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"MagicBox_M_30_E","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"test-keys","TIME":1648817817000,"TYPE":"user","UNKNOWN":"unknown","USER":"admin","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","FIRST_SDK_INT":29,"INCREMENTAL":"eng.admin.20220401.205803","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"10.0.1-RS-20220401.2133","RESOURCES_SDK_INT":29,"SDK":"29","SDK_INT":29,"SECURITY_PATCH":"2019-12-05"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv.debug","BUILD_TYPE":"debug","DEBUG":true,"DEVELOPMENT":false,"VERSION_CODE":140002,"VERSION_NAME":"0.14.0-beta.2"}
```  

### Device information

***Android version***: `10.0.1-RS-20220401.2133`  
***Device brand***: `MagicBox_M_30_E`  
***Device product***: `MagicBox_M_30_E`  
***Device model***: `MagicBox_M_30_E`  

### Crash information

***Start time***: `2022-07-24T00:47:04.451+08:00`  
***Crash time***: `2022-07-24T00:47:08.437+08:00`  

### Application version

0.14.0-beta.2

### Device information

Tmall magic box/M13

### Android version

custom ROM

### Jellyfin server version

10.8.1

**Comment by nielsvanvelzen** [comment]
This is a really weird error, my best guess is an issue in the operating system. Did you test the app on  other devices?

**Comment by Bobechang** [comment]
> This is a really weird error, my best guess is an issue in the operating system. Did you test the app on other devices?

no, I have one android tv dev only

**Comment by Bobechang** [comment]
After crash, if I modify the password and relaunch the client, the login page will be show

**Comment by nielsvanvelzen** [comment]
I've found one bug related to this bug report but I'm not entirely sure if it fixes the actual issue. This issue might auto-close after merging but if the issue persists after the next update please comment here so we can re-open the issue.
