### ISSUE TITLE
App crash when resuming

### ISSUE THREAD

**Issue by krutburken** [jellyfin/jellyfin-androidtv#1903]
### Describe the bug

Not referring to resuming playback, just normal browsing in the app.

Maybe dupe of #1859

1: Log in to app as usual, enter home screen
2: Browse to an item (a movie for example)
3: Wait approx 5-10 minutes on the item details screen (idle)
4: Try to use the app and watch it crash

Not sure exactly how much idle time is necessary, but the crash is easily recreated like this. I think it did this before beta2 as well, but I never bothered to get the crash logs. Very helpful that the app is now logging to the server!

### Logs

```log
java.lang.RuntimeException: Unable to resume activity {org.jellyfin.androidtv/org.jellyfin.androidtv.ui.browsing.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.UUID org.jellyfin.sdk.model.api.UserDto.getId()' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4205)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.UUID org.jellyfin.sdk.model.api.UserDto.getId()' on a null object reference
	at org.jellyfin.androidtv.ui.itemhandling.BaseRowItem.refresh(BaseRowItem.java:496)
	at org.jellyfin.androidtv.ui.browsing.StdRowsFragment.refreshCurrentItem(StdRowsFragment.java:216)
	at org.jellyfin.androidtv.ui.browsing.StdRowsFragment.onResume(StdRowsFragment.java:89)
	at org.jellyfin.androidtv.ui.home.HomeFragment.onResume(HomeFragment.kt:69)
	at androidx.fragment.app.Fragment.performResume(Fragment.java:3180)
	at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:606)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1424)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2968)
	at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2900)
	at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:285)
	at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:334)
	at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:323)
	at android.app.Activity.performResume(Activity.java:7979)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
	... 11 more
```  
Another:
```log
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.UUID org.jellyfin.sdk.model.api.UserDto.getId()' on a null object reference
	at org.jellyfin.androidtv.ui.itemhandling.BaseRowItem.refresh(BaseRowItem.java:496)
	at org.jellyfin.androidtv.ui.browsing.StdGridFragment.refreshCurrentItem(StdGridFragment.java:754)
	at org.jellyfin.androidtv.ui.browsing.StdGridFragment.lambda$onResume$0$org-jellyfin-androidtv-ui-browsing-StdGridFragment(StdGridFragment.java:429)
	at org.jellyfin.androidtv.ui.browsing.StdGridFragment$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```  

### Application version

0.14.0-beta2

### Where did you install the app from?

Google Play

### Device information

Google TV

### Android version

Not sure. Can check later

### Jellyfin server version

10.8.1

**Comment by nielsvanvelzen** [comment]
Can you post the full crash report file?
