### ISSUE TITLE
Crash after returning from external video player

### ISSUE THREAD

**Issue by hashnag** [jellyfin/jellyfin-androidtv#1929]
### Describe the bug

Launching any video with an external player (eg VLC or YouTube in the new 14.0) works great until you return to the Jellyfin UI which almost immediately crashes.

I've tried it with and without "Always ask for credentials" checked and it's happened with about every version since 11.3.

### Application version

0.14.0

### Where did you install the app from?

Sideloaded APK

### Device information

Sony Bravia 4K 2015

### Android version

Android TV 8.0

### Jellyfin server version

10.8.3

**Comment by nielsvanvelzen** [comment]
Can you share the crash logs?

**Comment by Andy2244** [comment]
@hashnag check your server admin log's tab, there should be a AndroidTv client crash log uploaded, add this here.

**Comment by hashnag** [comment]
---
client: Jellyfin for Android TV
client_version: 0.14.0
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.RuntimeException: Unable to resume activity {org.jellyfin.androidtv.debug/org.jellyfin.androidtv.ui.browsing.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.UUID org.jellyfin.sdk.model.api.UserDto.getId()' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3645)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3685)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1643)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.UUID org.jellyfin.sdk.model.api.UserDto.getId()' on a null object reference
	at org.jellyfin.androidtv.ui.itemhandling.BaseRowItem.refresh(BaseRowItem.java:496)
	at org.jellyfin.androidtv.ui.browsing.StdRowsFragment.refreshCurrentItem(StdRowsFragment.java:216)
	at org.jellyfin.androidtv.ui.browsing.StdRowsFragment.onResume(StdRowsFragment.java:89)
	at org.jellyfin.androidtv.ui.home.HomeFragment.onResume(HomeFragment.kt:69)
	at androidx.fragment.app.Fragment.performResume(Fragment.java:3180)
	at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:606)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1424)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2968)
	at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2900)
	at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:285)
	at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:334)
	at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:323)
	at android.app.Activity.performResume(Activity.java:7103)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3620)
	... 8 more

```  
***Logcat***: 
```log
--------- beginning of main
08-08 22:54:23.366 D/skia    (15933): jpg_init return 0.
08-08 22:54:23.376 I/jellyfin-apiclient(15933): Response received from: http://192.168.1.2:8097/Items/b2242c3e318cabc45bfc6c020096e210/Similar?Fields=PrimaryImageAspectRatio%2CChildCount&UserId=1ca07d19-d3d8-4daf-8ec0-00865eb190a1&Limit=10&format=json
08-08 22:54:23.405 D/skia    (15933): start to dlopen libJpgHwDecoder.so.
08-08 22:54:23.422 D/skia    (15933): dlopen ok.
08-08 22:54:23.422 D/        (15933): 00 image_width = 202, image_height = 260
08-08 22:54:23.422 D/        (15933): the colormode is not JCS_YV16, turn to sw decoder.
08-08 22:54:23.422 D/skia    (15933): jpg_init return 0.
08-08 22:54:23.458 D/ACRA    (15933): onActivitySaveInstanceState class org.jellyfin.androidtv.ui.browsing.MainActivity
08-08 22:54:23.472 D/skia    (15933): start to dlopen libJpgHwDecoder.so.
08-08 22:54:23.473 D/skia    (15933): dlopen ok.
08-08 22:54:23.473 D/        (15933): 00 image_width = 202, image_height = 260
08-08 22:54:23.473 D/        (15933): the colormode is not JCS_YV16, turn to sw decoder.
08-08 22:54:23.473 D/skia    (15933): jpg_init return 0.
08-08 22:54:23.489 D/ACRA    (15933): onActivityStopped class org.jellyfin.androidtv.ui.browsing.MainActivity
08-08 22:54:23.492 D/skia    (15933): start to dlopen libJpgHwDecoder.so.
08-08 22:54:23.493 D/skia    (15933): dlopen ok.
08-08 22:54:23.493 D/        (15933): 00 image_width = 202, image_height = 260
08-08 22:54:23.493 D/        (15933): the colormode is not JCS_YV16, turn to sw decoder.
08-08 22:54:23.493 D/skia    (15933): jpg_init return 0.
08-08 22:54:23.548 D/skia    (15933): start to dlopen libJpgHwDecoder.so.
08-08 22:54:23.551 D/skia    (15933): dlopen ok.
08-08 22:54:23.551 D/        (15933): 00 image_width = 202, image_height = 260
08-08 22:54:23.551 D/        (15933): the colormode is not JCS_YV16, turn to sw decoder.
08-08 22:54:23.551 D/skia    (15933): jpg_init return 0.
08-08 22:54:23.576 D/skia    (15933): start to dlopen libJpgHwDecoder.so.
08-08 22:54:23.578 D/skia    (15933): dlopen ok.
08-08 22:54:23.578 D/        (15933): 00 image_width = 202, image_height = 260
08-08 22:54:23.579 D/        (15933): the colormode is not JCS_YV16, turn to sw decoder.
08-08 22:54:23.579 D/skia    (15933): jpg_init return 0.
08-08 22:54:25.780 E/ThemeUtils(15933): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
08-08 22:54:25.823 E/ThemeUtils(15933): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
08-08 22:54:25.849 E/ThemeUtils(15933): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
08-08 22:54:25.872 E/ThemeUtils(15933): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
08-08 22:54:25.897 E/ThemeUtils(15933): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
08-08 22:54:25.977 D/skia    (15933): start to dlopen libJpgHwDecoder.so.
08-08 22:54:25.985 D/skia    (15933): dlopen ok.
08-08 22:54:25.986 D/        (15933): 00 image_width = 1920, image_height = 1080
08-08 22:54:25.986 D/        (15933): the colormode is not JCS_YV16, turn to sw decoder.
08-08 22:54:25.986 D/skia    (15933): jpg_init return 0.
08-08 22:54:26.003 D/skia    (15933): start to dlopen libJpgHwDecoder.so.
08-08 22:54:26.007 D/skia    (15933): dlopen ok.
08-08 22:54:26.007 D/        (15933): 00 image_width = 1920, image_height = 1080
08-08 22:54:26.007 D/        (15933): the colormode is not JCS_YV16, turn to sw decoder.
08-08 22:54:26.007 D/skia    (15933): jpg_init return 0.
08-08 22:54:26.164 D/skia    (15933): start to dlopen libJpgHwDecoder.so.
08-08 22:54:26.167 D/skia    (15933): dlopen ok.
08-08 22:54:26.167 D/        (15933): 00 image_width = 1920, image_height = 1080
08-08 22:54:26.167 D/        (15933): the colormode is not JCS_YV16, turn to sw decoder.
08-08 22:54:26.167 D/skia    (15933): jpg_init return 0.
08-08 22:54:26.225 D/skia    (15933): start to dlopen libJpgHwDecoder.so.
08-08 22:54:26.230 D/skia    (15933): dlopen ok.
08-08 22:54:26.230 D/        (15933): 00 image_width = 1920, image_height = 1080
08-08 22:54:26.230 D/        (15933): the colormode is not JCS_YV16, turn to sw decoder.
08-08 22:54:26.230 D/skia    (15933): jpg_init return 0.
08-08 22:54:26.313 D/skia    (15933): start to dlopen libJpgHwDecoder.so.
08-08 22:54:26.316 D/skia    (15933): dlopen ok.
08-08 22:54:26.316 D/        (15933): 00 image_width = 1920, image_height = 1080
08-08 22:54:26.316 D/        (15933): the colormode is not JCS_YV16, turn to sw decoder.
08-08 22:54:26.316 D/skia    (15933): jpg_init return 0.
08-08 22:54:28.474 D/ACRA    (15933): onActivityPaused class org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity
08-08 22:54:28.941 W/libEGL  (15933): EGLNativeWindowType 0x7a196008 disconnect failed
08-08 22:54:28.941 D/OpenGLRenderer(15933): endAllActiveAnimators on 0x7fecb900 (AppCompatImageView) with handle 0x8017d6b0
08-08 22:54:29.554 D/ACRA    (15933): onActivitySaveInstanceState class org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity
08-08 22:54:29.575 D/ACRA    (15933): onActivityStopped class org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity
08-08 22:54:36.948 D/ACRA    (15933): onActivityStarted class org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity
08-08 22:54:36.987 I/JellyfinApplication$onCreate(15933): Process lifecycle started
08-08 22:54:36.996 D/SessionRepositoryImpl(15933): Restoring session
08-08 22:54:36.998 D/SessionRepositoryImpl(15933): Destroying current session
08-08 22:54:37.007 D/ACRA    (15933): onActivityResumed class org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity
08-08 22:54:37.009 D/BackgroundServiceFragment(15933): Restoring active backgrounds
08-08 22:54:37.012 D/BackgroundServiceFragment(15933): Restoring background drawable
08-08 22:54:37.039 D/mali_winsys(15933): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
--------- beginning of system
08-08 22:54:37.060 W/ViewRootImpl[FullDetailsActivity](15933): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=158, metaState=0, flags=0x28, repeatCount=0, eventTime=178944855, downTime=178944683, deviceId=4, source=0x301 }
08-08 22:54:37.067 W/ViewRootImpl[FullDetailsActivity](15933): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=158, metaState=0, flags=0x28, repeatCount=0, eventTime=178944855, downTime=178944683, deviceId=4, source=0x301 }
08-08 22:54:37.068 W/ViewRootImpl[FullDetailsActivity](15933): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=158, metaState=0, flags=0x28, repeatCount=0, eventTime=178944855, downTime=178944683, deviceId=4, source=0x301 }
08-08 22:54:37.068 W/ViewRootImpl[FullDetailsActivity](15933): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=158, metaState=0, flags=0x28, repeatCount=0, eventTime=178944855, downTime=178944683, deviceId=4, source=0x301 }
08-08 22:54:37.068 W/ViewRootImpl[FullDetailsActivity](15933): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=158, metaState=0, flags=0x28, repeatCount=0, eventTime=178944855, downTime=178944683, deviceId=4, source=0x301 }
08-08 22:54:37.068 W/ViewRootImpl[FullDetailsActivity](15933): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=158, metaState=0, flags=0x28, repeatCount=0, eventTime=178944855, downTime=178944683, deviceId=4, source=0x301 }
08-08 22:54:37.069 W/ViewRootImpl[FullDetailsActivity](15933): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=158, metaState=0, flags=0x28, repeatCount=0, eventTime=178944855, downTime=178944683, deviceId=4, source=0x301 }
08-08 22:54:37.069 W/ViewRootImpl[FullDetailsActivity](15933): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=158, metaState=0, flags=0x28, repeatCount=0, eventTime=178944855, downTime=178944683, deviceId=4, source=0x301 }
08-08 22:54:37.069 W/ViewRootImpl[FullDetailsActivity](15933): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=158, metaState=0, flags=0x28, repeatCount=0, eventTime=178944855, downTime=178944683, deviceId=4, source=0x301 }
08-08 22:54:37.212 I/vndksupport(15933): sphal namespace is not configured for this process. Loading /odm/lib/hw/gralloc.mt5890.so from the current namespace instead.
08-08 22:54:37.292 I/vndksupport(15933): sphal namespace is not configured for this process. Loading /odm/lib/hw/gralloc.mt5890.so from the current namespace instead.
08-08 22:54:37.308 I/vndksupport(15933): sphal namespace is not configured for this process. Loading /odm/lib/hw/gralloc.mt5890.so from the current namespace instead.
08-08 22:54:37.765 D/FullDetailsActivity(15933): current time 1659966877759 last playback event time 0 last refresh time 1659966862726
08-08 22:54:43.129 D/ACRA    (15933): onActivityPaused class org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity
08-08 22:54:43.142 D/ACRA    (15933): onActivityStarted class org.jellyfin.androidtv.ui.browsing.MainActivity
08-08 22:54:43.148 D/ACRA    (15933): onActivityResumed class org.jellyfin.androidtv.ui.browsing.MainActivity
08-08 22:54:43.153 D/StdRowsFragment(15933): Refresh item "The Roundup"
08-08 22:54:43.158 D/AndroidRuntime(15933): Shutting down VM
--------- beginning of crash
08-08 22:54:43.179 E/AndroidRuntime(15933): FATAL EXCEPTION: main
08-08 22:54:43.179 E/AndroidRuntime(15933): Process: org.jellyfin.androidtv.debug, PID: 15933
08-08 22:54:43.179 E/AndroidRuntime(15933): java.lang.RuntimeException: Unable to resume activity {org.jellyfin.androidtv.debug/org.jellyfin.androidtv.ui.browsing.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.UUID org.jellyfin.sdk.model.api.UserDto.getId()' on a null object reference
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3645)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3685)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1643)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at android.os.Handler.dispatchMessage(Handler.java:105)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at android.os.Looper.loop(Looper.java:164)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at java.lang.reflect.Method.invoke(Native Method)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
08-08 22:54:43.179 E/AndroidRuntime(15933): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.UUID org.jellyfin.sdk.model.api.UserDto.getId()' on a null object reference
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at org.jellyfin.androidtv.ui.itemhandling.BaseRowItem.refresh(BaseRowItem.java:496)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at org.jellyfin.androidtv.ui.browsing.StdRowsFragment.refreshCurrentItem(StdRowsFragment.java:216)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at org.jellyfin.androidtv.ui.browsing.StdRowsFragment.onResume(StdRowsFragment.java:89)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at org.jellyfin.androidtv.ui.home.HomeFragment.onResume(HomeFragment.kt:69)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at androidx.fragment.app.Fragment.performResume(Fragment.java:3180)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:606)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1424)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2968)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2900)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:285)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:334)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:323)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at android.app.Activity.performResume(Activity.java:7103)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3620)
08-08 22:54:43.179 E/AndroidRuntime(15933): 	... 8 more
08-08 22:54:43.186 E/ACRA    (15933): ACRA caught a RuntimeException for org.jellyfin.androidtv.debug
08-08 22:54:43.186 E/ACRA    (15933): java.lang.RuntimeException: Unable to resume activity {org.jellyfin.androidtv.debug/org.jellyfin.androidtv.ui.browsing.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.UUID org.jellyfin.sdk.model.api.UserDto.getId()' on a null object reference
08-08 22:54:43.186 E/ACRA    (15933): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3645)
08-08 22:54:43.186 E/ACRA    (15933): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3685)
08-08 22:54:43.186 E/ACRA    (15933): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1643)
08-08 22:54:43.186 E/ACRA    (15933): 	at android.os.Handler.dispatchMessage(Handler.java:105)
08-08 22:54:43.186 E/ACRA    (15933): 	at android.os.Looper.loop(Looper.java:164)
08-08 22:54:43.186 E/ACRA    (15933): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
08-08 22:54:43.186 E/ACRA    (15933): 	at java.lang.reflect.Method.invoke(Native Method)
08-08 22:54:43.186 E/ACRA    (15933): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
08-08 22:54:43.186 E/ACRA    (15933): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
08-08 22:54:43.186 E/ACRA    (15933): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.UUID org.jellyfin.sdk.model.api.UserDto.getId()' on a null object reference
08-08 22:54:43.186 E/ACRA    (15933): 	at org.jellyfin.androidtv.ui.itemhandling.BaseRowItem.refresh(BaseRowItem.java:496)
08-08 22:54:43.186 E/ACRA    (15933): 	at org.jellyfin.androidtv.ui.browsing.StdRowsFragment.refreshCurrentItem(StdRowsFragment.java:216)
08-08 22:54:43.186 E/ACRA    (15933): 	at org.jellyfin.androidtv.ui.browsing.StdRowsFragment.onResume(StdRowsFragment.java:89)
08-08 22:54:43.186 E/ACRA    (15933): 	at org.jellyfin.androidtv.ui.home.HomeFragment.onResume(HomeFragment.kt:69)
08-08 22:54:43.186 E/ACRA    (15933): 	at androidx.fragment.app.Fragment.performResume(Fragment.java:3180)
08-08 22:54:43.186 E/ACRA    (15933): 	at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:606)
08-08 22:54:43.186 E/ACRA    (15933): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
08-08 22:54:43.186 E/ACRA    (15933): 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
08-08 22:54:43.186 E/ACRA    (15933): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1424)
08-08 22:54:43.186 E/ACRA    (15933): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2968)
08-08 22:54:43.186 E/ACRA    (15933): 	at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2900)
08-08 22:54:43.186 E/ACRA    (15933): 	at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:285)
08-08 22:54:43.186 E/ACRA    (15933): 	at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:334)
08-08 22:54:43.186 E/ACRA    (15933): 	at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:323)
08-08 22:54:43.186 E/ACRA    (15933): 	at android.app.Activity.performResume(Activity.java:7103)
08-08 22:54:43.186 E/ACRA    (15933): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3620)
08-08 22:54:43.186 E/ACRA    (15933): 	... 8 more
08-08 22:54:43.187 D/ACRA    (15933): Building report
08-08 22:54:43.196 D/ACRA    (15933): Starting collectors with priority FIRST
08-08 22:54:43.204 D/ACRA    (15933): Calling collector org.acra.collector.StacktraceCollector
08-08 22:54:43.205 D/ACRA    (15933): Calling collector org.acra.collector.DropBoxCollector
08-08 22:54:43.205 D/ACRA    (15933): Calling collector org.acra.collector.LogCatCollector
08-08 22:54:43.207 D/ACRA    (15933): Collector org.acra.collector.DropBoxCollector completed
08-08 22:54:43.209 D/ACRA    (15933): Collector org.acra.collector.StacktraceCollector completed
08-08 22:54:43.223 D/ACRA    (15933): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.14.0` (`140099`)  
***Package name***: `org.jellyfin.androidtv.debug`  
***Build***: 
```json
{"BOARD":"SVPDTV15","BOOTLOADER":"unknown","BRAND":"Sony","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"SVP-DTV15","DISPLAY":"SVP4KDTV15_UC-user 8.0.0 OPR2.170623.027.S16 6.827 release-keys","FINGERPRINT":"Sony\/SVP4KDTV15_UC\/SVP-DTV15:8.0.0\/OPR2.170623.027.S16\/6.827:user\/release-keys","HARDWARE":"mt5890","HOST":"BuildHost728","ID":"OPR2.170623.027.S16","IS_CONTAINER":false,"IS_DEBUGGABLE":false,"IS_EMULATOR":false,"IS_ENG":false,"IS_TREBLE_ENABLED":false,"IS_USER":true,"IS_USERDEBUG":false,"MANUFACTURER":"Sony","MODEL":"BRAVIA 4K 2015","PERMISSIONS_REVIEW_REQUIRED":false,"PRODUCT":"SVP4KDTV15_UC","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1583308711000,"TYPE":"user","UNKNOWN":"unknown","USER":"root","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"6.827","PREVIEW_SDK_INT":0,"RELEASE":"8.0.0","RESOURCES_SDK_INT":26,"SDK":"26","SDK_INT":26,"SECURITY_PATCH":"2020-01-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv.debug","BUILD_TYPE":"debug","DEBUG":true,"DEVELOPMENT":false,"VERSION_CODE":140099,"VERSION_NAME":"0.14.0"}
```  

### Device information

***Android version***: `8.0.0`  
***Device brand***: `Sony`  
***Device product***: `SVP4KDTV15_UC`  
***Device model***: `BRAVIA 4K 2015`  

### Crash information

***Start time***: `2022-08-08T22:53:40.609+09:00`  
***Crash time***: `2022-08-08T22:54:43.360+09:00`

**Comment by Andy2244** [comment]
Its the `BaseRowItem.refresh()` again, i did just wrap it with a null check, which seems to have fixed the crashes for me.

**Comment by Andy2244** [comment]
@hashnag If you can easily reproduce this bug, can you confirm that this version fixes the issue?
https://drive.google.com/file/d/1sPFTDbg40fpQmB2QH6N27imPj0mhUX0B/view

**Comment by hashnag** [comment]
That seems to have fixed the issue.
