### ISSUE TITLE
Subtitles crash playback

### ISSUE THREAD

**Issue by QuickListTech** [jellyfin/jellyfin-androidtv#2026]
### Describe the bug

1. Start playback on a 4k file and you get "subtitle loading" while playback starts
2. Select a PGS (builtin) subtitle
3. black screen + Player crashes saying something like "too many errors"
4. Start playback again, this time subtitles load automatically without user intervention

Using default configuration of jellyfin client.

### Logs
```
[2022-09-04 08:30:03.773 +09:30] [INF] StreamBuilder.BuildVideoItem( Profile="AndroidTV-libVLC", Path="nfs://blob/export/Video/Movies/Gattaca/Gattaca.1997.2160p.BluRay.mkv", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/3da5d3eb-9eeb-d8f5-23cb-600b778b11ea/stream.mkv?MediaSourceId=3da5d3eb9eebd8f523cb600b778b11ea&Static=true&VideoCodec=hevc&AudioCodec=truehd&AudioStreamIndex=1&SubtitleStreamIndex=2&api_key=<token>&SubtitleMethod=Embed&Tag=3b6e838e417a9aae2c0c6d75e004dbd4"
[2022-09-04 08:30:03.806 +09:30] [INF] User policy for "tv". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2022-09-04 08:30:03.807 +09:30] [INF] StreamBuilder.BuildVideoItem( Profile="AndroidTV-ExoPlayer", Path="nfs://blob/export/Video/Movies/Gattaca/Gattaca.1997.2160p.BluRay.mkv", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/3da5d3eb-9eeb-d8f5-23cb-600b778b11ea/stream.mkv?MediaSourceId=3da5d3eb9eebd8f523cb600b778b11ea&Static=true&VideoCodec=hevc&AudioCodec=truehd&AudioStreamIndex=1&SubtitleStreamIndex=2&api_key=<token>&SubtitleMethod=Embed&Tag=3b6e838e417a9aae2c0c6d75e004dbd4"
[2022-09-04 08:30:04.433 +09:30] [INF] Started user data sync
[2022-09-04 08:30:04.445 +09:30] [INF] User Data Sync: User "tv" ("90de945c716743e69ab33f2c5758a629") posted 2 updates
[2022-09-04 08:30:04.445 +09:30] [INF] Finished user data sync, taking "00:00:00.0125153"
[2022-09-04 08:30:04.736 +09:30] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-i file:\"/srv/Data/Video/Movies/Gattaca/Gattaca.1997.2160p.BluRay.mkv\" -copyts -map 0:2 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/3/34494620-71e1-ac39-49de-86798f74b2aa.srt\""
[2022-09-04 08:30:33.415 +09:30] [INF] Playback stopped reported by app "Android TV" "0.14.2" playing "Gattaca". Stopped at "18972" ms
[2022-09-04 08:30:33.496 +09:30] [INF] User policy for "tv". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2022-09-04 08:30:33.496 +09:30] [INF] StreamBuilder.BuildVideoItem( Profile="AndroidTV-libVLC", Path="nfs://blob/export/Video/Movies/Gattaca/Gattaca.1997.2160p.BluRay.mkv", AudioStreamIndex=null, SubtitleStreamIndex=4 ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/3da5d3eb-9eeb-d8f5-23cb-600b778b11ea/stream.mkv?MediaSourceId=3da5d3eb9eebd8f523cb600b778b11ea&Static=true&VideoCodec=hevc&AudioCodec=truehd&AudioStreamIndex=1&SubtitleStreamIndex=4&api_key=<token>&SubtitleMethod=Embed&Tag=3b6e838e417a9aae2c0c6d75e004dbd4"
[2022-09-04 08:30:33.512 +09:30] [INF] User policy for "tv". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2022-09-04 08:30:33.512 +09:30] [INF] StreamBuilder.BuildVideoItem( Profile="AndroidTV-ExoPlayer", Path="nfs://blob/export/Video/Movies/Gattaca/Gattaca.1997.2160p.BluRay.mkv", AudioStreamIndex=null, SubtitleStreamIndex=4 ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported ) "media:/videos/3da5d3eb-9eeb-d8f5-23cb-600b778b11ea/master.m3u8?MediaSourceId=3da5d3eb9eebd8f523cb600b778b11ea&VideoCodec=hevc,h264,hevc&AudioCodec=ac3,aac,mp3&AudioStreamIndex=1&SubtitleStreamIndex=4&VideoBitrate=115360333&AudioBitrate=4639667&MaxFramerate=23.976025&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=3b6e838e417a9aae2c0c6d75e004dbd4&SegmentContainer=ts&BreakOnNonKeyFrames=False&hevc-level=150&hevc-profile=main10&h264-profile=high,main,baseline,constrainedbaseline&h264-level=52&h264-maxrefframes=4&ac3-audiochannels=8&TranscodeReasons=SubtitleCodecNotSupported"
[2022-09-04 08:30:34.208 +09:30] [INF] Started user data sync
[2022-09-04 08:30:34.281 +09:30] [INF] User Data Sync: User "tv" ("90de945c716743e69ab33f2c5758a629") posted 2 updates
[2022-09-04 08:30:34.281 +09:30] [INF] Finished user data sync, taking "00:00:00.0720082"
[2022-09-04 08:30:37.028 +09:30] [WRN] WS "192.168.1.117" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2022-09-04 08:30:37.033 +09:30] [INF] WS "192.168.1.117" closed
[2022-09-04 08:30:39.430 +09:30] [INF] WS "192.168.1.117" request
[2022-09-04 08:30:47.322 +09:30] [INF] WS "192.168.1.132" closed
[2022-09-04 08:30:47.692 +09:30] [INF] WS "192.168.1.132" request
[2022-09-04 08:32:12.785 +09:30] [INF] ffmpeg subtitle extraction completed for "file:\"/srv/Data/Video/Movies/Gattaca/Gattaca.1997.2160p.BluRay.mkv\"" to "/var/lib/jellyfin/data/subtitles/3/34494620-71e1-ac39-49de-86798f74b2aa.srt"
[2022-09-04 08:32:12.806 +09:30] [WRN] Slow HTTP Response from "http://192.168.1.200:8096/Videos/3da5d3eb9eebd8f523cb600b778b11ea/3da5d3eb9eebd8f523cb600b778b11ea/Subtitles/2/0/Stream.JSON?format=json" to "192.168.1.117" in 0:02:08.0718816 with Status Code 200
[2022-09-04 08:32:41.628 +09:30] [INF] WS "192.168.1.132" closed
[2022-09-04 08:32:42.055 +09:30] [INF] WS "192.168.1.132" request
```

### Application version

0.14.2

### Device information

nvidia shield (2019)

### Android version

Android 11,  9.1.0

### Jellyfin server version

10.8.4

**Comment by mueslimak3r** [comment]
Can you upload the client log? They should be available in your server dashboard

**Comment by QuickListTech** [comment]
[2022-09-04 08:37:37.157 +09:30] [INF] User policy for "tv". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2022-09-04 08:37:37.157 +09:30] [INF] StreamBuilder.BuildVideoItem( Profile="AndroidTV-libVLC", Path="nfs://blob/export/Video/Movies/The Green Mile/The.Green.Mile.1999.2160p.mkv", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/0b8e5c35-d3a7-4f8c-5358-2dc115d88c17/stream.mkv?MediaSourceId=0b8e5c35d3a74f8c53582dc115d88c17&Static=true&VideoCodec=hevc&AudioCodec=truehd&AudioStreamIndex=1&SubtitleStreamIndex=4&api_key=<token>&SubtitleMethod=Embed&Tag=f09e997716719fecb86b7518b54f0b04"
[2022-09-04 08:37:37.238 +09:30] [INF] User policy for "tv". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2022-09-04 08:37:37.238 +09:30] [INF] StreamBuilder.BuildVideoItem( Profile="AndroidTV-ExoPlayer", Path="nfs://blob/export/Video/Movies/The Green Mile/The.Green.Mile.1999.2160p.UHD.BluRay.x265.10bit.HDR.DTS-HD.MA.TrueHD.7.1.Atmos-SWTYBLZ.mkv", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/0b8e5c35-d3a7-4f8c-5358-2dc115d88c17/stream.mkv?MediaSourceId=0b8e5c35d3a74f8c53582dc115d88c17&Static=true&VideoCodec=hevc&AudioCodec=truehd&AudioStreamIndex=1&SubtitleStreamIndex=4&api_key=<token>&SubtitleMethod=Embed&Tag=f09e997716719fecb86b7518b54f0b04"
[2022-09-04 08:37:37.974 +09:30] [INF] Started user data sync
[2022-09-04 08:37:38.006 +09:30] [INF] User Data Sync: User "tv" ("90de945c716743e69ab33f2c5758a629") posted 2 updates
[2022-09-04 08:37:38.006 +09:30] [INF] Finished user data sync, taking "00:00:00.0320598"
[2022-09-04 08:37:40.285 +09:30] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-i file:\"/srv/Data/Video/Movies/The Green Mile/The.Green.Mile.1999.2160p.mkv\" -copyts -map 0:4 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/7/755e2d2d-eaf7-96a3-9b4a-7089197097e3.srt\""
[2022-09-04 08:38:22.578 +09:30] [INF] Playback stopped reported by app "Android TV" "0.14.2" playing "The Green Mile". Stopped at "17570" ms
[2022-09-04 08:38:22.615 +09:30] [INF] User policy for "tv". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2022-09-04 08:38:22.615 +09:30] [INF] StreamBuilder.BuildVideoItem( Profile="AndroidTV-libVLC", Path="nfs://blob/export/Video/Movies/The Green Mile/The.Green.Mile.1999.2160p.UHD.BluRay.x265.10bit.HDR.DTS-HD.MA.TrueHD.7.1.Atmos-SWTYBLZ.mkv", AudioStreamIndex=null, SubtitleStreamIndex=6 ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/0b8e5c35-d3a7-4f8c-5358-2dc115d88c17/stream.mkv?MediaSourceId=0b8e5c35d3a74f8c53582dc115d88c17&Static=true&VideoCodec=hevc&AudioCodec=truehd&AudioStreamIndex=1&SubtitleStreamIndex=6&api_key=<token>&SubtitleMethod=Embed&Tag=f09e997716719fecb86b7518b54f0b04"
[2022-09-04 08:38:22.669 +09:30] [INF] User policy for "tv". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2022-09-04 08:38:22.669 +09:30] [INF] StreamBuilder.BuildVideoItem( Profile="AndroidTV-ExoPlayer", Path="nfs://blob/export/Video/Movies/The Green Mile/The.Green.Mile.1999.2160p.UHD.BluRay.x265.10bit.HDR.DTS-HD.MA.TrueHD.7.1.Atmos-SWTYBLZ.mkv", AudioStreamIndex=null, SubtitleStreamIndex=6 ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported ) "media:/videos/0b8e5c35-d3a7-4f8c-5358-2dc115d88c17/master.m3u8?MediaSourceId=0b8e5c35d3a74f8c53582dc115d88c17&VideoCodec=hevc,h264,hevc&AudioCodec=ac3,aac,mp3&AudioStreamIndex=1&SubtitleStreamIndex=6&VideoBitrate=116848607&AudioBitrate=3151393&MaxFramerate=23.976025&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=f09e997716719fecb86b7518b54f0b04&SegmentContainer=ts&BreakOnNonKeyFrames=False&hevc-level=153&hevc-profile=main10&h264-profile=high,main,baseline,constrainedbaseline&h264-level=52&h264-maxrefframes=4&ac3-audiochannels=8&TranscodeReasons=SubtitleCodecNotSupported"
[2022-09-04 08:38:23.541 +09:30] [INF] Started user data sync
[2022-09-04 08:38:23.624 +09:30] [INF] User Data Sync: User "tv" ("90de945c716743e69ab33f2c5758a629") posted 2 updates
[2022-09-04 08:38:23.624 +09:30] [INF] Finished user data sync, taking "00:00:00.0830234"
[2022-09-04 08:38:28.634 +09:30] [WRN] WS "192.168.1.117" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2022-09-04 08:38:28.638 +09:30] [INF] WS "192.168.1.117" closed
[2022-09-04 08:38:28.808 +09:30] [INF] Sending ForceKeepAlive message to 1 inactive WebSockets.
[2022-09-04 08:38:29.472 +09:30] [ERR] Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session b8fe8c6981e66d56d4049382a70587cc not found.
   at Emby.Server.Implementations.Session.SessionManager.GetSession(String sessionId, Boolean throwOnMissing)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2022-09-04 08:38:30.472 +09:30] [ERR] Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session b8fe8c6981e66d56d4049382a70587cc not found.
   at Emby.Server.Implementations.Session.SessionManager.GetSession(String sessionId, Boolean throwOnMissing)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2022-09-04 08:38:31.146 +09:30] [INF] WS "192.168.1.117" request

**Comment by QuickListTech** [comment]
Also, if I switch the preferred media player from "Automatically choose" to "libVLC", subtitles seem to load fine with no crashing.

**Comment by QuickListTech** [comment]
> Can you upload the client log? They should be available in your server dashboard

Is it meant to be in the logs section? All is see is server logs (ive uploaded some)

**Comment by mueslimak3r** [comment]
> > Can you upload the client log? They should be available in your server dashboard
> 
> 
> 
> Is it meant to be in the logs section? All is see is server logs (ive uploaded some)

In the app settings -> crash reporting -> make sure both "send crash reports to server" and "include logs" are enabled.

Then afaik they should be in the logs section of the jf dashboard following a crash.

**Comment by ghzgod** [comment]
Issue still exists
