### ISSUE TITLE
Crushes on Google chromecast

### ISSUE THREAD

**Issue by fdfytr** [jellyfin/jellyfin-androidtv#2040]
### Describe the bug

Install app from Google playstore
Add user to server
Login with password or quick connect

App crashes
Tried to reinstall app 

### Logs

---
client: Jellyfin for Android TV
client_version: 0.14.2
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
org.jellyfin.apiclient.model.net.HttpException: VolleyError com.android.volley.ServerError: 
	at org.jellyfin.apiclient.interaction.VolleyErrorListener.onErrorResponse(VolleyErrorListener.java:25)
	at com.android.volley.Request.deliverError(Request.java:648)
	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:104)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7975815, Dispatchers.IO]
Caused by: com.android.volley.ServerError
	at com.android.volley.toolbox.NetworkUtility.shouldRetryException(NetworkUtility.java:201)
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:145)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

```  
***Logcat***: 
```log
--------- beginning of main
09-06 19:47:03.540 I/ACRA    ( 8429): ACRA is enabled for org.jellyfin.androidtv, initializing...
09-06 19:47:03.540 D/ACRA    ( 8429): SimplePluginLoader loading services from plugin classes : [Ljava.lang.Class;@194a285
09-06 19:47:03.541 D/ACRA    ( 8429): ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.collector.Collector]
09-06 19:47:03.593 D/ACRA    ( 8429): Loaded Collector of type org.acra.collector.ConfigurationCollector
09-06 19:47:03.593 D/ACRA    ( 8429): Loaded Collector of type org.acra.collector.CustomDataCollector
09-06 19:47:03.594 D/ACRA    ( 8429): Loaded Collector of type org.acra.collector.DeviceFeaturesCollector
09-06 19:47:03.594 D/ACRA    ( 8429): Loaded Collector of type org.acra.collector.DeviceIdCollector
09-06 19:47:03.594 D/ACRA    ( 8429): Loaded Collector of type org.acra.collector.DisplayManagerCollector
09-06 19:47:03.595 D/ACRA    ( 8429): Loaded Collector of type org.acra.collector.DropBoxCollector
09-06 19:47:03.596 D/ACRA    ( 8429): Loaded Collector of type org.acra.collector.LogCatCollector
09-06 19:47:03.596 D/ACRA    ( 8429): Loaded Collector of type org.acra.collector.LogFileCollector
09-06 19:47:03.597 D/ACRA    ( 8429): Loaded Collector of type org.acra.collector.MediaCodecListCollector
09-06 19:47:03.597 D/ACRA    ( 8429): Loaded Collector of type org.acra.collector.MemoryInfoCollector
09-06 19:47:03.598 D/ACRA    ( 8429): Loaded Collector of type org.acra.collector.PackageManagerCollector
09-06 19:47:03.598 D/ACRA    ( 8429): Loaded Collector of type org.acra.collector.ReflectionCollector
09-06 19:47:03.598 D/ACRA    ( 8429): Loaded Collector of type org.acra.collector.SettingsCollector
09-06 19:47:03.599 D/ACRA    ( 8429): Loaded Collector of type org.acra.collector.SharedPreferencesCollector
09-06 19:47:03.599 D/ACRA    ( 8429): Loaded Collector of type org.acra.collector.SimpleValuesCollector
09-06 19:47:03.599 D/ACRA    ( 8429): Loaded Collector of type org.acra.collector.StacktraceCollector
09-06 19:47:03.599 D/ACRA    ( 8429): Loaded Collector of type org.acra.collector.ThreadCollector
09-06 19:47:03.616 D/ACRA    ( 8429): Loaded Collector of type org.acra.collector.TimeCollector
09-06 19:47:03.630 D/ACRA    ( 8429): SimplePluginLoader loading services from plugin classes : [Ljava.lang.Class;@194a285
09-06 19:47:03.630 D/ACRA    ( 8429): ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.scheduler.SenderSchedulerFactory]
09-06 19:47:03.631 D/ACRA    ( 8429): SimplePluginLoader loading services from plugin classes : [Ljava.lang.Class;@194a285
09-06 19:47:03.631 D/ACRA    ( 8429): ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.config.ReportingAdministrator]
09-06 19:47:03.638 I/LogInitializer( 8429): Debug tree planted
09-06 19:47:03.723 W/lyfin.androidt( 8429): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (greylist-max-o, reflection, denied)
09-06 19:47:03.723 W/lyfin.androidt( 8429): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
09-06 19:47:03.724 W/lyfin.androidt( 8429): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
09-06 19:47:03.746 D/SessionRepositoryImpl( 8429): Restoring session
09-06 19:47:03.771 D/SessionRepositoryImpl( 8429): Updating current session. userId=f0b9cada-80ae-4209-a864-2b0c2877db39 apiBindingSuccess=true
09-06 19:47:03.782 I/KtorClient( 8429): GET http://192.168.1.86:8096/Users/Me
09-06 19:47:03.824 I/MigrationContext( 8429): Requested migration from 6 to 6. Found 3 migrations in total.
09-06 19:47:03.825 I/ProcessLifecycleInitializer$create( 8429): Registering 2 ActivityLifecycleCallbacks
09-06 19:47:03.825 D/WM-WrkMgrInitializer( 8429): Initializing WorkManager with default configuration.
09-06 19:47:03.834 D/NetworkSecurityConfig( 8429): No Network Security Config specified, using platform default
09-06 19:47:03.846 D/ACRA    ( 8429): ACRA processName='org.jellyfin.androidtv'
09-06 19:47:03.874 I/AuthenticatedUserCallbacks( 8429): Activity org.jellyfin.androidtv.ui.startup.StartupActivity is ignored
09-06 19:47:03.875 I/AppThemeCallbacks( 8429): Applying theme: DARK
09-06 19:47:03.878 D/ACRA    ( 8429): onActivityCreated class org.jellyfin.androidtv.ui.startup.StartupActivity
09-06 19:47:03.902 I/BackgroundService( 8429): Adding BackgroundServiceFragment to activity
09-06 19:47:03.914 D/ACRA    ( 8429): onActivityStarted class org.jellyfin.androidtv.ui.startup.StartupActivity
09-06 19:47:03.942 I/ProcessLifecycleInitializer$create( 8429): Process lifecycle started
09-06 19:47:03.945 D/ACRA    ( 8429): onActivityResumed class org.jellyfin.androidtv.ui.startup.StartupActivity
09-06 19:47:03.946 D/BackgroundServiceFragment( 8429): Restoring background drawable
09-06 19:47:03.963 D/ACRA    ( 8429): SimplePluginLoader loading services from plugin classes : [Ljava.lang.Class;@194a285
09-06 19:47:03.963 D/ACRA    ( 8429): ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.startup.StartupProcessor]
09-06 19:47:03.965 D/ACRA    ( 8429): Loaded StartupProcessor of type org.acra.startup.UnapprovedStartupProcessor
09-06 19:47:04.032 E/ion     ( 8429): ioctl c0044901 failed with code -1: Invalid argument
09-06 19:47:04.032 W/gralloc ( 8429): WARNING: internal format modifier bits not mutually exclusive. AFBC basic bit is always set, so extended AFBC support bits must always be checked.
09-06 19:47:04.119 I/KtorClient( 8429): GET http://192.168.1.86:8096/DisplayPreferences/livetv?userId=f0b9cada-80ae-4209-a864-2b0c2877db39&client=jellyfin-androidtv
09-06 19:47:04.190 I/KtorClient( 8429): GET http://192.168.1.86:8096/DisplayPreferences/usersettings?userId=f0b9cada-80ae-4209-a864-2b0c2877db39&client=emby
09-06 19:47:04.243 I/StartupActivity$onPermissionsGranted( 8429): Found a session in the session repository, waiting for the currentUser in the application class.
09-06 19:47:04.246 I/StartupActivity$onPermissionsGranted( 8429): CurrentUser changed to f0b9cada-80ae-4209-a864-2b0c2877db39 while waiting for startup.
09-06 19:47:04.251 D/StartupActivity( 8429): Determining next activity (action=android.intent.action.MAIN, itemId=null, itemIsUserView=false)
09-06 19:47:04.255 D/SessionRepositoryImpl( 8429): Restoring session
09-06 19:47:04.267 I/KtorClient( 8429): GET http://192.168.1.86:8096/Playback/BitrateTest?size=4000000
09-06 19:47:04.285 D/SocketInstance( 8429): Reconnect requested
09-06 19:47:04.286 I/SocketInstance( 8429): Reconnecting
09-06 19:47:04.286 D/ReconnectHelper( 8429): Notified about reconnect, attempts=1
09-06 19:47:04.288 D/SocketInstance( 8429): Reconnect requested
09-06 19:47:04.288 D/SocketInstance( 8429): Reconnect requested
09-06 19:47:04.289 I/chatty  ( 8429): uid=10071(org.jellyfin.androidtv) DefaultDispatch identical 1 line
09-06 19:47:04.290 D/SocketInstance( 8429): Reconnect requested
09-06 19:47:04.298 I/KtorClient( 8429): POST http://192.168.1.86:8096/Sessions/Capabilities?playableMediaTypes=Video%2CAudio&supportedCommands=DisplayMessage%2CSendString&supportsMediaControl=true&supportsSync=false&supportsPersistentIdentifier=true
09-06 19:47:04.366 I/OkHttpWebsocketSession( 8429): WebSocket has opened
09-06 19:47:04.380 D/SocketInstance( 8429): Credential update requested
09-06 19:47:04.381 D/SocketInstance( 8429): Unable to update credentials: credentials did not change
09-06 19:47:04.386 D/ReconnectHelper( 8429): Notified about connect, attempts reset
09-06 19:47:04.398 D/StartupActivity( 8429): Opening next activity Intent { flg=0x10004000 cmp=org.jellyfin.androidtv/.ui.browsing.MainActivity }
09-06 19:47:04.415 D/ACRA    ( 8429): onActivityPaused class org.jellyfin.androidtv.ui.startup.StartupActivity
09-06 19:47:04.424 W/ActivityThread( 8429): handleWindowVisibility: no activity for token android.os.BinderProxy@aa31e4a
09-06 19:47:04.431 I/AppThemeCallbacks( 8429): Applying theme: DARK
09-06 19:47:04.432 D/ACRA    ( 8429): onActivityCreated class org.jellyfin.androidtv.ui.browsing.MainActivity
09-06 19:47:04.442 I/BackgroundService( 8429): Adding BackgroundServiceFragment to activity
09-06 19:47:04.445 D/ACRA    ( 8429): onActivityStarted class org.jellyfin.androidtv.ui.browsing.MainActivity
09-06 19:47:04.481 I/BackgroundService( 8429): Adding BackgroundServiceFragment to activity
09-06 19:47:04.487 D/jellyfin-apiclient( 8429): Adding request to queue: http://192.168.1.86:8096/LiveTv/Programs/Recommended?UserId=f0b9cada-80ae-4209-a864-2b0c2877db39&EnableTotalRecordCount=false&IsAiring=true&Limit=1&ImageTypeLimit=1&format=json
09-06 19:47:04.488 D/MediaManager( 8429): Added event listener.  Total listeners: 1
09-06 19:47:04.527 I/OkHttpWebsocketSession( 8429): Receiving (raw) message {"MessageType":"ForceKeepAlive","MessageId":"00000000000000000000000000000000","Data":60}
09-06 19:47:04.533 E/Volley  ( 8429): [353] NetworkUtility.shouldRetryException: Unexpected response code 500 for http://192.168.1.86:8096/LiveTv/Programs/Recommended?UserId=f0b9cada-80ae-4209-a864-2b0c2877db39&EnableTotalRecordCount=false&IsAiring=true&Limit=1&ImageTypeLimit=1&format=json
09-06 19:47:04.535 I/KeepAliveHelper( 8429): Using a KeepAlive message delay of 30 seconds
09-06 19:47:04.542 I/OkHttpWebsocketSession( 8429): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
09-06 19:47:04.547 I/OkHttpWebsocketSession( 8429): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"f734c459233c41c98bdc3778650a55ad"}
09-06 19:47:04.555 D/ACRA    ( 8429): onActivityResumed class org.jellyfin.androidtv.ui.browsing.MainActivity
09-06 19:47:04.557 I/HomeFragment( 8429): Updating audio queue in HomeFragment (onResume)
09-06 19:47:04.558 D/BackgroundServiceFragment( 8429): Restoring background drawable
09-06 19:47:04.559 D/BackgroundServiceFragment( 8429): Restoring background drawable
09-06 19:47:04.569 E/jellyfin-apiclient( 8429): VolleyError com.android.volley.ServerError: null
09-06 19:47:04.569 E/jellyfin-apiclient( 8429): com.android.volley.ServerError
09-06 19:47:04.569 E/jellyfin-apiclient( 8429): 	at com.android.volley.toolbox.NetworkUtility.shouldRetryException(NetworkUtility.java:201)
09-06 19:47:04.569 E/jellyfin-apiclient( 8429): 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:145)
09-06 19:47:04.569 E/jellyfin-apiclient( 8429): 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
09-06 19:47:04.569 E/jellyfin-apiclient( 8429): 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
09-06 19:47:04.569 E/jellyfin-apiclient( 8429): 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
09-06 19:47:04.581 E/ACRA    ( 8429): ACRA caught a HttpException for org.jellyfin.androidtv
09-06 19:47:04.581 E/ACRA    ( 8429): org.jellyfin.apiclient.model.net.HttpException: VolleyError com.android.volley.ServerError: 
09-06 19:47:04.581 E/ACRA    ( 8429): 	at org.jellyfin.apiclient.interaction.VolleyErrorListener.onErrorResponse(VolleyErrorListener.java:25)
09-06 19:47:04.581 E/ACRA    ( 8429): 	at com.android.volley.Request.deliverError(Request.java:648)
09-06 19:47:04.581 E/ACRA    ( 8429): 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:104)
09-06 19:47:04.581 E/ACRA    ( 8429): 	at android.os.Handler.handleCallback(Handler.java:883)
09-06 19:47:04.581 E/ACRA    ( 8429): 	at android.os.Handler.dispatchMessage(Handler.java:100)
09-06 19:47:04.581 E/ACRA    ( 8429): 	at android.os.Looper.loop(Looper.java:214)
09-06 19:47:04.581 E/ACRA    ( 8429): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
09-06 19:47:04.581 E/ACRA    ( 8429): 	at java.lang.reflect.Method.invoke(Native Method)
09-06 19:47:04.581 E/ACRA    ( 8429): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
09-06 19:47:04.581 E/ACRA    ( 8429): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
09-06 19:47:04.581 E/ACRA    ( 8429): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7975815, Dispatchers.IO]
09-06 19:47:04.581 E/ACRA    ( 8429): Caused by: com.android.volley.ServerError
09-06 19:47:04.581 E/ACRA    ( 8429): 	at com.android.volley.toolbox.NetworkUtility.shouldRetryException(NetworkUtility.java:201)
09-06 19:47:04.581 E/ACRA    ( 8429): 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:145)
09-06 19:47:04.581 E/ACRA    ( 8429): 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
09-06 19:47:04.581 E/ACRA    ( 8429): 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
09-06 19:47:04.581 E/ACRA    ( 8429): 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
09-06 19:47:04.582 D/ACRA    ( 8429): Building report
09-06 19:47:04.586 D/ACRA    ( 8429): Starting collectors with priority FIRST
09-06 19:47:04.590 D/ACRA    ( 8429): Calling collector org.acra.collector.DropBoxCollector
09-06 19:47:04.591 D/ACRA    ( 8429): Calling collector org.acra.collector.LogCatCollector
09-06 19:47:04.592 D/ACRA    ( 8429): Calling collector org.acra.collector.StacktraceCollector
09-06 19:47:04.593 D/ACRA    ( 8429): Collector org.acra.collector.StacktraceCollector completed
09-06 19:47:04.593 D/ACRA    ( 8429): Collector org.acra.collector.DropBoxCollector completed
09-06 19:47:04.595 I/KtorClient( 8429): GET http://192.168.1.86:8096/Users/f0b9cada-80ae-4209-a864-2b0c2877db39/Items/Resume?limit=10&fields=DateCreated&mediaTypes=Video&imageTypeLimit=1&includeItemTypes=Episode%2CMovie&enableTotalRecordCount=true&enableImages=true&excludeActiveSessions=true
09-06 19:47:04.603 I/KtorClient( 8429): GET http://192.168.1.86:8096/Shows/NextUp?userId=f0b9cada-80ae-4209-a864-2b0c2877db39&limit=10&fields=DateCreated&imageTypeLimit=1&enableTotalRecordCount=true&disableFirstEpisode=false&enableRewatching=false
09-06 19:47:04.648 D/ACRA    ( 8429): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.14.2` (`140299`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"sabrina","BOOTLOADER":"01.01.220111.043647","BRAND":"google","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"sabrina","DISPLAY":"QTS1.220504.008.8726984","FINGERPRINT":"google\/sabrina_prod_stable\/sabrina:10\/QTS1.220504.008\/8726984:user\/release-keys","HARDWARE":"amlogic","HOST":"abfarm-64-central-00314","ID":"QTS1.220504.008","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Google","MODEL":"Chromecast","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"sabrina_prod_stable","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1655289146000,"TYPE":"user","UNKNOWN":"unknown","USER":"android-build","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","FIRST_SDK_INT":29,"INCREMENTAL":"8726984","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"10","RESOURCES_SDK_INT":29,"SDK":"29","SDK_INT":29,"SECURITY_PATCH":"2022-05-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":140299,"VERSION_NAME":"0.14.2"}
```  

### Device information

***Android version***: `10`  
***Device brand***: `google`  
***Device product***: `sabrina_prod_stable`  
***Device model***: `Chromecast`  

### Crash information

***Start time***: `2022-09-06T19:47:03.629+01:00`  
***Crash time***: `2022-09-06T19:47:04.857+01:00`  

### Application version

0.14.2

### Where did you install the app from?

Google Play

### Device information

Google chromecast TV 4K

### Android version

Android 10

### Jellyfin server version

10.8.4

**Comment by nielsvanvelzen** [comment]
It looks like something is wrong on your server:

```
09-06 19:47:04.533 E/Volley  ( 8429): [353] NetworkUtility.shouldRetryException: Unexpected response code 500 for http://192.168.1.86:8096/LiveTv/Programs/Recommended?UserId=f0b9cada-80ae-4209-a864-2b0c2877db39&EnableTotalRecordCount=false&IsAiring=true&Limit=1&ImageTypeLimit=1&format=json
```
This indicates an error when retrieving recommended live tv programs. There should something in your server logs for this issue.

**Comment by fdfytr** [comment]
thanks for looking into that
i dont have any problem with accessing server via mobile android app or through firefox

i cannot delete live tv library for some reason + logs shows jellyfin is trying to access old transcodes directory
looks like i will have reinstall whole thing :(
