### ISSUE TITLE
Jellyfin crashed problems

### ISSUE THREAD

**Issue by Karmylr** [jellyfin/jellyfin-androidtv#2140]
### Describe the bug

when i use collection, app will crash.

### Logs

***Stack Trace***: 
```log
java.lang.IllegalStateException: Fragment BrowseGridFragment{ab4d9c3} (88a0cefe-743d-4d0e-9ac5-a71800723413) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:967)
	at org.jellyfin.androidtv.ui.GridFragment.setItem(GridFragment.java:155)
	at org.jellyfin.androidtv.ui.browsing.StdGridFragment$10.run(StdGridFragment.java:788)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:6740)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```  
***Logcat***: 
```log
--------- beginning of main
10-05 13:49:29.587 D/BackgroundServiceFragment(17184): Restoring background drawable
10-05 13:49:29.587 D/BackgroundServiceFragment(17184): Restoring active backgrounds
10-05 13:49:29.588 D/BackgroundServiceFragment(17184): Restoring background drawable
10-05 13:49:29.663 D/ACRA    (17184): onActivityStopped class org.jellyfin.androidtv.ui.browsing.GenericGridActivity
10-05 13:49:29.664 D/ACRA    (17184): onActivityDestroyed class org.jellyfin.androidtv.ui.browsing.GenericGridActivity
10-05 13:49:29.668 D/MediaManager(17184): Removed event listener.  Total listeners: 1
10-05 13:49:31.188 D/ItemLauncher(17184): Item selected: 2 - 合集 (CollectionFolder)
10-05 13:49:31.188 D/ItemLauncher(17184): **** Collection type: boxsets
10-05 13:49:31.201 D/ACRA    (17184): onActivityPaused class org.jellyfin.androidtv.ui.browsing.MainActivity
10-05 13:49:31.211 W/ActivityThread(17184): handleWindowVisibility: no activity for token android.os.BinderProxy@b9038c2
10-05 13:49:31.216 D/ACRA    (17184): onActivityCreated class org.jellyfin.androidtv.ui.browsing.GenericGridActivity
10-05 13:49:31.216 I/AppThemeCallbacks(17184): Applying theme: DARK
10-05 13:49:31.223 D/ACRA    (17184): onActivityStarted class org.jellyfin.androidtv.ui.browsing.GenericGridActivity
10-05 13:49:31.225 I/BackgroundService(17184): Adding BackgroundServiceFragment to activity
10-05 13:49:31.227 D/StdGridFragment(17184): numCardsScreen <0>
10-05 13:49:31.248 E/ThemeUtils(17184): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-05 13:49:31.251 D/HorizontalGridPresenter(17184): mNumRows 3
10-05 13:49:31.251 D/HorizontalGridPresenter(17184): onBindViewHolder null
10-05 13:49:31.252 D/StdGridFragment(17184): buildAdapter cardHeight <248> getCardWidthBy <165> chunks <25> type <Items>
10-05 13:49:31.252 D/StdGridFragment(17184): buildAdapter adjusting chunkSize to <36> screenEst <33>
10-05 13:49:31.253 D/HorizontalGridPresenter(17184): onBindViewHolder org.jellyfin.androidtv.ui.itemhandling.ItemRowAdapter@ec5fb96
10-05 13:49:31.254 D/jellyfin-apiclient(17184): Adding request to queue: http://myemby.com:8096/Users/aad14edc-bdc3-4661-9b1a-fd61048feba1/Items?SortBy=SortName&recursive=true&Fields=PrimaryImageAspectRatio%2CChildCount%2CMediaSources%2CMediaStreams%2CDisplayPreferencesId&sortOrder=Ascending&Limit=36&IncludeItemTypes=BoxSet&format=json
10-05 13:49:31.256 D/ACRA    (17184): onActivityResumed class org.jellyfin.androidtv.ui.browsing.GenericGridActivity
10-05 13:49:31.257 D/BackgroundServiceFragment(17184): Restoring background drawable
10-05 13:49:31.266 D/MediaManager(17184): Added event listener.  Total listeners: 2
10-05 13:49:31.301 I/jellyfin-apiclient(17184): Response received from: http://myemby.com:8096/Users/aad14edc-bdc3-4661-9b1a-fd61048feba1/Items?SortBy=SortName&recursive=true&Fields=PrimaryImageAspectRatio%2CChildCount%2CMediaSources%2CMediaStreams%2CDisplayPreferencesId&sortOrder=Ascending&Limit=36&IncludeItemTypes=BoxSet&format=json
10-05 13:49:31.304 E/ThemeUtils(17184): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-05 13:49:31.312 D/GridFragment(17184): row selected position 0
10-05 13:49:31.315 E/ThemeUtils(17184): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-05 13:49:31.323 E/ThemeUtils(17184): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-05 13:49:31.331 E/ThemeUtils(17184): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-05 13:49:31.338 E/ThemeUtils(17184): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-05 13:49:31.346 E/ThemeUtils(17184): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-05 13:49:31.354 E/ThemeUtils(17184): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-05 13:49:31.382 D/OpenGLRenderer(17184): endAllActiveAnimators on 0x899a2600 (RelativeLayout) with handle 0x89b6d370
10-05 13:49:31.404 D/ACRA    (17184): onActivityStopped class org.jellyfin.androidtv.ui.browsing.MainActivity
10-05 13:49:31.405 D/ACRA    (17184): onActivitySaveInstanceState class org.jellyfin.androidtv.ui.browsing.MainActivity
10-05 13:49:31.869 D/ItemLauncher(17184): Item selected: 0 - gomypasuta (BoxSet)
10-05 13:49:31.882 D/ACRA    (17184): onActivityPaused class org.jellyfin.androidtv.ui.browsing.GenericGridActivity
10-05 13:49:31.890 W/ActivityThread(17184): handleWindowVisibility: no activity for token android.os.BinderProxy@5a9db6b
10-05 13:49:31.896 D/ACRA    (17184): onActivityCreated class org.jellyfin.androidtv.ui.browsing.CollectionActivity
10-05 13:49:31.896 I/AppThemeCallbacks(17184): Applying theme: DARK
10-05 13:49:31.903 D/ACRA    (17184): onActivityStarted class org.jellyfin.androidtv.ui.browsing.CollectionActivity
10-05 13:49:31.908 E/ThemeUtils(17184): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-05 13:49:31.913 I/BackgroundService(17184): Adding BackgroundServiceFragment to activity
10-05 13:49:31.915 D/jellyfin-apiclient(17184): Adding request to queue: http://myemby.com:8096/Users/aad14edc-bdc3-4661-9b1a-fd61048feba1/Items?ParentId=928533e9b3d32aa0524c2e207eacc05b&recursive=false&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount%2CMediaStreams%2CMediaSources&Limit=100&IncludeItemTypes=Movie&format=json
10-05 13:49:31.916 D/jellyfin-apiclient(17184): Adding request to queue: http://myemby.com:8096/Users/aad14edc-bdc3-4661-9b1a-fd61048feba1/Items?ParentId=928533e9b3d32aa0524c2e207eacc05b&recursive=false&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount&Limit=100&IncludeItemTypes=Series&format=json
10-05 13:49:31.917 D/jellyfin-apiclient(17184): Adding request to queue: http://myemby.com:8096/Users/aad14edc-bdc3-4661-9b1a-fd61048feba1/Items?ParentId=928533e9b3d32aa0524c2e207eacc05b&recursive=false&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount&Limit=100&ExcludeItemTypes=Movie%2CSeries&format=json
10-05 13:49:31.919 D/ACRA    (17184): onActivityResumed class org.jellyfin.androidtv.ui.browsing.CollectionActivity
10-05 13:49:31.920 D/BackgroundServiceFragment(17184): Restoring background drawable
10-05 13:49:31.928 D/MediaManager(17184): Added event listener.  Total listeners: 3
10-05 13:49:31.948 W/View    (17184): requestLayout() improperly called by android.widget.TextView{3b53b32 V.ED..... ......ID 120,40-1578,126 #7f0b02f4 app:id/title} during layout: running second layout pass
10-05 13:49:31.948 W/View    (17184): requestLayout() improperly called by android.widget.LinearLayout{6dfa083 V.E...... ......ID 120,132-1598,172 #7f0b01a0 app:id/infoRow} during layout: running second layout pass
10-05 13:49:31.952 I/jellyfin-apiclient(17184): Response received from: http://myemby.com:8096/Users/aad14edc-bdc3-4661-9b1a-fd61048feba1/Items?ParentId=928533e9b3d32aa0524c2e207eacc05b&recursive=false&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount%2CMediaStreams%2CMediaSources&Limit=100&IncludeItemTypes=Movie&format=json
10-05 13:49:31.961 I/jellyfin-apiclient(17184): Response received from: http://myemby.com:8096/Users/aad14edc-bdc3-4661-9b1a-fd61048feba1/Items?ParentId=928533e9b3d32aa0524c2e207eacc05b&recursive=false&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount&Limit=100&IncludeItemTypes=Series&format=json
10-05 13:49:31.961 I/jellyfin-apiclient(17184): Response received from: http://myemby.com:8096/Users/aad14edc-bdc3-4661-9b1a-fd61048feba1/Items?ParentId=928533e9b3d32aa0524c2e207eacc05b&recursive=false&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount&Limit=100&ExcludeItemTypes=Movie%2CSeries&format=json
10-05 13:49:31.975 E/ThemeUtils(17184): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-05 13:49:31.987 E/ThemeUtils(17184): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-05 13:49:31.995 E/ThemeUtils(17184): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-05 13:49:32.003 E/ThemeUtils(17184): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-05 13:49:32.010 W/View    (17184): requestLayout() improperly called by androidx.leanback.widget.HorizontalGridView{a67ddd5 VFE...... .....AID 0,0-1920,88 #7f0b0269 app:id/row_content} during layout: running second layout pass
10-05 13:49:32.010 W/View    (17184): requestLayout() improperly called by android.widget.TextView{3b53b32 V.ED..... ......ID 120,40-1578,126 #7f0b02f4 app:id/title} during layout: running second layout pass
10-05 13:49:32.011 W/View    (17184): requestLayout() improperly called by android.widget.LinearLayout{6dfa083 V.E...... ......ID 120,132-1598,172 #7f0b01a0 app:id/infoRow} during layout: running second layout pass
10-05 13:49:32.035 D/OpenGLRenderer(17184): endAllActiveAnimators on 0x899b1300 (RelativeLayout) with handle 0x87cedf30
10-05 13:49:32.102 D/ACRA    (17184): onActivityStopped class org.jellyfin.androidtv.ui.browsing.GenericGridActivity
10-05 13:49:32.103 D/ACRA    (17184): onActivitySaveInstanceState class org.jellyfin.androidtv.ui.browsing.GenericGridActivity
10-05 13:49:32.637 D/ACRA    (17184): onActivityPaused class org.jellyfin.androidtv.ui.browsing.CollectionActivity
10-05 13:49:32.647 D/ACRA    (17184): onActivityStarted class org.jellyfin.androidtv.ui.browsing.GenericGridActivity
10-05 13:49:32.648 D/ACRA    (17184): onActivityResumed class org.jellyfin.androidtv.ui.browsing.GenericGridActivity
10-05 13:49:32.649 D/BackgroundServiceFragment(17184): Restoring active backgrounds
10-05 13:49:32.650 D/BackgroundServiceFragment(17184): Restoring background drawable
10-05 13:49:32.713 D/ACRA    (17184): onActivityStopped class org.jellyfin.androidtv.ui.browsing.CollectionActivity
10-05 13:49:32.714 D/ACRA    (17184): onActivityDestroyed class org.jellyfin.androidtv.ui.browsing.CollectionActivity
10-05 13:49:32.717 D/MediaManager(17184): Removed event listener.  Total listeners: 2
10-05 13:49:33.149 D/StdGridFragment(17184): Refresh item "gomypasuta"
10-05 13:49:33.150 D/jellyfin-apiclient(17184): Adding request to queue: http://myemby.com:8096/Users/aad14edc-bdc3-4661-9b1a-fd61048feba1/Items/928533e9b3d32aa0524c2e207eacc05b?format=json
10-05 13:49:33.157 I/jellyfin-apiclient(17184): Response received from: http://myemby.com:8096/Users/aad14edc-bdc3-4661-9b1a-fd61048feba1/Items/928533e9b3d32aa0524c2e207eacc05b?format=json
10-05 13:49:33.167 D/GridFragment(17184): row selected position 0
10-05 13:49:33.312 D/ACRA    (17184): onActivityPaused class org.jellyfin.androidtv.ui.browsing.GenericGridActivity
10-05 13:49:33.321 D/ACRA    (17184): onActivityStarted class org.jellyfin.androidtv.ui.browsing.MainActivity
10-05 13:49:33.323 D/ACRA    (17184): onActivityResumed class org.jellyfin.androidtv.ui.browsing.MainActivity
10-05 13:49:33.324 I/HomeFragment(17184): Updating audio queue in HomeFragment (onResume)
10-05 13:49:33.325 D/BackgroundServiceFragment(17184): Restoring active backgrounds
10-05 13:49:33.325 D/BackgroundServiceFragment(17184): Restoring background drawable
10-05 13:49:33.326 D/BackgroundServiceFragment(17184): Restoring active backgrounds
10-05 13:49:33.326 D/BackgroundServiceFragment(17184): Restoring background drawable
10-05 13:49:33.399 D/ACRA    (17184): onActivityStopped class org.jellyfin.androidtv.ui.browsing.GenericGridActivity
10-05 13:49:33.400 D/ACRA    (17184): onActivityDestroyed class org.jellyfin.androidtv.ui.browsing.GenericGridActivity
10-05 13:49:33.404 D/MediaManager(17184): Removed event listener.  Total listeners: 1
10-05 13:49:33.418 D/AndroidRuntime(17184): Shutting down VM
--------- beginning of crash
10-05 13:49:33.418 E/AndroidRuntime(17184): FATAL EXCEPTION: main
10-05 13:49:33.418 E/AndroidRuntime(17184): Process: org.jellyfin.androidtv, PID: 17184
10-05 13:49:33.418 E/AndroidRuntime(17184): java.lang.IllegalStateException: Fragment BrowseGridFragment{ab4d9c3} (88a0cefe-743d-4d0e-9ac5-a71800723413) not attached to a context.
10-05 13:49:33.418 E/AndroidRuntime(17184): 	at androidx.fragment.app.Fragment.requireContext(Fragment.java:967)
10-05 13:49:33.418 E/AndroidRuntime(17184): 	at org.jellyfin.androidtv.ui.GridFragment.setItem(GridFragment.java:155)
10-05 13:49:33.418 E/AndroidRuntime(17184): 	at org.jellyfin.androidtv.ui.browsing.StdGridFragment$10.run(StdGridFragment.java:788)
10-05 13:49:33.418 E/AndroidRuntime(17184): 	at android.os.Handler.handleCallback(Handler.java:873)
10-05 13:49:33.418 E/AndroidRuntime(17184): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-05 13:49:33.418 E/AndroidRuntime(17184): 	at android.os.Looper.loop(Looper.java:211)
10-05 13:49:33.418 E/AndroidRuntime(17184): 	at android.app.ActivityThread.main(ActivityThread.java:6740)
10-05 13:49:33.418 E/AndroidRuntime(17184): 	at java.lang.reflect.Method.invoke(Native Method)
10-05 13:49:33.418 E/AndroidRuntime(17184): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-05 13:49:33.418 E/AndroidRuntime(17184): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
10-05 13:49:33.419 E/ACRA    (17184): ACRA caught a IllegalStateException for org.jellyfin.androidtv
10-05 13:49:33.419 E/ACRA    (17184): java.lang.IllegalStateException: Fragment BrowseGridFragment{ab4d9c3} (88a0cefe-743d-4d0e-9ac5-a71800723413) not attached to a context.
10-05 13:49:33.419 E/ACRA    (17184): 	at androidx.fragment.app.Fragment.requireContext(Fragment.java:967)
10-05 13:49:33.419 E/ACRA    (17184): 	at org.jellyfin.androidtv.ui.GridFragment.setItem(GridFragment.java:155)
10-05 13:49:33.419 E/ACRA    (17184): 	at org.jellyfin.androidtv.ui.browsing.StdGridFragment$10.run(StdGridFragment.java:788)
10-05 13:49:33.419 E/ACRA    (17184): 	at android.os.Handler.handleCallback(Handler.java:873)
10-05 13:49:33.419 E/ACRA    (17184): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-05 13:49:33.419 E/ACRA    (17184): 	at android.os.Looper.loop(Looper.java:211)
10-05 13:49:33.419 E/ACRA    (17184): 	at android.app.ActivityThread.main(ActivityThread.java:6740)
10-05 13:49:33.419 E/ACRA    (17184): 	at java.lang.reflect.Method.invoke(Native Method)
10-05 13:49:33.419 E/ACRA    (17184): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-05 13:49:33.419 E/ACRA    (17184): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
10-05 13:49:33.419 D/ACRA    (17184): Building report
10-05 13:49:33.420 D/ACRA    (17184): Starting collectors with priority FIRST
10-05 13:49:33.421 D/ACRA    (17184): Calling collector org.acra.collector.DropBoxCollector
10-05 13:49:33.421 D/ACRA    (17184): Collector org.acra.collector.DropBoxCollector completed
10-05 13:49:33.421 D/ACRA    (17184): Calling collector org.acra.collector.LogCatCollector
10-05 13:49:33.421 D/ACRA    (17184): Calling collector org.acra.collector.StacktraceCollector
10-05 13:49:33.422 D/ACRA    (17184): Collector org.acra.collector.StacktraceCollector completed
10-05 13:49:33.423 D/ACRA    (17184): Retrieving logcat output (buffer:default)...

### Application version

0.14.3

### Where did you install the app from?

amazon app store

### Device information

fire tv 4k stick max

### Android version

Fire OS 7

### Jellyfin server version

10.8.5

**Comment by seth100** [comment]
Same issue happened to me! 
Same Fire Stick, app and OS version

**Comment by wjbridge** [comment]
Same here. Using a Nvidia Shield Pro.

```
---
   2   │ client: Jellyfin for Android TV
   3   │ client_version: 0.14.4
   4   │ client_repository: https://github.com/jellyfin/jellyfin-androidtv
   5   │ type: crash_report
   6   │ format: markdown
   7   │ ---
   8   │ ### Logs
   9   │
  10   │ ***Stack Trace***:
  11   │ ```log
  12   │ java.lang.IllegalStateException: Fragment BrowseGridFragment{84905a5} (7aebd97c-3a6c-473b-9439-3567b6e532a5) not attached to a context.
  13   │     at androidx.fragment.app.Fragment.requireContext(Fragment.java:967)
  14   │     at org.jellyfin.androidtv.ui.browsing.StdGridFragment.refreshCurrentItem(StdGridFragment.java:753)
  15   │     at org.jellyfin.androidtv.ui.browsing.StdGridFragment.lambda$onResume$0$org-jellyfin-androidtv-ui-browsing-StdGridFragment(StdGridFrag
       │ ment.java:429)
  16   │     at org.jellyfin.androidtv.ui.browsing.StdGridFragment$$ExternalSyntheticLambda0.run(Unknown Source:2)
  17   │     at android.os.Handler.handleCallback(Handler.java:938)
  18   │     at android.os.Handler.dispatchMessage(Handler.java:99)
  19   │     at android.os.Looper.loop(Looper.java:223)
  20   │     at android.app.ActivityThread.main(ActivityThread.java:7668)
  21   │     at java.lang.reflect.Method.invoke(Native Method)
  22   │     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
  23   │     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

More Details:
```
  83   │ 10-28 22:37:35.152 E/ThemeUtils(23676): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used w
       │ ith a Theme.AppCompat theme (or descendant).
  84   │ 10-28 22:37:35.159 E/ThemeUtils(23676): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used w
       │ ith a Theme.AppCompat theme (or descendant).
  85   │ 10-28 22:37:35.173 D/ACRA    (23676): onActivityStopped class org.jellyfin.androidtv.ui.browsing.GenericGridActivity
  86   │ 10-28 22:37:35.173 D/ACRA    (23676): onActivitySaveInstanceState class org.jellyfin.androidtv.ui.browsing.GenericGridActivity
  87   │ 10-28 22:37:35.184 E/Surface (23676): freeAllBuffers: 1 buffers were freed while being dequeued!
  88   │ 10-28 22:37:35.617 D/FullDetailsActivity(23676): current time 1667011055616 last playback event time 0 last refresh time 1667011054964
  89   │ 10-28 22:37:36.121 D/ACRA    (23676): onActivityPaused class org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity
  90   │ 10-28 22:37:36.128 D/ACRA    (23676): onActivityStarted class org.jellyfin.androidtv.ui.browsing.GenericGridActivity
  91   │ 10-28 22:37:36.129 D/ACRA    (23676): onActivityResumed class org.jellyfin.androidtv.ui.browsing.GenericGridActivity
  92   │ 10-28 22:37:36.130 D/BackgroundServiceFragment(23676): Restoring active backgrounds
  93   │ 10-28 22:37:36.130 D/BackgroundServiceFragment(23676): Restoring background drawable
  94   │ 10-28 22:37:36.151 E/libc    (23676): Access denied finding property "ro.vendor.sys.NV_ASYNC"
  95   │ 10-28 22:37:36.151 E/libc    (23676): Access denied finding property "ro.vendor.sys.NV_LOGFPS"
  96   │ 10-28 22:37:36.151 E/libc    (23676): Access denied finding property "ro.vendor.sys.NV_PROCESS_NAME"
  97   │ 10-28 22:37:36.151 E/libc    (23676): Access denied finding property "ro.vendor.sys.NV_FPSDYNAMIC"
  98   │ 10-28 22:37:36.364 D/ACRA    (23676): onActivityPaused class org.jellyfin.androidtv.ui.browsing.GenericGridActivity
  99   │ 10-28 22:37:36.376 D/ACRA    (23676): onActivityStarted class org.jellyfin.androidtv.ui.browsing.MainActivity
 100   │ 10-28 22:37:36.379 D/ACRA    (23676): onActivityResumed class org.jellyfin.androidtv.ui.browsing.MainActivity
 101   │ 10-28 22:37:36.379 I/HomeFragment(23676): Updating audio queue in HomeFragment (onResume)
 102   │ 10-28 22:37:36.380 D/BackgroundServiceFragment(23676): Restoring active backgrounds
 103   │ 10-28 22:37:36.380 D/BackgroundServiceFragment(23676): Restoring background drawable
 104   │ 10-28 22:37:36.381 D/BackgroundServiceFragment(23676): Restoring active backgrounds
 105   │ 10-28 22:37:36.381 D/BackgroundServiceFragment(23676): Restoring background drawable
 106   │ 10-28 22:37:36.398 E/libc    (23676): Access denied finding property "ro.vendor.sys.NV_ASYNC"
 107   │ 10-28 22:37:36.398 E/libc    (23676): Access denied finding property "ro.vendor.sys.NV_LOGFPS"
 108   │ 10-28 22:37:36.398 E/libc    (23676): Access denied finding property "ro.vendor.sys.NV_PROCESS_NAME"
 109   │ 10-28 22:37:36.398 E/libc    (23676): Access denied finding property "ro.vendor.sys.NV_FPSDYNAMIC"
 110   │ 10-28 22:37:36.428 E/Surface (23676): freeAllBuffers: 1 buffers were freed while being dequeued!
 111   │ 10-28 22:37:36.464 D/ACRA    (23676): onActivityStopped class org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity
 112   │ 10-28 22:37:36.465 D/ACRA    (23676): onActivityDestroyed class org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity
 113   │ 10-28 22:37:36.470 D/MediaManager(23676): Removed event listener.  Total listeners: 2
 114   │ 10-28 22:37:36.624 E/Surface (23676): freeAllBuffers: 1 buffers were freed while being dequeued!
 115   │ 10-28 22:37:36.631 D/ACRA    (23676): onActivityStopped class org.jellyfin.androidtv.ui.browsing.GenericGridActivity
 116   │ 10-28 22:37:36.632 D/ACRA    (23676): onActivityDestroyed class org.jellyfin.androidtv.ui.browsing.GenericGridActivity
 117   │ 10-28 22:37:36.635 D/MediaManager(23676): Removed event listener.  Total listeners: 1
 118   │ 10-28 22:37:36.639 D/AndroidRuntime(23676): Shutting down VM
 119   │ --------- beginning of crash
 120   │ 10-28 22:37:36.640 E/AndroidRuntime(23676): FATAL EXCEPTION: main
 121   │ 10-28 22:37:36.640 E/AndroidRuntime(23676): Process: org.jellyfin.androidtv, PID: 23676
 122   │ 10-28 22:37:36.640 E/AndroidRuntime(23676): java.lang.IllegalStateException: Fragment BrowseGridFragment{84905a5} (7aebd97c-3a6c-473b-9439
       │ -3567b6e532a5) not attached to a context.
 123   │ 10-28 22:37:36.640 E/AndroidRuntime(23676):     at androidx.fragment.app.Fragment.requireContext(Fragment.java:967)
 124   │ 10-28 22:37:36.640 E/AndroidRuntime(23676):     at org.jellyfin.androidtv.ui.browsing.StdGridFragment.refreshCurrentItem(StdGridFragment.j
       │ ava:753)
 125   │ 10-28 22:37:36.640 E/AndroidRuntime(23676):     at org.jellyfin.androidtv.ui.browsing.StdGridFragment.lambda$onResume$0$org-jellyfin-andro
       │ idtv-ui-browsing-StdGridFragment(StdGridFragment.java:429)
 126   │ 10-28 22:37:36.640 E/AndroidRuntime(23676):     at org.jellyfin.androidtv.ui.browsing.StdGridFragment$$ExternalSyntheticLambda0.run(Unknow
       │ n Source:2)
 127   │ 10-28 22:37:36.640 E/AndroidRuntime(23676):     at android.os.Handler.handleCallback(Handler.java:938)
 128   │ 10-28 22:37:36.640 E/AndroidRuntime(23676):     at android.os.Handler.dispatchMessage(Handler.java:99)
 129   │ 10-28 22:37:36.640 E/AndroidRuntime(23676):     at android.os.Looper.loop(Looper.java:223)
 130   │ 10-28 22:37:36.640 E/AndroidRuntime(23676):     at android.app.ActivityThread.main(ActivityThread.java:7668)
 131   │ 10-28 22:37:36.640 E/AndroidRuntime(23676):     at java.lang.reflect.Method.invoke(Native Method)
 132   │ 10-28 22:37:36.640 E/AndroidRuntime(23676):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
 133   │ 10-28 22:37:36.640 E/AndroidRuntime(23676):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
 134   │ 10-28 22:37:36.640 E/ACRA    (23676): ACRA caught a IllegalStateException for org.jellyfin.androidtv
 135   │ 10-28 22:37:36.640 E/ACRA    (23676): java.lang.IllegalStateException: Fragment BrowseGridFragment{84905a5} (7aebd97c-3a6c-473b-9439-3567b
       │ 6e532a5) not attached to a context.
 136   │ 10-28 22:37:36.640 E/ACRA    (23676):   at androidx.fragment.app.Fragment.requireContext(Fragment.java:967)
 137   │ 10-28 22:37:36.640 E/ACRA    (23676):   at org.jellyfin.androidtv.ui.browsing.StdGridFragment.refreshCurrentItem(StdGridFragment.java:753)
 138   │ 10-28 22:37:36.640 E/ACRA    (23676):   at org.jellyfin.androidtv.ui.browsing.StdGridFragment.lambda$onResume$0$org-jellyfin-androidtv-ui-
       │ browsing-StdGridFragment(StdGridFragment.java:429)
 139   │ 10-28 22:37:36.640 E/ACRA    (23676):   at org.jellyfin.androidtv.ui.browsing.StdGridFragment$$ExternalSyntheticLambda0.run(Unknown Source
       │ :2)
 140   │ 10-28 22:37:36.640 E/ACRA    (23676):   at android.os.Handler.handleCallback(Handler.java:938)
 141   │ 10-28 22:37:36.640 E/ACRA    (23676):   at android.os.Handler.dispatchMessage(Handler.java:99)
 142   │ 10-28 22:37:36.640 E/ACRA    (23676):   at android.os.Looper.loop(Looper.java:223)
 143   │ 10-28 22:37:36.640 E/ACRA    (23676):   at android.app.ActivityThread.main(ActivityThread.java:7668)
 144   │ 10-28 22:37:36.640 E/ACRA    (23676):   at java.lang.reflect.Method.invoke(Native Method)
 145   │ 10-28 22:37:36.640 E/ACRA    (23676):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
 146   │ 10-28 22:37:36.640 E/ACRA    (23676):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by nielsvanvelzen** [comment]
This issue should be fixed in the upcoming 0.15 release. It required quite a lot of code changes so we can't backport it to the current 0.14 version.

**Comment by wjbridge** [comment]
Thanks @nielsvanvelzen for the info! Approx when is the upcoming 0.15 release? Are we talking weeks or months out? It is crashing for me about four times a day but I know this is open source so just trying to get an idea.

**Comment by nielsvanvelzen** [comment]
I'm hoping to release the first beta in the coming weeks. So you can opt into the beta program on Google Play to receive those beta updates.
