### ISSUE TITLE
Crash when using jellyfin-plugin-intros and starting a movie

### ISSUE THREAD

**Issue by mooninite** [jellyfin/jellyfin-androidtv#2163]
### Describe the bug

1. Install the https://github.com/dkanada/jellyfin-plugin-intros plugin
2. Play a movie

The Android TV app immediately crashes.

Playing a TV Show does not trigger intros (another bug?, but the crasher is more important).

### Logs

---
client: Jellyfin for Android TV
client_version: 0.14.4
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at org.jellyfin.androidtv.ui.playback.VideoManager.setExoPlayerTrack(VideoManager.java:536)
	at org.jellyfin.androidtv.ui.playback.PlaybackController.switchAudioStream(PlaybackController.java:945)
	at org.jellyfin.androidtv.ui.playback.PlaybackController.onPrepared(PlaybackController.java:1492)
	at org.jellyfin.androidtv.ui.playback.VideoManager$1.onIsPlayingChanged(VideoManager.java:121)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$24(ExoPlayerImpl.java:1944)
	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda8.invoke(Unknown Source:4)
	at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:281)
	at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:190)
	at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:211)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1955)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlayWhenReady(ExoPlayerImpl.java:2553)
	at com.google.android.exoplayer2.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:744)
	at org.jellyfin.androidtv.ui.playback.VideoManager.start(VideoManager.java:315)
	at org.jellyfin.androidtv.ui.playback.PlaybackController$7.run(PlaybackController.java:861)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```  
***Logcat***: 
```log
--------- beginning of main
10-09 19:30:26.347 I/ExoPlayerImpl(11080): Init 70cc746 [ExoPlayerLib/2.18.1] [sabrina, Chromecast, Google, 29]
10-09 19:30:26.357 I/DefaultRenderersFactory(11080): Loaded FfmpegAudioRenderer.
10-09 19:30:26.376 D/PlaybackController(11080): Play called from state: IDLE with pos: 0 and sub index: null
10-09 19:30:26.376 D/PlaybackController(11080): Max bitrate is: 100000000
10-09 19:30:26.382 I/PlaybackController(11080): *** Using extended Exoplayer profile options
10-09 19:30:26.385 D/jellyfin-apiclient(11080): Adding request to queue: https://foo.bar.com/Items/8312cd9345d24a9188ce7d96255737a0/PlaybackInfo?format=json
10-09 19:30:26.388 D/ACRA    (11080): onActivityResumed class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
10-09 19:30:26.388 W/AudioManager(11080): Use of stream types is deprecated for operations other than volume control
10-09 19:30:26.388 W/AudioManager(11080): See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
10-09 19:30:26.825 I/jellyfin-apiclient(11080): Response received from: https://foo.bar.com/Items/8312cd9345d24a9188ce7d96255737a0/PlaybackInfo?format=json
10-09 19:30:26.828 I/PlaybackController(11080): VLC would direct stream
10-09 19:30:26.831 D/jellyfin-apiclient(11080): Adding request to queue: https://foo.bar.com/Items/8312cd9345d24a9188ce7d96255737a0/PlaybackInfo?format=json
10-09 19:30:26.862 I/jellyfin-apiclient(11080): Response received from: https://foo.bar.com/Items/8312cd9345d24a9188ce7d96255737a0/PlaybackInfo?format=json
10-09 19:30:26.864 I/PlaybackController(11080): Internal player would direct stream
10-09 19:30:26.865 I/PlaybackController(11080): Explicit deinterlacing will NOT be used
10-09 19:30:26.866 I/PlaybackController(11080): User preferred player is: EXOPLAYER
10-09 19:30:26.866 I/PlaybackController(11080): Will use internal player
10-09 19:30:26.895 I/VideoManager(11080): Network buffer set to 600
10-09 19:30:26.901 W/libOpenSLES(11080): class OutputMix interface 0 requested but unavailable MPH=43
10-09 19:30:26.903 D/VideoManager(11080): Surface attached
10-09 19:30:26.903 D/PlaybackController(11080): default audio index set to 1
10-09 19:30:26.904 D/PlaybackController(11080): default audio index set to 1 remote default 1
10-09 19:30:26.904 D/PlaybackController(11080): default sub index set to -1 remote default null
10-09 19:30:26.905 I/PlaybackController(11080): Playing back in native mode.
10-09 19:30:26.906 D/VideoManager(11080): Setting playback speed: 1.000000
10-09 19:30:26.910 I/VideoManager(11080): Video path set to: https://foo.bar.com/Videos/8312cd9345d24a9188ce7d96255737a0/stream.mov?api_key=3c1e3d87052c4f8c9009955f45a2034a&DeviceId=f8cc80686dbc17df2ea81e7029b2b3729580e44c&MediaSourceId=8312cd9345d24a9188ce7d96255737a0&Tag=570ecfb44f098d2268fcb8128f940165&Static=true
10-09 19:30:26.914 D/VideoManager(11080): Caught player timeline change - reason: PLAYLIST_CHANGED
10-09 19:30:26.916 D/VideoManager(11080): Player is buffering
10-09 19:30:26.917 D/jellyfin-apiclient(11080): Adding request to queue: https://foo.bar.com/Sessions/Playing
10-09 19:30:26.918 I/ReportingHelper(11080): Playback of Netflix Modern  Preroll started.
10-09 19:30:26.933 D/VideoManager(11080): Caught player timeline change - reason: SOURCE_UPDATE
10-09 19:30:26.952 W/libEGL  (11080): EGLNativeWindowType 0xbf80e4e8 disconnect failed
10-09 19:30:26.956 I/jellyfin-apiclient(11080): Response received from: https://foo.bar.com/Sessions/Playing
10-09 19:30:26.965 D/ACRA    (11080): onActivityStopped class org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity
10-09 19:30:26.967 D/ACRA    (11080): onActivitySaveInstanceState class org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity
10-09 19:30:26.971 D/VideoManager(11080): Caught player timeline change - reason: SOURCE_UPDATE
10-09 19:30:26.982 I/OMXClient(11080): IOmx service obtained
10-09 19:30:26.989 D/VideoManager(11080): Tracks changed
10-09 19:30:26.998 D/SurfaceUtils(11080): connecting to surface 0xc952d008, reason connectToSurface
10-09 19:30:26.999 I/MediaCodec(11080): [OMX.amlogic.avc.decoder.awesome2] setting surface generation to 11345923
10-09 19:30:26.999 D/SurfaceUtils(11080): disconnecting from surface 0xc952d008, reason connectToSurface(reconnect)
10-09 19:30:27.000 D/SurfaceUtils(11080): connecting to surface 0xc952d008, reason connectToSurface(reconnect)
10-09 19:30:27.001 E/ACodec  (11080): [OMX.amlogic.avc.decoder.awesome2] setPortMode on output to DynamicANWBuffer failed w/ err -2147483648
10-09 19:30:27.007 I/ACodec  (11080): codec does not support config priority (err -1010)
10-09 19:30:27.031 D/SurfaceUtils(11080): disconnecting from surface 0xc952d008, reason setNativeWindowSizeFormatAndUsage
10-09 19:30:27.031 D/SurfaceUtils(11080): connecting to surface 0xc952d008, reason setNativeWindowSizeFormatAndUsage
10-09 19:30:27.031 D/SurfaceUtils(11080): set up nativeWindow 0xc952d008 for 1920x1080, color 0x11, rotation 0, usage 0x402933
10-09 19:30:27.037 W/gralloc (11080): Buffer descriptor with invalid usage bits 0x2000
10-09 19:30:27.039 W/gralloc (11080): Buffer descriptor with invalid usage bits 0x2000
10-09 19:30:27.040 W/gralloc (11080): Buffer descriptor with invalid usage bits 0x2000
10-09 19:30:27.042 W/gralloc (11080): Buffer descriptor with invalid usage bits 0x2000
10-09 19:30:27.044 W/gralloc (11080): Buffer descriptor with invalid usage bits 0x2000
10-09 19:30:27.045 W/gralloc (11080): Buffer descriptor with invalid usage bits 0x2000
10-09 19:30:27.047 W/gralloc (11080): Buffer descriptor with invalid usage bits 0x2000
10-09 19:30:27.049 W/gralloc (11080): Buffer descriptor with invalid usage bits 0x2000
10-09 19:30:27.140 D/CCodec  (11080): allocate(c2.android.aac.decoder)
10-09 19:30:27.144 I/Codec2Client(11080): Available Codec2 services: "software"
10-09 19:30:27.144 I/Codec2Client(11080): Creating a Codec2 client to service "software"
10-09 19:30:27.147 I/Codec2Client(11080): Client to Codec2 service "software" created
10-09 19:30:27.157 I/CCodec  (11080): Created component [c2.android.aac.decoder]
10-09 19:30:27.158 D/CCodecConfig(11080): read media type: audio/mp4a-latm
10-09 19:30:27.160 D/ReflectedParamUpdater(11080): extent() != 1 for single value type: algo.buffers.max-count.values
10-09 19:30:27.161 D/ReflectedParamUpdater(11080): extent() != 1 for single value type: output.subscribed-indices.values
10-09 19:30:27.161 D/ReflectedParamUpdater(11080): extent() != 1 for single value type: input.buffers.allocator-ids.values
10-09 19:30:27.161 D/ReflectedParamUpdater(11080): extent() != 1 for single value type: output.buffers.allocator-ids.values
10-09 19:30:27.161 D/ReflectedParamUpdater(11080): extent() != 1 for single value type: algo.buffers.allocator-ids.values
10-09 19:30:27.161 D/ReflectedParamUpdater(11080): extent() != 1 for single value type: output.buffers.pool-ids.values
10-09 19:30:27.161 D/ReflectedParamUpdater(11080): extent() != 1 for single value type: algo.buffers.pool-ids.values
10-09 19:30:27.166 I/CCodecConfig(11080): query failed after returning 16 values (BAD_INDEX)
10-09 19:30:27.166 D/CCodecConfig(11080): c2 config is Dict {
10-09 19:30:27.166 D/CCodecConfig(11080):   c2::u32 coded.aac-packaging.value = 0
10-09 19:30:27.166 D/CCodecConfig(11080):   c2::u32 coded.bitrate.value = 64000
10-09 19:30:27.166 D/CCodecConfig(11080):   c2::u32 coded.pl.level = 0
10-09 19:30:27.166 D/CCodecConfig(11080):   c2::u32 coded.pl.profile = 8192
10-09 19:30:27.166 D/CCodecConfig(11080):   c2::float coding.drc.attenuation-factor.value = 1
10-09 19:30:27.166 D/CCodecConfig(11080):   c2::float coding.drc.boost-factor.value = 1
10-09 19:30:27.166 D/CCodecConfig(11080):   c2::i32 coding.drc.compression-mode.value = 3
10-09 19:30:27.166 D/CCodecConfig(11080):   c2::i32 coding.drc.effect-type.value = 3
10-09 19:30:27.166 D/CCodecConfig(11080):   c2::float coding.drc.encoded-level.value = 0.25
10-09 19:30:27.166 D/CCodecConfig(11080):   c2::float coding.drc.reference-level.value = -16
10-09 19:30:27.166 D/CCodecConfig(11080):   c2::u32 input.buffers.max-size.value = 8192
10-09 19:30:27.166 D/CCodecConfig(11080):   c2::u32 input.delay.value = 0
10-09 19:30:27.166 D/CCodecConfig(11080):   string input.media-type.value = "audio/mp4a-latm"
10-09 19:30:27.166 D/CCodecConfig(11080):   c2::u32 output.delay.value = 2
10-09 19:30:27.166 D/CCodecConfig(11080):   string output.media-type.value = "audio/raw"
10-09 19:30:27.166 D/CCodecConfig(11080):   c2::u32 raw.channel-count.value = 1
10-09 19:30:27.166 D/CCodecConfig(11080):   c2::u32 raw.sample-rate.value = 44100
10-09 19:30:27.166 D/CCodecConfig(11080): }
10-09 19:30:27.168 D/CCodecConfig(11080): config failed => CORRUPTED
10-09 19:30:27.168 D/CCodecConfig(11080): c2 config is Dict {
10-09 19:30:27.168 D/CCodecConfig(11080):   c2::u32 coded.aac-packaging.value = 0
10-09 19:30:27.168 D/CCodecConfig(11080):   c2::u32 coded.bitrate.value = 64000
10-09 19:30:27.168 D/CCodecConfig(11080):   c2::u32 coded.pl.level = 0
10-09 19:30:27.168 D/CCodecConfig(11080):   c2::u32 coded.pl.profile = 8192
10-09 19:30:27.168 D/CCodecConfig(11080):   c2::float coding.drc.attenuation-factor.value = 1
10-09 19:30:27.168 D/CCodecConfig(11080):   c2::float coding.drc.boost-factor.value = 1
10-09 19:30:27.168 D/CCodecConfig(11080):   c2::i32 coding.drc.compression-mode.value = 3
10-09 19:30:27.168 D/CCodecConfig(11080):   c2::i32 coding.drc.effect-type.value = 3
10-09 19:30:27.168 D/CCodecConfig(11080):   c2::float coding.drc.encoded-level.value = 0.25
10-09 19:30:27.168 D/CCodecConfig(11080):   c2::float coding.drc.reference-level.value = -16
10-09 19:30:27.168 D/CCodecConfig(11080):   c2::u32 input.buffers.max-size.value = 8192
10-09 19:30:27.168 D/CCodecConfig(11080):   c2::u32 input.delay.value = 0
10-09 19:30:27.168 D/CCodecConfig(11080):   string input.media-type.value = "audio/mp4a-latm"
10-09 19:30:27.168 D/CCodecConfig(11080):   c2::u32 output.delay.value = 2
10-09 19:30:27.168 D/CCodecConfig(11080):   string output.media-type.value = "audio/raw"
10-09 19:30:27.168 D/CCodecConfig(11080):   c2::u32 raw.channel-count.value = 2
10-09 19:30:27.168 D/CCodecConfig(11080):   c2::u32 raw.sample-rate.value = 48000
10-09 19:30:27.168 D/CCodecConfig(11080): }
10-09 19:30:27.169 W/Codec2Client(11080): query -- param skipped: index = 1107298332.
10-09 19:30:27.170 D/CCodec  (11080): client requested max input size 949, which is smaller than what component recommended (8192); overriding with component recommendation.
10-09 19:30:27.170 W/CCodec  (11080): This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
10-09 19:30:27.170 D/CCodec  (11080): setup formats input: AMessage(what = 0x00000000) = {
10-09 19:30:27.170 D/CCodec  (11080):   int32_t channel-count = 2
10-09 19:30:27.170 D/CCodec  (11080):   int32_t level = 0
10-09 19:30:27.170 D/CCodec  (11080):   int32_t max-input-size = 8192
10-09 19:30:27.170 D/CCodec  (11080):   string mime = "audio/mp4a-latm"
10-09 19:30:27.170 D/CCodec  (11080):   int32_t profile = 2
10-09 19:30:27.170 D/CCodec  (11080):   int32_t sample-rate = 48000
10-09 19:30:27.170 D/CCodec  (11080): } and output: AMessage(what = 0x00000000) = {
10-09 19:30:27.170 D/CCodec  (11080):   int32_t channel-count = 2
10-09 19:30:27.170 D/CCodec  (11080):   string mime = "audio/raw"
10-09 19:30:27.170 D/CCodec  (11080):   int32_t sample-rate = 48000
10-09 19:30:27.170 D/CCodec  (11080): }
10-09 19:30:27.170 W/Codec2Client(11080): query -- param skipped: index = 1342179345.
10-09 19:30:27.171 W/Codec2Client(11080): query -- param skipped: index = 2415921170.
10-09 19:30:27.171 W/Codec2Client(11080): query -- param skipped: index = 1610614798.
10-09 19:30:27.173 D/CCodecBufferChannel(11080): [c2.android.aac.decoder#376] Created input block pool with allocatorID 16 => poolID 17 - OK (0)
10-09 19:30:27.174 I/CCodecBufferChannel(11080): [c2.android.aac.decoder#376] Created output block pool with allocatorID 16 => poolID 30 - OK
10-09 19:30:27.175 D/CCodecBufferChannel(11080): [c2.android.aac.decoder#376] Configured output block pool ids 30 => OK
10-09 19:30:27.175 E/ion     (11080): ioctl c0044901 failed with code -1: Invalid argument
10-09 19:30:27.465 I/OkHttpWebsocketSession(11080): Receiving (raw) message {"MessageType":"UserDataChanged","MessageId":"14df0bb74c054df3a27eb861e5eb980f","Data":{"UserId":"<removed>","UserDataList":[{"PlaybackPositionTicks":0,"PlayCount":1,"IsFavorite":false,"LastPlayedDate":"2022-10-10T00:30:26.9527188Z","Played":false,"Key":"8312cd93-45d2-4a91-88ce-7d96255737a0","ItemId":"8312cd9345d24a9188ce7d96255737a0"}]}}
10-09 19:30:27.679 D/jellyfin-apiclient(11080): Adding request to queue: https://foo.bar.com/Sessions/Playing/Progress
10-09 19:30:27.688 I/PlaybackController(11080): Play method: Direct
10-09 19:30:27.689 I/PlaybackController(11080): Turning off subs
10-09 19:30:27.691 D/PlaybackController(11080): Setting subtitle index to: -1
10-09 19:30:27.700 D/PlaybackController(11080): trying to switch audio stream from -1 to 1
10-09 19:30:27.701 D/AndroidRuntime(11080): Shutting down VM
--------- beginning of crash
10-09 19:30:27.704 E/AndroidRuntime(11080): FATAL EXCEPTION: main
10-09 19:30:27.704 E/AndroidRuntime(11080): Process: org.jellyfin.androidtv, PID: 11080
10-09 19:30:27.704 E/AndroidRuntime(11080): java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at java.util.ArrayList.get(ArrayList.java:437)
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at org.jellyfin.androidtv.ui.playback.VideoManager.setExoPlayerTrack(VideoManager.java:536)
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at org.jellyfin.androidtv.ui.playback.PlaybackController.switchAudioStream(PlaybackController.java:945)
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at org.jellyfin.androidtv.ui.playback.PlaybackController.onPrepared(PlaybackController.java:1492)
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at org.jellyfin.androidtv.ui.playback.VideoManager$1.onIsPlayingChanged(VideoManager.java:121)
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$24(ExoPlayerImpl.java:1944)
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda8.invoke(Unknown Source:4)
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:281)
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:190)
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.run(Unknown Source:6)
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:211)
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1955)
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlayWhenReady(ExoPlayerImpl.java:2553)
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at com.google.android.exoplayer2.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:744)
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at org.jellyfin.androidtv.ui.playback.VideoManager.start(VideoManager.java:315)
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at org.jellyfin.androidtv.ui.playback.PlaybackController$7.run(PlaybackController.java:861)
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at android.os.Handler.handleCallback(Handler.java:883)
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at android.os.Looper.loop(Looper.java:214)
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at java.lang.reflect.Method.invoke(Native Method)
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
10-09 19:30:27.704 E/AndroidRuntime(11080): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
10-09 19:30:27.706 E/ACRA    (11080): ACRA caught a IndexOutOfBoundsException for org.jellyfin.androidtv
10-09 19:30:27.706 E/ACRA    (11080): java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
10-09 19:30:27.706 E/ACRA    (11080): 	at java.util.ArrayList.get(ArrayList.java:437)
10-09 19:30:27.706 E/ACRA    (11080): 	at org.jellyfin.androidtv.ui.playback.VideoManager.setExoPlayerTrack(VideoManager.java:536)
10-09 19:30:27.706 E/ACRA    (11080): 	at org.jellyfin.androidtv.ui.playback.PlaybackController.switchAudioStream(PlaybackController.java:945)
10-09 19:30:27.706 E/ACRA    (11080): 	at org.jellyfin.androidtv.ui.playback.PlaybackController.onPrepared(PlaybackController.java:1492)
10-09 19:30:27.706 E/ACRA    (11080): 	at org.jellyfin.androidtv.ui.playback.VideoManager$1.onIsPlayingChanged(VideoManager.java:121)
10-09 19:30:27.706 E/ACRA    (11080): 	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$24(ExoPlayerImpl.java:1944)
10-09 19:30:27.706 E/ACRA    (11080): 	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda8.invoke(Unknown Source:4)
10-09 19:30:27.706 E/ACRA    (11080): 	at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:281)
10-09 19:30:27.706 E/ACRA    (11080): 	at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:190)
10-09 19:30:27.706 E/ACRA    (11080): 	at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.run(Unknown Source:6)
10-09 19:30:27.706 E/ACRA    (11080): 	at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:211)
10-09 19:30:27.706 E/ACRA    (11080): 	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1955)
10-09 19:30:27.706 E/ACRA    (11080): 	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlayWhenReady(ExoPlayerImpl.java:2553)
10-09 19:30:27.706 E/ACRA    (11080): 	at com.google.android.exoplayer2.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:744)
10-09 19:30:27.706 E/ACRA    (11080): 	at org.jellyfin.androidtv.ui.playback.VideoManager.start(VideoManager.java:315)
10-09 19:30:27.706 E/ACRA    (11080): 	at org.jellyfin.androidtv.ui.playback.PlaybackController$7.run(PlaybackController.java:861)
10-09 19:30:27.706 E/ACRA    (11080): 	at android.os.Handler.handleCallback(Handler.java:883)
10-09 19:30:27.706 E/ACRA    (11080): 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-09 19:30:27.706 E/ACRA    (11080): 	at android.os.Looper.loop(Looper.java:214)
10-09 19:30:27.706 E/ACRA    (11080): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
10-09 19:30:27.706 E/ACRA    (11080): 	at java.lang.reflect.Method.invoke(Native Method)
10-09 19:30:27.706 E/ACRA    (11080): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
10-09 19:30:27.706 E/ACRA    (11080): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
10-09 19:30:27.706 D/ACRA    (11080): Building report
10-09 19:30:27.710 D/ACRA    (11080): Starting collectors with priority FIRST
10-09 19:30:27.715 D/ACRA    (11080): Calling collector org.acra.collector.LogCatCollector
10-09 19:30:27.715 D/ACRA    (11080): Calling collector org.acra.collector.DropBoxCollector
10-09 19:30:27.715 D/ACRA    (11080): Calling collector org.acra.collector.StacktraceCollector
10-09 19:30:27.716 D/ACRA    (11080): Collector org.acra.collector.DropBoxCollector completed
10-09 19:30:27.717 D/ACRA    (11080): Collector org.acra.collector.StacktraceCollector completed
10-09 19:30:27.724 D/ACRA    (11080): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.14.4` (`140499`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"sabrina","BOOTLOADER":"01.01.220111.043647","BRAND":"google","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"sabrina","DISPLAY":"QTS1.220504.008.8726984","FINGERPRINT":"google\/sabrina_prod_stable\/sabrina:10\/QTS1.220504.008\/8726984:user\/release-keys","HARDWARE":"amlogic","HOST":"abfarm-64-central-00314","ID":"QTS1.220504.008","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Google","MODEL":"Chromecast","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"sabrina_prod_stable","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1655289146000,"TYPE":"user","UNKNOWN":"unknown","USER":"android-build","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","FIRST_SDK_INT":29,"INCREMENTAL":"8726984","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"10","RESOURCES_SDK_INT":29,"SDK":"29","SDK_INT":29,"SECURITY_PATCH":"2022-05-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":140499,"VERSION_NAME":"0.14.4"}
```  

### Device information

***Android version***: `10`  
***Device brand***: `google`  
***Device product***: `sabrina_prod_stable`  
***Device model***: `Chromecast`  

### Crash information

***Start time***: `2022-10-09T19:07:07.554-05:00`  
***Crash time***: `2022-10-09T19:30:27.804-05:00`  

### Application version

0.14.4

### Where did you install the app from?

Google Play

### Device information

Chromecast Google TV 4K

### Android version

Android 10

### Jellyfin server version

10.8.5

**Comment by Optinux** [comment]
Note that this only happens when trying to play with ExoPlayer. LibVLC works fine.

**Comment by butts136** [comment]
I have the same problem but a part of the problem seems coming from the Jellyfin-Intros-plugins itself.

I have done few test with lots of videos from vimeo.

There's is three problems i have notice

P/s : When i talk about crash, it's only on Firestick as far i can say but it's blurred on all devices

90% of the videos from vimeo are downloaded in 360p instead of what we ask, like 1080p. when the video is downloaded in 360p, It's blurred in LibVLC and Exoplayer but Exoplayer crash automaticly.
When it's in the desired resolution, 480, 720, 1080 or more, it's working well on both player without any problems.

Like I said, some videos that I have uploaded earlier this year was working and are still working, but if I upload again the same exacte video files on Vimeo, This one is now not working, That's weird,

If i took one of my old videos working from vimeo and use it with the local source option, it's in original quality and working on VLC but still crash on ExoPlayer.

I don't understand why it's downloading only in 360p Most of the time,
Probably mixed with ExoPlayer compatibility problem. He can plan the video but not if it is an intro.

Thanks ;)
