### ISSUE TITLE
Daydream mostly just shows Jellyfin logo

### ISSUE THREAD

**Issue by thiakil** [jellyfin/jellyfin-androidtv#2238]
### Describe the bug

1. Activate screensaver/dream mode in system settings to use Jellyfin
2. Wait for screensaver to activate

System starts Jellyfin in Dream mode, but 90% of the time I just get the Jellyfin logo and no backdrops.
If I leave it long enough, I might get one backdrop to show and then it just goes back to the JF logo when it should transition to another backdrop.

I would expect it to always show some backdrop, I have plenty of series and movies in the library for it to choose from

### Application version

0.14.4

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield P3430

### Android version

Android11 Shield 9.1.1

### Jellyfin server version

10.8.6

**Comment by nielsvanvelzen** [comment]
The screensaver shows the Jellyfin logo when it's unable to download the backdrop. This could be caused by a few things:

- The image doesn't exist but the server thinks it does
- The storage is really slow and a timeout is hit while downloading (this can happen when using cloud storage for example)
- The image format is unsupported, unlikely but can happen

**Comment by thiakil** [comment]
How do we diagnose which is happening?
I don't know why it would be any of those things

**Comment by nielsvanvelzen** [comment]
You might be able to find errors in the client logs when the daydream is active.

**Comment by thiakil** [comment]
And how do I find those when there's not a crash? Google isn't very helpful...

**Comment by thiakil** [comment]
Had to add some extra debug loggin to the app to get any useful info out.

Seems some of them fail to parse (though the file load fine in Chrome - I made it print the url)

```
java.util.concurrent.ExecutionException: com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                                                                    There were 2 root causes:
                                                                                                    com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException(Mark has been invalidated, pos: 202764 markLimit: 5242880)
                                                                                                    com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException(Mark has been invalidated, pos: 6491 markLimit: 5242880)
                                                                                                     call GlideException#logRootCauses(String) for more detail
                                                                                                    	at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:217)
                                                                                                    	at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:130)
                                                                                                    	at org.jellyfin.androidtv.integration.dream.LibraryDreamService$loadBackdrop$3.invokeSuspend(LibraryDreamService.kt:114)
                                                                                                    	at org.jellyfin.androidtv.integration.dream.LibraryDreamService$loadBackdrop$3.invoke(Unknown Source:8)
                                                                                                    	at org.jellyfin.androidtv.integration.dream.LibraryDreamService$loadBackdrop$3.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
                                                                                                    	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
                                                                                                    	at org.jellyfin.androidtv.integration.dream.LibraryDreamService.loadBackdrop(LibraryDreamService.kt:107)
                                                                                                    	at org.jellyfin.androidtv.integration.dream.LibraryDreamService.access$loadBackdrop(LibraryDreamService.kt:37)
                                                                                                    	at org.jellyfin.androidtv.integration.dream.LibraryDreamService$loadBackdrop$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    Caused by: com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                                                                    There were 2 root causes:
                                                                                                    com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException(Mark has been invalidated, pos: 202764 markLimit: 5242880)
                                                                                                    com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException(Mark has been invalidated, pos: 6491 markLimit: 5242880)
                                                                                                     call GlideException#logRootCauses(String) for more detail
```

but sometimes there's some sort of timeout 12ms after starting...
```
2022-11-19 20:52:03.391 21261-21392 LibraryDre...adBackdrop org.jellyfin.androidtv.debug         E  http://10.1.2.1:8096/Items/82fceb45-fbb6-1ec1-2f86-debfc134fa4b/Images/Backdrop?tag=917fddd59a63e47443050923253ea7be&format=Webp
2022-11-19 20:52:03.403 21261-21392 LibraryDre...adBackdrop org.jellyfin.androidtv.debug         E  java.util.concurrent.ExecutionException: com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                                                                    There was 1 root cause:
                                                                                                    com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)
                                                                                                     call GlideException#logRootCauses(String) for more detail
                                                                                                    	at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:217)
                                                                                                    	at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:130)
                                                                                                    	at org.jellyfin.androidtv.integration.dream.LibraryDreamService$loadBackdrop$3.invokeSuspend(LibraryDreamService.kt:116)
                                                                                                    	at org.jellyfin.androidtv.integration.dream.LibraryDreamService$loadBackdrop$3.invoke(Unknown Source:8)
                                                                                                    	at org.jellyfin.androidtv.integration.dream.LibraryDreamService$loadBackdrop$3.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
                                                                                                    	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
                                                                                                    	at org.jellyfin.androidtv.integration.dream.LibraryDreamService.loadBackdrop(LibraryDreamService.kt:109)
                                                                                                    	at org.jellyfin.androidtv.integration.dream.LibraryDreamService.access$loadBackdrop(LibraryDreamService.kt:39)
                                                                                                    	at org.jellyfin.androidtv.integration.dream.LibraryDreamService$loadBackdrop$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    Caused by: com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                                                                    There was 1 root cause:
                                                                                                    com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)
                                                                                                     call GlideException#logRootCauses(String) for more detail
2022-11-19 20:52:03.420 21261-21392 LibraryDre...adBackdrop org.jellyfin.androidtv.debug         E  com.bumptech.glide.load.HttpException: Failed to connect or obtain data, status code: -1
                                                                                                    	at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:98)
                                                                                                    	at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:58)
                                                                                                    	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
                                                                                                    	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:95)
                                                                                                    	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:88)
                                                                                                    	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
                                                                                                    	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280)
                                                                                                    	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
                                                                                                    	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultPriorityThreadFactory$1.run(GlideExecutor.java:372)
                                                                                                    Caused by: java.net.SocketTimeoutException: timeout
                                                                                                    	at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:214)
                                                                                                    	at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263)
                                                                                                    	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
                                                                                                    	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
                                                                                                    	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
                                                                                                    	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
                                                                                                    	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
                                                                                                    	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
                                                                                                    	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
                                                                                                    	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
                                                                                                    	at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:95)
                                                                                                    	at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:58) 
                                                                                                    	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100) 
                                                                                                    	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:95) 
                                                                                                    	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:88) 
                                                                                                    	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311) 
                                                                                                    	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280) 
                                                                                                    	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413) 
                                                                                                    	at java.lang.Thread.run(Thread.java:923) 
                                                                                                    	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultPriorityThreadFactory$1.run(GlideExecutor.java:372) 
                                                                                                    Caused by: java.net.SocketException: Socket closed
                                                                                                    	at java.net.SocketInputStream.read(SocketInputStream.java:209)
                                                                                                    	at java.net.SocketInputStream.read(SocketInputStream.java:144)
                                                                                                    	at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
                                                                                                    	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
                                                                                                    	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307) 
                                                                                                    	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301) 
                                                                                                    	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197) 
                                                                                                    	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188) 
                                                                                                    	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129) 
                                                                                                    	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750) 
                                                                                                    	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622) 
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475) 
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411) 
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248) 
                                                                                                    	at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:95) 
                                                                                                    	at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:58) 
                                                                                                    	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100) 
                                                                                                    	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:95) 
                                                                                                    	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:88) 
                                                                                                    	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311) 
                                                                                                    	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280) 
                                                                                                    	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413) 
                                                                                                    	at java.lang.Thread.run(Thread.java:923) 
                                                                                                    	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultPriorityThreadFactory$1.run(GlideExecutor.java:372) 
```

I don't quite understand how that would happen though - the Shield is connected via ethernet, Jellyfin is running under Docker on the router, it's using the IPv4 address..

They are appearing in the server's log (one of these matches the above image). `Time in ms after which a response is considered slow` is at the default 500. (so much higher than the observed 12ms socket failure)

```
[2022-11-19 12:51:30.521 +00:00] [WRN] [51] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://10.1.2.1:8096/Items/7345c364-838e-3670-db1d-ab78893f4f77/Images/Backdrop?tag=cbfb69146b844f09f4f453587277253b&format=Webp" to "10.1.2.200" in 0:00:01.2409415 with Status Code 200
[2022-11-19 12:52:03.841 +00:00] [WRN] [63] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://10.1.2.1:8096/Items/82fceb45-fbb6-1ec1-2f86-debfc134fa4b/Images/Backdrop?tag=917fddd59a63e47443050923253ea7be&format=Webp" to "10.1.2.200" in 0:00:02.7586385 with Status Code 200
[2022-11-19 12:53:36.235 +00:00] [WRN] [63] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://10.1.2.1:8096/Items/2d6d1ee0-7bc0-48a9-38b5-e15a58c8e4db/Images/Backdrop?tag=4c0a5e10532429e7bb938d6f1b39eba4&format=Webp" to "10.1.2.200" in 0:00:00.9690519 with Status Code 200
[2022-11-19 12:54:08.903 +00:00] [WRN] [80] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://10.1.2.1:8096/Items/f8e1460b-17dc-bf28-a304-6654204fea3c/Images/Backdrop?tag=140abbd68a02dd09954183395c919858&format=Webp" to "10.1.2.200" in 0:00:02.2333062 with Status Code 200
[2022-11-19 12:54:51.585 +00:00] [WRN] [91] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://10.1.2.1:8096/Items/ba587b54-37a0-d35b-38c1-4b83dcbc96f3/Images/Backdrop?tag=2cfe3298b690bd93c8c086a44efb7483&format=Webp" to "10.1.2.200" in 0:00:12.1814286 with Status Code 200
[2022-11-19 12:55:14.939 +00:00] [WRN] [37] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://10.1.2.1:8096/Items/010e3db7-5ab0-5099-26b2-f9c1c60554d5/Images/Backdrop?tag=c9508e62f45597b5de520491e78218b3&format=Webp" to "10.1.2.200" in 0:00:02.7136948 with Status Code 200
[2022-11-19 12:55:46.694 +00:00] [WRN] [37] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://10.1.2.1:8096/Items/d0ec1d0c-4500-8d2d-e05c-193d6a614953/Images/Backdrop?tag=5ce679854264165ef8b2f66bd39c5174&format=Webp" to "10.1.2.200" in 0:00:01.6492164 with Status Code 200
[2022-11-19 12:56:53.012 +00:00] [WRN] [91] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://10.1.2.1:8096/Items/d281949e-7d5d-4a1f-64fd-d90cc3e779dc/Images/Backdrop?tag=7810fbbe1b4d72ab6fae6ca50b4165d2&format=Webp" to "10.1.2.200" in 0:00:05.3959147 with Status Code 200
[2022-11-19 12:57:21.362 +00:00] [WRN] [56] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://10.1.2.1:8096/Items/85e07196-9e28-804c-df16-7748afcb527d/Images/Backdrop?tag=a3de6aee8875ede19379827ac1017cbf&format=Webp" to "10.1.2.200" in 0:00:00.9405424 with Status Code 200
```
