### ISSUE TITLE
Live TV on chromecast with google tv device jellyfin for android TV 0.14.5

### ISSUE THREAD

**Issue by bigworm** [jellyfin/jellyfin-androidtv#2267]
### Describe the bug

After the update to 0.14.5 jellyfin for android TV attempting to watch any channel on live tv results in the jellyfin app crashing/closing and going back to the google tv home screen with the error "No playable items"  Occurs on every playback app option(exoplayer, libvlc, etc.)

This issue does not occur on my Nvidia Shield Pro..only chromecast with google tv.

### Logs

---
client: Jellyfin for Android TV
client_version: 0.14.5
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs
 
***Stack Trace***: 
```log
java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
	at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:353)
	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:153)
	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:133)
	at com.bumptech.glide.Glide.with(Glide.java:818)
	at org.jellyfin.androidtv.ui.GuideChannelHeader.loadImage(GuideChannelHeader.java:63)
	at org.jellyfin.androidtv.ui.livetv.LiveTvGuideActivity$DisplayProgramsTask$1.run(LiveTvGuideActivity.java:562)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
 
```  
***Logcat***: 
```log
--------- beginning of main
11-14 01:14:10.974 I/MediaCodec(13882): [OMX.amlogic.avc.decoder.awesome2] setting surface generation to 14215174
11-14 01:14:10.974 D/SurfaceUtils(13882): disconnecting from surface 0xc485a008, reason connectToSurface(reconnect)
11-14 01:14:10.974 D/SurfaceUtils(13882): connecting to surface 0xc485a008, reason connectToSurface(reconnect)
11-14 01:14:10.975 D/CCodecConfig(13882): c2 config diff is   c2::float output.drc.output-loudness.value = -16
11-14 01:14:10.976 D/CCodecBuffers(13882): [c2.android.aac.decoder#206:Output[N]] popFromStashAndRegister: at 1000000020411us, output format changed to AMessage(what = 0x00000000) = {
11-14 01:14:10.976 D/CCodecBuffers(13882):   int32_t aac-drc-album-mode = 0
11-14 01:14:10.976 D/CCodecBuffers(13882):   int32_t aac-drc-boost-level = 127
11-14 01:14:10.976 D/CCodecBuffers(13882):   int32_t aac-drc-cut-level = 127
11-14 01:14:10.976 D/CCodecBuffers(13882):   int32_t aac-drc-effect-type = 3
11-14 01:14:10.976 D/CCodecBuffers(13882):   int32_t aac-drc-output-loudness = 64
11-14 01:14:10.976 D/CCodecBuffers(13882):   int32_t aac-encoded-target-level = -1
11-14 01:14:10.976 D/CCodecBuffers(13882):   int32_t aac-max-output-channel_count = 8
11-14 01:14:10.976 D/CCodecBuffers(13882):   int32_t aac-target-ref-level = 64
11-14 01:14:10.976 D/CCodecBuffers(13882):   int32_t channel-count = 2
11-14 01:14:10.976 D/CCodecBuffers(13882):   string mime = "audio/raw"
11-14 01:14:10.976 D/CCodecBuffers(13882):   int32_t sample-rate = 48000
11-14 01:14:10.976 D/CCodecBuffers(13882): }
11-14 01:14:10.981 D/SurfaceUtils(13882): disconnecting from surface 0xc485a008, reason setNativeWindowSizeFormatAndUsage
11-14 01:14:10.981 D/SurfaceUtils(13882): connecting to surface 0xc485a008, reason setNativeWindowSizeFormatAndUsage
11-14 01:14:10.981 D/SurfaceUtils(13882): set up nativeWindow 0xc485a008 for 1280x720, color 0x11, rotation 0, usage 0x402900
11-14 01:14:10.981 D/SurfaceUtils(13882): disconnecting from surface 0xc485bc08, reason disconnectFromSurface
11-14 01:14:10.981 E/Surface (13882): freeAllBuffers: 4 buffers were freed while being dequeued!
11-14 01:14:10.986 D/ACRA    (13882): onActivityStopped class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
11-14 01:14:10.992 D/CustomPlaybackOverlayFragment(13882): Stopping!
11-14 01:14:11.000 D/CustomPlaybackOverlayFragment(13882): this fragment belongs to the current session, ending it
11-14 01:14:11.001 D/PlaybackController(13882): stop called at 851000
11-14 01:14:11.041 W/MediaCodec(13882): mapFormat: no mediaType information
11-14 01:14:11.155 I/jellyfin-apiclient(13882): ReportPlaybackStopped: Item 62aebebd48481fb74315ccdfe47101d4, Ticks: 8510000000
11-14 01:14:11.155 D/jellyfin-apiclient(13882): Adding request to queue: https://myserver.com/Sessions/Playing/Stopped
11-14 01:14:11.166 I/ExoPlayerImpl(13882): Release ec32c35 [ExoPlayerLib/2.18.1] [sabrina, Chromecast, Google, 31] [goog.exo.core, goog.exo.ui, goog.exo.exoplayer, goog.exo.decoder, goog.exo.datasource, goog.exo.extractor, goog.exo.ffmpeg]
11-14 01:14:11.183 D/MediaCodec(13882): keep callback message for reclaim
11-14 01:14:11.188 D/CCodecBuffers(13882): [c2.android.aac.decoder#206:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 0
11-14 01:14:11.188 D/CCodecBuffers(13882): [c2.android.aac.decoder#206:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 1
11-14 01:14:11.189 D/CCodecBuffers(13882): [c2.android.aac.decoder#206:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 2
11-14 01:14:11.189 D/MediaCodec(13882): keep callback message for reclaim
11-14 01:14:11.190 I/CCodecConfig(13882): query failed after returning 19 values (BAD_INDEX)
11-14 01:14:11.192 W/Codec2Client(13882): query -- param skipped: index = 1342179345.
11-14 01:14:11.192 W/Codec2Client(13882): query -- param skipped: index = 2415921170.
11-14 01:14:11.192 W/Codec2Client(13882): query -- param skipped: index = 1610614798.
11-14 01:14:11.197 D/SurfaceUtils(13882): connecting to surface 0xc73cb008, reason connectToSurface
11-14 01:14:11.197 I/MediaCodec(13882): [OMX.amlogic.avc.decoder.awesome2] setting surface generation to 14215175
11-14 01:14:11.197 D/SurfaceUtils(13882): disconnecting from surface 0xc73cb008, reason connectToSurface(reconnect)
11-14 01:14:11.197 D/SurfaceUtils(13882): connecting to surface 0xc73cb008, reason connectToSurface(reconnect)
11-14 01:14:11.201 D/SurfaceUtils(13882): disconnecting from surface 0xc73cb008, reason setNativeWindowSizeFormatAndUsage
11-14 01:14:11.201 D/SurfaceUtils(13882): connecting to surface 0xc73cb008, reason setNativeWindowSizeFormatAndUsage
11-14 01:14:11.201 D/SurfaceUtils(13882): set up nativeWindow 0xc73cb008 for 1280x720, color 0x11, rotation 0, usage 0x402900
11-14 01:14:11.201 D/SurfaceUtils(13882): disconnecting from surface 0xc485a008, reason disconnectFromSurface
11-14 01:14:11.202 E/Surface (13882): freeAllBuffers: 4 buffers were freed while being dequeued!
11-14 01:14:11.203 D/CCodecBufferChannel(13882): [c2.android.aac.decoder#206] MediaCodec discarded an unknown buffer
11-14 01:14:11.204 D/CCodecBufferChannel(13882): [c2.android.aac.decoder#206] MediaCodec discarded an unknown buffer
11-14 01:14:11.204 D/CCodecBufferChannel(13882): [c2.android.aac.decoder#206] MediaCodec discarded an unknown buffer
11-14 01:14:11.204 D/CCodecBufferChannel(13882): [c2.android.aac.decoder#206] MediaCodec discarded an unknown buffer
11-14 01:14:11.215 I/hw-BpHwBinder(13882): onLastStrongRef automatically unlinking death recipients
11-14 01:14:11.231 D/ACRA    (13882): onActivitySaveInstanceState class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
11-14 01:14:11.235 D/ACRA    (13882): onActivityDestroyed class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
11-14 01:14:11.238 D/SurfaceUtils(13882): disconnecting from surface 0xc73cb008, reason disconnectFromSurface
11-14 01:14:11.282 I/AppThemeCallbacks(13882): Applying theme: DARK
11-14 01:14:11.289 D/ACRA    (13882): onActivityCreated class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
11-14 01:14:11.310 D/CompatibilityChangeReporter(13882): Compat change id reported: 147798919; UID 10075; state: ENABLED
11-14 01:14:11.344 D/ACRA    (13882): onActivityDestroyed class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
11-14 01:14:11.358 I/AppThemeCallbacks(13882): Applying theme: DARK
11-14 01:14:11.358 D/ACRA    (13882): onActivityCreated class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
11-14 01:14:11.367 D/ACRA    (13882): onActivityStarted class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
11-14 01:14:11.428 E/ThemeUtils(13882): View class org.jellyfin.androidtv.ui.shared.StrokeTextView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
11-14 01:14:11.430 E/ThemeUtils(13882): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
11-14 01:14:11.447 I/ExoPlayerImpl(13882): Init 8f526ab [ExoPlayerLib/2.18.1] [sabrina, Chromecast, Google, 31]
11-14 01:14:11.456 I/DefaultRenderersFactory(13882): Loaded FfmpegAudioRenderer.
11-14 01:14:11.475 W/PhoneWindow(13882): Previously focused view reported id 2131427900 during save, but can't be found during restore.
11-14 01:14:11.513 D/ACRA    (13882): onActivityDestroyed class org.jellyfin.androidtv.ui.livetv.LiveTvGuideActivity
11-14 01:14:12.062 I/AppThemeCallbacks(13882): Applying theme: DARK
11-14 01:14:12.064 D/ACRA    (13882): onActivityCreated class org.jellyfin.androidtv.ui.livetv.LiveTvGuideActivity
11-14 01:14:12.091 D/ACRA    (13882): onActivityStarted class org.jellyfin.androidtv.ui.livetv.LiveTvGuideActivity
11-14 01:14:12.092 W/PhoneWindow(13882): Previously focused view reported id 129 during save, but can't be found during restore.
11-14 01:14:12.093 D/ACRA    (13882): onActivityResumed class org.jellyfin.androidtv.ui.livetv.LiveTvGuideActivity
11-14 01:14:12.106 D/TvManager(13882): *** About to load channels
11-14 01:14:12.107 D/TvManager(13882): Preferences: EnableFavoriteSorting=false, ChannelOrder=SortName
11-14 01:14:12.107 D/jellyfin-apiclient(13882): Adding request to queue: https://myserver.com/LiveTv/Channels?UserId=8e0eced8-8de8-46b6-92cf-2fd0697646b7&SortBy=SortName&EnableFavoriteSorting=false&format=json
11-14 01:14:12.115 I/Choreographer(13882): Skipped 36 frames!  The application may be doing too much work on its main thread.
11-14 01:14:12.117 I/OkHttpWebsocketSession(13882): Receiving (raw) message {"MessageType":"UserDataChanged","MessageId":"ad542974784e482d8aa1ed77a599e6a1","Data":{"UserId":"8e0eced88de846b692cf2fd0697646b7","UserDataList":[{"PlaybackPositionTicks":0,"PlayCount":391,"IsFavorite":false,"LastPlayedDate":"2022-11-14T06:14:10.5351676Z","Played":false,"Key":"62aebebd-4848-1fb7-4315-ccdfe47101d4","ItemId":"62aebebd48481fb74315ccdfe47101d4"},{"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"2b2bca16-aacc-8a14-d53a-11bb829eafa5","ItemId":"2b2bca16aacc8a14d53a11bb829eafa5"}]}}
11-14 01:14:12.157 D/ACRA    (13882): onActivityPaused class org.jellyfin.androidtv.ui.livetv.LiveTvGuideActivity
11-14 01:14:12.159 D/ACRA    (13882): onActivityStopped class org.jellyfin.androidtv.ui.livetv.LiveTvGuideActivity
11-14 01:14:12.159 D/ACRA    (13882): onActivitySaveInstanceState class org.jellyfin.androidtv.ui.livetv.LiveTvGuideActivity
11-14 01:14:12.160 D/ACRA    (13882): onActivityDestroyed class org.jellyfin.androidtv.ui.livetv.LiveTvGuideActivity
11-14 01:14:12.176 I/AppThemeCallbacks(13882): Applying theme: DARK
11-14 01:14:12.177 D/ACRA    (13882): onActivityCreated class org.jellyfin.androidtv.ui.livetv.LiveTvGuideActivity
11-14 01:14:12.201 D/ACRA    (13882): onActivityStarted class org.jellyfin.androidtv.ui.livetv.LiveTvGuideActivity
11-14 01:14:12.203 D/ACRA    (13882): onActivityResumed class org.jellyfin.androidtv.ui.livetv.LiveTvGuideActivity
11-14 01:14:12.214 D/TvManager(13882): *** About to load channels
11-14 01:14:12.214 D/TvManager(13882): Preferences: EnableFavoriteSorting=false, ChannelOrder=SortName
11-14 01:14:12.214 D/jellyfin-apiclient(13882): Adding request to queue: https://myserver.com/LiveTv/Channels?UserId=8e0eced8-8de8-46b6-92cf-2fd0697646b7&SortBy=SortName&EnableFavoriteSorting=false&format=json
11-14 01:14:12.223 I/jellyfin-apiclient(13882): Response received from: https://myserver.com/Sessions/Playing/Stopped
11-14 01:14:12.259 I/jellyfin-apiclient(13882): Response received from: https://myserver.com/LiveTv/Channels?UserId=8e0eced8-8de8-46b6-92cf-2fd0697646b7&SortBy=SortName&EnableFavoriteSorting=false&format=json
11-14 01:14:12.295 D/TvManager(13882): *** channel query response
11-14 01:14:12.296 D/LiveTvGuideActivity(13882): *** Display channels pre-execute
11-14 01:14:12.297 D/LiveTvGuideActivity(13882): *** Programs response
11-14 01:14:12.298 D/LiveTvGuideActivity$DisplayProgramsTask(13882): *** Display programs pre-execute
11-14 01:14:12.302 D/LiveTvGuideActivity$DisplayProgramsTask(13882): *** About to iterate programs
11-14 01:14:12.314 D/ACRA    (13882): onActivityStopped class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
11-14 01:14:12.316 D/CustomPlaybackOverlayFragment(13882): Stopping!
11-14 01:14:12.317 D/ACRA    (13882): onActivityDestroyed class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
11-14 01:14:12.363 D/AndroidRuntime(13882): Shutting down VM
--------- beginning of crash
11-14 01:14:12.370 E/AndroidRuntime(13882): FATAL EXCEPTION: main
11-14 01:14:12.370 E/AndroidRuntime(13882): Process: org.jellyfin.androidtv, PID: 13882
11-14 01:14:12.370 E/AndroidRuntime(13882): java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
11-14 01:14:12.370 E/AndroidRuntime(13882): 	at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:353)
11-14 01:14:12.370 E/AndroidRuntime(13882): 	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:153)
11-14 01:14:12.370 E/AndroidRuntime(13882): 	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:133)
11-14 01:14:12.370 E/AndroidRuntime(13882): 	at com.bumptech.glide.Glide.with(Glide.java:818)
11-14 01:14:12.370 E/AndroidRuntime(13882): 	at org.jellyfin.androidtv.ui.GuideChannelHeader.loadImage(GuideChannelHeader.java:63)
11-14 01:14:12.370 E/AndroidRuntime(13882): 	at org.jellyfin.androidtv.ui.livetv.LiveTvGuideActivity$DisplayProgramsTask$1.run(LiveTvGuideActivity.java:562)
11-14 01:14:12.370 E/AndroidRuntime(13882): 	at android.os.Handler.handleCallback(Handler.java:938)
11-14 01:14:12.370 E/AndroidRuntime(13882): 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-14 01:14:12.370 E/AndroidRuntime(13882): 	at android.os.Looper.loopOnce(Looper.java:201)
11-14 01:14:12.370 E/AndroidRuntime(13882): 	at android.os.Looper.loop(Looper.java:288)
11-14 01:14:12.370 E/AndroidRuntime(13882): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
11-14 01:14:12.370 E/AndroidRuntime(13882): 	at java.lang.reflect.Method.invoke(Native Method)
11-14 01:14:12.370 E/AndroidRuntime(13882): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-14 01:14:12.370 E/AndroidRuntime(13882): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
11-14 01:14:12.374 E/ACRA    (13882): ACRA caught a IllegalArgumentException for org.jellyfin.androidtv
11-14 01:14:12.374 E/ACRA    (13882): java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
11-14 01:14:12.374 E/ACRA    (13882): 	at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:353)
11-14 01:14:12.374 E/ACRA    (13882): 	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:153)
11-14 01:14:12.374 E/ACRA    (13882): 	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:133)
11-14 01:14:12.374 E/ACRA    (13882): 	at com.bumptech.glide.Glide.with(Glide.java:818)
11-14 01:14:12.374 E/ACRA    (13882): 	at org.jellyfin.androidtv.ui.GuideChannelHeader.loadImage(GuideChannelHeader.java:63)
11-14 01:14:12.374 E/ACRA    (13882): 	at org.jellyfin.androidtv.ui.livetv.LiveTvGuideActivity$DisplayProgramsTask$1.run(LiveTvGuideActivity.java:562)
11-14 01:14:12.374 E/ACRA    (13882): 	at android.os.Handler.handleCallback(Handler.java:938)
11-14 01:14:12.374 E/ACRA    (13882): 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-14 01:14:12.374 E/ACRA    (13882): 	at android.os.Looper.loopOnce(Looper.java:201)
11-14 01:14:12.374 E/ACRA    (13882): 	at android.os.Looper.loop(Looper.java:288)
11-14 01:14:12.374 E/ACRA    (13882): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
11-14 01:14:12.374 E/ACRA    (13882): 	at java.lang.reflect.Method.invoke(Native Method)
11-14 01:14:12.374 E/ACRA    (13882): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-14 01:14:12.374 E/ACRA    (13882): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
11-14 01:14:12.374 D/ACRA    (13882): Building report
11-14 01:14:12.376 D/ACRA    (13882): Starting collectors with priority FIRST
11-14 01:14:12.377 I/lyfin.androidt(13882): Background young concurrent copying GC freed 152851(9871KB) AllocSpace objects, 55(3236KB) LOS objects, 34% free, 23MB/36MB, paused 143us total 160.518ms
11-14 01:14:12.380 D/ACRA    (13882): Calling collector org.acra.collector.DropBoxCollector
11-14 01:14:12.381 D/ACRA    (13882): Collector org.acra.collector.DropBoxCollector completed
11-14 01:14:12.381 D/ACRA    (13882): Calling collector org.acra.collector.StacktraceCollector
11-14 01:14:12.382 D/ACRA    (13882): Collector org.acra.collector.StacktraceCollector completed
11-14 01:14:12.382 D/ACRA    (13882): Calling collector org.acra.collector.LogCatCollector
11-14 01:14:12.406 D/ACRA    (13882): Retrieving logcat output (buffer:default)...
 
```  
 
### App information
 
***App version***: `0.14.5` (`140599`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"sabrina","BOOTLOADER":"01.01.220802.100215","BRAND":"google","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"sabrina","DISPLAY":"STTE.220621.019.A2.9082754","FINGERPRINT":"google\/sabrina_prod_stable\/sabrina:12\/STTE.220621.019.A2\/9082754:user\/release-keys","HARDWARE":"amlogic","HOST":"abfarm827","ID":"STTE.220621.019.A2","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Google","MODEL":"Chromecast","ODM_SKU":"US","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"sabrina_prod_stable","RADIO":"unknown","SKU":"US","SOC_MANUFACTURER":"Amlogic","SOC_MODEL":"AMLS905D3","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1663662203000,"TYPE":"user","UNKNOWN":"unknown","USER":"android-build","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"9082754","MEDIA_PERFORMANCE_CLASS":0,"PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"12","RELEASE_OR_CODENAME":"12","SDK":"31","SDK_INT":31,"SECURITY_PATCH":"2022-07-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":140599,"VERSION_NAME":"0.14.5"}
```  
 
### Device information
 
***Android version***: `12`  
***Device brand***: `google`  
***Device product***: `sabrina_prod_stable`  
***Device model***: `Chromecast`  
 
### Crash information
 
***Start time***: `2022-11-13T20:11:04.206-05:00`  
***Crash time***: `2022-11-14T01:14:12.739-05:00`  

### Media info of the file

```shell
Live TV
```

### Application version

0.14.5

### Device information

Chromecast with Google TV

### Android version

Android 12

### Jellyfin server version

10.8.7

**Comment by bigworm** [comment]
I updated to beta 0.15.0 released 3 days ago and it doesn't work, but the behavior is slightly different.

on the beta it appears to start the stream with audio only for about 5 seconds with a black screen before crashing.

**Comment by nielsvanvelzen** [comment]
Is the crash log in 0.15.0-beta.1 the same as the one in this issue?

**Comment by bigworm** [comment]
On 0.15.0-beta.1 it doesn't crash the whole app back to the main screen.  It just returns to the guide in jf.  No crash log is sent to the server.

Here are the entries from the regular log

`[2022-11-16 17:58:29.060 +00:00] [INF] [149] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_playing_id     = "c7b4ff73227f8381760cefd27f2c1f06"
[2022-11-16 17:58:29.060 +00:00] [INF] [149] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id        = "e9aa5d5786db4dd9b29233e71a01bf57"
[2022-11-16 17:58:29.061 +00:00] [INF] [149] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id_int    = 1
[2022-11-16 17:58:29.061 +00:00] [INF] [149] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_playing_id   = "0212fe941d8992df6d4d8b9c95cae343"
[2022-11-16 17:58:29.061 +00:00] [INF] [149] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_user_id      = "e9aa5d5786db4dd9b29233e71a01bf57"
[2022-11-16 17:58:29.061 +00:00] [INF] [149] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : play_method          = "DirectPlay"
[2022-11-16 17:58:29.061 +00:00] [INF] [149] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.ClientName         = "Android TV"
[2022-11-16 17:58:29.061 +00:00] [INF] [149] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.DeviceName         = "Master Bedroom TV"
[2022-11-16 17:58:29.061 +00:00] [INF] [149] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemName             = "Channel3"
[2022-11-16 17:58:29.061 +00:00] [INF] [149] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemId               = "c7b4ff73227f8381760cefd27f2c1f06"
[2022-11-16 17:58:29.062 +00:00] [INF] [149] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemType             = "TvChannel"
[2022-11-16 17:58:29.062 +00:00] [INF] [149] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Details do not match for play item
[2022-11-16 17:58:29.062 +00:00] [INF] [149] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Exited`

**Comment by bigworm** [comment]
Let me know if there is anything further I can provide to assist in resolving this issue.

**Comment by bigworm** [comment]
Same behavior in v0.15.0-beta.2 as v0.15.0-beta.1...

**Comment by bigworm** [comment]
Clearing cache fixed the issue on latest beta.  I reinstalled 0.14.5(effectively clearing cache/data) and it worked!  Must have been some kind of issue in the update process as this happened to me and a friend.
