### ISSUE TITLE
AndroidTV crashing sometimes after stopping playback

### ISSUE THREAD

**Issue by loughnane** [jellyfin/jellyfin-androidtv#2291]
### Describe the bug

1. Start playing back a video.
2. While video is playing press the "back" button on the nvidia shield remote.
3. App crashes

### Logs

---
client: Jellyfin for Android TV
client_version: 0.14.5
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.IllegalStateException: can't get VLCObject instance
	at org.videolan.libvlc.MediaPlayer.nativeSetAudioOutputDevice(Native Method)
	at org.videolan.libvlc.MediaPlayer.setAudioOutputDeviceInternal(MediaPlayer.java:969)
	at org.videolan.libvlc.MediaPlayer.updateAudioOutputDevice(MediaPlayer.java:459)
	at org.videolan.libvlc.MediaPlayer.access$600(MediaPlayer.java:58)
	at org.videolan.libvlc.MediaPlayer$3.onAudioDevicesChanged(MediaPlayer.java:535)
	at org.videolan.libvlc.MediaPlayer$3.onAudioDevicesRemoved(MediaPlayer.java:559)
	at android.media.AudioManager$NativeEventHandlerDelegate$1.handleMessage(AudioManager.java:6270)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```  
***Logcat***: 
```log
--------- beginning of main
11-25 16:51:41.159 I/ACodec  (13320): Scaled Width is 1280, height is 720
11-25 16:51:41.176 D/SurfaceUtils(13320): set up nativeWindow 0x28319b99d0 for 1280x720, color 0x106, rotation 0, usage 0x2900
11-25 16:51:41.183 I/android_os_HwBinder(13320): HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
11-25 16:51:41.185 I/OMXClient(13320): IOmx service obtained
11-25 16:51:41.193 I/ACodec  (13320): Get OMX_IndexConfigScale: 0x10000/0x10000
11-25 16:51:41.193 I/ACodec  (13320): Scaled Width is 1280, height is 720
11-25 16:51:41.194 D/SurfaceUtils(13320): set up nativeWindow 0x28319b99d0 for 1280x720, color 0x146, rotation 0, usage 0x2900
11-25 16:51:41.209 I/ACodec  (13320): Get OMX_IndexConfigScale: 0x10000/0x10000
11-25 16:51:41.209 I/ACodec  (13320): Scaled Width is 1280, height is 720
11-25 16:51:41.223 I/android_os_HwBinder(13320): HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
11-25 16:51:41.225 I/android_os_HwBinder(13320): HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
11-25 16:51:41.227 I/android_os_HwBinder(13320): HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
11-25 16:51:41.228 I/ACodec  (13320): codec does not support config priority (err -2147483648)
11-25 16:51:41.262 I/OkHttpWebsocketSession(13320): Receiving (raw) message {"MessageType":"UserDataChanged","MessageId":"91a67dfd331740aa84c171b5098bf61f","Data":{"UserId":"0abd6019f18d454db93fbef34c13e670","UserDataList":[{"PlayedPercentage":52.21436609400444,"PlaybackPositionTicks":15173500000,"PlayCount":3,"IsFavorite":false,"LastPlayedDate":"2022-11-25T21:51:42.7012111Z","Played":false,"Key":"bd6ff3d7-5f6f-3217-c5b3-c233bdc0297f001003","ItemId":"e628aa4bde1908857c7d7e10c12c8d05"},{"UnplayedItemCount":1,"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"8c96e05a-2f7f-8f9e-55de-b03e040a335f","ItemId":"8c96e05a2f7f8f9e55deb03e040a335f"}]}}
11-25 16:51:41.299 D/VideoManager(13320): re-retrieved exoplayer track index 2
11-25 16:51:41.299 D/jellyfin-apiclient(13320): Adding request to queue: http://192.168.3.100:8096/Sessions/Playing/Progress
11-25 16:51:41.299 I/PlaybackController(13320): Play method: Direct
11-25 16:51:41.299 I/PlaybackController(13320): Turning off subs
11-25 16:51:41.300 D/PlaybackController(13320): Setting subtitle index to: -1
11-25 16:51:41.302 D/VideoManager(13320): re-retrieved exoplayer track index 2
11-25 16:51:41.302 D/PlaybackController(13320): trying to switch audio stream from 2 to 2
11-25 16:51:41.302 D/PlaybackController(13320): skipping setting audio stream, already set to requested index 2
11-25 16:51:41.302 D/PlaybackController(13320): setting mCurrentOptions audio stream index from null to 2
11-25 16:51:41.317 D/AudioTrack(13320): getTimestamp_l(6473): device stall time corrected using current time 6043940203188243
11-25 16:51:41.333 D/VideoManager(13320): current media item is seekable
11-25 16:51:41.334 D/PlaybackController(13320): Trying to seek from 1517350 to 1517350
11-25 16:51:41.334 D/PlaybackController(13320): Container: mov
11-25 16:51:41.334 D/VideoManager(13320): current media item is seekable
11-25 16:51:41.334 D/PlaybackController(13320): Seek method - native
11-25 16:51:41.334 I/VideoManager(13320): Exo length in seek is: 2906001
11-25 16:51:41.337 D/VideoManager(13320): Player is buffering
11-25 16:51:41.337 D/jellyfin-apiclient(13320): Adding request to queue: http://192.168.3.100:8096/Sessions/Playing/Progress
11-25 16:51:41.676 I/jellyfin-apiclient(13320): Response received from: http://192.168.3.100:8096/Sessions/Playing/Progress
11-25 16:51:41.826 I/jellyfin-apiclient(13320): Response received from: http://192.168.3.100:8096/Sessions/Playing/Progress
11-25 16:51:41.956 I/PlaybackController(13320): Play method: Direct
11-25 16:51:41.957 I/PlaybackController(13320): Turning off subs
11-25 16:51:41.957 D/PlaybackController(13320): Setting subtitle index to: -1
11-25 16:51:41.958 D/PlaybackController(13320): trying to switch audio stream from 2 to 2
11-25 16:51:41.958 D/PlaybackController(13320): skipping setting audio stream, already set to requested index 2
11-25 16:51:41.965 D/AudioTrack(13320): getTimestamp_l(6481): device stall time corrected using current time 6043940851557253
11-25 16:51:41.995 D/AudioTrack(13320): getTimestamp_l(6481): stale timestamp time corrected, currentTimeNanos: 6043940324816211 < limitNs: 6043940774534180 < mStartNs: 6043940816534180
11-25 16:51:41.995 W/AudioTrack(13320): getTimestamp_l(6481): retrograde timestamp time corrected, 6043940774534180 < 6043940861676940
11-25 16:51:44.365 D/jellyfin-apiclient(13320): Adding request to queue: http://192.168.3.100:8096/Sessions/Playing/Progress
11-25 16:51:44.725 I/jellyfin-apiclient(13320): Response received from: http://192.168.3.100:8096/Sessions/Playing/Progress
11-25 16:51:47.399 D/jellyfin-apiclient(13320): Adding request to queue: http://192.168.3.100:8096/Sessions/Playing/Progress
11-25 16:51:47.598 I/jellyfin-apiclient(13320): Response received from: http://192.168.3.100:8096/Sessions/Playing/Progress
11-25 16:51:47.634 D/ACRA    (13320): onActivityPaused class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
11-25 16:51:47.897 D/ACRA    (13320): onActivityStarted class org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity
11-25 16:51:47.897 I/ViewTarget(13320): Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
11-25 16:51:47.897 I/ViewTarget(13320): Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
11-25 16:51:47.899 D/ACRA    (13320): onActivityResumed class org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity
11-25 16:51:47.899 D/BackgroundServiceFragment(13320): Restoring active backgrounds
11-25 16:51:47.899 D/BackgroundServiceFragment(13320): Restoring background drawable
11-25 16:51:47.916 E/libc    (13320): Access denied finding property "ro.vendor.sys.NV_ASYNC"
11-25 16:51:47.916 E/libc    (13320): Access denied finding property "ro.vendor.sys.NV_LOGFPS"
11-25 16:51:47.916 E/libc    (13320): Access denied finding property "ro.vendor.sys.NV_PROCESS_NAME"
11-25 16:51:47.916 E/libc    (13320): Access denied finding property "ro.vendor.sys.NV_FPSDYNAMIC"
11-25 16:51:48.375 E/libc    (13320): Access denied finding property "ro.vendor.sys.NV_ASYNC"
11-25 16:51:48.375 E/libc    (13320): Access denied finding property "ro.vendor.sys.NV_LOGFPS"
11-25 16:51:48.375 E/libc    (13320): Access denied finding property "ro.vendor.sys.NV_PROCESS_NAME"
11-25 16:51:48.375 E/libc    (13320): Access denied finding property "ro.vendor.sys.NV_FPSDYNAMIC"
11-25 16:51:48.410 D/SurfaceUtils(13320): connecting to surface 0x28319d3290, reason connectToSurface
11-25 16:51:48.410 I/MediaCodec(13320): [OMX.Nvidia.h264.decode] setting surface generation to 13639682
11-25 16:51:48.410 D/SurfaceUtils(13320): disconnecting from surface 0x28319d3290, reason connectToSurface(reconnect)
11-25 16:51:48.410 D/SurfaceUtils(13320): connecting to surface 0x28319d3290, reason connectToSurface(reconnect)
11-25 16:51:49.079 D/SurfaceUtils(13320): set up nativeWindow 0x28319d3290 for 1280x720, color 0x146, rotation 0, usage 0x2900
11-25 16:51:49.079 D/SurfaceUtils(13320): disconnecting from surface 0x28319b99d0, reason disconnectFromSurface
11-25 16:51:49.079 E/Surface (13320): freeAllBuffers: 10 buffers were freed while being dequeued!
11-25 16:51:49.082 E/Surface (13320): freeAllBuffers: 1 buffers were freed while being dequeued!
11-25 16:51:49.083 W/AudioTrack(13320): restartIfDisabled(6481): releaseBuffer() track 0x27b1a5fd40 disabled due to previous underrun, restarting
11-25 16:51:49.090 D/ACRA    (13320): onActivityStopped class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
11-25 16:51:49.091 D/CustomPlaybackOverlayFragment(13320): Stopping!
11-25 16:51:49.091 D/CustomPlaybackOverlayFragment(13320): this fragment belongs to the current session, ending it
11-25 16:51:49.091 D/PlaybackController(13320): stop called at 1523302
11-25 16:51:49.105 D/SurfaceUtils(13320): connecting to surface 0x2831999ae0, reason connectToSurface
11-25 16:51:49.105 I/MediaCodec(13320): [OMX.Nvidia.h264.decode] setting surface generation to 13639683
11-25 16:51:49.105 D/SurfaceUtils(13320): disconnecting from surface 0x2831999ae0, reason connectToSurface(reconnect)
11-25 16:51:49.105 D/SurfaceUtils(13320): connecting to surface 0x2831999ae0, reason connectToSurface(reconnect)
11-25 16:51:49.106 D/SurfaceUtils(13320): set up nativeWindow 0x2831999ae0 for 1280x720, color 0x146, rotation 0, usage 0x2900
11-25 16:51:49.106 D/SurfaceUtils(13320): disconnecting from surface 0x28319d3290, reason disconnectFromSurface
11-25 16:51:49.106 E/Surface (13320): freeAllBuffers: 10 buffers were freed while being dequeued!
11-25 16:51:49.124 D/SurfaceUtils(13320): disconnecting from surface 0x2831999ae0, reason disconnectFromSurface
11-25 16:51:49.242 I/jellyfin-apiclient(13320): ReportPlaybackStopped: Item e628aa4bde1908857c7d7e10c12c8d05, Ticks: 15233020000
11-25 16:51:49.243 D/jellyfin-apiclient(13320): Adding request to queue: http://192.168.3.100:8096/Sessions/Playing/Stopped
11-25 16:51:49.247 I/ExoPlayerImpl(13320): Release 96687d6 [ExoPlayerLib/2.18.1] [mdarcy, SHIELD Android TV, NVIDIA, 30] [goog.exo.core, goog.exo.ui, goog.exo.exoplayer, goog.exo.decoder, goog.exo.datasource, goog.exo.extractor, goog.exo.ffmpeg]
11-25 16:51:49.248 D/ACRA    (13320): onActivityDestroyed class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
11-25 16:51:49.257 D/FullDetailsActivity(13320): current time 1669413109257 last playback event time 1669413109243 last refresh time 1669413097796
11-25 16:51:49.257 I/FullDetailsActivity(13320): Re-loading after new episode playback
11-25 16:51:49.258 D/jellyfin-apiclient(13320): Adding request to queue: http://192.168.3.100:8096/Users/0abd6019-f18d-454d-b93f-bef34c13e670/Items/e628aa4b-de19-0885-7c7d-7e10c12c8d05?format=json
11-25 16:51:49.258 D/AndroidRuntime(13320): Shutting down VM
--------- beginning of crash
11-25 16:51:49.259 E/AndroidRuntime(13320): FATAL EXCEPTION: main
11-25 16:51:49.259 E/AndroidRuntime(13320): Process: org.jellyfin.androidtv, PID: 13320
11-25 16:51:49.259 E/AndroidRuntime(13320): java.lang.IllegalStateException: can't get VLCObject instance
11-25 16:51:49.259 E/AndroidRuntime(13320): 	at org.videolan.libvlc.MediaPlayer.nativeSetAudioOutputDevice(Native Method)
11-25 16:51:49.259 E/AndroidRuntime(13320): 	at org.videolan.libvlc.MediaPlayer.setAudioOutputDeviceInternal(MediaPlayer.java:969)
11-25 16:51:49.259 E/AndroidRuntime(13320): 	at org.videolan.libvlc.MediaPlayer.updateAudioOutputDevice(MediaPlayer.java:459)
11-25 16:51:49.259 E/AndroidRuntime(13320): 	at org.videolan.libvlc.MediaPlayer.access$600(MediaPlayer.java:58)
11-25 16:51:49.259 E/AndroidRuntime(13320): 	at org.videolan.libvlc.MediaPlayer$3.onAudioDevicesChanged(MediaPlayer.java:535)
11-25 16:51:49.259 E/AndroidRuntime(13320): 	at org.videolan.libvlc.MediaPlayer$3.onAudioDevicesRemoved(MediaPlayer.java:559)
11-25 16:51:49.259 E/AndroidRuntime(13320): 	at android.media.AudioManager$NativeEventHandlerDelegate$1.handleMessage(AudioManager.java:6270)
11-25 16:51:49.259 E/AndroidRuntime(13320): 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-25 16:51:49.259 E/AndroidRuntime(13320): 	at android.os.Looper.loop(Looper.java:223)
11-25 16:51:49.259 E/AndroidRuntime(13320): 	at android.app.ActivityThread.main(ActivityThread.java:7668)
11-25 16:51:49.259 E/AndroidRuntime(13320): 	at java.lang.reflect.Method.invoke(Native Method)
11-25 16:51:49.259 E/AndroidRuntime(13320): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-25 16:51:49.259 E/AndroidRuntime(13320): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
11-25 16:51:49.259 E/ACRA    (13320): ACRA caught a IllegalStateException for org.jellyfin.androidtv
11-25 16:51:49.259 E/ACRA    (13320): java.lang.IllegalStateException: can't get VLCObject instance
11-25 16:51:49.259 E/ACRA    (13320): 	at org.videolan.libvlc.MediaPlayer.nativeSetAudioOutputDevice(Native Method)
11-25 16:51:49.259 E/ACRA    (13320): 	at org.videolan.libvlc.MediaPlayer.setAudioOutputDeviceInternal(MediaPlayer.java:969)
11-25 16:51:49.259 E/ACRA    (13320): 	at org.videolan.libvlc.MediaPlayer.updateAudioOutputDevice(MediaPlayer.java:459)
11-25 16:51:49.259 E/ACRA    (13320): 	at org.videolan.libvlc.MediaPlayer.access$600(MediaPlayer.java:58)
11-25 16:51:49.259 E/ACRA    (13320): 	at org.videolan.libvlc.MediaPlayer$3.onAudioDevicesChanged(MediaPlayer.java:535)
11-25 16:51:49.259 E/ACRA    (13320): 	at org.videolan.libvlc.MediaPlayer$3.onAudioDevicesRemoved(MediaPlayer.java:559)
11-25 16:51:49.259 E/ACRA    (13320): 	at android.media.AudioManager$NativeEventHandlerDelegate$1.handleMessage(AudioManager.java:6270)
11-25 16:51:49.259 E/ACRA    (13320): 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-25 16:51:49.259 E/ACRA    (13320): 	at android.os.Looper.loop(Looper.java:223)
11-25 16:51:49.259 E/ACRA    (13320): 	at android.app.ActivityThread.main(ActivityThread.java:7668)
11-25 16:51:49.259 E/ACRA    (13320): 	at java.lang.reflect.Method.invoke(Native Method)
11-25 16:51:49.259 E/ACRA    (13320): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-25 16:51:49.259 E/ACRA    (13320): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
11-25 16:51:49.259 D/ACRA    (13320): Building report
11-25 16:51:49.260 D/ACRA    (13320): Starting collectors with priority FIRST
11-25 16:51:49.260 D/ACRA    (13320): Calling collector org.acra.collector.DropBoxCollector
11-25 16:51:49.260 D/ACRA    (13320): Collector org.acra.collector.DropBoxCollector completed
11-25 16:51:49.260 D/ACRA    (13320): Calling collector org.acra.collector.StacktraceCollector
11-25 16:51:49.261 D/ACRA    (13320): Collector org.acra.collector.StacktraceCollector completed
11-25 16:51:49.262 D/ACRA    (13320): Calling collector org.acra.collector.LogCatCollector
11-25 16:51:49.270 D/ACRA    (13320): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.14.5` (`140599`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"darcy","BOOTLOADER":"32.00.2019.50-t210-69ebfcbe","BRAND":"NVIDIA","CPU_ABI":"arm64-v8a","CPU_ABI2":"","DEVICE":"mdarcy","DISPLAY":"RQ1A.210105.003.7094531_2971.7725","FINGERPRINT":"NVIDIA\/mdarcy\/mdarcy:11\/RQ1A.210105.003\/7094531_2971.7725:user\/release-keys","HARDWARE":"darcy","HOST":"mobile-u64-5422-d7000","ID":"RQ1A.210105.003","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"NVIDIA","MODEL":"SHIELD Android TV","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"mdarcy","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":["arm64-v8a"],"SUPPORTED_ABIS":["arm64-v8a","armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1644045633000,"TYPE":"user","UNKNOWN":"unknown","USER":"NVIDIA","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"7094531_2971.7725","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"11","RELEASE_OR_CODENAME":"11","SDK":"30","SDK_INT":30,"SECURITY_PATCH":"2022-01-05"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":140599,"VERSION_NAME":"0.14.5"}
```  

### Device information

***Android version***: `11`  
***Device brand***: `NVIDIA`  
***Device product***: `mdarcy`  
***Device model***: `SHIELD Android TV`  

### Crash information

***Start time***: `2022-11-25T13:07:36.986-05:00`  
***Crash time***: `2022-11-25T16:51:49.311-05:00`  

### Application version

0.14.5

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro (2017)

### Android version

Android 9.0.1(33.1.0.283)

### Jellyfin server version

10.8.7

**Comment by nielsvanvelzen** [comment]
Does this crash also happen when you use the 0.15 beta version of the app?

**Comment by j-insan3** [comment]
I have the same issue on the Shield pro. It happens when i have de automatic refresh rate switcher enabled, when i disable this it doens't happen.

Also, when using the 0.15Beta, the whole shield freezes and needs a power reset.

**Comment by loughnane** [comment]
I haven’t tried the 0.15 beta, just whatever is on the App Store. Maybe I’ll pull that down and try.

Re: automatic refresh rate switcher I’m not familiar with that functionality. Is it on by default? If so, where?

**Comment by loughnane** [comment]
Nevernind. Found it under playback in the Jellyfin app. I had been looking at the shield settings.

After switching that off it doesn’t seem to be crashing as it had.

**Comment by Violat0r** [comment]
Seeing this exact crash on my 2019 Shield Pro as well. 

I see it when I press back to return to the main menu or when a video ends and attempts to return to main menu. It mainly crashes the app but other times the Shield will become unresponsive and require a reboot by unplugging the power to the Shield.

Disabling refresh rate switching as suggested above does seem to stop the crashing.

**Comment by nielsvanvelzen** [comment]
I believe I figured out the problem and it should be fixed in the next beta.
