### ISSUE TITLE
(0.15.0-beta3) Series recording in Live TV crash

### ISSUE THREAD

**Issue by MichaelRUSF** [jellyfin/jellyfin-androidtv#2312]
### Describe the bug

Opening up a series recording in the Series menu from Live TV will lead to a crash. This crash also occurred in the last stable build (.14.5). 

### Logs

---
client: Jellyfin for Android TV
client_version: 0.15.0-beta.3
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.NullPointerException
	at org.jellyfin.androidtv.util.sdk.compat.ModelCompat.asSdk(ModelCompat.kt:134)
	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment.setBaseItem(FullDetailsFragment.java:520)
	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment.loadItem(FullDetailsFragment.java:407)
	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment.onCreateView(FullDetailsFragment.java:231)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)

```  
***Logcat***: 
```log
--------- beginning of main
12-05 11:18:08.519 I/BackgroundService(20966): Adding BackgroundServiceFragment to activity
12-05 11:18:08.527 D/ACRA    (20966): onActivityStarted class org.jellyfin.androidtv.ui.browsing.MainActivity
12-05 11:18:08.530 D/ACRA    (20966): onActivityResumed class org.jellyfin.androidtv.ui.browsing.MainActivity
12-05 11:18:08.532 D/BackgroundServiceFragment(20966): Restoring background drawable
12-05 11:18:08.607 D/MediaManager(20966): Added event listener.  Total listeners: 1
12-05 11:18:08.631 I/org.jellyfin.sdk.api.client.KtorClient(20966): GET http://192.168.1.39:8096/LiveTv/Programs/Recommended?userId=2e695138-b100-4cd4-89c0-bc17f36c8608&limit=1&isAiring=true&imageTypeLimit=1&enableTotalRecordCount=false
12-05 11:18:08.677 I/HomeRowsFragment(20966): Updating audio queue in HomeFragment (onResume)
12-05 11:18:08.759 D/mali_winsys(20966): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
12-05 11:18:08.772 D/gralloc (20966): mali_gralloc_select_format: req_format=0x00000001, usage=0x20000b00, req_base_format=0x1, alloc_format=0x8700000001, internal_format=0x8700000001
12-05 11:18:08.811 D/gralloc (20966): mali_gralloc_select_format: req_format=0x00000001, usage=0x20000b00, req_base_format=0x1, alloc_format=0x8700000001, internal_format=0x8700000001
12-05 11:18:08.826 D/jellyfin-apiclient(20966): Adding request to queue: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Views?format=json
12-05 11:18:08.821 I/lyfin.androidt(20966): Background young concurrent copying GC freed 88413(5197KB) AllocSpace objects, 32(1252KB) LOS objects, 77% free, 7111KB/30MB, paused 1.266ms total 233.290ms
12-05 11:18:08.860 D/jellyfin-apiclient(20966): Adding request to queue: http://192.168.1.39:8096/Shows/NextUp?Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&UserId=2e695138-b100-4cd4-89c0-bc17f36c8608&Limit=50&ImageTypeLimit=1&format=json
12-05 11:18:08.865 D/jellyfin-apiclient(20966): Adding request to queue: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items?SortBy=DatePlayed&EnableTotalRecordCount=false&ExcludeLocationTypes=Virtual&MediaTypes=Video&ImageTypeLimit=1&recursive=true&Filters=IsResumable&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount&sortOrder=Descending&Limit=50&format=json
12-05 11:18:08.877 D/jellyfin-apiclient(20966): Adding request to queue: http://192.168.1.39:8096/LiveTv/Programs/Recommended?Fields=Overview%2CPrimaryImageAspectRatio%2CChannelInfo%2CChildCount&UserId=2e695138-b100-4cd4-89c0-bc17f36c8608&EnableTotalRecordCount=false&IsAiring=true&Limit=20&ImageTypeLimit=1&format=json
12-05 11:18:08.882 D/jellyfin-apiclient(20966): Adding request to queue: http://192.168.1.39:8096/Shows/NextUp?Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&UserId=2e695138-b100-4cd4-89c0-bc17f36c8608&Limit=50&ImageTypeLimit=1&format=json
12-05 11:18:08.893 I/org.jellyfin.sdk.api.client.KtorClient(20966): GET http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Views?includeHidden=false
12-05 11:18:08.924 I/org.jellyfin.sdk.api.client.KtorClient(20966): GET http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Views?includeHidden=false
12-05 11:18:08.982 I/lyfin.androidt(20966): Method exceeds compiler instruction limit: 21504 in org.jellyfin.sdk.model.api.BaseItemDto org.jellyfin.sdk.model.api.BaseItemDto$$serializer.deserialize(kotlinx.serialization.encoding.Decoder)
12-05 11:18:09.059 D/jellyfin-apiclient(20966): Adding request to queue: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?ParentId=d49a1e03-df26-2eef-307a-b2ec0b67fa4e&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&Limit=50&GroupItems=true&format=json
12-05 11:18:09.060 D/jellyfin-apiclient(20966): Adding request to queue: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?ParentId=f137a2dd-21bb-c1b9-9aa5-c0f6bf02a805&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&Limit=50&GroupItems=true&format=json
12-05 11:18:09.073 D/jellyfin-apiclient(20966): Adding request to queue: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?ParentId=f53fc094-64c1-5245-f537-3088e52a7f1a&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&Limit=50&GroupItems=true&format=json
12-05 11:18:09.075 D/jellyfin-apiclient(20966): Adding request to queue: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?ParentId=9fcf63d9-3232-c8f3-246c-83c6611ed78d&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&Limit=50&GroupItems=true&format=json
12-05 11:18:09.076 D/jellyfin-apiclient(20966): Adding request to queue: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?ParentId=a656b907-eb3a-7353-2e40-e44b968d0225&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&Limit=50&GroupItems=true&format=json
12-05 11:18:09.077 D/jellyfin-apiclient(20966): Adding request to queue: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?ParentId=bdf38141-c3a3-66eb-1a2a-8240d2e65e68&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&Limit=50&GroupItems=true&format=json
12-05 11:18:09.078 D/jellyfin-apiclient(20966): Adding request to queue: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?ParentId=d7e58e58-ad49-209c-5917-1d6a3ecd6952&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&Limit=50&GroupItems=true&format=json
12-05 11:18:09.080 D/jellyfin-apiclient(20966): Adding request to queue: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?ParentId=7e64e319-657a-9516-ec78-490da03edccb&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&Limit=50&GroupItems=true&format=json
12-05 11:18:09.087 D/jellyfin-apiclient(20966): Adding request to queue: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?ParentId=89613829-c7fa-a2d3-39ba-c9cccce02855&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&Limit=50&GroupItems=true&format=json
12-05 11:18:09.088 D/jellyfin-apiclient(20966): Adding request to queue: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?ParentId=79a2726d-3c50-e769-a8af-1e4184e4fccf&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&Limit=50&GroupItems=true&format=json
12-05 11:18:09.295 I/lyfin.androidt(20966): Method exceeds compiler instruction limit: 21504 in org.jellyfin.sdk.model.api.BaseItemDto org.jellyfin.sdk.model.api.BaseItemDto$$serializer.deserialize(kotlinx.serialization.encoding.Decoder)
12-05 11:18:09.404 D/gralloc (20966): mali_gralloc_select_format: req_format=0x00000001, usage=0x20000b00, req_base_format=0x1, alloc_format=0x8700000001, internal_format=0x8700000001
12-05 11:18:09.405 I/jellyfin-apiclient(20966): Response received from: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Views?format=json
12-05 11:18:09.505 D/ItemRowAdapterHelperKt(20966): Creating items from 0 existing and 12 new, adapter size is 0
12-05 11:18:09.533 I/jellyfin-apiclient(20966): Response received from: http://192.168.1.39:8096/LiveTv/Programs/Recommended?Fields=Overview%2CPrimaryImageAspectRatio%2CChannelInfo%2CChildCount&UserId=2e695138-b100-4cd4-89c0-bc17f36c8608&EnableTotalRecordCount=false&IsAiring=true&Limit=20&ImageTypeLimit=1&format=json
12-05 11:18:09.593 I/jellyfin-apiclient(20966): Response received from: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items?SortBy=DatePlayed&EnableTotalRecordCount=false&ExcludeLocationTypes=Virtual&MediaTypes=Video&ImageTypeLimit=1&recursive=true&Filters=IsResumable&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount&sortOrder=Descending&Limit=50&format=json
12-05 11:18:09.622 D/ItemRowAdapterHelperKt(20966): Creating items from 0 existing and 6 new, adapter size is 0
12-05 11:18:09.640 I/jellyfin-apiclient(20966): Response received from: http://192.168.1.39:8096/Shows/NextUp?Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&UserId=2e695138-b100-4cd4-89c0-bc17f36c8608&Limit=50&ImageTypeLimit=1&format=json
12-05 11:18:09.688 I/jellyfin-apiclient(20966): Response received from: http://192.168.1.39:8096/Shows/NextUp?Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&UserId=2e695138-b100-4cd4-89c0-bc17f36c8608&Limit=50&ImageTypeLimit=1&format=json
12-05 11:18:09.735 I/Choreographer(20966): Skipped 32 frames!  The application may be doing too much work on its main thread.
12-05 11:18:10.307 I/OpenGLRenderer(20966): Davey! duration=1116ms; Flags=0, IntendedVsync=73934169973521, Vsync=73934703306833, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=73934715574122, AnimationStart=73934715600122, PerformTraversalsStart=73934716505205, DrawStart=73935174481705, SyncQueued=73935189005455, SyncStart=73935189848788, IssueDrawCommandsStart=73935226214955, SwapBuffers=73935286530288, FrameCompleted=73935287321455, DequeueBufferDuration=698000, QueueBufferDuration=270000, 
12-05 11:18:10.308 D/ACRA    (20966): onActivityStopped class org.jellyfin.androidtv.ui.startup.StartupActivity
12-05 11:18:10.312 D/ACRA    (20966): onActivityDestroyed class org.jellyfin.androidtv.ui.startup.StartupActivity
12-05 11:18:10.315 D/Compose Focus(20966): Owner FocusChanged(false)
12-05 11:18:10.316 D/Compose Focus(20966): Owner FocusChanged(true)
12-05 11:18:10.316 D/Compose Focus(20966): Owner FocusChanged(false)
12-05 11:18:10.342 W/libEGL  (20966): EGLNativeWindowType 0xdf918ea8 disconnect failed
12-05 11:18:10.346 I/jellyfin-apiclient(20966): Response received from: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?ParentId=d49a1e03-df26-2eef-307a-b2ec0b67fa4e&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&Limit=50&GroupItems=true&format=json
12-05 11:18:10.402 D/ItemRowAdapterHelperKt(20966): Creating items from 0 existing and 31 new, adapter size is 0
12-05 11:18:10.447 I/jellyfin-apiclient(20966): Response received from: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?ParentId=9fcf63d9-3232-c8f3-246c-83c6611ed78d&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&Limit=50&GroupItems=true&format=json
12-05 11:18:10.458 D/ItemRowAdapterHelperKt(20966): Creating items from 0 existing and 12 new, adapter size is 0
12-05 11:18:10.467 I/jellyfin-apiclient(20966): Response received from: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?ParentId=f53fc094-64c1-5245-f537-3088e52a7f1a&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&Limit=50&GroupItems=true&format=json
12-05 11:18:10.475 I/WM-WorkerWrapper(20966): Worker result SUCCESS for Work [ id=c1924009-c931-4297-b24a-74ead1c48a32, tags={ org.jellyfin.androidtv.integration.LeanbackChannelWorker } ]
12-05 11:18:10.508 D/ItemRowAdapterHelperKt(20966): Creating items from 0 existing and 32 new, adapter size is 0
12-05 11:18:10.534 I/jellyfin-apiclient(20966): Response received from: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?ParentId=f137a2dd-21bb-c1b9-9aa5-c0f6bf02a805&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&Limit=50&GroupItems=true&format=json
12-05 11:18:10.584 D/ItemRowAdapterHelperKt(20966): Creating items from 0 existing and 50 new, adapter size is 0
12-05 11:18:10.645 I/jellyfin-apiclient(20966): Response received from: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?ParentId=bdf38141-c3a3-66eb-1a2a-8240d2e65e68&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&Limit=50&GroupItems=true&format=json
12-05 11:18:10.653 D/ItemRowAdapterHelperKt(20966): Creating items from 0 existing and 9 new, adapter size is 0
12-05 11:18:10.660 I/jellyfin-apiclient(20966): Response received from: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?ParentId=d7e58e58-ad49-209c-5917-1d6a3ecd6952&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&Limit=50&GroupItems=true&format=json
12-05 11:18:10.688 D/ItemRowAdapterHelperKt(20966): Creating items from 0 existing and 50 new, adapter size is 0
12-05 11:18:10.718 I/jellyfin-apiclient(20966): Response received from: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?ParentId=a656b907-eb3a-7353-2e40-e44b968d0225&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&Limit=50&GroupItems=true&format=json
12-05 11:18:10.729 D/ItemRowAdapterHelperKt(20966): Creating items from 0 existing and 27 new, adapter size is 0
12-05 11:18:10.749 I/jellyfin-apiclient(20966): Response received from: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?ParentId=7e64e319-657a-9516-ec78-490da03edccb&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&Limit=50&GroupItems=true&format=json
12-05 11:18:10.758 D/ItemRowAdapterHelperKt(20966): Creating items from 0 existing and 35 new, adapter size is 0
12-05 11:18:10.797 I/jellyfin-apiclient(20966): Response received from: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?ParentId=79a2726d-3c50-e769-a8af-1e4184e4fccf&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&Limit=50&GroupItems=true&format=json
12-05 11:18:10.798 D/ItemRowAdapterHelperKt(20966): Creating items from 0 existing and 2 new, adapter size is 0
12-05 11:18:10.800 I/jellyfin-apiclient(20966): Response received from: http://192.168.1.39:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?ParentId=89613829-c7fa-a2d3-39ba-c9cccce02855&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&Limit=50&GroupItems=true&format=json
12-05 11:18:10.815 D/ItemRowAdapterHelperKt(20966): Creating items from 0 existing and 45 new, adapter size is 0
12-05 11:18:10.825 I/Choreographer(20966): Skipped 65 frames!  The application may be doing too much work on its main thread.
12-05 11:18:10.850 I/OpenGLRenderer(20966): Davey! duration=1110ms; Flags=0, IntendedVsync=73934719874911, Vsync=73935803208201, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=73935805869538, AnimationStart=73935805896538, PerformTraversalsStart=73935812371872, DrawStart=73935824591955, SyncQueued=73935825462288, SyncStart=73935825738872, IssueDrawCommandsStart=73935826848205, SwapBuffers=73935828594788, FrameCompleted=73935830524622, DequeueBufferDuration=209000, QueueBufferDuration=559000, 
12-05 11:18:11.275 I/AutoBitrate(20966): Auto bitrate set to: 10362694
12-05 11:18:11.369 I/lyfin.androidt(20966): Background concurrent copying GC freed 309331(12MB) AllocSpace objects, 94(5624KB) LOS objects, 50% free, 15MB/31MB, paused 114us total 129.394ms
12-05 11:18:12.958 D/ProfileInstaller(20966): Skipping profile installation for org.jellyfin.androidtv
12-05 11:18:18.481 D/NavigationRepositoryImpl(20966): Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.browsing.BrowseViewFragment (Kotlin reflection is not available), arguments=Bundle[{folder={"Id":"11111111-0000-0000-0000-000000000002","Type":"Folder","DisplayPreferencesId":"11111111-0000-0000-0000-000000000002","CollectionType":"SeriesTimers"}}])
12-05 11:18:18.501 D/jellyfin-apiclient(20966): Adding request to queue: http://192.168.1.39:8096/LiveTv/SeriesTimers?SortOrder=Ascending&format=json
12-05 11:18:18.529 D/MediaManager(20966): Added event listener.  Total listeners: 2
12-05 11:18:18.558 W/View    (20966): requestLayout() improperly called by android.widget.TextView{4afb835 V.ED..... ......ID 120,40-1578,126 #7f0b02fb app:id/title} during layout: running second layout pass
12-05 11:18:18.559 W/View    (20966): requestLayout() improperly called by android.widget.LinearLayout{6efc4ca V.E...... ......ID 120,132-1598,172 #7f0b01a4 app:id/infoRow} during layout: running second layout pass
12-05 11:18:18.561 I/jellyfin-apiclient(20966): Response received from: http://192.168.1.39:8096/LiveTv/SeriesTimers?SortOrder=Ascending&format=json
12-05 11:18:18.599 D/skia    (20966): --- Failed to create image decoder with message 'unimplemented'
12-05 11:18:18.603 I/chatty  (20966): uid=10225(org.jellyfin.androidtv) glide-source-th identical 4 lines
12-05 11:18:18.603 D/skia    (20966): --- Failed to create image decoder with message 'unimplemented'
12-05 11:18:18.637 W/View    (20966): requestLayout() improperly called by android.widget.LinearLayout{6efc4ca V.E...... ......ID 120,132-1598,172 #7f0b01a4 app:id/infoRow} during layout: running second layout pass
12-05 11:18:18.637 W/View    (20966): requestLayout() improperly called by android.widget.TextView{4afb835 V.ED..... ......ID 120,40-1578,126 #7f0b02fb app:id/title} during layout: running second layout pass
12-05 11:18:32.191 I/AssistStructure(20966): Flattened final assist data: 3860 bytes, containing 1 windows, 39 views
12-05 11:18:38.363 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(20966): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
12-05 11:18:38.366 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(20966): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"626825092791469a85ed76c614c7a4aa"}
12-05 11:18:42.456 D/NavigationRepositoryImpl(20966): Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment (Kotlin reflection is not available), arguments=Bundle[{ItemId=59a0b3f2-1674-2684-2733-d4d8f1b5ed87, SeriesTimer={"Id":"59a0b3f2167426842733d4d8f1b5ed87","Type":"SeriesTimer","ServerId":"14563fffa3c04620aeb3595c0fa1015d","ExternalId":"54816f2018ca4d43be58daf2141c4ca6","ChannelId":"11a5332e-6882-9f79-c11c-710ff0103259","ExternalChannelId":"hdhr_10.1","ChannelName":"WTSP-HD","ProgramId":"24b237792ae7fd482cca4175120d1def","ExternalProgramId":"I10.1.20495.zap2it.com_2022-08-03T19:30:00.0000000-04:00_hdhr_10.1","Name":"Jeopardy!","Overview":"Matt Amodio; Jessica Stephens; Jonathan Fisher.","StartDate":"2022-08-03T23:30:00-04:00","EndDate":"2022-08-04T00:00:00-04:00","ServiceName":"Emby","Priority":0,"PrePaddingSeconds":0,"PostPaddingSeconds":0,"IsPrePaddingRequired":false,"ParentBackdropItemId":"51a8f0e184f84eb5508d03cf5f9c6a3e","ParentBackdropImageTags":["a886dd018b9e46362c3260570c3d3806"],"IsPostPaddingRequired":false,"KeepUntil":"UntilDeleted","RecordAnyTime":true,"SkipEpisodesInLibrary":true,"RecordAnyChannel":false,"KeepUpTo":0,"RecordNewOnly":true,"Days":["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],"DayPattern":"Daily","ImageTags":{},"ParentPrimaryImageItemId":"51a8f0e184f84eb5508d03cf5f9c6a3e","ParentPrimaryImageTag":"57b8ef9daa45a64e7e975c65aec13a93"}}])
12-05 11:18:42.484 D/AndroidRuntime(20966): Shutting down VM
--------- beginning of crash
12-05 11:18:42.484 E/AndroidRuntime(20966): FATAL EXCEPTION: main
12-05 11:18:42.484 E/AndroidRuntime(20966): Process: org.jellyfin.androidtv, PID: 20966
12-05 11:18:42.484 E/AndroidRuntime(20966): java.lang.NullPointerException
12-05 11:18:42.484 E/AndroidRuntime(20966): 	at org.jellyfin.androidtv.util.sdk.compat.ModelCompat.asSdk(ModelCompat.kt:134)
12-05 11:18:42.484 E/AndroidRuntime(20966): 	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment.setBaseItem(FullDetailsFragment.java:520)
12-05 11:18:42.484 E/AndroidRuntime(20966): 	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment.loadItem(FullDetailsFragment.java:407)
12-05 11:18:42.484 E/AndroidRuntime(20966): 	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment.onCreateView(FullDetailsFragment.java:231)
12-05 11:18:42.484 E/AndroidRuntime(20966): 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
12-05 11:18:42.484 E/AndroidRuntime(20966): 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
12-05 11:18:42.484 E/AndroidRuntime(20966): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
12-05 11:18:42.484 E/AndroidRuntime(20966): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
12-05 11:18:42.484 E/AndroidRuntime(20966): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
12-05 11:18:42.484 E/AndroidRuntime(20966): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
12-05 11:18:42.484 E/AndroidRuntime(20966): 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
12-05 11:18:42.484 E/AndroidRuntime(20966): 	at android.os.Handler.handleCallback(Handler.java:883)
12-05 11:18:42.484 E/AndroidRuntime(20966): 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-05 11:18:42.484 E/AndroidRuntime(20966): 	at android.os.Looper.loop(Looper.java:214)
12-05 11:18:42.484 E/AndroidRuntime(20966): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
12-05 11:18:42.484 E/AndroidRuntime(20966): 	at java.lang.reflect.Method.invoke(Native Method)
12-05 11:18:42.484 E/AndroidRuntime(20966): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-05 11:18:42.484 E/AndroidRuntime(20966): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
12-05 11:18:42.484 E/ACRA    (20966): ACRA caught a NullPointerException for org.jellyfin.androidtv
12-05 11:18:42.484 E/ACRA    (20966): java.lang.NullPointerException
12-05 11:18:42.484 E/ACRA    (20966): 	at org.jellyfin.androidtv.util.sdk.compat.ModelCompat.asSdk(ModelCompat.kt:134)
12-05 11:18:42.484 E/ACRA    (20966): 	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment.setBaseItem(FullDetailsFragment.java:520)
12-05 11:18:42.484 E/ACRA    (20966): 	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment.loadItem(FullDetailsFragment.java:407)
12-05 11:18:42.484 E/ACRA    (20966): 	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment.onCreateView(FullDetailsFragment.java:231)
12-05 11:18:42.484 E/ACRA    (20966): 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
12-05 11:18:42.484 E/ACRA    (20966): 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
12-05 11:18:42.484 E/ACRA    (20966): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
12-05 11:18:42.484 E/ACRA    (20966): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
12-05 11:18:42.484 E/ACRA    (20966): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
12-05 11:18:42.484 E/ACRA    (20966): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
12-05 11:18:42.484 E/ACRA    (20966): 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
12-05 11:18:42.484 E/ACRA    (20966): 	at android.os.Handler.handleCallback(Handler.java:883)
12-05 11:18:42.484 E/ACRA    (20966): 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-05 11:18:42.484 E/ACRA    (20966): 	at android.os.Looper.loop(Looper.java:214)
12-05 11:18:42.484 E/ACRA    (20966): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
12-05 11:18:42.484 E/ACRA    (20966): 	at java.lang.reflect.Method.invoke(Native Method)
12-05 11:18:42.484 E/ACRA    (20966): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-05 11:18:42.484 E/ACRA    (20966): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
12-05 11:18:42.484 D/ACRA    (20966): Building report
12-05 11:18:42.485 D/ACRA    (20966): Starting collectors with priority FIRST
12-05 11:18:42.486 D/ACRA    (20966): Calling collector org.acra.collector.DropBoxCollector
12-05 11:18:42.486 D/ACRA    (20966): Calling collector org.acra.collector.LogCatCollector
12-05 11:18:42.486 D/ACRA    (20966): Collector org.acra.collector.DropBoxCollector completed
12-05 11:18:42.486 D/ACRA    (20966): Calling collector org.acra.collector.StacktraceCollector
12-05 11:18:42.487 D/ACRA    (20966): Collector org.acra.collector.StacktraceCollector completed
12-05 11:18:42.493 D/ACRA    (20966): Retrieving logcat output (buffer:default)...
12-05 11:18:42.506 E/libc    (21270): Access denied finding property "persist.vendor.system.svp.dbg.loglevel"

```  

### App information

***App version***: `0.15.0-beta.3` (`150003`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"mt5895","BOOTLOADER":"unknown","BRAND":"Sony","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"BRAVIA_VH2","DISPLAY":"BRAVIA_VH2_M_UC-user 10 QTG3.200305.006.S252 660701 release-keys","FINGERPRINT":"Sony\/BRAVIA_VH2_M_UC\/BRAVIA_VH2:10\/QTG3.200305.006.S252\/660701:user\/release-keys","HARDWARE":"mt5895","HOST":"BuildHost708","ID":"QTG3.200305.006.S252","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Sony","MODEL":"BRAVIA 4K VH2","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"BRAVIA_VH2_M_UC","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1666962932000,"TYPE":"user","UNKNOWN":"unknown","USER":"root","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","FIRST_SDK_INT":29,"INCREMENTAL":"660701","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"10","RESOURCES_SDK_INT":29,"SDK":"29","SDK_INT":29,"SECURITY_PATCH":"2022-09-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":150003,"VERSION_NAME":"0.15.0-beta.3"}
```  

### Device information

***Android version***: `10`  
***Device brand***: `Sony`  
***Device product***: `BRAVIA_VH2_M_UC`  
***Device model***: `BRAVIA 4K VH2`  

### Crash information

***Start time***: `2022-12-05T11:18:06.821-05:00`  
***Crash time***: `2022-12-05T11:18:42.530-05:00`  

### Application version

0.15.0-beta3

### Where did you install the app from?

Sideloaded APK

### Device information

Sony Bravia 4k VH2

### Android version

Android TV OS 10

### Jellyfin server version

10.8.8

**Comment by nielsvanvelzen** [comment]
This issue might be fixed in the next beta, but I'm unable to test it.
