### ISSUE TITLE
Crash when selecting favorites playlist in music library

### ISSUE THREAD

**Issue by crobibero** [jellyfin/jellyfin-androidtv#2349]
### Describe the bug

1. Go to music library
2. Click on "Favorites" playlist
3. Crash

I don't have any music favorited

### Logs

---
client: Jellyfin for Android TV
client_version: 0.15.0-beta.4
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.LinearLayout.removeAllViews()' on a null object reference
	at org.jellyfin.androidtv.util.InfoLayoutHelper.addInfoRow(InfoLayoutHelper.java:50)
	at org.jellyfin.androidtv.ui.itemdetail.ItemListFragment.setBaseItem(ItemListFragment.java:355)
	at org.jellyfin.androidtv.ui.itemdetail.ItemListFragment.loadItem(ItemListFragment.java:337)
	at org.jellyfin.androidtv.ui.itemdetail.ItemListFragment.onCreateView(ItemListFragment.java:164)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6721)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```  
***Logcat***: 
```log
12-14 18:19:40.384 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(28627): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"e5ec3873b64b4f059b38a33557847c9e"}
12-14 18:19:40.384 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(28627): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"d16566d184744c27a955e86d22c1c564"}
12-14 18:19:40.385 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(28627): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"5fbd6db0db0b480186c084529877fb2b"}
12-14 18:19:40.386 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(28627): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"eff4af5a468f4d1e83c21e0ccca4c728"}
12-14 18:19:40.443 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(28627): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"98f38babee0046b1b1f421c648e53eef"}
12-14 18:19:40.444 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(28627): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"ecd6ec71adc44b5e94644258eaedec26"}
12-14 18:20:10.416 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(28627): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
12-14 18:20:10.478 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(28627): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"70d924ec8c5e4c0da7cb8e3e126063e9"}
12-14 18:20:40.449 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(28627): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
12-14 18:20:40.512 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(28627): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"2e4a86a98dba465cbb7f3b66306045c8"}
12-14 18:21:10.472 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(28627): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
12-14 18:21:10.534 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(28627): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"d722a2682fa847818b6551feafd0c887"}
12-14 18:21:40.514 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(28627): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
12-14 18:21:40.573 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(28627): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"5c1bad7d861b4eaa8b6671e25f1b12ff"}
12-14 18:22:10.520 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(28627): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
12-14 18:22:10.578 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(28627): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"876250840b0149d591d889ca3adc1f07"}
12-14 18:22:40.560 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(28627): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
12-14 18:22:40.622 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(28627): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"8fda60fb36754f8eae61f148636ef988"}
12-14 18:23:09.797 D/ACRA    (28627): onActivityStarted class org.jellyfin.androidtv.ui.browsing.MainActivity
12-14 18:23:09.806 I/ProcessLifecycleInitializer$create(28627): Process lifecycle started
12-14 18:23:09.807 D/SessionRepositoryImpl(28627): Restoring session
12-14 18:23:09.821 D/ACRA    (28627): onActivityResumed class org.jellyfin.androidtv.ui.browsing.MainActivity
12-14 18:23:09.824 D/BackgroundServiceFragment(28627): Restoring active backgrounds
12-14 18:23:09.825 D/BackgroundServiceFragment(28627): Restoring background drawable
12-14 18:23:09.828 I/HomeRowsFragment(28627): Updating audio queue in HomeFragment (onResume)
12-14 18:23:10.601 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(28627): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
12-14 18:23:10.664 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(28627): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"de7ac1e8474a4cd793b9937037d2ea08"}
12-14 18:23:13.046 D/ItemLauncher(28627): Item selected: 6 - Music (CollectionFolder)
12-14 18:23:13.047 D/ItemLauncher(28627): **** Collection type: music
12-14 18:23:13.060 D/NavigationRepositoryImpl(28627): Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.browsing.BrowseViewFragment (Kotlin reflection is not available), arguments=Bundle[{folder={"Name":"Music","ServerId":"88a04f45760f45119f97d206a33042af","Id":"7e64e319-657a-9516-ec78-490da03edccb","Etag":"6496f4ea72688c177948fb91398e097e","DateCreated":"2022-10-05T21:24:17-06:00","CanDelete":false,"CanDownload":false,"SupportsSync":false,"SortName":"music","ExternalUrls":[],"Path":"/config/root/default/Music","EnableMediaSourceDisplay":false,"Taglines":[],"Genres":[],"PlayAccess":"Full","RemoteTrailers":[],"ProviderIds":{},"IsFolder":true,"ParentId":"e9d5075a-555c-1cbc-394e-ec4cef295274","Type":"CollectionFolder","People":[],"Studios":[],"GenreItems":[],"LocalTrailerCount":0,"UserData":{"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"7e64e319-657a-9516-ec78-490da03edccb"},"ChildCount":2,"SpecialFeatureCount":0,"DisplayPreferencesId":"7e64e319657a9516ec78490da03edccb","Tags":[],"PrimaryImageAspectRatio":1.7777777777777777,"CollectionType":"music","ImageTags":{"Primary":"a054d327686195cba36b3add8759954b"},"BackdropImageTags":[],"ImageBlurHashes":{"Primary":{"a054d327686195cba36b3add8759954b":"WBAc@{0MM{bco1%M%Mt6WDoyaKWV9FoL-;ofM{WBWBj[ofj[WCay"}},"LocationType":"FileSystem","LockedFields":[],"LockData":false}}])
12-14 18:23:13.097 D/jellyfin-apiclient(28627): Adding request to queue: https://jellyfin.domain.tld/Users/2130c095-606e-4961-9adc-bacfbdabe373/Items/Latest?ParentId=7e64e319-657a-9516-ec78-490da03edccb&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&IncludeItemTypes=Audio&Limit=50&GroupItems=true&format=json
12-14 18:23:13.101 D/jellyfin-apiclient(28627): Adding request to queue: https://jellyfin.domain.tld/Users/2130c095-606e-4961-9adc-bacfbdabe373/Items?SortBy=DatePlayed&EnableTotalRecordCount=false&ImageTypeLimit=1&recursive=true&Filters=IsPlayed&IncludeItemTypes=Audio&ParentId=7e64e319-657a-9516-ec78-490da03edccb&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount&sortOrder=Descending&Limit=50&format=json
12-14 18:23:13.104 D/jellyfin-apiclient(28627): Adding request to queue: https://jellyfin.domain.tld/Users/2130c095-606e-4961-9adc-bacfbdabe373/Items?ParentId=7e64e319-657a-9516-ec78-490da03edccb&SortBy=SortName&ImageTypeLimit=1&recursive=true&Filters=IsFavorite&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount&Limit=60&IncludeItemTypes=MusicAlbum%2CMusicArtist&format=json
12-14 18:23:13.107 D/jellyfin-apiclient(28627): Adding request to queue: https://jellyfin.domain.tld/Users/2130c095-606e-4961-9adc-bacfbdabe373/Items?SortBy=DateCreated&ImageTypeLimit=1&recursive=true&Fields=PrimaryImageAspectRatio%2CCumulativeRunTimeTicks%2CChildCount&sortOrder=Descending&Limit=60&IncludeItemTypes=Playlist&format=json
12-14 18:23:13.157 D/MediaManager(28627): Added event listener.  Total listeners: 2
12-14 18:23:13.280 W/View    (28627): requestLayout() improperly called by android.widget.TextView{6178fe3 V.ED..... ......ID 120,40-1600,126 #7f0b02fb app:id/title} during layout: running second layout pass
12-14 18:23:13.280 W/View    (28627): requestLayout() improperly called by android.widget.LinearLayout{2719de0 V.E...... ......ID 120,132-1620,172 #7f0b01a4 app:id/infoRow} during layout: running second layout pass
12-14 18:23:13.417 I/jellyfin-apiclient(28627): Response received from: https://jellyfin.domain.tld/Users/2130c095-606e-4961-9adc-bacfbdabe373/Items?ParentId=7e64e319-657a-9516-ec78-490da03edccb&SortBy=SortName&ImageTypeLimit=1&recursive=true&Filters=IsFavorite&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount&Limit=60&IncludeItemTypes=MusicAlbum%2CMusicArtist&format=json
12-14 18:23:13.419 I/jellyfin-apiclient(28627): Response received from: https://jellyfin.domain.tld/Users/2130c095-606e-4961-9adc-bacfbdabe373/Items?SortBy=DateCreated&ImageTypeLimit=1&recursive=true&Fields=PrimaryImageAspectRatio%2CCumulativeRunTimeTicks%2CChildCount&sortOrder=Descending&Limit=60&IncludeItemTypes=Playlist&format=json
12-14 18:23:13.529 W/View    (28627): requestLayout() improperly called by android.widget.TextView{6178fe3 V.ED..... ......ID 120,40-1600,126 #7f0b02fb app:id/title} during layout: running second layout pass
12-14 18:23:13.529 W/View    (28627): requestLayout() improperly called by android.widget.LinearLayout{2719de0 V.E...... ......ID 120,132-1620,172 #7f0b01a4 app:id/infoRow} during layout: running second layout pass
12-14 18:23:13.625 I/jellyfin-apiclient(28627): Response received from: https://jellyfin.domain.tld/Users/2130c095-606e-4961-9adc-bacfbdabe373/Items?SortBy=DatePlayed&EnableTotalRecordCount=false&ImageTypeLimit=1&recursive=true&Filters=IsPlayed&IncludeItemTypes=Audio&ParentId=7e64e319-657a-9516-ec78-490da03edccb&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount&sortOrder=Descending&Limit=50&format=json
12-14 18:23:13.644 D/ItemRowAdapterHelperKt(28627): Creating items from 0 existing and 50 new, adapter size is 0
12-14 18:23:13.826 I/jellyfin-apiclient(28627): Response received from: https://jellyfin.domain.tld/Users/2130c095-606e-4961-9adc-bacfbdabe373/Items/Latest?ParentId=7e64e319-657a-9516-ec78-490da03edccb&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&IncludeItemTypes=Audio&Limit=50&GroupItems=true&format=json
12-14 18:23:13.832 D/ItemRowAdapterHelperKt(28627): Creating items from 0 existing and 23 new, adapter size is 0
12-14 18:23:14.048 W/View    (28627): requestLayout() improperly called by android.widget.LinearLayout{2719de0 V.E...... ......ID 120,132-1620,172 #7f0b01a4 app:id/infoRow} during layout: running second layout pass
12-14 18:23:14.048 W/View    (28627): requestLayout() improperly called by android.widget.TextView{6178fe3 V.ED..... ......ID 120,40-1600,126 #7f0b02fb app:id/title} during layout: running second layout pass
12-14 18:23:15.470 D/NavigationRepositoryImpl(28627): Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.itemdetail.ItemListFragment (Kotlin reflection is not available), arguments=Bundle[{ItemId=11111111-0000-0000-0000-000000000001, ParentId=7e64e319-657a-9516-ec78-490da03edccb}])
12-14 18:23:15.557 D/AndroidRuntime(28627): Shutting down VM
--------- beginning of crash
12-14 18:23:15.559 E/AndroidRuntime(28627): FATAL EXCEPTION: main
12-14 18:23:15.559 E/AndroidRuntime(28627): Process: org.jellyfin.androidtv.debug, PID: 28627
12-14 18:23:15.559 E/AndroidRuntime(28627): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.LinearLayout.removeAllViews()' on a null object reference
12-14 18:23:15.559 E/AndroidRuntime(28627): 	at org.jellyfin.androidtv.util.InfoLayoutHelper.addInfoRow(InfoLayoutHelper.java:50)
12-14 18:23:15.559 E/AndroidRuntime(28627): 	at org.jellyfin.androidtv.ui.itemdetail.ItemListFragment.setBaseItem(ItemListFragment.java:355)
12-14 18:23:15.559 E/AndroidRuntime(28627): 	at org.jellyfin.androidtv.ui.itemdetail.ItemListFragment.loadItem(ItemListFragment.java:337)
12-14 18:23:15.559 E/AndroidRuntime(28627): 	at org.jellyfin.androidtv.ui.itemdetail.ItemListFragment.onCreateView(ItemListFragment.java:164)
12-14 18:23:15.559 E/AndroidRuntime(28627): 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
12-14 18:23:15.559 E/AndroidRuntime(28627): 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
12-14 18:23:15.559 E/AndroidRuntime(28627): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
12-14 18:23:15.559 E/AndroidRuntime(28627): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
12-14 18:23:15.559 E/AndroidRuntime(28627): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
12-14 18:23:15.559 E/AndroidRuntime(28627): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
12-14 18:23:15.559 E/AndroidRuntime(28627): 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
12-14 18:23:15.559 E/AndroidRuntime(28627): 	at android.os.Handler.handleCallback(Handler.java:873)
12-14 18:23:15.559 E/AndroidRuntime(28627): 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-14 18:23:15.559 E/AndroidRuntime(28627): 	at android.os.Looper.loop(Looper.java:193)
12-14 18:23:15.559 E/AndroidRuntime(28627): 	at android.app.ActivityThread.main(ActivityThread.java:6721)
12-14 18:23:15.559 E/AndroidRuntime(28627): 	at java.lang.reflect.Method.invoke(Native Method)
12-14 18:23:15.559 E/AndroidRuntime(28627): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-14 18:23:15.559 E/AndroidRuntime(28627): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
12-14 18:23:15.560 E/ACRA    (28627): ACRA caught a NullPointerException for org.jellyfin.androidtv.debug
12-14 18:23:15.560 E/ACRA    (28627): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.LinearLayout.removeAllViews()' on a null object reference
12-14 18:23:15.560 E/ACRA    (28627): 	at org.jellyfin.androidtv.util.InfoLayoutHelper.addInfoRow(InfoLayoutHelper.java:50)
12-14 18:23:15.560 E/ACRA    (28627): 	at org.jellyfin.androidtv.ui.itemdetail.ItemListFragment.setBaseItem(ItemListFragment.java:355)
12-14 18:23:15.560 E/ACRA    (28627): 	at org.jellyfin.androidtv.ui.itemdetail.ItemListFragment.loadItem(ItemListFragment.java:337)
12-14 18:23:15.560 E/ACRA    (28627): 	at org.jellyfin.androidtv.ui.itemdetail.ItemListFragment.onCreateView(ItemListFragment.java:164)
12-14 18:23:15.560 E/ACRA    (28627): 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
12-14 18:23:15.560 E/ACRA    (28627): 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
12-14 18:23:15.560 E/ACRA    (28627): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
12-14 18:23:15.560 E/ACRA    (28627): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
12-14 18:23:15.560 E/ACRA    (28627): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
12-14 18:23:15.560 E/ACRA    (28627): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
12-14 18:23:15.560 E/ACRA    (28627): 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
12-14 18:23:15.560 E/ACRA    (28627): 	at android.os.Handler.handleCallback(Handler.java:873)
12-14 18:23:15.560 E/ACRA    (28627): 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-14 18:23:15.560 E/ACRA    (28627): 	at android.os.Looper.loop(Looper.java:193)
12-14 18:23:15.560 E/ACRA    (28627): 	at android.app.ActivityThread.main(ActivityThread.java:6721)
12-14 18:23:15.560 E/ACRA    (28627): 	at java.lang.reflect.Method.invoke(Native Method)
12-14 18:23:15.560 E/ACRA    (28627): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-14 18:23:15.560 E/ACRA    (28627): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
12-14 18:23:15.560 D/ACRA    (28627): Building report
12-14 18:23:15.562 D/ACRA    (28627): Starting collectors with priority FIRST
12-14 18:23:15.563 D/ACRA    (28627): Calling collector org.acra.collector.LogCatCollector
12-14 18:23:15.563 D/ACRA    (28627): Calling collector org.acra.collector.DropBoxCollector
12-14 18:23:15.563 D/ACRA    (28627): Collector org.acra.collector.DropBoxCollector completed
12-14 18:23:15.563 D/ACRA    (28627): Calling collector org.acra.collector.StacktraceCollector
12-14 18:23:15.564 D/ACRA    (28627): Collector org.acra.collector.StacktraceCollector completed
12-14 18:23:15.566 D/ACRA    (28627): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.15.0-beta.4` (`150004`)  
***Package name***: `org.jellyfin.androidtv.debug`  
***Build***: 
```json
{"BOARD":"sif","BOOTLOADER":"32.00.2019.50-t210-79558a05","BRAND":"NVIDIA","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"sif","DISPLAY":"PPR1.180610.011.4079180_2740.7538","FINGERPRINT":"NVIDIA\/sif\/sif:9\/PPR1.180610.011\/4079180_2740.7538:user\/release-keys","HARDWARE":"sif","HOST":"mobile-u64-5495-d6000","ID":"PPR1.180610.011","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"NVIDIA","MODEL":"SHIELD Android TV","PERMISSIONS_REVIEW_REQUIRED":false,"PRODUCT":"sif","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1621883973000,"TYPE":"user","UNKNOWN":"unknown","USER":"NVIDIA","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","FIRST_SDK_INT":28,"INCREMENTAL":"4079180_2740.7538","PREVIEW_SDK_INT":0,"RELEASE":"9","RESOURCES_SDK_INT":28,"SDK":"28","SDK_INT":28,"SECURITY_PATCH":"2021-04-05"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv.debug","BUILD_TYPE":"debug","DEBUG":true,"DEVELOPMENT":false,"VERSION_CODE":150004,"VERSION_NAME":"0.15.0-beta.4"}
```  

### Device information

***Android version***: `9`  
***Device brand***: `NVIDIA`  
***Device product***: `sif`  
***Device model***: `SHIELD Android TV`  

### Crash information

***Start time***: `2022-12-14T18:09:22.587-07:00`  
***Crash time***: `2022-12-14T18:23:15.601-07:00`  

### Application version

0.15.0-beta.4

### Where did you install the app from?

Sideloaded APK

### Device information

Nvidia Shield Pro (2019)

### Android version

Android 9

### Jellyfin server version

10.8.8

**Comment by nielsvanvelzen** [comment]
Fixed in the next beta, thanks for the report!
