### ISSUE TITLE
Firestick 4k will not play h264 files with dts audio

### ISSUE THREAD

**Issue by parkerRose** [jellyfin/jellyfin-androidtv#2357]
### Describe the bug

Hello,
I use Jellyfin to play my bluray rips, and a lot of the audio is encoded in DTS and video in h264. These files won't play on the AndroidTV 0.15.0 release or the 0.14 release on the Amazon Appstore. It just gives 'player error occurred' and boots me back to the library. It will play files with DTS audio encoding with the video in different formats (I have older blurays encoded in VC1/DTS that work) and h264 files with TrueHD audio work, so it's not either of these in isolation. Additionally, the files play on the web client of jellyfin, so they are fine files.
 Please let me know if you need more technical details / logs (please provide instructions on how to get those logs too because I am not the most technically advanced).

### Application version

0.15.0-beta.5 (downloaded direct) and 0.14.15 (amazon App Store)

### Device information

Amazon Fire TV stick 4k 

### Android version

Fire OS 6.2.9.4

### Jellyfin server version

10.8.8

**Comment by kai-tub** [comment]
I think I have the same issue, though in my case, all video playbacks seem to crash (audio only works) and brings me back to the Fire TV menu.
I also have a Fire TV stick 4K Max (Note: Max)  with Fire OS 7.6.1.4 with jellyfin-androidtv 0.15.0 (not beta) sideloaded.
Interestingly, all files are played back correctly if I start them from the jellyfin android app, which I accidentally sideloaded before that. Can also confirm that all titles can be played back on other devices without any issues.

Here are my logs with developer options enabled:

<details>
<summary>Logs</summary>
---
client: Jellyfin for Android TV
client_version: 0.15.0
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
android.view.InflateException: Binary XML file line #39: Binary XML file line #39: Error inflating class com.google.android.exoplayer2.ui.PlayerView
Caused by: android.view.InflateException: Binary XML file line #39: Error inflating class com.google.android.exoplayer2.ui.PlayerView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at org.jellyfin.androidtv.databinding.VlcPlayerInterfaceBinding.inflate(VlcPlayerInterfaceBinding.java:107)
	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.onCreateView(CustomPlaybackOverlayFragment.java:203)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2985)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2895)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
	at android.app.Activity.performStart(Activity.java:7194)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2983)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:6769)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.view.InflateException: Binary XML file line #34: Binary XML file line #34: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #34: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at com.google.android.exoplayer2.ui.PlayerControlView.<init>(PlayerControlView.java:421)
	at com.google.android.exoplayer2.ui.PlayerView.<init>(PlayerView.java:502)
	at com.google.android.exoplayer2.ui.PlayerView.<init>(PlayerView.java:322)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at org.jellyfin.androidtv.databinding.VlcPlayerInterfaceBinding.inflate(VlcPlayerInterfaceBinding.java:107)
	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.onCreateView(CustomPlaybackOverlayFragment.java:203)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2985)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2895)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
	at android.app.Activity.performStart(Activity.java:7194)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2983)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:6769)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.content.res.Resources$NotFoundException: Drawable (missing name) with resource ID #0x7f0800a3
Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0800a3
	at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:255)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:785)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:631)
	at android.content.res.Resources.loadDrawable(Resources.java:897)
	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:955)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:930)
	at android.widget.ImageView.<init>(ImageView.java:189)
	at android.widget.ImageButton.<init>(ImageButton.java:86)
	at android.widget.ImageButton.<init>(ImageButton.java:82)
	at android.widget.ImageButton.<init>(ImageButton.java:78)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at com.google.android.exoplayer2.ui.PlayerControlView.<init>(PlayerControlView.java:421)
	at com.google.android.exoplayer2.ui.PlayerView.<init>(PlayerView.java:502)
	at com.google.android.exoplayer2.ui.PlayerView.<init>(PlayerView.java:322)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at org.jellyfin.androidtv.databinding.VlcPlayerInterfaceBinding.inflate(VlcPlayerInterfaceBinding.java:107)
	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.onCreateView(CustomPlaybackOverlayFragment.java:203)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2985)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2895)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
	at android.app.Activity.performStart(Activity.java:7194)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2983)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:6769)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```  
***Logcat***: 
```log
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
01-05 20:44:33.411 E/ACRA    (10037): 	at org.jellyfin.androidtv.databinding.VlcPlayerInterfaceBinding.inflate(VlcPlayerInterfaceBinding.java:107)
01-05 20:44:33.411 E/ACRA    (10037): 	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.onCreateView(CustomPlaybackOverlayFragment.java:203)
01-05 20:44:33.411 E/ACRA    (10037): 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
01-05 20:44:33.411 E/ACRA    (10037): 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
01-05 20:44:33.411 E/ACRA    (10037): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
01-05 20:44:33.411 E/ACRA    (10037): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
01-05 20:44:33.411 E/ACRA    (10037): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
01-05 20:44:33.411 E/ACRA    (10037): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
01-05 20:44:33.411 E/ACRA    (10037): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2985)
01-05 20:44:33.411 E/ACRA    (10037): 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2895)
01-05 20:44:33.411 E/ACRA    (10037): 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
01-05 20:44:33.411 E/ACRA    (10037): 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.app.Activity.performStart(Activity.java:7194)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2983)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.os.Looper.loop(Looper.java:211)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.app.ActivityThread.main(ActivityThread.java:6769)
01-05 20:44:33.411 E/ACRA    (10037): 	at java.lang.reflect.Method.invoke(Native Method)
01-05 20:44:33.411 E/ACRA    (10037): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-05 20:44:33.411 E/ACRA    (10037): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-05 20:44:33.411 E/ACRA    (10037): Caused by: android.content.res.Resources$NotFoundException: Drawable (missing name) with resource ID #0x7f0800a3
01-05 20:44:33.411 E/ACRA    (10037): Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0800a3
01-05 20:44:33.411 E/ACRA    (10037): 	at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:255)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:785)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:631)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.content.res.Resources.loadDrawable(Resources.java:897)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:955)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.content.res.TypedArray.getDrawable(TypedArray.java:930)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.widget.ImageView.<init>(ImageView.java:189)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.widget.ImageButton.<init>(ImageButton.java:86)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.widget.ImageButton.<init>(ImageButton.java:82)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.widget.ImageButton.<init>(ImageButton.java:78)
01-05 20:44:33.411 E/ACRA    (10037): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
01-05 20:44:33.411 E/ACRA    (10037): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
01-05 20:44:33.411 E/ACRA    (10037): 	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
01-05 20:44:33.411 E/ACRA    (10037): 	at com.google.android.exoplayer2.ui.PlayerControlView.<init>(PlayerControlView.java:421)
01-05 20:44:33.411 E/ACRA    (10037): 	at com.google.android.exoplayer2.ui.PlayerView.<init>(PlayerView.java:502)
01-05 20:44:33.411 E/ACRA    (10037): 	at com.google.android.exoplayer2.ui.PlayerView.<init>(PlayerView.java:322)
01-05 20:44:33.411 E/ACRA    (10037): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
01-05 20:44:33.411 E/ACRA    (10037): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
01-05 20:44:33.411 E/ACRA    (10037): 	at org.jellyfin.androidtv.databinding.VlcPlayerInterfaceBinding.inflate(VlcPlayerInterfaceBinding.java:107)
01-05 20:44:33.411 E/ACRA    (10037): 	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.onCreateView(CustomPlaybackOverlayFragment.java:203)
01-05 20:44:33.411 E/ACRA    (10037): 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
01-05 20:44:33.411 E/ACRA    (10037): 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
01-05 20:44:33.411 E/ACRA    (10037): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
01-05 20:44:33.411 E/ACRA    (10037): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
01-05 20:44:33.411 E/ACRA    (10037): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
01-05 20:44:33.411 E/ACRA    (10037): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
01-05 20:44:33.411 E/ACRA    (10037): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2985)
01-05 20:44:33.411 E/ACRA    (10037): 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2895)
01-05 20:44:33.411 E/ACRA    (10037): 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
01-05 20:44:33.411 E/ACRA    (10037): 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.app.Activity.performStart(Activity.java:7194)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2983)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.os.Looper.loop(Looper.java:211)
01-05 20:44:33.411 E/ACRA    (10037): 	at android.app.ActivityThread.main(ActivityThread.java:6769)
01-05 20:44:33.411 E/ACRA    (10037): 	at java.lang.reflect.Method.invoke(Native Method)
01-05 20:44:33.411 E/ACRA    (10037): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-05 20:44:33.411 E/ACRA    (10037): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```  

### App information

***App version***: `0.15.0` (`150099`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"kara","BOOTLOADER":"unknown","BRAND":"Amazon","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"kara","DISPLAY":"PS7614.3227N","FINGERPRINT":"Amazon\/kara\/kara:9\/PS7614.3227N\/0025938402048:user\/amz-p,release-keys","HARDWARE":"mt8696","HOST":"i3-ri-14-use1a-b-16-04-fos-183","ID":"PS7614.3227N","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Amazon","MODEL":"AFTKA","PERMISSIONS_REVIEW_REQUIRED":false,"PRODUCT":"kara","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"amz-p,release-keys","TIME":1668821539000,"TYPE":"user","UNKNOWN":"unknown","USER":"build","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"PPR1.180610.009","CODENAME":"REL","FIRST_SDK_INT":28,"INCREMENTAL":"0025938402180","PREVIEW_SDK_INT":0,"RELEASE":"9","RESOURCES_SDK_INT":28,"SDK":"28","SDK_INT":28,"SECURITY_PATCH":"2022-01-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":150099,"VERSION_NAME":"0.15.0"}
```  

### Device information

***Android version***: `9`  
***Device brand***: `Amazon`  
***Device product***: `kara`  
***Device model***: `AFTKA`  

### Crash information

***Start time***: `2023-01-05T20:39:08.844+01:00`  
***Crash time***: `2023-01-05T20:44:33.478+01:00`  
</details>

**Comment by felix-walter** [comment]
Can confirm this issue on a Firestick 4k as well as on a Philips OLED 706 (Android) with the Jellyfin app v0.15.3. Playback in ExoPlayer crashes as described above, using LibVLC or an external VLC player works but downmixes everything to stereo. Same behavior if the app is installed directly via apk. If the audio output setting in the app is configured to downmix everything to stereo, all files work in all tested configurations.

It seems this only occurs if using direct play. However, when selecting a maximum bit rate so low that it forces transcoding, often times no audio is played (though video works in this case).

There seems to be an easy solution to the crashes, at least in some cases: setting the FireTV stick audio output to "PCM". This will probably break with S/PDIF, but if an AV receiver is attached via HDMI, it works for most videos with DTS tracks in my case.

Unfortunately, there is again a downside to this: it breaks some other files for me - particularly those with a Dolby TrueHD audio track in case they have to be transcoded, which will now crash ExoPlayer. But this is probably another issue...

If I can support with debugging this (further logs, testing various files, etc.), I will be happy to help!
