### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by krutburken** [jellyfin/jellyfin-androidtv#2382]
### Describe the bug

Episode crashes the app, but video does play about three seconds first. Episode works fine in jellyfin-web client.

### Logs

---
client: Jellyfin for Android TV
client_version: 0.15.0
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.get(ArrayList.java:437)
	at org.jellyfin.androidtv.ui.playback.VideoManager.setExoPlayerTrack(VideoManager.java:549)
	at org.jellyfin.androidtv.ui.playback.PlaybackController.switchAudioStream(PlaybackController.java:955)
	at org.jellyfin.androidtv.ui.playback.PlaybackController.onPrepared(PlaybackController.java:1489)
	at org.jellyfin.androidtv.ui.playback.VideoManager$1.onIsPlayingChanged(VideoManager.java:134)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$24(ExoPlayerImpl.java:1955)
	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda8.invoke(Unknown Source:4)
	at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:282)
	at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:190)
	at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:211)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1966)
	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:1794)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$1$com-google-android-exoplayer2-ExoPlayerImpl(ExoPlayerImpl.java:312)
	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda24.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```  
***Logcat***: 
```log
01-02 21:02:04.028 D/VideoManager( 8052): Caught player timeline change - reason: SOURCE_UPDATE
01-02 21:02:04.032 D/ProfileInstaller( 8052): Skipping profile installation for org.jellyfin.androidtv
01-02 21:02:04.094 I/jellyfin-apiclient( 8052): Response received from: https://my.cool.site/Sessions/Playing
01-02 21:02:04.245 E/Surface ( 8052): freeAllBuffers: 1 buffers were freed while being dequeued!
01-02 21:02:04.250 D/ACRA    ( 8052): onActivityStopped class org.jellyfin.androidtv.ui.browsing.MainActivity
01-02 21:02:04.250 D/ACRA    ( 8052): onActivitySaveInstanceState class org.jellyfin.androidtv.ui.browsing.MainActivity
01-02 21:02:04.583 D/VideoManager( 8052): Caught player timeline change - reason: SOURCE_UPDATE
01-02 21:02:04.593 D/VideoManager( 8052): Tracks changed
01-02 21:02:04.595 I/android_os_HwBinder( 8052): HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
01-02 21:02:04.605 I/OMXClient( 8052): IOmx service obtained
01-02 21:02:04.610 I/android_os_HwBinder( 8052): HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
01-02 21:02:04.613 I/chatty  ( 8052): uid=10088(org.jellyfin.androidtv) ExoPlayer:Playb identical 1 line
01-02 21:02:04.616 I/android_os_HwBinder( 8052): HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
01-02 21:02:04.617 D/SurfaceUtils( 8052): connecting to surface 0xcbe9f7d8, reason connectToSurface
01-02 21:02:04.617 I/MediaCodec( 8052): [OMX.Nvidia.h264.decode] setting surface generation to 8245249
01-02 21:02:04.617 D/SurfaceUtils( 8052): disconnecting from surface 0xcbe9f7d8, reason connectToSurface(reconnect)
01-02 21:02:04.617 D/SurfaceUtils( 8052): connecting to surface 0xcbe9f7d8, reason connectToSurface(reconnect)
01-02 21:02:04.621 I/ACodec  ( 8052): Enable timestamp filtering for Video Decoder
01-02 21:02:04.622 I/ACodec  ( 8052): Get OMX_IndexConfigScale: 0x10000/0x10000
01-02 21:02:04.622 I/ACodec  ( 8052): Scaled Width is 1920, height is 1080
01-02 21:02:04.634 D/SurfaceUtils( 8052): set up nativeWindow 0xcbe9f7d8 for 1920x1080, color 0x106, rotation 0, usage 0x2900
01-02 21:02:04.639 I/android_os_HwBinder( 8052): HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
01-02 21:02:04.641 I/OMXClient( 8052): IOmx service obtained
01-02 21:02:04.648 I/android_os_HwBinder( 8052): HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
01-02 21:02:04.650 I/chatty  ( 8052): uid=10088(org.jellyfin.androidtv) ExoPlayer:Playb identical 1 line
01-02 21:02:04.651 I/android_os_HwBinder( 8052): HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
01-02 21:02:04.652 I/ACodec  ( 8052): codec does not support config priority (err -2147483648)
01-02 21:02:04.652 I/ACodec  ( 8052): codec does not support config operating rate (err -2147483648)
01-02 21:02:05.222 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession( 8052): Receiving (raw) message {"MessageType":"UserDataChanged","MessageId":"b5b0592d3538447a92303a369489c6ca","Data":{"UserId":"11e69615e9fa400ebe8e0e5b638b314c","UserDataList":[{"PlaybackPositionTicks":0,"PlayCount":2,"IsFavorite":false,"LastPlayedDate":"2023-01-02T20:02:04.8878712Z","Played":false,"Key":"182111010001","ItemId":"bee00af2569311c7e96784eb582789d9"},{"UnplayedItemCount":1,"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"651d8bf3-ca4c-dea0-123f-2cf6ca50c615","ItemId":"651d8bf3ca4cdea0123f2cf6ca50c615"}]}}
01-02 21:02:05.279 I/ACodec  ( 8052): Get OMX_IndexConfigScale: 0x10000/0x10000
01-02 21:02:05.279 I/ACodec  ( 8052): Scaled Width is 1920, height is 1080
01-02 21:02:05.280 D/SurfaceUtils( 8052): set up nativeWindow 0xcbe9f7d8 for 1920x1080, color 0x146, rotation 0, usage 0x2900
01-02 21:02:05.298 I/ACodec  ( 8052): Get OMX_IndexConfigScale: 0x10000/0x10000
01-02 21:02:05.298 I/ACodec  ( 8052): Scaled Width is 1920, height is 1080
01-02 21:02:05.381 D/jellyfin-apiclient( 8052): Adding request to queue: https://my.cool.site/Sessions/Playing/Progress
01-02 21:02:05.382 I/PlaybackController( 8052): Play method: Direct
01-02 21:02:05.382 I/PlaybackController( 8052): Turning off subs
01-02 21:02:05.382 D/PlaybackController( 8052): Setting subtitle index to: -1
01-02 21:02:05.383 D/PlaybackController( 8052): trying to switch audio stream from -1 to 2
01-02 21:02:05.383 D/AndroidRuntime( 8052): Shutting down VM
--------- beginning of crash
01-02 21:02:05.383 E/AndroidRuntime( 8052): FATAL EXCEPTION: main
01-02 21:02:05.383 E/AndroidRuntime( 8052): Process: org.jellyfin.androidtv, PID: 8052
01-02 21:02:05.383 E/AndroidRuntime( 8052): java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
01-02 21:02:05.383 E/AndroidRuntime( 8052): 	at java.util.ArrayList.get(ArrayList.java:437)
01-02 21:02:05.383 E/AndroidRuntime( 8052): 	at org.jellyfin.androidtv.ui.playback.VideoManager.setExoPlayerTrack(VideoManager.java:549)
01-02 21:02:05.383 E/AndroidRuntime( 8052): 	at org.jellyfin.androidtv.ui.playback.PlaybackController.switchAudioStream(PlaybackController.java:955)
01-02 21:02:05.383 E/AndroidRuntime( 8052): 	at org.jellyfin.androidtv.ui.playback.PlaybackController.onPrepared(PlaybackController.java:1489)
01-02 21:02:05.383 E/AndroidRuntime( 8052): 	at org.jellyfin.androidtv.ui.playback.VideoManager$1.onIsPlayingChanged(VideoManager.java:134)
01-02 21:02:05.383 E/AndroidRuntime( 8052): 	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$24(ExoPlayerImpl.java:1955)
01-02 21:02:05.383 E/AndroidRuntime( 8052): 	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda8.invoke(Unknown Source:4)
01-02 21:02:05.383 E/AndroidRuntime( 8052): 	at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:282)
01-02 21:02:05.383 E/AndroidRuntime( 8052): 	at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:190)
01-02 21:02:05.383 E/AndroidRuntime( 8052): 	at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.run(Unknown Source:6)
01-02 21:02:05.383 E/AndroidRuntime( 8052): 	at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:211)
01-02 21:02:05.383 E/AndroidRuntime( 8052): 	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1966)
01-02 21:02:05.383 E/AndroidRuntime( 8052): 	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:1794)
01-02 21:02:05.383 E/AndroidRuntime( 8052): 	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$1$com-google-android-exoplayer2-ExoPlayerImpl(ExoPlayerImpl.java:312)
01-02 21:02:05.383 E/AndroidRuntime( 8052): 	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda24.run(Unknown Source:4)
01-02 21:02:05.383 E/AndroidRuntime( 8052): 	at android.os.Handler.handleCallback(Handler.java:938)
01-02 21:02:05.383 E/AndroidRuntime( 8052): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-02 21:02:05.383 E/AndroidRuntime( 8052): 	at android.os.Looper.loop(Looper.java:223)
01-02 21:02:05.383 E/AndroidRuntime( 8052): 	at android.app.ActivityThread.main(ActivityThread.java:7668)
01-02 21:02:05.383 E/AndroidRuntime( 8052): 	at java.lang.reflect.Method.invoke(Native Method)
01-02 21:02:05.383 E/AndroidRuntime( 8052): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
01-02 21:02:05.383 E/AndroidRuntime( 8052): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
01-02 21:02:05.384 E/ACRA    ( 8052): ACRA caught a IndexOutOfBoundsException for org.jellyfin.androidtv
01-02 21:02:05.384 E/ACRA    ( 8052): java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
01-02 21:02:05.384 E/ACRA    ( 8052): 	at java.util.ArrayList.get(ArrayList.java:437)
01-02 21:02:05.384 E/ACRA    ( 8052): 	at org.jellyfin.androidtv.ui.playback.VideoManager.setExoPlayerTrack(VideoManager.java:549)
01-02 21:02:05.384 E/ACRA    ( 8052): 	at org.jellyfin.androidtv.ui.playback.PlaybackController.switchAudioStream(PlaybackController.java:955)
01-02 21:02:05.384 E/ACRA    ( 8052): 	at org.jellyfin.androidtv.ui.playback.PlaybackController.onPrepared(PlaybackController.java:1489)
01-02 21:02:05.384 E/ACRA    ( 8052): 	at org.jellyfin.androidtv.ui.playback.VideoManager$1.onIsPlayingChanged(VideoManager.java:134)
01-02 21:02:05.384 E/ACRA    ( 8052): 	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$24(ExoPlayerImpl.java:1955)
01-02 21:02:05.384 E/ACRA    ( 8052): 	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda8.invoke(Unknown Source:4)
01-02 21:02:05.384 E/ACRA    ( 8052): 	at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:282)
01-02 21:02:05.384 E/ACRA    ( 8052): 	at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:190)
01-02 21:02:05.384 E/ACRA    ( 8052): 	at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.run(Unknown Source:6)
01-02 21:02:05.384 E/ACRA    ( 8052): 	at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:211)
01-02 21:02:05.384 E/ACRA    ( 8052): 	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1966)
01-02 21:02:05.384 E/ACRA    ( 8052): 	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:1794)
01-02 21:02:05.384 E/ACRA    ( 8052): 	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$1$com-google-android-exoplayer2-ExoPlayerImpl(ExoPlayerImpl.java:312)
01-02 21:02:05.384 E/ACRA    ( 8052): 	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda24.run(Unknown Source:4)
01-02 21:02:05.384 E/ACRA    ( 8052): 	at android.os.Handler.handleCallback(Handler.java:938)
01-02 21:02:05.384 E/ACRA    ( 8052): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-02 21:02:05.384 E/ACRA    ( 8052): 	at android.os.Looper.loop(Looper.java:223)
01-02 21:02:05.384 E/ACRA    ( 8052): 	at android.app.ActivityThread.main(ActivityThread.java:7668)
01-02 21:02:05.384 E/ACRA    ( 8052): 	at java.lang.reflect.Method.invoke(Native Method)
01-02 21:02:05.384 E/ACRA    ( 8052): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
01-02 21:02:05.384 E/ACRA    ( 8052): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
01-02 21:02:05.384 D/ACRA    ( 8052): Building report
01-02 21:02:05.384 D/ACRA    ( 8052): Starting collectors with priority FIRST
01-02 21:02:05.386 D/AudioTrack( 8052): getTimestamp_l(967): device stall time corrected using current time 626590145989252
01-02 21:02:05.387 D/ACRA    ( 8052): Calling collector org.acra.collector.DropBoxCollector
01-02 21:02:05.387 D/ACRA    ( 8052): Collector org.acra.collector.DropBoxCollector completed
01-02 21:02:05.387 D/ACRA    ( 8052): Calling collector org.acra.collector.LogCatCollector
01-02 21:02:05.388 D/ACRA    ( 8052): Calling collector org.acra.collector.StacktraceCollector
01-02 21:02:05.389 D/ACRA    ( 8052): Collector org.acra.collector.StacktraceCollector completed
01-02 21:02:05.395 D/ACRA    ( 8052): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.15.0` (`150099`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"sif","BOOTLOADER":"32.00.2019.50-t210-69ebfcbe","BRAND":"NVIDIA","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"sif","DISPLAY":"RQ1A.210105.003.7825199_3167.5736","FINGERPRINT":"NVIDIA\/sif\/sif:11\/RQ1A.210105.003\/7825199_3167.5736:user\/release-keys","HARDWARE":"sif","HOST":"mobile-u64-5306-d6000","ID":"RQ1A.210105.003","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"NVIDIA","MODEL":"SHIELD Android TV","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"sif","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1665975946000,"TYPE":"user","UNKNOWN":"unknown","USER":"NVIDIA","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"7825199_3167.5736","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"11","RELEASE_OR_CODENAME":"11","SDK":"30","SDK_INT":30,"SECURITY_PATCH":"2022-04-05"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":150099,"VERSION_NAME":"0.15.0"}
```  

### Device information

***Android version***: `11`  
***Device brand***: `NVIDIA`  
***Device product***: `sif`  
***Device model***: `SHIELD Android TV`  

### Crash information

***Start time***: `2023-01-02T21:01:58.828+01:00`  
***Crash time***: `2023-01-02T21:02:05.571+01:00`  

### FFmpeg logs

```shell
No ffmpeg logs produced
```

### Media info of the file

```shell
ffprobe version N-63101-gc92edd969a-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      57. 36.101 / 57. 36.101
  libavcodec     59. 42.104 / 59. 42.104
  libavformat    59. 30.101 / 59. 30.101
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 48.100 /  8. 48.100
  libswscale      6.  8.108 /  6.  8.108
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
[h264 @ 0x6494240] number of reference frames (0+5) exceeds max (4; probably corrupt input), discarding one
[h264 @ 0x6494240] Increasing reorder buffer to 3
Input #0, matroska,webm, from '/the-path/digging.for.britain.s10e01.mkv':
  Metadata:
    ENCODER         : Lavf59.27.100
  Duration: 00:59:29.05, start: 0.000000, bitrate: 4486 kb/s
  Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1k tbn (default)
    Metadata:
      DURATION        : 00:59:28.781000000
  Stream #0:1(eng): Subtitle: dvb_subtitle
    Metadata:
      DURATION        : 00:59:29.046000000
  Stream #0:2(eng): Audio: aac (LC), 48000 Hz, stereo, fltp (default)
    Metadata:
      ENCODER         : Lavc59.37.100 aac
      DURATION        : 00:59:28.789000000
```

### Application version

0.15.0

### Device information

Shield TV

### Android version

11

### Jellyfin server version

10.8.8

**Comment by nielsvanvelzen** [comment]
I'm not sure why this happens after the video played for a few seconds, I'd expect it to crash immediately. I've made a fix that should at least avoid the crash which will be in the next update (0.15.1).
