### ISSUE TITLE
Crash with NullPointerException direct playing video

### ISSUE THREAD

**Issue by moeffju** [jellyfin/jellyfin-androidtv#2421]
### Describe the bug

A number of web videos that I downloaded using yt-dlp crashes the Jellyfin Android TV app on playback. The first second or so of audio will continue playing while the "Jellyfin has crashed" toast appears and Jellyfin shuts down.

### Logs

---
client: Jellyfin for Android TV
client_version: 0.15.2
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.NullPointerException: Attempt to get length of null array
	at org.jellyfin.androidtv.ui.playback.VideoManager.setVLCAudioTrack(VideoManager.java:654)
	at org.jellyfin.androidtv.ui.playback.PlaybackController.switchAudioStream(PlaybackController.java:958)
	at org.jellyfin.androidtv.ui.playback.PlaybackController.onPrepared(PlaybackController.java:1489)
	at org.jellyfin.androidtv.ui.playback.VideoManager.lambda$setupVLCListeners$2$org-jellyfin-androidtv-ui-playback-VideoManager(VideoManager.java:970)
	at org.jellyfin.androidtv.ui.playback.VideoManager$$ExternalSyntheticLambda2.onEvent(Unknown Source:2)
	at org.jellyfin.androidtv.ui.playback.VlcEventHandler.onEvent(VlcEventHandler.kt:14)
	at org.jellyfin.androidtv.ui.playback.VlcEventHandler.onEvent(VlcEventHandler.kt:5)
	at org.videolan.libvlc.VLCObject$1EventRunnable.run(VLCObject.java:170)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```  
***Logcat***: 
```log
01-15 10:10:59.181 W/MediaCodecCapabilitiesTest(24391): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
01-15 10:10:59.181 W/MediaCodecCapabilitiesTest(24391): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
01-15 10:10:59.181 W/MediaCodecCapabilitiesTest(24391): 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-15 10:10:59.181 W/MediaCodecCapabilitiesTest(24391): 	at android.os.Looper.loopOnce(Looper.java:201)
01-15 10:10:59.181 W/MediaCodecCapabilitiesTest(24391): 	at android.os.Looper.loop(Looper.java:288)
01-15 10:10:59.181 W/MediaCodecCapabilitiesTest(24391): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
01-15 10:10:59.181 W/MediaCodecCapabilitiesTest(24391): 	at java.lang.reflect.Method.invoke(Native Method)
01-15 10:10:59.181 W/MediaCodecCapabilitiesTest(24391): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-15 10:10:59.181 W/MediaCodecCapabilitiesTest(24391): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
01-15 10:10:59.188 I/PlaybackController(24391): *** Using extended Exoplayer profile options
01-15 10:10:59.194 D/jellyfin-apiclient(24391): Adding request to queue: https://jellyfin-host/Items/778a0655-214d-e0f9-0d90-bbc1b01aecd0/PlaybackInfo?format=json
01-15 10:10:59.197 D/ACRA    (24391): onActivityResumed class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
01-15 10:10:59.197 W/AudioManager(24391): Use of stream types is deprecated for operations other than volume control
01-15 10:10:59.197 W/AudioManager(24391): See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
01-15 10:10:59.339 I/jellyfin-apiclient(24391): Response received from: https://jellyfin-host/Items/778a0655-214d-e0f9-0d90-bbc1b01aecd0/PlaybackInfo?format=json
01-15 10:10:59.343 I/PlaybackController(24391): VLC would direct stream
01-15 10:10:59.345 D/jellyfin-apiclient(24391): Adding request to queue: https://jellyfin-host/Items/778a0655-214d-e0f9-0d90-bbc1b01aecd0/PlaybackInfo?format=json
01-15 10:10:59.461 I/jellyfin-apiclient(24391): Response received from: https://jellyfin-host/Items/778a0655-214d-e0f9-0d90-bbc1b01aecd0/PlaybackInfo?format=json
01-15 10:10:59.462 I/PlaybackController(24391): Internal player would transcode
01-15 10:10:59.463 I/PlaybackController(24391): Explicit deinterlacing will NOT be used
01-15 10:10:59.464 I/PlaybackController(24391): User preferred player is: VLC
01-15 10:10:59.465 I/PlaybackController(24391): Preferring VLC
01-15 10:10:59.611 I/VideoManager(24391): Network buffer set to 600
01-15 10:10:59.628 D/VideoManager(24391): Surface attached
01-15 10:10:59.629 D/PlaybackController(24391): default audio index set to 1
01-15 10:10:59.629 D/PlaybackController(24391): default audio index set to 1 remote default 1
01-15 10:10:59.629 D/PlaybackController(24391): default sub index set to -1 remote default null
01-15 10:10:59.630 I/PlaybackController(24391): Playing back in VLC.
01-15 10:10:59.631 D/VideoManager(24391): Setting playback speed: 1.000000
01-15 10:10:59.638 I/ViewTarget(24391): Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
01-15 10:10:59.646 W/libOpenSLES(24391): class OutputMix interface 0 requested but unavailable MPH=43
01-15 10:10:59.648 I/PlaybackController(24391): Setting compatible audio mode...
01-15 10:10:59.649 I/VideoManager(24391): Video path set to: https://jellyfin-host/Videos/778a0655-214d-e0f9-0d90-bbc1b01aecd0/stream.mpegts?api_key=XXX&DeviceId=XXX&MediaSourceId=778a0655214de0f90d90bbc1b01aecd0&Tag=XXX&Static=true
01-15 10:10:59.655 D/VideoManager(24391): Setting video index to: 0
01-15 10:10:59.659 D/jellyfin-apiclient(24391): Adding request to queue: https://jellyfin-host/Sessions/Playing
01-15 10:10:59.661 I/ReportingHelper(24391): Playback of (Video Title) started.
01-15 10:10:59.714 D/ACRA    (24391): onActivityStopped class org.jellyfin.androidtv.ui.browsing.MainActivity
01-15 10:10:59.717 D/ACRA    (24391): onActivitySaveInstanceState class org.jellyfin.androidtv.ui.browsing.MainActivity
01-15 10:11:00.017 I/jellyfin-apiclient(24391): Response received from: https://jellyfin-host/Sessions/Playing
01-15 10:11:00.505 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(24391): Receiving (raw) message {"MessageType":"UserDataChanged","MessageId":"b357fe6f293d4003a7a126952845bb92","Data":{"UserId":"XXX","UserDataList":[{"PlaybackPositionTicks":0,"PlayCount":1,"IsFavorite":false,"LastPlayedDate":"2023-01-15T09:10:23.5595664Z","Played":false,"Key":"356085007012","ItemId":"778a0655214de0f90d90bbc1b01aecd0"},{"UnplayedItemCount":1,"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"356085007","ItemId":"994ae48bc71283ead7fc99f10dd3acfb"}]}}
01-15 10:11:00.951 W/VLC     (24391): [ef0b5d90/5fb9] libvlc demux: discontinuity indicator (pid=17) 
01-15 10:11:00.951 W/VLC     (24391): [ef0b5d90/5fb9] libvlc demux: discontinuity indicator (pid=0) 
01-15 10:11:00.951 W/VLC     (24391): [ef0b5d90/5fb9] libvlc demux: discontinuity indicator (pid=4096) 
01-15 10:11:00.955 D/VideoManager(24391): re-retrieved libVLC audio track index -1
01-15 10:11:00.958 D/jellyfin-apiclient(24391): Adding request to queue: https://jellyfin-host/Sessions/Playing/Progress
01-15 10:11:00.960 I/PlaybackController(24391): Play method: Direct
01-15 10:11:00.961 I/PlaybackController(24391): Turning off subs
01-15 10:11:00.962 D/PlaybackController(24391): Setting subtitle index to: -1
01-15 10:11:00.965 D/VideoManager(24391): re-retrieved libVLC audio track index -1
01-15 10:11:00.966 D/PlaybackController(24391): trying to switch audio stream from -1 to 1
01-15 10:11:00.967 D/VideoManager(24391): Setting VLC audio track index to: 1
01-15 10:11:00.970 D/AndroidRuntime(24391): Shutting down VM
--------- beginning of crash
01-15 10:11:00.971 E/AndroidRuntime(24391): FATAL EXCEPTION: main
01-15 10:11:00.971 E/AndroidRuntime(24391): Process: org.jellyfin.androidtv, PID: 24391
01-15 10:11:00.971 E/AndroidRuntime(24391): java.lang.NullPointerException: Attempt to get length of null array
01-15 10:11:00.971 E/AndroidRuntime(24391): 	at org.jellyfin.androidtv.ui.playback.VideoManager.setVLCAudioTrack(VideoManager.java:654)
01-15 10:11:00.971 E/AndroidRuntime(24391): 	at org.jellyfin.androidtv.ui.playback.PlaybackController.switchAudioStream(PlaybackController.java:958)
01-15 10:11:00.971 E/AndroidRuntime(24391): 	at org.jellyfin.androidtv.ui.playback.PlaybackController.onPrepared(PlaybackController.java:1489)
01-15 10:11:00.971 E/AndroidRuntime(24391): 	at org.jellyfin.androidtv.ui.playback.VideoManager.lambda$setupVLCListeners$2$org-jellyfin-androidtv-ui-playback-VideoManager(VideoManager.java:970)
01-15 10:11:00.971 E/AndroidRuntime(24391): 	at org.jellyfin.androidtv.ui.playback.VideoManager$$ExternalSyntheticLambda2.onEvent(Unknown Source:2)
01-15 10:11:00.971 E/AndroidRuntime(24391): 	at org.jellyfin.androidtv.ui.playback.VlcEventHandler.onEvent(VlcEventHandler.kt:14)
01-15 10:11:00.971 E/AndroidRuntime(24391): 	at org.jellyfin.androidtv.ui.playback.VlcEventHandler.onEvent(VlcEventHandler.kt:5)
01-15 10:11:00.971 E/AndroidRuntime(24391): 	at org.videolan.libvlc.VLCObject$1EventRunnable.run(VLCObject.java:170)
01-15 10:11:00.971 E/AndroidRuntime(24391): 	at android.os.Handler.handleCallback(Handler.java:938)
01-15 10:11:00.971 E/AndroidRuntime(24391): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-15 10:11:00.971 E/AndroidRuntime(24391): 	at android.os.Looper.loopOnce(Looper.java:201)
01-15 10:11:00.971 E/AndroidRuntime(24391): 	at android.os.Looper.loop(Looper.java:288)
01-15 10:11:00.971 E/AndroidRuntime(24391): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
01-15 10:11:00.971 E/AndroidRuntime(24391): 	at java.lang.reflect.Method.invoke(Native Method)
01-15 10:11:00.971 E/AndroidRuntime(24391): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-15 10:11:00.971 E/AndroidRuntime(24391): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
01-15 10:11:00.973 E/ACRA    (24391): ACRA caught a NullPointerException for org.jellyfin.androidtv
01-15 10:11:00.973 E/ACRA    (24391): java.lang.NullPointerException: Attempt to get length of null array
01-15 10:11:00.973 E/ACRA    (24391): 	at org.jellyfin.androidtv.ui.playback.VideoManager.setVLCAudioTrack(VideoManager.java:654)
01-15 10:11:00.973 E/ACRA    (24391): 	at org.jellyfin.androidtv.ui.playback.PlaybackController.switchAudioStream(PlaybackController.java:958)
01-15 10:11:00.973 E/ACRA    (24391): 	at org.jellyfin.androidtv.ui.playback.PlaybackController.onPrepared(PlaybackController.java:1489)
01-15 10:11:00.973 E/ACRA    (24391): 	at org.jellyfin.androidtv.ui.playback.VideoManager.lambda$setupVLCListeners$2$org-jellyfin-androidtv-ui-playback-VideoManager(VideoManager.java:970)
01-15 10:11:00.973 E/ACRA    (24391): 	at org.jellyfin.androidtv.ui.playback.VideoManager$$ExternalSyntheticLambda2.onEvent(Unknown Source:2)
01-15 10:11:00.973 E/ACRA    (24391): 	at org.jellyfin.androidtv.ui.playback.VlcEventHandler.onEvent(VlcEventHandler.kt:14)
01-15 10:11:00.973 E/ACRA    (24391): 	at org.jellyfin.androidtv.ui.playback.VlcEventHandler.onEvent(VlcEventHandler.kt:5)
01-15 10:11:00.973 E/ACRA    (24391): 	at org.videolan.libvlc.VLCObject$1EventRunnable.run(VLCObject.java:170)
01-15 10:11:00.973 E/ACRA    (24391): 	at android.os.Handler.handleCallback(Handler.java:938)
01-15 10:11:00.973 E/ACRA    (24391): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-15 10:11:00.973 E/ACRA    (24391): 	at android.os.Looper.loopOnce(Looper.java:201)
01-15 10:11:00.973 E/ACRA    (24391): 	at android.os.Looper.loop(Looper.java:288)
01-15 10:11:00.973 E/ACRA    (24391): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
01-15 10:11:00.973 E/ACRA    (24391): 	at java.lang.reflect.Method.invoke(Native Method)
01-15 10:11:00.973 E/ACRA    (24391): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-15 10:11:00.973 E/ACRA    (24391): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
01-15 10:11:00.973 D/ACRA    (24391): Building report
01-15 10:11:00.974 D/ACRA    (24391): Starting collectors with priority FIRST
01-15 10:11:00.976 D/ACRA    (24391): Calling collector org.acra.collector.DropBoxCollector
01-15 10:11:00.977 D/ACRA    (24391): Collector org.acra.collector.DropBoxCollector completed
01-15 10:11:00.977 D/ACRA    (24391): Calling collector org.acra.collector.LogCatCollector
01-15 10:11:00.977 D/ACRA    (24391): Calling collector org.acra.collector.StacktraceCollector
01-15 10:11:00.978 D/ACRA    (24391): Collector org.acra.collector.StacktraceCollector completed
01-15 10:11:00.984 D/ACRA    (24391): Retrieving logcat output (buffer:default)...
01-15 10:11:01.001 W/VLC     (24391): [ef0b5d90/5fb9] libvlc demux: discontinuity indicator (pid=256) 

```  

### App information

***App version***: `0.15.2` (`150299`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"sabrina","BOOTLOADER":"01.01.221014.042927","BRAND":"google","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"sabrina","DISPLAY":"STTE.220920.015.A1.9261725","FINGERPRINT":"google\/sabrina_prod_stable\/sabrina:12\/STTE.220920.015.A1\/9261725:user\/release-keys","HARDWARE":"amlogic","HOST":"abfarm-release-2004-0103","ID":"STTE.220920.015.A1","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Google","MODEL":"Chromecast","ODM_SKU":"DE","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"sabrina_prod_stable","RADIO":"unknown","SKU":"DE","SOC_MANUFACTURER":"Amlogic","SOC_MODEL":"AMLS905D3","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1667789403000,"TYPE":"user","UNKNOWN":"unknown","USER":"android-build","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"9261725","MEDIA_PERFORMANCE_CLASS":0,"PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"12","RELEASE_OR_CODENAME":"12","SDK":"31","SDK_INT":31,"SECURITY_PATCH":"2022-10-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":150299,"VERSION_NAME":"0.15.2"}
```  

### Device information

***Android version***: `12`  
***Device brand***: `google`  
***Device product***: `sabrina_prod_stable`  
***Device model***: `Chromecast`  

### Crash information

***Start time***: `2023-01-15T10:10:14.363+01:00`  
***Crash time***: `2023-01-15T10:11:01.170+01:00`  

### FFmpeg logs

```shell
n/a - direct play
```

### Media info of the file

```shell
Input #0, mpegts, from '....mp4':
  Duration: 00:30:00.72, start: 0.700000, bitrate: 4611 kb/s
  Program 1
    Metadata:
      service_name    : HLS
      service_provider: Vimeo
    Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1920x1080, 23.98 fps, 23.98 tbr, 90k tbn, 48k tbc
    Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 255 kb/s
```

### Application version

0.15.2

### Device information

Google Chromecast with Google TV

### Android version

Android 12

### Jellyfin server version

10.8.8

**Comment by moeffju** [comment]
To add, I tried with both the "Automatic" setting and explicitly choosing LibVLC for playback, no difference.
The same video plays fine using the Jellyfin Android (non-TV) app chromecasting to the same device.

**Comment by nielsvanvelzen** [comment]
Did you try ExoPlayer (the default option)?

**Comment by moeffju** [comment]
If the default setting is = automatic then yes, but I can try it explicitly, will feed back.

**Comment by moeffju** [comment]
It appears it simply works in Exoplayer. I don't recall changing the default from "Automatically select", but I'll keep it set to ExoPlayer for now.
