### ISSUE TITLE
Crash after Authenticating

### ISSUE THREAD

**Issue by candry7731** [jellyfin/jellyfin-androidtv#2444]
### Describe the bug

Enter Server Address
Enter username and password
Wait for app to load
Immediate crash

### Logs

---
client: Jellyfin for Android TV
client_version: 0.15.2
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
org.jellyfin.sdk.api.client.exception.TimeoutException: Socket timed out
	at org.jellyfin.sdk.api.client.KtorClient.request$suspendImpl(KtorClient.kt:118)
	at org.jellyfin.sdk.api.client.KtorClient$request$1.invokeSuspend(Unknown Source:19)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:194)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:89)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:194)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:89)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:194)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:89)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:194)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:89)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at org.jellyfin.androidtv.util.CoroutineUtils.runBlocking(CoroutineUtils.kt:13)
	at org.jellyfin.androidtv.ui.home.HomeFragmentLatestRow.addToRowsAdapter(HomeFragmentLatestRow.kt:29)
	at org.jellyfin.androidtv.ui.home.HomeRowsFragment$onCreate$1$1.invokeSuspend(HomeRowsFragment.kt:135)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:6769)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f2bfd1a, Dispatchers.IO]
Caused by: io.ktor.network.sockets.SocketTimeoutException: Socket timeout has expired [url=http://localhost:8097/Users/87300746-500a-4eaa-ac11-74c6b16de830/Views?includeHidden=false, socket_timeout=10000] ms
	at io.ktor.client.features.HttpTimeoutKt.SocketTimeoutException(HttpTimeout.kt:207)
	at io.ktor.client.engine.okhttp.OkUtilsKt.mapOkHttpException(OkUtils.kt:79)
	at io.ktor.client.engine.okhttp.OkUtilsKt.access$mapOkHttpException(OkUtils.kt:1)
	at io.ktor.client.engine.okhttp.OkHttpCallback.onFailure(OkUtils.kt:39)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.net.SocketTimeoutException: timeout
	at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:143)
	at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:162)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:335)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	... 3 more
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:144)
	at okio.InputStreamSource.read(JvmOkio.kt:90)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
	... 20 more

```  
***Logcat***: 
```log
01-24 08:09:20.618 W/LeanbackChannelWorker(13430): 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
01-24 08:09:20.618 W/LeanbackChannelWorker(13430): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-24 08:09:20.618 W/LeanbackChannelWorker(13430): 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
01-24 08:09:20.618 W/LeanbackChannelWorker(13430): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-24 08:09:20.618 W/LeanbackChannelWorker(13430): 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
01-24 08:09:20.618 W/LeanbackChannelWorker(13430): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-24 08:09:20.618 W/LeanbackChannelWorker(13430): 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
01-24 08:09:20.619 W/LeanbackChannelWorker(13430): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-24 08:09:20.619 W/LeanbackChannelWorker(13430): 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
01-24 08:09:20.619 W/LeanbackChannelWorker(13430): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-24 08:09:20.619 W/LeanbackChannelWorker(13430): 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
01-24 08:09:20.619 W/LeanbackChannelWorker(13430): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
01-24 08:09:20.619 W/LeanbackChannelWorker(13430): 	... 3 more
01-24 08:09:20.619 W/LeanbackChannelWorker(13430): Caused by: java.net.SocketException: Socket closed
01-24 08:09:20.619 W/LeanbackChannelWorker(13430): 	at java.net.SocketInputStream.read(SocketInputStream.java:209)
01-24 08:09:20.619 W/LeanbackChannelWorker(13430): 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
01-24 08:09:20.619 W/LeanbackChannelWorker(13430): 	at okio.InputStreamSource.read(JvmOkio.kt:90)
01-24 08:09:20.619 W/LeanbackChannelWorker(13430): 	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
01-24 08:09:20.619 W/LeanbackChannelWorker(13430): 	... 20 more
01-24 08:09:20.625 I/WM-WorkerWrapper(13430): Worker result RETRY for Work [ id=76b0c296-41fd-46f8-88da-c559343cc774, tags={ org.jellyfin.androidtv.integration.LeanbackChannelWorker } ]
01-24 08:09:25.758 I/Choreographer(13430): Skipped 601 frames!  The application may be doing too much work on its main thread.
01-24 08:09:25.766 E/ACRA    (13430): ACRA caught a TimeoutException for org.jellyfin.androidtv
01-24 08:09:25.766 E/ACRA    (13430): org.jellyfin.sdk.api.client.exception.TimeoutException: Socket timed out
01-24 08:09:25.766 E/ACRA    (13430): 	at org.jellyfin.sdk.api.client.KtorClient.request$suspendImpl(KtorClient.kt:118)
01-24 08:09:25.766 E/ACRA    (13430): 	at org.jellyfin.sdk.api.client.KtorClient$request$1.invokeSuspend(Unknown Source:19)
01-24 08:09:25.766 E/ACRA    (13430): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-24 08:09:25.766 E/ACRA    (13430): 	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:194)
01-24 08:09:25.766 E/ACRA    (13430): 	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:15)
01-24 08:09:25.766 E/ACRA    (13430): 	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:89)
01-24 08:09:25.766 E/ACRA    (13430): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
01-24 08:09:25.766 E/ACRA    (13430): 	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:194)
01-24 08:09:25.766 E/ACRA    (13430): 	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:15)
01-24 08:09:25.766 E/ACRA    (13430): 	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:89)
01-24 08:09:25.766 E/ACRA    (13430): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
01-24 08:09:25.766 E/ACRA    (13430): 	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:194)
01-24 08:09:25.766 E/ACRA    (13430): 	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:15)
01-24 08:09:25.766 E/ACRA    (13430): 	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:89)
01-24 08:09:25.766 E/ACRA    (13430): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
01-24 08:09:25.766 E/ACRA    (13430): 	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:194)
01-24 08:09:25.766 E/ACRA    (13430): 	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:15)
01-24 08:09:25.766 E/ACRA    (13430): 	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:89)
01-24 08:09:25.766 E/ACRA    (13430): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
01-24 08:09:25.766 E/ACRA    (13430): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
01-24 08:09:25.766 E/ACRA    (13430): 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
01-24 08:09:25.766 E/ACRA    (13430): 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
01-24 08:09:25.766 E/ACRA    (13430): 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
01-24 08:09:25.766 E/ACRA    (13430): 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
01-24 08:09:25.766 E/ACRA    (13430): 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
01-24 08:09:25.766 E/ACRA    (13430): 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
01-24 08:09:25.766 E/ACRA    (13430): 	at org.jellyfin.androidtv.util.CoroutineUtils.runBlocking(CoroutineUtils.kt:13)
01-24 08:09:25.766 E/ACRA    (13430): 	at org.jellyfin.androidtv.ui.home.HomeFragmentLatestRow.addToRowsAdapter(HomeFragmentLatestRow.kt:29)
01-24 08:09:25.766 E/ACRA    (13430): 	at org.jellyfin.androidtv.ui.home.HomeRowsFragment$onCreate$1$1.invokeSuspend(HomeRowsFragment.kt:135)
01-24 08:09:25.766 E/ACRA    (13430): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-24 08:09:25.766 E/ACRA    (13430): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
01-24 08:09:25.766 E/ACRA    (13430): 	at android.os.Handler.handleCallback(Handler.java:873)
01-24 08:09:25.766 E/ACRA    (13430): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-24 08:09:25.766 E/ACRA    (13430): 	at android.os.Looper.loop(Looper.java:211)
01-24 08:09:25.766 E/ACRA    (13430): 	at android.app.ActivityThread.main(ActivityThread.java:6769)
01-24 08:09:25.766 E/ACRA    (13430): 	at java.lang.reflect.Method.invoke(Native Method)
01-24 08:09:25.766 E/ACRA    (13430): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-24 08:09:25.766 E/ACRA    (13430): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-24 08:09:25.766 E/ACRA    (13430): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f2bfd1a, Dispatchers.IO]
01-24 08:09:25.766 E/ACRA    (13430): Caused by: io.ktor.network.sockets.SocketTimeoutException: Socket timeout has expired [url=http://localhost:8097/Users/87300746-500a-4eaa-ac11-74c6b16de830/Views?includeHidden=false, socket_timeout=10000] ms
01-24 08:09:25.766 E/ACRA    (13430): 	at io.ktor.client.features.HttpTimeoutKt.SocketTimeoutException(HttpTimeout.kt:207)
01-24 08:09:25.766 E/ACRA    (13430): 	at io.ktor.client.engine.okhttp.OkUtilsKt.mapOkHttpException(OkUtils.kt:79)
01-24 08:09:25.766 E/ACRA    (13430): 	at io.ktor.client.engine.okhttp.OkUtilsKt.access$mapOkHttpException(OkUtils.kt:1)
01-24 08:09:25.766 E/ACRA    (13430): 	at io.ktor.client.engine.okhttp.OkHttpCallback.onFailure(OkUtils.kt:39)
01-24 08:09:25.766 E/ACRA    (13430): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
01-24 08:09:25.767 E/ACRA    (13430): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-24 08:09:25.767 E/ACRA    (13430): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-24 08:09:25.767 E/ACRA    (13430): 	at java.lang.Thread.run(Thread.java:764)
01-24 08:09:25.767 E/ACRA    (13430): Caused by: java.net.SocketTimeoutException: timeout
01-24 08:09:25.767 E/ACRA    (13430): 	at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:143)
01-24 08:09:25.767 E/ACRA    (13430): 	at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:162)
01-24 08:09:25.767 E/ACRA    (13430): 	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:335)
01-24 08:09:25.767 E/ACRA    (13430): 	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
01-24 08:09:25.767 E/ACRA    (13430): 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
01-24 08:09:25.767 E/ACRA    (13430): 	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
01-24 08:09:25.767 E/ACRA    (13430): 	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
01-24 08:09:25.767 E/ACRA    (13430): 	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
01-24 08:09:25.767 E/ACRA    (13430): 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
01-24 08:09:25.767 E/ACRA    (13430): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-24 08:09:25.767 E/ACRA    (13430): 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
01-24 08:09:25.767 E/ACRA    (13430): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-24 08:09:25.767 E/ACRA    (13430): 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
01-24 08:09:25.767 E/ACRA    (13430): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-24 08:09:25.767 E/ACRA    (13430): 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
01-24 08:09:25.767 E/ACRA    (13430): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-24 08:09:25.767 E/ACRA    (13430): 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
01-24 08:09:25.767 E/ACRA    (13430): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-24 08:09:25.767 E/ACRA    (13430): 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
01-24 08:09:25.767 E/ACRA    (13430): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
01-24 08:09:25.767 E/ACRA    (13430): 	... 3 more
01-24 08:09:25.767 E/ACRA    (13430): Caused by: java.net.SocketException: Socket closed
01-24 08:09:25.767 E/ACRA    (13430): 	at java.net.SocketInputStream.read(SocketInputStream.java:209)
01-24 08:09:25.767 E/ACRA    (13430): 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
01-24 08:09:25.767 E/ACRA    (13430): 	at okio.InputStreamSource.read(JvmOkio.kt:90)
01-24 08:09:25.767 E/ACRA    (13430): 	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
01-24 08:09:25.767 E/ACRA    (13430): 	... 20 more

```  

### App information

***App version***: `0.15.2` (`150299`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"sheldonp","BOOTLOADER":"unknown","BRAND":"Amazon","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"sheldonp","DISPLAY":"PS7614.3227N","FINGERPRINT":"Amazon\/sheldonp\/sheldonp:9\/PS7614.3227N\/0025938402048:user\/amz-p,release-keys","HARDWARE":"mt8695","HOST":"i3-ri-14-use1a-b-16-04-fos-99","ID":"PS7614.3227N","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Amazon","MODEL":"AFTSSS","PERMISSIONS_REVIEW_REQUIRED":false,"PRODUCT":"sheldonp","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"amz-p,release-keys","TIME":1668822366000,"TYPE":"user","UNKNOWN":"unknown","USER":"build","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"PPR1.180610.009","CODENAME":"REL","FIRST_SDK_INT":28,"INCREMENTAL":"0025938402180","PREVIEW_SDK_INT":0,"RELEASE":"9","RESOURCES_SDK_INT":28,"SDK":"28","SDK_INT":28,"SECURITY_PATCH":"2022-01-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":150299,"VERSION_NAME":"0.15.2"}
```  

### Device information

***Android version***: `9`  
***Device brand***: `Amazon`  
***Device product***: `sheldonp`  
***Device model***: `AFTSSS`  

### Crash information

***Start time***: `2023-01-24T08:09:06.718-05:00`  
***Crash time***: `2023-01-24T08:09:25.834-05:00`  

### Application version

0.15.2

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon

### Android version

Android 9

### Jellyfin server version

10.8.9

**Comment by candry7731** [comment]
I was able to allow my user to login by deleting the Parental Controls. 

However, I have a friend that does not have parental controls setup and his still crashes with the same socket error.
