### ISSUE TITLE
Crash when opening jpg

### ISSUE THREAD

**Issue by nsu700** [jellyfin/jellyfin-androidtv#2456]
### Describe the bug

1. Click into the photo library
2. Open either one of the jpg photo, the client failed to load the picture and crash, but it works ok for videos

### Logs

```yaml
2023-01-30T17:49:13+08:00	01-30 17:48:43.260 D/jellyfin-apiclient(13559): Adding request to queue: http://192.168.31.115:8096/Users/faf121f9-18b0-435b-9735-6d97e91bdaa3/Items?SortBy=DatePlayed&EnableTotalRecordCount=false&ExcludeLocationTypes=Virtual&MediaTypes=Audio&ImageTypeLimit=1&recursive=true&Filters=IsResumable&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount&sortOrder=Descending&Limit=50&format=json
2023-01-30T17:49:13+08:00	01-30 17:48:43.259 D/jellyfin-apiclient(13559): Adding request to queue: http://192.168.31.115:8096/Users/faf121f9-18b0-435b-9735-6d97e91bdaa3/Items?SortBy=DatePlayed&EnableTotalRecordCount=false&ExcludeLocationTypes=Virtual&MediaTypes=Video&ImageTypeLimit=1&recursive=true&Filters=IsResumable&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount&sortOrder=Descending&Limit=50&format=json
2023-01-30T17:49:13+08:00	01-30 17:48:43.239 D/jellyfin-apiclient(13559): Adding request to queue: http://192.168.31.115:8096/Users/faf121f9-18b0-435b-9735-6d97e91bdaa3/Views?format=json
2023-01-30T17:49:13+08:00	01-30 17:48:43.161 I/[Gralloc](13559): ddebug, pair (share_fd=86, user_hnd=4, ion_client=69)
2023-01-30T17:49:13+08:00	01-30 17:48:43.122 I/HomeRowsFragment(13559): Updating audio queue in HomeFragment (onResume)
2023-01-30T17:49:13+08:00	01-30 17:48:43.107 D/MediaManager(13559): Added event listener.  Total listeners: 1
2023-01-30T17:49:13+08:00	01-30 17:48:43.106 I/org.jellyfin.sdk.api.client.KtorClient(13559): GET http://192.168.31.115:8096/LiveTv/Programs/Recommended?userId=faf121f9-18b0-435b-9735-6d97e91bdaa3&limit=1&isAiring=true&imageTypeLimit=1&enableTotalRecordCount=false
2023-01-30T17:49:13+08:00	01-30 17:48:43.063 D/BackgroundServiceFragment(13559): Restoring background drawable
2023-01-30T17:49:13+08:00	01-30 17:48:43.063 D/ACRA    (13559): onActivityResumed class org.jellyfin.androidtv.ui.browsing.MainActivity
2023-01-30T17:49:13+08:00	01-30 17:48:43.062 D/ACRA    (13559): onActivityStarted class org.jellyfin.androidtv.ui.browsing.MainActivity
2023-01-30T17:49:13+08:00	01-30 17:48:43.058 I/BackgroundService(13559): Adding BackgroundServiceFragment to activity
2023-01-30T17:49:13+08:00	01-30 17:48:43.058 I/ActivityThemeExtensionsKt(13559): Applying theme DARK
2023-01-30T17:49:13+08:00	01-30 17:48:43.051 D/ACRA    (13559): onActivityCreated class org.jellyfin.androidtv.ui.browsing.MainActivity
2023-01-30T17:49:13+08:00	01-30 17:48:43.047 W/ActivityThread(13559): handleWindowVisibility: no activity for token android.os.BinderProxy@7c27f93
2023-01-30T17:49:13+08:00	01-30 17:48:43.041 D/ACRA    (13559): onActivityPaused class org.jellyfin.androidtv.ui.startup.StartupActivity
2023-01-30T17:49:13+08:00	01-30 17:48:43.031 D/StartupActivity(13559): Opening next activity Intent { flg=0x10004000 cmp=org.jellyfin.androidtv/.ui.browsing.MainActivity }
2023-01-30T17:49:13+08:00	01-30 17:48:43.029 D/NavigationRepositoryImpl(13559): Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.home.HomeFragment (Kotlin reflection is not available), arguments=Bundle[{}])
2023-01-30T17:49:13+08:00	01-30 17:48:43.029 D/org.jellyfin.sdk.api.sockets.SocketInstance(13559): Unable to update credentials: credentials did not change
2023-01-30T17:49:13+08:00	01-30 17:48:43.028 D/org.jellyfin.sdk.api.sockets.SocketInstance(13559): Credential update requested
2023-01-30T17:49:13+08:00	01-30 17:48:42.966 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(13559): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"bbe71c8cace944f6b3b0a08ec5271cec"}
2023-01-30T17:49:13+08:00	01-30 17:48:42.960 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(13559): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
2023-01-30T17:49:13+08:00	01-30 17:48:42.958 I/org.jellyfin.sdk.api.sockets.helper.KeepAliveHelper(13559): Using a KeepAlive message delay of 30 seconds
2023-01-30T17:49:13+08:00	```log
2023-01-30T17:49:13+08:00	***Logcat***:
2023-01-30T17:49:13+08:00	```
2023-01-30T17:49:13+08:00
2023-01-30T17:49:13+08:00		Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d336b94, Dispatchers.IO]
2023-01-30T17:49:13+08:00		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2023-01-30T17:49:13+08:00		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2023-01-30T17:49:13+08:00		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2023-01-30T17:49:13+08:00		at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2023-01-30T17:49:13+08:00		at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2023-01-30T17:49:13+08:00		at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
2023-01-30T17:49:13+08:00		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2023-01-30T17:49:13+08:00		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-01-30T17:49:13+08:00		at org.jellyfin.androidtv.ui.picture.PictureViewerViewModel$createPresentationJob$1.invokeSuspend(PictureViewerViewModel.kt:73)
2023-01-30T17:49:13+08:00		at org.jellyfin.androidtv.ui.picture.PictureViewerViewModel.showNext(PictureViewerViewModel.kt:51)
2023-01-30T17:49:13+08:00		at kotlin.collections.EmptyList.get(Collections.kt:24)
2023-01-30T17:49:13+08:00		at kotlin.collections.EmptyList.get(Collections.kt:36)
2023-01-30T17:49:13+08:00	java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.
2023-01-30T17:49:13+08:00	```log
2023-01-30T17:49:13+08:00	***Stack Trace***:
2023-01-30T17:49:13+08:00
2023-01-30T17:49:13+08:00	### Logs
2023-01-30T17:49:13+08:00	---
2023-01-30T17:49:13+08:00	format: markdown
2023-01-30T17:49:13+08:00	type: crash_report
2023-01-30T17:49:13+08:00	client_repository: https://github.com/jellyfin/jellyfin-androidtv
2023-01-30T17:49:13+08:00	client_version: 0.15.3
2023-01-30T17:49:13+08:00	client: Jellyfin for Android TV
2023-01-30T17:49:13+08:00	---
2023-01-30T17:49:10+08:00	[2023-01-30 17:49:10.653 +08:00] [WRN] Slow HTTP Response from "http://192.168.31.115:8096/Users/faf121f9-18b0-435b-9735-6d97e91bdaa3/Items?sortOrder=Descending&parentId=2d5b5152-9150-29a2-f062-ab4c235d8b37&fields=PrimaryImageAspectRatio&includeItemTypes=Photo&sortBy=DateCreated&sortBy=SortName&enableTotalRecordCount=true&enableImages=true" to "192.168.31.101" in 0:00:06.4900095 with Status Code 200
```

### Application version

0.15.3

### Where did you install the app from?

Google Play

### Device information

onn

### Android version

Android 10

### Jellyfin server version

10.8.8-1

**Comment by nielsvanvelzen** [comment]
Please post the crash logs as-is

**Comment by nsu700** [comment]
[Explore-logs-2023-01-31 09_44_53.txt](https://github.com/jellyfin/jellyfin-androidtv/files/10541727/Explore-logs-2023-01-31.09_44_53.txt)

**Comment by nielsvanvelzen** [comment]
```
2023-01-30T17:53:23+08:00	   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
2023-01-30T17:53:23+08:00	   at Jellyfin.Drawing.Skia.SkiaEncoder.EncodeImage(String inputPath, DateTime dateModified, String outputPath, Boolean autoOrient, Nullable`1 orientation, Int32 quality, ImageProcessingOptions options, ImageFormat outputFormat)
2023-01-30T17:53:23+08:00	System.IO.InvalidDataException: Skia unable to read image /Multimedia/Photo/58f42e4b5f4519ca582ca38cca00d0c8.JPG
```

I feel like this is an server issue. Can you check if this file exists and if the capitalization is correct (e.g. the file uses `.JPG` instead of `.jpg`)?

**Comment by nsu700** [comment]
You are true, just checked that all the JPG becomes 0 bytes, let me remove all the 0 bytes file and rescan the library
```
nsu@raspberrypi:~ $ ls -l /Multimedia/Photo/58f42e4b5f4519ca582ca38cca00d0c8.JPG
-rwxrwx--- 1 nsu users 0 Nov 11 17:41 /Multimedia/Photo/58f42e4b5f4519ca582ca38cca00d0c8.JPG
```

**Comment by nsu700** [comment]
Thank you @nielsvanvelzen , after removing all the 0 bytes file, it not crash anymore, but most of my pictures become blurry, and I found a lot error in the server side:
```
[2023-02-01 15:04:57.847 +08:00] [ERR] ffmpeg image extraction failed for "file:\"/Multimedia/Photo/2022-12-25 19.45.19.MOV\""
[2023-02-01 15:04:57.848 +08:00] [ERR] I-frame image extraction failed, will attempt standard way. Input: "file:\"/Multimedia/Photo/2022-12-25 19.45.19.MOV\""
MediaBrowser.Common.FfmpegException: ffmpeg image extraction failed for file:"/Multimedia/Photo/2022-12-25 19.45.19.MOV"
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImageInternal(String inputPath, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, Nullable`1 threedFormat, Nullable`1 offset, Boolean useIFrame, Nullable`1 targetFormat, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImage(String inputFile, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, MediaSourceInfo mediaSource, Boolean isAudio, Nullable`1 threedFormat, Nullable`1 offset, Nullable`1 targetFormat, CancellationToken cancellationToken)
[2023-02-01 15:05:08.636 +08:00] [ERR] ffmpeg image extraction failed for "file:\"/Multimedia/Photo/2021-11-20 17.02.00.MOV\""
[2023-02-01 15:05:08.644 +08:00] [ERR] I-frame image extraction failed, will attempt standard way. Input: "file:\"/Multimedia/Photo/2021-11-20 17.02.00.MOV\""
MediaBrowser.Common.FfmpegException: ffmpeg image extraction failed for file:"/Multimedia/Photo/2021-11-20 17.02.00.MOV"
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImageInternal(String inputPath, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, Nullable`1 threedFormat, Nullable`1 offset, Boolean useIFrame, Nullable`1 targetFormat, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImage(String inputFile, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, MediaSourceInfo mediaSource, Boolean isAudio, Nullable`1 threedFormat, Nullable`1 offset, Nullable`1 targetFormat, CancellationToken cancellationToken)
[2023-02-01 15:05:08.811 +08:00] [ERR] ffmpeg image extraction failed for "file:\"/Multimedia/Photo/2021-05-21 19.42.02.MOV\""
[2023-02-01 15:05:08.812 +08:00] [ERR] I-frame image extraction failed, will attempt standard way. Input: "file:\"/Multimedia/Photo/2021-05-21 19.42.02.MOV\""
MediaBrowser.Common.FfmpegException: ffmpeg image extraction failed for file:"/Multimedia/Photo/2021-05-21 19.42.02.MOV"
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImageInternal(String inputPath, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, Nullable`1 threedFormat, Nullable`1 offset, Boolean useIFrame, Nullable`1 targetFormat, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImage(String inputFile, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, MediaSourceInfo mediaSource, Boolean isAudio, Nullable`1 threedFormat, Nullable`1 offset, Nullable`1 targetFormat, CancellationToken cancellationToken)
```
[jellyfin20230201.log](https://github.com/jellyfin/jellyfin-androidtv/files/10554488/jellyfin20230201.log)

**Comment by nielsvanvelzen** [comment]
I made some changes so the client won't crash anymore when there are invalid images. I'd recommend creating an issue in the server repository for the server errors.
