### ISSUE TITLE
Crash when starting playback

### ISSUE THREAD

**Issue by OdinGitDat** [jellyfin/jellyfin-androidtv#2480]
### Describe the bug

Jellyfin app crashes when I resume a video from a certain time.

### Logs

---
client: Jellyfin for Android TV
client_version: 0.15.3
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.IllegalStateException: can't get VLCObject instance
	at org.videolan.libvlc.MediaPlayer.nativeSetAudioOutputDevice(Native Method)
	at org.videolan.libvlc.MediaPlayer.setAudioOutputDeviceInternal(MediaPlayer.java:995)
	at org.videolan.libvlc.MediaPlayer.updateAudioOutputDevice(MediaPlayer.java:485)
	at org.videolan.libvlc.MediaPlayer.access$600(MediaPlayer.java:58)
	at org.videolan.libvlc.MediaPlayer$3.onAudioDevicesChanged(MediaPlayer.java:561)
	at org.videolan.libvlc.MediaPlayer$3.onAudioDevicesAdded(MediaPlayer.java:574)
	at android.media.AudioManager$NativeEventHandlerDelegate$1.handleMessage(AudioManager.java:6264)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```  
***Logcat***: 
```log
02-05 17:34:55.481 W/AudioTrack( 9095): Use of stream types is deprecated for operations other than volume control
02-05 17:34:55.481 W/AudioTrack( 9095): See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
02-05 17:34:55.481 E/VLC     ( 9095): [0000002e12ce3d80/2bb9] libvlc audio output: AudioTrack getState failed
02-05 17:34:55.481 W/VLC     ( 9095): [0000002e12ce3d80/2bb9] libvlc audio output: SPDIF configuration failed
02-05 17:34:55.481 E/VLC     ( 9095): [0000002e12ce3d80/2bb9] libvlc audio output: module not functional
02-05 17:34:55.481 E/VLC     ( 9095): [0000002e22f519e0/2bb9] libvlc decoder: failed to create audio output
02-05 17:34:55.498 W/AudioTrack( 9095): Use of stream types is deprecated for operations other than volume control
02-05 17:34:55.498 W/AudioTrack( 9095): See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
02-05 17:34:55.618 D/ACRA    ( 9095): onActivityPaused class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
02-05 17:34:55.630 E/Surface ( 9095): freeAllBuffers: 11 buffers were freed while being dequeued!
02-05 17:34:55.633 D/ACRA    ( 9095): onActivityStopped class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
02-05 17:34:55.633 D/CustomPlaybackOverlayFragment( 9095): Stopping!
02-05 17:34:55.634 D/CustomPlaybackOverlayFragment( 9095): this fragment belongs to the current session, ending it
02-05 17:34:55.634 D/PlaybackController( 9095): stop called at 0
02-05 17:34:55.699 W/AudioSystem( 9095): ioConfigChanged() modifying unknown output! 38
02-05 17:34:55.700 W/AudioSystem( 9095): ioConfigChanged() modifying unknown output! 85
02-05 17:34:55.747 W/AudioTrack( 9095): restoreTrack_l(16): dead IAudioTrack, PCM, creating a new one from processAudioBuffer()
02-05 17:34:55.747 I/AudioSystem( 9095): clear the audio_io_handle:13
02-05 17:34:55.747 I/AudioSystem( 9095): clear the audio_io_handle:21
02-05 17:34:55.747 I/AudioSystem( 9095): clear the audio_io_handle:29
02-05 17:34:55.747 I/BpBinder( 9095): onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
02-05 17:34:55.748 I/BpBinder( 9095): onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
02-05 17:34:55.752 E/AudioSystem( 9095): calling AudioErrorCallbacks, err:0x0
02-05 17:34:55.940 E/NdkMediaCodec( 9095): sf error code: -13
02-05 17:34:55.953 E/Surface ( 9095): getSlotFromBufferLocked: unknown buffer: 0x2df2d38b10
02-05 17:34:55.953 W/ACodec  ( 9095): [OMX.Nvidia.h264.decode] can not return buffer 26 to native window
02-05 17:34:55.953 E/Surface ( 9095): getSlotFromBufferLocked: unknown buffer: 0x2df2d40210
02-05 17:34:55.953 W/ACodec  ( 9095): [OMX.Nvidia.h264.decode] can not return buffer 25 to native window
02-05 17:34:55.954 E/Surface ( 9095): getSlotFromBufferLocked: unknown buffer: 0x2df2d06610
02-05 17:34:55.954 W/ACodec  ( 9095): [OMX.Nvidia.h264.decode] can not return buffer 24 to native window
02-05 17:34:55.954 E/Surface ( 9095): getSlotFromBufferLocked: unknown buffer: 0x2df2d69790
02-05 17:34:55.954 W/ACodec  ( 9095): [OMX.Nvidia.h264.decode] can not return buffer 23 to native window
02-05 17:34:55.955 E/Surface ( 9095): getSlotFromBufferLocked: unknown buffer: 0x2df2d20690
02-05 17:34:55.955 W/ACodec  ( 9095): [OMX.Nvidia.h264.decode] can not return buffer 22 to native window
02-05 17:34:55.955 E/Surface ( 9095): getSlotFromBufferLocked: unknown buffer: 0x2df2d20310
02-05 17:34:55.955 W/ACodec  ( 9095): [OMX.Nvidia.h264.decode] can not return buffer 21 to native window
02-05 17:34:55.955 E/Surface ( 9095): getSlotFromBufferLocked: unknown buffer: 0x2df2d1fa50
02-05 17:34:55.955 W/ACodec  ( 9095): [OMX.Nvidia.h264.decode] can not return buffer 20 to native window
02-05 17:34:55.956 E/Surface ( 9095): getSlotFromBufferLocked: unknown buffer: 0x2df2d1f190
02-05 17:34:55.956 W/ACodec  ( 9095): [OMX.Nvidia.h264.decode] can not return buffer 19 to native window
02-05 17:34:55.956 E/Surface ( 9095): getSlotFromBufferLocked: unknown buffer: 0x2df2d1d590
02-05 17:34:55.956 W/ACodec  ( 9095): [OMX.Nvidia.h264.decode] can not return buffer 18 to native window
02-05 17:34:55.956 E/Surface ( 9095): getSlotFromBufferLocked: unknown buffer: 0x2df2d37450
02-05 17:34:55.956 W/ACodec  ( 9095): [OMX.Nvidia.h264.decode] can not return buffer 17 to native window
02-05 17:34:55.957 E/Surface ( 9095): getSlotFromBufferLocked: unknown buffer: 0x2df2d38cd0
02-05 17:34:55.957 W/ACodec  ( 9095): [OMX.Nvidia.h264.decode] can not return buffer 16 to native window
02-05 17:34:55.958 D/SurfaceUtils( 9095): disconnecting from surface 0x2ea2d41f80, reason disconnectFromSurface
02-05 17:34:55.958 E/Surface ( 9095): freeAllBuffers: 11 buffers were freed while being dequeued!
02-05 17:34:55.964 D/AudioTrack( 9095): stop(25): called with 0 frames delivered
02-05 17:34:55.970 E/VLC     ( 9095): [0000002df2d65220/2baa] http stream: local stream 11 error: Cancellation (0x8)
02-05 17:34:55.971 E/VLC     ( 9095): [0000002df2d65220/2bad] http stream: peer error: No error (0x0)
02-05 17:34:55.980 E/libEGL  ( 9095): eglCreateWindowSurface: native_window_api_connect (win=0x2ea2d41f80) failed (0xffffffed) (already connected to another API?)
02-05 17:34:55.980 E/libEGL  ( 9095): eglCreateWindowSurfaceTmpl:850 error 3003 (EGL_BAD_ALLOC)
02-05 17:34:55.980 E/VLC     ( 9095): [0000002de2ce25e0/2baf] libvlc gl: cannot create EGL window surface
02-05 17:34:56.131 I/jellyfin-apiclient( 9095): ReportPlaybackStopped: Item 67f519e5-d26e-5fa2-2891-e590b2c6eed1, Ticks: 0
02-05 17:34:56.131 D/jellyfin-apiclient( 9095): Adding request to queue: https://xxx.com/Sessions/Playing/Stopped
02-05 17:34:56.134 I/ExoPlayerImpl( 9095): Release 4ea9d5c [ExoPlayerLib/2.18.2] [mdarcy, SHIELD Android TV, NVIDIA, 30] [goog.exo.core, goog.exo.ui, goog.exo.exoplayer, goog.exo.decoder]
02-05 17:34:56.142 D/ACRA    ( 9095): onActivitySaveInstanceState class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
02-05 17:34:56.144 D/AndroidRuntime( 9095): Shutting down VM
--------- beginning of crash
02-05 17:34:56.144 E/AndroidRuntime( 9095): FATAL EXCEPTION: main
02-05 17:34:56.144 E/AndroidRuntime( 9095): Process: org.jellyfin.androidtv, PID: 9095
02-05 17:34:56.144 E/AndroidRuntime( 9095): java.lang.IllegalStateException: can't get VLCObject instance
02-05 17:34:56.144 E/AndroidRuntime( 9095): 	at org.videolan.libvlc.MediaPlayer.nativeSetAudioOutputDevice(Native Method)
02-05 17:34:56.144 E/AndroidRuntime( 9095): 	at org.videolan.libvlc.MediaPlayer.setAudioOutputDeviceInternal(MediaPlayer.java:995)
02-05 17:34:56.144 E/AndroidRuntime( 9095): 	at org.videolan.libvlc.MediaPlayer.updateAudioOutputDevice(MediaPlayer.java:485)
02-05 17:34:56.144 E/AndroidRuntime( 9095): 	at org.videolan.libvlc.MediaPlayer.access$600(MediaPlayer.java:58)
02-05 17:34:56.144 E/AndroidRuntime( 9095): 	at org.videolan.libvlc.MediaPlayer$3.onAudioDevicesChanged(MediaPlayer.java:561)
02-05 17:34:56.144 E/AndroidRuntime( 9095): 	at org.videolan.libvlc.MediaPlayer$3.onAudioDevicesAdded(MediaPlayer.java:574)
02-05 17:34:56.144 E/AndroidRuntime( 9095): 	at android.media.AudioManager$NativeEventHandlerDelegate$1.handleMessage(AudioManager.java:6264)
02-05 17:34:56.144 E/AndroidRuntime( 9095): 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-05 17:34:56.144 E/AndroidRuntime( 9095): 	at android.os.Looper.loop(Looper.java:223)
02-05 17:34:56.144 E/AndroidRuntime( 9095): 	at android.app.ActivityThread.main(ActivityThread.java:7668)
02-05 17:34:56.144 E/AndroidRuntime( 9095): 	at java.lang.reflect.Method.invoke(Native Method)
02-05 17:34:56.144 E/AndroidRuntime( 9095): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-05 17:34:56.144 E/AndroidRuntime( 9095): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
02-05 17:34:56.144 E/ACRA    ( 9095): ACRA caught a IllegalStateException for org.jellyfin.androidtv
02-05 17:34:56.144 E/ACRA    ( 9095): java.lang.IllegalStateException: can't get VLCObject instance
02-05 17:34:56.144 E/ACRA    ( 9095): 	at org.videolan.libvlc.MediaPlayer.nativeSetAudioOutputDevice(Native Method)
02-05 17:34:56.144 E/ACRA    ( 9095): 	at org.videolan.libvlc.MediaPlayer.setAudioOutputDeviceInternal(MediaPlayer.java:995)
02-05 17:34:56.144 E/ACRA    ( 9095): 	at org.videolan.libvlc.MediaPlayer.updateAudioOutputDevice(MediaPlayer.java:485)
02-05 17:34:56.144 E/ACRA    ( 9095): 	at org.videolan.libvlc.MediaPlayer.access$600(MediaPlayer.java:58)
02-05 17:34:56.144 E/ACRA    ( 9095): 	at org.videolan.libvlc.MediaPlayer$3.onAudioDevicesChanged(MediaPlayer.java:561)
02-05 17:34:56.144 E/ACRA    ( 9095): 	at org.videolan.libvlc.MediaPlayer$3.onAudioDevicesAdded(MediaPlayer.java:574)
02-05 17:34:56.144 E/ACRA    ( 9095): 	at android.media.AudioManager$NativeEventHandlerDelegate$1.handleMessage(AudioManager.java:6264)
02-05 17:34:56.144 E/ACRA    ( 9095): 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-05 17:34:56.144 E/ACRA    ( 9095): 	at android.os.Looper.loop(Looper.java:223)
02-05 17:34:56.144 E/ACRA    ( 9095): 	at android.app.ActivityThread.main(ActivityThread.java:7668)
02-05 17:34:56.144 E/ACRA    ( 9095): 	at java.lang.reflect.Method.invoke(Native Method)
02-05 17:34:56.144 E/ACRA    ( 9095): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-05 17:34:56.144 E/ACRA    ( 9095): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
02-05 17:34:56.144 D/ACRA    ( 9095): Building report
02-05 17:34:56.145 D/ACRA    ( 9095): Starting collectors with priority FIRST
02-05 17:34:56.146 D/ACRA    ( 9095): Calling collector org.acra.collector.DropBoxCollector
02-05 17:34:56.146 D/ACRA    ( 9095): Collector org.acra.collector.DropBoxCollector completed
02-05 17:34:56.146 D/ACRA    ( 9095): Calling collector org.acra.collector.LogCatCollector
02-05 17:34:56.146 D/ACRA    ( 9095): Calling collector org.acra.collector.StacktraceCollector
02-05 17:34:56.147 D/ACRA    ( 9095): Collector org.acra.collector.StacktraceCollector completed
02-05 17:34:56.149 D/ACRA    ( 9095): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.15.3` (`150399`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"darcy","BOOTLOADER":"32.00.2019.50-t210-69ebfcbe","BRAND":"NVIDIA","CPU_ABI":"arm64-v8a","CPU_ABI2":"","DEVICE":"mdarcy","DISPLAY":"RQ1A.210105.003.7825230_3167.5736","FINGERPRINT":"NVIDIA\/mdarcy\/mdarcy:11\/RQ1A.210105.003\/7825230_3167.5736:user\/release-keys","HARDWARE":"darcy","HOST":"mobile-u64-5308-d7000","ID":"RQ1A.210105.003","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"NVIDIA","MODEL":"SHIELD Android TV","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"mdarcy","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":["arm64-v8a"],"SUPPORTED_ABIS":["arm64-v8a","armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1665975826000,"TYPE":"user","UNKNOWN":"unknown","USER":"NVIDIA","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"7825230_3167.5736","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"11","RELEASE_OR_CODENAME":"11","SDK":"30","SDK_INT":30,"SECURITY_PATCH":"2022-04-05"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":150399,"VERSION_NAME":"0.15.3"}
```  

### Device information

***Android version***: `11`  
***Device brand***: `NVIDIA`  
***Device product***: `mdarcy`  
***Device model***: `SHIELD Android TV`  

### Crash information

***Start time***: `2023-02-05T17:03:55.875+01:00`  
***Crash time***: `2023-02-05T17:34:56.169+01:00`  

### Application version

0.15.3

### Device information

SHIELD Android TV

### Android version

11

### Jellyfin server version

10.8.9

**Comment by StanDaMann** [comment]
I have the same issue.
ZFold 4
Android 13

**Comment by ValentinBerkatyuk** [comment]
same
Fire Stick
