### ISSUE TITLE
Crash on exiting playback java.lang.IllegalStateException

### ISSUE THREAD

**Issue by Violat0r** [jellyfin/jellyfin-androidtv#2508]
### Describe the bug

1. Play a video
2. Press back to return to Jellyfin menu.
3. Shield becomes unresponsive and needs to be unplugged.

I have refresh rate switching scale on TV on.  Turning it off I believe stops the crashing from my limited testing.

Might be related to  #2316 

### Logs

---
client: Jellyfin for Android TV
client_version: 0.15.3
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.IllegalStateException: can't get VLCObject instance
	at org.videolan.libvlc.MediaPlayer.nativeSetAudioOutputDevice(Native Method)
	at org.videolan.libvlc.MediaPlayer.setAudioOutputDeviceInternal(MediaPlayer.java:995)
	at org.videolan.libvlc.MediaPlayer.updateAudioOutputDevice(MediaPlayer.java:485)
	at org.videolan.libvlc.MediaPlayer.access$600(MediaPlayer.java:58)
	at org.videolan.libvlc.MediaPlayer$3.onAudioDevicesChanged(MediaPlayer.java:561)
	at org.videolan.libvlc.MediaPlayer$3.onAudioDevicesRemoved(MediaPlayer.java:585)
	at android.media.AudioManager$NativeEventHandlerDelegate$1.handleMessage(AudioManager.java:6270)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```  
***Logcat***: 
```log
02-16 16:50:41.641 E/libc    (10465): Access denied finding property "ro.vendor.sys.NV_LOGFPS"
02-16 16:50:41.641 E/libc    (10465): Access denied finding property "ro.vendor.sys.NV_PROCESS_NAME"
02-16 16:50:41.641 E/libc    (10465): Access denied finding property "ro.vendor.sys.NV_FPSDYNAMIC"
02-16 16:50:41.677 D/SurfaceUtils(10465): connecting to surface 0x2420011850, reason connectToSurface
02-16 16:50:41.677 I/MediaCodec(10465): [OMX.Nvidia.h265.decode] setting surface generation to 10716162
02-16 16:50:41.677 D/SurfaceUtils(10465): disconnecting from surface 0x2420011850, reason connectToSurface(reconnect)
02-16 16:50:41.677 D/SurfaceUtils(10465): connecting to surface 0x2420011850, reason connectToSurface(reconnect)
02-16 16:50:41.678 D/SurfaceUtils(10465): set up nativeWindow 0x2420011850 for 3828x1592, color 0x18b, rotation 0, usage 0x2900
02-16 16:50:41.678 D/SurfaceUtils(10465): disconnecting from surface 0x241fff3b70, reason disconnectFromSurface
02-16 16:50:41.678 E/Surface (10465): freeAllBuffers: 13 buffers were freed while being dequeued!
02-16 16:50:41.680 E/AudioTrack-JNI(10465): Error -32 during AudioTrack native read
02-16 16:50:41.680 E/DecoderAudioRenderer(10465): Audio sink error
02-16 16:50:41.680 E/DecoderAudioRenderer(10465):   com.google.android.exoplayer2.audio.AudioSink$WriteException: AudioTrack write failed: -6
02-16 16:50:41.680 E/DecoderAudioRenderer(10465):       at com.google.android.exoplayer2.audio.DefaultAudioSink.writeBuffer(DefaultAudioSink.java:1177)
02-16 16:50:41.680 E/DecoderAudioRenderer(10465):       at com.google.android.exoplayer2.audio.DefaultAudioSink.processBuffers(DefaultAudioSink.java:1099)
02-16 16:50:41.680 E/DecoderAudioRenderer(10465):       at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:1026)
02-16 16:50:41.680 E/DecoderAudioRenderer(10465):       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:706)
02-16 16:50:41.680 E/DecoderAudioRenderer(10465):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.bypassRender(MediaCodecRenderer.java:2203)
02-16 16:50:41.680 E/DecoderAudioRenderer(10465):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:787)
02-16 16:50:41.680 E/DecoderAudioRenderer(10465):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:994)
02-16 16:50:41.680 E/DecoderAudioRenderer(10465):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:495)
02-16 16:50:41.680 E/DecoderAudioRenderer(10465):       at android.os.Handler.dispatchMessage(Handler.java:102)
02-16 16:50:41.680 E/DecoderAudioRenderer(10465):       at android.os.Looper.loop(Looper.java:223)
02-16 16:50:41.680 E/DecoderAudioRenderer(10465):       at android.os.HandlerThread.run(HandlerThread.java:67)
02-16 16:50:41.681 D/ACRA    (10465): onActivityStopped class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
02-16 16:50:41.688 W/ExoPlayerImplInternal(10465): Recoverable renderer error
02-16 16:50:41.688 W/ExoPlayerImplInternal(10465):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(2, null, null, audio/eac3, null, -1, en, [-1, -1, -1.0], [6, 48000]), format_supported=YES
02-16 16:50:41.688 W/ExoPlayerImplInternal(10465):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:571)
02-16 16:50:41.688 W/ExoPlayerImplInternal(10465):       at android.os.Handler.dispatchMessage(Handler.java:102)
02-16 16:50:41.688 W/ExoPlayerImplInternal(10465):       at android.os.Looper.loop(Looper.java:223)
02-16 16:50:41.688 W/ExoPlayerImplInternal(10465):       at android.os.HandlerThread.run(HandlerThread.java:67)
02-16 16:50:41.688 W/ExoPlayerImplInternal(10465):   Caused by: com.google.android.exoplayer2.audio.AudioSink$WriteException: AudioTrack write failed: -6
02-16 16:50:41.688 W/ExoPlayerImplInternal(10465):       at com.google.android.exoplayer2.audio.DefaultAudioSink.writeBuffer(DefaultAudioSink.java:1177)
02-16 16:50:41.688 W/ExoPlayerImplInternal(10465):       at com.google.android.exoplayer2.audio.DefaultAudioSink.processBuffers(DefaultAudioSink.java:1099)
02-16 16:50:41.688 W/ExoPlayerImplInternal(10465):       at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:1026)
02-16 16:50:41.688 W/ExoPlayerImplInternal(10465):       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:706)
02-16 16:50:41.688 W/ExoPlayerImplInternal(10465):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.bypassRender(MediaCodecRenderer.java:2203)
02-16 16:50:41.688 W/ExoPlayerImplInternal(10465):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:787)
02-16 16:50:41.688 W/ExoPlayerImplInternal(10465):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:994)
02-16 16:50:41.688 W/ExoPlayerImplInternal(10465):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:495)
02-16 16:50:41.688 W/ExoPlayerImplInternal(10465):       ... 3 more
02-16 16:50:41.706 D/CustomPlaybackOverlayFragment(10465): Stopping!
02-16 16:50:41.706 D/CustomPlaybackOverlayFragment(10465): this fragment belongs to the current session, ending it
02-16 16:50:41.706 D/PlaybackController(10465): stop called at 856900
02-16 16:50:41.760 I/lyfin.androidt(10465): Waiting for a blocking GC ProfileSaver
02-16 16:50:41.895 I/jellyfin-apiclient(10465): ReportPlaybackStopped: Item 9e3a05a9-c50b-7021-bf0c-d34ce94bda10, Ticks: 8569000000
02-16 16:50:41.895 D/jellyfin-apiclient(10465): Adding request to queue: https://jellyfin.RREMOVED.net/Sessions/Playing/Stopped
02-16 16:50:41.905 I/ExoPlayerImpl(10465): Release 5af00d3 [ExoPlayerLib/2.18.2] [mdarcy, SHIELD Android TV, NVIDIA, 30] [goog.exo.core, goog.exo.ui, goog.exo.exoplayer, goog.exo.decoder, goog.exo.datasource, goog.exo.extractor, goog.exo.ffmpeg]
02-16 16:50:41.922 I/lyfin.androidt(10465): WaitForGcToComplete blocked ProfileSaver on HeapTrim for 162.256ms
02-16 16:50:41.937 D/SurfaceUtils(10465): connecting to surface 0x242000d430, reason connectToSurface
02-16 16:50:41.937 I/MediaCodec(10465): [OMX.Nvidia.h265.decode] setting surface generation to 10716163
02-16 16:50:41.937 D/SurfaceUtils(10465): disconnecting from surface 0x242000d430, reason connectToSurface(reconnect)
02-16 16:50:41.937 D/SurfaceUtils(10465): connecting to surface 0x242000d430, reason connectToSurface(reconnect)
02-16 16:50:41.939 D/SurfaceUtils(10465): set up nativeWindow 0x242000d430 for 3828x1592, color 0x18b, rotation 0, usage 0x2900
02-16 16:50:41.940 D/SurfaceUtils(10465): disconnecting from surface 0x2420011850, reason disconnectFromSurface
02-16 16:50:41.940 E/Surface (10465): freeAllBuffers: 13 buffers were freed while being dequeued!
02-16 16:50:41.956 D/SurfaceUtils(10465): disconnecting from surface 0x242000d430, reason disconnectFromSurface
02-16 16:50:42.018 D/ACRA    (10465): onActivitySaveInstanceState class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
02-16 16:50:42.030 D/AndroidRuntime(10465): Shutting down VM
--------- beginning of crash
02-16 16:50:42.041 E/AndroidRuntime(10465): FATAL EXCEPTION: main
02-16 16:50:42.041 E/AndroidRuntime(10465): Process: org.jellyfin.androidtv, PID: 10465
02-16 16:50:42.041 E/AndroidRuntime(10465): java.lang.IllegalStateException: can't get VLCObject instance
02-16 16:50:42.041 E/AndroidRuntime(10465): 	at org.videolan.libvlc.MediaPlayer.nativeSetAudioOutputDevice(Native Method)
02-16 16:50:42.041 E/AndroidRuntime(10465): 	at org.videolan.libvlc.MediaPlayer.setAudioOutputDeviceInternal(MediaPlayer.java:995)
02-16 16:50:42.041 E/AndroidRuntime(10465): 	at org.videolan.libvlc.MediaPlayer.updateAudioOutputDevice(MediaPlayer.java:485)
02-16 16:50:42.041 E/AndroidRuntime(10465): 	at org.videolan.libvlc.MediaPlayer.access$600(MediaPlayer.java:58)
02-16 16:50:42.041 E/AndroidRuntime(10465): 	at org.videolan.libvlc.MediaPlayer$3.onAudioDevicesChanged(MediaPlayer.java:561)
02-16 16:50:42.041 E/AndroidRuntime(10465): 	at org.videolan.libvlc.MediaPlayer$3.onAudioDevicesRemoved(MediaPlayer.java:585)
02-16 16:50:42.041 E/AndroidRuntime(10465): 	at android.media.AudioManager$NativeEventHandlerDelegate$1.handleMessage(AudioManager.java:6270)
02-16 16:50:42.041 E/AndroidRuntime(10465): 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-16 16:50:42.041 E/AndroidRuntime(10465): 	at android.os.Looper.loop(Looper.java:223)
02-16 16:50:42.041 E/AndroidRuntime(10465): 	at android.app.ActivityThread.main(ActivityThread.java:7668)
02-16 16:50:42.041 E/AndroidRuntime(10465): 	at java.lang.reflect.Method.invoke(Native Method)
02-16 16:50:42.041 E/AndroidRuntime(10465): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-16 16:50:42.041 E/AndroidRuntime(10465): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
02-16 16:50:42.052 E/ACRA    (10465): ACRA caught a IllegalStateException for org.jellyfin.androidtv
02-16 16:50:42.052 E/ACRA    (10465): java.lang.IllegalStateException: can't get VLCObject instance
02-16 16:50:42.052 E/ACRA    (10465): 	at org.videolan.libvlc.MediaPlayer.nativeSetAudioOutputDevice(Native Method)
02-16 16:50:42.052 E/ACRA    (10465): 	at org.videolan.libvlc.MediaPlayer.setAudioOutputDeviceInternal(MediaPlayer.java:995)
02-16 16:50:42.052 E/ACRA    (10465): 	at org.videolan.libvlc.MediaPlayer.updateAudioOutputDevice(MediaPlayer.java:485)
02-16 16:50:42.052 E/ACRA    (10465): 	at org.videolan.libvlc.MediaPlayer.access$600(MediaPlayer.java:58)
02-16 16:50:42.052 E/ACRA    (10465): 	at org.videolan.libvlc.MediaPlayer$3.onAudioDevicesChanged(MediaPlayer.java:561)
02-16 16:50:42.052 E/ACRA    (10465): 	at org.videolan.libvlc.MediaPlayer$3.onAudioDevicesRemoved(MediaPlayer.java:585)
02-16 16:50:42.052 E/ACRA    (10465): 	at android.media.AudioManager$NativeEventHandlerDelegate$1.handleMessage(AudioManager.java:6270)
02-16 16:50:42.052 E/ACRA    (10465): 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-16 16:50:42.052 E/ACRA    (10465): 	at android.os.Looper.loop(Looper.java:223)
02-16 16:50:42.052 E/ACRA    (10465): 	at android.app.ActivityThread.main(ActivityThread.java:7668)
02-16 16:50:42.052 E/ACRA    (10465): 	at java.lang.reflect.Method.invoke(Native Method)
02-16 16:50:42.052 E/ACRA    (10465): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-16 16:50:42.052 E/ACRA    (10465): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
02-16 16:50:42.052 D/ACRA    (10465): Building report
02-16 16:50:42.058 D/ACRA    (10465): Starting collectors with priority FIRST
02-16 16:50:42.059 D/ACRA    (10465): Calling collector org.acra.collector.DropBoxCollector
02-16 16:50:42.059 D/ACRA    (10465): Calling collector org.acra.collector.StacktraceCollector
02-16 16:50:42.059 D/ACRA    (10465): Calling collector org.acra.collector.LogCatCollector
02-16 16:50:42.059 D/ACRA    (10465): Collector org.acra.collector.DropBoxCollector completed
02-16 16:50:42.059 D/ACRA    (10465): Collector org.acra.collector.StacktraceCollector completed
02-16 16:50:42.120 D/ACRA    (10465): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.15.3` (`150399`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"darcy","BOOTLOADER":"32.00.2019.50-t210-69ebfcbe","BRAND":"NVIDIA","CPU_ABI":"arm64-v8a","CPU_ABI2":"","DEVICE":"mdarcy","DISPLAY":"RQ1A.210105.003.7825230_3167.5736","FINGERPRINT":"NVIDIA\/mdarcy\/mdarcy:11\/RQ1A.210105.003\/7825230_3167.5736:user\/release-keys","HARDWARE":"darcy","HOST":"mobile-u64-5308-d7000","ID":"RQ1A.210105.003","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"NVIDIA","MODEL":"SHIELD Android TV","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"mdarcy","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":["arm64-v8a"],"SUPPORTED_ABIS":["arm64-v8a","armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1665975826000,"TYPE":"user","UNKNOWN":"unknown","USER":"NVIDIA","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"7825230_3167.5736","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"11","RELEASE_OR_CODENAME":"11","SDK":"30","SDK_INT":30,"SECURITY_PATCH":"2022-04-05"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":150399,"VERSION_NAME":"0.15.3"}
```  

### Device information

***Android version***: `11`  
***Device brand***: `NVIDIA`  
***Device product***: `mdarcy`  
***Device model***: `SHIELD Android TV`  

### Crash information

***Start time***: `2023-02-16T16:26:12.292-08:00`  
***Crash time***: `2023-02-16T16:50:42.354-08:00`  

### Application version

0.15.3

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro 2019

### Android version

Android 11

### Jellyfin server version

10.8.8 in Docker by linuxserver

**Comment by zilexa** [comment]
I have the same. On a ShieldTV Pro. Also had it with previous versions. Makes it completely unusable. I have to unplug the ShieldTV and replug. 
This can't be good for the device.

**Comment by Violat0r** [comment]
#2480 looks to be the same issue.

**Comment by OdinGitDat** [comment]
Correct, same problem but I've had refresh rate switching disabled so I don't think that setting is related.
