### ISSUE TITLE
Crash at Login

### ISSUE THREAD

**Issue by jumoog** [jellyfin/jellyfin-androidtv#2514]
### Describe the bug

Open the App and tried to login.

### Logs

***Stack Trace***: 
```log
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.UUID org.jellyfin.sdk.model.api.UserDto.getId()' on a null object reference
	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment.loadItem(FullDetailsFragment.java:409)
	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment.access$500(FullDetailsFragment.java:125)
	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment$3.run(FullDetailsFragment.java:270)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```  
***Logcat***: 
```log
02-19 21:32:14.216 E/Surface (12783): getSlotFromBufferLocked: unknown buffer: 0xc310a980
02-19 21:32:14.216 W/ACodec  (12783): [OMX.amlogic.avc.decoder.awesome2] can not return buffer 11 to native window
02-19 21:32:14.217 E/Surface (12783): getSlotFromBufferLocked: unknown buffer: 0xc310a5c0
02-19 21:32:14.217 W/ACodec  (12783): [OMX.amlogic.avc.decoder.awesome2] can not return buffer 10 to native window
02-19 21:32:14.218 E/Surface (12783): getSlotFromBufferLocked: unknown buffer: 0xc310a480
02-19 21:32:14.218 W/ACodec  (12783): [OMX.amlogic.avc.decoder.awesome2] can not return buffer 9 to native window
02-19 21:32:14.219 E/Surface (12783): getSlotFromBufferLocked: unknown buffer: 0xc310a340
02-19 21:32:14.219 W/ACodec  (12783): [OMX.amlogic.avc.decoder.awesome2] can not return buffer 8 to native window
02-19 21:32:14.236 E/BufferQueueProducer(12783): [SurfaceView[org.jellyfin.androidtv/org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity]#89(BLAST Consumer)89](id:31ef00000059,api:0,p:-1,c:12783) connect: BufferQueue has been abandoned
02-19 21:32:14.236 E/libEGL  (12783): eglCreateWindowSurface: native_window_api_connect (win=0xef97b408) failed (0xffffffed) (already connected to another API?)
02-19 21:32:14.236 E/libEGL  (12783): eglCreateWindowSurfaceTmpl:676 error 3003 (EGL_BAD_ALLOC)
02-19 21:32:14.236 E/VLC     (12783): [f2979cb0/1cdb] libvlc gl: cannot create EGL window surface
02-19 21:32:14.521 D/ACRA    (12783): onActivityStopped class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
02-19 21:32:14.522 D/CustomPlaybackOverlayFragment(12783): Stopping!
02-19 21:32:14.523 D/CustomPlaybackOverlayFragment(12783): this fragment belongs to the current session, ending it
02-19 21:32:14.524 D/PlaybackController(12783): stop called at 562721
02-19 21:32:14.529 D/lyfin.androidt(12783): PlayerBase::stop() from IPlayer
02-19 21:32:14.529 D/AudioTrack(12783): stop(273): called with 27042180 frames delivered
02-19 21:32:14.533 D/lyfin.androidt(12783): PlayerBase::stop() from IPlayer
02-19 21:32:14.533 D/AudioTrack(12783): stop(273): called with 0 frames delivered
02-19 21:32:14.537 E/VLC     (12783): [f2d2bd70/1cd4] http stream: local stream 7 error: Cancellation (0x8)
02-19 21:32:14.568 E/VLC     (12783): [f2d2bd70/1cd9] http stream: peer error: No error (0x0)
02-19 21:32:14.794 I/jellyfin-apiclient(12783): ReportPlaybackStopped: Item a39beed1-849d-8974-bcf0-a4cd7e9eb4e3, Ticks: 5627210000
02-19 21:32:14.795 D/jellyfin-apiclient(12783): Adding request to queue: https://******:8920/Sessions/Playing/Stopped
02-19 21:32:14.798 I/ExoPlayerImpl(12783): Release 467e79 [ExoPlayerLib/2.18.2] [sabrina, Chromecast, Google, 31] [goog.exo.core, goog.exo.ui, goog.exo.exoplayer, goog.exo.decoder]
02-19 21:32:14.849 D/ACRA    (12783): onActivitySaveInstanceState class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
02-19 21:32:14.852 D/ACRA    (12783): onActivityDestroyed class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
02-19 21:32:14.988 I/jellyfin-apiclient(12783): Response received from: https://******:8920/Sessions/Playing/Stopped
02-19 21:32:15.468 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(12783): Receiving (raw) message {"MessageType":"UserDataChanged","MessageId":"83beb383a4e44cc3b461c1b675c6e0ea","Data":{"UserId":"2cdf4968f747496ca2b5cde86b4fbaf7","UserDataList":[{"PlayedPercentage":23.254778399507458,"PlaybackPositionTicks":5627210000,"PlayCount":2,"IsFavorite":false,"LastPlayedDate":"2023-02-19T20:20:53.9824063Z","Played":false,"Key":"95441001003","ItemId":"a39beed1849d8974bcf0a4cd7e9eb4e3"},{"UnplayedItemCount":22,"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"95441001","ItemId":"49cfb2fe9b1656f31737fe66fe0c818c"}]}}
02-19 21:32:24.264 D/ACRA    (12783): onActivityStarted class org.jellyfin.androidtv.ui.browsing.MainActivity
02-19 21:32:24.265 I/ProcessLifecycleInitializer$create(12783): Process lifecycle started
02-19 21:32:24.266 D/SessionRepositoryImpl(12783): Restoring session
02-19 21:32:24.268 D/SessionRepositoryImpl(12783): Destroying current session
02-19 21:32:24.268 D/ACRA    (12783): onActivityResumed class org.jellyfin.androidtv.ui.browsing.MainActivity
02-19 21:32:24.269 W/ActivityAuthenticationExtensionsKt(12783): Activity org.jellyfin.androidtv.ui.browsing.MainActivity started without a session, bouncing to StartupActivity
02-19 21:32:24.279 D/BackgroundServiceFragment(12783): Restoring active backgrounds
02-19 21:32:24.280 D/BackgroundServiceFragment(12783): Restoring background drawable
02-19 21:32:24.370 D/ACRA    (12783): onActivityPaused class org.jellyfin.androidtv.ui.browsing.MainActivity
02-19 21:32:24.389 D/ACRA    (12783): onActivityCreated class org.jellyfin.androidtv.ui.startup.StartupActivity
02-19 21:32:24.397 I/ActivityThemeExtensionsKt(12783): Applying theme DARK
02-19 21:32:24.399 I/BackgroundService(12783): Adding BackgroundServiceFragment to activity
02-19 21:32:24.401 D/ACRA    (12783): onActivityStarted class org.jellyfin.androidtv.ui.startup.StartupActivity
02-19 21:32:24.403 D/ACRA    (12783): onActivityResumed class org.jellyfin.androidtv.ui.startup.StartupActivity
02-19 21:32:24.404 D/BackgroundServiceFragment(12783): Restoring background drawable
02-19 21:32:24.420 D/Compose Focus(12783): Owner FocusChanged(true)
02-19 21:32:24.449 D/MediaManager(12783): clearing the audio queue
02-19 21:32:24.454 I/MediaManager(12783): Firing queue state change listener. false
02-19 21:32:24.460 I/MediaManager(12783): Firing queue state change listener. false
02-19 21:32:24.519 I/org.jellyfin.sdk.api.client.KtorClient(12783): GET https://******:8920/Users/Public
02-19 21:32:24.524 D/Compose Focus(12783): Owner FocusChanged(false)
02-19 21:32:24.524 D/Compose Focus(12783): Owner FocusChanged(true)
02-19 21:32:24.524 D/Compose Focus(12783): Owner FocusChanged(false)
02-19 21:32:24.524 D/Compose Focus(12783): Owner FocusChanged(true)
02-19 21:32:24.525 D/Compose Focus(12783): Owner FocusChanged(false)
02-19 21:32:24.525 D/Compose Focus(12783): Owner FocusChanged(true)
02-19 21:32:24.525 D/Compose Focus(12783): Owner FocusChanged(false)
02-19 21:32:24.532 I/org.jellyfin.sdk.api.client.KtorClient(12783): GET https://******:8920/Users/Public
02-19 21:32:24.536 I/org.jellyfin.sdk.api.client.KtorClient(12783): GET https://******:8920/Branding/Configuration
02-19 21:32:24.593 I/AssistStructure(12783): Flattened final assist data: 4224 bytes, containing 1 windows, 36 views
02-19 21:32:24.743 D/ACRA    (12783): onActivityPaused class org.jellyfin.androidtv.ui.startup.StartupActivity
02-19 21:32:25.038 D/FullDetailsFragment(12783): current time 1676838745033 last playback event time 1676838734795 last refresh time 1676838051223
02-19 21:32:25.043 I/FullDetailsFragment(12783): Re-loading after new episode playback
02-19 21:32:25.044 D/AndroidRuntime(12783): Shutting down VM
--------- beginning of crash
02-19 21:32:25.045 E/AndroidRuntime(12783): FATAL EXCEPTION: main
02-19 21:32:25.045 E/AndroidRuntime(12783): Process: org.jellyfin.androidtv, PID: 12783
02-19 21:32:25.045 E/AndroidRuntime(12783): java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.UUID org.jellyfin.sdk.model.api.UserDto.getId()' on a null object reference
02-19 21:32:25.045 E/AndroidRuntime(12783): 	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment.loadItem(FullDetailsFragment.java:409)
02-19 21:32:25.045 E/AndroidRuntime(12783): 	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment.access$500(FullDetailsFragment.java:125)
02-19 21:32:25.045 E/AndroidRuntime(12783): 	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment$3.run(FullDetailsFragment.java:270)
02-19 21:32:25.045 E/AndroidRuntime(12783): 	at android.os.Handler.handleCallback(Handler.java:938)
02-19 21:32:25.045 E/AndroidRuntime(12783): 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-19 21:32:25.045 E/AndroidRuntime(12783): 	at android.os.Looper.loopOnce(Looper.java:201)
02-19 21:32:25.045 E/AndroidRuntime(12783): 	at android.os.Looper.loop(Looper.java:288)
02-19 21:32:25.045 E/AndroidRuntime(12783): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
02-19 21:32:25.045 E/AndroidRuntime(12783): 	at java.lang.reflect.Method.invoke(Native Method)
02-19 21:32:25.045 E/AndroidRuntime(12783): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-19 21:32:25.045 E/AndroidRuntime(12783): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
02-19 21:32:25.046 E/ACRA    (12783): ACRA caught a NullPointerException for org.jellyfin.androidtv
02-19 21:32:25.046 E/ACRA    (12783): java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.UUID org.jellyfin.sdk.model.api.UserDto.getId()' on a null object reference
02-19 21:32:25.046 E/ACRA    (12783): 	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment.loadItem(FullDetailsFragment.java:409)
02-19 21:32:25.046 E/ACRA    (12783): 	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment.access$500(FullDetailsFragment.java:125)
02-19 21:32:25.046 E/ACRA    (12783): 	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment$3.run(FullDetailsFragment.java:270)
02-19 21:32:25.046 E/ACRA    (12783): 	at android.os.Handler.handleCallback(Handler.java:938)
02-19 21:32:25.046 E/ACRA    (12783): 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-19 21:32:25.046 E/ACRA    (12783): 	at android.os.Looper.loopOnce(Looper.java:201)
02-19 21:32:25.046 E/ACRA    (12783): 	at android.os.Looper.loop(Looper.java:288)
02-19 21:32:25.046 E/ACRA    (12783): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
02-19 21:32:25.046 E/ACRA    (12783): 	at java.lang.reflect.Method.invoke(Native Method)
02-19 21:32:25.046 E/ACRA    (12783): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-19 21:32:25.046 E/ACRA    (12783): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
02-19 21:32:25.046 D/ACRA    (12783): Building report
02-19 21:32:25.056 D/ACRA    (12783): Starting collectors with priority FIRST
02-19 21:32:25.061 D/ACRA    (12783): Calling collector org.acra.collector.DropBoxCollector
02-19 21:32:25.062 D/ACRA    (12783): Collector org.acra.collector.DropBoxCollector completed
02-19 21:32:25.063 D/ACRA    (12783): Calling collector org.acra.collector.StacktraceCollector
02-19 21:32:25.064 D/ACRA    (12783): Collector org.acra.collector.StacktraceCollector completed
02-19 21:32:25.065 D/ACRA    (12783): Calling collector org.acra.collector.LogCatCollector
02-19 21:32:25.102 D/ACRA    (12783): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.15.3` (`150399`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"sabrina","BOOTLOADER":"01.01.221215.094359","BRAND":"google","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"sabrina","DISPLAY":"STTE.220920.016.H1.9408258","FINGERPRINT":"google\/sabrina_prod_stable\/sabrina:12\/STTE.220920.016.H1\/9408258:user\/release-keys","HARDWARE":"amlogic","HOST":"abfarm-release-2004-0189","ID":"STTE.220920.016.H1","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Google","MODEL":"Chromecast","ODM_SKU":"DE","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"sabrina_prod_stable","RADIO":"unknown","SKU":"DE","SOC_MANUFACTURER":"Amlogic","SOC_MODEL":"AMLS905D3","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1671101937000,"TYPE":"user","UNKNOWN":"unknown","USER":"android-build","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"9408258","MEDIA_PERFORMANCE_CLASS":0,"PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"12","RELEASE_OR_CODENAME":"12","SDK":"31","SDK_INT":31,"SECURITY_PATCH":"2022-10-01"}}
```

### Application version

0.15.3

### Where did you install the app from?

Google Play

### Device information

Chromecast

### Android version

12

### Jellyfin server version

10.8.9

**Comment by jumoog** [comment]
It happens when I remove a library from the user and start the app again,
