### ISSUE TITLE
crash when stopped from dashboard, when not active

### ISSUE THREAD

**Issue by systemcrash** [jellyfin/jellyfin-androidtv#2653]
### Describe the bug

* Go to jellyfin dashboard
* click stop button on a TV instance (that is no longer playing). 

### Logs

---
client: Jellyfin for Android TV
client_version: 0.15.6
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.fragment.app.FragmentActivity org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.getActivity()' on a null object reference
	at org.jellyfin.androidtv.ui.playback.PlaybackController.endPlayback(PlaybackController.java:1148)
	at org.jellyfin.androidtv.data.eventhandling.SocketHandler$onPlayStateMessage$1.invokeSuspend(SocketHandler.kt:137)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@95bd265, Dispatchers.Main]

```  
***Logcat***: 
```log
04-08 01:18:59.606 I/lyfin.androidt(26059): NativeAlloc concurrent copying GC freed 132342(6388KB) AllocSpace objects, 10(704KB) LOS objects, 49% free, 14MB/28MB, paused 127us total 147.086ms
04-08 01:19:04.917 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:19:04.924 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"f9549bf04580488ea9c978125efc3f54"}
04-08 01:19:34.917 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:19:34.923 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"ca55df7fc0114066bc73ed95ab5b226f"}
04-08 01:20:04.919 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:20:04.926 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"900b84ca4b7440e095aefc78c09645d0"}
04-08 01:20:34.920 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:20:34.936 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"63c5f29085fa484ca268fa2c96354e62"}
04-08 01:21:04.921 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:21:04.926 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"775d0203698f4a17a5b7039a897b88ba"}
04-08 01:21:34.922 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:21:34.930 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"aa626902f5284862ac659ef0bafcab9a"}
04-08 01:22:04.923 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:22:04.932 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"bce39d01e1bf49679d4ae6eb0389fcc7"}
04-08 01:22:17.876 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"LibraryChanged","MessageId":"64a4aab0d5db41f2b218f05384e8f48a","Data":{"FoldersAddedTo":[],"FoldersRemovedFrom":["256d40bebd31895dc3ed97a76dd51b17"],"ItemsAdded":[],"ItemsRemoved":["e5f25d3935892b66cc15b1eedc12877f"],"ItemsUpdated":["7f594e5e8a641da2b3c5cb3684e273b1"],"CollectionFolders":["a656b907eb3a73532e40e44b968d0225","f137a2dd21bbc1b99aa5c0f6bf02a805"],"IsEmpty":false}}
04-08 01:22:17.883 D/SocketHandler(26059): Library changed.
04-08 01:22:17.883 D/SocketHandler(26059): Added 0 items
04-08 01:22:17.883 D/SocketHandler(26059): Removed 1 items
04-08 01:22:17.883 D/SocketHandler(26059): Updated 1 items
04-08 01:22:34.925 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:22:34.932 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"61123f6d3c9849f89b4b2eb3888a22b1"}
04-08 01:23:04.927 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:23:04.936 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"8610fbd09d5c4eb597b75f19556fb16f"}
04-08 01:23:34.928 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:23:34.934 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"bb380ce94ca34a3e992543e6a1d45dc1"}
04-08 01:24:04.930 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:24:04.938 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"ca851aedef9e4ca1b18ad7d8614bb014"}
04-08 01:24:34.932 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:24:34.938 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"544db4fe1e2d41d9ba267bf6bae80c42"}
04-08 01:25:04.932 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:25:04.940 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"10ae8ec4e073422e8dae9613eab2fe00"}
04-08 01:25:21.267 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"LibraryChanged","MessageId":"21dc4218b26b404d9d260065647468bd","Data":{"FoldersAddedTo":[],"FoldersRemovedFrom":["256d40bebd31895dc3ed97a76dd51b17"],"ItemsAdded":[],"ItemsRemoved":["2f95f1ae299d97355a54fcaf9fa07b2b","351df3b39e86671a8a78ab39c2bd5b18"],"ItemsUpdated":["7f594e5e8a641da2b3c5cb3684e273b1"],"CollectionFolders":["a656b907eb3a73532e40e44b968d0225","f137a2dd21bbc1b99aa5c0f6bf02a805"],"IsEmpty":false}}
04-08 01:25:21.271 D/SocketHandler(26059): Library changed.
04-08 01:25:21.271 D/SocketHandler(26059): Added 0 items
04-08 01:25:21.271 D/SocketHandler(26059): Removed 2 items
04-08 01:25:21.271 D/SocketHandler(26059): Updated 1 items
04-08 01:25:34.934 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:25:34.981 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"b0d31b6ae890430a90e7dc0cb1df7533"}
04-08 01:26:04.935 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:26:04.942 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"646f8f1a78314b4dbb16babfae36864f"}
04-08 01:26:34.937 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:26:34.945 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"e53a71dd0db347779d6b1969a180ee0f"}
04-08 01:27:04.938 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:27:04.958 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"5ade3e33457c4bcebbf020fe85136324"}
04-08 01:27:23.832 I/AssistStructure(26059): Flattened final assist data: 19780 bytes, containing 1 windows, 357 views
04-08 01:27:23.959 D/ACRA    (26059): onActivityPaused class org.jellyfin.androidtv.ui.browsing.MainActivity
04-08 01:27:24.745 W/libEGL  (26059): EGLNativeWindowType 0xe3524108 disconnect failed
04-08 01:27:24.756 D/ACRA    (26059): onActivityStopped class org.jellyfin.androidtv.ui.browsing.MainActivity
04-08 01:27:24.778 D/ACRA    (26059): onActivitySaveInstanceState class org.jellyfin.androidtv.ui.browsing.MainActivity
04-08 01:27:34.939 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:27:34.956 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"9d4e2e57ee8944758b8aa8973bbcab84"}
04-08 01:28:04.981 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:28:05.038 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"999b1bef88424503ae2999ebc27d8c0c"}
04-08 01:28:35.021 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:28:35.120 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"71353bf238264682840d81b0cfa36096"}
04-08 01:29:05.061 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:29:05.068 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"409f771bad704dfba55c0c1d082c3915"}
04-08 01:29:35.102 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:29:35.150 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"84187cc38f3d4b1285aa8e29d62b6fbe"}
04-08 01:30:05.142 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:30:05.185 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"bab2ddead17c4859b86f7a8f1a29daf5"}
04-08 01:30:35.185 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:30:35.261 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"a61640ff2e2343e38019a27bb5fbce0b"}
04-08 01:31:05.227 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:31:05.243 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"1025e59c82f941e2a3262b30cc9b3fe7"}
04-08 01:31:35.266 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:31:35.320 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"f2a9f7aa7d114142ab797c68104a883b"}
04-08 01:32:05.307 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:32:05.353 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"ee05dc096a9c40a2b4bc461521a73f1f"}
04-08 01:32:35.346 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:32:35.377 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"af0d72d1a41849d09d351a9b5a99c09f"}
04-08 01:33:05.386 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
04-08 01:33:05.404 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"a1de87f6617444beaa9294a086adef9a"}
04-08 01:33:31.713 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(26059): Receiving (raw) message {"MessageType":"Playstate","MessageId":"57ca5e63e605405d9930643e2a6f0c37","Data":{"Command":"Stop","ControllingUserId":"dda9dd6851bd429f8568423fd036a466"}}
04-08 01:33:31.747 I/SocketHandler$onPlayStateMessage(26059): Received PlayStateMessage with command Stop
04-08 01:33:31.763 E/ACRA    (26059): ACRA caught a NullPointerException for org.jellyfin.androidtv
04-08 01:33:31.763 E/ACRA    (26059): java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.fragment.app.FragmentActivity org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.getActivity()' on a null object reference
04-08 01:33:31.763 E/ACRA    (26059): 	at org.jellyfin.androidtv.ui.playback.PlaybackController.endPlayback(PlaybackController.java:1148)
04-08 01:33:31.763 E/ACRA    (26059): 	at org.jellyfin.androidtv.data.eventhandling.SocketHandler$onPlayStateMessage$1.invokeSuspend(SocketHandler.kt:137)
04-08 01:33:31.763 E/ACRA    (26059): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-08 01:33:31.763 E/ACRA    (26059): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
04-08 01:33:31.763 E/ACRA    (26059): 	at android.os.Handler.handleCallback(Handler.java:883)
04-08 01:33:31.763 E/ACRA    (26059): 	at android.os.Handler.dispatchMessage(Handler.java:100)
04-08 01:33:31.763 E/ACRA    (26059): 	at android.os.Looper.loop(Looper.java:214)
04-08 01:33:31.763 E/ACRA    (26059): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
04-08 01:33:31.763 E/ACRA    (26059): 	at java.lang.reflect.Method.invoke(Native Method)
04-08 01:33:31.763 E/ACRA    (26059): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
04-08 01:33:31.763 E/ACRA    (26059): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
04-08 01:33:31.763 E/ACRA    (26059): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@95bd265, Dispatchers.Main]
04-08 01:33:31.763 D/ACRA    (26059): Building report
04-08 01:33:31.765 D/ACRA    (26059): Starting collectors with priority FIRST
04-08 01:33:31.767 D/ACRA    (26059): Calling collector org.acra.collector.DropBoxCollector
04-08 01:33:31.767 D/ACRA    (26059): Collector org.acra.collector.DropBoxCollector completed
04-08 01:33:31.767 D/ACRA    (26059): Calling collector org.acra.collector.LogCatCollector
04-08 01:33:31.768 D/ACRA    (26059): Calling collector org.acra.collector.StacktraceCollector
04-08 01:33:31.768 D/ACRA    (26059): Collector org.acra.collector.StacktraceCollector completed
04-08 01:33:31.779 D/ACRA    (26059): Retrieving logcat output (buffer:default)...
04-08 01:33:31.814 E/libc    ( 7234): Access denied finding property "persist.vendor.system.svp.dbg.loglevel"

```  

### App information

***App version***: `0.15.6` (`150699`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"mt5895","BOOTLOADER":"unknown","BRAND":"Sony","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"BRAVIA_VH2","DISPLAY":"BRAVIA_VH2_EU-user 10 QTG3.200305.006.S272 664741 release-keys","FINGERPRINT":"Sony\/BRAVIA_VH2_EU\/BRAVIA_VH2:10\/QTG3.200305.006.S272\/664741:user\/release-keys","HARDWARE":"mt5895","HOST":"BuildHost739","ID":"QTG3.200305.006.S272","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Sony","MODEL":"BRAVIA 4K VH2","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"BRAVIA_VH2_EU","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1673511500000,"TYPE":"user","UNKNOWN":"unknown","USER":"root","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","FIRST_SDK_INT":29,"INCREMENTAL":"664741","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"10","RESOURCES_SDK_INT":29,"SDK":"29","SDK_INT":29,"SECURITY_PATCH":"2022-12-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":150699,"VERSION_NAME":"0.15.6"}
```  

### Device information

***Android version***: `10`  
***Device brand***: `Sony`  
***Device product***: `BRAVIA_VH2_EU`  
***Device model***: `BRAVIA 4K VH2`  

### Crash information

***Start time***: `2023-04-07T23:04:28.309+02:00`  
***Crash time***: `2023-04-08T01:33:31.868+02:00`  

### Application version

0.15.6

### Where did you install the app from?

Google Play

### Device information

BRAVIA_VH2_EU

### Android version

10

### Jellyfin server version

10.8.9

**Comment by nielsvanvelzen** [comment]
Thanks for the report! Fixed with the next release.
