### ISSUE TITLE
can't remove emby completely to do reinstall. data remains

### ISSUE THREAD

**Issue by tdasen** [jellyfin/jellyfin-androidtv#2776]
### Describe the bug

1. start app in browser after reinstall
2. 2 installations show up
3. did not ask for new user/password
Note: Emby had been removed and was being replaced by Jellyfin

### Logs

----- First Start log ---------
[2023-05-17 18:30:39.846 -05:00] [INF] [7] Main: Jellyfin version: "10.8.10"
[2023-05-17 18:30:39.865 -05:00] [INF] [7] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, D:\ProgramData\Jellyfin\Server\log]"]
[2023-05-17 18:30:39.869 -05:00] [INF] [7] Main: Arguments: ["D:\Program Files\Jellyfin\Server\jellyfin.dll", "--datadir", "D:\ProgramData\Jellyfin\Server"]
[2023-05-17 18:30:39.872 -05:00] [INF] [7] Main: Operating system: "Windows"
[2023-05-17 18:30:39.873 -05:00] [INF] [7] Main: Architecture: X64
[2023-05-17 18:30:39.875 -05:00] [INF] [7] Main: 64-Bit Process: True
[2023-05-17 18:30:39.876 -05:00] [INF] [7] Main: User Interactive: True
[2023-05-17 18:30:39.877 -05:00] [INF] [7] Main: Processor count: 16
[2023-05-17 18:30:39.878 -05:00] [INF] [7] Main: Program data path: "D:\ProgramData\Jellyfin\Server"
[2023-05-17 18:30:39.879 -05:00] [INF] [7] Main: Web resources path: "D:\Program Files\Jellyfin\Server\jellyfin-web"
[2023-05-17 18:30:39.880 -05:00] [INF] [7] Main: Application directory: "D:\Program Files\Jellyfin\Server\"
[2023-05-17 18:30:40.094 -05:00] [INF] [7] Jellyfin.Server.Migrations.MigrationRunner: Marking following migrations as applied because this is a fresh install: ["CreateNetworkConfiguration"]
[2023-05-17 18:30:40.364 -05:00] [INF] [7] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "D:\ProgramData\Jellyfin\Server\cache"
[2023-05-17 18:30:40.589 -05:00] [INF] [7] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2023-05-17 18:30:42.448 -05:00] [INF] [7] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2023-05-17 18:30:42.450 -05:00] [INF] [7] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2023-05-17 18:30:42.451 -05:00] [INF] [7] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2023-05-17 18:30:42.464 -05:00] [INF] [7] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2023-05-17 18:30:42.465 -05:00] [INF] [7] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2023-05-17 18:30:44.991 -05:00] [INF] [7] Jellyfin.Server.Implementations.JellyfinDbProvider: There are pending EFCore migrations in the database. Applying... (This may take a while, do not stop Jellyfin)
[2023-05-17 18:30:45.989 -05:00] [INF] [7] Jellyfin.Server.Implementations.JellyfinDbProvider: EFCore migrations applied successfully
[2023-05-17 18:30:46.848 -05:00] [INF] [7] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[2023-05-17 18:30:46.850 -05:00] [INF] [7] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "D:\ProgramData\Jellyfin\Server\cache"
[2023-05-17 18:30:46.855 -05:00] [INF] [7] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.8.10.0"
[2023-05-17 18:30:46.857 -05:00] [INF] [7] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.8.10.0"
[2023-05-17 18:30:46.859 -05:00] [INF] [7] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.8.10.0"
[2023-05-17 18:30:46.860 -05:00] [INF] [7] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.8.10.0"
[2023-05-17 18:30:46.862 -05:00] [INF] [7] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.8.10.0"
[2023-05-17 18:30:47.007 -05:00] [INF] [7] Jellyfin.Server.Migrations.MigrationRunner: Marking following migrations as applied because this is a fresh install: ["DisableTranscodingThrottling", "CreateLoggingConfigHeirarchy", "MigrateActivityLogDatabase", "RemoveDuplicateExtras", "MigrateUserDatabase", "MigrateDisplayPreferencesDatabase", "RemoveDownloadImagesInAdvance", "MigrateAuthenticationDatabase"]
[2023-05-17 18:30:47.011 -05:00] [INF] [7] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"AddDefaultPluginRepository"'
[2023-05-17 18:30:47.012 -05:00] [INF] [7] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[2023-05-17 18:30:47.014 -05:00] [INF] [7] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "D:\ProgramData\Jellyfin\Server\cache"
[2023-05-17 18:30:47.015 -05:00] [INF] [7] Jellyfin.Server.Migrations.MigrationRunner: Migration '"AddDefaultPluginRepository"' applied successfully
[2023-05-17 18:30:47.025 -05:00] [INF] [7] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"ReaddDefaultPluginRepository"'
[2023-05-17 18:30:47.026 -05:00] [INF] [7] Jellyfin.Server.Migrations.MigrationRunner: Migration '"ReaddDefaultPluginRepository"' applied successfully
[2023-05-17 18:30:47.032 -05:00] [INF] [7] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"AddPeopleQueryIndex"'
[2023-05-17 18:30:47.034 -05:00] [INF] [7] Jellyfin.Server.Migrations.Routines.AddPeopleQueryIndex: Creating index idx_TypedBaseItemsUserDataKeyType
[2023-05-17 18:30:47.130 -05:00] [INF] [7] Jellyfin.Server.Migrations.Routines.AddPeopleQueryIndex: Creating index idx_PeopleNameListOrder
[2023-05-17 18:30:47.231 -05:00] [INF] [7] Jellyfin.Server.Migrations.MigrationRunner: Migration '"AddPeopleQueryIndex"' applied successfully
[2023-05-17 18:30:47.237 -05:00] [INF] [7] Main: Kestrel listening on "Any IP4 Address"
[2023-05-17 18:30:47.870 -05:00] [INF] [7] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2023-05-17 18:30:47.922 -05:00] [INF] [7] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 2023-05-18 02:00:00.000 -05:00, which is 07:29:12.0772747 from now.
[2023-05-17 18:30:48.064 -05:00] [INF] [7] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "5.1.3"
[2023-05-17 18:30:48.118 -05:00] [INF] [7] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "dca", "flac", "mp3", "truehd"]
[2023-05-17 18:30:48.157 -05:00] [INF] [7] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
[2023-05-17 18:30:48.201 -05:00] [INF] [7] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["deinterlace_qsv", "hwupload_cuda", "hwupload_vaapi", "overlay_opencl", "overlay_qsv", "overlay_cuda", "scale_cuda", "scale_opencl", "scale_qsv", "tonemap_cuda", "tonemap_opencl", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
[2023-05-17 18:30:48.344 -05:00] [WRN] [7] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: "overlay_vaapi" with option "Action to take when encountering EOF from secondary input" is not available
[2023-05-17 18:30:48.372 -05:00] [INF] [7] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "dxva2", "qsv", "d3d11va", "opencl"]
[2023-05-17 18:30:48.493 -05:00] [INF] [7] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: "ffmpeg"
[2023-05-17 18:30:48.495 -05:00] [INF] [7] Emby.Server.Implementations.ApplicationHost: ServerId: "829ddf55ed224c9dbea3d18b19eaf32c"
[2023-05-17 18:30:48.668 -05:00] [INF] [7] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.1666554
[2023-05-17 18:30:48.670 -05:00] [INF] [7] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2023-05-17 18:30:48.943 -05:00] [INF] [7] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.2717726
[2023-05-17 18:30:48.944 -05:00] [INF] [7] Main: Startup complete 0:00:10.2825089
[2023-05-17 18:30:50.938 -05:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: "StartupTrigger" fired for task: "Update Plugins"
[2023-05-17 18:30:50.939 -05:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "PluginUpdateTask"
[2023-05-17 18:30:50.942 -05:00] [INF] [7] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Update Plugins"
[2023-05-17 18:30:51.611 -05:00] [INF] [19] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 0 seconds
[2023-05-17 18:30:51.626 -05:00] [INF] [19] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2023-05-17 18:30:53.989 -05:00] [INF] [4] Emby.Dlna.Main.DlnaEntryPoint: DLNA Session created for "[TV] Samsung 7 Series (65)" - "UN65RU7100FXZA"

-------- Restart Log ----------
[2023-05-17 18:30:43.964 -05:00] [INF] [1] Main: Jellyfin version: "10.8.10"
[2023-05-17 18:30:43.984 -05:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, D:\ProgramData\Jellyfin\Server\log]"]
[2023-05-17 18:30:43.988 -05:00] [INF] [1] Main: Arguments: ["D:\Program Files\Jellyfin\Server\jellyfin.dll", "--datadir", "D:\ProgramData\Jellyfin\Server"]
[2023-05-17 18:30:43.993 -05:00] [INF] [1] Main: Operating system: "Windows"
[2023-05-17 18:30:43.995 -05:00] [INF] [1] Main: Architecture: X64
[2023-05-17 18:30:43.996 -05:00] [INF] [1] Main: 64-Bit Process: True
[2023-05-17 18:30:43.997 -05:00] [INF] [1] Main: User Interactive: True
[2023-05-17 18:30:43.999 -05:00] [INF] [1] Main: Processor count: 16
[2023-05-17 18:30:44.000 -05:00] [INF] [1] Main: Program data path: "D:\ProgramData\Jellyfin\Server"
[2023-05-17 18:30:44.001 -05:00] [INF] [1] Main: Web resources path: "D:\Program Files\Jellyfin\Server\jellyfin-web"
[2023-05-17 18:30:44.002 -05:00] [INF] [1] Main: Application directory: "D:\Program Files\Jellyfin\Server\"
[2023-05-17 18:30:44.077 -05:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Marking following migrations as applied because this is a fresh install: ["CreateNetworkConfiguration"]
[2023-05-17 18:30:44.102 -05:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "D:\ProgramData\Jellyfin\Server\cache"
[2023-05-17 18:30:44.109 -05:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2023-05-17 18:30:44.225 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2023-05-17 18:30:44.226 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2023-05-17 18:30:44.228 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2023-05-17 18:30:44.239 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2023-05-17 18:30:44.240 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2023-05-17 18:30:45.347 -05:00] [INF] [1] Jellyfin.Server.Implementations.JellyfinDbProvider: There are pending EFCore migrations in the database. Applying... (This may take a while, do not stop Jellyfin)
[2023-05-17 18:30:45.914 -05:00] [FTL] [1] Main: Error while starting server.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'table "__EFMigrationsHistory" already exists'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Jellyfin.Server.Implementations.JellyfinDbProvider..ctor(IServiceProvider serviceProvider, IApplicationPaths appPaths, ILogger`1 logger)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Emby.Server.Implementations.ApplicationHost.Resolve[T]()
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2023-05-17 18:30:46.031 -05:00] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[2023-05-17 18:30:46.088 -05:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
[2023-05-17 18:30:46.090 -05:00] [FTL] [1] Main: Unhandled Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.ApplicationHost.DisposeAsyncCore()
   at Emby.Server.Implementations.ApplicationHost.DisposeAsync()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)

### Application version

0.14.0

### Where did you install the app from?

None

### Device information

Windows 10 PC - AMD

### Android version

 Windows 10

### Jellyfin server version

10.8.1

**Comment by tdasen** [comment]
Neither emby or jellyfin uninstalled completely. Both left data that seemed to cause problems. Jellyfin data could not be deleted manually because it would restart on reboot blocking deletion. I managed to change the .exe file to .exex and rebooted. This allowed me to delete the directory. It also seems that jellyfin is leaving database data somewhere. Hope this helps.
