### ISSUE TITLE
Media play crash

### ISSUE THREAD

**Issue by Expired-Cookie** [jellyfin/jellyfin-androidtv#2854]
### Describe the bug

When play on android TV,app crash

### Logs

---
client: Jellyfin for Android TV
client_version: 0.15.6
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.jellyfin.androidtv/org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2433)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5439)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:936)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
	at org.jellyfin.androidtv.ui.playback.PlaybackController.play(PlaybackController.java:537)
	at org.jellyfin.androidtv.ui.playback.PlaybackController.play(PlaybackController.java:445)
	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.onActivityCreated(CustomPlaybackOverlayFragment.java:332)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3137)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:579)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:264)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2985)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2895)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
	at android.app.Activity.performStart(Activity.java:6268)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2396)
	... 9 more

```  
***Logcat***: 
```log
06-24 21:00:12.436 D/AudioManager( 7533): preDispatchKeyEvent 22
06-24 21:00:14.537 D/AudioManager( 7533): preDispatchKeyEvent 21
06-24 21:00:14.655 D/AudioManager( 7533): preDispatchKeyEvent 21
06-24 21:00:15.225 D/AudioManager( 7533): preDispatchKeyEvent 23
06-24 21:00:15.375 D/AudioManager( 7533): preDispatchKeyEvent 23
06-24 21:00:15.382 D/jellyfin-apiclient( 7533): Adding request to queue: http://192.168.88.252:8096/Users/59b3e3f2-85c9-4adf-959f-f5d12d83bd7f/PlayedItems/258d3963970fbebfb5a95f74b8a83d91?format=json
06-24 21:00:15.420 I/jellyfin-apiclient( 7533): Response received from: http://192.168.88.252:8096/Users/59b3e3f2-85c9-4adf-959f-f5d12d83bd7f/PlayedItems/258d3963970fbebfb5a95f74b8a83d91?format=json
06-24 21:00:15.920 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession( 7533): Receiving (raw) message {"MessageType":"UserDataChanged","MessageId":"29e82507acb540e8b206b613aba03ec2","Data":{"UserId":"59b3e3f285c94adf959ff5d12d83bd7f","UserDataList":[{"PlaybackPositionTicks":0,"PlayCount":1,"IsFavorite":false,"LastPlayedDate":"2023-06-24T13:00:15.4917368Z","Played":true,"Key":"258d3963-970f-bebf-b5a9-5f74b8a83d91","ItemId":"258d3963970fbebfb5a95f74b8a83d91"},{"UnplayedItemCount":503,"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"2324fbce-8b2e-36e8-83e8-ecee15f70b2d","ItemId":"2324fbce8b2e36e883e8ecee15f70b2d"}]}}
06-24 21:00:17.568 D/AudioManager( 7533): preDispatchKeyEvent 23
06-24 21:00:17.716 D/AudioManager( 7533): preDispatchKeyEvent 23
06-24 21:00:17.717 D/jellyfin-apiclient( 7533): Adding request to queue: http://192.168.88.252:8096/Users/59b3e3f2-85c9-4adf-959f-f5d12d83bd7f/PlayedItems/258d3963970fbebfb5a95f74b8a83d91?format=json
06-24 21:00:17.753 I/jellyfin-apiclient( 7533): Response received from: http://192.168.88.252:8096/Users/59b3e3f2-85c9-4adf-959f-f5d12d83bd7f/PlayedItems/258d3963970fbebfb5a95f74b8a83d91?format=json
06-24 21:00:18.253 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession( 7533): Receiving (raw) message {"MessageType":"UserDataChanged","MessageId":"ab1e6faddf3047ed8852e88af7d47ae2","Data":{"UserId":"59b3e3f285c94adf959ff5d12d83bd7f","UserDataList":[{"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"258d3963-970f-bebf-b5a9-5f74b8a83d91","ItemId":"258d3963970fbebfb5a95f74b8a83d91"},{"UnplayedItemCount":504,"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"2324fbce-8b2e-36e8-83e8-ecee15f70b2d","ItemId":"2324fbce8b2e36e883e8ecee15f70b2d"}]}}
06-24 21:00:18.527 D/AudioManager( 7533): preDispatchKeyEvent 23
06-24 21:00:18.615 D/AudioManager( 7533): preDispatchKeyEvent 23
06-24 21:00:18.616 D/jellyfin-apiclient( 7533): Adding request to queue: http://192.168.88.252:8096/Users/59b3e3f2-85c9-4adf-959f-f5d12d83bd7f/PlayedItems/258d3963970fbebfb5a95f74b8a83d91?format=json
06-24 21:00:18.646 I/jellyfin-apiclient( 7533): Response received from: http://192.168.88.252:8096/Users/59b3e3f2-85c9-4adf-959f-f5d12d83bd7f/PlayedItems/258d3963970fbebfb5a95f74b8a83d91?format=json
06-24 21:00:19.065 D/AudioManager( 7533): preDispatchKeyEvent 23
06-24 21:00:19.147 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession( 7533): Receiving (raw) message {"MessageType":"UserDataChanged","MessageId":"88c49ea4c2434d59acdfeab91702d058","Data":{"UserId":"59b3e3f285c94adf959ff5d12d83bd7f","UserDataList":[{"PlaybackPositionTicks":0,"PlayCount":1,"IsFavorite":false,"LastPlayedDate":"2023-06-24T13:00:18.7174844Z","Played":true,"Key":"258d3963-970f-bebf-b5a9-5f74b8a83d91","ItemId":"258d3963970fbebfb5a95f74b8a83d91"},{"UnplayedItemCount":503,"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"2324fbce-8b2e-36e8-83e8-ecee15f70b2d","ItemId":"2324fbce8b2e36e883e8ecee15f70b2d"}]}}
06-24 21:00:19.155 D/AudioManager( 7533): preDispatchKeyEvent 23
06-24 21:00:19.156 D/jellyfin-apiclient( 7533): Adding request to queue: http://192.168.88.252:8096/Users/59b3e3f2-85c9-4adf-959f-f5d12d83bd7f/PlayedItems/258d3963970fbebfb5a95f74b8a83d91?format=json
06-24 21:00:19.176 I/jellyfin-apiclient( 7533): Response received from: http://192.168.88.252:8096/Users/59b3e3f2-85c9-4adf-959f-f5d12d83bd7f/PlayedItems/258d3963970fbebfb5a95f74b8a83d91?format=json
06-24 21:00:19.677 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession( 7533): Receiving (raw) message {"MessageType":"UserDataChanged","MessageId":"7c52deca13254cc5be21c0659e0a9f35","Data":{"UserId":"59b3e3f285c94adf959ff5d12d83bd7f","UserDataList":[{"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"258d3963-970f-bebf-b5a9-5f74b8a83d91","ItemId":"258d3963970fbebfb5a95f74b8a83d91"},{"UnplayedItemCount":504,"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"2324fbce-8b2e-36e8-83e8-ecee15f70b2d","ItemId":"2324fbce8b2e36e883e8ecee15f70b2d"}]}}
06-24 21:00:19.876 D/AudioManager( 7533): preDispatchKeyEvent 22
06-24 21:00:19.965 D/AudioManager( 7533): preDispatchKeyEvent 22
06-24 21:00:20.326 D/AudioManager( 7533): preDispatchKeyEvent 22
06-24 21:00:20.476 D/AudioManager( 7533): preDispatchKeyEvent 22
06-24 21:00:21.046 D/AudioManager( 7533): preDispatchKeyEvent 22
06-24 21:00:21.165 D/AudioManager( 7533): preDispatchKeyEvent 22
06-24 21:00:21.766 D/AudioManager( 7533): preDispatchKeyEvent 19
06-24 21:00:21.885 D/AudioManager( 7533): preDispatchKeyEvent 19
06-24 21:00:22.516 D/AudioManager( 7533): preDispatchKeyEvent 20
06-24 21:00:22.665 D/AudioManager( 7533): preDispatchKeyEvent 20
06-24 21:00:23.866 D/AudioManager( 7533): preDispatchKeyEvent 22
06-24 21:00:24.045 D/AudioManager( 7533): preDispatchKeyEvent 22
06-24 21:00:24.285 D/AudioManager( 7533): preDispatchKeyEvent 22
06-24 21:00:24.437 D/AudioManager( 7533): preDispatchKeyEvent 22
06-24 21:00:24.826 D/AudioManager( 7533): preDispatchKeyEvent 22
06-24 21:00:24.916 D/AudioManager( 7533): preDispatchKeyEvent 22
06-24 21:00:25.186 D/AudioManager( 7533): preDispatchKeyEvent 22
06-24 21:00:25.336 D/AudioManager( 7533): preDispatchKeyEvent 22
06-24 21:00:25.546 D/AudioManager( 7533): preDispatchKeyEvent 22
06-24 21:00:25.666 D/AudioManager( 7533): preDispatchKeyEvent 22
06-24 21:00:27.496 D/AudioManager( 7533): preDispatchKeyEvent 21
06-24 21:00:27.587 D/AudioManager( 7533): preDispatchKeyEvent 21
06-24 21:00:28.486 D/AudioManager( 7533): preDispatchKeyEvent 22
06-24 21:00:28.636 D/AudioManager( 7533): preDispatchKeyEvent 22
06-24 21:00:28.935 D/AudioManager( 7533): preDispatchKeyEvent 23
06-24 21:00:29.116 D/AudioManager( 7533): preDispatchKeyEvent 23
06-24 21:00:29.117 D/jellyfin-apiclient( 7533): Adding request to queue: http://192.168.88.252:8096/Users/59b3e3f2-85c9-4adf-959f-f5d12d83bd7f/Items/258d3963-970f-bebf-b5a9-5f74b8a83d91?format=json
06-24 21:00:29.130 I/jellyfin-apiclient( 7533): Response received from: http://192.168.88.252:8096/Users/59b3e3f2-85c9-4adf-959f-f5d12d83bd7f/Items/258d3963-970f-bebf-b5a9-5f74b8a83d91?format=json
06-24 21:00:29.136 D/NavigationRepositoryImp( 7533): Navigating to Activity(activity=class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity (Kotlin reflection is not available), extras=Bundle[{Position=1500000}])
06-24 21:00:29.145 D/NavigationRepositoryImp( 7533): Navigating to nothing
06-24 21:00:29.147 D/ACRA    ( 7533): onActivityPaused class org.jellyfin.androidtv.ui.browsing.MainActivity
06-24 21:00:29.304 I/ActivityThemeExtensions( 7533): Applying theme DARK
06-24 21:00:29.304 D/ACRA    ( 7533): onActivityCreated class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
06-24 21:00:29.318 D/ACRA    ( 7533): onActivityStarted class org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity
06-24 21:00:29.514 I/ExoPlayerImpl( 7533): Init b5609c2 [ExoPlayerLib/2.18.4] [pulpfiction, MiTV4, xiaomi, 23]
06-24 21:00:29.552 I/DefaultRenderersFactory( 7533): Loaded FfmpegAudioRenderer.
06-24 21:00:29.604 D/PlaybackController( 7533): Play called from state: IDLE with pos: 1500000 and sub index: null
06-24 21:00:29.606 D/AndroidRuntime( 7533): Shutting down VM
06-24 21:00:29.607 E/ACRA    ( 7533): ACRA caught a RuntimeException for org.jellyfin.androidtv
06-24 21:00:29.607 E/ACRA    ( 7533): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.jellyfin.androidtv/org.jellyfin.androidtv.ui.playback.PlaybackOverlayActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
06-24 21:00:29.607 E/ACRA    ( 7533): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2433)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at android.os.Looper.loop(Looper.java:148)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at android.app.ActivityThread.main(ActivityThread.java:5439)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at java.lang.reflect.Method.invoke(Native Method)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:936)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
06-24 21:00:29.607 E/ACRA    ( 7533): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
06-24 21:00:29.607 E/ACRA    ( 7533): 	at org.jellyfin.androidtv.ui.playback.PlaybackController.play(PlaybackController.java:537)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at org.jellyfin.androidtv.ui.playback.PlaybackController.play(PlaybackController.java:445)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.onActivityCreated(CustomPlaybackOverlayFragment.java:332)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3137)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:579)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:264)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2985)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2895)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at android.app.Activity.performStart(Activity.java:6268)
06-24 21:00:29.607 E/ACRA    ( 7533): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2396)
06-24 21:00:29.607 E/ACRA    ( 7533): 	... 9 more
06-24 21:00:29.607 D/ACRA    ( 7533): Building report
06-24 21:00:29.608 D/ACRA    ( 7533): Starting collectors with priority FIRST
06-24 21:00:29.610 D/ACRA    ( 7533): Calling collector org.acra.collector.DropBoxCollector
06-24 21:00:29.610 D/ACRA    ( 7533): Collector org.acra.collector.DropBoxCollector completed
06-24 21:00:29.611 D/ACRA    ( 7533): Calling collector org.acra.collector.LogCatCollector
06-24 21:00:29.612 D/ACRA    ( 7533): Calling collector org.acra.collector.StacktraceCollector
06-24 21:00:29.613 D/ACRA    ( 7533): Collector org.acra.collector.StacktraceCollector completed
06-24 21:00:29.648 D/ACRA    ( 7533): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.15.6` (`150699`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"pulpfiction","BOOTLOADER":"unknown","BRAND":"Xiaomi","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"pulpfiction","DISPLAY":"9.1.8.2318","FINGERPRINT":"Xiaomi\/pulpfiction\/pulpfiction:6.0.1\/MHC19J\/2318:user\/release-keys","HARDWARE":"amlogic","HOST":"c3-mitv-bsp-build01.bj","ID":"MHC19J","IS_DEBUGGABLE":false,"MANUFACTURER":"xiaomi","MODEL":"MiTV4","PRODUCT":"pulpfiction","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1546921447000,"TYPE":"user","UNKNOWN":"unknown","USER":"jenkins","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"2318","PREVIEW_SDK_INT":0,"RELEASE":"6.0.1","RESOURCES_SDK_INT":23,"SDK":"23","SDK_INT":23,"SECURITY_PATCH":"2017-04-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":150699,"VERSION_NAME":"0.15.6"}
```  

### Device information

***Android version***: `6.0.1`  
***Device brand***: `Xiaomi`  
***Device product***: `pulpfiction`  
***Device model***: `MiTV4`  

### Crash information

***Start time***: `2023-06-24T21:00:02.159+08:00`  
***Crash time***: `2023-06-24T21:00:29.704+08:00`  

### FFmpeg logs

```shell
in docker ,do not know path
```

### Application version

0.15.6

### Device information

Xiaomi TV 

### Android version

6.0.1

### Jellyfin server version

10.8.9

**Comment by nielsvanvelzen** [comment]
We do not support older releases. Make sure to update Jellyfin to 10.8.10 and the app to 0.15.10 first.
