### ISSUE TITLE
Jellyfin on FireTV crashes after selecting user

### ISSUE THREAD

**Issue by letrad** [jellyfin/jellyfin-androidtv#2863]
### Describe the bug

1. Open Jellyfin on Firestick
2. Select Server
3. Select User

Then it just instantly crashes and says a report was sent to the server

### Logs

***Stack Trace***: 
```log
kotlinx.serialization.MissingFieldException: Field 'MessageId' is required for type with serial name 'org.jellyfin.sdk.model.socket.RawIncomingSocketMessage', but it was missing at path: $
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:90)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:95)
	at org.jellyfin.sdk.api.client.util.ApiSerializer.decodeSocketMessage(ApiSerializer.kt:108)
	at org.jellyfin.sdk.api.sockets.SocketInstance.forwardMessage(SocketInstance.kt:280)
	at org.jellyfin.sdk.api.sockets.SocketInstance.access$forwardMessage(SocketInstance.kt:35)
	at org.jellyfin.sdk.api.sockets.SocketInstance$connectAndBind$2.invokeSuspend(SocketInstance.kt:220)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@de337a2, Dispatchers.Default]
Caused by: kotlinx.serialization.MissingFieldException: Field 'MessageId' is required for type with serial name 'org.jellyfin.sdk.model.socket.RawIncomingSocketMessage', but it was missing
	at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
	at org.jellyfin.sdk.model.socket.RawIncomingSocketMessage.<init>(RawIncomingSocketMessage.kt:13)
	at org.jellyfin.sdk.model.socket.RawIncomingSocketMessage$$serializer.deserialize(RawIncomingSocketMessage.kt:13)
	at org.jellyfin.sdk.model.socket.RawIncomingSocketMessage$$serializer.deserialize(RawIncomingSocketMessage.kt:13)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
	... 11 more

```  
***Logcat***: 
```log
07-01 09:58:10.814 W/ViewRootImpl[StartupActivity](28962): Dropping event due to no window focus: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_DPAD_CENTER, scanCode=96, metaState=0, flags=0x8, repeatCount=0, eventTime=1512984358, downTime=1512984358, deviceId=54, source=0x301 }
07-01 09:58:10.815 W/ViewRootImpl[StartupActivity](28962): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=96, metaState=0, flags=0x28, repeatCount=0, eventTime=1512984478, downTime=1512984358, deviceId=54, source=0x301 }
07-01 09:58:10.815 W/ViewRootImpl[StartupActivity](28962): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=96, metaState=0, flags=0x28, repeatCount=0, eventTime=1512984478, downTime=1512984358, deviceId=54, source=0x301 }
07-01 09:58:10.815 W/ViewRootImpl[StartupActivity](28962): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=96, metaState=0, flags=0x28, repeatCount=0, eventTime=1512984478, downTime=1512984358, deviceId=54, source=0x301 }
07-01 09:58:10.815 W/ViewRootImpl[StartupActivity](28962): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=96, metaState=0, flags=0x28, repeatCount=0, eventTime=1512984478, downTime=1512984358, deviceId=54, source=0x301 }
07-01 09:58:10.815 W/ViewRootImpl[StartupActivity](28962): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=96, metaState=0, flags=0x28, repeatCount=0, eventTime=1512984478, downTime=1512984358, deviceId=54, source=0x301 }
07-01 09:58:10.815 W/ViewRootImpl[StartupActivity](28962): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=96, metaState=0, flags=0x28, repeatCount=0, eventTime=1512984478, downTime=1512984358, deviceId=54, source=0x301 }
07-01 09:58:10.815 W/ViewRootImpl[StartupActivity](28962): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=96, metaState=0, flags=0x28, repeatCount=0, eventTime=1512984478, downTime=1512984358, deviceId=54, source=0x301 }
07-01 09:58:10.815 W/ViewRootImpl[StartupActivity](28962): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=96, metaState=0, flags=0x28, repeatCount=0, eventTime=1512984478, downTime=1512984358, deviceId=54, source=0x301 }
07-01 09:58:10.815 W/ViewRootImpl[StartupActivity](28962): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=96, metaState=0, flags=0x28, repeatCount=0, eventTime=1512984478, downTime=1512984358, deviceId=54, source=0x301 }
07-01 09:58:10.890 W/ViewRootImpl[StartupActivity](28962): Dropping event due to no window focus: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_DPAD_CENTER, scanCode=96, metaState=0, flags=0x8, repeatCount=0, eventTime=1512984558, downTime=1512984558, deviceId=54, source=0x301 }
07-01 09:58:10.895 W/ViewRootImpl[StartupActivity](28962): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=96, metaState=0, flags=0x28, repeatCount=0, eventTime=1512984678, downTime=1512984558, deviceId=54, source=0x301 }
07-01 09:58:10.895 W/ViewRootImpl[StartupActivity](28962): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=96, metaState=0, flags=0x28, repeatCount=0, eventTime=1512984678, downTime=1512984558, deviceId=54, source=0x301 }
07-01 09:58:10.895 W/ViewRootImpl[StartupActivity](28962): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=96, metaState=0, flags=0x28, repeatCount=0, eventTime=1512984678, downTime=1512984558, deviceId=54, source=0x301 }
07-01 09:58:10.895 W/ViewRootImpl[StartupActivity](28962): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=96, metaState=0, flags=0x28, repeatCount=0, eventTime=1512984678, downTime=1512984558, deviceId=54, source=0x301 }
07-01 09:58:10.895 W/ViewRootImpl[StartupActivity](28962): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=96, metaState=0, flags=0x28, repeatCount=0, eventTime=1512984678, downTime=1512984558, deviceId=54, source=0x301 }
07-01 09:58:10.895 W/ViewRootImpl[StartupActivity](28962): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=96, metaState=0, flags=0x28, repeatCount=0, eventTime=1512984678, downTime=1512984558, deviceId=54, source=0x301 }
07-01 09:58:10.895 W/ViewRootImpl[StartupActivity](28962): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=96, metaState=0, flags=0x28, repeatCount=0, eventTime=1512984678, downTime=1512984558, deviceId=54, source=0x301 }
07-01 09:58:10.895 W/ViewRootImpl[StartupActivity](28962): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=96, metaState=0, flags=0x28, repeatCount=0, eventTime=1512984678, downTime=1512984558, deviceId=54, source=0x301 }
07-01 09:58:10.895 W/ViewRootImpl[StartupActivity](28962): Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=96, metaState=0, flags=0x28, repeatCount=0, eventTime=1512984678, downTime=1512984558, deviceId=54, source=0x301 }
07-01 09:58:17.385 I/FrameworkJumpTable(29071): Successfully loaded all classes
07-01 09:58:17.398 I/FrameworkJumpTable(29071): Successfully loaded all methods
07-01 09:58:17.400 I/FrameworkJumpTable(29071): Successfully loaded all fields
07-01 09:58:17.400 I/FrameworkJumpTable(29071): Successfully loaded all constructors
07-01 09:59:13.449 I/FrameworkJumpTable(29293): Successfully loaded all classes
07-01 09:59:13.462 I/FrameworkJumpTable(29293): Successfully loaded all methods
07-01 09:59:13.464 I/FrameworkJumpTable(29293): Successfully loaded all fields
07-01 09:59:13.464 I/FrameworkJumpTable(29293): Successfully loaded all constructors
07-01 09:59:41.775 I/FrameworkJumpTable(29512): Successfully loaded all classes
07-01 09:59:41.787 I/FrameworkJumpTable(29512): Successfully loaded all methods
07-01 09:59:41.789 I/FrameworkJumpTable(29512): Successfully loaded all fields
07-01 09:59:41.789 I/FrameworkJumpTable(29512): Successfully loaded all constructors
07-01 09:59:49.014 I/FrameworkJumpTable(29630): Successfully loaded all classes
07-01 09:59:49.027 I/FrameworkJumpTable(29630): Successfully loaded all methods
07-01 09:59:49.029 I/FrameworkJumpTable(29630): Successfully loaded all fields
07-01 09:59:49.029 I/FrameworkJumpTable(29630): Successfully loaded all constructors
07-01 10:00:04.999 I/FrameworkJumpTable(29751): Successfully loaded all classes
07-01 10:00:05.012 I/FrameworkJumpTable(29751): Successfully loaded all methods
07-01 10:00:05.014 I/FrameworkJumpTable(29751): Successfully loaded all fields
07-01 10:00:05.014 I/FrameworkJumpTable(29751): Successfully loaded all constructors
07-01 10:00:57.526 I/FrameworkJumpTable(29891): Successfully loaded all classes
07-01 10:00:57.539 I/FrameworkJumpTable(29891): Successfully loaded all methods
07-01 10:00:57.540 I/FrameworkJumpTable(29891): Successfully loaded all fields
07-01 10:00:57.540 I/FrameworkJumpTable(29891): Successfully loaded all constructors
07-01 11:01:24.230 I/FrameworkJumpTable( 4445): Successfully loaded all classes
07-01 11:01:24.243 I/FrameworkJumpTable( 4445): Successfully loaded all methods
07-01 11:01:24.245 I/FrameworkJumpTable( 4445): Successfully loaded all fields
07-01 11:01:24.245 I/FrameworkJumpTable( 4445): Successfully loaded all constructors
--------- beginning of main
07-01 12:43:25.467 I/MigrationContext( 4445): Requested migration from 6 to 6. Found 3 migrations in total.
07-01 12:43:25.481 I/ActivityThemeExtensions( 4445): Applying theme MUTED_PURPLE
07-01 12:43:25.540 I/BackgroundService( 4445): Adding BackgroundServiceFragment to activity
07-01 12:43:25.573 I/PerfStatsManager( 4445): start attempting to update service remote
07-01 12:43:25.582 I/ProcessLifecycleInitial( 4445): Process lifecycle started
07-01 12:43:25.639 E/MTK_GRALLOC( 4445): Ref log out of bound
07-01 12:43:25.778 I/OpenGLRenderer( 4445): Initialized EGL, version 1.4
07-01 12:43:25.999 I/org.jellyfin.sdk.api.client.KtorClient( 4445): GET http://192.168.0.66/Users/Public
07-01 12:43:26.014 W/art     ( 4445): Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
07-01 12:43:26.060 I/org.jellyfin.sdk.api.client.KtorClient( 4445): GET http://192.168.0.66/Users/Public
07-01 12:43:26.063 I/org.jellyfin.sdk.api.client.KtorClient( 4445): GET http://192.168.0.66/Branding/Configuration
07-01 12:43:26.134 W/OpenGLRenderer( 4445): Points are too far apart 4.000003
07-01 12:43:26.286 I/art     ( 4445): Background partial concurrent mark sweep GC freed 12564(581KB) AllocSpace objects, 3(3MB) LOS objects, 40% free, 5MB/8MB, paused 1.620ms total 101.031ms
07-01 12:43:26.351 I/org.jellyfin.sdk.api.client.KtorClient( 4445): GET http://192.168.0.66/System/Info/Public
07-01 12:43:27.018 I/org.jellyfin.sdk.api.client.KtorClient( 4445): GET http://192.168.0.66/Users/Me
07-01 12:43:27.587 I/org.jellyfin.sdk.api.client.KtorClient( 4445): GET http://192.168.0.66/DisplayPreferences/livetv?userId=801b31a5-97e6-4551-88d2-775efb72fe21&client=jellyfin-androidtv
07-01 12:43:27.681 I/org.jellyfin.sdk.api.client.KtorClient( 4445): GET http://192.168.0.66/DisplayPreferences/usersettings?userId=801b31a5-97e6-4551-88d2-775efb72fe21&client=emby
07-01 12:43:27.701 I/StartupActivity$onPermi( 4445): Found a session in the session repository, waiting for the currentUser in the application class.
07-01 12:43:27.703 I/StartupActivity$onPermi( 4445): CurrentUser changed to 801b31a5-97e6-4551-88d2-775efb72fe21 while waiting for startup.
07-01 12:43:27.722 I/org.jellyfin.sdk.api.client.KtorClient( 4445): GET http://192.168.0.66/Users/Me
07-01 12:43:27.728 I/org.jellyfin.sdk.api.sockets.SocketInstance( 4445): Reconnecting
07-01 12:43:27.740 I/org.jellyfin.sdk.api.client.KtorClient( 4445): POST http://192.168.0.66/Sessions/Capabilities?playableMediaTypes=Video&playableMediaTypes=Audio&supportedCommands=DisplayMessage&supportedCommands=SendString&supportedCommands=DisplayContent&supportsMediaControl=true&supportsSync=false&supportsPersistentIdentifier=true
07-01 12:43:27.769 I/org.jellyfin.sdk.api.client.KtorClient( 4445): GET http://192.168.0.66/Playback/BitrateTest?size=4000000
07-01 12:43:27.797 I/WM-WorkerWrapper( 4445): Worker result FAILURE for Work [ id=5ad77a69-c56c-4f2e-b462-41dfb2a5d792, tags={ org.jellyfin.androidtv.integration.LeanbackChannelWorker } ]
07-01 12:43:27.883 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession( 4445): WebSocket has opened
07-01 12:43:28.421 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession( 4445): Receiving (raw) message {"Data":60,"MessageType":"ForceKeepAlive"}
07-01 12:43:28.462 I/ActivityThemeExtensions( 4445): Applying theme MUTED_PURPLE
07-01 12:43:28.467 E/ACRA    ( 4445): ACRA caught a MissingFieldException for org.jellyfin.androidtv
07-01 12:43:28.467 E/ACRA    ( 4445): kotlinx.serialization.MissingFieldException: Field 'MessageId' is required for type with serial name 'org.jellyfin.sdk.model.socket.RawIncomingSocketMessage', but it was missing at path: $
07-01 12:43:28.467 E/ACRA    ( 4445): 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:90)
07-01 12:43:28.467 E/ACRA    ( 4445): 	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:95)
07-01 12:43:28.467 E/ACRA    ( 4445): 	at org.jellyfin.sdk.api.client.util.ApiSerializer.decodeSocketMessage(ApiSerializer.kt:108)
07-01 12:43:28.467 E/ACRA    ( 4445): 	at org.jellyfin.sdk.api.sockets.SocketInstance.forwardMessage(SocketInstance.kt:280)
07-01 12:43:28.467 E/ACRA    ( 4445): 	at org.jellyfin.sdk.api.sockets.SocketInstance.access$forwardMessage(SocketInstance.kt:35)
07-01 12:43:28.467 E/ACRA    ( 4445): 	at org.jellyfin.sdk.api.sockets.SocketInstance$connectAndBind$2.invokeSuspend(SocketInstance.kt:220)
07-01 12:43:28.467 E/ACRA    ( 4445): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07-01 12:43:28.467 E/ACRA    ( 4445): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
07-01 12:43:28.467 E/ACRA    ( 4445): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
07-01 12:43:28.467 E/ACRA    ( 4445): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
07-01 12:43:28.467 E/ACRA    ( 4445): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
07-01 12:43:28.467 E/ACRA    ( 4445): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
07-01 12:43:28.467 E/ACRA    ( 4445): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@de337a2, Dispatchers.Default]
07-01 12:43:28.467 E/ACRA    ( 4445): Caused by: kotlinx.serialization.MissingFieldException: Field 'MessageId' is required for type with serial name 'org.jellyfin.sdk.model.socket.RawIncomingSocketMessage', but it was missing
07-01 12:43:28.467 E/ACRA    ( 4445): 	at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
07-01 12:43:28.467 E/ACRA    ( 4445): 	at org.jellyfin.sdk.model.socket.RawIncomingSocketMessage.<init>(RawIncomingSocketMessage.kt:13)
07-01 12:43:28.467 E/ACRA    ( 4445): 	at org.jellyfin.sdk.model.socket.RawIncomingSocketMessage$$serializer.deserialize(RawIncomingSocketMessage.kt:13)
07-01 12:43:28.467 E/ACRA    ( 4445): 	at org.jellyfin.sdk.model.socket.RawIncomingSocketMessage$$serializer.deserialize(RawIncomingSocketMessage.kt:13)
07-01 12:43:28.467 E/ACRA    ( 4445): 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
07-01 12:43:28.467 E/ACRA    ( 4445): 	... 11 more
07-01 12:43:28.477 I/BackgroundService( 4445): Adding BackgroundServiceFragment to activity

```  

### App information

***App version***: `0.15.10` (`151099`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"mantis","BOOTLOADER":"unknown","BRAND":"Amazon","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"mantis","DISPLAY":"NS6297","FINGERPRINT":"Amazon\/mantis\/mantis:6.0\/NS6297\/4655N:user\/amz-p,release-keys","HARDWARE":"mt8695","HOST":"i3-ri-14-use1a-b-16-04-fos-43","ID":"NS6297","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Amazon","MODEL":"AFTMM","PERMISSIONS_REVIEW_REQUIRED":false,"PRODUCT":"mantis","RADIO":"unknown","REQ_BATTERY_LEVEL":0.3,"SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"amz-p,release-keys","TIME":1685652540000,"TYPE":"user","UNKNOWN":"unknown","USER":"build","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"NHG47K","CODENAME":"REL","INCREMENTAL":"0009161551748","PREVIEW_SDK_INT":0,"RELEASE":"7.1.2","RESOURCES_SDK_INT":25,"SDK":"25","SDK_INT":25,"SECURITY_PATCH":"2022-01-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":151099,"VERSION_NAME":"0.15.10"}
```  

### Device information

***Android version***: `7.1.2`  
***Device brand***: `Amazon`  
***Device product***: `mantis`  
***Device model***: `AFTMM`  

### Crash information

***Start time***: `2023-07-01T11:01:24.184+10:00`  
***Crash time***: `2023-07-01T12:43:28.523+10:00`  

### Application version

0.15.10

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon FireTV Stick 4K

### Android version

7.1.2

### Jellyfin server version

10.9.0

**Comment by nielsvanvelzen** [comment]
We're still working on some changes for 10.9 and right now the client is not compatible yet. Use Jellyfin 10.8 for now.

**Comment by SigHunter** [comment]
This regularly happens to me too, with server version 10.8.10. are you sure it's because of 10.9? ATV version 0.15.10, also was on .9. On fire tv stick 4k and nv shield pro

**Comment by letrad** [comment]
@SigHunter, in my case, this was purely because I was on an unstable server version.

**Comment by alexdelprete** [comment]
> We're still working on some changes for 10.9 and right now the client is not compatible yet. Use Jellyfin 10.8 for now.

Is there a way to go back to 10.8 stable? I tried but at startup there's an error regarding the database schema: `SQLite Error 1: 'no such column: u.EasyPassword'`

What can I do?

**Comment by nielsvanvelzen** [comment]
You cannot downgrade from 10.9->10.8 without restoring a backup. Right now the WebSocket messages between 10.8 and 10.9 are incompatible so it's almost guaranteed to crash the application once signed in (which is on startup with auto login enabled).

**Comment by alexdelprete** [comment]
Ok, I will have to wait 'til the client supports the new websocket message then.

Thanks for the answer.

**Comment by nielsvanvelzen** [comment]
In this case the issue is with the server, it's tracked in jellyfin/jellyfin#9934 and should be fixed soon.

**Comment by alexdelprete** [comment]
I'll subscribe to that issue and then when ready, install the latest unstable server version that contains the fix. Thanks.

**Comment by alexdelprete** [comment]
> In this case the issue is with the server, it's tracked in [jellyfin/jellyfin#9934](https://github.com/jellyfin/jellyfin/issues/9934) and should be fixed soon.

can you confirm this has been fixed with this PR? https://github.com/jellyfin/jellyfin/pull/9948
