### ISSUE TITLE
[v0.16.0-beta.1] Crash while searching

### ISSUE THREAD

**Issue by VampiricAlien** [jellyfin/jellyfin-androidtv#2930]
### Describe the bug

Searching crashes the app?

### Logs

---
client: Jellyfin for Android TV
client_version: 0.16.0-beta.1
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.jellyfin.sdk.model.api.LocationType.ordinal()' on a null object reference
	at org.jellyfin.androidtv.ui.presentation.CardPresenter$ViewHolder.setItem(CardPresenter.java:257)
	at org.jellyfin.androidtv.ui.presentation.CardPresenter.onBindViewHolder(CardPresenter.java:355)
	at androidx.leanback.widget.Presenter.onBindViewHolder(Presenter.java:140)
	at androidx.leanback.widget.ItemBridgeAdapter.onBindViewHolder(ItemBridgeAdapter.java:422)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7847)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6646)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6917)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
	at androidx.leanback.widget.GridLayoutManager.measureScrapChild(GridLayoutManager.java:1318)
	at androidx.leanback.widget.GridLayoutManager.processRowSizeSecondary(GridLayoutManager.java:1402)
	at androidx.leanback.widget.GridLayoutManager.onMeasure(GridLayoutManager.java:1508)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:4078)
	at android.view.View.measure(View.java:25490)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25490)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25490)
	at androidx.leanback.widget.GridLayoutManager.measureChild(GridLayoutManager.java:1600)
	at androidx.leanback.widget.GridLayoutManager$2.createItem(GridLayoutManager.java:1702)
	at androidx.leanback.widget.SingleRow.appendVisibleItems(SingleRow.java:113)
	at androidx.leanback.widget.Grid.appendVisibleItems(Grid.java:397)
	at androidx.leanback.widget.GridLayoutManager.appendVisibleItems(GridLayoutManager.java:1965)
	at androidx.leanback.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:2318)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2106)
	at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:468)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:727)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```  
***Logcat***: 
```log
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at org.jellyfin.androidtv.ui.presentation.CardPresenter.onBindViewHolder(CardPresenter.java:355)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at androidx.leanback.widget.Presenter.onBindViewHolder(Presenter.java:140)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at androidx.leanback.widget.ItemBridgeAdapter.onBindViewHolder(ItemBridgeAdapter.java:422)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7847)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6646)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6917)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at androidx.leanback.widget.GridLayoutManager.measureScrapChild(GridLayoutManager.java:1318)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at androidx.leanback.widget.GridLayoutManager.processRowSizeSecondary(GridLayoutManager.java:1402)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at androidx.leanback.widget.GridLayoutManager.onMeasure(GridLayoutManager.java:1508)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:4078)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at android.view.View.measure(View.java:25490)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at android.view.View.measure(View.java:25490)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at android.view.View.measure(View.java:25490)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at androidx.leanback.widget.GridLayoutManager.measureChild(GridLayoutManager.java:1600)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at androidx.leanback.widget.GridLayoutManager$2.createItem(GridLayoutManager.java:1702)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at androidx.leanback.widget.SingleRow.appendVisibleItems(SingleRow.java:113)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at androidx.leanback.widget.Grid.appendVisibleItems(Grid.java:397)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at androidx.leanback.widget.GridLayoutManager.appendVisibleItems(GridLayoutManager.java:1965)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at androidx.leanback.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:2318)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2106)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:468)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at android.view.Choreographer.doFrame(Choreographer.java:727)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at android.os.Handler.handleCallback(Handler.java:938)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at android.os.Looper.loop(Looper.java:223)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at android.app.ActivityThread.main(ActivityThread.java:7668)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at java.lang.reflect.Method.invoke(Native Method)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
07-31 11:20:55.800 E/AndroidRuntime(10153): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
07-31 11:20:55.801 E/ACRA    (10153): ACRA caught a NullPointerException for org.jellyfin.androidtv.debug
07-31 11:20:55.801 E/ACRA    (10153): java.lang.NullPointerException: Attempt to invoke virtual method 'int org.jellyfin.sdk.model.api.LocationType.ordinal()' on a null object reference
07-31 11:20:55.801 E/ACRA    (10153): 	at org.jellyfin.androidtv.ui.presentation.CardPresenter$ViewHolder.setItem(CardPresenter.java:257)
07-31 11:20:55.801 E/ACRA    (10153): 	at org.jellyfin.androidtv.ui.presentation.CardPresenter.onBindViewHolder(CardPresenter.java:355)
07-31 11:20:55.801 E/ACRA    (10153): 	at androidx.leanback.widget.Presenter.onBindViewHolder(Presenter.java:140)
07-31 11:20:55.801 E/ACRA    (10153): 	at androidx.leanback.widget.ItemBridgeAdapter.onBindViewHolder(ItemBridgeAdapter.java:422)
07-31 11:20:55.801 E/ACRA    (10153): 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7847)
07-31 11:20:55.801 E/ACRA    (10153): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6646)
07-31 11:20:55.801 E/ACRA    (10153): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6917)
07-31 11:20:55.801 E/ACRA    (10153): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
07-31 11:20:55.801 E/ACRA    (10153): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
07-31 11:20:55.801 E/ACRA    (10153): 	at androidx.leanback.widget.GridLayoutManager.measureScrapChild(GridLayoutManager.java:1318)
07-31 11:20:55.801 E/ACRA    (10153): 	at androidx.leanback.widget.GridLayoutManager.processRowSizeSecondary(GridLayoutManager.java:1402)
07-31 11:20:55.801 E/ACRA    (10153): 	at androidx.leanback.widget.GridLayoutManager.onMeasure(GridLayoutManager.java:1508)
07-31 11:20:55.801 E/ACRA    (10153): 	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:4078)
07-31 11:20:55.801 E/ACRA    (10153): 	at android.view.View.measure(View.java:25490)
07-31 11:20:55.801 E/ACRA    (10153): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
07-31 11:20:55.801 E/ACRA    (10153): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
07-31 11:20:55.801 E/ACRA    (10153): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
07-31 11:20:55.801 E/ACRA    (10153): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
07-31 11:20:55.801 E/ACRA    (10153): 	at android.view.View.measure(View.java:25490)
07-31 11:20:55.801 E/ACRA    (10153): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
07-31 11:20:55.801 E/ACRA    (10153): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
07-31 11:20:55.801 E/ACRA    (10153): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
07-31 11:20:55.801 E/ACRA    (10153): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
07-31 11:20:55.801 E/ACRA    (10153): 	at android.view.View.measure(View.java:25490)
07-31 11:20:55.801 E/ACRA    (10153): 	at androidx.leanback.widget.GridLayoutManager.measureChild(GridLayoutManager.java:1600)
07-31 11:20:55.801 E/ACRA    (10153): 	at androidx.leanback.widget.GridLayoutManager$2.createItem(GridLayoutManager.java:1702)
07-31 11:20:55.801 E/ACRA    (10153): 	at androidx.leanback.widget.SingleRow.appendVisibleItems(SingleRow.java:113)
07-31 11:20:55.801 E/ACRA    (10153): 	at androidx.leanback.widget.Grid.appendVisibleItems(Grid.java:397)
07-31 11:20:55.801 E/ACRA    (10153): 	at androidx.leanback.widget.GridLayoutManager.appendVisibleItems(GridLayoutManager.java:1965)
07-31 11:20:55.801 E/ACRA    (10153): 	at androidx.leanback.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:2318)
07-31 11:20:55.801 E/ACRA    (10153): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
07-31 11:20:55.801 E/ACRA    (10153): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
07-31 11:20:55.801 E/ACRA    (10153): 	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2106)
07-31 11:20:55.801 E/ACRA    (10153): 	at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:468)
07-31 11:20:55.801 E/ACRA    (10153): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
07-31 11:20:55.801 E/ACRA    (10153): 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
07-31 11:20:55.801 E/ACRA    (10153): 	at android.view.Choreographer.doFrame(Choreographer.java:727)
07-31 11:20:55.801 E/ACRA    (10153): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
07-31 11:20:55.801 E/ACRA    (10153): 	at android.os.Handler.handleCallback(Handler.java:938)
07-31 11:20:55.801 E/ACRA    (10153): 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-31 11:20:55.801 E/ACRA    (10153): 	at android.os.Looper.loop(Looper.java:223)
07-31 11:20:55.801 E/ACRA    (10153): 	at android.app.ActivityThread.main(ActivityThread.java:7668)
07-31 11:20:55.801 E/ACRA    (10153): 	at java.lang.reflect.Method.invoke(Native Method)
07-31 11:20:55.801 E/ACRA    (10153): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
07-31 11:20:55.801 E/ACRA    (10153): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
07-31 11:20:55.801 D/ACRA    (10153): Building report
07-31 11:20:55.803 D/ACRA    (10153): Starting collectors with priority FIRST
07-31 11:20:55.804 D/ACRA    (10153): Calling collector org.acra.collector.DropBoxCollector
07-31 11:20:55.804 D/ACRA    (10153): Collector org.acra.collector.DropBoxCollector completed
07-31 11:20:55.804 D/ACRA    (10153): Calling collector org.acra.collector.LogCatCollector
07-31 11:20:55.804 D/ACRA    (10153): Calling collector org.acra.collector.StacktraceCollector
07-31 11:20:55.805 D/ACRA    (10153): Collector org.acra.collector.StacktraceCollector completed
07-31 11:20:55.820 D/ACRA    (10153): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.16.0-beta.1` (`160001`)  
***Package name***: `org.jellyfin.androidtv.debug`  
***Build***: 
```json
{"BOARD":"sif","BOOTLOADER":"32.00.2019.50-t210-69ebfcbe","BRAND":"NVIDIA","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"sif","DISPLAY":"RQ1A.210105.003.7825199_3167.5736","FINGERPRINT":"NVIDIA\/sif\/sif:11\/RQ1A.210105.003\/7825199_3167.5736:user\/release-keys","HARDWARE":"sif","HOST":"mobile-u64-5306-d6000","ID":"RQ1A.210105.003","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"NVIDIA","MODEL":"SHIELD Android TV","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"sif","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1665975946000,"TYPE":"user","UNKNOWN":"unknown","USER":"NVIDIA","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"7825199_3167.5736","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"11","RELEASE_OR_CODENAME":"11","SDK":"30","SDK_INT":30,"SECURITY_PATCH":"2022-04-05"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv.debug","BUILD_TYPE":"debug","DEBUG":true,"DEVELOPMENT":false,"VERSION_CODE":160001,"VERSION_NAME":"0.16.0-beta.1"}
```  

### Device information

***Android version***: `11`  
***Device brand***: `NVIDIA`  
***Device product***: `sif`  
***Device model***: `SHIELD Android TV`  

### Crash information

***Start time***: `2023-07-31T09:21:56.469+10:00`  
***Crash time***: `2023-07-31T11:20:55.870+10:00`  

### Application version

v0.16.0-beta.1

### Where did you install the app from?

Sideloaded APK

### Device information

SHIELD

### Android version

11

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment]
I can't reproduce this issue, it is probably caused by one specific item in your library. Can you try the build from #2932 with the same search and see if it still crashes?
