### ISSUE TITLE
[0.16.0-beta.1] New playback module for video

### ISSUE THREAD

**Issue by VampiricAlien** [jellyfin/jellyfin-androidtv#2934]
### Describe the bug

With the option enable no media will play. Creating this issue so it can be tracked.
One of two message appear
```
Found item type episode triage
Could not find item (itemid=null)
```

### Logs

System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at MediaBrowser.Controller.Net.BasePeriodicWebSocketListener`2.Start(WebSocketMessageInfo message)
   at MediaBrowser.Controller.Net.BasePeriodicWebSocketListener`2.ProcessMessageAsync(WebSocketMessageInfo message)
   at Emby.Server.Implementations.HttpServer.WebSocketManager.ProcessWebSocketMessageReceived(WebSocketMessageInfo result)
   at Emby.Server.Implementations.HttpServer.WebSocketConnection.ProcessInternal(PipeReader reader)
   at Emby.Server.Implementations.HttpServer.WebSocketConnection.ProcessAsync(CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.WebSocketManager.WebSocketRequestHandler(HttpContext context)
[2023-08-01 21:03:53.485 +10:00] [INF] Sending ForceKeepAlive message to 1 inactive WebSockets.
[2023-08-01 21:03:53.485 +10:00] [INF] Error sending ForceKeepAlive message to WebSocket.
System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Closed') for this operation. Valid states are: 'Open, CloseReceived'
   at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.SendAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, WebSocketMessageFlags messageFlags, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Emby.Server.Implementations.Session.SessionWebSocketListener.KeepAliveSockets()
[2023-08-01 21:03:53.486 +10:00] [INF] Lost 1 WebSockets.

### Application version

0.16.0-beta.1

### Where did you install the app from?

Sideloaded APK

### Device information

SHIELD

### Android version

11

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment]
This is intended behavior, there is no video implementation yet.
