### ISSUE TITLE
Crash when signing into server

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-androidtv#296]
This is from a user crash report in tracepot. Not sure if this is actually an issue here or in the apiclient.

Stack trace:
```
java.lang.IllegalArgumentException: address
	at org.jellyfin.apiclient.interaction.connectionmanager.ConnectionManager.NormalizeAddress(ConnectionManager.java:386)
	at org.jellyfin.apiclient.interaction.connectionmanager.ConnectionManager.Connect(ConnectionManager.java:214)
	at org.jellyfin.androidtv.util.apiclient.AuthenticationHelper.signInToServer(AuthenticationHelper.java:143)
	at org.jellyfin.androidtv.util.apiclient.AuthenticationHelper$1.onClick(AuthenticationHelper.java:54)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6188)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)
```

**Comment by nielsvanvelzen** [comment]
Might be someone trying to use an empty server url or corrupt one.

**Comment by thornbill** [comment]
Looks like it's caused by entering a blank server address.

**Comment by nielsvanvelzen** [comment]
We could probably add an alert or just don't allow empty input. I don't think this is an issue introduced by 0.11.0 though.

I'll put it back to 0.12.0

**Comment by thornbill** [comment]
It's a quick fix and one of the most frequent crashes, so I moved it back into 0.11.1 :smile:
