### ISSUE TITLE
NPE in VideoManager

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-androidtv#297]
Stack trace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.google.android.exoplayer2.SimpleExoPlayer.getCurrentPosition()' on a null object reference
	at org.jellyfin.androidtv.playback.VideoManager.getCurrentPosition(VideoManager.java:172)
	at org.jellyfin.androidtv.playback.PlaybackController$15.run(PlaybackController.java:1002)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by nielsvanvelzen** [comment]
This _might_ be fixed in #251 by @Florianisme

https://github.com/jellyfin/jellyfin-androidtv/pull/251/files#diff-f9076d10ef5855d7f531b8f53ad952f1R174

**Comment by thornbill** [comment]
That looks like it should fix it, so I will move this to the 0.12.0 project.

**Comment by Florianisme** [comment]
Why not cherry pick it into a seperate PR? This crash occured 1/3 times when I closed the video player so quite often.

**Comment by nielsvanvelzen** [comment]
> Why not cherry pick it into a seperate PR? This crash occured 1/3 times when I closed the video player so quite often.

I did that just now, thanks for fixing it before we were aware of it 😄

**Comment by Florianisme** [comment]
Always here to help 😄
