### ISSUE TITLE
Artwork-Thumbs-Assets Not Loading

### ISSUE THREAD

**Issue by BSmith-66** [jellyfin/jellyfin-androidtv#3015]
### Describe the bug

No Artwork, Artists, Movie Posters etc is loaded - just the default movie or person icon etc 
if scan quickly through (fast scroll) then blurred colour images appear but disappear once stop scrolling
cleared cache and data - still persists

log attached for reference but not sure there is much there..as it doesn't actually crash
everything works fine just no images loaded

### Logs

---
client: Jellyfin for Android TV
client_version: 0.16.0-beta.3
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.NullPointerException: Parameter specified as non-null is null: method androidx.activity.OnBackPressedDispatcher.addCallback, parameter onBackPressedCallback
	at androidx.activity.OnBackPressedDispatcher.addCallback(Unknown Source:2)
	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.onActivityCreated(CustomPlaybackOverlayFragment.java:346)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3156)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:619)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:275)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1934)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```  
***Logcat***: 
```log
08-31 19:17:14.888 I/jellyfin-apiclient( 1800): Response received from: https://[DOMAIN]/Sessions/Playing/Progress
08-31 19:17:17.826 D/jellyfin-apiclient( 1800): Adding request to queue: https://[DOMAIN]/Sessions/Playing/Progress
08-31 19:17:17.889 I/jellyfin-apiclient( 1800): Response received from: https://[DOMAIN]/Sessions/Playing/Progress
08-31 19:17:20.828 D/jellyfin-apiclient( 1800): Adding request to queue: https://[DOMAIN]/Sessions/Playing/Progress
08-31 19:17:20.867 I/jellyfin-apiclient( 1800): Response received from: https://[DOMAIN]/Sessions/Playing/Progress
08-31 19:17:23.829 D/jellyfin-apiclient( 1800): Adding request to queue: https://[DOMAIN]/Sessions/Playing/Progress
08-31 19:17:23.894 I/jellyfin-apiclient( 1800): Response received from: https://[DOMAIN]/Sessions/Playing/Progress
08-31 19:17:26.831 D/jellyfin-apiclient( 1800): Adding request to queue: https://[DOMAIN]/Sessions/Playing/Progress
08-31 19:17:26.895 I/jellyfin-apiclient( 1800): Response received from: https://[DOMAIN]/Sessions/Playing/Progress
08-31 19:17:29.833 D/jellyfin-apiclient( 1800): Adding request to queue: https://[DOMAIN]/Sessions/Playing/Progress
08-31 19:17:29.897 I/jellyfin-apiclient( 1800): Response received from: https://[DOMAIN]/Sessions/Playing/Progress
08-31 19:17:32.834 D/jellyfin-apiclient( 1800): Adding request to queue: https://[DOMAIN]/Sessions/Playing/Progress
08-31 19:17:32.893 I/jellyfin-apiclient( 1800): Response received from: https://[DOMAIN]/Sessions/Playing/Progress
08-31 19:17:35.835 D/jellyfin-apiclient( 1800): Adding request to queue: https://[DOMAIN]/Sessions/Playing/Progress
08-31 19:17:36.157 I/jellyfin-apiclient( 1800): Response received from: https://[DOMAIN]/Sessions/Playing/Progress
08-31 19:17:38.836 D/jellyfin-apiclient( 1800): Adding request to queue: https://[DOMAIN]/Sessions/Playing/Progress
08-31 19:17:39.229 I/jellyfin-apiclient( 1800): Response received from: https://[DOMAIN]/Sessions/Playing/Progress
08-31 19:17:41.758 W/VLC     ( 1800): [dac7b590/3371] libvlc demux: find KaxCues FIXME
08-31 19:17:41.758 W/VLC     ( 1800): [dac7b590/3371] libvlc demux: EOF
08-31 19:17:41.758 W/VLC     ( 1800): [dac7b590/3371] libvlc demux: cannot get block EOF?
08-31 19:17:41.838 D/jellyfin-apiclient( 1800): Adding request to queue: https://[DOMAIN]/Sessions/Playing/Progress
08-31 19:17:41.911 I/jellyfin-apiclient( 1800): Response received from: https://[DOMAIN]/Sessions/Playing/Progress
08-31 19:17:42.199 E/VLC     ( 1800): [c0d1dc30/337d] libvlc decoder: Decoder is draining
08-31 19:17:42.201 W/VLC     ( 1800): [c0d1dc30/337d] libvlc decoder: EOS sent, waiting for OutThread
08-31 19:17:43.327 W/VLC     ( 1800): [c0d1dc30/337c] libvlc decoder: EOS received
08-31 19:17:43.441 W/VLC     ( 1800): [c8b5f530/319f] libvlc video output: picture is too late to be displayed (missing 291 ms)
08-31 19:17:43.505 D/lyfin.androidt( 1800): PlayerBase::stop() from IPlayer
08-31 19:17:43.505 D/AudioTrack( 1800): stop(75): called with 57023040 frames delivered
08-31 19:17:43.563 D/PlaybackController( 1800): On Completion fired
08-31 19:17:43.564 D/PlaybackController( 1800): stop called at 1427746
08-31 19:17:43.565 E/NdkMediaCodec( 1800): sf error code: -38
08-31 19:17:43.565 W/VLC     ( 1800): [c0d1dc30/337c] libvlc decoder: AMediaCodec.dequeueOutputBuffer failed
08-31 19:17:43.624 D/SurfaceUtils( 1800): disconnecting from surface 0xf6e7c408, reason disconnectFromSurface
08-31 19:17:43.633 D/MediaCodec( 1800): flushMediametrics
08-31 19:17:43.635 D/lyfin.androidt( 1800): PlayerBase::stop() from IPlayer
08-31 19:17:43.636 D/lyfin.androidt( 1800): PlayerBase::stop() from IPlayer
08-31 19:17:43.636 D/AudioTrack( 1800): stop(75): called with 0 frames delivered
08-31 19:17:43.637 D/lyfin.androidt( 1800): PlayerBase::stop() from IPlayer
08-31 19:17:43.715 I/jellyfin-apiclient( 1800): ReportPlaybackStopped: Item aa4925de-f6fd-4f76-0f17-07be4ed6b4d3, Ticks: 14277460000
08-31 19:17:43.715 D/jellyfin-apiclient( 1800): Adding request to queue: https://[DOMAIN]/Sessions/Playing/Stopped
08-31 19:17:43.716 D/PlaybackController( 1800): Moving to next queue item. Index: 1
08-31 19:17:43.720 D/NavigationRepositoryImpl( 1800): Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.playback.nextup.NextUpFragment (Kotlin reflection is not available), arguments=Bundle[{item_id=XXXXXXXXXX}]) (via navigate function)
08-31 19:17:43.723 D/PlaybackController( 1800): stop called at 1427746
08-31 19:17:43.749 I/ExoPlayerImpl( 1800): Release dd6c3a4 [ExoPlayerLib/2.19.1] [sabrina, Chromecast, Google, 31] [goog.exo.core, goog.exo.ui, goog.exo.exoplayer, goog.exo.decoder]
08-31 19:17:43.776 D/CustomPlaybackOverlayFragment( 1800): Stopping!
08-31 19:17:43.788 I/org.jellyfin.sdk.api.client.KtorClient( 1800): GET https://[DOMAIN]/Users/[MAYBE API KEY]
08-31 19:17:43.863 I/jellyfin-apiclient( 1800): Response received from: https://[DOMAIN]/Sessions/Playing/Stopped
08-31 19:17:50.872 D/NavigationRepositoryImpl( 1800): Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment (Kotlin reflection is not available), arguments=Bundle[{Position=0}]) (via navigate function)
08-31 19:17:50.939 I/ExoPlayerImpl( 1800): Init bb51eb0 [ExoPlayerLib/2.19.1] [sabrina, Chromecast, Google, 31]
08-31 19:17:50.956 I/DefaultRenderersFactory( 1800): Loaded FfmpegAudioRenderer.
08-31 19:17:50.979 D/AndroidRuntime( 1800): Shutting down VM
--------- beginning of crash
08-31 19:17:50.980 E/AndroidRuntime( 1800): FATAL EXCEPTION: main
08-31 19:17:50.980 E/AndroidRuntime( 1800): Process: org.jellyfin.androidtv, PID: 1800
08-31 19:17:50.980 E/AndroidRuntime( 1800): java.lang.NullPointerException: Parameter specified as non-null is null: method androidx.activity.OnBackPressedDispatcher.addCallback, parameter onBackPressedCallback
08-31 19:17:50.980 E/AndroidRuntime( 1800): 	at androidx.activity.OnBackPressedDispatcher.addCallback(Unknown Source:2)
08-31 19:17:50.980 E/AndroidRuntime( 1800): 	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.onActivityCreated(CustomPlaybackOverlayFragment.java:346)
08-31 19:17:50.980 E/AndroidRuntime( 1800): 	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3156)
08-31 19:17:50.980 E/AndroidRuntime( 1800): 	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:619)
08-31 19:17:50.980 E/AndroidRuntime( 1800): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:275)
08-31 19:17:50.980 E/AndroidRuntime( 1800): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1934)
08-31 19:17:50.980 E/AndroidRuntime( 1800): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
08-31 19:17:50.980 E/AndroidRuntime( 1800): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
08-31 19:17:50.980 E/AndroidRuntime( 1800): 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
08-31 19:17:50.980 E/AndroidRuntime( 1800): 	at android.os.Handler.handleCallback(Handler.java:938)
08-31 19:17:50.980 E/AndroidRuntime( 1800): 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-31 19:17:50.980 E/AndroidRuntime( 1800): 	at android.os.Looper.loopOnce(Looper.java:201)
08-31 19:17:50.980 E/AndroidRuntime( 1800): 	at android.os.Looper.loop(Looper.java:288)
08-31 19:17:50.980 E/AndroidRuntime( 1800): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
08-31 19:17:50.980 E/AndroidRuntime( 1800): 	at java.lang.reflect.Method.invoke(Native Method)
08-31 19:17:50.980 E/AndroidRuntime( 1800): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-31 19:17:50.980 E/AndroidRuntime( 1800): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
08-31 19:17:50.982 E/ACRA    ( 1800): ACRA caught a NullPointerException for org.jellyfin.androidtv
08-31 19:17:50.982 E/ACRA    ( 1800): java.lang.NullPointerException: Parameter specified as non-null is null: method androidx.activity.OnBackPressedDispatcher.addCallback, parameter onBackPressedCallback
08-31 19:17:50.982 E/ACRA    ( 1800): 	at androidx.activity.OnBackPressedDispatcher.addCallback(Unknown Source:2)
08-31 19:17:50.982 E/ACRA    ( 1800): 	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.onActivityCreated(CustomPlaybackOverlayFragment.java:346)
08-31 19:17:50.982 E/ACRA    ( 1800): 	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3156)
08-31 19:17:50.982 E/ACRA    ( 1800): 	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:619)
08-31 19:17:50.982 E/ACRA    ( 1800): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:275)
08-31 19:17:50.982 E/ACRA    ( 1800): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1934)
08-31 19:17:50.982 E/ACRA    ( 1800): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
08-31 19:17:50.982 E/ACRA    ( 1800): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
08-31 19:17:50.982 E/ACRA    ( 1800): 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
08-31 19:17:50.982 E/ACRA    ( 1800): 	at android.os.Handler.handleCallback(Handler.java:938)
08-31 19:17:50.982 E/ACRA    ( 1800): 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-31 19:17:50.982 E/ACRA    ( 1800): 	at android.os.Looper.loopOnce(Looper.java:201)
08-31 19:17:50.982 E/ACRA    ( 1800): 	at android.os.Looper.loop(Looper.java:288)
08-31 19:17:50.982 E/ACRA    ( 1800): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
08-31 19:17:50.982 E/ACRA    ( 1800): 	at java.lang.reflect.Method.invoke(Native Method)
08-31 19:17:50.982 E/ACRA    ( 1800): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-31 19:17:50.982 E/ACRA    ( 1800): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
08-31 19:17:50.983 D/ACRA    ( 1800): Building report
08-31 19:17:50.987 D/ACRA    ( 1800): Starting collectors with priority FIRST
08-31 19:17:50.988 D/ACRA    ( 1800): Calling collector org.acra.collector.DropBoxCollector
08-31 19:17:50.988 D/ACRA    ( 1800): Calling collector org.acra.collector.LogCatCollector
08-31 19:17:50.988 D/ACRA    ( 1800): Calling collector org.acra.collector.StacktraceCollector
08-31 19:17:50.988 D/ACRA    ( 1800): Collector org.acra.collector.DropBoxCollector completed
08-31 19:17:50.989 D/ACRA    ( 1800): Collector org.acra.collector.StacktraceCollector completed
08-31 19:17:50.993 D/ACRA    ( 1800): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.16.0-beta.3` (`160003`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"sabrina","BOOTLOADER":"01.01.230614.043521","BRAND":"google","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"sabrina","DISPLAY":"STTE.230319.008.H1.10319030","FINGERPRINT":"google\/sabrina_prod_stable\/sabrina:12\/STTE.230319.008.H1\/10319030:user\/release-keys","HARDWARE":"amlogic","HOST":"abfarm-release-2004-0234","ID":"STTE.230319.008.H1","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Google","MODEL":"Chromecast","ODM_SKU":"AU","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"sabrina_prod_stable","RADIO":"unknown","SKU":"AU","SOC_MANUFACTURER":"Amlogic","SOC_MODEL":"AMLS905D3","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1686731890000,"TYPE":"user","UNKNOWN":"unknown","USER":"android-build","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"10319030","MEDIA_PERFORMANCE_CLASS":0,"PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"12","RELEASE_OR_CODENAME":"12","SDK":"31","SDK_INT":31,"SECURITY_PATCH":"2023-04-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":160003,"VERSION_NAME":"0.16.0-beta.3"}
```  

### Device information

***Android version***: `12`  
***Device brand***: `google`  
***Device product***: `sabrina_prod_stable`  
***Device model***: `Chromecast`  

### Crash information

***Start time***: `2023-06-15T05:06:54.573+10:00`  
***Crash time***: `2023-08-31T19:17:51.149+10:00`  

### Application version

0.16.0Beta3

### Where did you install the app from?

Google Play

### Device information

Google Chromecast with Google TV

### Android version

latest version at time of posting

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment]
Those crash logs are unrelated to the description so not much that we can do about that one. For the images not loading; please explain your networking setup etc. anything that would help find the cause of the problem.

**Comment by BSmith-66** [comment]
JF server running in debian LXC on a seperate VLAN
CWGT devices running on a dedicated VLAN (with internet access)
devices access to JF server though NGNIX Rev proxy (local only)
all with certs etc. was ok until beta 3 i think cannot confirm. 

web and normal android seem to be fine across same networks. 
i did read there was a refactor of the image code in relation to posters vs thumbs etc, but im not guru enough to tell if they are related. 

if there's anyway i can help troubleshoot, happy to contribute in any way i can. 
I will tweak some firewall rules and test direct connection without rev proxy tomorrow to narrow things down.

**Comment by nielsvanvelzen** [comment]
Did you also try the stable version (0.15.12) of the app and did the images work in that version?

If possible, can you get some logs while opening a screen in the app that fails to load images?

You'll need to use logcat to get the logs from a device: https://wiki.lineageos.org/how-to/logcat. Make sure to reproduce the issue just before getting the logs.

**Comment by BSmith-66** [comment]
I have 2 devices with same setup 
Just rolled one back to 0.15.12 and artwork/images appear as expected.
Will figure out logs on the other as soon as I can. Definately something in 16 beta 3 for me. Pretty sure beta 2 was ok may try side loading each version to narrow it down .

**Comment by BSmith-66** [comment]
[log.txt](https://github.com/jellyfin/jellyfin-androidtv/files/12567986/log.txt)

Just generated logs for the unit still on 16 beta 3, I navigated a few folders on the main menu, and a actor and then played a show. 

hope this helps... i saw web socket on there and wonder if i have a reverse proxy issue.. i need to get around to eliminating that from the mix

**Comment by BSmith-66** [comment]
issue continued on B4, but ok on the 0.15 releases
bypassed reverse proxy so basically chomecast WGTV--> jellyfin server and on 0.16 B4 all works... 
i'm using nginx as rev proxy (jellyfin.mydomain.com ---> server:8096) will compare setup vs jellyfin documentation to make sure my setup isn't missing anything but interesting it changed from 0.15 to 0.16 branch.

**Comment by BSmith-66** [comment]
ok for anyone in future pretty sure its the security headers on the nginx or bot protection that was not allowing artwork to load.
I also tweaked up minimum body size to 200m just in-case that was it
used this opnsense guide as reference  [https://forum.opnsense.org/index.php?topic=24778.0](url)

thanks for the help along the way keep up the good work and sorry to waste time on my own config issues..

**Comment by nielsvanvelzen** [comment]
Can you share the specific header that caused the issue and how you fixed it? Could be useful for others running into the same issue.
