### ISSUE TITLE
[Beta 4 v0.16.0] Crash on resume

### ISSUE THREAD

**Issue by VampiricAlien** [jellyfin/jellyfin-androidtv#3063]
### Describe the bug

Crash while waking up after android screensaver.

I think it's one of the other crashes here: https://github.com/jellyfin/jellyfin-androidtv/issues/3052

### Logs

---
client: Jellyfin for Android TV
client_version: 0.16.0-beta.4
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.NullPointerException
	at org.jellyfin.androidtv.ui.home.HomeFragmentHelper.loadResume(HomeFragmentHelper.kt:33)
	at org.jellyfin.androidtv.ui.home.HomeFragmentHelper.loadResumeVideo(HomeFragmentHelper.kt:51)
	at org.jellyfin.androidtv.ui.home.HomeRowsFragment$onCreate$1.invokeSuspend(HomeRowsFragment.kt:123)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e23aaef, Dispatchers.IO]

```  
***Logcat***: 
```log
09-22 12:44:24.252 D/ACRA    ( 4207): SimplePluginLoader loading services from plugin classes : [Ljava.lang.Class;@6562d83
09-22 12:44:24.253 D/ACRA    ( 4207): ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.startup.StartupProcessor]
09-22 12:44:24.258 D/ACRA    ( 4207): Loaded StartupProcessor of type org.acra.startup.UnapprovedStartupProcessor
09-22 12:44:24.302 I/WM-WorkerWrapper( 4207): Worker result RETRY for Work [ id=e5e-6871-459b-bef1-3c94, tags={ org.jellyfin.androidtv.integration.LeanbackChannelWorker } ]
09-22 12:44:24.544 I/org.jellyfin.sdk.api.client.KtorClient( 4207): GET http://IP Address:8096/System/Info/Public
09-22 12:44:24.598 I/SessionRepositoryImpl( 4207): Updating current session. userId=dufyhs-djofow-jkdkfhw-uihfks apiBindingSuccess=true
09-22 12:44:24.609 I/org.jellyfin.sdk.api.client.KtorClient( 4207): GET http://IP Address:8096/Users/Me
09-22 12:44:24.744 I/org.jellyfin.sdk.api.client.KtorClient( 4207): GET http://IP Address:8096/DisplayPreferences/livetv?huserId=dufyhs-djofow-jkdkfhw-uihfks=jellyfin-androidtv
09-22 12:44:24.787 I/org.jellyfin.sdk.api.client.KtorClient( 4207): GET http://IP Address:8096/DisplayPreferences/usersettings?huserId=dufyhs-djofow-jkdkfhw-uihfks=emby
09-22 12:44:29.610 D/ProfileInstaller( 4207): Installing profile for org.jellyfin.androidtv.debug
09-22 12:54:24.444 I/org.jellyfin.sdk.api.client.KtorClient( 4207): GET http://IP Address:8096/Shows/NextUp?userId=dufyhs-djofow-jkdkfhw-uihfks&limit=10&fields=DateCreated&imageTypeLimit=1&enableTotalRecordCount=true&disableFirstEpisode=false&enableRewatching=false
09-22 12:54:24.478 I/org.jellyfin.sdk.api.client.KtorClient( 4207): GET http://IP Address:8096/Users/f0c7388228-fha1-473d-8950-yg873d77af/Items/Resume?limit=10&fields=DateCreated&mediaTypes=Video&imageTypeLimit=1&includeItemTypes=Episode&includeItemTypes=Movie&enableTotalRecordCount=true&enableImages=true&excludeActiveSessions=true
09-22 12:54:25.037 W/androidtv.debu( 4207): Verification of org.jellyfin.sdk.model.api.BaseItemDto org.jellyfin.sdk.model.api.BaseItemDto$$serializer.deserialize(kotlinx.serialization.encoding.Decoder) took 197.383ms (large method) (65223.41 bytecodes/s) (217832B approximate peak alloc)
09-22 12:54:25.696 I/org.jellyfin.sdk.api.client.KtorClient( 4207): GET http://IP Address:8096/Users/f0c7388228-fha1-473d-8950-yg873d77af/Items/Latest?fields=Overview&includeItemTypes=Movie&isPlayed=false&limit=50&groupItems=true
09-22 12:54:25.696 I/org.jellyfin.sdk.api.client.KtorClient( 4207): GET http://IP Address:8096/Users/f0c7388228-fha1-473d-8950-yg873d77af/Items/Latest?fields=Overview&includeItemTypes=Episode&isPlayed=false&limit=50&groupItems=true
09-22 12:54:25.696 I/org.jellyfin.sdk.api.client.KtorClient( 4207): GET http://IP Address:8096/Users/f0c7388228-fha1-473d-8950-yg873d77af/Items/Latest?fields=Overview&includeItemTypes=Movie&includeItemTypes=Series&isPlayed=false&limit=50&groupItems=true
09-22 12:54:26.148 I/org.jellyfin.sdk.api.client.KtorClient( 4207): GET http://IP Address:8096/Users/f0c736e068677af/Views?includeHidden=false
09-22 12:54:26.348 I/MigrationContext( 4207): Requested migration from 7 to 7. Found 1 migrations in total.
09-22 12:54:26.349 D/LeanbackChannelWorker( 4207): Updating channel content://android.media.tv/channel/167
09-22 12:54:26.476 D/LeanbackChannelWorker( 4207): Updating channel content://android.media.tv/channel/165
09-22 12:54:26.755 D/LeanbackChannelWorker( 4207): Updating channel content://android.media.tv/channel/168
09-22 12:54:26.971 D/LeanbackChannelWorker( 4207): Updating channel content://android.media.tv/channel/169
09-22 12:54:27.064 D/LeanbackChannelWorker( 4207): Updating channel content://android.media.tv/channel/166
09-22 12:54:27.141 I/WM-WorkerWrapper( 4207): Worker result SUCCESS for Work [ id=e592c59b-bef1-3cf894, tags={ org.jellyfin.androidtv.integration.LeanbackChannelWorker } ]
09-22 12:56:21.254 I/androidtv.debu( 4540): Late-enabling -Xcheck:jni
09-22 12:56:21.328 I/androidtv.debu( 4540): Unquickening 12 vdex files!
--------- beginning of system
09-22 12:56:21.519 W/ActivityThread( 4540): Application org.jellyfin.androidtv.debug can be debugged on port 8100...
09-22 12:56:25.309 D/NetworkSecurityConfig( 4540): No Network Security Config specified, using platform default
09-22 12:56:25.312 D/NetworkSecurityConfig( 4540): No Network Security Config specified, using platform default
09-22 12:56:25.607 D/ACRA    ( 4540): ACRA processName='org.jellyfin.androidtv.debug'
09-22 12:56:25.649 I/ACRA    ( 4540): ACRA is enabled for org.jellyfin.androidtv.debug, initializing...
09-22 12:56:25.660 D/ACRA    ( 4540): SimplePluginLoader loading services from plugin classes : [Ljava.lang.Class;@6562d83
09-22 12:56:25.661 D/ACRA    ( 4540): ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.collector.Collector]
09-22 12:56:26.402 D/ACRA    ( 4540): Loaded Collector of type org.acra.collector.ConfigurationCollector
09-22 12:56:26.404 D/ACRA    ( 4540): Loaded Collector of type org.acra.collector.CustomDataCollector
09-22 12:56:26.406 D/ACRA    ( 4540): Loaded Collector of type org.acra.collector.DeviceFeaturesCollector
09-22 12:56:26.409 D/ACRA    ( 4540): Loaded Collector of type org.acra.collector.DeviceIdCollector
09-22 12:56:26.415 D/ACRA    ( 4540): Loaded Collector of type org.acra.collector.DisplayManagerCollector
09-22 12:56:26.425 D/ACRA    ( 4540): Loaded Collector of type org.acra.collector.DropBoxCollector
09-22 12:56:26.430 D/ACRA    ( 4540): Loaded Collector of type org.acra.collector.LogCatCollector
09-22 12:56:26.432 D/ACRA    ( 4540): Loaded Collector of type org.acra.collector.LogFileCollector
09-22 12:56:26.442 D/ACRA    ( 4540): Loaded Collector of type org.acra.collector.MediaCodecListCollector
09-22 12:56:26.445 D/ACRA    ( 4540): Loaded Collector of type org.acra.collector.MemoryInfoCollector
09-22 12:56:26.447 D/ACRA    ( 4540): Loaded Collector of type org.acra.collector.PackageManagerCollector
09-22 12:56:26.451 D/ACRA    ( 4540): Loaded Collector of type org.acra.collector.ReflectionCollector
09-22 12:56:26.455 D/ACRA    ( 4540): Loaded Collector of type org.acra.collector.SettingsCollector
09-22 12:56:26.457 D/ACRA    ( 4540): Loaded Collector of type org.acra.collector.SharedPreferencesCollector
09-22 12:56:26.461 D/ACRA    ( 4540): Loaded Collector of type org.acra.collector.SimpleValuesCollector
09-22 12:56:26.464 D/ACRA    ( 4540): Loaded Collector of type org.acra.collector.StacktraceCollector
09-22 12:56:26.465 D/ACRA    ( 4540): Loaded Collector of type org.acra.collector.ThreadCollector
09-22 12:56:26.550 D/ACRA    ( 4540): Loaded Collector of type org.acra.collector.TimeCollector
09-22 12:56:26.558 I/androidtv.debu( 4540): Waiting for a blocking GC ClassLinker
09-22 12:56:26.579 I/androidtv.debu( 4540): WaitForGcToComplete blocked ClassLinker on ClassLinker for 20.565ms
09-22 12:56:26.662 D/ACRA    ( 4540): SimplePluginLoader loading services from plugin classes : [Ljava.lang.Class;@6562d83
09-22 12:56:26.663 D/ACRA    ( 4540): ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.scheduler.SenderSchedulerFactory]
09-22 12:56:26.684 D/ACRA    ( 4540): SimplePluginLoader loading services from plugin classes : [Ljava.lang.Class;@6562d83
09-22 12:56:26.684 D/ACRA    ( 4540): ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.config.ReportingAdministrator]
09-22 12:56:26.761 D/WM-WrkMgrInitializer( 4540): Initializing WorkManager with default configuration.
09-22 12:56:26.945 W/androidtv.debu( 4540): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (greylist-max-o, reflection, denied)
09-22 12:56:26.946 W/androidtv.debu( 4540): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->c:Ljava/util/Collection; (greylist, reflection, allowed)
09-22 12:56:26.946 W/androidtv.debu( 4540): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
09-22 12:56:26.947 W/androidtv.debu( 4540): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
09-22 12:56:27.094 I/TetheringManager( 4540): registerTetheringEventCallback:org.jellyfin.androidtv.debug
09-22 12:56:27.153 W/androidtv.debu( 4540): Accessing hidden method Ldalvik/system/CloseGuard;->setEnabled(Z)V (greylist,core-platform-api, reflection, allowed)
09-22 12:56:27.169 I/LogInitializer( 4540): Debug tree planted
09-22 12:56:28.209 I/MigrationContext( 4540): Requested migration from 2 to 2. Found 1 migrations in total.
09-22 12:56:29.248 I/SessionRepositoryImpl( 4540): Restoring session
09-22 12:56:29.702 I/org.jellyfin.sdk.api.client.KtorClient( 4540): GET http://IP Address:8096/Branding/Configuration
09-22 12:56:30.060 D/ACRA    ( 4540): ACRA processName='org.jellyfin.androidtv.debug'
09-22 12:56:30.323 I/androidtv.debu( 4540): Waiting for a blocking GC ProfileSaver
09-22 12:56:30.339 I/androidtv.debu( 4540): WaitForGcToComplete blocked ProfileSaver on ClassLinker for 15.882ms
09-22 12:56:30.364 I/androidtv.debu( 4540): WaitForGcToComplete blocked RunEmptyCheckpoint on ProfileSaver for 23.206ms
09-22 12:56:30.545 I/MigrationContext( 4540): Requested migration from 7 to 7. Found 1 migrations in total.
09-22 12:56:30.567 I/ActivityThemeExtensionsKt( 4540): Applying theme DARK
09-22 12:56:30.794 D/ACRA    ( 4540): onActivityCreated class org.jellyfin.androidtv.ui.browsing.MainActivity
09-22 12:56:31.090 D/NavigationRepositoryImpl( 4540): Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.home.HomeFragment (Kotlin reflection is not available), arguments=Bundle[{}]) (via init)
09-22 12:56:31.139 E/ACRA    ( 4540): ACRA caught a NullPointerException for org.jellyfin.androidtv.debug
09-22 12:56:31.139 E/ACRA    ( 4540): java.lang.NullPointerException
09-22 12:56:31.139 E/ACRA    ( 4540): 	at org.jellyfin.androidtv.ui.home.HomeFragmentHelper.loadResume(HomeFragmentHelper.kt:33)
09-22 12:56:31.139 E/ACRA    ( 4540): 	at org.jellyfin.androidtv.ui.home.HomeFragmentHelper.loadResumeVideo(HomeFragmentHelper.kt:51)
09-22 12:56:31.139 E/ACRA    ( 4540): 	at org.jellyfin.androidtv.ui.home.HomeRowsFragment$onCreate$1.invokeSuspend(HomeRowsFragment.kt:123)
09-22 12:56:31.139 E/ACRA    ( 4540): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-22 12:56:31.139 E/ACRA    ( 4540): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
09-22 12:56:31.139 E/ACRA    ( 4540): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
09-22 12:56:31.139 E/ACRA    ( 4540): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
09-22 12:56:31.139 E/ACRA    ( 4540): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
09-22 12:56:31.139 E/ACRA    ( 4540): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
09-22 12:56:31.139 E/ACRA    ( 4540): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
09-22 12:56:31.139 E/ACRA    ( 4540): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
09-22 12:56:31.139 E/ACRA    ( 4540): 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e23aaef, Dispatchers.IO]
09-22 12:56:31.139 D/ACRA    ( 4540): Building report
09-22 12:56:31.148 D/ACRA    ( 4540): Starting collectors with priority FIRST
09-22 12:56:31.151 D/ACRA    ( 4540): Calling collector org.acra.collector.DropBoxCollector
09-22 12:56:31.152 D/ACRA    ( 4540): Collector org.acra.collector.DropBoxCollector completed
09-22 12:56:31.153 D/ACRA    ( 4540): Calling collector org.acra.collector.StacktraceCollector
09-22 12:56:31.154 D/ACRA    ( 4540): Calling collector org.acra.collector.LogCatCollector
09-22 12:56:31.157 D/ACRA    ( 4540): Collector org.acra.collector.StacktraceCollector completed
09-22 12:56:31.182 D/ACRA    ( 4540): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.16.0-beta.4` (`160004`)  
***Package name***: `org.jellyfin.androidtv.debug`  
***Build***: 
```json
{"BOARD":"sif","BOOTLOADER":"32.00.2019.50-t210-69ebfcbe","BRAND":"NVIDIA","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"sif","DISPLAY":"RQ1A.210105.003.7825199_3167.5736","FINGERPRINT":"NVIDIA\/sif\/sif:11\/RQ1A.210105.003\/7825199_3167.5736:user\/release-keys","HARDWARE":"sif","HOST":"mobile-u64-5306-d6000","ID":"RQ1A.210105.003","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"NVIDIA","MODEL":"SHIELD Android TV","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"sif","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1665975946000,"TYPE":"user","UNKNOWN":"unknown","USER":"NVIDIA","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"7825199_3167.5736","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"11","RELEASE_OR_CODENAME":"11","SDK":"30","SDK_INT":30,"SECURITY_PATCH":"2022-04-05"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv.debug","BUILD_TYPE":"debug","DEBUG":true,"DEVELOPMENT":false,"VERSION_CODE":160004,"VERSION_NAME":"0.16.0-beta.4"}
```  

### Device information

***Android version***: `11`  
***Device brand***: `NVIDIA`  
***Device product***: `sif`  
***Device model***: `SHIELD Android TV`  

### Crash information

***Start time***: `2023-09-22T12:56:26.645+10:00`  
***Crash time***: `2023-09-22T12:56:31.392+10:00`  

### Application version

0.16.0-beta.4

### Where did you install the app from?

Sideloaded APK

### Device information

SHIELD

### Android version

11

### Jellyfin server version

10.8.10

**Comment by warmoans** [comment]
I can confirm this happens for me on my Nvidia Sheild Pro 2019

[upload_org.jellyfin.androidtv_0.16.0-beta.4_20230925015735_1fe64904ee3f4e8288a3a46b814a2753.log](https://github.com/jellyfin/jellyfin-androidtv/files/12718051/upload_org.jellyfin.androidtv_0.16.0-beta.4_20230925015735_1fe64904ee3f4e8288a3a46b814a2753.log)
[upload_org.jellyfin.androidtv_0.16.0-beta.4_20230925025850_d13ae0800a5e44a1a2d7e78d781f1bd2.log](https://github.com/jellyfin/jellyfin-androidtv/files/12718052/upload_org.jellyfin.androidtv_0.16.0-beta.4_20230925025850_d13ae0800a5e44a1a2d7e78d781f1bd2.log)
[upload_org.jellyfin.androidtv_0.16.0-beta.4_20230925034148_f9cb2e7b3eed499cb9352626d05c9e67.log](https://github.com/jellyfin/jellyfin-androidtv/files/12718054/upload_org.jellyfin.androidtv_0.16.0-beta.4_20230925034148_f9cb2e7b3eed499cb9352626d05c9e67.log)


This issue didn't show up when searching open issues. So I'll close mine.

**Comment by nielsvanvelzen** [comment]
The app loses its state when killed, if Android then resumes the app again it crashes. This issue has always happened (it existed before I started even using Jellyfin) and fixing it takes time. I can't use my magic wand and suddenly make it disappear in 0.16.

**Comment by warmoans** [comment]
I want to add that the built in jellyfin screensaver works totally fine. I wasn't aware of it before.
