### ISSUE TITLE
Startup crash:Cannot initialize WorkManager in direct boot mode

### ISSUE THREAD

**Issue by MDCY9008** [jellyfin/jellyfin-androidtv#3143]
### Describe the bug

```01-01 08:01:16.675     0     0 D kernel  : [   67.591448@0] logd logdr: UID=10028 GID=10028 PID=5047 n tail=100 logMask=99 pid=0 start=0ns timeout=0ns
01-01 08:01:16.712  3704  3721 W WindowManager: [addWindow] title:Toast
01-01 08:01:18.824  3474  3551 E storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
01-01 08:01:20.217  3704  3721 W NotificationService: Toast already killed. pkg=org.jellyfin.androidtv callback=android.app.ITransientNotification$Stub$Proxy@ec2e5a6
01-01 08:01:20.402  3704  3719 I ActivityManager: Process org.jellyfin.androidtv (pid 5025) has died: fore TOP 
01-01 08:01:20.402  3704  5024 I WindowManager: WIN DEATH: Window{c78f7cd u0 Toast EXITING}
01-01 08:01:20.406  3704  3719 I ActivityManager: startProcessLocked ProcessRecord{497037e 0:org.jellyfin.androidtv/u0a28}
01-01 08:01:20.406  3704  3719 D ActivityManager: network not ok
01-01 08:01:20.423  3704  3727 I ActivityManager: Start proc 5083:org.jellyfin.androidtv/u0a28 for activity org.jellyfin.androidtv/.ui.startup.StartupActivity
01-01 08:01:20.486  3704  3719 I WindowManager: Screen frozen for +23ms due to new-config
01-01 08:01:20.747  3704  3733 W ActivityManager: setHasOverlayUi called on unknown pid: 5025
01-01 08:01:20.892  5083  5083 E AndroidRuntime: FATAL EXCEPTION: main
01-01 08:01:20.892  5083  5083 E AndroidRuntime: Process: org.jellyfin.androidtv, PID: 5083
01-01 08:01:20.892  5083  5083 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.IllegalStateException: Cannot initialize WorkManager in direct boot mode
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6396)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:891)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: Caused by: androidx.startup.StartupException: java.lang.IllegalStateException: Cannot initialize WorkManager in direct boot mode
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1919)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1894)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6391)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	... 10 more
01-01 08:01:20.892  5083  5083 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Cannot initialize WorkManager in direct boot mode
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at androidx.work.impl.WorkManagerImpl.internalInit(WorkManagerImpl.java:833)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at androidx.work.impl.WorkManagerImpl.<init>(WorkManagerImpl.java:293)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at androidx.work.impl.WorkManagerImpl.<init>(WorkManagerImpl.java:256)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at androidx.work.impl.WorkManagerImpl.<init>(WorkManagerImpl.java:234)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:213)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at androidx.work.WorkManager.initialize(WorkManager.java:210)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at androidx.work.WorkManagerInitializer.create(WorkManagerInitializer.java:39)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at androidx.work.WorkManagerInitializer.create(WorkManagerInitializer.java:30)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
01-01 08:01:20.892  5083  5083 E AndroidRuntime: 	... 16 more```

### Logs

_No response_

### Application version

v0.16.0-beta.5

### Where did you install the app from?

Sideloaded APK

### Device information

CM311-1A(S905L3A)

### Android version

Android 9

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment]
Please use the bug report template.

**Comment by SJJ-dot** [comment]
@MDCY9008 用这个试试 https://github.com/SJJ-dot/jellyfin-androidtv
