### ISSUE TITLE
NGINX Reverse proxy on Uncommon port not working

### ISSUE THREAD

**Issue by rlsmntr** [jellyfin/jellyfin-androidtv#316]
So as much detail as I can provide i am running my jellyfin via an uncommon ssl port example is https://jellyfin.supersecret.mydomain.com:1234/  This works on android (phone) app, web app but it is not working on the android tv app.  I get the following error:

```
[2020-02-07 17:59:50.749 -06:00] [ERR] AcceptWebSocketAsync error
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Emby.Server.Implementations.SocketSharp.WebSocketSharpListener.ProcessWebSocketRequest(HttpContext ctx)
```

**Comment by anthonylavado** [comment]
Including full log snippet (source [Pastebin](https://pastebin.com/raw/TWwk7E3i), via [Reddit](https://www.reddit.com/r/jellyfin/comments/f03nm1/android_tv_fqdn_through_nginx_not_working_right/)):
```
[2020-02-06 20:29:23.402 -06:00] [INF] Saving system configuration
[2020-02-06 20:29:23.403 -06:00] [INF] Setting cache path to /config/cache
[2020-02-06 20:29:31.884 -06:00] [INF] Saving system configuration
[2020-02-06 20:29:31.885 -06:00] [INF] Setting cache path to /config/cache
[2020-02-06 20:29:39.249 -06:00] [INF] WS "http://jellyfin.***DOMAINHERE***.com/socket?api_key=***APIKEYHERE***&deviceId=***DEVICEIDHERE***". UserAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
[2020-02-06 20:30:39.243 -06:00] [ERR] AcceptWebSocketAsync error
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Emby.Server.Implementations.SocketSharp.WebSocketSharpListener.ProcessWebSocketRequest(HttpContext ctx)
```

**Comment by anthonylavado** [comment]
Our current understanding is that this appears to be a Chrome connection, not the Android TV app.

**Comment by rlsmntr** [comment]
So you are correct that log is unrelated.  I just tried hitting it several times from the android tv with only chrome open on the logs and it gave no relevant information.  I could not even get anything to change in the logs until it automatically scanned a library.  It just fails on the androidtv without any log information on the server.  As requested here is the nginx config I am using with port changed and domain.

https://pastebin.com/raw/nzbcMSYE

**Comment by stephankellermayr** [comment]
Are you sure that `proxy_pass http://192.168.10.15:8096;` in line 46 is correct?
I think it should be `proxy_pass http://192.168.10.15:8096/socket;`, but i don't really know if that is related to your Problem.
