### ISSUE TITLE
Frequent crashes on NullPointerException for null object reference to CustomPlaybackOverlayFragment

### ISSUE THREAD

**Issue by AhiyaHiya** [jellyfin/jellyfin-androidtv#3234]
### Describe the bug

The bug is fairly easy to reproduce. Using the latest `Jellyfin for Android TV` client, version `0.16.0`, on an NVIDIA Shield, navigate to the home screen and let the device sit idle for more than 5 minutes.

When you attempt to open Jellyfin from the main screen, you get the crash reported listed in the logs, pasted below.

### Logs

---
client: Jellyfin for Android TV
client_version: 0.16.0
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.getContext()' on a null object reference
	at org.jellyfin.androidtv.ui.playback.PlaybackController.buildVLCOptions(PlaybackController.java:591)
	at org.jellyfin.androidtv.ui.playback.PlaybackController.play(PlaybackController.java:540)
	at org.jellyfin.androidtv.ui.playback.PlaybackController.play(PlaybackController.java:435)
	at org.jellyfin.androidtv.ui.playback.overlay.VideoPlayerAdapter.play(VideoPlayerAdapter.java:29)
	at org.jellyfin.androidtv.ui.playback.overlay.action.PlayPauseAction.onActionClicked(PlayPauseAction.kt:12)
	at org.jellyfin.androidtv.ui.playback.overlay.CustomPlaybackTransportControlGlue.onActionClicked(CustomPlaybackTransportControlGlue.java:292)
	at org.jellyfin.androidtv.ui.playback.overlay.CustomPlaybackTransportControlGlue$2.onProgressBarClicked(CustomPlaybackTransportControlGlue.java:165)
	at androidx.leanback.widget.PlaybackTransportRowPresenter$ViewHolder$3.onClick(PlaybackTransportRowPresenter.java:275)
	at android.view.View.performClick(View.java:7448)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.onKeyUp(View.java:15060)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2886)
	at android.view.View.dispatchKeyEvent(View.java:14247)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at androidx.leanback.widget.PlaybackTransportRowView.dispatchKeyEvent(PlaybackTransportRowView.java:71)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at androidx.leanback.widget.BaseGridView.dispatchKeyEvent(BaseGridView.java:1081)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:476)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1861)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4085)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:120)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:138)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:390)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6186)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6054)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5529)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5704)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5761)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5737)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5895)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3217)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2759)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2750)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3194)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```  
***Logcat***: 
```log
12-17 15:16:22.411 E/AndroidRuntime( 7408): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
12-17 15:16:22.411 E/AndroidRuntime( 7408): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
12-17 15:16:22.411 E/AndroidRuntime( 7408): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
12-17 15:16:22.411 E/AndroidRuntime( 7408): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
12-17 15:16:22.411 E/AndroidRuntime( 7408): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
12-17 15:16:22.411 E/AndroidRuntime( 7408): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
12-17 15:16:22.411 E/AndroidRuntime( 7408): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
12-17 15:16:22.411 E/AndroidRuntime( 7408): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5737)
12-17 15:16:22.411 E/AndroidRuntime( 7408): 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5895)
12-17 15:16:22.411 E/AndroidRuntime( 7408): 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3217)
12-17 15:16:22.411 E/AndroidRuntime( 7408): 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2759)
12-17 15:16:22.411 E/AndroidRuntime( 7408): 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2750)
12-17 15:16:22.411 E/AndroidRuntime( 7408): 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3194)
12-17 15:16:22.411 E/AndroidRuntime( 7408): 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
12-17 15:16:22.411 E/AndroidRuntime( 7408): 	at android.os.MessageQueue.nativePollOnce(Native Method)
12-17 15:16:22.411 E/AndroidRuntime( 7408): 	at android.os.MessageQueue.next(MessageQueue.java:335)
12-17 15:16:22.411 E/AndroidRuntime( 7408): 	at android.os.Looper.loop(Looper.java:183)
12-17 15:16:22.411 E/AndroidRuntime( 7408): 	at android.app.ActivityThread.main(ActivityThread.java:7668)
12-17 15:16:22.411 E/AndroidRuntime( 7408): 	at java.lang.reflect.Method.invoke(Native Method)
12-17 15:16:22.411 E/AndroidRuntime( 7408): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
12-17 15:16:22.411 E/AndroidRuntime( 7408): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
12-17 15:16:22.421 E/ACRA    ( 7408): ACRA caught a NullPointerException for org.jellyfin.androidtv
12-17 15:16:22.421 E/ACRA    ( 7408): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.getContext()' on a null object reference
12-17 15:16:22.421 E/ACRA    ( 7408): 	at org.jellyfin.androidtv.ui.playback.PlaybackController.buildVLCOptions(PlaybackController.java:591)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at org.jellyfin.androidtv.ui.playback.PlaybackController.play(PlaybackController.java:540)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at org.jellyfin.androidtv.ui.playback.PlaybackController.play(PlaybackController.java:435)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at org.jellyfin.androidtv.ui.playback.overlay.VideoPlayerAdapter.play(VideoPlayerAdapter.java:29)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at org.jellyfin.androidtv.ui.playback.overlay.action.PlayPauseAction.onActionClicked(PlayPauseAction.kt:12)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at org.jellyfin.androidtv.ui.playback.overlay.CustomPlaybackTransportControlGlue.onActionClicked(CustomPlaybackTransportControlGlue.java:292)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at org.jellyfin.androidtv.ui.playback.overlay.CustomPlaybackTransportControlGlue$2.onProgressBarClicked(CustomPlaybackTransportControlGlue.java:165)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at androidx.leanback.widget.PlaybackTransportRowPresenter$ViewHolder$3.onClick(PlaybackTransportRowPresenter.java:275)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.View.performClick(View.java:7448)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.View.performClickInternal(View.java:7425)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.View.onKeyUp(View.java:15060)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.KeyEvent.dispatch(KeyEvent.java:2886)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.View.dispatchKeyEvent(View.java:14247)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at androidx.leanback.widget.PlaybackTransportRowView.dispatchKeyEvent(PlaybackTransportRowView.java:71)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at androidx.leanback.widget.BaseGridView.dispatchKeyEvent(BaseGridView.java:1081)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:476)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1861)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.app.Activity.dispatchKeyEvent(Activity.java:4085)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:120)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:138)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:390)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6186)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6054)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5529)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5704)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5761)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5737)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5895)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3217)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2759)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2750)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3194)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.os.MessageQueue.nativePollOnce(Native Method)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.os.MessageQueue.next(MessageQueue.java:335)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.os.Looper.loop(Looper.java:183)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at android.app.ActivityThread.main(ActivityThread.java:7668)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at java.lang.reflect.Method.invoke(Native Method)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
12-17 15:16:22.421 E/ACRA    ( 7408): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
12-17 15:16:22.421 D/ACRA    ( 7408): Building report
12-17 15:16:22.453 D/ACRA    ( 7408): Starting collectors with priority FIRST
12-17 15:16:22.454 D/ACRA    ( 7408): Calling collector org.acra.collector.DropBoxCollector
12-17 15:16:22.454 D/ACRA    ( 7408): Calling collector org.acra.collector.LogCatCollector
12-17 15:16:22.454 D/ACRA    ( 7408): Collector org.acra.collector.DropBoxCollector completed
12-17 15:16:22.454 D/ACRA    ( 7408): Calling collector org.acra.collector.StacktraceCollector
12-17 15:16:22.455 D/ACRA    ( 7408): Collector org.acra.collector.StacktraceCollector completed
12-17 15:16:22.461 D/ACRA    ( 7408): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.16.0` (`160099`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"darcy","BOOTLOADER":"32.00.2019.50-t210-69ebfcbe","BRAND":"NVIDIA","CPU_ABI":"arm64-v8a","CPU_ABI2":"","DEVICE":"mdarcy","DISPLAY":"RQ1A.210105.003.7825230_3167.5736","FINGERPRINT":"NVIDIA\/mdarcy\/mdarcy:11\/RQ1A.210105.003\/7825230_3167.5736:user\/release-keys","HARDWARE":"darcy","HOST":"mobile-u64-5308-d7000","ID":"RQ1A.210105.003","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"NVIDIA","MODEL":"SHIELD Android TV","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"mdarcy","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":["arm64-v8a"],"SUPPORTED_ABIS":["arm64-v8a","armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1665975826000,"TYPE":"user","UNKNOWN":"unknown","USER":"NVIDIA","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"7825230_3167.5736","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"11","RELEASE_OR_CODENAME":"11","SDK":"30","SDK_INT":30,"SECURITY_PATCH":"2022-04-05"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":160099,"VERSION_NAME":"0.16.0"}
```  

### Device information

***Android version***: `11`  
***Device brand***: `NVIDIA`  
***Device product***: `mdarcy`  
***Device model***: `SHIELD Android TV`  

### Crash information

***Start time***: `2023-12-17T08:39:59.503-07:00`  
***Crash time***: `2023-12-17T15:16:22.536-07:00`  

### Application version

0.16.0

### Where did you install the app from?

Google Play

### Device information

NVIDIA SHIELD Android TV Pro Streaming Media Player (2020)

### Android version

SHIELD Android TV 9.1.1 (33.2.0.157)

### Jellyfin server version

10.8.7

**Comment by advokatb** [comment]
Same here. Mi Box. 
The latest Jellyfin for Android TV app.
Got the same error (and crash) randomly every 30-60 minutes.

**Comment by nielsvanvelzen** [comment]
Please re-test with Jellyfin 10.8.13 and Jellyfin for Android TV 0.16.1.

**Comment by AhiyaHiya** [comment]
I was able to update my Ubuntu installation of Jellyfin to `10.8.13.0`, however I was not able to update the NVIDIA Shield to the above listed version.

Using just the updated version of Jellyfin server, it seems that the problem has been resolved. I haven't seen the crash since updating the server.

**Comment by nielsvanvelzen** [comment]
Good to hear it's working now. Closing the issue as resolved.
