### ISSUE TITLE
Crash on re-entring the app if its process has been killed by Android in the meantime (aka The Clock Crash)

### ISSUE THREAD

**Issue by AndreasGB** [jellyfin/jellyfin-androidtv#325]
Currently, the app crashes when re-entered after its process got killed by the system.

To force this crash for debugging purposes, set `Developer Options -> Background Process Limit` to `No background processes`

Stack traces look something like this
```
2020-02-09 16:59:56.728 15398-15398/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.jellyfin.androidtv.debug, PID: 15398
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jellyfin.apiclient.model.dto.UserDto.getName()' on a null object reference
        at org.jellyfin.androidtv.ui.ClockUserView.init(ClockUserView.java:42)
        at org.jellyfin.androidtv.ui.ClockUserView.<init>(ClockUserView.java:25)
        at org.jellyfin.androidtv.browsing.StdBrowseFragment.setupUIElements(StdBrowseFragment.java:300)
        at org.jellyfin.androidtv.browsing.StdBrowseFragment.onActivityCreated(StdBrowseFragment.java:111)
        at org.jellyfin.androidtv.ui.home.HomeFragment.onActivityCreated(HomeFragment.java:90)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2460)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1483)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7157)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Fixing this will probably require rather involved refactoring.

**Comment by nielsvanvelzen** [comment]
This same issue is also triggered when Android tries to recover a crashed activity.
