### ISSUE TITLE
NoSuchMethodError exception when start music playing

### ISSUE THREAD

**Issue by HorkyChen** [jellyfin/jellyfin-androidtv#3305]
### Describe the bug

Enter music library, play any one music or album, after several seconds, app will be crashed.

### Logs

---
client: Jellyfin for Android TV
client_version: 0.16.3
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.NoSuchMethodError: No virtual method getAndSetObject(Ljava/lang/Object;JLjava/lang/Object;)Ljava/lang/Object; in class Lsun/misc/Unsafe; or its super classes (declaration of 'sun.misc.Unsafe' appears in /system/framework/core-libart.jar)
	at com.google.common.util.concurrent.AbstractFuture$UnsafeAtomicHelper.gasWaiters(AbstractFuture.java:1411)
	at com.google.common.util.concurrent.AbstractFuture.releaseWaiters(AbstractFuture.java:1126)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1005)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:782)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.afterRanInterruptiblySuccess(TrustedListenableFutureTask.java:136)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:88)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

```  
***Logcat***: 
```log
01-07 21:08:32.720 I/jellyfin-apiclient( 7076): Response received from: http://192.168.31.230:8096/Users/02740a34-f66e-4a9a-bd06-b866c0c75ef1/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=7f09ac8d-4f2f-9f30-6712-c0d21acd9863&GroupItems=true&format=json
01-07 21:08:32.750 D/ItemRowAdapterHelperKt( 7076): Creating items from 0 existing and 50 new, adapter size is 0
01-07 21:08:32.770 I/jellyfin-apiclient( 7076): Response received from: http://192.168.31.230:8096/Users/02740a34-f66e-4a9a-bd06-b866c0c75ef1/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=7e64e319-657a-9516-ec78-490da03edccb&GroupItems=true&format=json
01-07 21:08:32.772 D/ItemRowAdapterHelperKt( 7076): Creating items from 0 existing and 5 new, adapter size is 0
01-07 21:08:32.863 D/ACRA    ( 7076): onActivityStopped class org.jellyfin.androidtv.ui.startup.StartupActivity
01-07 21:08:32.873 D/ACRA    ( 7076): onActivityDestroyed class org.jellyfin.androidtv.ui.startup.StartupActivity
01-07 21:08:32.874 D/Compose Focus( 7076): Owner FocusChanged(false)
01-07 21:08:32.876 D/Compose Focus( 7076): Owner FocusChanged(true)
01-07 21:08:32.876 D/Compose Focus( 7076): Owner FocusChanged(false)
01-07 21:08:33.441 W/RenderInspector( 7076): QueueBuffer time out on org.jellyfin.androidtv/org.jellyfin.androidtv.ui.browsing.MainActivity, count=1, avg=16 ms, max=16 ms.
01-07 21:08:33.762 D/AudioManager( 7076): preDispatchKeyEvent 22repeat count: 0
01-07 21:08:33.886 I/AutoBitrate( 7076): Auto bitrate set to: 9470257
01-07 21:08:33.911 D/AudioManager( 7076): preDispatchKeyEvent 22repeat count: 0
01-07 21:08:34.211 D/AudioManager( 7076): preDispatchKeyEvent 23repeat count: 0
01-07 21:08:34.363 D/AudioManager( 7076): preDispatchKeyEvent 23repeat count: 0
01-07 21:08:34.368 D/ItemLauncher( 7076): Item selected: 1 - Music (CollectionFolder)
01-07 21:08:34.370 D/ItemLauncher( 7076): **** Collection type: music
01-07 21:08:34.397 D/NavigationRepositoryImp( 7076): Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.browsing.BrowseViewFragment (Kotlin reflection is not available), arguments=Bundle[{folder={"Name":"Music","ServerId":"70f5ecaac60a4a1c88147b668d06b264","Id":"7e64e319-657a-9516-ec78-490da03edccb","Etag":"333976604329540e3474d7c1ab480e59","DateCreated":"2024-01-06T15:13:14+08:00","CanDelete":false,"CanDownload":false,"SupportsSync":false,"SortName":"music","ExternalUrls":[],"Path":"/var/lib/jellyfin/root/default/Music","EnableMediaSourceDisplay":false,"Taglines":[],"Genres":[],"PlayAccess":"Full","RemoteTrailers":[],"ProviderIds":{},"IsFolder":true,"ParentId":"e9d5075a-555c-1cbc-394e-ec4cef295274","Type":"CollectionFolder","People":[],"Studios":[],"GenreItems":[],"LocalTrailerCount":0,"UserData":{"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"7e64e319-657a-9516-ec78-490da03edccb"},"ChildCount":8,"SpecialFeatureCount":0,"DisplayPreferencesId":"7e64e319657a9516ec78490da03edccb","Tags":[],"PrimaryImageAspectRatio":1.3333333333333333,"CollectionType":"music","ImageTags":{"Primary":"c482ebebd78dcd5111e0dd829f69612a"},"BackdropImageTags":[],"ImageBlurHashes":{"Primary":{"c482ebebd78dcd5111e0dd829f69612a":"Vb2u4ef,ZzkDkWkXfPaefPkCVBe.kXadaeaKfRj?jZaK"}},"LocationType":"FileSystem","LockedFields":[],"LockData":false}}]) (via navigate function)
01-07 21:08:34.407 I/org.jellyfin.sdk.api.sockets.SocketInstance( 7076): Removing subscription for ScheduledTasksInfoMessage
01-07 21:08:34.408 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession( 7076): Sending (raw) message {"MessageType":"ScheduledTasksInfoStop","Data":{}}
01-07 21:08:34.408 I/org.jellyfin.sdk.api.sockets.SocketInstance( 7076): Removing subscription for ActivityLogEntryMessage
01-07 21:08:34.410 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession( 7076): Sending (raw) message {"MessageType":"ActivityLogEntryStop","Data":{}}
01-07 21:08:34.411 I/org.jellyfin.sdk.api.sockets.SocketInstance( 7076): Removing subscription for SessionsMessage
01-07 21:08:34.412 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession( 7076): Sending (raw) message {"MessageType":"SessionsStop","Data":{}}
01-07 21:08:34.443 D/jellyfin-apiclient( 7076): Adding request to queue: http://192.168.31.230:8096/Users/02740a34-f66e-4a9a-bd06-b866c0c75ef1/Items/Latest?Limit=50&IncludeItemTypes=Audio&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&ParentId=7e64e319-657a-9516-ec78-490da03edccb&GroupItems=true&format=json
01-07 21:08:34.449 D/jellyfin-apiclient( 7076): Adding request to queue: http://192.168.31.230:8096/Users/02740a34-f66e-4a9a-bd06-b866c0c75ef1/Items?Filters=IsPlayed&ImageTypeLimit=1&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount&sortOrder=Descending&SortBy=DatePlayed&IncludeItemTypes=Audio&ParentId=7e64e319-657a-9516-ec78-490da03edccb&EnableTotalRecordCount=false&recursive=true&Limit=50&format=json
01-07 21:08:34.450 D/jellyfin-apiclient( 7076): Adding request to queue: http://192.168.31.230:8096/Users/02740a34-f66e-4a9a-bd06-b866c0c75ef1/Items?Filters=IsFavorite&ImageTypeLimit=1&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount&recursive=true&Limit=60&SortBy=SortName&IncludeItemTypes=MusicAlbum%2CMusicArtist&ParentId=7e64e319-657a-9516-ec78-490da03edccb&format=json
01-07 21:08:34.452 D/jellyfin-apiclient( 7076): Adding request to queue: http://192.168.31.230:8096/Users/02740a34-f66e-4a9a-bd06-b866c0c75ef1/Items?ImageTypeLimit=1&Fields=PrimaryImageAspectRatio%2CCumulativeRunTimeTicks%2CChildCount&recursive=true&sortOrder=Descending&Limit=60&SortBy=DateCreated&IncludeItemTypes=Playlist&format=json
01-07 21:08:34.786 W/View    ( 7076): requestLayout() improperly called by android.widget.TextView{dc74aed V.ED..... ......ID 120,40-1598,126 #7f0b02f5 app:id/title isViewGroup=false mPrivateFlags = 81200810 mViewFlags=18000000} during layout: running second layout pass
01-07 21:08:34.786 W/View    ( 7076): requestLayout() improperly called by android.widget.LinearLayout{6fd4d22 V.E...... ......ID 120,132-1618,172 #7f0b01a7 app:id/infoRow isViewGroup=true mPrivateFlags = 81200890 mViewFlags=18000080} during layout: running second layout pass
01-07 21:08:34.812 I/jellyfin-apiclient( 7076): Response received from: http://192.168.31.230:8096/Users/02740a34-f66e-4a9a-bd06-b866c0c75ef1/Items?Filters=IsFavorite&ImageTypeLimit=1&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount&recursive=true&Limit=60&SortBy=SortName&IncludeItemTypes=MusicAlbum%2CMusicArtist&ParentId=7e64e319-657a-9516-ec78-490da03edccb&format=json
01-07 21:08:34.812 I/jellyfin-apiclient( 7076): Response received from: http://192.168.31.230:8096/Users/02740a34-f66e-4a9a-bd06-b866c0c75ef1/Items?ImageTypeLimit=1&Fields=PrimaryImageAspectRatio%2CCumulativeRunTimeTicks%2CChildCount&recursive=true&sortOrder=Descending&Limit=60&SortBy=DateCreated&IncludeItemTypes=Playlist&format=json
01-07 21:08:34.814 D/ItemRowAdapterHelperKt( 7076): Creating items from 1 existing and 1 new, adapter size is 1
01-07 21:08:34.816 I/jellyfin-apiclient( 7076): Response received from: http://192.168.31.230:8096/Users/02740a34-f66e-4a9a-bd06-b866c0c75ef1/Items/Latest?Limit=50&IncludeItemTypes=Audio&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&ParentId=7e64e319-657a-9516-ec78-490da03edccb&GroupItems=true&format=json
01-07 21:08:34.818 D/ItemRowAdapterHelperKt( 7076): Creating items from 0 existing and 5 new, adapter size is 0
01-07 21:08:34.821 I/jellyfin-apiclient( 7076): Response received from: http://192.168.31.230:8096/Users/02740a34-f66e-4a9a-bd06-b866c0c75ef1/Items?Filters=IsPlayed&ImageTypeLimit=1&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount&sortOrder=Descending&SortBy=DatePlayed&IncludeItemTypes=Audio&ParentId=7e64e319-657a-9516-ec78-490da03edccb&EnableTotalRecordCount=false&recursive=true&Limit=50&format=json
01-07 21:08:34.853 D/ItemRowAdapterHelperKt( 7076): Creating items from 0 existing and 50 new, adapter size is 0
01-07 21:08:35.443 W/View    ( 7076): requestLayout() improperly called by android.widget.TextView{dc74aed V.ED..... ......ID 120,40-1598,126 #7f0b02f5 app:id/title isViewGroup=false mPrivateFlags = 81200810 mViewFlags=18000000} during layout: running second layout pass
01-07 21:08:35.443 W/View    ( 7076): requestLayout() improperly called by android.widget.LinearLayout{6fd4d22 V.E...... ......ID 120,132-1618,172 #7f0b01a7 app:id/infoRow isViewGroup=true mPrivateFlags = 81200890 mViewFlags=18000080} during layout: running second layout pass
01-07 21:08:35.456 D/OpenGLRenderer( 7076):   Allocate layer: 1920x1088
01-07 21:08:35.459 D/OpenGLRenderer( 7076):   Allocate layer: 1920x1088
01-07 21:08:35.473 I/Choreographer( 7076): Skipped 34 frames!  The application may be doing too much work on its main thread.
01-07 21:08:35.482 V/RenderScript( 7076): 0xee2e3000 Launching thread(s), CPUs 4
01-07 21:08:37.005 D/AudioManager( 7076): preDispatchKeyEvent 20repeat count: 0
01-07 21:08:37.213 D/AudioManager( 7076): preDispatchKeyEvent 20repeat count: 0
01-07 21:08:37.421 D/AudioManager( 7076): preDispatchKeyEvent 20repeat count: 0
01-07 21:08:37.572 D/AudioManager( 7076): preDispatchKeyEvent 20repeat count: 0
01-07 21:08:38.471 D/AudioManager( 7076): preDispatchKeyEvent 19repeat count: 0
01-07 21:08:38.652 D/AudioManager( 7076): preDispatchKeyEvent 19repeat count: 0
01-07 21:08:38.831 D/AudioManager( 7076): preDispatchKeyEvent 19repeat count: 0
01-07 21:08:39.042 D/AudioManager( 7076): preDispatchKeyEvent 19repeat count: 0
01-07 21:08:39.941 D/AudioManager( 7076): preDispatchKeyEvent 19repeat count: 0
01-07 21:08:40.151 D/AudioManager( 7076): preDispatchKeyEvent 19repeat count: 0
01-07 21:08:40.901 D/AudioManager( 7076): preDispatchKeyEvent 22repeat count: 0
01-07 21:08:40.961 D/AudioManager( 7076): preDispatchKeyEvent 22repeat count: 0
01-07 21:08:41.024 D/AudioManager( 7076): preDispatchKeyEvent 22repeat count: 0
01-07 21:08:41.321 D/AudioManager( 7076): preDispatchKeyEvent 22repeat count: 0
01-07 21:08:41.411 D/AudioManager( 7076): preDispatchKeyEvent 22repeat count: 0
01-07 21:08:41.533 D/AudioManager( 7076): preDispatchKeyEvent 22repeat count: 0
01-07 21:08:41.892 D/AudioManager( 7076): preDispatchKeyEvent 23repeat count: 0
01-07 21:08:42.041 D/AudioManager( 7076): preDispatchKeyEvent 23repeat count: 0
01-07 21:08:42.046 D/ItemLauncher( 7076): Item selected: 3 - 4D顶级环绕 (MusicAlbum)
01-07 21:08:42.048 D/NavigationRepositoryImp( 7076): Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.itemdetail.ItemListFragment (Kotlin reflection is not available), arguments=Bundle[{ItemId=eff7fc7a-a518-ffc6-773c-c11b9eb147c0}]) (via navigate function)
01-07 21:08:42.127 W/art     ( 7076): Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
01-07 21:08:42.163 D/jellyfin-apiclient( 7076): Adding request to queue: http://192.168.31.230:8096/Users/02740a34-f66e-4a9a-bd06-b866c0c75ef1/Items/eff7fc7a-a518-ffc6-773c-c11b9eb147c0?format=json
01-07 21:08:42.212 I/ItemListFragment( 7076): Got playback state change event IDLE for item <unknown>
01-07 21:08:42.236 I/jellyfin-apiclient( 7076): Response received from: http://192.168.31.230:8096/Users/02740a34-f66e-4a9a-bd06-b866c0c75ef1/Items/eff7fc7a-a518-ffc6-773c-c11b9eb147c0?format=json
01-07 21:08:42.287 D/jellyfin-apiclient( 7076): Adding request to queue: http://192.168.31.230:8096/Users/02740a34-f66e-4a9a-bd06-b866c0c75ef1/Items?Fields=PrimaryImageAspectRatio%2CGenres%2CChildCount&recursive=true&Limit=200&SortBy=SortName&IncludeItemTypes=Audio&ParentId=eff7fc7aa518ffc6773cc11b9eb147c0&format=json
01-07 21:08:42.336 D/OpenGLRenderer( 7076):   Allocate layer: 1920x1088
01-07 21:08:42.406 I/jellyfin-apiclient( 7076): Response received from: http://192.168.31.230:8096/Users/02740a34-f66e-4a9a-bd06-b866c0c75ef1/Items?Fields=PrimaryImageAspectRatio%2CGenres%2CChildCount&recursive=true&Limit=200&SortBy=SortName&IncludeItemTypes=Audio&ParentId=eff7fc7aa518ffc6773cc11b9eb147c0&format=json
01-07 21:08:44.641 I/art     ( 7076): Background sticky concurrent mark sweep GC freed 112692(6MB) AllocSpace objects, 41(1556KB) LOS objects, 17% free, 38MB/46MB, paused 2.032ms total 102.025ms
01-07 21:08:44.651 D/AudioManager( 7076): preDispatchKeyEvent 23repeat count: 0
01-07 21:08:44.801 D/AudioManager( 7076): preDispatchKeyEvent 23repeat count: 0
01-07 21:08:44.809 D/ItemListFragment( 7076): play items: 79, ndx: 0, shuffle: false
01-07 21:08:44.829 D/DefaultPlayerQueueState( 7076): Queue changed, setting index to 0
01-07 21:08:44.832 D/NavigationRepositoryImp( 7076): Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.playback.AudioNowPlayingFragment (Kotlin reflection is not available), arguments=Bundle[{}]) (via navigate function)
01-07 21:08:44.842 I/HomeRowsFragment( 7076): Updating audio queue in HomeFragment (onQueueStatusChanged)
01-07 21:08:44.844 D/DefaultMediaStreamState( 7076): Queue entry changed to org.jellyfin.playback.jellyfin.queue.item.BaseItemDtoUserQueueEntry@a635331
01-07 21:08:44.847 I/org.jellyfin.sdk.api.client.KtorClient( 7076): POST http://192.168.31.230:8096/Items/573f6551-93b5-2433-c372-e20f57e20d50/PlaybackInfo
01-07 21:08:44.874 E/ACRA    ( 7076): ACRA caught a NoSuchMethodError for org.jellyfin.androidtv
01-07 21:08:44.874 E/ACRA    ( 7076): java.lang.NoSuchMethodError: No virtual method getAndSetObject(Ljava/lang/Object;JLjava/lang/Object;)Ljava/lang/Object; in class Lsun/misc/Unsafe; or its super classes (declaration of 'sun.misc.Unsafe' appears in /system/framework/core-libart.jar)
01-07 21:08:44.874 E/ACRA    ( 7076): 	at com.google.common.util.concurrent.AbstractFuture$UnsafeAtomicHelper.gasWaiters(AbstractFuture.java:1411)
01-07 21:08:44.874 E/ACRA    ( 7076): 	at com.google.common.util.concurrent.AbstractFuture.releaseWaiters(AbstractFuture.java:1126)
01-07 21:08:44.874 E/ACRA    ( 7076): 	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1005)
01-07 21:08:44.874 E/ACRA    ( 7076): 	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:782)
01-07 21:08:44.874 E/ACRA    ( 7076): 	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.afterRanInterruptiblySuccess(TrustedListenableFutureTask.java:136)
01-07 21:08:44.874 E/ACRA    ( 7076): 	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:88)
01-07 21:08:44.874 E/ACRA    ( 7076): 	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
01-07 21:08:44.874 E/ACRA    ( 7076): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-07 21:08:44.874 E/ACRA    ( 7076): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-07 21:08:44.874 E/ACRA    ( 7076): 	at java.lang.Thread.run(Thread.java:818)
01-07 21:08:44.874 D/ACRA    ( 7076): Building report
01-07 21:08:44.875 D/ACRA    ( 7076): Starting collectors with priority FIRST
01-07 21:08:44.880 D/ACRA    ( 7076): Calling collector org.acra.collector.DropBoxCollector
01-07 21:08:44.880 D/ACRA    ( 7076): Collector org.acra.collector.DropBoxCollector completed
01-07 21:08:44.883 D/ACRA    ( 7076): Calling collector org.acra.collector.LogCatCollector
01-07 21:08:44.885 D/ACRA    ( 7076): Calling collector org.acra.collector.StacktraceCollector
01-07 21:08:44.886 D/ACRA    ( 7076): Collector org.acra.collector.StacktraceCollector completed
01-07 21:08:44.939 D/ACRA    ( 7076): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.16.3` (`160399`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"xmen","BOOTLOADER":"unknown","BRAND":"Xiaomi","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"xmen","DISPLAY":"22.11.28.3390","FINGERPRINT":"Xiaomi\/xmen\/xmen:6.0.1\/MHC19J\/3390:user\/release-keys","HARDWARE":"amlogic","HOST":"c3-mitv-bsp-build02.bj","ID":"MHC19J","IS_DEBUGGABLE":false,"MANUFACTURER":"xiaomi","MODEL":"MiTV4-ANSM0","PRODUCT":"xmen","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1669644800000,"TYPE":"user","UNKNOWN":"unknown","USER":"jenkins","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"3390","PREVIEW_SDK_INT":0,"RELEASE":"6.0.1","RESOURCES_SDK_INT":23,"SDK":"23","SDK_INT":23,"SECURITY_PATCH":"2017-04-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":160399,"VERSION_NAME":"0.16.3"}
```  

### Device information

***Android version***: `6.0.1`  
***Device brand***: `Xiaomi`  
***Device product***: `xmen`  
***Device model***: `MiTV4-ANSM0`  

### Crash information

***Start time***: `2024-01-07T21:08:29.171+08:00`  
***Crash time***: `2024-01-07T21:08:45.130+08:00`  

### Application version

0.16.3

### Where did you install the app from?

None

### Device information

Xiaomi TV

### Android version

Not sure

### Jellyfin server version

10.8.13

**Comment by HorkyChen** [comment]
Tested with 0.16.4, mp3 files could be played normally, but flac and ogg files were crashed.
