### ISSUE TITLE
Random NullPointerException java.util.UUID after playback

### ISSUE THREAD

**Issue by RealGreenDragon** [jellyfin/jellyfin-androidtv#3311]
### Describe the bug

Sometimes after playback (both with internal or external player) Jellyfin Android TV app crash.

### Logs

---
client: Jellyfin for Android TV
client_version: 0.16.4
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.UUID org.jellyfin.sdk.model.api.UserDto.getId()' on a null object reference
	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment$3.run(FullDetailsFragment.java:275)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7719)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```  
***Logcat***: 
```log
--------- beginning of crash
01-13 21:24:15.737 E/AndroidRuntime(17335): FATAL EXCEPTION: main
01-13 21:24:15.737 E/AndroidRuntime(17335): Process: org.jellyfin.androidtv, PID: 17335
01-13 21:24:15.737 E/AndroidRuntime(17335): java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.UUID org.jellyfin.sdk.model.api.UserDto.getId()' on a null object reference
01-13 21:24:15.737 E/AndroidRuntime(17335): 	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment$3.run(FullDetailsFragment.java:275)
01-13 21:24:15.737 E/AndroidRuntime(17335): 	at android.os.Handler.handleCallback(Handler.java:938)
01-13 21:24:15.737 E/AndroidRuntime(17335): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-13 21:24:15.737 E/AndroidRuntime(17335): 	at android.os.Looper.loop(Looper.java:223)
01-13 21:24:15.737 E/AndroidRuntime(17335): 	at android.app.ActivityThread.main(ActivityThread.java:7719)
01-13 21:24:15.737 E/AndroidRuntime(17335): 	at java.lang.reflect.Method.invoke(Native Method)
01-13 21:24:15.737 E/AndroidRuntime(17335): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
01-13 21:24:15.737 E/AndroidRuntime(17335): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
--------- beginning of main
01-13 21:24:31.441 I/jellyfin-apiclient(21246): Response received from: http://<IP>:8096/Users/5be6b3ac-c1cf-478b-b9ca-0f18b86c2fb0/Items?ParentId=253bc9fc-2ae4-cb0a-47d9-9e75b7e36923&StartIndex=72&SortBy=SortName&recursive=true&Fields=PrimaryImageAspectRatio%2CChildCount%2CMediaSources%2CMediaStreams%2CDisplayPreferencesId&sortOrder=Ascending&Limit=36&IncludeItemTypes=Movie&format=json
01-13 21:24:32.046 I/lyfin.androidt(21246): NativeAlloc concurrent copying GC freed 135048(6100KB) AllocSpace objects, 66(2432KB) LOS objects, 49% free, 12MB/25MB, paused 169us total 180.257ms
01-13 21:24:32.690 W/RecyclerView(21246): No adapter attached; skipping layout
01-13 21:24:32.745 I/jellyfin-apiclient(21246): Response received from: http://<IP>:8096/Users/5be6b3ac-c1cf-478b-b9ca-0f18b86c2fb0/Items/a055470f-8251-f6c2-c651-25f1c03efa68?format=json
01-13 21:24:33.036 I/jellyfin-apiclient(21246): Response received from: http://<IP>:8096/Items/a055470f8251f6c2c65125f1c03efa68/Similar?Fields=PrimaryImageAspectRatio%2CChildCount&UserId=5be6b3ac-c1cf-478b-b9ca-0f18b86c2fb0&Limit=10&format=json
01-13 21:24:36.061 I/lyfin.androidt(21246): Could not find corresponding native window for surface
01-13 21:24:36.088 I/jellyfin-apiclient(21246): Response received from: http://<IP>:8096/Items/a055470f-8251-f6c2-c651-25f1c03efa68/PlaybackInfo?format=json
01-13 21:24:36.106 I/ExternalPlayerActivity(21246): Starting external playback of path: http://<IP>:8096/Videos/a055470f-8251-f6c2-c651-25f1c03efa68/stream.mkv?api_key=8222b7eeec2a4b879b1967c798e443bc&DeviceId=fbbb996ec9a902821f78d912d976f0b70939ce57&MediaSourceId=a055470f8251f6c2c65125f1c03efa68&Tag=ce593116ad4d92b2d43b0b4226547189&Static=true and mime: video/mkv at position/ms: 0
01-13 21:24:36.109 I/ReportingHelper(21246): Playback of L'arte della guerra started.
01-13 21:24:36.185 I/SessionRepositoryImpl$restoreSession(21246): Restoring session
01-13 21:24:36.185 I/SessionRepositoryImpl(21246): Destroying current session
01-13 21:24:36.255 I/jellyfin-apiclient(21246): Response received from: http://<IP>:8096/Sessions/Playing
01-13 21:24:36.330 I/jellyfin-apiclient(21246): Response received from: http://<IP>:8096/Sessions/Playing/Progress
01-13 21:24:36.411 I/lyfin.androidt(21246): Could not find corresponding native window for surface
01-13 21:25:06.295 I/ReportingHelper(21246): ReportingHelper.reportStopped called for a055470f-8251-f6c2-c651-25f1c03efa68 at position 0
01-13 21:25:06.300 I/jellyfin-apiclient(21246): ReportPlaybackStopped: Item a055470f-8251-f6c2-c651-25f1c03efa68, Ticks: 0
01-13 21:25:06.450 I/lyfin.androidt(21246): Could not find corresponding native window for surface
01-13 21:25:06.584 I/jellyfin-apiclient(21246): Response received from: http://<IP>:8096/Sessions/Playing/Stopped
01-13 21:25:09.019 I/lyfin.androidt(21246): Could not find corresponding native window for surface
01-13 21:25:09.075 W/MainActivity(21246): Activity org.jellyfin.androidtv.ui.browsing.MainActivity started without a session, bouncing to StartupActivity
01-13 21:25:09.220 I/ActivityThemeExtensionsKt(21246): Applying theme DARK
01-13 21:25:09.335 I/org.jellyfin.sdk.api.client.KtorClient(21246): GET http://<IP>:8096/Users/Public
01-13 21:25:09.347 I/org.jellyfin.sdk.api.client.KtorClient(21246): GET http://<IP>:8096/Users/Public
01-13 21:25:09.858 E/AndroidRuntime(21246): FATAL EXCEPTION: main
01-13 21:25:09.858 E/AndroidRuntime(21246): Process: org.jellyfin.androidtv, PID: 21246
01-13 21:25:09.858 E/AndroidRuntime(21246): java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.UUID org.jellyfin.sdk.model.api.UserDto.getId()' on a null object reference
01-13 21:25:09.858 E/AndroidRuntime(21246): 	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment$3.run(FullDetailsFragment.java:275)
01-13 21:25:09.858 E/AndroidRuntime(21246): 	at android.os.Handler.handleCallback(Handler.java:938)
01-13 21:25:09.858 E/AndroidRuntime(21246): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-13 21:25:09.858 E/AndroidRuntime(21246): 	at android.os.Looper.loop(Looper.java:223)
01-13 21:25:09.858 E/AndroidRuntime(21246): 	at android.app.ActivityThread.main(ActivityThread.java:7719)
01-13 21:25:09.858 E/AndroidRuntime(21246): 	at java.lang.reflect.Method.invoke(Native Method)
01-13 21:25:09.858 E/AndroidRuntime(21246): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
01-13 21:25:09.858 E/AndroidRuntime(21246): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
01-13 21:25:09.859 E/ACRA    (21246): ACRA caught a NullPointerException for org.jellyfin.androidtv
01-13 21:25:09.859 E/ACRA    (21246): java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.UUID org.jellyfin.sdk.model.api.UserDto.getId()' on a null object reference
01-13 21:25:09.859 E/ACRA    (21246): 	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment$3.run(FullDetailsFragment.java:275)
01-13 21:25:09.859 E/ACRA    (21246): 	at android.os.Handler.handleCallback(Handler.java:938)
01-13 21:25:09.859 E/ACRA    (21246): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-13 21:25:09.859 E/ACRA    (21246): 	at android.os.Looper.loop(Looper.java:223)
01-13 21:25:09.859 E/ACRA    (21246): 	at android.app.ActivityThread.main(ActivityThread.java:7719)
01-13 21:25:09.859 E/ACRA    (21246): 	at java.lang.reflect.Method.invoke(Native Method)
01-13 21:25:09.859 E/ACRA    (21246): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
01-13 21:25:09.859 E/ACRA    (21246): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```  

### App information

***App version***: `0.16.4` (`160499`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"karat","BOOTLOADER":"unknown","BRAND":"Amazon","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"karat","DISPLAY":"RS8102.1967N","FINGERPRINT":"Amazon\/karat\/karat:11\/RS8102.1967N\/0021978656644:user\/amz-p,release-keys","HARDWARE":"mt8696","HOST":"<HOST>","ID":"RS8102.1967N","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Amazon","MODEL":"AFTKM","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"karat","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"amz-p,release-keys","TIME":1701543841000,"TYPE":"user","UNKNOWN":"unknown","USER":"build","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"RP1A.200720.009","CODENAME":"REL","INCREMENTAL":"0021978656644","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"11","RELEASE_OR_CODENAME":"11","SDK":"30","SDK_INT":30,"SECURITY_PATCH":"2020-09-05"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":160499,"VERSION_NAME":"0.16.4"}
```  

### Device information

***Android version***: `11`  
***Device brand***: `Amazon`  
***Device product***: `karat`  
***Device model***: `AFTKM`  

### Crash information

***Start time***: `2024-01-13T21:24:20.109+01:00`  
***Crash time***: `2024-01-13T21:25:09.900+01:00`  

### Application version

0.16.4

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon Fire TV Stick 4K (2021)

### Android version

Fire OS 8

### Jellyfin server version

10.8.13

**Comment by RealGreenDragon** [comment]
I see now that this crash is similar at #3146 and #2703 (with v0.15.x).

**Comment by Alliyance** [comment]
Same


`client: Jellyfin for Android TV
client_version: 0.16.4
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.jellyfin.androidtv/org.jellyfin.androidtv.ui.browsing.MainActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2953)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3094)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:6775)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException
	at org.jellyfin.androidtv.data.querying.StdItemQuery.<init>(StdItemQuery.kt:23)
	at org.jellyfin.androidtv.ui.browsing.BrowseGridFragment.setupQueries(BrowseGridFragment.java:545)
	at org.jellyfin.androidtv.ui.browsing.BrowseGridFragment.onCreate(BrowseGridFragment.java:177)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3094)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:504)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:268)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:122)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2941)
	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:252)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:219)
	at org.jellyfin.androidtv.ui.browsing.MainActivity.onCreate(MainActivity.kt:55)
	at android.app.Activity.performCreate(Activity.java:7169)
	at android.app.Activity.performCreate(Activity.java:7159)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2933)
	... 11 more

```  
***Logcat***: 
```log
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at org.jellyfin.androidtv.preference.PreferencesRepository.getLibraryPreferences(PreferencesRepository.kt:23)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at org.jellyfin.androidtv.ui.browsing.BrowseGridFragment.onCreate(BrowseGridFragment.java:164)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3094)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:504)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:268)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:122)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2941)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:252)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:219)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at org.jellyfin.androidtv.ui.browsing.MainActivity.onCreate(MainActivity.kt:55)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at android.app.Activity.performCreate(Activity.java:7169)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at android.app.Activity.performCreate(Activity.java:7159)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2933)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3094)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at android.os.Looper.loop(Looper.java:211)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at android.app.ActivityThread.main(ActivityThread.java:6775)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at java.lang.reflect.Method.invoke(Native Method)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-13 13:59:17.965 E/DisplayPreferencesStore(30405): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-13 13:59:17.965 I/DisplayPreferencesStore(30405): Creating an empty DisplayPreferencesDto for next commit.
01-13 13:59:17.981 E/AndroidRuntime(30405): FATAL EXCEPTION: main
01-13 13:59:17.981 E/AndroidRuntime(30405): Process: org.jellyfin.androidtv, PID: 30405
01-13 13:59:17.981 E/AndroidRuntime(30405): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.jellyfin.androidtv/org.jellyfin.androidtv.ui.browsing.MainActivity}: java.lang.NullPointerException
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2953)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3094)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at android.os.Looper.loop(Looper.java:211)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at android.app.ActivityThread.main(ActivityThread.java:6775)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at java.lang.reflect.Method.invoke(Native Method)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-13 13:59:17.981 E/AndroidRuntime(30405): Caused by: java.lang.NullPointerException
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at org.jellyfin.androidtv.data.querying.StdItemQuery.<init>(StdItemQuery.kt:23)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at org.jellyfin.androidtv.ui.browsing.BrowseGridFragment.setupQueries(BrowseGridFragment.java:545)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at org.jellyfin.androidtv.ui.browsing.BrowseGridFragment.onCreate(BrowseGridFragment.java:177)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3094)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:504)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:268)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:122)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2941)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:252)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:219)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at org.jellyfin.androidtv.ui.browsing.MainActivity.onCreate(MainActivity.kt:55)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at android.app.Activity.performCreate(Activity.java:7169)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at android.app.Activity.performCreate(Activity.java:7159)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2933)
01-13 13:59:17.981 E/AndroidRuntime(30405): 	... 11 more
01-13 13:59:17.983 E/ACRA    (30405): ACRA caught a RuntimeException for org.jellyfin.androidtv
01-13 13:59:17.983 E/ACRA    (30405): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.jellyfin.androidtv/org.jellyfin.androidtv.ui.browsing.MainActivity}: java.lang.NullPointerException
01-13 13:59:17.983 E/ACRA    (30405): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2953)
01-13 13:59:17.983 E/ACRA    (30405): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3094)
01-13 13:59:17.983 E/ACRA    (30405): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
01-13 13:59:17.983 E/ACRA    (30405): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
01-13 13:59:17.983 E/ACRA    (30405): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
01-13 13:59:17.983 E/ACRA    (30405): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
01-13 13:59:17.983 E/ACRA    (30405): 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-13 13:59:17.983 E/ACRA    (30405): 	at android.os.Looper.loop(Looper.java:211)
01-13 13:59:17.983 E/ACRA    (30405): 	at android.app.ActivityThread.main(ActivityThread.java:6775)
01-13 13:59:17.983 E/ACRA    (30405): 	at java.lang.reflect.Method.invoke(Native Method)
01-13 13:59:17.983 E/ACRA    (30405): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-13 13:59:17.983 E/ACRA    (30405): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-13 13:59:17.983 E/ACRA    (30405): Caused by: java.lang.NullPointerException
01-13 13:59:17.983 E/ACRA    (30405): 	at org.jellyfin.androidtv.data.querying.StdItemQuery.<init>(StdItemQuery.kt:23)
01-13 13:59:17.983 E/ACRA    (30405): 	at org.jellyfin.androidtv.ui.browsing.BrowseGridFragment.setupQueries(BrowseGridFragment.java:545)
01-13 13:59:17.983 E/ACRA    (30405): 	at org.jellyfin.androidtv.ui.browsing.BrowseGridFragment.onCreate(BrowseGridFragment.java:177)
01-13 13:59:17.983 E/ACRA    (30405): 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3094)
01-13 13:59:17.983 E/ACRA    (30405): 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:504)
01-13 13:59:17.983 E/ACRA    (30405): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:268)
01-13 13:59:17.983 E/ACRA    (30405): 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:122)
01-13 13:59:17.983 E/ACRA    (30405): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
01-13 13:59:17.983 E/ACRA    (30405): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
01-13 13:59:17.983 E/ACRA    (30405): 	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2941)
01-13 13:59:17.983 E/ACRA    (30405): 	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:252)
01-13 13:59:17.983 E/ACRA    (30405): 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:219)
01-13 13:59:17.983 E/ACRA    (30405): 	at org.jellyfin.androidtv.ui.browsing.MainActivity.onCreate(MainActivity.kt:55)
01-13 13:59:17.983 E/ACRA    (30405): 	at android.app.Activity.performCreate(Activity.java:7169)
01-13 13:59:17.983 E/ACRA    (30405): 	at android.app.Activity.performCreate(Activity.java:7159)
01-13 13:59:17.983 E/ACRA    (30405): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
01-13 13:59:17.983 E/ACRA    (30405): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2933)
01-13 13:59:17.983 E/ACRA    (30405): 	... 11 more

```  

### App information

***App version***: `0.16.4` (`160499`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"sheldonp","BOOTLOADER":"unknown","BRAND":"Amazon","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"sheldonp","DISPLAY":"PS7664.3772N","FINGERPRINT":"Amazon\/sheldonp\/sheldonp:9\/PS7664.3772N\/0029159767040:user\/amz-p,release-keys","HARDWARE":"mt8695","HOST":"i3-ri-14-use1a-b-16-04-fos-121","ID":"PS7664.3772N","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Amazon","MODEL":"AFTSSS","PERMISSIONS_REVIEW_REQUIRED":false,"PRODUCT":"sheldonp","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"amz-p,release-keys","TIME":1695416111000,"TYPE":"user","UNKNOWN":"unknown","USER":"build","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"PPR1.180610.009","CODENAME":"REL","FIRST_SDK_INT":28,"INCREMENTAL":"0029159767172","PREVIEW_SDK_INT":0,"RELEASE":"9","RESOURCES_SDK_INT":28,"SDK":"28","SDK_INT":28,"SECURITY_PATCH":"2023-08-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":160499,"VERSION_NAME":"0.16.4"}
```  

### Device information

***Android version***: `9`  
***Device brand***: `Amazon`  
***Device product***: `sheldonp`  
***Device model***: `AFTSSS`  

### Crash information

***Start time***: `2024-01-13T13:59:17.341-05:00`  
***Crash time***: `2024-01-13T13:59:18.111-05:00`  
`

**Comment by fice-t** [comment]
I have another stack trace (this one without `MainActivity.onCreate`), but I can't seem to reproduce it. I first played a video, then went back once or twice, and then went to the home screen and back.

All of these result from `StdItemQuery` doing `userId = get<UserRepository>().currentUser.value!!.id` (`setupQueries` does this as well). Should the code attempt to wait until the current user is (re)validated, or should it fall back to a different fragment?

```
FATAL EXCEPTION: main
Process: org.jellyfin.androidtv.debug, PID: 23809
java.lang.NullPointerException
	at org.jellyfin.androidtv.data.querying.StdItemQuery.<init>(StdItemQuery.kt:23)
	at org.jellyfin.androidtv.ui.browsing.BrowseGridFragment.setupQueries(BrowseGridFragment.java:545)
	at org.jellyfin.androidtv.ui.browsing.BrowseGridFragment.onCreate(BrowseGridFragment.java:177)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3094)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:504)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:268)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by nielsvanvelzen** [comment]
Duplicate #2703
