### ISSUE TITLE
Crash When App Start

### ISSUE THREAD

**Issue by johnzhou2011** [jellyfin/jellyfin-androidtv#3526]
### Describe the bug

1.Start
2.Crash

### Logs

---
client: Jellyfin for Android TV
client_version: 0.16.8
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
org.jellyfin.sdk.api.client.exception.InvalidStatusException: Invalid HTTP status in response: 500
	at org.jellyfin.sdk.api.client.KtorClient.request$suspendImpl(KtorClient.kt:109)
	at org.jellyfin.sdk.api.client.KtorClient$request$1.invokeSuspend(KtorClient.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at android.os.Handler.handleCallback(Handler.java:742)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5444)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:943)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:833)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c432123, Dispatchers.Main.immediate]

```  
***Logcat***: 
```log
04-21 19:34:38.478 I/StartupActivity$onPermi( 6588): CurrentUser changed to a146126f-bee3-4e6a-9b99-244ec1d09c78 while waiting for startup.
04-21 19:34:38.480 D/StartupActivity( 6588): Determining next activity (action=android.intent.action.MAIN, itemId=null, itemIsUserView=false)
04-21 19:34:38.494 D/org.jellyfin.sdk.api.sockets.SocketInstance( 6588): Reconnect requested
04-21 19:34:38.495 I/org.jellyfin.sdk.api.sockets.SocketInstance( 6588): Reconnecting
04-21 19:34:38.495 D/org.jellyfin.sdk.api.sockets.helper.ReconnectHelper( 6588): Notified about reconnect, attempts=8
04-21 19:34:38.495 I/org.jellyfin.sdk.api.sockets.SocketInstance( 6588): Cancelling reconnect because baseUrl is null
04-21 19:34:38.497 D/org.jellyfin.sdk.api.sockets.SocketInstance( 6588): Reconnect requested
04-21 19:34:38.497 I/org.jellyfin.sdk.api.sockets.SocketInstance( 6588): Reconnecting
04-21 19:34:38.497 D/org.jellyfin.sdk.api.sockets.helper.ReconnectHelper( 6588): Notified about reconnect, attempts=9
04-21 19:34:38.497 I/org.jellyfin.sdk.api.sockets.SocketInstance( 6588): Cancelling reconnect because baseUrl is null
04-21 19:34:38.497 D/org.jellyfin.sdk.api.sockets.SocketInstance( 6588): Reconnect requested
04-21 19:34:38.497 I/org.jellyfin.sdk.api.sockets.SocketInstance( 6588): Reconnecting
04-21 19:34:38.497 D/org.jellyfin.sdk.api.sockets.helper.ReconnectHelper( 6588): Notified about reconnect, attempts=10
04-21 19:34:38.497 I/org.jellyfin.sdk.api.sockets.SocketInstance( 6588): Cancelling reconnect because baseUrl is null
04-21 19:34:38.498 D/org.jellyfin.sdk.api.sockets.SocketInstance( 6588): Reconnect requested
04-21 19:34:38.498 I/org.jellyfin.sdk.api.sockets.SocketInstance( 6588): Reconnecting
04-21 19:34:38.498 D/org.jellyfin.sdk.api.sockets.helper.ReconnectHelper( 6588): Notified about reconnect, attempts=11
04-21 19:34:38.498 I/org.jellyfin.sdk.api.sockets.SocketInstance( 6588): Cancelling reconnect because baseUrl is null
04-21 19:34:38.498 D/org.jellyfin.sdk.api.sockets.SocketInstance( 6588): Reconnect requested
04-21 19:34:38.498 I/org.jellyfin.sdk.api.sockets.SocketInstance( 6588): Reconnecting
04-21 19:34:38.498 D/org.jellyfin.sdk.api.sockets.helper.ReconnectHelper( 6588): Notified about reconnect, attempts=12
04-21 19:34:38.498 I/org.jellyfin.sdk.api.sockets.SocketInstance( 6588): Cancelling reconnect because baseUrl is null
04-21 19:34:38.509 I/org.jellyfin.sdk.api.client.KtorClient( 6588): POST http://192.168.0.128:8032/Sessions/Capabilities?playableMediaTypes=Video&playableMediaTypes=Audio&supportedCommands=DisplayContent&supportedCommands=DisplayMessage&supportedCommands=SendString&supportedCommands=VolumeUp&supportedCommands=VolumeDown&supportedCommands=SetVolume&supportedCommands=Mute&supportedCommands=Unmute&supportedCommands=ToggleMute&supportsMediaControl=true&supportsSync=false&supportsPersistentIdentifier=true
04-21 19:34:38.522 I/org.jellyfin.sdk.api.client.KtorClient( 6588): GET http://192.168.0.128:8032/Playback/BitrateTest?size=4000000
04-21 19:34:38.546 D/org.jellyfin.sdk.api.sockets.SocketInstance( 6588): Reconnect requested
04-21 19:34:38.546 I/org.jellyfin.sdk.api.sockets.SocketInstance( 6588): Reconnecting
04-21 19:34:38.546 D/org.jellyfin.sdk.api.sockets.helper.ReconnectHelper( 6588): Notified about reconnect, attempts=13
04-21 19:34:38.546 I/org.jellyfin.sdk.api.sockets.SocketInstance( 6588): Cancelling reconnect because baseUrl is null
04-21 19:34:38.698 D/NavigationRepositoryImp( 6588): Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.home.HomeFragment (Kotlin reflection is not available), arguments=Bundle[{}]) (via reset)
04-21 19:34:38.699 D/StartupActivity( 6588): Opening next activity Intent { flg=0x10004000 cmp=org.jellyfin.androidtv/.ui.browsing.MainActivity }
04-21 19:34:38.716 D/ACRA    ( 6588): onActivityPaused class org.jellyfin.androidtv.ui.startup.StartupActivity
04-21 19:34:38.737 I/ActivityThemeExtensions( 6588): Applying theme DARK
04-21 19:34:38.737 D/ACRA    ( 6588): onActivityCreated class org.jellyfin.androidtv.ui.browsing.MainActivity
04-21 19:34:38.759 D/ACRA    ( 6588): onActivityStarted class org.jellyfin.androidtv.ui.browsing.MainActivity
04-21 19:34:38.759 D/ACRA    ( 6588): onActivityResumed class org.jellyfin.androidtv.ui.browsing.MainActivity
04-21 19:34:38.792 I/org.jellyfin.sdk.api.client.KtorClient( 6588): GET http://192.168.0.128:8032/LiveTv/Programs/Recommended?userId=a146126f-bee3-4e6a-9b99-244ec1d09c78&limit=1&isAiring=true&imageTypeLimit=1&enableTotalRecordCount=false
04-21 19:34:38.800 I/HomeRowsFragment( 6588): Updating audio queue in HomeFragment (onQueueStatusChanged)
04-21 19:34:38.819 I/HomeRowsFragment( 6588): Updating audio queue in HomeFragment (onResume)
04-21 19:34:38.927 D/jellyfin-apiclient( 6588): Adding request to queue: http://192.168.0.128:8032/Users/a146126f-bee3-4e6a-9b99-244ec1d09c78/Views?format=json
04-21 19:34:38.945 I/org.jellyfin.sdk.api.client.KtorClient( 6588): GET http://192.168.0.128:8032/Users/a146126f-bee3-4e6a-9b99-244ec1d09c78/Items/Resume?limit=50&fields=PrimaryImageAspectRatio&fields=Overview&fields=ItemCounts&fields=DisplayPreferencesId&fields=ChildCount&mediaTypes=Video&imageTypeLimit=1&enableTotalRecordCount=false&enableImages=true&excludeActiveSessions=false
04-21 19:34:38.954 I/org.jellyfin.sdk.api.client.KtorClient( 6588): GET http://192.168.0.128:8032/Users/a146126f-bee3-4e6a-9b99-244ec1d09c78/Items/Resume?limit=50&fields=PrimaryImageAspectRatio&fields=Overview&fields=ItemCounts&fields=DisplayPreferencesId&fields=ChildCount&mediaTypes=Audio&imageTypeLimit=1&enableTotalRecordCount=false&enableImages=true&excludeActiveSessions=false
04-21 19:34:38.962 D/jellyfin-apiclient( 6588): Adding request to queue: http://192.168.0.128:8032/Shows/NextUp?Limit=50&UserId=a146126f-bee3-4e6a-9b99-244ec1d09c78&ImageTypeLimit=1&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&format=json
04-21 19:34:38.964 I/org.jellyfin.sdk.api.client.KtorClient( 6588): GET http://192.168.0.128:8032/Users/a146126f-bee3-4e6a-9b99-244ec1d09c78/Views?includeHidden=false
04-21 19:34:38.972 I/art     ( 6588): Note: end time exceeds epoch: 
04-21 19:34:38.991 I/art     ( 6588): Note: end time exceeds epoch: 
04-21 19:34:38.992 I/art     ( 6588): Note: end time exceeds epoch: 
04-21 19:34:39.404 D/jellyfin-apiclient( 6588): Adding request to queue: http://192.168.0.128:8032/Users/a146126f-bee3-4e6a-9b99-244ec1d09c78/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=ccb55e75-1d80-0cf1-af4f-6eebd319c177&GroupItems=true&format=json
04-21 19:34:39.405 D/jellyfin-apiclient( 6588): Adding request to queue: http://192.168.0.128:8032/Users/a146126f-bee3-4e6a-9b99-244ec1d09c78/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=601a4fdb-6d43-488c-54f9-c9632a795d2c&GroupItems=true&format=json
04-21 19:34:39.406 D/jellyfin-apiclient( 6588): Adding request to queue: http://192.168.0.128:8032/Users/a146126f-bee3-4e6a-9b99-244ec1d09c78/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=3227ce1e-0697-54c5-94af-25ea66d69fc7&GroupItems=true&format=json
04-21 19:34:39.407 D/jellyfin-apiclient( 6588): Adding request to queue: http://192.168.0.128:8032/Users/a146126f-bee3-4e6a-9b99-244ec1d09c78/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=fc8fa12e-e6bc-083a-bb48-4b1b0bbc420f&GroupItems=true&format=json
04-21 19:34:39.408 D/jellyfin-apiclient( 6588): Adding request to queue: http://192.168.0.128:8032/Users/a146126f-bee3-4e6a-9b99-244ec1d09c78/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=48fa9152-c763-faf4-24e8-1dd03205c1f8&GroupItems=true&format=json
04-21 19:34:39.409 D/jellyfin-apiclient( 6588): Adding request to queue: http://192.168.0.128:8032/Users/a146126f-bee3-4e6a-9b99-244ec1d09c78/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=4657a515-91e2-ab04-bf49-f3cdbaae967c&GroupItems=true&format=json
04-21 19:34:39.420 I/Choreographer( 6588): Skipped 34 frames!  The application may be doing too much work on its main thread.
04-21 19:34:39.430 E/Volley  ( 6588): [349] NetworkUtility.shouldRetryException: Unexpected response code 500 for http://192.168.0.128:8032/Users/a146126f-bee3-4e6a-9b99-244ec1d09c78/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=3227ce1e-0697-54c5-94af-25ea66d69fc7&GroupItems=true&format=json
04-21 19:34:39.548 I/jellyfin-apiclient( 6588): Response received from: http://192.168.0.128:8032/Users/a146126f-bee3-4e6a-9b99-244ec1d09c78/Views?format=json
04-21 19:34:39.551 I/WM-WorkerWrapper( 6588): Worker result FAILURE for Work [ id=fbe67585-cded-41fd-b0ab-55382321f890, tags={ org.jellyfin.androidtv.integration.LeanbackChannelWorker } ]
04-21 19:34:39.725 D/ItemRowAdapterHelperKt( 6588): Creating items from 0 existing and 8 new, adapter size is 0
04-21 19:34:39.749 E/ACRA    ( 6588): ACRA caught a InvalidStatusException for org.jellyfin.androidtv
04-21 19:34:39.749 E/ACRA    ( 6588): org.jellyfin.sdk.api.client.exception.InvalidStatusException: Invalid HTTP status in response: 500
04-21 19:34:39.749 E/ACRA    ( 6588): 	at org.jellyfin.sdk.api.client.KtorClient.request$suspendImpl(KtorClient.kt:109)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at org.jellyfin.sdk.api.client.KtorClient$request$1.invokeSuspend(KtorClient.kt)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at android.os.Handler.handleCallback(Handler.java:742)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at android.os.Looper.loop(Looper.java:157)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at android.app.ActivityThread.main(ActivityThread.java:5444)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at java.lang.reflect.Method.invoke(Native Method)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:943)
04-21 19:34:39.749 E/ACRA    ( 6588): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:833)
04-21 19:34:39.749 E/ACRA    ( 6588): 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c432123, Dispatchers.Main.immediate]
04-21 19:34:39.749 D/ACRA    ( 6588): Building report
04-21 19:34:39.750 D/ACRA    ( 6588): Starting collectors with priority FIRST
04-21 19:34:39.752 D/ACRA    ( 6588): Calling collector org.acra.collector.DropBoxCollector
04-21 19:34:39.752 D/ACRA    ( 6588): Collector org.acra.collector.DropBoxCollector completed
04-21 19:34:39.753 D/ACRA    ( 6588): Calling collector org.acra.collector.LogCatCollector
04-21 19:34:39.754 D/ACRA    ( 6588): Calling collector org.acra.collector.StacktraceCollector
04-21 19:34:39.778 D/ACRA    ( 6588): Collector org.acra.collector.StacktraceCollector completed
04-21 19:34:39.792 D/ACRA    ( 6588): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.16.8` (`160899`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"xmen","BOOTLOADER":"unknown","BRAND":"Xiaomi","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"xmen","DISPLAY":"20.3.9.2061","FINGERPRINT":"Xiaomi\/xmen\/xmen:6.0.1\/MHC19J\/2061:user\/release-keys","HARDWARE":"amlogic","HOST":"c3-mitv-bsp-build01.bj","ID":"MHC19J","IS_DEBUGGABLE":false,"MANUFACTURER":"xiaomi","MODEL":"MiTV4-ANSM0","PRODUCT":"xmen","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1583748404000,"TYPE":"user","UNKNOWN":"unknown","USER":"jenkins","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"2061","PREVIEW_SDK_INT":0,"RELEASE":"6.0.1","RESOURCES_SDK_INT":23,"SDK":"23","SDK_INT":23,"SECURITY_PATCH":"2017-04-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":160899,"VERSION_NAME":"0.16.8"}
```  

### Device information

***Android version***: `6.0.1`  
***Device brand***: `Xiaomi`  
***Device product***: `xmen`  
***Device model***: `MiTV4-ANSM0`  

### Crash information

***Start time***: `2024-04-21T19:33:17.386+08:00`  
***Crash time***: `2024-04-21T19:34:39.859+08:00`  

### Application version

0.16.8

### Where did you install the app from?

None

### Device information

MiTV4-ANSM0

### Android version

6.0.1

### Jellyfin server version

10.8.1

**Comment by nielsvanvelzen** [comment]
It looks like the app crashes because of some issue in the server. Your server logs should have some more information about what went wrong.
