### ISSUE TITLE
App crash when series isn't completely played and doesn't have a next up episode

### ISSUE THREAD

**Issue by pascalwei** [jellyfin/jellyfin-androidtv#3626]
### Describe the bug

When the last episode in a series is marked as watched, the API no longer has a next episode for us. However episodes before the last episode might still be marked as unwatched, in that case the API tells us the series isn't completely played just yet.

Right now we display the "next up" button on the series details page when the UserData from the BaseItemDto suggests the series isn't completely played.

https://github.com/jellyfin/jellyfin-androidtv/blob/aa8a2fbdc8fc3c9997d3f20d8d4624ad23f02161/app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java#L908

When it comes to actually playing the next up episode, we just blindly assume there has to be one and crash our app in case we hand an empty list to our play method.

https://github.com/jellyfin/jellyfin-androidtv/blob/aa8a2fbdc8fc3c9997d3f20d8d4624ad23f02161/app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragmentHelper.kt#L266-L292

To fix this in the client we would have to call the server when loading the FullDetailsFragment and ask if there is a next episode. Because the BaseItemDto only knows the series isn't completely played, not whether a next episode exists. 

Another option is changing the API so items not tagged as played always have a next up episode, e.g. the first episode that is not completely watched in a series.

I'm unsure what's the right way to deal with this.

Trigger crash:
1. Login to server, e.g. the demo server at https://demo.jellyfin.org/stable
2. Mark the last episode in a series as watched, the episodes before as unwatched.
3. Click "Play next up" on the series details page.

### Logs

```
org.jellyfin.androidtv.debug         E  ACRA caught a IndexOutOfBoundsException for org.jellyfin.androidtv.debug
                                                                                                    java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
                                                                                                    	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
                                                                                                    	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
                                                                                                    	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
                                                                                                    	at java.util.Objects.checkIndex(Objects.java:359)
                                                                                                    	at java.util.ArrayList.get(ArrayList.java:434)
                                                                                                    	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment.play(FullDetailsFragment.java:1455)
                                                                                                    	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragmentHelperKt$resumePlayback$1.invokeSuspend(FullDetailsFragmentHelper.kt:285)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:65)
                                                                                                    	at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:343)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:146)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:11)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:70)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@79df261, Dispatchers.Main.immediate]
```

### Application version

master

### Where did you install the app from?

None

### Device information

Television 4K AVD

### Android version

Android 14

### Jellyfin server version

10.9.3

**Comment by nielsvanvelzen** [comment]
I've improved the querying for the next up item in #3633
