### ISSUE TITLE
App crash immediately after sign-in

### ISSUE THREAD

**Issue by epicylon** [jellyfin/jellyfin-androidtv#3634]
### Describe the bug

On Fire TV, Jellyfin-androidtv crashes consistently after signing in with any user. This only happens after upgrading Jellyfin to 10.9.X

### Logs

---
client: Jellyfin for Android TV
client_version: 0.16.11
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
org.jellyfin.sdk.api.client.exception.InvalidStatusException: Invalid HTTP status in response: 500
	at org.jellyfin.sdk.api.client.KtorClient.request$suspendImpl(KtorClient.kt:109)
	at org.jellyfin.sdk.api.client.KtorClient$request$1.invokeSuspend(KtorClient.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1ce21e7b, Dispatchers.IO]

```  
***Logcat***: 
```log
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at android.os.Handler.handleCallback(Handler.java:739)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at android.os.Looper.loop(Looper.java:135)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at android.app.ActivityThread.main(ActivityThread.java:5597)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at java.lang.reflect.Method.invoke(Native Method)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at java.lang.reflect.Method.invoke(Method.java:372)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
06-01 11:31:13.345 E/UserLoginViewModel(20962): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-01 11:31:19.676 W/IInputConnectionWrapper(20962): setSelection on inactive InputConnection
06-01 11:31:30.386 I/org.jellyfin.sdk.api.client.KtorClient(20962): POST https://jf.example.com/Users/AuthenticateByName
06-01 11:31:31.152 I/SessionRepositoryImpl(20962): Switching current session to user a65a8aae-873e-407f-8984-ec1d475077da
06-01 11:31:31.156 I/SessionRepositoryImpl(20962): Updating current session. userId=a65a8aae-873e-407f-8984-ec1d475077da apiBindingSuccess=true
06-01 11:31:31.157 I/org.jellyfin.sdk.api.client.KtorClient(20962): GET https://jf.example.com/Users/Me
06-01 11:31:31.229 I/art     (20962): Background sticky concurrent mark sweep GC freed 82139(3MB) AllocSpace objects, 2(32KB) LOS objects, 15% free, 17MB/20MB, paused 3.326ms total 104.583ms
06-01 11:31:31.282 I/org.jellyfin.sdk.api.client.KtorClient(20962): GET https://jf.example.com/DisplayPreferences/livetv?userId=a65a8aae-873e-407f-8984-ec1d475077da&client=jellyfin-androidtv
06-01 11:31:31.317 I/org.jellyfin.sdk.api.client.KtorClient(20962): GET https://jf.example.com/DisplayPreferences/usersettings?userId=a65a8aae-873e-407f-8984-ec1d475077da&client=emby
06-01 11:31:31.348 I/StartupActivity$onPermi(20962): Found a session in the session repository, waiting for the currentUser in the application class.
06-01 11:31:31.350 I/StartupActivity$onPermi(20962): CurrentUser changed to a65a8aae-873e-407f-8984-ec1d475077da while waiting for startup.
06-01 11:31:31.351 D/StartupActivity(20962): Determining next activity (action=android.intent.action.MAIN, itemId=null, itemIsUserView=false)
06-01 11:31:31.361 D/org.jellyfin.sdk.api.sockets.SocketInstance(20962): Reconnect requested
06-01 11:31:31.361 I/org.jellyfin.sdk.api.sockets.SocketInstance(20962): Reconnecting
06-01 11:31:31.361 D/org.jellyfin.sdk.api.sockets.helper.ReconnectHelper(20962): Notified about reconnect, attempts=8
06-01 11:31:31.361 I/org.jellyfin.sdk.api.sockets.SocketInstance(20962): Cancelling reconnect because baseUrl is null
06-01 11:31:31.362 D/org.jellyfin.sdk.api.sockets.SocketInstance(20962): Reconnect requested
06-01 11:31:31.363 I/org.jellyfin.sdk.api.sockets.SocketInstance(20962): Reconnecting
06-01 11:31:31.363 D/org.jellyfin.sdk.api.sockets.helper.ReconnectHelper(20962): Notified about reconnect, attempts=9
06-01 11:31:31.363 I/org.jellyfin.sdk.api.sockets.SocketInstance(20962): Cancelling reconnect because baseUrl is null
06-01 11:31:31.364 D/org.jellyfin.sdk.api.sockets.SocketInstance(20962): Reconnect requested
06-01 11:31:31.364 I/org.jellyfin.sdk.api.sockets.SocketInstance(20962): Reconnecting
06-01 11:31:31.364 D/org.jellyfin.sdk.api.sockets.helper.ReconnectHelper(20962): Notified about reconnect, attempts=10
06-01 11:31:31.364 I/org.jellyfin.sdk.api.sockets.SocketInstance(20962): Cancelling reconnect because baseUrl is null
06-01 11:31:31.365 D/org.jellyfin.sdk.api.sockets.SocketInstance(20962): Reconnect requested
06-01 11:31:31.365 I/org.jellyfin.sdk.api.sockets.SocketInstance(20962): Reconnecting
06-01 11:31:31.365 D/org.jellyfin.sdk.api.sockets.helper.ReconnectHelper(20962): Notified about reconnect, attempts=11
06-01 11:31:31.365 I/org.jellyfin.sdk.api.sockets.SocketInstance(20962): Cancelling reconnect because baseUrl is null
06-01 11:31:31.367 D/org.jellyfin.sdk.api.sockets.SocketInstance(20962): Reconnect requested
06-01 11:31:31.367 I/org.jellyfin.sdk.api.sockets.SocketInstance(20962): Reconnecting
06-01 11:31:31.367 D/org.jellyfin.sdk.api.sockets.helper.ReconnectHelper(20962): Notified about reconnect, attempts=12
06-01 11:31:31.367 I/org.jellyfin.sdk.api.sockets.SocketInstance(20962): Cancelling reconnect because baseUrl is null
06-01 11:31:31.372 I/org.jellyfin.sdk.api.client.KtorClient(20962): POST https://jf.example.com/Sessions/Capabilities?playableMediaTypes=Video&playableMediaTypes=Audio&supportedCommands=DisplayContent&supportedCommands=DisplayMessage&supportedCommands=SendString&supportsMediaControl=true&supportsSync=false&supportsPersistentIdentifier=true
06-01 11:31:31.383 I/org.jellyfin.sdk.api.client.KtorClient(20962): GET https://jf.example.com/Playback/BitrateTest?size=4000000
06-01 11:31:31.391 W/View    (20962): requestLayout() improperly called by androidx.compose.ui.platform.ViewLayerContainer{2b2a8935 V.E..... ......ID 0,0-0,0} during layout: running second layout pass
06-01 11:31:31.450 D/org.jellyfin.sdk.api.sockets.SocketInstance(20962): Reconnect requested
06-01 11:31:31.450 I/org.jellyfin.sdk.api.sockets.SocketInstance(20962): Reconnecting
06-01 11:31:31.450 D/org.jellyfin.sdk.api.sockets.helper.ReconnectHelper(20962): Notified about reconnect, attempts=13
06-01 11:31:31.450 I/org.jellyfin.sdk.api.sockets.SocketInstance(20962): Cancelling reconnect because baseUrl is null
06-01 11:31:31.503 D/NavigationRepositoryImp(20962): Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.home.HomeFragment (Kotlin reflection is not available), arguments=Bundle[{}]) (via reset)
06-01 11:31:31.503 D/StartupActivity(20962): Opening next activity Intent { flg=0x10004000 cmp=org.jellyfin.androidtv/.ui.browsing.MainActivity }
06-01 11:31:31.540 D/ACRA    (20962): onActivityPaused class org.jellyfin.androidtv.ui.startup.StartupActivity
06-01 11:31:31.591 I/ActivityThemeExtensions(20962): Applying theme DARK
06-01 11:31:31.592 D/ACRA    (20962): onActivityCreated class org.jellyfin.androidtv.ui.browsing.MainActivity
06-01 11:31:31.611 D/ACRA    (20962): onActivityStarted class org.jellyfin.androidtv.ui.browsing.MainActivity
06-01 11:31:31.611 D/ACRA    (20962): onActivityResumed class org.jellyfin.androidtv.ui.browsing.MainActivity
06-01 11:31:31.648 I/art     (20962): Background sticky concurrent mark sweep GC freed 38116(2MB) AllocSpace objects, 2(32KB) LOS objects, 1% free, 19MB/20MB, paused 4.241ms total 118.469ms
06-01 11:31:31.675 I/HomeRowsFragment(20962): Updating audio queue in HomeFragment (onQueueStatusChanged)
06-01 11:31:31.683 W/art     (20962): Suspending all threads took: 5.615ms
06-01 11:31:31.694 I/art     (20962): Background sticky concurrent mark sweep GC freed 3451(155KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 20MB/20MB, paused 13.702ms total 44.860ms
06-01 11:31:31.704 I/org.jellyfin.sdk.api.client.KtorClient(20962): GET https://jf.example.com/LiveTv/Programs/Recommended?userId=a65a8aae-873e-407f-8984-ec1d475077da&limit=1&isAiring=true&imageTypeLimit=1&enableTotalRecordCount=false
06-01 11:31:31.713 I/HomeRowsFragment(20962): Updating audio queue in HomeFragment (onResume)
06-01 11:31:31.822 E/ACRA    (20962): ACRA caught a InvalidStatusException for org.jellyfin.androidtv
06-01 11:31:31.822 E/ACRA    (20962): org.jellyfin.sdk.api.client.exception.InvalidStatusException: Invalid HTTP status in response: 500
06-01 11:31:31.822 E/ACRA    (20962): 	at org.jellyfin.sdk.api.client.KtorClient.request$suspendImpl(KtorClient.kt:109)
06-01 11:31:31.822 E/ACRA    (20962): 	at org.jellyfin.sdk.api.client.KtorClient$request$1.invokeSuspend(KtorClient.kt)
06-01 11:31:31.822 E/ACRA    (20962): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
06-01 11:31:31.822 E/ACRA    (20962): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
06-01 11:31:31.822 E/ACRA    (20962): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
06-01 11:31:31.822 E/ACRA    (20962): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
06-01 11:31:31.822 E/ACRA    (20962): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
06-01 11:31:31.822 E/ACRA    (20962): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
06-01 11:31:31.822 E/ACRA    (20962): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
06-01 11:31:31.822 E/ACRA    (20962): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
06-01 11:31:31.822 E/ACRA    (20962): 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1ce21e7b, Dispatchers.IO]
06-01 11:31:31.822 D/ACRA    (20962): Building report
06-01 11:31:31.824 D/ACRA    (20962): Starting collectors with priority FIRST
06-01 11:31:31.827 D/ACRA    (20962): Calling collector org.acra.collector.DropBoxCollector
06-01 11:31:31.827 D/ACRA    (20962): Collector org.acra.collector.DropBoxCollector completed
06-01 11:31:31.830 D/ACRA    (20962): Calling collector org.acra.collector.StacktraceCollector
06-01 11:31:31.831 D/ACRA    (20962): Calling collector org.acra.collector.LogCatCollector
06-01 11:31:31.831 I/HAL     (20962): loaded HAL id=gralloc path=/system/lib/hw/gralloc.msm8960.so hmi=0x0 handle=0xb1d323f4
06-01 11:31:31.864 D/ACRA    (20962): Collector org.acra.collector.StacktraceCollector completed
06-01 11:31:31.883 D/ACRA    (20962): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.16.11` (`161199`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"MSM8960","BOOTLOADER":"unknown","BRAND":"Amazon","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"bueller","DISPLAY":"LVY48F","FINGERPRINT":"Amazon\/bueller\/bueller:5.1.1\/LVY48F\/51.6.5.6_user_656639420:user\/release-keys","HARDWARE":"qcom","HOST":"i3-ri-14-use1a-b-15","ID":"LVY48F","IS_DEBUGGABLE":false,"MANUFACTURER":"Amazon","MODEL":"AFTB","PRODUCT":"bueller","RADIO":"unknown","REQ_BATTERY_LEVEL":0,"SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1628629745000,"TYPE":"user","UNKNOWN":"unknown","USER":"build","WAN":false,"VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"51.6.5.6_user_656639420","RELEASE":"5.1.1","RESOURCES_SDK_INT":22,"SDK":"22","SDK_INT":22,"SECURITY_PATCH":"2019-07-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":161199,"VERSION_NAME":"0.16.11"}
```  

### Device information

***Android version***: `5.1.1`  
***Device brand***: `Amazon`  
***Device product***: `bueller`  
***Device model***: `AFTB`  

### Crash information

***Start time***: `2024-06-01T11:31:02.874+02:00`  
***Crash time***: `2024-06-01T11:31:31.978+02:00`  

### Application version

0.16.11

### Where did you install the app from?

Sideloaded APK

### Device information

Amazon Fire TV - 1st Generation 

### Android version

Latest FireOS supported by 1st gen Fire TV

### Jellyfin server version

10.9.3

**Comment by nielsvanvelzen** [comment]
There is something wrong with your server and it is sending unexpected responses.

**Comment by epicylon** [comment]
Yep, you were right. It was a perm error, the server could not write to the cache dir. Thanks for your awesome work!
