### ISSUE TITLE
4k movies will crash since 0.17

### ISSUE THREAD

**Issue by N8-Yue** [jellyfin/jellyfin-androidtv#3846]
### Describe the bug

1. Start a 4K movie
2. player crashes

### Logs

   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at jellyfin_ani_sync.UpdateProviderStatus.Update(BaseItem e, Guid userId, Boolean playedToCompletion)
   at jellyfin_ani_sync.SessionServerEntry.PlaybackStopped(Object sender, PlaybackStopEventArgs e)
[16:17:25] [INF] [19] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop tracker found, processing stop : b0ecc3bde3e95478bc2239abf9b3252423846bf0-9fd8852c23cb4c6da3310a3fc06ac362-d394b3e2b8855c20d90c8a1db8cd7986
[16:17:25] [INF] [19] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Stop Event : 08/06/2024 16:17:25
[16:17:25] [INF] [19] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Saving playback tracking activity in DB
[16:17:25] [ERR] [19] Jellyfin.Plugin.Simkl.Services.PlaybackScrobbler: Can't scrobble: User Christian not logged in (True)
[16:21:25] [INF] [27] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for Christian. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[16:21:25] [INF] [22] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Adding playback tracker : b0ecc3bde3e95478bc2239abf9b3252423846bf0-9fd8852c23cb4c6da3310a3fc06ac362-d394b3e2b8855c20d90c8a1db8cd7986
[16:21:25] [INF] [22] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Start Event : 08/06/2024 16:21:25
[16:21:25] [INF] [22] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Creating StartPlaybackTimer Task
[16:21:25] [INF] [22] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Entered
[16:21:26] [INF] [20] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -init_hw_device vaapi=va:,kernel_driver=i915,driver=iHD -init_hw_device qsv=qs@va -init_hw_device opencl=ocl@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:"/data/movies1/Bad.Boys.Ride.or.Die.2024.German.EAC3.DL.2160p.WEB.DV.HDR.h265-VECTOR/Bad.Boys.Ride.or.Die.2024.German.EAC3.DL.2160p.WEB.DV.HDR.h265-VECTOR/Bad Boys - Ride or Die (2024).mkv" -noautoscale -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 hevc_qsv -tag:v:0 hvc1 -preset veryfast -b:v 25229491 -maxrate 25229491 -bufsize 50458982 -profile:v:0 main -level 50 -g:v:0 72 -keyint_min:v:0 72 -vf "setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc,hwmap=derive_device=opencl,tonemap_opencl=format=nv12:p=bt709:t=bt709:m=bt709:tonemap=bt2390:peak=100:desat=0,hwmap=derive_device=qsv:reverse=1:extra_hw_frames=16,format=qsv" -codec:a:0 libfdk_aac -ac 6 -ab 640000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/data/transcodes/a6de758a055a5cf8bf59c8b24dc0501d%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/data/transcodes/a6de758a055a5cf8bf59c8b24dc0501d.m3u8"
[16:21:26] [INF] [27] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : b0ecc3bde3e95478bc2239abf9b3252423846bf0-9fd8852c23cb4c6da3310a3fc06ac362-d394b3e2b8855c20d90c8a1db8cd7986
[16:21:26] [ERR] [27] Jellyfin.Plugin.Simkl.Services.PlaybackScrobbler: Can't scrobble: User Christian not logged in (True)
[16:21:34] [INF] [13] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for /config/data/transcodes/a6de758a055a5cf8bf59c8b24dc0501d.m3u8
[16:21:35] [INF] [13] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[16:21:35] [INF] [13] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -ss 00:02:26.312 -fflags +genpts  -i file:"/data/movies1/Bad.Boys.Ride.or.Die.2024.German.EAC3.DL.2160p.WEB.DV.HDR.h265-VECTOR/Bad.Boys.Ride.or.Die.2024.German.EAC3.DL.2160p.WEB.DV.HDR.h265-VECTOR/Bad Boys - Ride or Die (2024).mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -tag:v:0 hvc1 -bsf:v hevc_mp4toannexb -start_at_zero -codec:a:0 libfdk_aac -ac 6 -ab 640000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 24 -hls_segment_filename "/config/data/transcodes/a6de758a055a5cf8bf59c8b24dc0501d%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/data/transcodes/a6de758a055a5cf8bf59c8b24dc0501d.m3u8"
[16:21:40] [INF] [20] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for /config/data/transcodes/a6de758a055a5cf8bf59c8b24dc0501d.m3u8
[16:21:40] [INF] [39] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for Christian. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[16:21:40] [INF] [53] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[16:21:40] [INF] [20] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) /config/data/transcodes/a6de758a055a5cf8bf59c8b24dc0501d.m3u8
[16:21:41] [INF] [53] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Existing tracker found! : b0ecc3bde3e95478bc2239abf9b3252423846bf0-9fd8852c23cb4c6da3310a3fc06ac362-d394b3e2b8855c20d90c8a1db8cd7986
[16:21:41] [INF] [53] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Removing existing tracker : b0ecc3bde3e95478bc2239abf9b3252423846bf0-9fd8852c23cb4c6da3310a3fc06ac362-d394b3e2b8855c20d90c8a1db8cd7986
[16:21:41] [INF] [53] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Adding playback tracker : b0ecc3bde3e95478bc2239abf9b3252423846bf0-9fd8852c23cb4c6da3310a3fc06ac362-d394b3e2b8855c20d90c8a1db8cd7986
[16:21:41] [INF] [53] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Start Event : 08/06/2024 16:21:41
[16:21:41] [INF] [53] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Creating StartPlaybackTimer Task
[16:21:41] [INF] [53] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Entered
[16:21:41] [INF] [39] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -fflags +genpts  -i file:"/data/movies1/Bad.Boys.Ride.or.Die.2024.German.EAC3.DL.2160p.WEB.DV.HDR.h265-VECTOR/Bad.Boys.Ride.or.Die.2024.German.EAC3.DL.2160p.WEB.DV.HDR.h265-VECTOR/Bad Boys - Ride or Die (2024).mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -tag:v:0 hvc1 -bsf:v hevc_mp4toannexb -start_at_zero -codec:a:0 libfdk_aac -ac 6 -ab 640000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/data/transcodes/6d9a060561ab427e189337555d936814%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/data/transcodes/6d9a060561ab427e189337555d936814.m3u8"
[16:21:42] [INF] [32] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : b0ecc3bde3e95478bc2239abf9b3252423846bf0-9fd8852c23cb4c6da3310a3fc06ac362-d394b3e2b8855c20d90c8a1db8cd7986
[16:21:42] [INF] [32] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for /config/data/transcodes/6d9a060561ab427e189337555d936814.m3u8
[16:21:42] [INF] [22] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for Christian. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[16:21:42] [INF] [27] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Existing tracker found! : b0ecc3bde3e95478bc2239abf9b3252423846bf0-9fd8852c23cb4c6da3310a3fc06ac362-d394b3e2b8855c20d90c8a1db8cd7986
[16:21:42] [INF] [27] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Removing existing tracker : b0ecc3bde3e95478bc2239abf9b3252423846bf0-9fd8852c23cb4c6da3310a3fc06ac362-d394b3e2b8855c20d90c8a1db8cd7986
[16:21:42] [INF] [27] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Adding playback tracker : b0ecc3bde3e95478bc2239abf9b3252423846bf0-9fd8852c23cb4c6da3310a3fc06ac362-d394b3e2b8855c20d90c8a1db8cd7986
[16:21:42] [INF] [27] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Start Event : 08/06/2024 16:21:42
[16:21:42] [INF] [27] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Creating StartPlaybackTimer Task
[16:21:42] [INF] [27] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Entered
[16:21:42] [INF] [22] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[16:21:42] [INF] [32] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) /config/data/transcodes/6d9a060561ab427e189337555d936814.m3u8
[16:21:42] [INF] [25] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -fflags +genpts  -i file:"/data/movies1/Bad.Boys.Ride.or.Die.2024.German.EAC3.DL.2160p.WEB.DV.HDR.h265-VECTOR/Bad.Boys.Ride.or.Die.2024.German.EAC3.DL.2160p.WEB.DV.HDR.h265-VECTOR/Bad Boys - Ride or Die (2024).mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -tag:v:0 hvc1 -bsf:v hevc_mp4toannexb -start_at_zero -codec:a:0 libfdk_aac -ac 6 -ab 640000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/data/transcodes/3e6e4ee09d227b571e1623f8bc56798d%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/data/transcodes/3e6e4ee09d227b571e1623f8bc56798d.m3u8"
[16:21:42] [INF] [32] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Android TV 0.17.0 playing Bad Boys: Ride or Die. Stopped at 152828 ms
[16:21:42] [ERR] [22] jellyfin_ani_sync.SessionServerEntry: Fatal error occured during anime sync job: System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at jellyfin_ani_sync.UpdateProviderStatus.Update(BaseItem e, Guid userId, Boolean playedToCompletion)
   at jellyfin_ani_sync.SessionServerEntry.PlaybackStopped(Object sender, PlaybackStopEventArgs e)
[16:21:42] [INF] [22] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop tracker found, processing stop : b0ecc3bde3e95478bc2239abf9b3252423846bf0-9fd8852c23cb4c6da3310a3fc06ac362-d394b3e2b8855c20d90c8a1db8cd7986
[16:21:42] [INF] [22] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Stop Event : 08/06/2024 16:21:42
[16:21:42] [INF] [22] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop but TrackedPlaybackInfo not found! not storing activity in DB
[16:21:42] [ERR] [22] Jellyfin.Plugin.Simkl.Services.PlaybackScrobbler: Can't scrobble: User Christian not logged in (True)
[16:21:43] [INF] [25] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for /config/data/transcodes/3e6e4ee09d227b571e1623f8bc56798d.m3u8
[16:21:43] [INF] [25] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[16:21:43] [INF] [25] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) /config/data/transcodes/3e6e4ee09d227b571e1623f8bc56798d.m3u8
[16:21:43] [INF] [32] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Android TV 0.17.0 playing Bad Boys: Ride or Die. Stopped at 152828 ms
[16:21:43] [ERR] [22] jellyfin_ani_sync.SessionServerEntry: Fatal error occured during anime sync job: System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at jellyfin_ani_sync.UpdateProviderStatus.Update(BaseItem e, Guid userId, Boolean playedToCompletion)
   at jellyfin_ani_sync.SessionServerEntry.PlaybackStopped(Object sender, PlaybackStopEventArgs e)
[16:21:43] [INF] [22] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop did not have a tracker : b0ecc3bde3e95478bc2239abf9b3252423846bf0-9fd8852c23cb4c6da3310a3fc06ac362-d394b3e2b8855c20d90c8a1db8cd7986
[16:21:43] [ERR] [22] Jellyfin.Plugin.Simkl.Services.PlaybackScrobbler: Can't scrobble: User Christian not logged in (True)
[16:21:44] [INF] [22] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Android TV 0.17.0 playing Bad Boys: Ride or Die. Stopped at 152828 ms
[16:21:44] [ERR] [32] jellyfin_ani_sync.SessionServerEntry: Fatal error occured during anime sync job: System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at jellyfin_ani_sync.UpdateProviderStatus.Update(BaseItem e, Guid userId, Boolean playedToCompletion)
   at jellyfin_ani_sync.SessionServerEntry.PlaybackStopped(Object sender, PlaybackStopEventArgs e)
[16:21:44] [INF] [32] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop did not have a tracker : b0ecc3bde3e95478bc2239abf9b3252423846bf0-9fd8852c23cb4c6da3310a3fc06ac362-d394b3e2b8855c20d90c8a1db8cd7986
[16:21:44] [ERR] [32] Jellyfin.Plugin.Simkl.Services.PlaybackScrobbler: Can't scrobble: User Christian not logged in (True)
[16:21:45] [INF] [25] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: session.RemoteEndPoint : 192.168.178.135
[16:21:45] [INF] [25] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_playing_id     = d394b3e2b8855c20d90c8a1db8cd7986
[16:21:45] [INF] [25] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id        = 9fd8852c23cb4c6da3310a3fc06ac362
[16:21:45] [INF] [25] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id_int    = 3
[16:21:45] [INF] [25] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_playing_id   = 
[16:21:45] [INF] [25] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_user_id      = 9fd8852c23cb4c6da3310a3fc06ac362
[16:21:45] [INF] [25] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : play_method          = na
[16:21:45] [INF] [25] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.ClientName         = Android TV
[16:21:45] [INF] [25] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.DeviceName         = AFTKRT
[16:21:45] [INF] [25] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemName             = Bad Boys: Ride or Die
[16:21:45] [INF] [25] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemId               = d394b3e2b8855c20d90c8a1db8cd7986
[16:21:45] [INF] [25] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemType             = Movie
[16:21:45] [INF] [25] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Details do not match for play item
[16:21:45] [INF] [25] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Exited
[16:22:01] [INF] [53] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: session.RemoteEndPoint : 192.168.178.135
[16:22:01] [INF] [53] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_playing_id     = d394b3e2b8855c20d90c8a1db8cd7986
[16:22:01] [INF] [53] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id        = 9fd8852c23cb4c6da3310a3fc06ac362
[16:22:01] [INF] [53] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id_int    = 3
[16:22:01] [INF] [53] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_playing_id   = 
[16:22:01] [INF] [53] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_user_id      = 9fd8852c23cb4c6da3310a3fc06ac362
[16:22:01] [INF] [53] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : play_method          = na
[16:22:01] [INF] [53] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.ClientName         = Android TV
[16:22:01] [INF] [53] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.DeviceName         = AFTKRT
[16:22:01] [INF] [53] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemName             = Bad Boys: Ride or Die
[16:22:01] [INF] [53] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemId               = d394b3e2b8855c20d90c8a1db8cd7986
[16:22:01] [INF] [53] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemType             = Movie
[16:22:01] [INF] [53] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Details do not match for play item
[16:22:01] [INF] [53] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Exited

### Application version

0.17.0

### Device information

latest firetv cube,stick

### Android version

latest firetv os

### Jellyfin server version

10.9.9

**Comment by N8-Yue** [comment]
I also tried the direct fix but this wont help. The file will play for a short time until it crashes even if I force transcoding

**Comment by N8-Yue** [comment]
I reverted back to 0.16.11 and everything works fine. The file plays and works completely fine and is remuxing accordingly. On 0.17.1 it was transcoding and didn't work at all as the client crashed after stopping the movie. This is definitely a 0.17 issue that wasn't fixed with 0.17.1

**Comment by nielsvanvelzen** [comment]
Please share the app crash logs.

**Comment by N8-Yue** [comment]
[upload_org.jellyfin.androidtv_0.17.1_20240810114000_54bb9d38373d4c6db05317543d9046f7.log](https://github.com/user-attachments/files/16569595/upload_org.jellyfin.androidtv_0.17.1_20240810114000_54bb9d38373d4c6db05317543d9046f7.log)
