### ISSUE TITLE
response code 416 

### ISSUE THREAD

**Issue by bin101** [jellyfin/jellyfin-androidtv#3849]
### Describe the bug

Sadly I don't know the exact conditions but when I activate Dolby Digital bitstreaming and try to directplay the asset in question I get the following stacktrace inside logcat:
```
Playback error
  androidx.media3.exoplayer.ExoPlaybackException: Source error
    at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:736)
    at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:708)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.os.HandlerThread.run(HandlerThread.java:67)
  Caused by: androidx.media3.datasource.HttpDataSource$InvalidResponseCodeException: Response code: 416
    at androidx.media3.datasource.DefaultHttpDataSource.open(DefaultHttpDataSource.java:397)
    at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:275)
    at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
    at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1045)
    at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)
  Caused by: androidx.media3.datasource.DataSourceException
    at androidx.media3.datasource.DefaultHttpDataSource.open(DefaultHttpDataSource.java:395)
    at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:275)
    at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
    at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1045)
    at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)
``` 

This is the only hint I can deliver, nothing is uploaded to my jellyfin server instance. Just this plain stacktrace is available. The App directly responses with `Player-Error: trying again` and `to much errors: abort` Toasts.

But maybe this is related upstream in media3?:
https://github.com/androidx/media/issues/1071

### Logs

nothing uploaded to my jellyfin server

### FFmpeg logs

```shell
nothing uploaded to my jellyfin server
```

### Media info of the file

```shell
Video
Title: 4K HEVC HDR
Codec: HEVC
AVC: No
Profile: Main 10
Level: 153
Resolution: 3840x1608
Aspect ratio: 2.40:1
Anamorphic: No
Interlaced: No
Framerate: 23.976025
Bitrate: 16776 kbps
Bit depth: 10 bit
Video range: HDR
Video range type: HDR10
Color space: bt2020nc
Color transfer: smpte2084
Color primaries: bt2020
Pixel format: yuv420p10le
Ref frames: 1

Audio
Title: E-AC-3 7.1 - English - Dolby Digital+ - Default
Language: eng
Codec: EAC3
AVC: No
Layout: 7.1
Channels: 8 ch
Bitrate: 768 kbps
Sample rate: 48000 Hz
Default: Yes
Forced: No
External: No

Subtitle
Title: English - SUBRIP
Language: eng
Codec: SUBRIP
AVC: No
Default: No
Forced: No
External: No
```

### Application version

0.17.0

### Device information

Philips TV 77OLED908 + Sennheiser Ambeo Max soundbar

### Android version

Android TV 12

### Jellyfin server version

10.9.9

**Comment by nielsvanvelzen** [comment]
Are you connecting directly to the Jellyfin server or do you have any proxies in between (like nginx)?

**Comment by bin101** [comment]
@nielsvanvelzen I have an nginx running. I am wondering why this would have anything to do with my problem. Every other client plays the asset fine and it doesn't matter if I use directplay or transcoding.

With disabled Dolby Digital bitstreaming the asset also played fine on my Philips TV

**Comment by bin101** [comment]
And I double checked the configuration of the android tv client this evening: I used the ip:port variant during the initial setup, so the traffic isn't even touching my proxy.

**Comment by nielsvanvelzen** [comment]
The reason I asked is that sometimes a reverse proxy can cause such issues. Nginx should work fine though. Is it specific to just this one file or are you having this problem with multiple files?

**Comment by bin101** [comment]
I feel so dumb... it WAS just this one file. Reencoded the blueray and now it works... Sorry to bother you.

**Comment by bin101** [comment]
But the app didn't report anything to the server, so this could be improved.

**Comment by nielsvanvelzen** [comment]
Good to hear it was just an encoding issue and you were able to fix it. Improving our error handling is definitely something I'm working on as part of the overall changes to the playback code.
