### ISSUE TITLE
LiveTV throws errors and no playback after upgrade to 17.x

### ISSUE THREAD

**Issue by Shekyno6** [jellyfin/jellyfin-androidtv#3853]
### Describe the bug

Connect to Jellyfin server via app on FireTV stick, click LiveTV, click channel, error prompt received that there are too many errors and log is being sent to my server.
Previously worked on FireTV stick. Still works in browser.

### Logs

---
client: Jellyfin for Android TV
client_version: 0.17.1
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.IllegalStateException: Fragment CustomPlaybackOverlayFragment{8195617} (8c96e4da-3b4d-445e-88cb-5cd740a30a92) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:977)
	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.lambda$prepareChannelAdapter$11$org-jellyfin-androidtv-ui-playback-CustomPlaybackOverlayFragment(CustomPlaybackOverlayFragment.java:1300)
	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment$$ExternalSyntheticLambda12.apply(D8$$SyntheticClass:0)
	at org.jellyfin.androidtv.ui.livetv.TvManager.lambda$loadAllChannels$0(TvManager.java:102)
	at org.jellyfin.androidtv.ui.livetv.TvManager$$ExternalSyntheticLambda2.invoke(D8$$SyntheticClass:0)
	at org.jellyfin.androidtv.ui.livetv.TvManagerHelperKt$loadLiveTvChannels$1.invokeSuspend(TvManagerHelper.kt:46)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:6775)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c48be3e, Dispatchers.Main.immediate]

```  

### App information

***App version***: `0.17.1` (`170199`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"sheldonp","BOOTLOADER":"unknown","BRAND":"Amazon","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"sheldonp","DISPLAY":"PS7673.4183N","FINGERPRINT":"Amazon\/sheldonp\/sheldonp:9\/PS7673.4183N\/0030367831808:user\/amz-p,release-keys","HARDWARE":"mt8695","HOST":"i3-ri-14-use1a-b-16-04-fos-144","ID":"PS7673.4183N","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Amazon","MODEL":"AFTSSS","PERMISSIONS_REVIEW_REQUIRED":false,"PRODUCT":"sheldonp","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"amz-p,release-keys","TIME":1715944319000,"TYPE":"user","UNKNOWN":"unknown","USER":"build","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"PPR1.180610.009","CODENAME":"REL","FIRST_SDK_INT":28,"INCREMENTAL":"0030367831940","PREVIEW_SDK_INT":0,"RELEASE":"9","RESOURCES_SDK_INT":28,"SDK":"28","SDK_INT":28,"SECURITY_PATCH":"2024-02-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":170199,"VERSION_NAME":"0.17.1"}
```  

### Device information

***Android version***: `9`  
***Device brand***: `Amazon`  
***Device product***: `sheldonp`  
***Device model***: `AFTSSS`  

### Crash information

***Start time***: `2024-08-07T11:13:31.484-04:00`  
***Crash time***: `2024-08-07T11:13:45.185-04:00`  

### Application version

0.17.1

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon Fire Stick

### Android version

N/A

### Jellyfin server version

10.9.9

**Comment by Shekyno6** [comment]
I have resolved this inside the Advanced Playback settings and unclicking direct stream and instead using transcode when necessary. Previously this was not needed.

**Comment by nielsvanvelzen** [comment]
Yes some Live TV streams don't work when requested by the client and they need to be retrieves via the Jellyfin server. That is where you use that option for. Closing as resolved.
