### ISSUE TITLE
0.17.2 playback and press back button, the app crash

### ISSUE THREAD

**Issue by Zachwang007** [jellyfin/jellyfin-androidtv#3880]
### Describe the bug

0.17.2 playback and press back button, the app crash,but with app 0.17.1 is normal.

### Logs

---
client: Jellyfin for Android TV
client_version: 0.17.2
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at org.jellyfin.androidtv.ui.browsing.composable.inforow.BaseItemInfoRowKt.getDefault(BaseItemInfoRow.kt:142)
	at org.jellyfin.androidtv.ui.browsing.composable.inforow.BaseItemInfoRowKt.InfoRowMediaDetails(BaseItemInfoRow.kt:153)
	at org.jellyfin.androidtv.ui.browsing.composable.inforow.BaseItemInfoRowKt.BaseItemInfoRow(BaseItemInfoRow.kt:366)
	at org.jellyfin.androidtv.ui.browsing.composable.inforow.BaseItemInfoRowView.Content(BaseItemInfoRow.kt:412)
	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:252)
	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:251)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:186)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:119)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:118)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:110)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:139)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:138)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:138)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:123)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:90)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3302)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3235)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:725)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1071)
	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:633)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:619)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:123)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:114)
	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1289)
	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:114)
	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:164)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.jvm.kt:320)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.jvm.kt:198)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:121)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:114)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1364)
	at android.view.View.dispatchAttachedToWindow(View.java:20487)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3495)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5284)
	at android.view.ViewGroup.addView(ViewGroup.java:5070)
	at android.view.ViewGroup.addView(ViewGroup.java:5010)
	at androidx.recyclerview.widget.RecyclerView$5.addView(RecyclerView.java:950)
	at androidx.recyclerview.widget.ChildHelper.addView(ChildHelper.java:131)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:9430)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:9388)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:9375)
	at androidx.leanback.widget.GridLayoutManager$2.createItem(GridLayoutManager.java:1660)
	at androidx.leanback.widget.SingleRow.appendVisibleItems(SingleRow.java:113)
	at androidx.leanback.widget.Grid.appendOneColumnVisibleItems(Grid.java:389)
	at androidx.leanback.widget.GridLayoutManager.appendOneColumnVisibleItems(GridLayoutManager.java:1870)
	at androidx.leanback.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:2303)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
	at android.view.View.layout(View.java:22886)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22886)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:22886)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22886)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:22886)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22886)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22886)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:784)
	at android.view.View.layout(View.java:22886)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3505)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2961)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1964)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8258)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:990)
	at android.view.Choreographer.doCallbacks(Choreographer.java:813)
	at android.view.Choreographer.doFrame(Choreographer.java:744)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:975)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7683)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

```  
***Logcat***: 
```log
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:138)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:123)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:90)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3302)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3235)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:725)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1071)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:633)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:619)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:123)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:114)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1289)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:114)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:164)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.jvm.kt:320)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.jvm.kt:198)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:121)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:114)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1364)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.View.dispatchAttachedToWindow(View.java:20487)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3495)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5284)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.ViewGroup.addView(ViewGroup.java:5070)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.ViewGroup.addView(ViewGroup.java:5010)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.recyclerview.widget.RecyclerView$5.addView(RecyclerView.java:950)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.recyclerview.widget.ChildHelper.addView(ChildHelper.java:131)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:9430)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:9388)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:9375)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.leanback.widget.GridLayoutManager$2.createItem(GridLayoutManager.java:1660)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.leanback.widget.SingleRow.appendVisibleItems(SingleRow.java:113)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.leanback.widget.Grid.appendOneColumnVisibleItems(Grid.java:389)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.leanback.widget.GridLayoutManager.appendOneColumnVisibleItems(GridLayoutManager.java:1870)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.leanback.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:2303)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
08-11 21:33:06.691 E/ACRA    (24407): 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.View.layout(View.java:22886)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.ViewGroup.layout(ViewGroup.java:6395)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.View.layout(View.java:22886)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.ViewGroup.layout(ViewGroup.java:6395)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.View.layout(View.java:22886)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.ViewGroup.layout(ViewGroup.java:6395)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.View.layout(View.java:22886)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.ViewGroup.layout(ViewGroup.java:6395)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.View.layout(View.java:22886)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.ViewGroup.layout(ViewGroup.java:6395)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.View.layout(View.java:22886)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.ViewGroup.layout(ViewGroup.java:6395)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.View.layout(View.java:22886)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.ViewGroup.layout(ViewGroup.java:6395)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
08-11 21:33:06.691 E/ACRA    (24407): 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:784)
08-11 21:33:06.691 E/ACRA    (24407): 	at android.view.View.layout(View.java:22886)
08-11 21:33:06.692 E/ACRA    (24407): 	at android.view.ViewGroup.layout(ViewGroup.java:6395)
08-11 21:33:06.692 E/ACRA    (24407): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3505)
08-11 21:33:06.692 E/ACRA    (24407): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2961)
08-11 21:33:06.692 E/ACRA    (24407): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1964)
08-11 21:33:06.692 E/ACRA    (24407): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8258)
08-11 21:33:06.692 E/ACRA    (24407): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:990)
08-11 21:33:06.692 E/ACRA    (24407): 	at android.view.Choreographer.doCallbacks(Choreographer.java:813)
08-11 21:33:06.692 E/ACRA    (24407): 	at android.view.Choreographer.doFrame(Choreographer.java:744)
08-11 21:33:06.692 E/ACRA    (24407): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:975)
08-11 21:33:06.692 E/ACRA    (24407): 	at android.os.Handler.handleCallback(Handler.java:938)
08-11 21:33:06.692 E/ACRA    (24407): 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-11 21:33:06.692 E/ACRA    (24407): 	at android.os.Looper.loop(Looper.java:236)
08-11 21:33:06.692 E/ACRA    (24407): 	at android.app.ActivityThread.main(ActivityThread.java:7683)
08-11 21:33:06.692 E/ACRA    (24407): 	at java.lang.reflect.Method.invoke(Native Method)
08-11 21:33:06.692 E/ACRA    (24407): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
08-11 21:33:06.692 E/ACRA    (24407): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
08-11 21:33:06.692 D/ACRA    (24407): Building report
08-11 21:33:06.692 D/ACRA    (24407): Starting collectors with priority FIRST
08-11 21:33:06.693 D/ACRA    (24407): Calling collector org.acra.collector.DropBoxCollector
08-11 21:33:06.693 D/ACRA    (24407): Collector org.acra.collector.DropBoxCollector completed
08-11 21:33:06.693 D/ACRA    (24407): Calling collector org.acra.collector.LogCatCollector
08-11 21:33:06.696 D/ACRA    (24407): Calling collector org.acra.collector.StacktraceCollector
08-11 21:33:06.699 D/ACRA    (24407): Collector org.acra.collector.StacktraceCollector completed
08-11 21:33:06.700 D/ACRA    (24407): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.17.2` (`170299`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"freeguy","BOOTLOADER":"01.01.240413","BRAND":"xiaomi","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"freeguy","DISPLAY":"V816.0.21.0.RFTMATV","FINGERPRINT":"xiaomi\/freeguy\/freeguy:11\/RP1A.200720.011\/V816.0.21.0.RFTMATV:user\/release-keys","HARDWARE":"mt9653","HOST":"pangu-build-component-system-85348-2hss0-vkdfs-n030g","ID":"RP1A.200720.011","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"xiaomi","MODEL":"MiTV-MFTR0","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"freeguy","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1712969343000,"TYPE":"user","UNKNOWN":"unknown","USER":"builder","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"V816.0.21.0.RFTMATV","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"11","RELEASE_OR_CODENAME":"11","SDK":"30","SDK_INT":30,"SECURITY_PATCH":"2023-02-05"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":170299,"VERSION_NAME":"0.17.2"}
```  

### Device information

***Android version***: `11`  
***Device brand***: `xiaomi`  
***Device product***: `freeguy`  
***Device model***: `MiTV-MFTR0`  

### Crash information

***Start time***: `2024-08-11T21:30:58.121+08:00`  
***Crash time***: `2024-08-11T21:33:06.813+08:00`  

### Application version

0.17.2

### Where did you install the app from?

None

### Device information

xiaomi  s pro 65

### Android version

android 11

### Jellyfin server version

10.9.9

**Comment by rickysixx** [comment]
I am facing too a crash with the same exception stacktrace, but in my case it happens when I open the detail of a movie (the screen with the play button, movie info, etc.) from the home screen.

After a debugging session I have found that the exception is caused by a `defaultIndex = -1` in the `getDefault()` method (in my case that `-1` is the result of `mediaSource.mediaStreams?.getDefault(MediaStreamType.SUBTITLE, mediaSource.defaultSubtitleStreamIndex)`).

**Comment by nielsvanvelzen** [comment]
Thanks for reporting, the media I tested with all had default tracks set and I wrongfully assumed the server would send a `null` value instead of a `-1` value if there is no default. Fixed for the next release.

**Comment by Zachwang007** [comment]
> d default tracks set and I wrongfully assumed t

everytime you update the app and the server ,i try it at once.
