### ISSUE TITLE
Playback error when seeking

### ISSUE THREAD

**Issue by kingp0dd** [jellyfin/jellyfin-androidtv#3907]
### Describe the bug

Plays fine when played, but when seeking forward/back, gives error Playback error.
Happened with two files already, both are:

`Codec: MPEG-H Part2/HEVC (H.265) (hevc)`

### Logs

```
[2024-08-18 21:43:49.432 +08:00] [INF] [41] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "john". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-08-18 21:43:49.539 +08:00] [WRN] [86] Trakt.ServerMediator: Received playback progress from user "john" but initial state was never set - setting it now!
[2024-08-18 21:44:05.000 +08:00] [INF] [86] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Android" "2.6.2" playing "The Hunger Games: The Ballad of Songbirds & Snakes". Stopped at "4552133" ms
[2024-08-18 21:45:04.193 +08:00] [ERR] [34] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Shows/114fb20a65f04cbf5113f9fcb734eb40/Seasons".
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Controller.Entities.Folder.FillUserDataDtoValues(UserItemDataDto dto, UserItemData userData, BaseItemDto itemDto, User user, DtoOptions fields)
   at Emby.Server.Implementations.Dto.DtoService.AttachUserSpecificInfo(BaseItemDto dto, BaseItem item, User user, DtoOptions options)
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtoInternal(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtos(IReadOnlyList`1 items, DtoOptions options, User user, BaseItem owner)
   at Jellyfin.Api.Controllers.TvShowsController.GetSeasons(Guid seriesId, Nullable`1 userId, ItemFields[] fields, Nullable`1 isSpecialSeason, Nullable`1 isMissing, Nullable`1 adjacentTo, Nullable`1 enableImages, Nullable`1 imageTypeLimit, ImageType[] enableImageTypes, Nullable`1 enableUserData)
   at lambda_method1250(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2024-08-18 21:46:12.422 +08:00] [WRN] [8] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "10.10.1.245" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2024-08-18 21:46:12.424 +08:00] [INF] [8] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "10.10.1.245" closed
```
### Application version

0.17.3

### Where did you install the app from?

Google Play

### Device information

Chromecast Ultra

### Android version

Android 9

### Jellyfin server version

10.9.9

**Comment by nmeyvis** [comment]
I'm getting the same broken behavior with a h.265 file.

**Comment by AT-StephenDetomasi** [comment]
Same issue here with x265 encoded media. TCL 65" TV
