### ISSUE TITLE
Crashing when switching to next episode in playlist

### ISSUE THREAD

**Issue by jadev-projects** [jellyfin/jellyfin-androidtv#3926]
### Describe the bug

1.Go to playlist
2.Select first track
3.Play and wait for the next track

When the player needs to skip to the next track, the application crashes.

### Logs

---
client: Jellyfin for Android TV
client_version: 0.17.3
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.NullPointerException: Parameter specified as non-null is null: method org.jellyfin.androidtv.util.InfoLayoutHelper.addInfoRow, parameter layout
	at org.jellyfin.androidtv.util.InfoLayoutHelper.addInfoRow(Unknown Source:7)
	at org.jellyfin.androidtv.ui.itemdetail.ItemListFragment.setBaseItem(ItemListFragment.java:311)
	at org.jellyfin.androidtv.ui.itemdetail.ItemListFragmentHelperKt$loadItem$1.invokeSuspend(ItemListFragmentHelper.kt:33)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:65)
	at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:343)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:146)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:11)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:70)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6721)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d15e87b, Dispatchers.Main.immediate]

```  

### Application version

0.17.3

### Device information

Nvidia Shield

### Android version

Android 9

### Jellyfin server version

10.9.9

**Comment by JousiaPiha** [comment]
I have the same problem with server 10.9.9 and client 0.17.4. However, I found a workaround: it's working when preferences => playback => show next video info is set to 'never'
