### ISSUE TITLE
Jellyfin crushes while playing videos in a playlist.

### ISSUE THREAD

**Issue by mathias-ted** [jellyfin/jellyfin-androidtv#3950]
### Describe the bug

I added a total of  100 videos to my playlist. When I click the "Play All" or "Shuffle" button, Jellyfin only plays the first video and crashes while trying to play the second video.

### Logs

client: Jellyfin for Android TV
client_version: 0.17.4
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.NullPointerException: Parameter specified as non-null is null: method org.jellyfin.androidtv.util.InfoLayoutHelper.addInfoRow, parameter layout
	at org.jellyfin.androidtv.util.InfoLayoutHelper.addInfoRow(InfoLayoutHelper.kt)
	at org.jellyfin.androidtv.ui.itemdetail.ItemListFragment.setBaseItem(ItemListFragment.java:311)
	at org.jellyfin.androidtv.ui.itemdetail.ItemListFragmentHelperKt$loadItem$1.invokeSuspend(ItemListFragmentHelper.kt:33)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:65)
	at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:343)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:146)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:11)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:70)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ebb28b0, Dispatchers.Main.immediate]

```  
  

### App information

***App version***: `0.17.4` (`170499`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"p281","BOOTLOADER":"unknown","BRAND":"Amlogic","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"p281","DISPLAY":"p281-userdebug 7.1.2 NHG47L 20180412 test-keys","FINGERPRINT":"Amlogic\/p281\/p281:7.1.2\/NHG47L\/20180412:userdebug\/test-keys","HARDWARE":"amlogic","HOST":"akrd-51","ID":"NHG47L","IS_DEBUGGABLE":true,"IS_EMULATOR":false,"MANUFACTURER":"Amlogic","MODEL":"MXQpro","PERMISSIONS_REVIEW_REQUIRED":false,"PRODUCT":"p281","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"test-keys","TIME":1523497614000,"TYPE":"userdebug","UNKNOWN":"unknown","USER":"aike4","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"20180412","PREVIEW_SDK_INT":0,"RELEASE":"7.1.2","RESOURCES_SDK_INT":25,"SDK":"25","SDK_INT":25,"SECURITY_PATCH":"2017-08-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":170499,"VERSION_NAME":"0.17.4"}
```  

### Device information

***Android version***: `7.1.2`  
***Device brand***: `Amlogic`  
***Device product***: `p281`  
***Device model***: `MXQpro`  

### Crash information

***Start time***: `2015-01-01T03:08:46.156+03:00`  
***Crash time***: `2015-01-01T03:14:11.146+03:00`  

### Application version

0.17.4

### Device information

MXQpro

### Android version

Android 7.1.2

### Jellyfin server version

10.9.7

**Comment by amavis442** [comment]
I get a little different error when just playing playlist randomly. It does not play anything and just crashes.

---
client: Jellyfin for Android TV
client_version: 0.17.4
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.NullPointerException: Attempt to invoke virtual method 'void org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.onPause()' on a null object reference
	at org.jellyfin.androidtv.ui.playback.overlay.LeanbackOverlayFragment.onPause(LeanbackOverlayFragment.java:92)
	at androidx.fragment.app.Fragment.performPause(Fragment.java:3330)
	at androidx.fragment.app.FragmentStateManager.pause(FragmentStateManager.java:692)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:318)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1675)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3259)
	at androidx.fragment.app.FragmentManager.dispatchPause(FragmentManager.java:3195)
	at androidx.fragment.app.Fragment.performPause(Fragment.java:3323)
	at androidx.fragment.app.FragmentStateManager.pause(FragmentStateManager.java:692)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:318)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2155)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2059)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:702)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```  
***Logcat***: 
```log
09-01 17:07:58.126 D/HorizontalGridPresenter(13835): onBindViewHolder org.jellyfin.androidtv.ui.itemhandling.ItemRowAdapter@1838b9b
09-01 17:07:58.131 I/org.jellyfin.sdk.api.ktor.KtorClient(13835): GET http://192.168.2.210:8096/Items?startIndex=0&limit=36&recursive=true&sortOrder=Ascending&fields=PrimaryImageAspectRatio&fields=ChildCount&fields=MediaSources&fields=MediaStreams&fields=DisplayPreferencesId&includeItemTypes=BoxSet&sortBy=SortName&enableTotalRecordCount=true&enableImages=true
09-01 17:07:58.133 V/io.ktor.client.plugins.HttpPlainText(13835): Adding Accept-Charset=UTF-8 to http://192.168.2.210:8096/Items?startIndex=0&limit=36&recursive=true&sortOrder=Ascending&fields=PrimaryImageAspectRatio&fields=ChildCount&fields=MediaSources&fields=MediaStreams&fields=DisplayPreferencesId&includeItemTypes=BoxSet&sortBy=SortName&enableTotalRecordCount=true&enableImages=true
09-01 17:07:58.178 D/BrowseGridFragment(13835): row selected position 0
09-01 17:07:58.185 V/io.ktor.client.plugins.HttpCallValidator(13835): Validating response for request http://192.168.2.210:8096/Items?startIndex=0&limit=36&recursive=true&sortOrder=Ascending&fields=PrimaryImageAspectRatio&fields=ChildCount&fields=MediaSources&fields=MediaStreams&fields=DisplayPreferencesId&includeItemTypes=BoxSet&sortBy=SortName&enableTotalRecordCount=true&enableImages=true
09-01 17:07:58.185 V/io.ktor.client.plugins.DefaultResponseValidation(13835): Skipping default response validation for http://192.168.2.210:8096/Items?startIndex=0&limit=36&recursive=true&sortOrder=Ascending&fields=PrimaryImageAspectRatio&fields=ChildCount&fields=MediaSources&fields=MediaStreams&fields=DisplayPreferencesId&includeItemTypes=BoxSet&sortBy=SortName&enableTotalRecordCount=true&enableImages=true
09-01 17:07:58.186 V/io.ktor.client.plugins.defaultTransformers(13835): Transformed with default transformers response body for http://192.168.2.210:8096/Items?startIndex=0&limit=36&recursive=true&sortOrder=Ascending&fields=PrimaryImageAspectRatio&fields=ChildCount&fields=MediaSources&fields=MediaStreams&fields=DisplayPreferencesId&includeItemTypes=BoxSet&sortBy=SortName&enableTotalRecordCount=true&enableImages=true to interface io.ktor.utils.io.ByteReadChannel (Kotlin reflection is not available)
09-01 17:07:58.189 D/ItemRowAdapterHelperKt(13835): Creating items from 0 existing and 1 new, adapter size is 1
09-01 17:07:58.665 D/BrowseGridFragment(13835): Refresh item "Relax"
09-01 17:07:58.666 I/org.jellyfin.sdk.api.ktor.KtorClient(13835): GET http://192.168.2.210:8096/Items/234c8c02-7734-3045-9aba-5f6c693e9e3d
09-01 17:07:58.668 V/io.ktor.client.plugins.HttpPlainText(13835): Adding Accept-Charset=UTF-8 to http://192.168.2.210:8096/Items/234c8c02-7734-3045-9aba-5f6c693e9e3d
09-01 17:07:58.684 V/io.ktor.client.plugins.HttpCallValidator(13835): Validating response for request http://192.168.2.210:8096/Items/234c8c02-7734-3045-9aba-5f6c693e9e3d
09-01 17:07:58.684 V/io.ktor.client.plugins.DefaultResponseValidation(13835): Skipping default response validation for http://192.168.2.210:8096/Items/234c8c02-7734-3045-9aba-5f6c693e9e3d
09-01 17:07:58.686 V/io.ktor.client.plugins.defaultTransformers(13835): Transformed with default transformers response body for http://192.168.2.210:8096/Items/234c8c02-7734-3045-9aba-5f6c693e9e3d to interface io.ktor.utils.io.ByteReadChannel (Kotlin reflection is not available)
09-01 17:07:58.710 D/BrowseGridFragment(13835): row selected position 0
09-01 17:08:01.457 D/org.jellyfin.sdk.api.sockets.OkHttpSocketConnection(13835): Sending (raw) message {"MessageType":"KeepAlive"}
09-01 17:08:01.470 D/org.jellyfin.sdk.api.sockets.OkHttpSocketConnection(13835): Receiving (raw) message {"MessageId":"d15951449c094419a7fc56376ada2079","MessageType":"KeepAlive"}
09-01 17:08:06.501 D/KeyProcessor(13835): Menu for: Relax
09-01 17:08:13.285 I/lyfin.androidt(13835): Background concurrent copying GC freed 172785(22MB) AllocSpace objects, 23(1488KB) LOS objects, 49% free, 10MB/20MB, paused 130us total 211.437ms
09-01 17:08:13.827 I/org.jellyfin.sdk.api.ktor.KtorClient(13835): GET http://192.168.2.210:8096/Items/234c8c02-7734-3045-9aba-5f6c693e9e3d
09-01 17:08:13.829 V/io.ktor.client.plugins.HttpPlainText(13835): Adding Accept-Charset=UTF-8 to http://192.168.2.210:8096/Items/234c8c02-7734-3045-9aba-5f6c693e9e3d
09-01 17:08:13.846 V/io.ktor.client.plugins.HttpCallValidator(13835): Validating response for request http://192.168.2.210:8096/Items/234c8c02-7734-3045-9aba-5f6c693e9e3d
09-01 17:08:13.846 V/io.ktor.client.plugins.DefaultResponseValidation(13835): Skipping default response validation for http://192.168.2.210:8096/Items/234c8c02-7734-3045-9aba-5f6c693e9e3d
09-01 17:08:13.849 V/io.ktor.client.plugins.defaultTransformers(13835): Transformed with default transformers response body for http://192.168.2.210:8096/Items/234c8c02-7734-3045-9aba-5f6c693e9e3d to interface io.ktor.utils.io.ByteReadChannel (Kotlin reflection is not available)
09-01 17:08:13.859 I/org.jellyfin.sdk.api.ktor.KtorClient(13835): GET http://192.168.2.210:8096/Items?isMissing=false&limit=150&recursive=true&parentId=234c8c02-7734-3045-9aba-5f6c693e9e3d&fields=MediaSources&fields=MediaStreams&fields=Chapters&fields=Path&fields=Overview&fields=PrimaryImageAspectRatio&fields=ChildCount&includeItemTypes=Episode&includeItemTypes=Movie&includeItemTypes=Video&sortBy=Random&enableTotalRecordCount=true&enableImages=true
09-01 17:08:13.861 V/io.ktor.client.plugins.HttpPlainText(13835): Adding Accept-Charset=UTF-8 to http://192.168.2.210:8096/Items?isMissing=false&limit=150&recursive=true&parentId=234c8c02-7734-3045-9aba-5f6c693e9e3d&fields=MediaSources&fields=MediaStreams&fields=Chapters&fields=Path&fields=Overview&fields=PrimaryImageAspectRatio&fields=ChildCount&includeItemTypes=Episode&includeItemTypes=Movie&includeItemTypes=Video&sortBy=Random&enableTotalRecordCount=true&enableImages=true
09-01 17:08:13.874 V/io.ktor.client.plugins.HttpCallValidator(13835): Validating response for request http://192.168.2.210:8096/Items?isMissing=false&limit=150&recursive=true&parentId=234c8c02-7734-3045-9aba-5f6c693e9e3d&fields=MediaSources&fields=MediaStreams&fields=Chapters&fields=Path&fields=Overview&fields=PrimaryImageAspectRatio&fields=ChildCount&includeItemTypes=Episode&includeItemTypes=Movie&includeItemTypes=Video&sortBy=Random&enableTotalRecordCount=true&enableImages=true
09-01 17:08:13.874 V/io.ktor.client.plugins.DefaultResponseValidation(13835): Skipping default response validation for http://192.168.2.210:8096/Items?isMissing=false&limit=150&recursive=true&parentId=234c8c02-7734-3045-9aba-5f6c693e9e3d&fields=MediaSources&fields=MediaStreams&fields=Chapters&fields=Path&fields=Overview&fields=PrimaryImageAspectRatio&fields=ChildCount&includeItemTypes=Episode&includeItemTypes=Movie&includeItemTypes=Video&sortBy=Random&enableTotalRecordCount=true&enableImages=true
09-01 17:08:13.875 V/io.ktor.client.plugins.defaultTransformers(13835): Transformed with default transformers response body for http://192.168.2.210:8096/Items?isMissing=false&limit=150&recursive=true&parentId=234c8c02-7734-3045-9aba-5f6c693e9e3d&fields=MediaSources&fields=MediaStreams&fields=Chapters&fields=Path&fields=Overview&fields=PrimaryImageAspectRatio&fields=ChildCount&includeItemTypes=Episode&includeItemTypes=Movie&includeItemTypes=Video&sortBy=Random&enableTotalRecordCount=true&enableImages=true to interface io.ktor.utils.io.ByteReadChannel (Kotlin reflection is not available)
09-01 17:08:13.883 D/NavigationRepositoryImpl(13835): Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment (Kotlin reflection is not available), arguments=Bundle[{Position=0}]) (via navigate function)
09-01 17:08:13.910 D/DefaultPlayerQueueState(13835): Queue changed, setting index to 0
09-01 17:08:13.911 D/CompatibilityChangeReporter(13835): Compat change id reported: 147798919; UID 10096; state: ENABLED
09-01 17:08:13.940 D/NavigationRepositoryImpl(13835): Navigating back
09-01 17:08:14.066 I/ExoPlayerImpl(13835): Init 730e1b5 [AndroidXMedia3/1.4.0] [sabrina, Chromecast, Google, 31]
09-01 17:08:14.068 I/DefaultRenderersFactory(13835): Loaded FfmpegVideoRenderer.
09-01 17:08:14.077 I/DefaultRenderersFactory(13835): Loaded FfmpegAudioRenderer.
09-01 17:08:14.112 W/AudioManager(13835): Use of stream types is deprecated for operations other than volume control
09-01 17:08:14.112 W/AudioManager(13835): See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
09-01 17:08:14.117 D/AndroidRuntime(13835): Shutting down VM
--------- beginning of crash
09-01 17:08:14.118 E/AndroidRuntime(13835): FATAL EXCEPTION: main
09-01 17:08:14.118 E/AndroidRuntime(13835): Process: org.jellyfin.androidtv, PID: 13835
09-01 17:08:14.118 E/AndroidRuntime(13835): java.lang.NullPointerException: Attempt to invoke virtual method 'void org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.onPause()' on a null object reference
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at org.jellyfin.androidtv.ui.playback.overlay.LeanbackOverlayFragment.onPause(LeanbackOverlayFragment.java:92)
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at androidx.fragment.app.Fragment.performPause(Fragment.java:3330)
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at androidx.fragment.app.FragmentStateManager.pause(FragmentStateManager.java:692)
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:318)
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1675)
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3259)
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at androidx.fragment.app.FragmentManager.dispatchPause(FragmentManager.java:3195)
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at androidx.fragment.app.Fragment.performPause(Fragment.java:3323)
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at androidx.fragment.app.FragmentStateManager.pause(FragmentStateManager.java:692)
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:318)
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2155)
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2059)
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:702)
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at android.os.Handler.handleCallback(Handler.java:938)
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at android.os.Looper.loopOnce(Looper.java:201)
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at android.os.Looper.loop(Looper.java:288)
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at java.lang.reflect.Method.invoke(Native Method)
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-01 17:08:14.118 E/AndroidRuntime(13835): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
09-01 17:08:14.119 E/ACRA    (13835): ACRA caught a NullPointerException for org.jellyfin.androidtv
09-01 17:08:14.119 E/ACRA    (13835): java.lang.NullPointerException: Attempt to invoke virtual method 'void org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.onPause()' on a null object reference
09-01 17:08:14.119 E/ACRA    (13835): 	at org.jellyfin.androidtv.ui.playback.overlay.LeanbackOverlayFragment.onPause(LeanbackOverlayFragment.java:92)
09-01 17:08:14.119 E/ACRA    (13835): 	at androidx.fragment.app.Fragment.performPause(Fragment.java:3330)
09-01 17:08:14.119 E/ACRA    (13835): 	at androidx.fragment.app.FragmentStateManager.pause(FragmentStateManager.java:692)
09-01 17:08:14.119 E/ACRA    (13835): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:318)
09-01 17:08:14.119 E/ACRA    (13835): 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
09-01 17:08:14.119 E/ACRA    (13835): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1675)
09-01 17:08:14.119 E/ACRA    (13835): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3259)
09-01 17:08:14.119 E/ACRA    (13835): 	at androidx.fragment.app.FragmentManager.dispatchPause(FragmentManager.java:3195)
09-01 17:08:14.119 E/ACRA    (13835): 	at androidx.fragment.app.Fragment.performPause(Fragment.java:3323)
09-01 17:08:14.119 E/ACRA    (13835): 	at androidx.fragment.app.FragmentStateManager.pause(FragmentStateManager.java:692)
09-01 17:08:14.119 E/ACRA    (13835): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:318)
09-01 17:08:14.119 E/ACRA    (13835): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2155)
09-01 17:08:14.119 E/ACRA    (13835): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2059)
09-01 17:08:14.119 E/ACRA    (13835): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
09-01 17:08:14.119 E/ACRA    (13835): 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:702)
09-01 17:08:14.119 E/ACRA    (13835): 	at android.os.Handler.handleCallback(Handler.java:938)
09-01 17:08:14.119 E/ACRA    (13835): 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-01 17:08:14.119 E/ACRA    (13835): 	at android.os.Looper.loopOnce(Looper.java:201)
09-01 17:08:14.119 E/ACRA    (13835): 	at android.os.Looper.loop(Looper.java:288)
09-01 17:08:14.119 E/ACRA    (13835): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
09-01 17:08:14.119 E/ACRA    (13835): 	at java.lang.reflect.Method.invoke(Native Method)
09-01 17:08:14.119 E/ACRA    (13835): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-01 17:08:14.119 E/ACRA    (13835): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
09-01 17:08:14.119 D/ACRA    (13835): Building report
09-01 17:08:14.120 D/ACRA    (13835): Starting collectors with priority FIRST
09-01 17:08:14.123 D/ACRA    (13835): Calling collector org.acra.collector.StacktraceCollector
09-01 17:08:14.124 D/ACRA    (13835): Collector org.acra.collector.StacktraceCollector completed
09-01 17:08:14.124 D/ACRA    (13835): Calling collector org.acra.collector.LogCatCollector
09-01 17:08:14.126 D/ACRA    (13835): Calling collector org.acra.collector.DropBoxCollector
09-01 17:08:14.126 D/ACRA    (13835): Collector org.acra.collector.DropBoxCollector completed
09-01 17:08:14.140 D/ACRA    (13835): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.17.4` (`170499`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"sabrina","BOOTLOADER":"01.01.231226.064815","BRAND":"google","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"sabrina","DISPLAY":"STTL.240508.005.12011027","FINGERPRINT":"google\/sabrina_prod_stable\/sabrina:12\/STTL.240508.005\/12011027:user\/release-keys","HARDWARE":"amlogic","HOST":"r-d3d21742fc70d910-xpkc","ID":"STTL.240508.005","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Google","MODEL":"Chromecast","ODM_SKU":"NL","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"sabrina_prod_stable","RADIO":"unknown","SKU":"NL","SOC_MANUFACTURER":"Amlogic","SOC_MODEL":"AMLS905D3","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1719300940000,"TYPE":"user","UNKNOWN":"unknown","USER":"android-build","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"12011027","MEDIA_PERFORMANCE_CLASS":0,"PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"12","RELEASE_OR_CODENAME":"12","SDK":"31","SDK_INT":31,"SECURITY_PATCH":"2024-06-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":170499,"VERSION_NAME":"0.17.4"}
```  

### Device information

***Android version***: `12`  
***Device brand***: `google`  
***Device product***: `sabrina_prod_stable`  
***Device model***: `Chromecast`  

### Crash information

***Start time***: `2024-09-01T14:38:19.298+02:00`  
***Crash time***: `2024-09-01T17:08:14.406+02:00`
