### ISSUE TITLE
Video does not start and trying to move forward crashes the app 

### ISSUE THREAD

**Issue by chattm** [jellyfin/jellyfin-androidtv#3956]
### Describe the bug

1 - Start playing one video
2 - Video does not start
3 - Click on a random timestamp 
4 - Player crashes

FYI, Video is read fine on other clients. Doesn't look like a codec issue, since this seems pretty basic : 
  Title 4K HEVC SDR
  Codec HEVC
  AVC No
  Profile Main 10
  Level 150
  Resolution 3840x1920
  Aspect ratio 2:1
  Anamorphic No
  Interlaced No
  Framerate 23.976025
  Bitrate 12611 kbps
  Bit depth 10 bit
  Video range SDR
  Video range type SDR
  Pixel format yuv420p10le
  Ref frames1

### Logs

---
client: Jellyfin for Android TV
client_version: 0.17.4
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jellyfin.androidtv.data.compat.StreamInfo.getPlaySessionId()' on a null object reference
	at org.jellyfin.androidtv.ui.playback.PlaybackManager.changeVideoStream(PlaybackManager.java:73)
	at org.jellyfin.androidtv.ui.playback.PlaybackController.seek(PlaybackController.java:1008)
	at org.jellyfin.androidtv.ui.playback.overlay.VideoPlayerAdapter.seekTo(VideoPlayerAdapter.java:51)
	at androidx.leanback.media.PlaybackBaseControlGlue.seekTo(PlaybackBaseControlGlue.java:611)
	at androidx.leanback.media.PlaybackTransportControlGlue$SeekUiClient.onSeekFinished(PlaybackTransportControlGlue.java:372)
	at androidx.leanback.app.PlaybackSupportFragment$11.onSeekFinished(PlaybackSupportFragment.java:1156)
	at androidx.leanback.widget.PlaybackTransportRowPresenter$ViewHolder.stopSeek(PlaybackTransportRowPresenter.java:396)
	at androidx.leanback.widget.PlaybackTransportRowPresenter$ViewHolder$4.onKey(PlaybackTransportRowPresenter.java:308)
	at android.view.View.dispatchKeyEvent(View.java:14243)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at androidx.leanback.widget.PlaybackTransportRowView.dispatchKeyEvent(PlaybackTransportRowView.java:71)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at androidx.leanback.widget.BaseGridView.dispatchKeyEvent(BaseGridView.java:1081)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:476)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1861)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4085)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.kt:103)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.kt:117)
	at org.jellyfin.androidtv.ui.browsing.MainActivity.dispatchKeyEvent(MainActivity.kt:213)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:390)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6186)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6054)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5529)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5704)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5761)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5737)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5895)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3217)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2759)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2750)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3194)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```  
***Logcat***: 
```log
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5737)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5895)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3217)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2759)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2750)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3194)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at android.os.MessageQueue.nativePollOnce(Native Method)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at android.os.MessageQueue.next(MessageQueue.java:335)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at android.os.Looper.loop(Looper.java:183)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at android.app.ActivityThread.main(ActivityThread.java:7668)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at java.lang.reflect.Method.invoke(Native Method)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-01 20:33:45.911 E/AndroidRuntime(20085): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
09-01 20:33:45.912 E/ACRA    (20085): ACRA caught a NullPointerException for org.jellyfin.androidtv
09-01 20:33:45.912 E/ACRA    (20085): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jellyfin.androidtv.data.compat.StreamInfo.getPlaySessionId()' on a null object reference
09-01 20:33:45.912 E/ACRA    (20085): 	at org.jellyfin.androidtv.ui.playback.PlaybackManager.changeVideoStream(PlaybackManager.java:73)
09-01 20:33:45.912 E/ACRA    (20085): 	at org.jellyfin.androidtv.ui.playback.PlaybackController.seek(PlaybackController.java:1008)
09-01 20:33:45.912 E/ACRA    (20085): 	at org.jellyfin.androidtv.ui.playback.overlay.VideoPlayerAdapter.seekTo(VideoPlayerAdapter.java:51)
09-01 20:33:45.912 E/ACRA    (20085): 	at androidx.leanback.media.PlaybackBaseControlGlue.seekTo(PlaybackBaseControlGlue.java:611)
09-01 20:33:45.912 E/ACRA    (20085): 	at androidx.leanback.media.PlaybackTransportControlGlue$SeekUiClient.onSeekFinished(PlaybackTransportControlGlue.java:372)
09-01 20:33:45.912 E/ACRA    (20085): 	at androidx.leanback.app.PlaybackSupportFragment$11.onSeekFinished(PlaybackSupportFragment.java:1156)
09-01 20:33:45.912 E/ACRA    (20085): 	at androidx.leanback.widget.PlaybackTransportRowPresenter$ViewHolder.stopSeek(PlaybackTransportRowPresenter.java:396)
09-01 20:33:45.912 E/ACRA    (20085): 	at androidx.leanback.widget.PlaybackTransportRowPresenter$ViewHolder$4.onKey(PlaybackTransportRowPresenter.java:308)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.View.dispatchKeyEvent(View.java:14243)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
09-01 20:33:45.912 E/ACRA    (20085): 	at androidx.leanback.widget.PlaybackTransportRowView.dispatchKeyEvent(PlaybackTransportRowView.java:71)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
09-01 20:33:45.912 E/ACRA    (20085): 	at androidx.leanback.widget.BaseGridView.dispatchKeyEvent(BaseGridView.java:1081)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
09-01 20:33:45.912 E/ACRA    (20085): 	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:476)
09-01 20:33:45.912 E/ACRA    (20085): 	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1861)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.app.Activity.dispatchKeyEvent(Activity.java:4085)
09-01 20:33:45.912 E/ACRA    (20085): 	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.kt:103)
09-01 20:33:45.912 E/ACRA    (20085): 	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)
09-01 20:33:45.912 E/ACRA    (20085): 	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.kt:117)
09-01 20:33:45.912 E/ACRA    (20085): 	at org.jellyfin.androidtv.ui.browsing.MainActivity.dispatchKeyEvent(MainActivity.kt:213)
09-01 20:33:45.912 E/ACRA    (20085): 	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:390)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6186)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6054)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5529)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5704)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5761)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5737)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5895)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3217)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2759)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2750)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3194)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.os.MessageQueue.nativePollOnce(Native Method)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.os.MessageQueue.next(MessageQueue.java:335)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.os.Looper.loop(Looper.java:183)
09-01 20:33:45.912 E/ACRA    (20085): 	at android.app.ActivityThread.main(ActivityThread.java:7668)
09-01 20:33:45.912 E/ACRA    (20085): 	at java.lang.reflect.Method.invoke(Native Method)
09-01 20:33:45.912 E/ACRA    (20085): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-01 20:33:45.912 E/ACRA    (20085): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
09-01 20:33:45.912 D/ACRA    (20085): Building report
09-01 20:33:45.912 D/ACRA    (20085): Starting collectors with priority FIRST
09-01 20:33:45.913 D/ACRA    (20085): Calling collector org.acra.collector.DropBoxCollector
09-01 20:33:45.913 D/ACRA    (20085): Calling collector org.acra.collector.LogCatCollector
09-01 20:33:45.913 D/ACRA    (20085): Collector org.acra.collector.DropBoxCollector completed
09-01 20:33:45.913 D/ACRA    (20085): Calling collector org.acra.collector.StacktraceCollector
09-01 20:33:45.914 D/ACRA    (20085): Collector org.acra.collector.StacktraceCollector completed
09-01 20:33:45.921 D/ACRA    (20085): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.17.4` (`170499`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"darcy","BOOTLOADER":"32.00.2019.50-t210-69ebfcbe","BRAND":"NVIDIA","CPU_ABI":"arm64-v8a","CPU_ABI2":"","DEVICE":"mdarcy","DISPLAY":"RQ1A.210105.003.7825230_3167.5736","FINGERPRINT":"NVIDIA\/mdarcy\/mdarcy:11\/RQ1A.210105.003\/7825230_3167.5736:user\/release-keys","HARDWARE":"darcy","HOST":"mobile-u64-5308-d7000","ID":"RQ1A.210105.003","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"NVIDIA","MODEL":"SHIELD Android TV","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"mdarcy","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":["arm64-v8a"],"SUPPORTED_ABIS":["arm64-v8a","armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1665975826000,"TYPE":"user","UNKNOWN":"unknown","USER":"NVIDIA","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"7825230_3167.5736","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"11","RELEASE_OR_CODENAME":"11","SDK":"30","SDK_INT":30,"SECURITY_PATCH":"2022-04-05"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":170499,"VERSION_NAME":"0.17.4"}
```  

### Device information

***Android version***: `11`  
***Device brand***: `NVIDIA`  
***Device product***: `mdarcy`  
***Device model***: `SHIELD Android TV`  

### Crash information

***Start time***: `2024-09-01T20:32:09.004+02:00`  
***Crash time***: `2024-09-01T20:33:45.955+02:00`  

### Application version

0.17.4

### Device information

SHIELD Android TV 2019

### Android version

Android 11

### Jellyfin server version

10.9.10

**Comment by patrickdk77** [comment]
looks like a duplicate of #3952

**Comment by chattm** [comment]
Issue #3952  was fixed but I am still having the issue on the latest version.

**Comment by chattm** [comment]
After further investigation, it looks like the issue is coming from ASS format subtitles. I am reading media with subtitles put by default and when videos have only ass format subtitles, the video is stuck and you are unable to do anything (including remove/change subtitles). 
Is it possible to catch the error in this case, and ignore the subtitles if the player is unable to read them ?
