### ISSUE TITLE
Fire TV 4K Server not reachable

### ISSUE THREAD

**Issue by LegendaryB** [jellyfin/jellyfin-androidtv#399]
Hello Guys,

I received my new Fire TV 4K Stick and are not able to connect the app to the server. I use the newest jellyfin server version in docker + the newest app version from the store.
The only thing I could find is this in the logs:

```
[2020-03-15 01:28:01.990 +01:00] [ERR] Error in DummySeasonProvider
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at TvDbSharper.Infrastructure.ApiClient.SendRequestAsync(ApiRequest request, CancellationToken cancellationToken)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetAllEpisodesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.MissingEpisodeProvider.Run(Series series, Boolean addNewItems, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.SeriesMetadataService.AfterMetadataRefresh(Series item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
```

It always happens after I press login in the app.
Any ideas?

**Comment by thornbill** [comment]
Can you provide some more details about what error you see in the app and when it happens? Are you entering the server url and getting to the select user screen? Thanks!

**Comment by LegendaryB** [comment]
Im trying to connect by ip. I'm entering the 192.168.1.2:81 like before. So this should be fine I guess. I'm not getting to the user select screen. I just directly get a Android Toast with the Text "Server not reachable".

**Comment by LegendaryB** [comment]
Any ideas?

**Comment by nielsvanvelzen** [comment]
Can you try adding a protocol? (so `http://192.168.1.2:81` or `https://192.168.1.2:81`). Also, are you sure you're running with port 81? The default for Jellyfin is 8096.

**Comment by LegendaryB** [comment]
I will try it and report back. I'm using 81 because my host port 81 is mapped to 8096 of the container

**Comment by LegendaryB** [comment]
I get the same error message. Via Web UI everything works as expected hm

**Comment by LegendaryB** [comment]
Anything new?

**Comment by AndreasGB** [comment]
Hi there, this appears to be a problem with your network or docker setup, as for me connecting by IP and port 81 works in the emulator as well as on my Nexus Player.

Can you please provide more details such as the docker-compose file you are using?

**Comment by LegendaryB** [comment]
Thanks for the answers. I will reorganize my setup on the long weekend. If the problem persists I will just reopen this issue

**Comment by AndreasGB** [comment]
Sure, good luck :)
