### ISSUE TITLE
Jellyfin crashes when trying to load main page

### ISSUE THREAD

**Issue by Sulframus** [jellyfin/jellyfin-androidtv#4013]
### Describe the bug

When trying to open Jellyfin to go into the main page, it crashes. Application works before being signed in or if trying to open an episode from AndroidTV home screen. Tested with Findroid, which worked fine.

### Logs

---
client: Jellyfin for Android TV
client_version: 0.17.5
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
org.jellyfin.sdk.api.client.exception.InvalidStatusException: Invalid HTTP status in response: 404
	at org.jellyfin.sdk.api.ktor.KtorClient.request$suspendImpl(KtorClient.kt:132)
	at org.jellyfin.sdk.api.ktor.KtorClient$request$1.invokeSuspend(Unknown Source:19)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at org.jellyfin.androidtv.ui.home.HomeFragmentLatestRow.addToRowsAdapter(HomeFragmentLatestRow.kt:28)
	at org.jellyfin.androidtv.ui.home.HomeRowsFragment$onCreate$1$1.invokeSuspend(HomeRowsFragment.kt:144)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2b67878, Dispatchers.IO]

```  
***Logcat***: 
```log
09-21 20:22:53.544 V/io.ktor.client.plugins.DefaultResponseValidation(23562): Skipping default response validation for https://jellyfin.domain.com/Sessions/Capabilities?playableMediaTypes=Video&playableMediaTypes=Audio&supportedCommands=DisplayContent&supportedCommands=SetSubtitleStreamIndex&supportedCommands=SetAudioStreamIndex&supportedCommands=DisplayMessage&supportedCommands=SendString&supportedCommands=VolumeUp&supportedCommands=VolumeDown&supportedCommands=SetVolume&supportedCommands=Mute&supportedCommands=Unmute&supportedCommands=ToggleMute&supportsMediaControl=true&supportsPersistentIdentifier=true
09-21 20:22:53.546 E/SocketHandler(23562): Unable to update capabilities
09-21 20:22:53.546 E/SocketHandler(23562): org.jellyfin.sdk.api.client.exception.InvalidStatusException: Invalid HTTP status in response: 404
09-21 20:22:53.546 E/SocketHandler(23562): 	at org.jellyfin.sdk.api.ktor.KtorClient.request$suspendImpl(KtorClient.kt:132)
09-21 20:22:53.546 E/SocketHandler(23562): 	at org.jellyfin.sdk.api.ktor.KtorClient$request$1.invokeSuspend(Unknown Source:19)
09-21 20:22:53.546 E/SocketHandler(23562): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-21 20:22:53.546 E/SocketHandler(23562): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
09-21 20:22:53.546 E/SocketHandler(23562): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
09-21 20:22:53.546 E/SocketHandler(23562): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
09-21 20:22:53.546 E/SocketHandler(23562): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
09-21 20:22:53.546 E/SocketHandler(23562): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
09-21 20:22:53.546 E/SocketHandler(23562): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
09-21 20:22:53.546 E/SocketHandler(23562): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
09-21 20:22:53.547 D/NavigationRepositoryImpl(23562): Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.home.HomeFragment (Kotlin reflection is not available), arguments=Bundle[{}]) (via reset, clearHistory=true)
09-21 20:22:53.547 D/StartupActivity(23562): Opening next activity Intent { flg=0x10004000 cmp=org.jellyfin.androidtv/.ui.browsing.MainActivity }
09-21 20:22:53.547 V/io.ktor.client.plugins.HttpCallValidator(23562): Processing exception java.util.concurrent.CancellationException: Parent job is Cancelling for request https://jellyfin.domain.com/Shows/NextUp?limit=10&fields=DateCreated&imageTypeLimit=1&enableTotalRecordCount=true&disableFirstEpisode=false&enableResumable=false&enableRewatching=false
09-21 20:22:53.548 E/LeanbackChannelWorker(23562): SDK error, trying again later
09-21 20:22:53.548 E/LeanbackChannelWorker(23562): org.jellyfin.sdk.api.client.exception.InvalidStatusException: Invalid HTTP status in response: 404
09-21 20:22:53.548 E/LeanbackChannelWorker(23562): 	at org.jellyfin.sdk.api.ktor.KtorClient.request$suspendImpl(KtorClient.kt:132)
09-21 20:22:53.548 E/LeanbackChannelWorker(23562): 	at org.jellyfin.sdk.api.ktor.KtorClient$request$1.invokeSuspend(Unknown Source:19)
09-21 20:22:53.548 E/LeanbackChannelWorker(23562): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-21 20:22:53.548 E/LeanbackChannelWorker(23562): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
09-21 20:22:53.548 E/LeanbackChannelWorker(23562): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
09-21 20:22:53.548 E/LeanbackChannelWorker(23562): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
09-21 20:22:53.548 E/LeanbackChannelWorker(23562): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
09-21 20:22:53.548 E/LeanbackChannelWorker(23562): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
09-21 20:22:53.548 E/LeanbackChannelWorker(23562): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
09-21 20:22:53.548 E/LeanbackChannelWorker(23562): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
09-21 20:22:53.549 I/WM-WorkerWrapper(23562): Worker result RETRY for Work [ id=71d13548-d537-4540-b0bb-4bb6718d55fd, tags={ org.jellyfin.androidtv.integration.LeanbackChannelWorker } ]
09-21 20:22:53.555 D/ACRA    (23562): onActivityPaused class org.jellyfin.androidtv.ui.startup.StartupActivity
09-21 20:22:53.568 I/ActivityThemeExtensionsKt(23562): Applying theme DARK
09-21 20:22:53.569 D/ACRA    (23562): onActivityCreated class org.jellyfin.androidtv.ui.browsing.MainActivity
09-21 20:22:53.583 D/ACRA    (23562): onActivityStarted class org.jellyfin.androidtv.ui.browsing.MainActivity
09-21 20:22:53.584 D/ACRA    (23562): onActivityResumed class org.jellyfin.androidtv.ui.browsing.MainActivity
09-21 20:22:53.591 W/org.jellyfin.sdk.api.sockets.OkHttpSocketConnection(23562): WebSocket has failed
09-21 20:22:53.591 W/org.jellyfin.sdk.api.sockets.OkHttpSocketConnection(23562): java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
09-21 20:22:53.591 W/org.jellyfin.sdk.api.sockets.OkHttpSocketConnection(23562): 	at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess$okhttp(RealWebSocket.kt:224)
09-21 20:22:53.591 W/org.jellyfin.sdk.api.sockets.OkHttpSocketConnection(23562): 	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
09-21 20:22:53.591 W/org.jellyfin.sdk.api.sockets.OkHttpSocketConnection(23562): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
09-21 20:22:53.591 W/org.jellyfin.sdk.api.sockets.OkHttpSocketConnection(23562): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-21 20:22:53.591 W/org.jellyfin.sdk.api.sockets.OkHttpSocketConnection(23562): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-21 20:22:53.591 W/org.jellyfin.sdk.api.sockets.OkHttpSocketConnection(23562): 	at java.lang.Thread.run(Thread.java:923)
09-21 20:22:53.592 D/org.jellyfin.sdk.api.sockets.DefaultSocketApi(23562): WebSocket connection closed with 14 active subscriptions. Reconnect policy suggests waiting for 1s.
09-21 20:22:53.601 I/android_os_HwBinder(23562): HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
09-21 20:22:53.628 I/HomeRowsFragment(23562): Updating audio queue in HomeFragment (onResume)
09-21 20:22:53.633 I/HomeRowsFragment(23562): Updating audio queue in HomeFragment (onQueueStatusChanged)
09-21 20:22:53.634 D/org.jellyfin.sdk.api.sockets.DefaultSocketApi(23562): Subscription count changed to 15
09-21 20:22:53.634 D/org.jellyfin.sdk.api.sockets.DefaultSocketApi(23562): Subscription count changed to 16
09-21 20:22:53.637 I/android_os_HwBinder(23562): HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
09-21 20:22:53.639 I/android_os_HwBinder(23562): HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
09-21 20:22:53.684 E/libc    (23562): Access denied finding property "ro.vendor.sys.NV_ASYNC"
09-21 20:22:53.684 E/libc    (23562): Access denied finding property "ro.vendor.sys.NV_LOGFPS"
09-21 20:22:53.684 E/libc    (23562): Access denied finding property "ro.vendor.sys.NV_PROCESS_NAME"
09-21 20:22:53.684 E/libc    (23562): Access denied finding property "ro.vendor.sys.NV_FPSDYNAMIC"
09-21 20:22:53.715 I/org.jellyfin.sdk.api.ktor.KtorClient(23562): GET https://jellyfin.domain.com/UserViews?includeHidden=false
09-21 20:22:53.716 V/io.ktor.client.plugins.HttpPlainText(23562): Adding Accept-Charset=UTF-8 to https://jellyfin.domain.com/UserViews?includeHidden=false
09-21 20:22:53.721 I/org.jellyfin.sdk.api.ktor.KtorClient(23562): GET https://jellyfin.domain.com/UserItems/Resume?limit=50&fields=PrimaryImageAspectRatio&fields=Overview&fields=ItemCounts&fields=DisplayPreferencesId&fields=ChildCount&mediaTypes=Video&imageTypeLimit=1&excludeItemTypes=AudioBook&enableTotalRecordCount=false&enableImages=true&excludeActiveSessions=false
09-21 20:22:53.722 V/io.ktor.client.plugins.HttpPlainText(23562): Adding Accept-Charset=UTF-8 to https://jellyfin.domain.com/UserItems/Resume?limit=50&fields=PrimaryImageAspectRatio&fields=Overview&fields=ItemCounts&fields=DisplayPreferencesId&fields=ChildCount&mediaTypes=Video&imageTypeLimit=1&excludeItemTypes=AudioBook&enableTotalRecordCount=false&enableImages=true&excludeActiveSessions=false
09-21 20:22:53.729 I/org.jellyfin.sdk.api.ktor.KtorClient(23562): GET https://jellyfin.domain.com/UserItems/Resume?limit=50&fields=PrimaryImageAspectRatio&fields=Overview&fields=ItemCounts&fields=DisplayPreferencesId&fields=ChildCount&mediaTypes=Audio&imageTypeLimit=1&excludeItemTypes=AudioBook&enableTotalRecordCount=false&enableImages=true&excludeActiveSessions=false
09-21 20:22:53.731 V/io.ktor.client.plugins.HttpPlainText(23562): Adding Accept-Charset=UTF-8 to https://jellyfin.domain.com/UserItems/Resume?limit=50&fields=PrimaryImageAspectRatio&fields=Overview&fields=ItemCounts&fields=DisplayPreferencesId&fields=ChildCount&mediaTypes=Audio&imageTypeLimit=1&excludeItemTypes=AudioBook&enableTotalRecordCount=false&enableImages=true&excludeActiveSessions=false
09-21 20:22:53.733 I/org.jellyfin.sdk.api.ktor.KtorClient(23562): GET https://jellyfin.domain.com/Shows/NextUp?limit=50&fields=PrimaryImageAspectRatio&fields=Overview&fields=ChildCount&imageTypeLimit=1&enableTotalRecordCount=true&disableFirstEpisode=false&enableResumable=false&enableRewatching=false
09-21 20:22:53.735 V/io.ktor.client.plugins.HttpPlainText(23562): Adding Accept-Charset=UTF-8 to https://jellyfin.domain.com/Shows/NextUp?limit=50&fields=PrimaryImageAspectRatio&fields=Overview&fields=ChildCount&imageTypeLimit=1&enableTotalRecordCount=true&disableFirstEpisode=false&enableResumable=false&enableRewatching=false
09-21 20:22:53.736 I/org.jellyfin.sdk.api.ktor.KtorClient(23562): GET https://jellyfin.domain.com/UserViews?includeHidden=false
09-21 20:22:53.737 V/io.ktor.client.plugins.HttpPlainText(23562): Adding Accept-Charset=UTF-8 to https://jellyfin.domain.com/UserViews?includeHidden=false
09-21 20:22:53.777 I/lyfin.androidt(23562): Background concurrent copying GC freed 35776(1976KB) AllocSpace objects, 4(80KB) LOS objects, 49% free, 5936KB/11MB, paused 102us total 106.945ms
09-21 20:22:53.781 V/io.ktor.client.plugins.HttpCallValidator(23562): Validating response for request https://jellyfin.domain.com/UserViews?includeHidden=false
09-21 20:22:53.782 V/io.ktor.client.plugins.DefaultResponseValidation(23562): Skipping default response validation for https://jellyfin.domain.com/UserViews?includeHidden=false
09-21 20:22:53.785 E/ACRA    (23562): ACRA caught a InvalidStatusException for org.jellyfin.androidtv
09-21 20:22:53.785 E/ACRA    (23562): org.jellyfin.sdk.api.client.exception.InvalidStatusException: Invalid HTTP status in response: 404
09-21 20:22:53.785 E/ACRA    (23562): 	at org.jellyfin.sdk.api.ktor.KtorClient.request$suspendImpl(KtorClient.kt:132)
09-21 20:22:53.785 E/ACRA    (23562): 	at org.jellyfin.sdk.api.ktor.KtorClient$request$1.invokeSuspend(Unknown Source:19)
09-21 20:22:53.785 E/ACRA    (23562): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-21 20:22:53.785 E/ACRA    (23562): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
09-21 20:22:53.785 E/ACRA    (23562): 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
09-21 20:22:53.785 E/ACRA    (23562): 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
09-21 20:22:53.785 E/ACRA    (23562): 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
09-21 20:22:53.785 E/ACRA    (23562): 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
09-21 20:22:53.785 E/ACRA    (23562): 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
09-21 20:22:53.785 E/ACRA    (23562): 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
09-21 20:22:53.785 E/ACRA    (23562): 	at org.jellyfin.androidtv.ui.home.HomeFragmentLatestRow.addToRowsAdapter(HomeFragmentLatestRow.kt:28)
09-21 20:22:53.785 E/ACRA    (23562): 	at org.jellyfin.androidtv.ui.home.HomeRowsFragment$onCreate$1$1.invokeSuspend(HomeRowsFragment.kt:144)
09-21 20:22:53.785 E/ACRA    (23562): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-21 20:22:53.785 E/ACRA    (23562): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
09-21 20:22:53.785 E/ACRA    (23562): 	at android.os.Handler.handleCallback(Handler.java:938)
09-21 20:22:53.785 E/ACRA    (23562): 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-21 20:22:53.785 E/ACRA    (23562): 	at android.os.Looper.loop(Looper.java:223)
09-21 20:22:53.785 E/ACRA    (23562): 	at android.app.ActivityThread.main(ActivityThread.java:7668)
09-21 20:22:53.785 E/ACRA    (23562): 	at java.lang.reflect.Method.invoke(Native Method)
09-21 20:22:53.785 E/ACRA    (23562): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-21 20:22:53.785 E/ACRA    (23562): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
09-21 20:22:53.785 E/ACRA    (23562): 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2b67878, Dispatchers.IO]
09-21 20:22:53.785 D/ACRA    (23562): Building report
09-21 20:22:53.785 D/ACRA    (23562): Starting collectors with priority FIRST
09-21 20:22:53.786 D/ACRA    (23562): Calling collector org.acra.collector.DropBoxCollector
09-21 20:22:53.786 D/ACRA    (23562): Calling collector org.acra.collector.LogCatCollector
09-21 20:22:53.786 D/ACRA    (23562): Collector org.acra.collector.DropBoxCollector completed
09-21 20:22:53.787 D/ACRA    (23562): Calling collector org.acra.collector.StacktraceCollector
09-21 20:22:53.788 D/ACRA    (23562): Collector org.acra.collector.StacktraceCollector completed
09-21 20:22:53.794 D/ACRA    (23562): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.17.5` (`170599`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"darcy","BOOTLOADER":"32.00.2019.50-t210-69ebfcbe","BRAND":"NVIDIA","CPU_ABI":"arm64-v8a","CPU_ABI2":"","DEVICE":"mdarcy","DISPLAY":"RQ1A.210105.003.7825230_3167.5736","FINGERPRINT":"NVIDIA\/mdarcy\/mdarcy:11\/RQ1A.210105.003\/7825230_3167.5736:user\/release-keys","HARDWARE":"darcy","HOST":"mobile-u64-5308-d7000","ID":"RQ1A.210105.003","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"NVIDIA","MODEL":"SHIELD Android TV","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"mdarcy","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":["arm64-v8a"],"SUPPORTED_ABIS":["arm64-v8a","armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1665975826000,"TYPE":"user","UNKNOWN":"unknown","USER":"NVIDIA","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"7825230_3167.5736","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"11","RELEASE_OR_CODENAME":"11","SDK":"30","SDK_INT":30,"SECURITY_PATCH":"2022-04-05"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":170599,"VERSION_NAME":"0.17.5"}
```  

### Device information

***Android version***: `11`  
***Device brand***: `NVIDIA`  
***Device product***: `mdarcy`  
***Device model***: `SHIELD Android TV`  

### Crash information

***Start time***: `2024-09-21T20:16:26.343+02:00`  
***Crash time***: `2024-09-21T20:22:53.830+02:00`  

### Application version

0.17.5

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro

### Android version

9.1.1(33.2.0.157)

### Jellyfin server version

10.9.11

**Comment by Sulframus** [comment]
Also grabbed debug info from android itself, hoping this can help
[crashlog.txt](https://github.com/user-attachments/files/17089451/crashlog.txt)

**Comment by nielsvanvelzen** [comment]
The app crashes because the server is returning invalid data when loading the home screen. Try clearing all app data from the system settings and then sign in again.

**Comment by Sulframus** [comment]
> The app crashes because the server is returning invalid data when loading the home screen. Try clearing all app data from the system settings and then sign in again.

I've even tried clearing data, reinstalling application and even factory resetting Shield, but the issue still remains.

**Comment by nielsvanvelzen** [comment]
Are you connecting directly to the server or using some reverse proxy / vpn?

**Comment by Sulframus** [comment]
Tested with both RP and direct connection over IP:PORT. No difference in results. I've tested also with another clean instance of JF server, which has worked, so the issue seems to be specific to AndroidTV JF + my existing JF server

**Comment by nielsvanvelzen** [comment]
Does the crash also occur when you try a different Jellyfin user?

**Comment by Sulframus** [comment]
Yes, it also happened when I've created a local test account as well.

**Comment by nielsvanvelzen** [comment]
Can you share server logs when reproducing the issue?

**Comment by Sulframus** [comment]
Something was wrong with my Jellyfin metadata. After migrating it using a different method to a new environment, the AndroidTV client no longer crashes. I still have the old server, if you'd like to look into it or it can be just closed off.
