### ISSUE TITLE
Cast to FireTV only once

### ISSUE THREAD

**Issue by millallo** [jellyfin/jellyfin-androidtv#4050]
### Describe the bug

1. power on or reboot Firetv
2. open jellyfin app in firetv
3. sleep 10s
4. open jellyfin web or mobile and you can cast to firetv
5. exit firetv app, web or mobile (end good phase)
6. sleep 5m or 1d or 1w...
6. open jellyfin app in firetv (same steps from 2...)
7. sleep 10s or 1m...
8. open jellyfin web or mobile and you CAN'T cast to firetv, it's not visible.

### Application version

>0.16

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon Fire Stick 2020 (3rd gen)

### Android version

latest official, no custom

### Jellyfin server version

>10.7.0

**Comment by nielsvanvelzen** [comment]
You're using old, unsupported, versions of both the app and server. Please update both to the latest and see if that fixes your issue.

**Comment by millallo** [comment]
Sorry for misunderstanding,
I'm using server 10.9.11, the problem exists since version 10.7.0 and using app 0.17.6 but the problem exists since version 0.16...

**Comment by BotBlake** [comment]
@millallo 
Does the issue persist on the latest Version of both Server+Client?
- Server `10.10.3`
- Android TV `0.18.3`

**Comment by millallo** [comment]
I'm waiting for version 0.18.3 to become available on amazon store, in the meantime casting with 0.18.2 and server 10.10.3 doesn't work. The firetv device is not shown in the list of devices to cast, also after rebooting device and server.

**Comment by nielsvanvelzen** [comment]
Please make sure to have the app open when trying to cast. Additionally, verify if websockets are correctly configured when using a reverse proxy.

**Comment by millallo** [comment]
Thanks Niels,
I've looked into the issue further and I think I've found a way to reproduce the problem in 0.18.x:
1. Reboot Firetv
2. open jellyfin app in firetv (authenticated as User1)
4. open jellyfin web or mobile authenticated as Admin 
5. casting from Admin (mobile) a movie of Library which User1 (firetv) can see, works fine.
7. casting from Admin (mobile) a movie of another Library which User1 (firetv) CANT see, app CRASHES. (Before 0.18 Admin can cast fine)
8. reopen the app, but firetv is no longer present in the cast list.

**Comment by nielsvanvelzen** [comment]
If the app crashes it should've posted a crashlog to your server. Please share that document.

**Comment by millallo** [comment]
see below
[upload_org.jellyfin.androidtv_0.18.2_20241231083355_eedbfc11d66244e88741c4e7134454bc.log](https://github.com/user-attachments/files/18281348/upload_org.jellyfin.androidtv_0.18.2_20241231083355_eedbfc11d66244e88741c4e7134454bc.log)

**Comment by millallo** [comment]
also 0.18.4:
[upload_org.jellyfin.androidtv_0.18.4_20250206181005_9cc9dc23db27487ba7b4e8f846a348a6.log](https://github.com/user-attachments/files/18702172/upload_org.jellyfin.androidtv_0.18.4_20250206181005_9cc9dc23db27487ba7b4e8f846a348a6.log)

**Comment by BotBlake** [comment]
@millallo FYI, the crash logs are written in Markdown, therefore you can just paste them into the Comment directly 👍 

Thank you for providing crash logs though!
Kind regards

**Comment by BotBlake** [comment]
Sorry to ask again, but does the issue persist on the latest Version of both Server+Client?
- Server 10.10.7
- Android TV 0.18.7

Please add as much info about the used devices/ platforms/ network config so that its easier to understand/ reproduce the issue. Also sorry for the wait time.

**Comment by millallo** [comment]
Same behavior:

---
client: Jellyfin for Android TV
client_version: 0.18.7
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***:
```log
org.jellyfin.sdk.api.client.exception.InvalidStatusException: Invalid HTTP status in response: 404
	at org.jellyfin.sdk.api.ktor.KtorClient.request(KtorClient.kt:146)
	at org.jellyfin.sdk.api.ktor.KtorClient$request$1.invokeSuspend(Unknown Source:19)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:65)
	at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:343)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:146)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:11)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:70)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:6775)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@23f3acc, Dispatchers.Main.immediate]

```
***Logcat***:
```log
04-11 19:00:59.201 I/lyfin.androidt( 4708):   at java.lang.Object coil3.intercept.EngineInterceptor.fetch(coil3.ComponentRegistry, coil3.request.ImageRequest, java.lang.Object, coil3.request.Options, coil3.EventListener, kotlin.coroutines.Continuation) (EngineInterceptor.kt:169)
04-11 19:00:59.201 I/lyfin.androidt( 4708):   at java.lang.Object coil3.intercept.EngineInterceptor.execute(coil3.request.ImageRequest, java.lang.Object, coil3.request.Options, coil3.EventListener, kotlin.coroutines.Continuation) (EngineInterceptor.kt:126)
04-11 19:00:59.201 I/lyfin.androidt( 4708):   at java.lang.Object coil3.intercept.EngineInterceptor.access$execute(coil3.intercept.EngineInterceptor, coil3.request.ImageRequest, java.lang.Object, coil3.request.Options, coil3.EventListener, kotlin.coroutines.Continuation) (EngineInterceptor.kt:43)
04-11 19:00:59.201 I/lyfin.androidt( 4708):   at java.lang.Object coil3.intercept.EngineInterceptor$intercept$2.invokeSuspend(java.lang.Object) (EngineInterceptor.kt:77)
04-11 19:00:59.201 I/lyfin.androidt( 4708):   at void kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(java.lang.Object) (ContinuationImpl.kt:33)
04-11 19:00:59.201 I/lyfin.androidt( 4708):   at void kotlinx.coroutines.DispatchedTask.run() (DispatchedTask.kt:100)
04-11 19:00:59.201 I/lyfin.androidt( 4708):   at void kotlinx.coroutines.internal.LimitedDispatcher$Worker.run() (LimitedDispatcher.kt:113)
04-11 19:00:59.201 I/lyfin.androidt( 4708):   at void kotlinx.coroutines.scheduling.TaskImpl.run() (Tasks.kt:89)
04-11 19:00:59.201 I/lyfin.androidt( 4708):   at void kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(kotlinx.coroutines.scheduling.Task) (CoroutineScheduler.kt:586)
04-11 19:00:59.201 I/lyfin.androidt( 4708):   at void kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(kotlinx.coroutines.scheduling.Task) (CoroutineScheduler.kt:820)
04-11 19:00:59.201 I/lyfin.androidt( 4708):   at void kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker() (CoroutineScheduler.kt:717)
04-11 19:00:59.201 I/lyfin.androidt( 4708):   at void kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run() (CoroutineScheduler.kt:704)
04-11 19:00:59.201 I/lyfin.androidt( 4708):
04-11 19:00:59.201 I/lyfin.androidt( 4708): Rejecting re-init on previously-failed class java.lang.Class<kotlinx.coroutines.internal.ClassValueCtorCache$cache$1>: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/ClassValue;
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at boolean org.acra.util.BundleKt$$ExternalSyntheticApiModelOutline0.m(java.nio.file.attribute.BasicFileAttributes) (D8$$SyntheticClass:0)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at okio.FileMetadata okio.NioSystemFileSystem.metadataOrNull(java.nio.file.Path) (NioSystemFileSystem.kt:51)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at okio.FileMetadata okio.NioSystemFileSystem.metadataOrNull(okio.Path) (NioSystemFileSystem.kt:35)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at okio.FileMetadata okio.ForwardingFileSystem.metadataOrNull(okio.Path) (ForwardingFileSystem.kt:159)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at boolean okio.internal.-FileSystem.commonExists(okio.FileSystem, okio.Path) (FileSystem.kt:41)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at boolean okio.FileSystem.exists(okio.Path) (FileSystem.kt:39)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at void coil3.disk.DiskLruCache.initialize() (DiskLruCache.kt:184)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at coil3.disk.DiskLruCache$Snapshot coil3.disk.DiskLruCache.get(java.lang.String) (DiskLruCache.kt:368)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at coil3.disk.DiskCache$Snapshot coil3.disk.RealDiskCache.openSnapshot(java.lang.String) (RealDiskCache.kt:30)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at coil3.disk.DiskCache$Snapshot coil3.network.NetworkFetcher.readFromDiskCache() (NetworkFetcher.kt:120)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at java.lang.Object coil3.network.NetworkFetcher.fetch(kotlin.coroutines.Continuation) (NetworkFetcher.kt:42)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at java.lang.Object coil3.intercept.EngineInterceptor.fetch(coil3.ComponentRegistry, coil3.request.ImageRequest, java.lang.Object, coil3.request.Options, coil3.EventListener, kotlin.coroutines.Continuation) (EngineInterceptor.kt:169)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at java.lang.Object coil3.intercept.EngineInterceptor.execute(coil3.request.ImageRequest, java.lang.Object, coil3.request.Options, coil3.EventListener, kotlin.coroutines.Continuation) (EngineInterceptor.kt:126)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at java.lang.Object coil3.intercept.EngineInterceptor.access$execute(coil3.intercept.EngineInterceptor, coil3.request.ImageRequest, java.lang.Object, coil3.request.Options, coil3.EventListener, kotlin.coroutines.Continuation) (EngineInterceptor.kt:43)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at java.lang.Object coil3.intercept.EngineInterceptor$intercept$2.invokeSuspend(java.lang.Object) (EngineInterceptor.kt:77)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at void kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(java.lang.Object) (ContinuationImpl.kt:33)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at void kotlinx.coroutines.DispatchedTask.run() (DispatchedTask.kt:100)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at void kotlinx.coroutines.internal.LimitedDispatcher$Worker.run() (LimitedDispatcher.kt:113)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at void kotlinx.coroutines.scheduling.TaskImpl.run() (Tasks.kt:89)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at void kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(kotlinx.coroutines.scheduling.Task) (CoroutineScheduler.kt:586)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at void kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(kotlinx.coroutines.scheduling.Task) (CoroutineScheduler.kt:820)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at void kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker() (CoroutineScheduler.kt:717)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at void kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run() (CoroutineScheduler.kt:704)
04-11 19:00:59.202 I/lyfin.androidt( 4708): Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.ClassValue" on path: DexPathList[[zip file "/data/app/org.jellyfin.androidtv-wsBznBwTC1IrUxEbRe5M6g==/base.apk"],nativeLibraryDirectories=[/data/app/org.jellyfin.androidtv-wsBznBwTC1IrUxEbRe5M6g==/lib/arm, /data/app/org.jellyfin.androidtv-wsBznBwTC1IrUxEbRe5M6g==/base.apk!/lib/armeabi-v7a, /system/lib]]
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at boolean org.acra.util.BundleKt$$ExternalSyntheticApiModelOutline0.m(java.nio.file.attribute.BasicFileAttributes) (D8$$SyntheticClass:0)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at okio.FileMetadata okio.NioSystemFileSystem.metadataOrNull(java.nio.file.Path) (NioSystemFileSystem.kt:51)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at okio.FileMetadata okio.NioSystemFileSystem.metadataOrNull(okio.Path) (NioSystemFileSystem.kt:35)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at okio.FileMetadata okio.ForwardingFileSystem.metadataOrNull(okio.Path) (ForwardingFileSystem.kt:159)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at boolean okio.internal.-FileSystem.commonExists(okio.FileSystem, okio.Path) (FileSystem.kt:41)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at boolean okio.FileSystem.exists(okio.Path) (FileSystem.kt:39)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at void coil3.disk.DiskLruCache.initialize() (DiskLruCache.kt:184)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at coil3.disk.DiskLruCache$Snapshot coil3.disk.DiskLruCache.get(java.lang.String) (DiskLruCache.kt:368)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at coil3.disk.DiskCache$Snapshot coil3.disk.RealDiskCache.openSnapshot(java.lang.String) (RealDiskCache.kt:30)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at coil3.disk.DiskCache$Snapshot coil3.network.NetworkFetcher.readFromDiskCache() (NetworkFetcher.kt:120)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at java.lang.Object coil3.network.NetworkFetcher.fetch(kotlin.coroutines.Continuation) (NetworkFetcher.kt:42)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at java.lang.Object coil3.intercept.EngineInterceptor.fetch(coil3.ComponentRegistry, coil3.request.ImageRequest, java.lang.Object, coil3.request.Options, coil3.EventListener, kotlin.coroutines.Continuation) (EngineInterceptor.kt:169)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at java.lang.Object coil3.intercept.EngineInterceptor.execute(coil3.request.ImageRequest, java.lang.Object, coil3.request.Options, coil3.EventListener, kotlin.coroutines.Continuation) (EngineInterceptor.kt:126)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at java.lang.Object coil3.intercept.EngineInterceptor.access$execute(coil3.intercept.EngineInterceptor, coil3.request.ImageRequest, java.lang.Object, coil3.request.Options, coil3.EventListener, kotlin.coroutines.Continuation) (EngineInterceptor.kt:43)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at java.lang.Object coil3.intercept.EngineInterceptor$intercept$2.invokeSuspend(java.lang.Object) (EngineInterceptor.kt:77)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at void kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(java.lang.Object) (ContinuationImpl.kt:33)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at void kotlinx.coroutines.DispatchedTask.run() (DispatchedTask.kt:100)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at void kotlinx.coroutines.internal.LimitedDispatcher$Worker.run() (LimitedDispatcher.kt:113)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at void kotlinx.coroutines.scheduling.TaskImpl.run() (Tasks.kt:89)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at void kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(kotlinx.coroutines.scheduling.Task) (CoroutineScheduler.kt:586)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at void kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(kotlinx.coroutines.scheduling.Task) (CoroutineScheduler.kt:820)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at void kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker() (CoroutineScheduler.kt:717)
04-11 19:00:59.202 I/lyfin.androidt( 4708):   at void kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run() (CoroutineScheduler.kt:704)
04-11 19:00:59.202 I/lyfin.androidt( 4708):
04-11 19:00:59.257 I/org.jellyfin.sdk.api.ktor.KtorClient( 4708): GET http://192.168.1.2:8096/UserViews?includeHidden=false
04-11 19:00:59.304 I/org.jellyfin.sdk.api.ktor.KtorClient( 4708): GET http://192.168.1.2:8096/UserItems/Resume?limit=50&fields=PrimaryImageAspectRatio&fields=Overview&fields=ItemCounts&fields=DisplayPreferencesId&fields=ChildCount&mediaTypes=Video&imageTypeLimit=1&excludeItemTypes=AudioBook&enableTotalRecordCount=false&enableImages=true&excludeActiveSessions=false
04-11 19:00:59.337 I/org.jellyfin.sdk.api.ktor.KtorClient( 4708): GET http://192.168.1.2:8096/Shows/NextUp?limit=50&fields=PrimaryImageAspectRatio&fields=Overview&fields=ChildCount&imageTypeLimit=1&enableTotalRecordCount=true&disableFirstEpisode=false&enableResumable=false&enableRewatching=false
04-11 19:00:59.370 I/org.jellyfin.sdk.api.ktor.KtorClient( 4708): GET http://192.168.1.2:8096/Items/Latest?parentId=ef4aec73-663e-3544-5b0e-e9c6bcfdc0b1&fields=PrimaryImageAspectRatio&fields=Overview&fields=ChildCount&fields=SeriesPrimaryImage&imageTypeLimit=1&limit=50&groupItems=true
04-11 19:00:59.388 I/lyfin.androidt( 4708): Background concurrent copying GC freed 64314(4MB) AllocSpace objects, 8(348KB) LOS objects, 50% free, 5MB/10MB, paused 430us total 177.701ms
04-11 19:00:59.402 I/org.jellyfin.sdk.api.ktor.KtorClient( 4708): GET http://192.168.1.2:8096/Items/Latest?parentId=5b2dc596-21f0-2c0a-84aa-5240d8869d1e&fields=PrimaryImageAspectRatio&fields=Overview&fields=ChildCount&fields=SeriesPrimaryImage&imageTypeLimit=1&limit=50&groupItems=true
04-11 19:00:59.431 I/org.jellyfin.sdk.api.ktor.KtorClient( 4708): GET http://192.168.1.2:8096/Items/Latest?parentId=1b8414a4-5d24-5177-d1c1-34bb724b1d92&fields=PrimaryImageAspectRatio&fields=Overview&fields=ChildCount&fields=SeriesPrimaryImage&imageTypeLimit=1&limit=50&groupItems=true
04-11 19:01:00.072 I/ConfigStore( 4708): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::vsyncEventPhaseOffsetNs retrieved: 1000000 (default)
04-11 19:01:00.072 I/ConfigStore( 4708): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::vsyncSfEventPhaseOffsetNs retrieved: 1000000 (default)
04-11 19:01:01.056 I/lyfin.androidt( 4708): Background concurrent copying GC freed 81749(3MB) AllocSpace objects, 34(712KB) LOS objects, 46% free, 7MB/13MB, paused 505us total 187.258ms
04-11 19:01:01.274 I/WM-WorkerWrapper( 4708): Worker result SUCCESS for Work [ id=eccb1a63-438d-4f75-8287-425cd237bc6a, tags={ org.jellyfin.androidtv.integration.LeanbackChannelWorker } ]
04-11 19:04:58.474 I/org.jellyfin.sdk.api.ktor.KtorClient( 4708): GET http://192.168.1.2:8096/Items/ed91fd72-9a13-733b-92ba-886fdd135ebe
04-11 19:04:58.655 E/ACRA    ( 4708): ACRA caught a InvalidStatusException for org.jellyfin.androidtv
04-11 19:04:58.655 E/ACRA    ( 4708): org.jellyfin.sdk.api.client.exception.InvalidStatusException: Invalid HTTP status in response: 404
04-11 19:04:58.655 E/ACRA    ( 4708): 	at org.jellyfin.sdk.api.ktor.KtorClient.request(KtorClient.kt:146)
04-11 19:04:58.655 E/ACRA    ( 4708): 	at org.jellyfin.sdk.api.ktor.KtorClient$request$1.invokeSuspend(Unknown Source:19)
04-11 19:04:58.655 E/ACRA    ( 4708): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-11 19:04:58.655 E/ACRA    ( 4708): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
04-11 19:04:58.655 E/ACRA    ( 4708): 	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:65)
04-11 19:04:58.655 E/ACRA    ( 4708): 	at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:343)
04-11 19:04:58.655 E/ACRA    ( 4708): 	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:146)
04-11 19:04:58.655 E/ACRA    ( 4708): 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
04-11 19:04:58.655 E/ACRA    ( 4708): 	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:11)
04-11 19:04:58.655 E/ACRA    ( 4708): 	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:70)
04-11 19:04:58.655 E/ACRA    ( 4708): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
04-11 19:04:58.655 E/ACRA    ( 4708): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
04-11 19:04:58.655 E/ACRA    ( 4708): 	at android.os.Handler.handleCallback(Handler.java:873)
04-11 19:04:58.655 E/ACRA    ( 4708): 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-11 19:04:58.655 E/ACRA    ( 4708): 	at android.os.Looper.loop(Looper.java:211)
04-11 19:04:58.655 E/ACRA    ( 4708): 	at android.app.ActivityThread.main(ActivityThread.java:6775)
04-11 19:04:58.655 E/ACRA    ( 4708): 	at java.lang.reflect.Method.invoke(Native Method)
04-11 19:04:58.655 E/ACRA    ( 4708): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-11 19:04:58.655 E/ACRA    ( 4708): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-11 19:04:58.655 E/ACRA    ( 4708): 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@23f3acc, Dispatchers.Main.immediate]

```

### App information

***App version***: `0.18.7` (`180799`)
***Package name***: `org.jellyfin.androidtv`
***Build***:
```json
{"BOARD":"sheldonp","BOOTLOADER":"unknown","BRAND":"Amazon","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"sheldonp","DISPLAY":"PS7690.4719N","FINGERPRINT":"Amazon\/sheldonp\/sheldonp:9\/PS7690.4719N\/0032381234944:user\/amz-p,release-keys","HARDWARE":"mt8695","HOST":"i3-ri-14-use1a-b-16-04-fos-172","ID":"PS7690.4719N","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Amazon","MODEL":"AFTSSS","PERMISSIONS_REVIEW_REQUIRED":false,"PRODUCT":"sheldonp","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"amz-p,release-keys","TIME":1743660790000,"TYPE":"user","UNKNOWN":"unknown","USER":"build","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"PPR1.180610.009","CODENAME":"REL","FIRST_SDK_INT":28,"INCREMENTAL":"0032381235076","PREVIEW_SDK_INT":0,"RELEASE":"9","RESOURCES_SDK_INT":28,"SDK":"28","SDK_INT":28,"SECURITY_PATCH":"2025-01-01"}}
```
***Build config***:
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":180799,"VERSION_NAME":"0.18.7"}
```

### Device information

***Android version***: `9`
***Device brand***: `Amazon`
***Device product***: `sheldonp`
***Device model***: `AFTSSS`

### Crash information

***Start time***: `2025-04-11T19:00:55.778+02:00`
***Crash time***: `2025-04-11T19:04:58.745+02:00`
