### ISSUE TITLE
x265 10bit Remote Stream

### ISSUE THREAD

**Issue by iwatch-x** [jellyfin/jellyfin-androidtv#410]
### **Hi,**

**i have troubleshooting when an user outside the network plays a movie direct stream the movie stops every 6 min , in my logs i got this:**

> [2020-03-29 18:50:05.170 +00:00] [WRN] HTTP Response 204 to "MY_IP". Time (slow): 0:00:01.0968984. "http://MY_URL/Sessions/Playing/Progress"
> [2020-03-29 18:51:41.154 +00:00] [WRN] HTTP Response 204 to "MY_IP". Time (slow): 0:00:01.0564404. "http://MY_URL/Sessions/Playing/Progress"
> [2020-03-29 18:52:26.773 +00:00] [ERR] Could not find handler for "/Sessions/Playing/Progress"
> [2020-03-29 18:52:26.775 +00:00] [ERR] Error processing request: "Unable to find the specified file."
> [2020-03-29 18:53:10.817 +00:00] [WRN] HTTP Response 204 to "MY_IP". Time (slow): 0:00:00.6328439. "http://MY_URL/Sessions/Playing/Progress"
> [2020-03-29 18:54:13.686 +00:00] [INF] Playback stopped reported by app "AndroidTV" "0.11.2" playing "Night School". Stopped at "6691878" ms
> 

**The movie itself has bitrate 4612 kbps and it's a x265 1080p 10bit file. my upload stream is 18.4 Mbps so don't think this can be the problem** 
![docker](https://user-images.githubusercontent.com/62252807/77909439-a278c380-728d-11ea-9d2d-2ba5693305be.jpg)
![chapter](https://user-images.githubusercontent.com/62252807/77909610-f4b9e480-728d-11ea-9f92-395164c34bac.jpg)

 - Jellyfin Version: **10.5.0:nightly**
 - Playback: **Direct Play** 
 - Installed Plugins: **Trakt, TMDb Box Sets, MusicBrainz, AudioDB**
 - Reverse Proxy: **Traefik**
 - Base URL: **none**
 - Networking: **Host, Bridge**
 - Storage: **Local**
 - Client: **Amazon Fire Stick 4k, Android Version 0.11.2**

**Comment by rowbawts** [comment]
I’ve been experiencing a similar issue with even x264 streams where it plays fine at first then starts pausing then even fully locks up and crashes the app or even once made my tv reboot. Same logs but I’m using nginx for my reverse proxy.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Artiume** [comment]
Can you try using libVLC while bypassing nginx?

**Comment by MrLemur** [comment]
Think I am facing this issue as well. Debug on the app doesn't help as the debugger detaches. Here is the relevant logcat. I have the same setup as the OP, but error shows on both release and latest dev builds.

```
2020-06-01 19:15:06.068 32127-32127/org.jellyfin.androidtv.debug E/ACRA: ACRA caught a RuntimeException for org.jellyfin.androidtv.debug
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.jellyfin.androidtv.debug/org.jellyfin.androidtv.details.FullDetailsActivity}: android.view.InflateException: Binary XML file line #16: Binary XML file line #16: Error inflating class org.jellyfin.androidtv.ui.ClockUserView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2681)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2748)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6188)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)
     Caused by: android.view.InflateException: Binary XML file line #16: Binary XML file line #16: Error inflating class org.jellyfin.androidtv.ui.ClockUserView
     Caused by: android.view.InflateException: Binary XML file line #16: Error inflating class org.jellyfin.androidtv.ui.ClockUserView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:419)
        at android.app.Activity.setContentView(Activity.java:2420)
        at org.jellyfin.androidtv.details.FullDetailsActivity.onCreate(FullDetailsActivity.java:136)
        at android.app.Activity.performCreate(Activity.java:6689)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2634)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2748)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6188)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jellyfin.apiclient.model.dto.UserDto.getName()' on a null object reference
        at org.jellyfin.androidtv.ui.ClockUserView.init(ClockUserView.java:34)
        at org.jellyfin.androidtv.ui.ClockUserView.<init>(ClockUserView.java:25)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:419) 
        at android.app.Activity.setContentView(Activity.java:2420) 
        at org.jellyfin.androidtv.details.FullDetailsActivity.onCreate(FullDetailsActivity.java:136) 
        at android.app.Activity.performCreate(Activity.java:6689) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2634) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2748) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6188) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801) 
2020-06-01 19:15:06.113 1189-23583/? I/SPCH-SCL_Http2Message: status: 204
2020-06-01 19:15:06.115 1189-23583/? I/SPCH-SCL_Http2Message: header: DefaultHttp2Headers[:status: 204, x-amzn-requestid: 2dcfae3f-451f-4ab8-ad9e-e6afae9d8544, x-amzn-requestid: 0aa8b6fffe1f923c-0000dd11-005350a5-57780be17f943639-9c8ea190-69, access-control-allow-origin: *]
2020-06-01 19:15:06.116 1189-23583/? D/SPCH-SCL_Http2Client-33: removing message with stream id: 69
2020-06-01 19:15:06.118 1189-1189/? I/CSM-ProactiveReporter: Got result SUCCESS
2020-06-01 19:15:06.118 1189-1644/? I/SPCH-SIM_SimStateMachine: Got EndEventResponseEvent in ReadyState
2020-06-01 19:15:06.118 1189-1644/? I/SPCH-SIM_SIMState: Ignoring EndEventResponseEvent
2020-06-01 19:15:06.118 1189-32144/? I/CSM-ProactiveReporter: Uninterruptibly waiting for 400
2020-06-01 19:15:06.132 257-257/? E/SELinux: avc:  denied  { find } for service=meminfo pid=32167 uid=10184 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:meminfo_service:s0 tclass=service_manager permissive=0
2020-06-01 19:15:06.142 606-2053/? W/ActivityManager: Duplicate finish request for ActivityRecord{f2aeb36 u0 org.jellyfin.androidtv.debug/org.jellyfin.androidtv.details.FullDetailsActivity t554 f}
2020-06-01 19:15:06.142 32127-32127/org.jellyfin.androidtv.debug I/Process: Sending signal. PID: 32127 SIG: 9
2020-06-01 19:15:06.200 606-2053/? I/ActivityManager: Process org.jellyfin.androidtv.debug (pid 32127) has died
```

**Comment by grravity** [comment]
I have issues as well playing 10bit streams locally on my Android/TV devices. Not sure if related. They play fine using the Jellyfin stream link to MPV and browser.

Jellyfin 10.5.5
Reverse Proxy Caddyv2
OS Windows 10 Home

**Comment by MrLemur** [comment]
This might have been fixed with the newer versions of libvlc, but I have not had a chance to build the app in a while.
