### ISSUE TITLE
Jellyfin crashes after movie/show

### ISSUE THREAD

**Issue by schrottsimon** [jellyfin/jellyfin-androidtv#4113]
### Describe the bug

After finishing a movie/show the application crashes see logs

### Logs

---
client: Jellyfin for Android TV
client_version: 0.17.8
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
org.jellyfin.sdk.api.client.exception.TimeoutException: HTTP host unreachable
	at org.jellyfin.sdk.api.ktor.KtorClient.request$suspendImpl(KtorClient.kt:137)
	at org.jellyfin.sdk.api.ktor.KtorClient$request$1.invokeSuspend(Unknown Source:19)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3145fe0, Dispatchers.Main.immediate]
Caused by: java.net.UnknownHostException: Unable to resolve host "xxxxxxxxxxxx": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:169)
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:131)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:73)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:200)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 23 more

```  
***Logcat***: 
```log
10-25 22:36:36.481 D/jellyfin-apiclient( 6716): Adding request to queue: 

10-25 22:36:36.563 I/jellyfin-apiclient( 6716): Response received from: 

10-25 22:36:39.482 D/jellyfin-apiclient( 6716): Adding request to queue: 

10-25 22:36:39.557 I/jellyfin-apiclient( 6716): Response received from: 

10-25 22:36:42.483 D/jellyfin-apiclient( 6716): Adding request to queue: 

10-25 22:36:42.564 I/jellyfin-apiclient( 6716): Response received from: 

10-25 22:36:45.483 D/jellyfin-apiclient( 6716): Adding request to queue: 

10-25 22:36:45.562 I/jellyfin-apiclient( 6716): Response received from: 

10-25 22:36:48.484 D/jellyfin-apiclient( 6716): Adding request to queue: 

10-25 22:36:48.558 I/jellyfin-apiclient( 6716): Response received from: 

10-25 22:36:51.275 D/org.jellyfin.sdk.api.sockets.OkHttpSocketConnection( 6716): Sending (raw) message {"MessageType":"KeepAlive"}
10-25 22:36:51.311 D/org.jellyfin.sdk.api.sockets.OkHttpSocketConnection( 6716): Receiving (raw) message {"MessageId":"e05381e916514f33940c3a964bfa10a4","MessageType":"KeepAlive"}
10-25 22:36:51.485 D/jellyfin-apiclient( 6716): Adding request to queue: 

10-25 22:36:51.564 I/jellyfin-apiclient( 6716): Response received from: 

10-25 22:36:54.485 D/jellyfin-apiclient( 6716): Adding request to queue: 

10-25 22:36:54.561 I/jellyfin-apiclient( 6716): Response received from: 

10-25 22:36:57.486 D/jellyfin-apiclient( 6716): Adding request to queue: 

10-25 22:36:57.565 I/jellyfin-apiclient( 6716): Response received from: 

10-25 22:37:00.278 D/org.jellyfin.sdk.api.sockets.OkHttpSocketConnection( 6716): Receiving (raw) message {"MessageId":"d08ed909eee14bc39183e4111b581f2f","Data":{"Name":"DisplayMessage","ControllingUserId":"00000000000000000000000000000000","Arguments":{"Header":"","Text":"Credits skipped","TimeoutMs":"2000"}},"MessageType":"GeneralCommand"}
10-25 22:37:00.278 D/org.jellyfin.sdk.api.sockets.OkHttpSocketConnection( 6716): Receiving (raw) message {"MessageId":"5adc7d05d0c74ab3ba619075cdb4b86e","Data":{"Command":"Seek","SeekPositionTicks":25200000000,"ControllingUserId":"948b587d2fb14b8b9f12319dedbe1649"},"MessageType":"Playstate"}
10-25 22:37:00.285 W/ExoPlayerBackend( 6716): Trying to seek but ExoPlayer doesn't support it for the current item
10-25 22:37:00.288 I/SocketHandler$onPlayStateMessage( 6716): Received PlayStateMessage with command Seek
10-25 22:37:00.289 D/PlaybackController( 6716): Trying to seek from 2487517 to 2520000
10-25 22:37:00.289 D/PlaybackController( 6716): Container: mkv
10-25 22:37:00.290 D/VideoManager( 6716): current media item is seekable
10-25 22:37:00.290 I/VideoManager( 6716): Exo length in seek is: 2520165
10-25 22:37:00.293 D/VideoManager( 6716): Player is buffering
10-25 22:37:00.295 D/jellyfin-apiclient( 6716): Adding request to queue: 

10-25 22:37:00.382 I/jellyfin-apiclient( 6716): Response received from: 

10-25 22:37:00.533 I/PlaybackController( 6716): Play method: Direct
10-25 22:37:00.535 I/PlaybackController( 6716): Turning off subs
10-25 22:37:00.536 D/PlaybackController( 6716): Setting subtitle index to: -1
10-25 22:37:00.537 D/PlaybackController( 6716): trying to switch audio stream from 1 to 1
10-25 22:37:00.538 D/PlaybackController( 6716): skipping setting audio stream, already set to requested index 1
10-25 22:37:00.700 D/PlaybackController( 6716): On Completion fired
10-25 22:37:00.701 D/PlaybackController( 6716): stop called at 2520026
10-25 22:37:00.703 I/ReportingHelper( 6716): ReportingHelper.reportStopped called for a008dde5-71e6-fff6-140b-ce29fb8dbe94 at position 25200260000
10-25 22:37:00.703 I/jellyfin-apiclient( 6716): ReportPlaybackStopped: Item a008dde5-71e6-fff6-140b-ce29fb8dbe94, Ticks: 25200260000
10-25 22:37:00.704 D/jellyfin-apiclient( 6716): Adding request to queue: 

10-25 22:37:00.705 D/PlaybackController( 6716): Moving to next queue item. Index: 1
10-25 22:37:00.706 D/NavigationRepositoryImpl( 6716): Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.playback.nextup.NextUpFragment (Kotlin reflection is not available), arguments=Bundle[{item_id=63d46331-9c74-69ce-a70c-1be5e6ec5f45}]) (via navigate function)
10-25 22:37:00.711 D/CustomPlaybackOverlayFragment( 6716): Stopping!
10-25 22:37:00.711 D/CustomPlaybackOverlayFragment( 6716): this fragment belongs to the current session, ending it
10-25 22:37:00.712 D/PlaybackController( 6716): stop called at 2520026
10-25 22:37:00.809 D/SurfaceUtils( 6716): disconnecting from surface 0xbab1c808, reason disconnectFromSurface
10-25 22:37:00.809 D/gralloc ( 6716): unregister FBM buffer
10-25 22:37:00.810 I/chatty  ( 6716): uid=10091(org.jellyfin.androidtv) identical 18 lines
10-25 22:37:00.810 D/gralloc ( 6716): unregister FBM buffer
10-25 22:37:00.812 D/MediaCodec( 6716): mState = 0, mHaveKick = 0, L(755)
10-25 22:37:00.813 D/MtkACodecPlugin( 6716): MtkACodecPlugin destoryAPlugin
10-25 22:37:00.817 I/ExoPlayerImpl( 6716): Release d7eb405 [AndroidXMedia3/1.4.1] [BRAVIA_VH2, BRAVIA 4K VH2, Sony, 29] [media3.common, media3.session, media3.exoplayer, media3.decoder, media3.ui, media3.datasource, media3.extractor, media3.decoder.ffmpeg]
10-25 22:37:00.852 I/org.jellyfin.sdk.api.ktor.KtorClient( 6716): GET https://xxxxxxxxxx/Items/63d46331-9c74-69ce-a70c-1be5e6ec5f45
10-25 22:37:00.853 D/PlaybackController( 6716): stop called at 2520026
10-25 22:37:00.853 V/io.ktor.client.plugins.HttpPlainText( 6716): Adding Accept-Charset=UTF-8 to https://xxxxxxxxxx/Items/63d46331-9c74-69ce-a70c-1be5e6ec5f45
10-25 22:37:00.863 I/jellyfin-apiclient( 6716): Response received from: https://xxxxxxxxxx/Sessions/Playing/Stopped
10-25 22:37:00.908 V/io.ktor.client.plugins.HttpCallValidator( 6716): Processing exception java.net.UnknownHostException: Unable to resolve host "xxxxxxxxxx": No address associated with hostname for request https://xxxxxxxxxxxxxxxxxxxxxxxxxx/Items/63d46331-9c74-69ce-a70c-1be5e6ec5f45
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): HTTP host unreachable
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): java.net.UnknownHostException: Unable to resolve host "xxxxxxxxxxxxxxxxxxxxxxxxxx": No address associated with hostname
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:169)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:131)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:73)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at java.lang.Thread.run(Thread.java:919)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at libcore.io.Linux.android_getaddrinfo(Native Method)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:200)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
10-25 22:37:00.910 D/org.jellyfin.sdk.api.ktor.KtorClient( 6716): 	... 23 more
10-25 22:37:00.914 E/ACRA    ( 6716): ACRA caught a TimeoutException for org.jellyfin.androidtv
10-25 22:37:00.914 D/ACRA    ( 6716): Building report
10-25 22:37:00.915 D/ACRA    ( 6716): Starting collectors with priority FIRST
10-25 22:37:00.916 D/ACRA    ( 6716): Calling collector org.acra.collector.DropBoxCollector
10-25 22:37:00.916 D/ACRA    ( 6716): Calling collector org.acra.collector.LogCatCollector
10-25 22:37:00.916 D/ACRA    ( 6716): Calling collector org.acra.collector.StacktraceCollector
10-25 22:37:00.916 D/ACRA    ( 6716): Collector org.acra.collector.DropBoxCollector completed
10-25 22:37:00.917 D/ACRA    ( 6716): Collector org.acra.collector.StacktraceCollector completed
10-25 22:37:00.918 D/ACRA    ( 6716): Retrieving logcat output (buffer:default)...
10-25 22:37:00.928 E/libc    ( 8814): Access denied finding property "persist.vendor.system.svp.dbg.loglevel"

```  

### App information

***App version***: `0.17.8` (`170899`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"mt5895","BOOTLOADER":"unknown","BRAND":"Sony","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"BRAVIA_VH2","DISPLAY":"BRAVIA_VH2_EU-user 10 QTG3.200305.006.S376 675321 release-keys","FINGERPRINT":"Sony\/BRAVIA_VH2_EU\/BRAVIA_VH2:10\/QTG3.200305.006.S376\/675321:user\/release-keys","HARDWARE":"mt5895","HOST":"BuildHost711","ID":"QTG3.200305.006.S376","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Sony","MODEL":"BRAVIA 4K VH2","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"BRAVIA_VH2_EU","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1712834369000,"TYPE":"user","UNKNOWN":"unknown","USER":"root","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","FIRST_SDK_INT":29,"INCREMENTAL":"675321","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"10","RESOURCES_SDK_INT":29,"SDK":"29","SDK_INT":29,"SECURITY_PATCH":"2024-03-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":170899,"VERSION_NAME":"0.17.8"}
```  

### Device information

***Android version***: `10`  
***Device brand***: `Sony`  
***Device product***: `BRAVIA_VH2_EU`  
***Device model***: `BRAVIA 4K VH2`  

### Crash information

***Start time***: `2024-10-25T21:45:45.546+02:00`  
***Crash time***: `2024-10-25T22:37:00.947+02:00`  

### Application version

0.17.8

### Where did you install the app from?

Google Play

### Device information

Sony BRAVIA_VH2_EU  4K VH2

### Android version

Android 10

### Jellyfin server version

10.10.0

**Comment by nielsvanvelzen** [comment]
Does this happen consistently or was this a one time crash?

**Comment by schrottsimon** [comment]
I have 6 of these crash logs with the same error since last week.

**Comment by nielsvanvelzen** [comment]
It looks like this issue is caused by your server/network as there are weird DNS errors in the crashlogs. I'd recommend using our troubleshooting chat or forum listed at https://jellyfin.org/contact.

**Comment by schrottsimon** [comment]
For anyone else finding this. DuckDNS was causing the crashes. Switched to a bought Domain to fix it.
