### ISSUE TITLE
Transcoding video on Nvidia shield (direct plays on Plex)

### ISSUE THREAD

**Issue by yoasif** [jellyfin/jellyfin-androidtv#414]
**Media Info of the file**

```
General
Unique ID                                : 0 (0x0)
Complete name                            : 24.S01E04.1080p.BluRay.x264-SHORTBREHD\24.S01E04.1080p.BluRay.x264-SHORTBREHD.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 3.97 GiB
Duration                                 : 41 min 58 s
Overall bit rate                         : 13.5 Mb/s
Encoded date                             : UTC 2010-02-22 21:41:29
Writing application                      : no_variable_data
Writing library                          : no_variable_data

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 41 min 58 s
Bit rate                                 : 13.3 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.268
Stream size                              : 3.82 GiB (96%)
Writing library                          : x264 core 152 r2851 ba24899
Encoding settings                        : cabac=1 / ref=4 / deblock=1:-3:-3 / analyse=0x3:0x113 / me=umh / subme=8 / psy=1 / psy_rd=1.15:0.00 / mixed_ref=1 / me_range=32 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=24 / lookahead_threads=4 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=240 / keyint_min=24 / scenecut=40 / intra_refresh=0 / rc_lookahead=50 / rc=2pass / mbtree=1 / bitrate=13313 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / aq=3:0.75
Default                                  : Yes
Forced                                   : No
Statistics Tags Issue                    : no_variable_data 1970-01-01 00:00:00 / no_variable_data 2010-02-22 21:41:29
FromStats_BitRate                        : 13309120
FromStats_Duration                       : 00:41:58.516000000
FromStats_FrameCount                     : 60384
FromStats_StreamSize                     : 4189904080

Audio
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 41 min 58 s
Bit rate mode                            : Constant
Bit rate                                 : 224 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 67.3 MiB (2%)
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No
Statistics Tags Issue                    : no_variable_data 1970-01-01 00:00:00 / no_variable_data 2010-02-22 21:41:29
FromStats_BitRate                        : 224000
FromStats_Duration                       : 00:41:58.528000000
FromStats_FrameCount                     : 78704
FromStats_StreamSize                     : 70518784

Text
ID                                       : 3
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Language                                 : English
Default                                  : No
Forced                                   : No
Statistics Tags Issue                    : no_variable_data 1970-01-01 00:00:00 / no_variable_data 2010-02-22 21:41:29
FromStats_BitRate                        : 51
FromStats_Duration                       : 00:40:15.914000000
FromStats_FrameCount                     : 362
FromStats_StreamSize                     : 15686

Menu
00:00:00.000                             : en:00:00:00.000
00:07:56.768                             : en:00:07:56.768
00:15:40.481                             : en:00:15:40.481
00:26:27.503                             : en:00:26:27.503
00:33:43.146                             : en:00:33:43.146
00:41:20.311                             : en:00:41:20.311
```

**Logs**

[jellyfin.log](https://github.com/jellyfin/jellyfin/files/4367304/jellyfin.log)

**FFmpeg Logs**

[ffmpeg.log](https://github.com/jellyfin/jellyfin/files/4367303/ffmpeg.log)

**Stats for Nerds Screenshots**

**Server System (please complete the following information):**
 - OS: Docker on Linux
 - Jellyfin Version: 10.5.0
 - Hardware settings & device: Xeon quadcore
 - Reverse proxy: no
 - Other hardware notes: 
 
**Client System (please complete the following information):**
 - Device: Nvidia shield
 - OS: Android
 - Client:  Android TV
 - Client and Browser Version: 0.11.2

**Comment by JustAMan** [comment]
Seems to be an AndroidTV-specific issue, so moved.

**Comment by Artiume** [comment]
```
[2020-03-23 01:08:14.873 -04:00] [INF] [31] App: GetPostedPlaybackInfo profile: DeviceProfile { Name: "Android-Exo", Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 20000000, MaxStaticBitrate: 30000000, MusicStreamingTranscodingBitrate: 128000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "m4v,mov,xvid,vob,mkv,wmv,asf,ogm,ogv,mp4,webm", AudioCodec: "aac,ac3,eac3,aac_latm,mp3,mp2,dca,dts", VideoCodec: "h264,hevc,vp8,vp9,mpeg,mpeg2video", Type: Video }, DirectPlayProfile { Container: "aac,mp3,mpa,wav,wma,mp2,ogg,oga,webma,ape,opus", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "jpg,jpeg,png,gif", AudioCodec: null, VideoCodec: null, Type: Photo }], TranscodingProfiles: [TranscodingProfile { Container: "mkv", Type: Video, VideoCodec: "h264", AudioCodec: "ac3,aac,mp3", Protocol: null, EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: True, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: null, EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "high|main|baseline|constrained baseline", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "51", IsRequired: False }], ApplyConditions: [], Codec: "h264", Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: LessThanEqual, Property: RefFrames, Value: "12", IsRequired: False }], ApplyConditions: [ProfileCondition { Condition: GreaterThanEqual, Property: Width, Value: "1200", IsRequired: False }], Codec: "h264", Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: LessThanEqual, Property: RefFrames, Value: "4", IsRequired: False }], ApplyConditions: [ProfileCondition { Condition: GreaterThanEqual, Property: Width, Value: "1900", IsRequired: False }], Codec: "h264", Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: VideoProfile, Value: "none", IsRequired: False }], ApplyConditions: [], Codec: "hevc", Container: null }, CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: LessThanEqual, Property: AudioChannels, Value: "6", IsRequired: False }], ApplyConditions: [], Codec: null, Container: null }], ResponseProfiles: [], SubtitleProfiles: [SubtitleProfile { Format: "srt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "srt", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "subrip", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: Encode, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: Encode, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgs", Method: Encode, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgssub", Method: Encode, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "dvdsub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "vtt", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "sub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "idx", Method: Embed, DidlMode: null, Language: null, Container: null }] }
[2020-03-23 01:08:14.931 -04:00] [INF] [31] App: User policy for "Tañas". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2020-03-23 01:08:14.931 -04:00] [INF] [31] App: Profile: "Android-Exo", Path: "/data/tvshows/24/24 s01/24.S01E04.1080p.BluRay.x264-SHORTBREHD/24.S01E04.1080p.BluRay.x264-SHORTBREHD.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-03-23 01:08:14.931 -04:00] [INF] [31] App: Profile: "Android-Exo", Path: "/data/tvshows/24/24 s01/24.S01E04.1080p.BluRay.x264-SHORTBREHD/24.S01E04.1080p.BluRay.x264-SHORTBREHD.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-03-23 01:08:14.962 -04:00] [ERR] [31] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request
MediaBrowser.Common.Extensions.ResourceNotFoundException: 24 does not have an image of type Logo
   at MediaBrowser.Api.Images.ImageService.GetImage(ImageRequest request, Guid itemId, BaseItem item, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-03-23 01:08:14.962 -04:00] [ERR] [21] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request
System.ArgumentException: Invalid type (Parameter 'type')
   at MediaBrowser.Api.BaseApiService.GetItemByName(String name, String type, ILibraryManager libraryManager, DtoOptions dtoOptions)
   at MediaBrowser.Api.Images.ImageService.Get(GetItemByNameImage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-03-23 01:08:15.069 -04:00] [INF] [34] MediaBrowser.Api.Playback.Progressive.VideoService: /usr/lib/jellyfin-ffmpeg/ffmpeg -f matroska,webm -i file:"/data/tvshows/24/24 s01/24.S01E04.1080p.BluRay.x264-SHORTBREHD/24.S01E04.1080p.BluRay.x264-SHORTBREHD.mkv" -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -force_key_frames "expr:gte(t,n_forced*5)" -vf "scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2" -copyts -avoid_negative_ts disabled -start_at_zero -pix_fmt yuv420p -preset superfast -crf 23 -maxrate 13535107 -bufsize 27070214 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -vsync -1 -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 ac3 -ac 2 -ab 224000  -y "/config/data/transcodes/efbc1ecac774827177ef274cb4e4d50b.mkv"
[2020-03-23 01:08:32.103 -04:00] [ERR] [35] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "The operation was canceled."
[2020-03-23 01:08:32.103 -04:00] [WRN] [35] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "192.168.69.201". Time (slow): 0:00:17.133864. "http://192.168.69.100:8096/videos/dde035a6-81cb-8634-4ccb-8fc985253cbd/stream.mkv?DeviceId=3032105d61921e3c&MediaSourceId=dde035a681cb86344ccb8fc985253cbd&VideoCodec=h264&AudioCodec=ac3,aac,mp3&AudioStreamIndex=1&VideoBitrate=99776000&AudioBitrate=224000&PlaySessionId=d6abc343a4974b5db1bf7ceedb4b66ed&SubtitleMethod=Encode&CopyTimestamps=true&RequireAvc=false&Tag=b58a53bf63c6b5b5d19de8ee733f3407&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&h264-maxrefframes=4&ac3-audiochannels=6&aac-audiochannels=6&mp3-audiochannels=6&TranscodeReasons=ContainerBitrateExceedsLimit&allowVideoStreamCopy=false&allowAudioStreamCopy=false,false"
[2020-03-23 01:08:32.119 -04:00] [INF] [21] App: Stopping ffmpeg process with q command for "/config/data/transcodes/efbc1ecac774827177ef274cb4e4d50b.mkv"
[2020-03-23 01:08:32.253 -04:00] [INF] [21] MediaBrowser.Api.Playback.Progressive.VideoService: FFMpeg exited with code 0
[2020-03-23 01:08:32.254 -04:00] [INF] [21] App: Deleting partial stream file(s) "/config/data/transcodes/efbc1ecac774827177ef274cb4e4d50b.mkv"
[2020-03-23 01:08:33.770 -04:00] [INF] [21] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "AndroidTV" "0.11.2" playing "3:00 A.M. - 4:00 A.M.". Stopped at "15544" ms
[2020-03-23 01:08:33.821 -04:00] [WRN] [21] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "192.168.69.201". Time (slow): 0:00:01.7057603. "http://192.168.69.100:8096/Sessions/Playing/Stopped"
```

Not sure what this is about
`[2020-03-23 01:08:14.962 -04:00] [ERR] [21] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request
System.ArgumentException: Invalid type (Parameter 'type')
   at MediaBrowser.Api.BaseApiService.GetItemByName(String name, String type, ILibraryManager libraryManager, DtoOptions dtoOptions)
   at MediaBrowser.Api.Images.ImageService.Get(GetItemByNameImage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)`



Digging into the AndroidTV code, the only thing I found that had a bitrate limit close to `VideoBitrate=99776000` was this for External Players. This shouldn't be impacting it but it's the only correlation I've found.

```

    public static DeviceProfile getExternalProfile() {
        DeviceProfile profile = new DeviceProfile();

        profile.setName("Android-External");
        profile.setMaxStaticBitrate(100000000);
```

This should be the bitrate limit setpoint if I'm reading this right.
```
    public static DeviceProfile getBaseProfile(boolean isLiveTv) {
        DeviceProfile profile = new DeviceProfile();

        profile.setName("Android");
        profile.setMaxStreamingBitrate(20000000);
        profile.setMaxStaticBitrate(30000000);

        List<TranscodingProfile> transcodingProfiles = new ArrayList<>();

        TranscodingProfile transProfile = new TranscodingProfile();
```

@thornbill You have any ideas?
