### ISSUE TITLE
Player crashes instantly when Direct Streaming & Stereo Downmixing for specific video formats

### ISSUE THREAD

**Issue by andries230** [jellyfin/jellyfin-androidtv#4238]
### Describe the bug

To reproduce:

1. Open the AndroidTV client
2. Go to settings (cog icon)
3. Go to 'Playback' > Make sure to set Audio to 'Stereo-downmix'
4. Direct-stream a video with (at least) Dolby Vision and Dolby Atmos
5. The error occurs...

### System log
```
[2024-11-21 10:06:35.256 +01:00] [INF] [31] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for "/config/cache/transcodes/21a5c5665d529214b0dd80c791eac585.m3u8"
[2024-11-21 10:06:35.261 +01:00] [INF] [17] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "Me". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-11-21 10:06:35.261 +01:00] [INF] [17] Jellyfin.Api.Helpers.MediaInfoHelper: RemoteClientBitrateLimit: 35000000, RemoteIP: "172.18.0.2", IsInLocalNetwork: False
[2024-11-21 10:06:35.293 +01:00] [INF] [31] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[2024-11-21 10:06:35.294 +01:00] [INF] [31] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) "/config/cache/transcodes/21a5c5665d529214b0dd80c791eac585.m3u8"
[2024-11-21 10:06:35.737 +01:00] [INF] [28] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -probesize 1G -readrate 10 -fflags +genpts -f matroska  -i file:\"/data/movies/Guardians.of.the.Galaxy.Vol.3.2023.2160p.WEB-DL.DDP5.1.Atmos.HDR.DV.HEVC-CMRG[TGx]/Guardians.of.the.Galaxy.Vol.3.2023.2160p.WEB-DL.DDP5.1.Atmos.HDR.DV.HEVC-CMRG.mkv\" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -tag:v:0 hvc1 -bsf:v hevc_mp4toannexb -start_at_zero -codec:a:0 libfdk_aac -ac 2 -ab 256000 -af \"volume=2\" -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_segment_filename \"/config/cache/transcodes/17bd4f13f583737c6b9879745f7983cb%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/config/cache/transcodes/17bd4f13f583737c6b9879745f7983cb.m3u8\""
[2024-11-21 10:06:36.802 +01:00] [INF] [28] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Android TV" "0.17.9" playing "Guardians of the Galaxy Vol. 3". Stopped at "907157" ms
[2024-11-21 10:06:37.499 +01:00] [INF] [32] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for "/config/cache/transcodes/17bd4f13f583737c6b9879745f7983cb.m3u8"
[2024-11-21 10:06:37.766 +01:00] [INF] [32] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[2024-11-21 10:06:37.766 +01:00] [INF] [32] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) "/config/cache/transcodes/17bd4f13f583737c6b9879745f7983cb.m3u8"
[2024-11-21 10:06:39.276 +01:00] [INF] [37] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Android TV" "0.17.9" playing "Guardians of the Galaxy Vol. 3". Stopped at "907157" ms
```

### FFMPEG LOG
```
{"Protocol":0,"Id":"0d7c20648c1b17c22f7d54d1aa745630","Path":"/data/movies/Guardians.of.the.Galaxy.Vol.3.2023.2160p.WEB-DL.DDP5.1.Atmos.HDR.DV.HEVC-CMRG[TGx]/Guardians.of.the.Galaxy.Vol.3.2023.2160p.WEB-DL.DDP5.1.Atmos.HDR.DV.HEVC-CMRG.mkv","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mkv","Size":28534114264,"Name":"Guardians.of.the.Galaxy.Vol.3.2023.2160p.WEB-DL.DDP5.1.Atmos.HDR.DV.HEVC-CMRG","IsRemote":false,"ETag":"f019591daf49a521ce0e41f7b6528d2a","RunTimeTicks":90027520000,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"UseMostCompatibleTranscodingProfile":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"subrip","CodecTag":null,"Language":"dut","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Rotation":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":"Undefined","LocalizedDefault":"Default","LocalizedForced":"Forced","LocalizedExternal":"External","LocalizedHearingImpaired":"Hearing Impaired","DisplayTitle":"Dut - SUBRIP - External","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"IsHearingImpaired":false,"Height":0,"Width":0,"AverageFrameRate":null,"RealFrameRate":null,"ReferenceFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":0,"Score":null,"IsExternal":true,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":"/data/movies/Guardians.of.the.Galaxy.Vol.3.2023.2160p.WEB-DL.DDP5.1.Atmos.HDR.DV.HEVC-CMRG[TGx]/Guardians.of.the.Galaxy.Vol.3.2023.2160p.WEB-DL.DDP5.1.Atmos.HDR.DV.HEVC-CMRG.dut.srt","PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"dut","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Rotation":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"synced","VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":"Undefined","LocalizedDefault":"Default","LocalizedForced":"Forced","LocalizedExternal":"External","LocalizedHearingImpaired":"Hearing Impaired","DisplayTitle":"synced - Dut - Default - SUBRIP - External","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":0,"Width":0,"AverageFrameRate":null,"RealFrameRate":null,"ReferenceFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":1,"Score":null,"IsExternal":true,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":"/data/movies/Guardians.of.the.Galaxy.Vol.3.2023.2160p.WEB-DL.DDP5.1.Atmos.HDR.DV.HEVC-CMRG[TGx]/Guardians.of.the.Galaxy.Vol.3.2023.2160p.WEB-DL.DDP5.1.Atmos.HDR.DV.HEVC-CMRG.dut.synced.default.srt","PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"hevc","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":"bt2020nc","ColorTransfer":"smpte2084","ColorPrimaries":"bt2020","DvVersionMajor":1,"DvVersionMinor":0,"DvProfile":8,"DvLevel":6,"RpuPresentFlag":1,"ElPresentFlag":0,"BlPresentFlag":1,"DvBlSignalCompatibilityId":1,"Rotation":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":2,"VideoRangeType":5,"VideoDoViTitle":"Dolby Vision Profile 8.1 (HDR10)","AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"LocalizedHearingImpaired":null,"DisplayTitle":"4K HEVC Dolby Vision Profile 8.1 (HDR10)","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":null,"BitRate":25355903,"BitDepth":10,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":2024,"Width":3840,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"ReferenceFrameRate":23.976025,"Profile":"Main 10","Type":1,"AspectRatio":"480:253","Index":2,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p10le","Level":150,"IsAnamorphic":false},{"Codec":"eac3","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Rotation":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":1,"LocalizedUndefined":null,"LocalizedDefault":"Default","LocalizedForced":null,"LocalizedExternal":"External","LocalizedHearingImpaired":null,"DisplayTitle":"English - Dolby Digital Plus \u002B Dolby Atmos - 5.1 - Default","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":"5.1","BitRate":768000,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":6,"SampleRate":48000,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"ReferenceFrameRate":null,"Profile":"Dolby Digital Plus \u002B Dolby Atmos","Type":0,"AspectRatio":null,"Index":3,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":26123903,"FallbackMaxStreamingBitrate":null,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":0,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null,"HasSegments":false}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -readrate 10 -fflags +genpts -f matroska  -i file:"/data/movies/Guardians.of.the.Galaxy.Vol.3.2023.2160p.WEB-DL.DDP5.1.Atmos.HDR.DV.HEVC-CMRG[TGx]/Guardians.of.the.Galaxy.Vol.3.2023.2160p.WEB-DL.DDP5.1.Atmos.HDR.DV.HEVC-CMRG.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -tag:v:0 hvc1 -bsf:v hevc_mp4toannexb -start_at_zero -codec:a:0 libfdk_aac -ac 2 -ab 256000 -af "volume=2" -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/cache/transcodes/17bd4f13f583737c6b9879745f7983cb%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/cache/transcodes/17bd4f13f583737c6b9879745f7983cb.m3u8"


ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13 (Ubuntu 13.2.0-23ubuntu4)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Input #0, matroska,webm, from 'file:/data/movies/Guardians.of.the.Galaxy.Vol.3.2023.2160p.WEB-DL.DDP5.1.Atmos.HDR.DV.HEVC-CMRG[TGx]/Guardians.of.the.Galaxy.Vol.3.2023.2160p.WEB-DL.DDP5.1.Atmos.HDR.DV.HEVC-CMRG.mkv':
  Metadata:
    encoder         : libebml v1.4.4 + libmatroska v1.7.1
  Duration: 02:30:02.75, start: 0.000000, bitrate: 25355 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 480.647000
      Metadata:
        title           : Chapter 01
    Chapter #0:1: start 480.647000, end 816.733000
      Metadata:
        title           : Chapter 02
    Chapter #0:2: start 816.733000, end 968.677000
      Metadata:
        title           : Chapter 03
    Chapter #0:3: start 968.677000, end 1124.374000
      Metadata:
        title           : Chapter 04
    Chapter #0:4: start 1124.374000, end 1237.153000
      Metadata:
        title           : Chapter 05
    Chapter #0:5: start 1237.153000, end 1438.772000
      Metadata:
        title           : Chapter 06
    Chapter #0:6: start 1438.772000, end 1604.979000
      Metadata:
        title           : Chapter 07
    Chapter #0:7: start 1604.979000, end 1844.594000
      Metadata:
        title           : Chapter 08
    Chapter #0:8: start 1844.594000, end 2085.627000
      Metadata:
        title           : Chapter 09
    Chapter #0:9: start 2085.627000, end 2435.685000
      Metadata:
        title           : Chapter 10
    Chapter #0:10: start 2435.685000, end 2990.657000
      Metadata:
        title           : Chapter 11
    Chapter #0:11: start 2990.657000, end 3135.218000
      Metadata:
        title           : Chapter 12
    Chapter #0:12: start 3135.218000, end 3438.146000
      Metadata:
        title           : Chapter 13
    Chapter #0:13: start 3438.146000, end 3583.458000
      Metadata:
        title           : Chapter 14
    Chapter #0:14: start 3583.458000, end 3778.486000
      Metadata:
        title           : Chapter 15
    Chapter #0:15: start 3778.486000, end 3937.896000
      Metadata:
        title           : Chapter 16
    Chapter #0:16: start 3937.896000, end 4152.318000
      Metadata:
        title           : Chapter 17
    Chapter #0:17: start 4152.318000, end 4435.727000
      Metadata:
        title           : Chapter 18
    Chapter #0:18: start 4435.727000, end 4793.960000
      Metadata:
        title           : Chapter 19
    Chapter #0:19: start 4793.960000, end 5206.790000
      Metadata:
        title           : Chapter 20
    Chapter #0:20: start 5206.790000, end 5460.043000
      Metadata:
        title           : Chapter 21
    Chapter #0:21: start 5460.043000, end 5962.962000
      Metadata:
        title           : Chapter 22
    Chapter #0:22: start 5962.962000, end 6265.932000
      Metadata:
        title           : Chapter 23
    Chapter #0:23: start 6265.932000, end 6704.829000
      Metadata:
        title           : Chapter 24
    Chapter #0:24: start 6704.829000, end 6909.284000
      Metadata:
        title           : Chapter 25
    Chapter #0:25: start 6909.284000, end 7155.947000
      Metadata:
        title           : Chapter 26
    Chapter #0:26: start 7155.947000, end 7401.401000
      Metadata:
        title           : Chapter 27
    Chapter #0:27: start 7401.401000, end 7669.461000
      Metadata:
        title           : Chapter 28
    Chapter #0:28: start 7669.461000, end 7906.072000
      Metadata:
        title           : Chapter 29
    Chapter #0:29: start 7906.072000, end 8414.664000
      Metadata:
        title           : Chapter 30
    Chapter #0:30: start 8414.664000, end 8482.065000
      Metadata:
        title           : Chapter 31
    Chapter #0:31: start 8482.065000, end 8576.659000
      Metadata:
        title           : Chapter 32
    Chapter #0:32: start 8576.659000, end 8954.079000
      Metadata:
        title           : Chapter 33
    Chapter #0:33: start 8954.079000, end 9002.752000
      Metadata:
        title           : Chapter 34
  Stream #0:0(eng): Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2024 [SAR 1:1 DAR 480:253], 23.98 fps, 23.98 tbr, 1k tbn (default) (original)
      Metadata:
        BPS             : 24585300
        DURATION        : 02:30:02.744000000
        NUMBER_OF_FRAMES: 215850
        NUMBER_OF_BYTES : 27666895830
        _STATISTICS_WRITING_APP: mkvmerge v75.0.0 ('Goliath') 64-bit
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      Side data:
        DOVI configuration record: version: 1.0, profile: 8, level: 6, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 1
  Stream #0:1(eng): Audio: eac3 (Dolby Digital Plus + Dolby Atmos), 48000 Hz, 5.1(side), fltp, 768 kb/s (default) (original)
      Metadata:
        BPS             : 768000
        DURATION        : 02:30:02.752000000
        NUMBER_OF_FRAMES: 281336
        NUMBER_OF_BYTES : 864264192
        _STATISTICS_WRITING_APP: mkvmerge v75.0.0 ('Goliath') 64-bit
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Subtitle: subrip (srt) (original)
      Metadata:
        BPS             : 41
        DURATION        : 02:27:31.351000000
        NUMBER_OF_FRAMES: 1617
        NUMBER_OF_BYTES : 45616
        _STATISTICS_WRITING_APP: mkvmerge v75.0.0 ('Goliath') 64-bit
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(eng): Subtitle: subrip (srt) (original) (hearing impaired)
      Metadata:
        title           : SDH
        BPS             : 70
        DURATION        : 02:29:53.855000000
        NUMBER_OF_FRAMES: 2790
        NUMBER_OF_BYTES : 79596
        _STATISTICS_WRITING_APP: mkvmerge v75.0.0 ('Goliath') 64-bit
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:4(spa): Subtitle: subrip (srt) (dub)
      Metadata:
        title           : Latin American
        BPS             : 39
        DURATION        : 02:27:47.743000000
        NUMBER_OF_FRAMES: 1626
        NUMBER_OF_BYTES : 43609
        _STATISTICS_WRITING_APP: mkvmerge v75.0.0 ('Goliath') 64-bit
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:5(fre): Subtitle: subrip (srt) (dub)
      Metadata:
        title           : Canadian
        BPS             : 44
        DURATION        : 02:27:47.743000000
        NUMBER_OF_FRAMES: 1628
        NUMBER_OF_BYTES : 48985
        _STATISTICS_WRITING_APP: mkvmerge v75.0.0 ('Goliath') 64-bit
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (eac3 (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
Output #0, hls, to '/config/cache/transcodes/17bd4f13f583737c6b9879745f7983cb.m3u8':
  Metadata:
    encoder         : Lavf61.1.100
  Stream #0:0: Video: hevc (Main 10) (hvc1 / 0x31637668), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2024 [SAR 1:1 DAR 480:253], q=2-31, 23.98 fps, 23.98 tbr, 90k tbn (default) (original)
      Side data:
        DOVI configuration record: version: 1.0, profile: 8, level: 6, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 1
  Stream #0:1: Audio: aac, 48000 Hz, stereo, s16, 256 kb/s (default) (original)
      Metadata:
        encoder         : Lavc61.3.100 libfdk_aac
size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
[hls @ 0x580e60344700] Opening '/config/cache/transcodes/17bd4f13f583737c6b9879745f7983cb0.ts' for writing
size=N/A time=00:00:05.00 bitrate=N/A speed=   5x    
[hls @ 0x580e60344700] Opening '/config/cache/transcodes/17bd4f13f583737c6b9879745f7983cb1.ts' for writing
size=N/A time=00:00:10.09 bitrate=N/A speed=6.73x    
[hls @ 0x580e60344700] Opening '/config/cache/transcodes/17bd4f13f583737c6b9879745f7983cb2.ts' for writing


[q] command received. Exiting.

[hls @ 0x580e60344700] Opening '/config/cache/transcodes/17bd4f13f583737c6b9879745f7983cb3.ts' for writing
[out#0/hls @ 0x580e60306300] video:43450KiB audio:641KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
size=N/A time=00:00:15.01 bitrate=N/A speed=7.47x    
```

### Application version

0.17.9

### Where did you install the app from?

Google Play

### Device information

Phillips TPM191E

### Android version

Latest

### Jellyfin server version

10.10.3

**Comment by Dnkhatri** [comment]
try 18 beta 4
https://github.com/jellyfin/jellyfin-androidtv/releases/tag/v0.18.0-beta.4

**Comment by relic664** [comment]
+1, same issue even on 0.18.2. I saw some errors related to parsing the subs, but even after that, it still fails. My logs are pretty similar to @andries230 in that there's no easily discernible error.

**Comment by relic664** [comment]
Here's the logcat snippet from when the error occurs:

```plain
E(22211:22211) playerFailed [eventTime=12.78, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_IO_UNSPECIFIED
E(22211:22211)   androidx.media3.exoplayer.ExoPlaybackException: Source error
E(22211:22211)       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:736)
E(22211:22211)       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:712)
E(22211:22211)       at android.os.Handler.dispatchMessage(Handler.java:102)
E(22211:22211)       at android.os.Looper.loop(Looper.java:223)
E(22211:22211)       at android.os.HandlerThread.run(HandlerThread.java:67)
E(22211:22211)   Caused by: androidx.media3.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException
E(22211:22211)       at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:442)
E(22211:22211)       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E(22211:22211)       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E(22211:22211)       at java.lang.Thread.run(Thread.java:923)
E(22211:22211)   Caused by: java.lang.IllegalArgumentException
E(22211:22211)       at androidx.media3.common.util.Assertions.checkArgument(Assertions.java:40)
E(22211:22211)       at androidx.media3.exoplayer.source.SampleQueue.commitSample(SampleQueue.java:811)
E(22211:22211)       at androidx.media3.exoplayer.source.SampleQueue.sampleMetadata(SampleQueue.java:655)
E(22211:22211)       at androidx.media3.exoplayer.hls.HlsSampleStreamWrapper$HlsSampleQueue.sampleMetadata(HlsSampleStreamWrapper.java:1790)
E(22211:22211)       at androidx.media3.extractor.ts.H265Reader$SampleReader.outputSample(H265Reader.java:398)
E(22211:22211)       at androidx.media3.extractor.ts.H265Reader$SampleReader.end(H265Reader.java:384)
E(22211:22211)       at androidx.media3.extractor.ts.H265Reader.packetFinished(H265Reader.java:178)
E(22211:22211)       at androidx.media3.extractor.ts.PesReader.consume(PesReader.java:111)
E(22211:22211)       at androidx.media3.extractor.ts.TsExtractor.read(TsExtractor.java:457)
E(22211:22211)       at androidx.media3.exoplayer.hls.BundledHlsMediaChunkExtractor.read(BundledHlsMediaChunkExtractor.java:102)
E(22211:22211)       at androidx.media3.exoplayer.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:503)
E(22211:22211)       at androidx.media3.exoplayer.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:467)
E(22211:22211)       at androidx.media3.exoplayer.hls.HlsMediaChunk.load(HlsMediaChunk.java:424)
E(22211:22211)       at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
E(22211:22211)       ... 3 more
E(22211:22211) ]
E(22211:22211) ***** Got error from player
E(22211:22211) Playback error - Failed to load video
```

**Comment by relic664** [comment]
So I've been able to narrow this down a bit to Dolby Vision with Dolby Atmos or DD+. My library isn't huge, but those are known to fail. 

I've also narrowed it down to something with HLS specifically that is unrelated to the audio codec:

- Taking the default downmix transcode command and generating a file instead of HLS works fine, playback has no problem
- Stripping the audio track from the HLS stream entirely still results in a crash. 

I'll provide some examples.

Baseline downmix ffmpeg command:

```
/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -fflags +genpts -f matroska  -i file:"/data/media/tv/file.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -tag:v:0 hvc1 -bsf:v hevc_mp4toannexb -start_at_zero -codec:a:0 libfdk_aac -ab 256000 -af "pan=stereo|c0=c2+0.30*c0+0.30*c4|c1=c2+0.30*c1+0.30*c5,volume=2" -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/cache/transcodes/94255cd07d5db1b31db24e7f4f1fa0d7%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/cache/transcodes/94255cd07d5db1b31db24e7f4f1fa0d7.m3u8"
```

MWE for copy (no HLS - this works)

```
/usr/lib/jellyfin-ffmpeg/ffmpeg -ss 00:00:00 -to 00:01:00 -analyzeduration 200M -probesize 1G -fflags +genpts -f matroska  -i file:"movie.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -tag:v:0 hvc1 -start_at_zero -an -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f matroska "/path/to/out/out.mkv"
```

MWE for HLS (this fails to play, even the individual `.ts` segments)

```
/usr/lib/jellyfin-ffmpeg/ffmpeg -ss 00:00:00 -to 00:01:00 -analyzeduration 200M -probesize 1G -fflags +genpts -f matroska  -i file:"movie.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -tag:v:0 hvc1 -start_at_zero -an -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/cache/transcodes/tc%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/cache/transcodes/tc.m3u8"
```

**Comment by Trenarius** [comment]
Exact same issue
- newest beta
- 4k fire tv stick
if i disable downmixing the player doesnt crash, but the image gets displayed wrong:
![Image](https://github.com/user-attachments/assets/eba15dbc-4979-4463-8e75-b5dbb99e1fd1)

Force transcoding by lowering bitrate stope the player from crashing. 
In Version 16.01 everything worked fine

**Comment by relic664** [comment]
@andries230 this issue was resolved for me at 0.18.8 at least.
