### ISSUE TITLE
Leaving seen collection results in app crash

### ISSUE THREAD

**Issue by bin101** [jellyfin/jellyfin-androidtv#4273]
### Describe the bug

1. Open Collections
2. Enable seen filter
3. Enter a collection which is completely seen (first issue: it should be filtered)
4. Navigate back
5. Apps crash 

### Logs

---
client: Jellyfin for Android TV
client_version: 0.18.1
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
android.util.AndroidRuntimeException: Animators may only be run on Looper threads
	at android.animation.ValueAnimator.end(ValueAnimator.java:1142)
	at androidx.leanback.widget.FocusHighlightHelper$FocusAnimator.endAnimation(FocusHighlightHelper.java:128)
	at androidx.leanback.widget.FocusHighlightHelper$FocusAnimator.animateFocus(FocusHighlightHelper.java:74)
	at androidx.leanback.widget.FocusHighlightHelper$BrowseItemFocusHighlight.onItemFocused(FocusHighlightHelper.java:169)
	at androidx.leanback.widget.ItemBridgeAdapter$ChainingFocusChangeListener.onFocusChange(ItemBridgeAdapter.java:103)
	at android.view.View.onFocusChanged(View.java:8109)
	at android.view.View.clearFocusInternal(View.java:7946)
	at android.view.View.unFocus(View.java:7979)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1203)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1205)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1205)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1205)
	at android.view.ViewGroup.requestChildFocus(ViewGroup.java:863)
	at android.view.ViewGroup.requestChildFocus(ViewGroup.java:869)
	at android.view.View.handleFocusGainInternal(View.java:7771)
	at android.view.View.requestFocusNoSearch(View.java:13540)
	at android.view.View.requestFocus(View.java:13514)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3374)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:3323)
	at android.view.View.requestFocus(View.java:13481)
	at android.view.View.requestFocus(View.java:13423)
	at org.jellyfin.androidtv.ui.browsing.BrowseGridFragment.lambda$refreshCurrentItem$3$org-jellyfin-androidtv-ui-browsing-BrowseGridFragment(BrowseGridFragment.java:888)
	at org.jellyfin.androidtv.ui.browsing.BrowseGridFragment$$ExternalSyntheticLambda2.invoke(D8$$SyntheticClass:0)
	at org.jellyfin.androidtv.ui.itemhandling.ItemRowAdapterHelperKt$refreshItem$2.invokeSuspend(ItemRowAdapterHelper.kt:697)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5d88ea2, Dispatchers.IO]

```  
***Logcat***: 
```log
12-05 17:59:04.952 E/ViewRootImpl(13933): 	at org.jellyfin.androidtv.ui.browsing.BrowseGridFragment.lambda$refreshCurrentItem$3$org-jellyfin-androidtv-ui-browsing-BrowseGridFragment(BrowseGridFragment.java:888)
12-05 17:59:04.952 E/ViewRootImpl(13933): 	at org.jellyfin.androidtv.ui.browsing.BrowseGridFragment$$ExternalSyntheticLambda2.invoke(D8$$SyntheticClass:0)
12-05 17:59:04.952 E/ViewRootImpl(13933): 	at org.jellyfin.androidtv.ui.itemhandling.ItemRowAdapterHelperKt$refreshItem$2.invokeSuspend(ItemRowAdapterHelper.kt:697)
12-05 17:59:04.952 E/ViewRootImpl(13933): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-05 17:59:04.952 E/ViewRootImpl(13933): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
12-05 17:59:04.952 E/ViewRootImpl(13933): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
12-05 17:59:04.952 E/ViewRootImpl(13933): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
12-05 17:59:04.952 E/ViewRootImpl(13933): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
12-05 17:59:04.952 E/ViewRootImpl(13933): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
12-05 17:59:04.952 E/ViewRootImpl(13933): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
12-05 17:59:04.952 E/ViewRootImpl(13933): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
12-05 17:59:04.953 E/ViewRootImpl(13933): Accessibility content change on non-UI thread. Future Android versions will throw an exception.
12-05 17:59:04.953 E/ViewRootImpl(13933): android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.runOrPost(ViewRootImpl.java:10221)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.ViewRootImpl.postSendWindowContentChangedCallback(ViewRootImpl.java:9053)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.ViewRootImpl.notifySubtreeAccessibilityStateChanged(ViewRootImpl.java:9233)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3847)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3847)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3847)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3847)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3847)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3847)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3847)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3847)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3847)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.View.notifyViewAccessibilityStateChangedIfNeeded(View.java:13950)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.View.setSelected(View.java:24879)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at androidx.leanback.widget.FocusHighlightHelper$BrowseItemFocusHighlight.onItemFocused(FocusHighlightHelper.java:168)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at androidx.leanback.widget.ItemBridgeAdapter$ChainingFocusChangeListener.onFocusChange(ItemBridgeAdapter.java:103)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.View.onFocusChanged(View.java:8109)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.View.clearFocusInternal(View.java:7946)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.View.unFocus(View.java:7979)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.ViewGroup.unFocus(ViewGroup.java:1203)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.ViewGroup.unFocus(ViewGroup.java:1205)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.ViewGroup.unFocus(ViewGroup.java:1205)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.ViewGroup.unFocus(ViewGroup.java:1205)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.ViewGroup.requestChildFocus(ViewGroup.java:863)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.ViewGroup.requestChildFocus(ViewGroup.java:869)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.View.handleFocusGainInternal(View.java:7771)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.View.requestFocusNoSearch(View.java:13540)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.View.requestFocus(View.java:13514)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3374)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.ViewGroup.requestFocus(ViewGroup.java:3323)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.View.requestFocus(View.java:13481)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at android.view.View.requestFocus(View.java:13423)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at org.jellyfin.androidtv.ui.browsing.BrowseGridFragment.lambda$refreshCurrentItem$3$org-jellyfin-androidtv-ui-browsing-BrowseGridFragment(BrowseGridFragment.java:888)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at org.jellyfin.androidtv.ui.browsing.BrowseGridFragment$$ExternalSyntheticLambda2.invoke(D8$$SyntheticClass:0)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at org.jellyfin.androidtv.ui.itemhandling.ItemRowAdapterHelperKt$refreshItem$2.invokeSuspend(ItemRowAdapterHelper.kt:697)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
12-05 17:59:04.953 E/ViewRootImpl(13933): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
12-05 17:59:04.955 E/ACRA    (13933): ACRA caught a AndroidRuntimeException for org.jellyfin.androidtv
12-05 17:59:04.955 E/ACRA    (13933): android.util.AndroidRuntimeException: Animators may only be run on Looper threads
12-05 17:59:04.955 E/ACRA    (13933): 	at android.animation.ValueAnimator.end(ValueAnimator.java:1142)
12-05 17:59:04.955 E/ACRA    (13933): 	at androidx.leanback.widget.FocusHighlightHelper$FocusAnimator.endAnimation(FocusHighlightHelper.java:128)
12-05 17:59:04.955 E/ACRA    (13933): 	at androidx.leanback.widget.FocusHighlightHelper$FocusAnimator.animateFocus(FocusHighlightHelper.java:74)
12-05 17:59:04.955 E/ACRA    (13933): 	at androidx.leanback.widget.FocusHighlightHelper$BrowseItemFocusHighlight.onItemFocused(FocusHighlightHelper.java:169)
12-05 17:59:04.955 E/ACRA    (13933): 	at androidx.leanback.widget.ItemBridgeAdapter$ChainingFocusChangeListener.onFocusChange(ItemBridgeAdapter.java:103)
12-05 17:59:04.955 E/ACRA    (13933): 	at android.view.View.onFocusChanged(View.java:8109)
12-05 17:59:04.955 E/ACRA    (13933): 	at android.view.View.clearFocusInternal(View.java:7946)
12-05 17:59:04.955 E/ACRA    (13933): 	at android.view.View.unFocus(View.java:7979)
12-05 17:59:04.955 E/ACRA    (13933): 	at android.view.ViewGroup.unFocus(ViewGroup.java:1203)
12-05 17:59:04.955 E/ACRA    (13933): 	at android.view.ViewGroup.unFocus(ViewGroup.java:1205)
12-05 17:59:04.955 E/ACRA    (13933): 	at android.view.ViewGroup.unFocus(ViewGroup.java:1205)
12-05 17:59:04.955 E/ACRA    (13933): 	at android.view.ViewGroup.unFocus(ViewGroup.java:1205)
12-05 17:59:04.955 E/ACRA    (13933): 	at android.view.ViewGroup.requestChildFocus(ViewGroup.java:863)
12-05 17:59:04.955 E/ACRA    (13933): 	at android.view.ViewGroup.requestChildFocus(ViewGroup.java:869)
12-05 17:59:04.955 E/ACRA    (13933): 	at android.view.View.handleFocusGainInternal(View.java:7771)
12-05 17:59:04.955 E/ACRA    (13933): 	at android.view.View.requestFocusNoSearch(View.java:13540)
12-05 17:59:04.955 E/ACRA    (13933): 	at android.view.View.requestFocus(View.java:13514)
12-05 17:59:04.955 E/ACRA    (13933): 	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3374)
12-05 17:59:04.955 E/ACRA    (13933): 	at android.view.ViewGroup.requestFocus(ViewGroup.java:3323)
12-05 17:59:04.955 E/ACRA    (13933): 	at android.view.View.requestFocus(View.java:13481)
12-05 17:59:04.955 E/ACRA    (13933): 	at android.view.View.requestFocus(View.java:13423)
12-05 17:59:04.955 E/ACRA    (13933): 	at org.jellyfin.androidtv.ui.browsing.BrowseGridFragment.lambda$refreshCurrentItem$3$org-jellyfin-androidtv-ui-browsing-BrowseGridFragment(BrowseGridFragment.java:888)
12-05 17:59:04.955 E/ACRA    (13933): 	at org.jellyfin.androidtv.ui.browsing.BrowseGridFragment$$ExternalSyntheticLambda2.invoke(D8$$SyntheticClass:0)
12-05 17:59:04.955 E/ACRA    (13933): 	at org.jellyfin.androidtv.ui.itemhandling.ItemRowAdapterHelperKt$refreshItem$2.invokeSuspend(ItemRowAdapterHelper.kt:697)
12-05 17:59:04.955 E/ACRA    (13933): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-05 17:59:04.955 E/ACRA    (13933): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
12-05 17:59:04.955 E/ACRA    (13933): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
12-05 17:59:04.955 E/ACRA    (13933): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
12-05 17:59:04.955 E/ACRA    (13933): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
12-05 17:59:04.955 E/ACRA    (13933): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
12-05 17:59:04.955 E/ACRA    (13933): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
12-05 17:59:04.955 E/ACRA    (13933): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
12-05 17:59:04.955 E/ACRA    (13933): 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5d88ea2, Dispatchers.IO]
12-05 17:59:04.956 D/ACRA    (13933): Building report
12-05 17:59:04.956 D/ACRA    (13933): Starting collectors with priority FIRST
12-05 17:59:04.957 D/ACRA    (13933): Calling collector org.acra.collector.DropBoxCollector
12-05 17:59:04.957 D/ACRA    (13933): Calling collector org.acra.collector.LogCatCollector
12-05 17:59:04.957 D/ACRA    (13933): Calling collector org.acra.collector.StacktraceCollector
12-05 17:59:04.957 D/ACRA    (13933): Collector org.acra.collector.DropBoxCollector completed
12-05 17:59:04.957 D/ACRA    (13933): Collector org.acra.collector.StacktraceCollector completed
12-05 17:59:04.962 D/ACRA    (13933): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.18.1` (`180199`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"PH1M_WW_9972","BOOTLOADER":"01.01.241016","BRAND":"Philips","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"PH1M_WW_9972","DISPLAY":"STT2.230831.001","FINGERPRINT":"Philips\/PH1M_WW_9972_21\/PH1M_WW_9972:12\/STT2.230831.001\/20736:user\/release-keys","HARDWARE":"mt5896","HOST":"TWTPSA392-ub1804","ID":"STT2.230831.001","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"TPV","MODEL":"Philips Google TV TA2","ODM_SKU":"unknown","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"PH1M_WW_9972_21","RADIO":"unknown","SKU":"unknown","SOC_MANUFACTURER":"Mediatek","SOC_MODEL":"t50","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1729068575000,"TYPE":"user","UNKNOWN":"unknown","USER":"jenkins","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"20736","MEDIA_PERFORMANCE_CLASS":0,"PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"12","RELEASE_OR_CODENAME":"12","SDK":"31","SDK_INT":31,"SECURITY_PATCH":"2024-09-05"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":180199,"VERSION_NAME":"0.18.1"}
```  

### Device information

***Android version***: `12`  
***Device brand***: `Philips`  
***Device product***: `PH1M_WW_9972_21`  
***Device model***: `Philips Google TV TA2`  

### Crash information

***Start time***: `2024-12-05T17:58:35.051+01:00`  
***Crash time***: `2024-12-05T17:59:05.433+01:00`  

### Application version

0.18.1

### Where did you install the app from?

Sideloaded APK

### Device information

philips 77oled908

### Android version

Android 12

### Jellyfin server version

10.10.3

**Comment by nielsvanvelzen** [comment]
Fixed for 10.8.2!
