### ISSUE TITLE
App stoped working without me changing anything

### ISSUE THREAD

**Issue by QBallDuke** [jellyfin/jellyfin-androidtv#4289]
### Describe the bug

Hi , this is my first bug report i hope im at the right place here and sry for my bad english. I cant start the app anymore as soon as i try to connect to my server it crashes and i cant figure out why it worked the most time but since a view days it stopped working wich is a shame . i realy love jellyfin and i hope you can fix this ot tell me how i can fix it . on play store there is no newer version available . on my oter devices my jellyfin server works . browsers pc and an evern older TV no problem . 

### Logs

---
client: Jellyfin for Android TV
client_version: 0.18.2
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
org.jellyfin.sdk.api.client.exception.InvalidContentException: Deserialization failed
	at org.jellyfin.sdk.api.operations.UserViewsApi.getUserViews(UserViewsApi.kt:113)
	at org.jellyfin.sdk.api.operations.UserViewsApi$getUserViews$1.invokeSuspend(Unknown Source:18)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b816be8, Dispatchers.IO]
Caused by: kotlinx.serialization.MissingFieldException: Field 'ItemId' is required for type with serial name 'org.jellyfin.sdk.model.api.UserItemDataDto', but it was missing at path: $.Items[0].UserData
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:95)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:78)
	at org.jellyfin.sdk.model.api.BaseItemDto$$serializer.deserialize(BaseItemDto.kt:33)
	at org.jellyfin.sdk.model.api.BaseItemDto$$serializer.deserialize(BaseItemDto.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:538)
	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
	at org.jellyfin.sdk.model.api.BaseItemDtoQueryResult$$serializer.deserialize(BaseItemDtoQueryResult.kt:16)
	at org.jellyfin.sdk.model.api.BaseItemDtoQueryResult$$serializer.deserialize(BaseItemDtoQueryResult.kt:16)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:165)
	at org.jellyfin.sdk.api.operations.UserViewsApi.getUserViews(UserViewsApi.kt:109)
	... 9 more
Caused by: kotlinx.serialization.MissingFieldException: Field 'ItemId' is required for type with serial name 'org.jellyfin.sdk.model.api.UserItemDataDto', but it was missing
	at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
	at org.jellyfin.sdk.model.api.UserItemDataDto.<init>(UserItemDataDto.kt:29)
	at org.jellyfin.sdk.model.api.UserItemDataDto$$serializer.deserialize(UserItemDataDto.kt:29)
	at org.jellyfin.sdk.model.api.UserItemDataDto$$serializer.deserialize(UserItemDataDto.kt:29)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	... 31 more

```  
***Logcat***: 
```log
12-12 18:26:14.045 E/AndroidRuntime(20142): Process: org.jellyfin.androidtv, PID: 20142
12-12 18:26:14.045 E/AndroidRuntime(20142): org.jellyfin.sdk.api.client.exception.InvalidContentException: Deserialization failed
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at org.jellyfin.sdk.api.operations.UserViewsApi.getUserViews(UserViewsApi.kt:113)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at org.jellyfin.sdk.api.operations.UserViewsApi$getUserViews$1.invokeSuspend(Unknown Source:18)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
12-12 18:26:14.045 E/AndroidRuntime(20142): Caused by: kotlinx.serialization.MissingFieldException: Field 'ItemId' is required for type with serial name 'org.jellyfin.sdk.model.api.UserItemDataDto', but it was missing at path: $.Items[0].UserData
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:95)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:78)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at org.jellyfin.sdk.model.api.BaseItemDto$$serializer.deserialize(BaseItemDto.kt:33)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at org.jellyfin.sdk.model.api.BaseItemDto$$serializer.deserialize(BaseItemDto.kt:33)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:538)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at org.jellyfin.sdk.model.api.BaseItemDtoQueryResult$$serializer.deserialize(BaseItemDtoQueryResult.kt:16)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at org.jellyfin.sdk.model.api.BaseItemDtoQueryResult$$serializer.deserialize(BaseItemDtoQueryResult.kt:16)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:165)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at org.jellyfin.sdk.api.operations.UserViewsApi.getUserViews(UserViewsApi.kt:109)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	... 9 more
12-12 18:26:14.045 E/AndroidRuntime(20142): Caused by: kotlinx.serialization.MissingFieldException: Field 'ItemId' is required for type with serial name 'org.jellyfin.sdk.model.api.UserItemDataDto', but it was missing
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
12-12 18:26:14.045 E/AndroidRuntime(20142): 	at org.jellyfin.sdk.model.api.UserItemDataDto.<init>(UserItemDataDto.kt:29)
12-12 18:26:14.046 E/AndroidRuntime(20142): 	at org.jellyfin.sdk.model.api.UserItemDataDto$$serializer.deserialize(UserItemDataDto.kt:29)
12-12 18:26:14.046 E/AndroidRuntime(20142): 	at org.jellyfin.sdk.model.api.UserItemDataDto$$serializer.deserialize(UserItemDataDto.kt:29)
12-12 18:26:14.046 E/AndroidRuntime(20142): 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
12-12 18:26:14.046 E/AndroidRuntime(20142): 	... 31 more
12-12 18:26:14.054 E/ACRA    (20142): ACRA caught a InvalidContentException for org.jellyfin.androidtv
12-12 18:26:14.054 E/ACRA    (20142): org.jellyfin.sdk.api.client.exception.InvalidContentException: Deserialization failed
12-12 18:26:14.054 E/ACRA    (20142): 	at org.jellyfin.sdk.api.operations.UserViewsApi.getUserViews(UserViewsApi.kt:113)
12-12 18:26:14.054 E/ACRA    (20142): 	at org.jellyfin.sdk.api.operations.UserViewsApi$getUserViews$1.invokeSuspend(Unknown Source:18)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
12-12 18:26:14.054 E/ACRA    (20142): 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b816be8, Dispatchers.IO]
12-12 18:26:14.054 E/ACRA    (20142): Caused by: kotlinx.serialization.MissingFieldException: Field 'ItemId' is required for type with serial name 'org.jellyfin.sdk.model.api.UserItemDataDto', but it was missing at path: $.Items[0].UserData
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:95)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:78)
12-12 18:26:14.054 E/ACRA    (20142): 	at org.jellyfin.sdk.model.api.BaseItemDto$$serializer.deserialize(BaseItemDto.kt:33)
12-12 18:26:14.054 E/ACRA    (20142): 	at org.jellyfin.sdk.model.api.BaseItemDto$$serializer.deserialize(BaseItemDto.kt:33)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:538)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
12-12 18:26:14.054 E/ACRA    (20142): 	at org.jellyfin.sdk.model.api.BaseItemDtoQueryResult$$serializer.deserialize(BaseItemDtoQueryResult.kt:16)
12-12 18:26:14.054 E/ACRA    (20142): 	at org.jellyfin.sdk.model.api.BaseItemDtoQueryResult$$serializer.deserialize(BaseItemDtoQueryResult.kt:16)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:165)
12-12 18:26:14.054 E/ACRA    (20142): 	at org.jellyfin.sdk.api.operations.UserViewsApi.getUserViews(UserViewsApi.kt:109)
12-12 18:26:14.054 E/ACRA    (20142): 	... 9 more
12-12 18:26:14.054 E/ACRA    (20142): Caused by: kotlinx.serialization.MissingFieldException: Field 'ItemId' is required for type with serial name 'org.jellyfin.sdk.model.api.UserItemDataDto', but it was missing
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
12-12 18:26:14.054 E/ACRA    (20142): 	at org.jellyfin.sdk.model.api.UserItemDataDto.<init>(UserItemDataDto.kt:29)
12-12 18:26:14.054 E/ACRA    (20142): 	at org.jellyfin.sdk.model.api.UserItemDataDto$$serializer.deserialize(UserItemDataDto.kt:29)
12-12 18:26:14.054 E/ACRA    (20142): 	at org.jellyfin.sdk.model.api.UserItemDataDto$$serializer.deserialize(UserItemDataDto.kt:29)
12-12 18:26:14.054 E/ACRA    (20142): 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
12-12 18:26:14.054 E/ACRA    (20142): 	... 31 more
12-12 18:26:14.054 D/ACRA    (20142): Building report
12-12 18:26:14.059 D/ACRA    (20142): Starting collectors with priority FIRST
12-12 18:26:14.060 D/ACRA    (20142): Calling collector org.acra.collector.DropBoxCollector
12-12 18:26:14.060 D/ACRA    (20142): Collector org.acra.collector.DropBoxCollector completed
12-12 18:26:14.064 D/ACRA    (20142): Calling collector org.acra.collector.LogCatCollector
12-12 18:26:14.065 D/ACRA    (20142): Calling collector org.acra.collector.StacktraceCollector
12-12 18:26:14.067 D/mali_winsys(20142): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
12-12 18:26:14.068 D/ACRA    (20142): Collector org.acra.collector.StacktraceCollector completed
12-12 18:26:14.080 D/ACRA    (20142): Retrieving logcat output (buffer:default)...
12-12 18:26:14.097 E/libc    (20248): Access denied finding property "persist.mtk.mlog2logcat"

```  

### App information

***App version***: `0.18.2` (`180299`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"BRAVIA_ATV2","BOOTLOADER":"unknown","BRAND":"Sony","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"BRAVIA_ATV2","DISPLAY":"BRAVIA_ATV2_EU-user 8.0.0 OPR2.170623.027.S30 665451 release-keys","FINGERPRINT":"Sony\/BRAVIA_ATV2_EU\/BRAVIA_ATV2:8.0.0\/OPR2.170623.027.S30\/665451:user\/release-keys","HARDWARE":"mt5891","HOST":"BuildHost672","ID":"OPR2.170623.027.S30","IS_CONTAINER":false,"IS_DEBUGGABLE":false,"IS_EMULATOR":false,"IS_ENG":false,"IS_TREBLE_ENABLED":false,"IS_USER":true,"IS_USERDEBUG":false,"MANUFACTURER":"Sony","MODEL":"BRAVIA 4K GB","PERMISSIONS_REVIEW_REQUIRED":false,"PRODUCT":"BRAVIA_ATV2_EU","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1573101926000,"TYPE":"user","UNKNOWN":"unknown","USER":"root","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"665451","PREVIEW_SDK_INT":0,"RELEASE":"8.0.0","RESOURCES_SDK_INT":26,"SDK":"26","SDK_INT":26,"SECURITY_PATCH":"2019-09-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":180299,"VERSION_NAME":"0.18.2"}
```  

### Device information

***Android version***: `8.0.0`  
***Device brand***: `Sony`  
***Device product***: `BRAVIA_ATV2_EU`  
***Device model***: `BRAVIA 4K GB`  

### Crash information

***Start time***: `2024-12-12T18:26:10.548+01:00`  
***Crash time***: `2024-12-12T18:26:14.234+01:00`  

### Application version

0.18.2

### Where did you install the app from?

Google Play

### Device information

BRAVIA_ATV2_EU

### Android version

8

### Jellyfin server version

10.10.0

**Comment by nielsvanvelzen** [comment]
Those errors indicate invalid responses from your server. Try updating your server to the latest 10.10.3 release and see if that fixes the issue. If that doesn't fix the issue please list the installed plugins as my best guess is that a third-party plugin is sending invalid data.

**Comment by QBallDuke** [comment]
Oh boy i did an update and it did overwrite just everything^^ .  i just did not asume that there could be any reason of overwriting existing configs .... well i gues i start from scratch ..... i realy wish for an update button instead of installing over . iv i get more in to the software i mabee can help improving it  .

**Comment by BotBlake** [comment]
@QBallDuke Based on your Thumbsup, I assume upgrading the Server Version fixed the issue for you.
Is this issue still valid or can it be closed?

Kind regards

**Comment by SwedishGojira** [comment]
I have exactly the same issue. The app stop working randomly, sometimes after a few hours, other times after a few days. I open the app and then it will close itself after a few seconds with error popup "Oops! Something went wrong...".

Clearing cache and data of app does not help. Only solution is to uninstall the app and then install it again.

I also have a Sony bravia TV, same as the reporting user.

My server is at 10.10.3 and I have the latest beta version of the app from the play store.

I never get any crashlogs uploaded to my server.

No problems logging in from android app on my phone, or via webpage.

**Comment by jinglebiscuits** [comment]
The issue described by @SwedishGojira is not the same as the issue described by @QBallDuke. This is safe to close imo.

**Comment by BotBlake** [comment]
@SwedishGojira 
Please open a new issue if your issue persists.
Make sure to include logs and other important info that the template asks for.

Kind regards.
