### ISSUE TITLE
Media Playback Suddenly Stop

### ISSUE THREAD

**Issue by dverzolla** [jellyfin/jellyfin-androidtv#4331]
### Describe the bug

Some few medias suddenly stops the playbay.
In some specific time, it's not randomly.

### Logs

---
client: Jellyfin for Android TV
client_version: 0.18.2
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.NullPointerException: Parameter specified as non-null is null: method org.jellyfin.androidtv.util.apiclient.ReportingHelper.reportProgress, parameter streamInfo
	at org.jellyfin.androidtv.util.apiclient.ReportingHelper.reportProgress(Unknown Source:18)
	at org.jellyfin.androidtv.ui.playback.PlaybackController.startPauseReportLoop(PlaybackController.java:1026)
	at org.jellyfin.androidtv.ui.playback.PlaybackController.pause(PlaybackController.java:759)
	at org.jellyfin.androidtv.ui.playback.overlay.VideoPlayerAdapter.pause(VideoPlayerAdapter.java:35)
	at org.jellyfin.androidtv.ui.playback.overlay.action.PlayPauseAction.onActionClicked(PlayPauseAction.kt:17)
	at org.jellyfin.androidtv.ui.playback.overlay.CustomPlaybackTransportControlGlue.onActionClicked(CustomPlaybackTransportControlGlue.java:284)
	at org.jellyfin.androidtv.ui.playback.overlay.CustomPlaybackFragmentGlueHost.setOnActionClickedListener$lambda$0(CustomPlaybackFragmentGlueHost.kt:21)
	at org.jellyfin.androidtv.ui.playback.overlay.CustomPlaybackFragmentGlueHost.$r8$lambda$7oEez3ihslTtgCa1PUIlwNS-lsM(Unknown Source:0)
	at org.jellyfin.androidtv.ui.playback.overlay.CustomPlaybackFragmentGlueHost$$ExternalSyntheticLambda0.onItemClicked(D8$$SyntheticClass:0)
	at androidx.leanback.app.PlaybackSupportFragment$1.onItemClicked(PlaybackSupportFragment.java:175)
	at androidx.leanback.widget.PlaybackTransportRowPresenter$2.onControlClicked(PlaybackTransportRowPresenter.java:575)
	at androidx.leanback.widget.ControlBarPresenter$ViewHolder$3.onClick(ControlBarPresenter.java:164)
	at android.view.View.performClick(View.java:6597)
	at android.view.View.performClickInternal(View.java:6574)
	at android.view.View.onKeyUp(View.java:13216)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2734)
	at android.view.View.dispatchKeyEvent(View.java:12450)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
	at androidx.leanback.widget.PlaybackTransportRowView.dispatchKeyEvent(PlaybackTransportRowView.java:71)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
	at androidx.leanback.widget.BaseGridView.dispatchKeyEvent(BaseGridView.java:1081)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:428)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1820)
	at android.app.Activity.dispatchKeyEvent(Activity.java:3361)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.kt:103)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.kt:117)
	at org.jellyfin.androidtv.ui.browsing.MainActivity.dispatchKeyEvent(MainActivity.kt:176)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:342)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5061)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4929)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4450)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4503)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4469)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4609)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4477)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4666)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4450)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4503)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4469)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4477)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4450)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4503)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4469)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4642)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4803)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2571)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2081)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2072)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2548)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:326)
	at android.os.Looper.loop(Looper.java:160)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```  
***Logcat***: 
```log
12-21 19:20:13.660 E/AndroidRuntime( 9593): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4642)
12-21 19:20:13.660 E/AndroidRuntime( 9593): 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4803)
12-21 19:20:13.660 E/AndroidRuntime( 9593): 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2571)
12-21 19:20:13.660 E/AndroidRuntime( 9593): 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2081)
12-21 19:20:13.660 E/AndroidRuntime( 9593): 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2072)
12-21 19:20:13.660 E/AndroidRuntime( 9593): 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2548)
12-21 19:20:13.660 E/AndroidRuntime( 9593): 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
12-21 19:20:13.660 E/AndroidRuntime( 9593): 	at android.os.MessageQueue.nativePollOnce(Native Method)
12-21 19:20:13.660 E/AndroidRuntime( 9593): 	at android.os.MessageQueue.next(MessageQueue.java:326)
12-21 19:20:13.660 E/AndroidRuntime( 9593): 	at android.os.Looper.loop(Looper.java:160)
12-21 19:20:13.660 E/AndroidRuntime( 9593): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
12-21 19:20:13.660 E/AndroidRuntime( 9593): 	at java.lang.reflect.Method.invoke(Native Method)
12-21 19:20:13.660 E/AndroidRuntime( 9593): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-21 19:20:13.660 E/AndroidRuntime( 9593): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
12-21 19:20:13.665 E/ACRA    ( 9593): ACRA caught a NullPointerException for org.jellyfin.androidtv
12-21 19:20:13.665 E/ACRA    ( 9593): java.lang.NullPointerException: Parameter specified as non-null is null: method org.jellyfin.androidtv.util.apiclient.ReportingHelper.reportProgress, parameter streamInfo
12-21 19:20:13.665 E/ACRA    ( 9593): 	at org.jellyfin.androidtv.util.apiclient.ReportingHelper.reportProgress(Unknown Source:18)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at org.jellyfin.androidtv.ui.playback.PlaybackController.startPauseReportLoop(PlaybackController.java:1026)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at org.jellyfin.androidtv.ui.playback.PlaybackController.pause(PlaybackController.java:759)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at org.jellyfin.androidtv.ui.playback.overlay.VideoPlayerAdapter.pause(VideoPlayerAdapter.java:35)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at org.jellyfin.androidtv.ui.playback.overlay.action.PlayPauseAction.onActionClicked(PlayPauseAction.kt:17)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at org.jellyfin.androidtv.ui.playback.overlay.CustomPlaybackTransportControlGlue.onActionClicked(CustomPlaybackTransportControlGlue.java:284)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at org.jellyfin.androidtv.ui.playback.overlay.CustomPlaybackFragmentGlueHost.setOnActionClickedListener$lambda$0(CustomPlaybackFragmentGlueHost.kt:21)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at org.jellyfin.androidtv.ui.playback.overlay.CustomPlaybackFragmentGlueHost.$r8$lambda$7oEez3ihslTtgCa1PUIlwNS-lsM(Unknown Source:0)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at org.jellyfin.androidtv.ui.playback.overlay.CustomPlaybackFragmentGlueHost$$ExternalSyntheticLambda0.onItemClicked(D8$$SyntheticClass:0)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at androidx.leanback.app.PlaybackSupportFragment$1.onItemClicked(PlaybackSupportFragment.java:175)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at androidx.leanback.widget.PlaybackTransportRowPresenter$2.onControlClicked(PlaybackTransportRowPresenter.java:575)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at androidx.leanback.widget.ControlBarPresenter$ViewHolder$3.onClick(ControlBarPresenter.java:164)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.View.performClick(View.java:6597)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.View.performClickInternal(View.java:6574)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.View.onKeyUp(View.java:13216)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.KeyEvent.dispatch(KeyEvent.java:2734)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.View.dispatchKeyEvent(View.java:12450)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at androidx.leanback.widget.PlaybackTransportRowView.dispatchKeyEvent(PlaybackTransportRowView.java:71)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at androidx.leanback.widget.BaseGridView.dispatchKeyEvent(BaseGridView.java:1081)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:428)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1820)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.app.Activity.dispatchKeyEvent(Activity.java:3361)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.kt:103)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.kt:117)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at org.jellyfin.androidtv.ui.browsing.MainActivity.dispatchKeyEvent(MainActivity.kt:176)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:342)
12-21 19:20:13.665 E/ACRA    ( 9593): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5061)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4929)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4450)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4503)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4469)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4609)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4477)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4666)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4450)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4503)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4469)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4477)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4450)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4503)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4469)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4642)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4803)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2571)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2081)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2072)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2548)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.os.MessageQueue.nativePollOnce(Native Method)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.os.MessageQueue.next(MessageQueue.java:326)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.os.Looper.loop(Looper.java:160)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at java.lang.reflect.Method.invoke(Native Method)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-21 19:20:13.666 E/ACRA    ( 9593): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
12-21 19:20:13.667 D/ACRA    ( 9593): Building report
12-21 19:20:13.672 D/ACRA    ( 9593): Starting collectors with priority FIRST
12-21 19:20:13.673 D/ACRA    ( 9593): Calling collector org.acra.collector.DropBoxCollector
12-21 19:20:13.674 D/ACRA    ( 9593): Calling collector org.acra.collector.LogCatCollector
12-21 19:20:13.674 D/ACRA    ( 9593): Collector org.acra.collector.DropBoxCollector completed
12-21 19:20:13.675 D/ACRA    ( 9593): Calling collector org.acra.collector.StacktraceCollector
12-21 19:20:13.677 D/ACRA    ( 9593): Collector org.acra.collector.StacktraceCollector completed
12-21 19:20:13.683 D/ACRA    ( 9593): Retrieving logcat output (buffer:default)...
12-21 19:20:13.742 E/libc    (11704): Access denied finding property "persist.svp.dbg.loglevel"

```  

### App information

***App version***: `0.18.2` (`180299`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"BRAVIA_ATV2","BOOTLOADER":"unknown","BRAND":"Sony","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"BRAVIA_ATV2","DISPLAY":"BRAVIA_ATV2_BR-user 9 PTT1.190515.001.S54 672201 release-keys","FINGERPRINT":"Sony\/BRAVIA_ATV2_BR\/BRAVIA_ATV2:9\/PTT1.190515.001.S54\/672201:user\/release-keys","HARDWARE":"mt5891","HOST":"BuildHost619","ID":"PTT1.190515.001.S54","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Sony","MODEL":"BRAVIA 4K GB","PERMISSIONS_REVIEW_REQUIRED":false,"PRODUCT":"BRAVIA_ATV2_BR","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1690249860000,"TYPE":"user","UNKNOWN":"unknown","USER":"root","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","FIRST_SDK_INT":24,"INCREMENTAL":"672201","PREVIEW_SDK_INT":0,"RELEASE":"9","RESOURCES_SDK_INT":28,"SDK":"28","SDK_INT":28,"SECURITY_PATCH":"2022-01-05"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":180299,"VERSION_NAME":"0.18.2"}
```  

### Device information

***Android version***: `9`  
***Device brand***: `Sony`  
***Device product***: `BRAVIA_ATV2_BR`  
***Device model***: `BRAVIA 4K GB`  

### Crash information

***Start time***: `2024-12-21T19:16:57.538-03:00`  
***Crash time***: `2024-12-21T19:20:13.798-03:00`  

### FFmpeg logs

```shell
size=N/A time=01:13:05.86 bitrate=N/A speed=18.5x
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f561.mp4' for writing
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f562.mp4' for writing
size=N/A time=01:13:27.13 bitrate=N/A speed=18.5x
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f563.mp4' for writing
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f564.mp4' for writing
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f565.mp4' for writing
size=N/A time=01:13:49.43 bitrate=N/A speed=18.6x
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f566.mp4' for writing
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f567.mp4' for writing
size=N/A time=01:14:04.00 bitrate=N/A speed=18.6x
size=N/A time=01:14:04.00 bitrate=N/A speed=18.6x
size=N/A time=01:14:04.93 bitrate=N/A speed=18.5x
size=N/A time=01:14:11.60 bitrate=N/A speed=18.5x
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f568.mp4' for writing
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f569.mp4' for writing
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f570.mp4' for writing
size=N/A time=01:14:32.46 bitrate=N/A speed=18.6x
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f571.mp4' for writing
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f572.mp4' for writing
size=N/A time=01:14:51.10 bitrate=N/A speed=18.6x
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f573.mp4' for writing
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f574.mp4' for writing
size=N/A time=01:15:02.13 bitrate=N/A speed=18.6x
size=N/A time=01:15:02.13 bitrate=N/A speed=18.6x
size=N/A time=01:15:02.13 bitrate=N/A speed=18.5x
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f575.mp4' for writing
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f576.mp4' for writing
size=N/A time=01:15:22.36 bitrate=N/A speed=18.6x
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f577.mp4' for writing
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f578.mp4' for writing
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f579.mp4' for writing
size=N/A time=01:15:44.80 bitrate=N/A speed=18.6x
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f580.mp4' for writing
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f581.mp4' for writing
size=N/A time=01:16:00.56 bitrate=N/A speed=18.7x
size=N/A time=01:16:01.33 bitrate=N/A speed=18.6x
size=N/A time=01:16:01.33 bitrate=N/A speed=18.6x
size=N/A time=01:16:01.33 bitrate=N/A speed=18.6x
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f582.mp4' for writing
size=N/A time=01:16:10.46 bitrate=N/A speed=18.6x
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f583.mp4' for writing
[hls @ 0x8352f0] Opening '/var/lib/jellyfin/transcodes/055cf54542b4c74cd198926902915a3f584.mp4' for writing
[out#0/hls @ 0x834e70] video:1448487KiB audio:124340KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
size=N/A time=01:16:17.60 bitrate=N/A speed=18.5x
Exiting normally, received signal 15.
```

### Media info of the file

```shell
ffprobe version 7.0.2-Jellyfin Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=armhf --cross-prefix=/usr/bin/arm-linux-gnueabihf- --toolchain=hardened --enable-cross-compile --enable-rkmpp --enable-rkrga
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Input #0, matroska,webm, from '/home/jellyfin/Movies/file.mkv':
  Metadata:
    encoder         : TMPGEnc Video Mastering Works 7 Version 7.0.30.33
    creation_time   : 2024-12-20T05:47:47.755000Z
  Duration: 01:51:56.57, start: 0.000000, bitrate: 2796 kb/s
  Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 1k tbn (default)
  Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp (default)
```

### Application version

0.18.2

### Device information

SONY BRAVIA 4K GB

### Android version

Android 9

### Jellyfin server version

Jellyfin.Server 10.10.3.0

**Comment by nielsvanvelzen** [comment]
Thanks for the report, should be fixed in next update.

**Comment by dverzolla** [comment]
Could you explain what happens ? Thanks

**Comment by nielsvanvelzen** [comment]
The app crashed because of an invalid state when it tried to peacefully stop playback
