### ISSUE TITLE
Video player crashes when using Emerald theme

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-androidtv#629]
**Describe the bug**
The app crashes when trying to play video with the Emerald theme

**To Reproduce**

1. Set theme to Emerald
2. Try to play a video
3. See error

**Expected behavior**
The app should not crash.

**Logs**
```
Process: org.jellyfin.androidtv.debug, PID: 4024
    android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:237)
        at android.content.res.Resources.getColor(Resources.java:982)
        at android.content.res.Resources.getColor(Resources.java:958)
        at androidx.leanback.widget.PlaybackTransportRowPresenter.getDefaultProgressColor(PlaybackTransportRowPresenter.java:669)
        at androidx.leanback.widget.PlaybackTransportRowPresenter.initRow(PlaybackTransportRowPresenter.java:697)
        at androidx.leanback.widget.PlaybackTransportRowPresenter.createRowViewHolder(PlaybackTransportRowPresenter.java:689)
        at org.jellyfin.androidtv.ui.playback.overlay.CustomPlaybackTransportControlGlue$2.createRowViewHolder(CustomPlaybackTransportControlGlue.java:116)
        at androidx.leanback.widget.RowPresenter.onCreateViewHolder(RowPresenter.java:326)
        at androidx.leanback.widget.ItemBridgeAdapter.onCreateViewHolder(ItemBridgeAdapter.java:363)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.leanback.widget.GridLayoutManager.getViewForPosition(GridLayoutManager.java:1109)
        at androidx.leanback.widget.GridLayoutManager$2.createItem(GridLayoutManager.java:1632)
        at androidx.leanback.widget.SingleRow.appendVisibleItems(SingleRow.java:113)
        at androidx.leanback.widget.Grid.appendOneColumnVisibleItems(Grid.java:389)
        at androidx.leanback.widget.GridLayoutManager.appendOneColumnVisibleItems(GridLayoutManager.java:1856)
        at androidx.leanback.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:2286)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:21822)
        at android.view.ViewGroup.layout(ViewGroup.java:6236)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:329)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:267)
        at android.view.View.layout(View.java:21822)
        at android.view.ViewGroup.layout(ViewGroup.java:6236)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:329)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:267)
        at android.view.View.layout(View.java:21822)
        at android.view.ViewGroup.layout(ViewGroup.java:6236)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:329)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:267)
        at android.view.View.layout(View.java:21822)
        at android.view.ViewGroup.layout(ViewGroup.java:6236)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:329)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:267)
        at android.view.View.layout(View.java:21822)
        at android.view.ViewGroup.layout(ViewGroup.java:6236)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:329)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:267)
        at android.view.View.layout(View.java:21822)
        at android.view.ViewGroup.layout(ViewGroup.java:6236)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1821)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1665)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1574)
        at android.view.View.layout(View.java:21822)
        at android.view.ViewGroup.layout(ViewGroup.java:6236)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:329)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:267)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
        at android.view.View.layout(View.java:21822)
2020-11-14 16:59:59.012 4024-4024/org.jellyfin.androidtv.debug E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:6236)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3067)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2581)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1704)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7516)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:726)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:966)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7021)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
2020-11-14 16:59:59.013 4024-4024/org.jellyfin.androidtv.debug E/ACRA: ACRA caught a NotFoundException for org.jellyfin.androidtv.debug
    android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:237)
        at android.content.res.Resources.getColor(Resources.java:982)
        at android.content.res.Resources.getColor(Resources.java:958)
        at androidx.leanback.widget.PlaybackTransportRowPresenter.getDefaultProgressColor(PlaybackTransportRowPresenter.java:669)
        at androidx.leanback.widget.PlaybackTransportRowPresenter.initRow(PlaybackTransportRowPresenter.java:697)
        at androidx.leanback.widget.PlaybackTransportRowPresenter.createRowViewHolder(PlaybackTransportRowPresenter.java:689)
        at org.jellyfin.androidtv.ui.playback.overlay.CustomPlaybackTransportControlGlue$2.createRowViewHolder(CustomPlaybackTransportControlGlue.java:116)
        at androidx.leanback.widget.RowPresenter.onCreateViewHolder(RowPresenter.java:326)
        at androidx.leanback.widget.ItemBridgeAdapter.onCreateViewHolder(ItemBridgeAdapter.java:363)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.leanback.widget.GridLayoutManager.getViewForPosition(GridLayoutManager.java:1109)
        at androidx.leanback.widget.GridLayoutManager$2.createItem(GridLayoutManager.java:1632)
        at androidx.leanback.widget.SingleRow.appendVisibleItems(SingleRow.java:113)
        at androidx.leanback.widget.Grid.appendOneColumnVisibleItems(Grid.java:389)
        at androidx.leanback.widget.GridLayoutManager.appendOneColumnVisibleItems(GridLayoutManager.java:1856)
        at androidx.leanback.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:2286)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:21822)
        at android.view.ViewGroup.layout(ViewGroup.java:6236)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:329)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:267)
        at android.view.View.layout(View.java:21822)
        at android.view.ViewGroup.layout(ViewGroup.java:6236)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:329)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:267)
        at android.view.View.layout(View.java:21822)
        at android.view.ViewGroup.layout(ViewGroup.java:6236)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:329)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:267)
        at android.view.View.layout(View.java:21822)
        at android.view.ViewGroup.layout(ViewGroup.java:6236)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:329)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:267)
        at android.view.View.layout(View.java:21822)
        at android.view.ViewGroup.layout(ViewGroup.java:6236)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:329)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:267)
        at android.view.View.layout(View.java:21822)
        at android.view.ViewGroup.layout(ViewGroup.java:6236)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1821)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1665)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1574)
        at android.view.View.layout(View.java:21822)
        at android.view.ViewGroup.layout(ViewGroup.java:6236)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:329)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:267)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
        at android.view.View.layout(View.java:21822)
2020-11-14 16:59:59.013 4024-4024/org.jellyfin.androidtv.debug E/ACRA:     at android.view.ViewGroup.layout(ViewGroup.java:6236)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3067)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2581)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1704)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7516)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:726)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:966)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7021)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
```

**System (please complete the following information):**
 - Android TV or Fire TV version: Android TV API Q in Emulator
 - Device manufacturer: Google
 - Device model: Google
 - Jellyfin server version: 1.33.7

**Additional context**
I'm not sure why this happens yet. Thanks to @MrChip53 for finding this issue.

**Comment by nielsvanvelzen** [comment]
Actually I think the issue is that the `colorAccent` item in the Emerald theme is using a hexadecimal color instead of a reference to a color resource. The leanback code doesn't support that because why would they support something obious?
After #401 is merged I'll move colors out of the themes files and use the references exclusively.

**Comment by MrChip53** [comment]
I'll may look into this a little bit also but on a side note with the emerald theme the background of the progress bar isnt transparent so you _may_ want to change that.

**Comment by MrChip53** [comment]
> Actually I think the issue is that the `colorAccent` item in the Emerald theme is using a hexadecimal color instead of a reference to a color resource. The leanback code doesn't support that because why would they support something obious?
> After #401 is merged I'll move colors out of the themes files and use the references exclusively.

Ah yes, did you actually test that? Because that is the issue. Or in hindsight was it obvious because the function was trying to get a resource color and not parse a color string.

**Comment by nielsvanvelzen** [comment]
A quick test by using another color with the reference notation fixed it for me yes
