### ISSUE TITLE
Playback breaks after a minute, breaks again after restart (FireTV, Docker)

### ISSUE THREAD

**Issue by totti4ever** [jellyfin/jellyfin-androidtv#643]
**Describe the bug**
Playback breaks after like 1 minute. Restarting playback is okay, but then it's breaking again after a minute

**System (please complete the following information):**
 - OS: Host is Ubuntu 18.04
 - Virtualization: Docker
 - Clients: FireTV 4k
 - Browser: Jellyfin app
 - Jellyfin Version: 10.6.4
 - Playback: Direct Play
 - Installed Plugins: none
 - Reverse Proxy: traefik
 - Base URL: none
 - Networking: ?
 - Storage: local

**To Reproduce**
Play episode

**Expected behavior**
no error

**Logs**
```
[21:31:08] [WRN] [18] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS ::ffff:172.16.0.10 error receiving data: The remote party closed the WebSocket connection without completing the close handshake.
[21:31:08] [INF] [18] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS ::ffff:172.16.0.10 closed
[21:31:08] [ERR] [17] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: The operation was canceled. URL: http://tv.home/Videos/c004b074eafcb041417c86f6b4a583e6/stream.mkv?DeviceId=d8dff4875dd17dbb&MediaSourceId=c004b074eafcb041417c86f6b4a583e6&Static=true&Tag=01f56d5d40a4fbe0072f8c3140631bd3
[21:31:08] [WRN] [17] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 206 to 192.168.192.197. Time (slow): 0:01:44.4826207. http://tv.home/Videos/c004b074eafcb041417c86f6b4a583e6/stream.mkv?DeviceId=d8dff4875dd17dbb&MediaSourceId=c004b074eafcb041417c86f6b4a583e6&Static=true&Tag=01f56d5d40a4fbe0072f8c3140631bd3
[21:31:11] [INF] [17] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS ::ffff:172.16.0.10 request
[21:31:11] [INF] [17] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS ::ffff:172.16.0.10 request
[21:31:12] [ERR] [16] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://tv.home/Items/2b2bca16aacc8a14d53a11bb829eafa5/Images/Primary?MaxHeight=300&EnableImageEnhancers=true
MediaBrowser.Common.Extensions.ResourceNotFoundException: Live TV does not have an image of type Primary
   at MediaBrowser.Api.Images.ImageService.GetImage(ImageRequest request, Guid itemId, BaseItem item, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

```
[21:35:22] [ERR] [18] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: The operation was canceled. URL: http://tv.home/Videos/c004b074eafcb041417c86f6b4a583e6/stream.mkv?DeviceId=d8dff4875dd17dbb&MediaSourceId=c004b074eafcb041417c86f6b4a583e6&Static=true&Tag=01f56d5d40a4fbe0072f8c3140631bd3
[21:35:22] [WRN] [18] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 206 to 192.168.192.197. Time (slow): 0:01:16.615702. http://tv.home/Videos/c004b074eafcb041417c86f6b4a583e6/stream.mkv?DeviceId=d8dff4875dd17dbb&MediaSourceId=c004b074eafcb041417c86f6b4a583e6&Static=true&Tag=01f56d5d40a4fbe0072f8c3140631bd3
[21:35:25] [INF] [19] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS ::ffff:172.16.0.10 request
[21:35:25] [INF] [11] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS ::ffff:172.16.0.10 request
[21:35:26] [ERR] [11] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://tv.home/Items/2b2bca16aacc8a14d53a11bb829eafa5/Images/Primary?MaxHeight=300&EnableImageEnhancers=true
MediaBrowser.Common.Extensions.ResourceNotFoundException: Live TV does not have an image of type Primary
   at MediaBrowser.Api.Images.ImageService.GetImage(ImageRequest request, Guid itemId, BaseItem item, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by totti4ever** [comment]
Okay, I managed to grab `logcat` from the FireTV:

```
11-27 20:57:54.144   610  6200 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=amzns://apps/android?p=org.jellyfin.androidtv flg=0x10000000 cmp=com.amazon.venezia/.pdi.AppLaunchActivity (has extras)} from uid 10113 on display 0
11-27 20:57:54.148   610 15024 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LEANBACK_LAUNCHER] flg=0x10000000 pkg=org.jellyfin.androidtv cmp=org.jellyfin.androidtv/.startup.StartupActivity (has extras)} from uid 1000 on display 0
11-27 20:57:54.204   610   898 I ActivityManager: Start proc 15025:org.jellyfin.androidtv/u0a165 for activity org.jellyfin.androidtv/.startup.StartupActivity
11-27 20:57:54.995   610   915 I ActivityManager: START u0 {flg=0x10000000 cmp=org.jellyfin.androidtv/org.acra.dialog.CrashReportDialog (has extras)} from uid 10165 on display 0
11-27 20:57:55.027   610  5576 I ActivityManager: Start proc 15065:org.jellyfin.androidtv:acra/u0a165 for activity org.jellyfin.androidtv/org.acra.dialog.CrashReportDialog
11-27 20:57:55.279   610   915 I ActivityManager: START u0 {cmp=org.jellyfin.androidtv/.startup.StartupActivity} from uid 10165 on display 0
11-27 20:57:55.614   610  6200 I ActivityManager: START u0 {cmp=org.jellyfin.androidtv/.browsing.MainActivity} from uid 10165 on display 0
11-27 20:57:55.620   610  6200 W ActivityManager: startActivity called from finishing ActivityRecord{37a16ec u0 org.jellyfin.androidtv/.startup.StartupActivity t1356 f}; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=org.jellyfin.androidtv/.browsing.MainActivity }
11-27 20:57:55.917   610  6200 W ActivityManager: Duplicate finish request for ActivityRecord{37a16ec u0 org.jellyfin.androidtv/.startup.StartupActivity t1356 f}
11-27 20:57:56.009   610  6200 I ActivityManager: START u0 {flg=0x10000000 cmp=org.jellyfin.androidtv/org.acra.dialog.CrashReportDialog (has extras)} from uid 10165 on display 0
11-27 20:57:56.091   610  6200 I WindowManager: WIN DEATH: Window{b59644d u0 org.jellyfin.androidtv/org.jellyfin.androidtv.startup.StartupActivity}
11-27 20:57:56.092   610  4186 I ActivityManager: Process org.jellyfin.androidtv (pid 15025) has died
11-27 20:57:56.098   610  2595 I WindowManager: WIN DEATH: Window{12f36c6 u0 org.jellyfin.androidtv/org.jellyfin.androidtv.startup.StartupActivity}
11-27 20:57:56.129   610  4186 I ActivityManager: START u0 {cmp=org.jellyfin.androidtv/.startup.StartupActivity} from uid 10165 on display 0
11-27 20:57:56.212   610  5576 I ActivityManager: Start proc 15119:org.jellyfin.androidtv/u0a165 for activity org.jellyfin.androidtv/.startup.StartupActivity
11-27 20:57:56.836   610  4186 I ActivityManager: START u0 {flg=0x10000000 cmp=org.jellyfin.androidtv/org.acra.dialog.CrashReportDialog (has extras)} from uid 10165 on display 0
11-27 20:57:56.885   610  4186 I ActivityManager: START u0 {cmp=org.jellyfin.androidtv/.startup.StartupActivity} from uid 10165 on display 0
11-27 20:57:57.074   610  6200 I ActivityManager: START u0 {cmp=org.jellyfin.androidtv/.browsing.MainActivity} from uid 10165 on display 0
11-27 20:58:18.616   610  3162 I ActivityManager: START u0 {cmp=org.jellyfin.androidtv/.details.FullDetailsActivity (has extras)} from uid 10165 on display 0
11-27 20:58:26.506   610  3162 I ActivityManager: START u0 {cmp=org.jellyfin.androidtv/.playback.PlaybackOverlayActivity (has extras)} from uid 10165 on display 0
11-27 20:59:10.921   610  4186 I ActivityManager: Process org.jellyfin.androidtv:acra (pid 15065) has died
11-27 20:59:42.222   610  5076 I WindowManager: WIN DEATH: Window{255117 u0 org.jellyfin.androidtv/org.jellyfin.androidtv.playback.PlaybackOverlayActivity}
11-27 20:59:42.227   610  3166 I ActivityManager: Process org.jellyfin.androidtv (pid 15119) has died
11-27 20:59:42.268   610  5076 W WindowManager: Force-removing child win Window{39f09b8 u0 SurfaceView - org.jellyfin.androidtv/org.jellyfin.androidtv.playback.PlaybackOverlayActivity} from container Window{255117 u0 org.jellyfin.androidtv/org.jellyfin.androidtv.playback.PlaybackOverlayActivity}
11-27 20:59:42.278   610  3166 W ActivityManager: Force removing ActivityRecord{a39c86c u0 org.jellyfin.androidtv/.playback.PlaybackOverlayActivity t1359}: app died, no saved state
11-27 20:59:42.437   610  5076 W WindowManager: Force-removing child win Window{bfd6391 u0 SurfaceView - org.jellyfin.androidtv/org.jellyfin.androidtv.playback.PlaybackOverlayActivity} from container Window{255117 u0 org.jellyfin.androidtv/org.jellyfin.androidtv.playback.PlaybackOverlayActivity}
11-27 20:59:42.455   610  3020 I WindowManager: WIN DEATH: Window{ae1027 u0 org.jellyfin.androidtv/org.jellyfin.androidtv.details.FullDetailsActivity}
11-27 20:59:42.460   610 15451 I WindowManager: WIN DEATH: Window{7905be3 u0 org.jellyfin.androidtv/org.jellyfin.androidtv.browsing.MainActivity}
11-27 20:59:42.514   610  3166 I ActivityManager: Start proc 15489:org.jellyfin.androidtv/u0a165 for activity org.jellyfin.androidtv/.details.FullDetailsActivity
11-27 20:59:43.605   610   850 I ActivityManager: START u0 {cmp=org.jellyfin.androidtv/.startup.StartupActivity} from uid 10165 on display 0
11-27 20:59:43.818   610   955 W ActivityManager: Duplicate finish request for ActivityRecord{1da1a4b u0 org.jellyfin.androidtv/.details.FullDetailsActivity t1359 f}
11-27 20:59:43.912   610 15468 I ActivityManager: Process org.jellyfin.androidtv (pid 15489) has died
11-27 20:59:43.928   610 15468 I ActivityManager: Start proc 15621:org.jellyfin.androidtv/u0a165 for activity org.jellyfin.androidtv/.startup.StartupActivity
11-27 20:59:44.704   610   898 I ActivityManager: START u0 {flg=0x10000000 cmp=org.jellyfin.androidtv/org.acra.dialog.CrashReportDialog (has extras)} from uid 10165 on display 0
11-27 20:59:44.736   610  3020 I ActivityManager: Start proc 15736:org.jellyfin.androidtv:acra/u0a165 for activity org.jellyfin.androidtv/org.acra.dialog.CrashReportDialog
11-27 20:59:45.026   610  3020 I ActivityManager: START u0 {cmp=org.jellyfin.androidtv/.startup.StartupActivity} from uid 10165 on display 0
11-27 20:59:45.263   610  3020 I ActivityManager: START u0 {cmp=org.jellyfin.androidtv/.browsing.MainActivity} from uid 10165 on display 0
11-27 21:00:22.819   610  3166 I ActivityManager: START u0 {cmp=org.jellyfin.androidtv/.details.FullDetailsActivity (has extras)} from uid 10165 on display 0
11-27 21:00:24.435   610 15468 I ActivityManager: START u0 {cmp=org.jellyfin.androidtv/.playback.PlaybackOverlayActivity (has extras)} from uid 10165 on display 0
11-27 21:02:24.562   610  3166 I ActivityManager: START u0 {cmp=org.jellyfin.androidtv/.playback.PlaybackOverlayActivity (has extras)} from uid 10165 on display 0
11-27 21:08:15.326   610  3166 I ActivityManager: Killing 15736:org.jellyfin.androidtv:acra/u0a165 (adj 900): empty #17
11-27 21:09:15.667 15621 17007 I chatty  : uid=10165(org.jellyfin.androidtv) expire 7 lines
11-27 21:09:15.887 15621 16998 I chatty  : uid=10165(org.jellyfin.androidtv) expire 7 lines
11-27 21:09:18.060 15621 15621 I chatty  : uid=10165(org.jellyfin.androidtv) expire 10 lines
11-27 21:09:33.065 15621 15621 I chatty  : uid=10165(org.jellyfin.androidtv) expire 11 lines
11-27 21:09:48.074 15621 15621 I chatty  : uid=10165(org.jellyfin.androidtv) expire 3 lines
11-27 21:09:50.993 15621 17007 I chatty  : uid=10165(org.jellyfin.androidtv) expire 1 line
11-27 21:09:51.403 15621 16998 I chatty  : uid=10165(org.jellyfin.androidtv) expire 1 line
11-27 21:09:51.467 15621 15621 I chatty  : uid=10165(org.jellyfin.androidtv) expire 3 lines
11-27 21:09:56.050 15621 17007 I chatty  : uid=10165(org.jellyfin.androidtv) expire 1 line
11-27 21:09:56.444 15621 16998 I chatty  : uid=10165(org.jellyfin.androidtv) expire 1 line
11-27 21:09:57.077 15621 15621 I chatty  : uid=10165(org.jellyfin.androidtv) expire 6 lines
11-27 21:10:01.100 15621 17007 I chatty  : uid=10165(org.jellyfin.androidtv) expire 1 line
11-27 21:10:01.482 15621 16998 I chatty  : uid=10165(org.jellyfin.androidtv) expire 2 lines
11-27 21:10:06.081 15621 15621 I chatty  : uid=10165(org.jellyfin.androidtv) expire 2 lines
11-27 21:10:06.117 15621 17007 I chatty  : uid=10165(org.jellyfin.androidtv) expire 1 line
11-27 21:10:08.022 15621 16458 I chatty  : uid=10165(org.jellyfin.androidtv) ExoPlayerImplIn expire 5 lines
11-27 21:10:08.048 15621 18190 I chatty  : uid=10165(org.jellyfin.androidtv) expire 2 lines
11-27 21:10:08.070 15621 16998 I chatty  : uid=10165(org.jellyfin.androidtv) expire 1 line
11-27 21:10:08.075 15621 17007 I chatty  : uid=10165(org.jellyfin.androidtv) expire 1 line
11-27 21:10:08.080 15621 16458 I chatty  : uid=10165(org.jellyfin.androidtv) ExoPlayerImplIn expire 3 lines
11-27 21:10:08.082 15621 15621 I chatty  : uid=10165(org.jellyfin.androidtv) expire 3 lines
11-27 21:10:08.088 15621 16458 I chatty  : uid=10165(org.jellyfin.androidtv) ExoPlayerImplIn expire 4 lines
11-27 21:10:09.082 15621 15621 I chatty  : uid=10165(org.jellyfin.androidtv) expire 2 lines
11-27 21:10:11.169 15621 17007 I chatty  : uid=10165(org.jellyfin.androidtv) expire 1 line
11-27 21:10:11.555 15621 16998 I chatty  : uid=10165(org.jellyfin.androidtv) expire 1 line
11-27 21:10:12.083 15621 15621 I chatty  : uid=10165(org.jellyfin.androidtv) expire 4 lines
11-27 21:10:13.025 15621 16998 I chatty  : uid=10165(org.jellyfin.androidtv) expire 1 line
11-27 21:10:13.056 15621 17007 I chatty  : uid=10165(org.jellyfin.androidtv) expire 2 lines
11-27 21:10:16.642 15621 16998 I chatty  : uid=10165(org.jellyfin.androidtv) expire 1 line
11-27 21:10:18.085 15621 15621 I chatty  : uid=10165(org.jellyfin.androidtv) expire 4 lines
11-27 21:10:21.285 15621 17007 I chatty  : uid=10165(org.jellyfin.androidtv) expire 1 line
11-27 21:10:21.721 15621 16998 I chatty  : uid=10165(org.jellyfin.androidtv) expire 1 line
11-27 21:10:24.088 15621 15621 I chatty  : uid=10165(org.jellyfin.androidtv) expire 2 lines
11-27 21:10:26.310 15621 17007 I chatty  : uid=10165(org.jellyfin.androidtv) expire 1 line
11-27 21:10:26.803 15621 16998 I chatty  : uid=10165(org.jellyfin.androidtv) expire 1 line
11-27 21:10:27.090 15621 15621 I chatty  : uid=10165(org.jellyfin.androidtv) expire 7 lines
11-27 21:10:30.617   610  3162 D MediaSessionService: Sending KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MEDIA_FAST_FORWARD, scanCode=208, metaState=0, flags=0x8, repeatCount=0, eventTime=7387354, downTime=7387354, deviceId=6, source=0x301 } to org.jellyfin.androidtv/MediaSessionHelper-org.jellyfin.androidtv (uid=0)
11-27 21:10:31.326 15621 17007 I chatty  : uid=10165(org.jellyfin.androidtv) expire 1 line
11-27 21:10:31.462 15621 15621 I chatty  : uid=10165(org.jellyfin.androidtv) expire 3 lines
11-27 21:10:31.464 15621 16458 I chatty  : uid=10165(org.jellyfin.androidtv) ExoPlayerImplIn expire 6 lines
11-27 21:10:31.488 15621 18195 I chatty  : uid=10165(org.jellyfin.androidtv) expire 2 lines
11-27 21:10:31.532   610  3162 D MediaSessionService: Sending KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MEDIA_FAST_FORWARD, scanCode=208, metaState=0, flags=0x8, repeatCount=0, eventTime=7388293, downTime=7388293, deviceId=6, source=0x301 } to org.jellyfin.androidtv/MediaSessionHelper-org.jellyfin.androidtv (uid=0)
11-27 21:10:31.554 15621 16458 I chatty  : uid=10165(org.jellyfin.androidtv) ExoPlayerImplIn expire 15 lines
11-27 21:10:31.690 15621 15621 I chatty  : uid=10165(org.jellyfin.androidtv) expire 10 lines
11-27 21:10:31.930   610  3162 D MediaSessionService: Sending KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MEDIA_FAST_FORWARD, scanCode=208, metaState=0, flags=0x8, repeatCount=0, eventTime=7388693, downTime=7388693, deviceId=6, source=0x301 } to org.jellyfin.androidtv/MediaSessionHelper-org.jellyfin.androidtv (uid=0)
11-27 21:10:32.610   610  3358 D MediaSessionService: Sending KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MEDIA_FAST_FORWARD, scanCode=208, metaState=0, flags=0x8, repeatCount=0, eventTime=7389373, downTime=7389373, deviceId=6, source=0x301 } to org.jellyfin.androidtv/MediaSessionHelper-org.jellyfin.androidtv (uid=0)
11-27 21:10:33.390 15621 15710 I chatty  : uid=10165(org.jellyfin.androidtv) Thread-6 expire 1 line
11-27 21:10:33.393 15621 15621 I chatty  : uid=10165(org.jellyfin.androidtv) expire 4 lines
11-27 21:10:33.398   610  3162 D MediaSessionService: Sending KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MEDIA_FAST_FORWARD, scanCode=208, metaState=0, flags=0x8, repeatCount=0, eventTime=7390153, downTime=7390153, deviceId=6, source=0x301 } to org.jellyfin.androidtv/MediaSessionHelper-org.jellyfin.androidtv (uid=0)
11-27 21:10:33.589 15621 16458 I chatty  : uid=10165(org.jellyfin.androidtv) ExoPlayerImplIn expire 4 lines
11-27 21:10:33.591 15621 15621 I chatty  : uid=10165(org.jellyfin.androidtv) expire 3 lines
11-27 21:10:33.651   610  3162 D MediaSessionService: Sending KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MEDIA_FAST_FORWARD, scanCode=208, metaState=0, flags=0x8, repeatCount=0, eventTime=7390413, downTime=7390413, deviceId=6, source=0x301 } to org.jellyfin.androidtv/MediaSessionHelper-org.jellyfin.androidtv (uid=0)
11-27 21:10:35.484 15621 15709 E Volley  : 	at org.jellyfin.apiclient.interaction.VolleyStringRequest.parseNetworkResponse(VolleyStringRequest.java:88)
11-27 21:10:42.972   610  3358 D MediaSessionService: Sending KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MEDIA_FAST_FORWARD, scanCode=208, metaState=0, flags=0x8, repeatCount=0, eventTime=7399734, downTime=7399734, deviceId=6, source=0x301 } to org.jellyfin.androidtv/MediaSessionHelper-org.jellyfin.androidtv (uid=0)
11-27 21:10:43.674   610  3162 D MediaSessionService: Sending KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MEDIA_FAST_FORWARD, scanCode=208, metaState=0, flags=0x8, repeatCount=0, eventTime=7400434, downTime=7400434, deviceId=6, source=0x301 } to org.jellyfin.androidtv/MediaSessionHelper-org.jellyfin.androidtv (uid=0)
11-27 21:10:44.135   610  3162 D MediaSessionService: Sending KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MEDIA_FAST_FORWARD, scanCode=208, metaState=0, flags=0x8, repeatCount=0, eventTime=7400874, downTime=7400874, deviceId=6, source=0x301 } to org.jellyfin.androidtv/MediaSessionHelper-org.jellyfin.androidtv (uid=0)
11-27 21:10:44.492   610   897 D MediaSessionService: Sending KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MEDIA_FAST_FORWARD, scanCode=208, metaState=0, flags=0x8, repeatCount=0, eventTime=7401254, downTime=7401254, deviceId=6, source=0x301 } to org.jellyfin.androidtv/MediaSessionHelper-org.jellyfin.androidtv (uid=0)
11-27 21:10:44.912   610  3358 D MediaSessionService: Sending KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MEDIA_FAST_FORWARD, scanCode=208, metaState=0, flags=0x8, repeatCount=0, eventTime=7401674, downTime=7401674, deviceId=6, source=0x301 } to org.jellyfin.androidtv/MediaSessionHelper-org.jellyfin.androidtv (uid=0)
11-27 21:10:45.953 15621 16458 I MediaCodecLogger: org.jellyfin.androidtv.HW.video.avc.StreamAvgFramerate = 2.222
11-27 21:10:47.941 15621 15708 E Volley  : 	at org.jellyfin.apiclient.interaction.VolleyStringRequest.parseNetworkResponse(VolleyStringRequest.java:88)
11-27 21:10:52.054   610  3358 D MediaSessionService: Sending KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MEDIA_FAST_FORWARD, scanCode=208, metaState=0, flags=0x8, repeatCount=0, eventTime=7408814, downTime=7408814, deviceId=6, source=0x301 } to org.jellyfin.androidtv/MediaSessionHelper-org.jellyfin.androidtv (uid=0)
11-27 21:10:52.732   610  3358 D MediaSessionService: Sending KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MEDIA_FAST_FORWARD, scanCode=208, metaState=0, flags=0x8, repeatCount=0, eventTime=7409494, downTime=7409494, deviceId=6, source=0x301 } to org.jellyfin.androidtv/MediaSessionHelper-org.jellyfin.androidtv (uid=0)
11-27 21:10:55.722 15621 15711 E Volley  : 	at org.jellyfin.apiclient.interaction.VolleyStringRequest.parseNetworkResponse(VolleyStringRequest.java:88)
11-27 21:11:06.556   610  3162 D MediaSessionService: Sending KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MEDIA_FAST_FORWARD, scanCode=208, metaState=0, flags=0x8, repeatCount=0, eventTime=7423316, downTime=7423316, deviceId=6, source=0x301 } to org.jellyfin.androidtv/MediaSessionHelper-org.jellyfin.androidtv (uid=0)
11-27 21:11:07.518 15621 16458 I MediaCodecLogger: org.jellyfin.androidtv.HW.video.avc.StreamAvgFramerate = 12.353
11-27 21:11:07.532   610  3358 D MediaSessionService: Sending KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MEDIA_FAST_FORWARD, scanCode=208, metaState=0, flags=0x8, repeatCount=0, eventTime=7424294, downTime=7424294, deviceId=6, source=0x301 } to org.jellyfin.androidtv/MediaSessionHelper-org.jellyfin.androidtv (uid=0)
11-27 21:11:08.634 15621 15708 E Volley  : 	at org.jellyfin.apiclient.interaction.VolleyStringRequest.parseNetworkResponse(VolleyStringRequest.java:88)
11-27 21:11:09.464 15621 15709 E Volley  : 	at org.jellyfin.apiclient.interaction.VolleyStringRequest.parseNetworkResponse(VolleyStringRequest.java:88)

```

**Comment by totti4ever** [comment]
Anything else I could provide to help fixing/debugging?

This bug is really annoying and makes watching kind of not so easy, when it skips back once every 30 minutes or so...and ruins every WAF. Especially as one cannot just continue (because it starts right from the beginning) and has to skip forward by trial and error to find where to resume :-/

**Comment by nielsvanvelzen** [comment]
I don't see anything weird in the provided logs (no exception or other log statements that indicate something not right). Can you try sideloading the latest app build and see if it works with that?

**Comment by totti4ever** [comment]
> I don't see anything weird in the provided logs (no exception or other log statements that indicate something not right). Can you try sideloading the latest app build and see if it works with that?

Hey, where would I find the latest build? Under releases I find 11.4, which seems to be the same as on my firetv stick

**Comment by nielsvanvelzen** [comment]
My bad, I should've included instructions as it's not that easy to find.

The latest build on the repository is this one:
https://dev.azure.com/jellyfin-project/jellyfin/_build/results?buildId=19491&view=artifacts&pathAsName=false&type=publishedArtifacts

You can download it (using the 3 dot menu) and install the .apk that has "debug" in the name. It will be installed separately from your current install. Note that this is a development version and not all functionality works as expected,

**Comment by ngdio** [comment]
I'm also experiencing this issue on my Fire TV 4K. I couldn't find anything in logcat/Jellyfin logs either that would explain why playback is breaking.

I installed the development version @nielsvanvelzen – unfortunately I can't test if direct streaming is working there because playback is now transcoded for absolutely no reason (hevc playback should always be direct streamed).

**Comment by totti4ever** [comment]
> I'm also experiencing this issue on my Fire TV 4K. I couldn't find anything in logcat/Jellyfin logs either that would explain why playback is breaking.
> 
> I installed the development version @nielsvanvelzen – unfortunately I can't test if direct streaming is working there because playback is now transcoded for absolutely no reason (hevc playback should always be direct streamed).

You can just disable right to transcode for that user in the admin interface, that will force direct play, no matter what.

> My bad, I should've included instructions as it's not that easy to find.
> 
> The latest build on the repository is this one:
> [dev.azure.com/jellyfin-project/jellyfin/_build/results?buildId=19491&view=artifacts&pathAsName=false&type=publishedArtifacts](https://dev.azure.com/jellyfin-project/jellyfin/_build/results?buildId=19491&view=artifacts&pathAsName=false&type=publishedArtifacts)
> 
> You can download it (using the 3 dot menu) and install the .apk that has "debug" in the name. It will be installed separately from your current install. Note that this is a development version and not all functionality works as expected,

Okay, I tried the dev version, but that made it even worse :-s Afterwards also the released version didn't work any better o_O
What helped a bit was using an internal URL instead of a https public URL (which is routed locally, so the difference might be the https). Both are using traefik.

Now there are only some freezes left, where one has to restart the episode, because resuming directly freezes again.

**Comment by ngdio** [comment]
I changed my firewall settings to dodge the reverse proxy (for now), now the app is working fine. I previously had similar issues with Kodi (no playback at all). I'm using Caddy though, not Traefik. Might try if Nginx is causing similar behaviour.

**Comment by smidley** [comment]
Is this the same issue?  https://github.com/jellyfin/jellyfin-androidtv/issues/614

**Comment by smidley** [comment]
I still have the same issue even without a reverse proxy: https://github.com/jellyfin/jellyfin-androidtv/issues/614
