### ISSUE TITLE
Jellyfin can't play files that were playable previously

### ISSUE THREAD

**Issue by afraazali** [jellyfin/jellyfin-androidtv#699]
**Describe the bug**

Last night I hooked up my shield to a Sony A8H after using Jellyfin on an old Samsung TV, and I can't seem to play any files at all from Jellyfin. Our other devices all work properly, mostly just testing on our iPhone's.

I've tried with different file types as well. 720P stereo, 720P 5.1 audio, 1080P 5.1 audio, and even 4K Dolby Atmos. My iPhone will play all of those, of course it bogs the server down with the 4K, but that's expected as the goal here is mostly direct play.

The same files through the Jellyfin plugin on Kodi direct play properly, however, I can't get Dolby Vision working with Kodi. Although, I believe only Plex has support for Dolby Vision at the moment.

**To Reproduce**

1. Go to play a movie or tv show
2. See that the movie/show doesn't load
3. Get booted back to the detail page

**Expected behavior**
I expect the episode or movie to play

**Logs**
```
"http://jellyfin:8096/Items/daa49b8ac813ab2ef3a6fc30f58d7a6c/Images/Logo?MaxWidth=440&EnableImageEnhancers=true"
MediaBrowser.Common.Extensions.ResourceNotFoundException: Walker does not have an image of type Logo
   at MediaBrowser.Api.Images.ImageService.GetImage(ImageRequest request, Guid itemId, BaseItem item, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2021-01-22 09:44:27.395 -08:00] [ERR] [121] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://jellyfin:8096/Studios/The+CW/Images/Primary?EnableImageEnhancers=true&MaxHeight=60"
System.ArgumentException: Invalid type (Parameter 'type')
   at MediaBrowser.Api.BaseApiService.GetItemByName(String name, String type, ILibraryManager libraryManager, DtoOptions dtoOptions)
   at MediaBrowser.Api.Images.ImageService.Get(GetItemByNameImage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2021-01-22 09:44:27.630 -08:00] [ERR] [115] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "The operation was canceled". URL: "http://jellyfin:8096/Videos/8f5923ec72f52575f0fe54c0d9a934d5/stream.mkv?DeviceId=e188939384ba582d&MediaSourceId=8f5923ec72f52575f0fe54c0d9a934d5&Tag=2e7f03be33625063e28799a6ca5370e7&Static=true"
[2021-01-22 09:44:28.044 -08:00] [WRN] [111] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "192.168.0.41". Time (slow): 0:00:00.5949441. "http://jellyfin:8096/Sessions/Playing"
[2021-01-22 09:44:28.200 -08:00] [WRN] [118] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 206 to "192.168.0.41". Time (slow): 0:00:00.6204525. "http://jellyfin:8096/Videos/8f5923ec72f52575f0fe54c0d9a934d5/stream.mkv?DeviceId=e188939384ba582d&MediaSourceId=8f5923ec72f52575f0fe54c0d9a934d5&Tag=2e7f03be33625063e28799a6ca5370e7&Static=true"
[2021-01-22 09:44:28.989 -08:00] [INF] [113] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "AndroidTV" "0.11.5" playing "Pilot". Stopped at "0" ms
```

```
[2021-01-25 18:09:36.228 -08:00] [INF] [189] MediaBrowser.Api.Playback.MediaInfoService: GetPostedPlaybackInfo profile: DeviceProfile { Name: "Android-VLC", Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 20000000, MaxStaticBitrate: 100000000, MusicStreamingTranscodingBitrate: 128000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "m4v,3gp,ts,mpegts,mov,xvid,vob,mkv,wmv,asf,ogm,ogv,m2v,mpg,mpeg,mp4,webm,wtv", AudioCodec: "aac,mp3,mp2,ac3,wma,wmav2,dca,dts,pcm,PCM_S16LE,PCM_S24LE,opus,flac,truehd", VideoCodec: null, Type: Video }, DirectPlayProfile { Container: "flac,aac,mp3,mpa,wav,wma,mp2,ogg,oga,webma,ape", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "jpg,jpeg,png,gif", AudioCodec: null, VideoCodec: null, Type: Photo }], TranscodingProfiles: [TranscodingProfile { Container: "mkv", Type: Video, VideoCodec: "h264", AudioCodec: "aac,mp3", Protocol: null, EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: True, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: null, EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: VideoProfile, Value: "none", IsRequired: False }], ApplyConditions: [], Codec: "hevc", Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "high|main|baseline|constrained baseline", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "51", IsRequired: False }, ProfileCondition { Condition: GreaterThanEqual, Property: RefFrames, Value: "2", IsRequired: False }], ApplyConditions: [], Codec: "h264", Container: null }, CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: LessThanEqual, Property: AudioChannels, Value: "8", IsRequired: False }], ApplyConditions: [], Codec: null, Container: null }], ResponseProfiles: [], SubtitleProfiles: [SubtitleProfile { Format: "srt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "srt", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "subrip", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgs", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgssub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "dvdsub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "vtt", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "sub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "smi", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "idx", Method: Embed, DidlMode: null, Language: null, Container: null }] }
[2021-01-25 18:09:36.272 -08:00] [INF] [189] MediaBrowser.Api.Playback.MediaInfoService: User policy for "User". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2021-01-25 18:09:36.272 -08:00] [INF] [189] MediaBrowser.Api.Playback.MediaInfoService: Profile: "Android-VLC", Path: "/data/media/movies/Spider-Man Far from Home (2019)/Spider-Man Far from Home (2019) [imdb-tt6320628][Dolby Vision (Single Layer) DoVi][Remux-2160p][HDR][10bit][h265][AC3 7.1]-LEGi0N.ts", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-01-25 18:09:36.272 -08:00] [INF] [189] MediaBrowser.Api.Playback.MediaInfoService: Profile: "Android-VLC", Path: "/data/media/movies/Spider-Man Far from Home (2019)/Spider-Man Far from Home (2019) [imdb-tt6320628][Dolby Vision (Single Layer) DoVi][Remux-2160p][HDR][10bit][h265][AC3 7.1]-LEGi0N.ts", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-01-25 18:09:36.272 -08:00] [INF] [189] MediaBrowser.Api.Playback.MediaInfoService: Profile: "Android-VLC", Path: "/data/media/movies/Spider-Man Far from Home (2019)/Spider-Man Far from Home (2019) [imdb-tt6320628][Dolby Vision (Single Layer) DoVi][Remux-2160p][HDR][10bit][h265][AC3 7.1]-LEGi0N.ts", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-01-25 18:09:36.324 -08:00] [INF] [189] MediaBrowser.Api.Playback.MediaInfoService: GetPostedPlaybackInfo profile: DeviceProfile { Name: "Android-Exo", Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 20000000, MaxStaticBitrate: 100000000, MusicStreamingTranscodingBitrate: 128000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "m4v,mov,xvid,vob,mkv,wmv,asf,ogm,ogv,mp4,webm", AudioCodec: "aac,ac3,eac3,aac_latm,mp3,mp2,dca,dts", VideoCodec: "h264,hevc,vp8,vp9,mpeg,mpeg2video", Type: Video }, DirectPlayProfile { Container: "aac,mp3,mpa,wav,wma,mp2,ogg,oga,webma,ape,opus", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "jpg,jpeg,png,gif", AudioCodec: null, VideoCodec: null, Type: Photo }], TranscodingProfiles: [TranscodingProfile { Container: "mkv", Type: Video, VideoCodec: "h264", AudioCodec: "ac3,aac,mp3", Protocol: null, EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: True, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: null, EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "high|main|baseline|constrained baseline", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "51", IsRequired: False }], ApplyConditions: [], Codec: "h264", Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: LessThanEqual, Property: RefFrames, Value: "12", IsRequired: False }], ApplyConditions: [ProfileCondition { Condition: GreaterThanEqual, Property: Width, Value: "1200", IsRequired: False }], Codec: "h264", Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: LessThanEqual, Property: RefFrames, Value: "4", IsRequired: False }], ApplyConditions: [ProfileCondition { Condition: GreaterThanEqual, Property: Width, Value: "1900", IsRequired: False }], Codec: "h264", Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: VideoProfile, Value: "none", IsRequired: False }], ApplyConditions: [], Codec: "hevc", Container: null }, CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: LessThanEqual, Property: AudioChannels, Value: "6", IsRequired: False }], ApplyConditions: [], Codec: null, Container: null }], ResponseProfiles: [], SubtitleProfiles: [SubtitleProfile { Format: "srt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "srt", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "subrip", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: Encode, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: Encode, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgs", Method: Encode, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgssub", Method: Encode, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "dvdsub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "vtt", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "sub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "idx", Method: Embed, DidlMode: null, Language: null, Container: null }] }
[2021-01-25 18:09:36.359 -08:00] [INF] [189] MediaBrowser.Api.Playback.MediaInfoService: User policy for "user". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2021-01-25 18:09:36.359 -08:00] [INF] [189] MediaBrowser.Api.Playback.MediaInfoService: Profile: "Android-Exo", Path: "/data/media/movies/Spider-Man Far from Home (2019)/Spider-Man Far from Home (2019) [imdb-tt6320628][Dolby Vision (Single Layer) DoVi][Remux-2160p][HDR][10bit][h265][AC3 7.1]-LEGi0N.ts", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-01-25 18:09:36.359 -08:00] [INF] [189] MediaBrowser.Api.Playback.MediaInfoService: Profile: "Android-Exo", No direct play profiles found for Path: "/data/media/movies/Spider-Man Far from Home (2019)/Spider-Man Far from Home (2019) [imdb-tt6320628][Dolby Vision (Single Layer) DoVi][Remux-2160p][HDR][10bit][h265][AC3 7.1]-LEGi0N.ts"
[2021-01-25 18:09:36.359 -08:00] [INF] [189] MediaBrowser.Api.Playback.MediaInfoService: Profile: "Android-Exo", Path: "/data/media/movies/Spider-Man Far from Home (2019)/Spider-Man Far from Home (2019) [imdb-tt6320628][Dolby Vision (Single Layer) DoVi][Remux-2160p][HDR][10bit][h265][AC3 7.1]-LEGi0N.ts", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-01-25 18:09:36.359 -08:00] [INF] [189] MediaBrowser.Api.Playback.MediaInfoService: Profile: "Android-Exo", No direct play profiles found for Path: "/data/media/movies/Spider-Man Far from Home (2019)/Spider-Man Far from Home (2019) [imdb-tt6320628][Dolby Vision (Single Layer) DoVi][Remux-2160p][HDR][10bit][h265][AC3 7.1]-LEGi0N.ts"
[2021-01-25 18:09:36.359 -08:00] [INF] [189] MediaBrowser.Api.Playback.MediaInfoService: Profile: "Android-Exo", Path: "/data/media/movies/Spider-Man Far from Home (2019)/Spider-Man Far from Home (2019) [imdb-tt6320628][Dolby Vision (Single Layer) DoVi][Remux-2160p][HDR][10bit][h265][AC3 7.1]-LEGi0N.ts", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-01-25 18:09:36.360 -08:00] [INF] [189] MediaBrowser.Api.Playback.MediaInfoService: Profile: "Android-Exo", No direct play profiles found for Path: "/data/media/movies/Spider-Man Far from Home (2019)/Spider-Man Far from Home (2019) [imdb-tt6320628][Dolby Vision (Single Layer) DoVi][Remux-2160p][HDR][10bit][h265][AC3 7.1]-LEGi0N.ts"
[2021-01-25 18:09:36.541 -08:00] [INF] [137] MediaBrowser.Api.Playback.Progressive.VideoService: /usr/lib/jellyfin-ffmpeg/ffmpeg -f mpegts -i file:"/data/media/movies/Spider-Man Far from Home (2019)/Spider-Man Far from Home (2019) [imdb-tt6320628][Dolby Vision (Single Layer) DoVi][Remux-2160p][HDR][10bit][h265][AC3 7.1]-LEGi0N.ts" -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -force_key_frames "expr:gte(t,n_forced*5)" -copyts -avoid_negative_ts disabled -start_at_zero -pix_fmt yuv420p -preset superfast -crf 23 -maxrate 99616000 -bufsize 199232000 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -vsync -1 -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 ac3 -ac 6 -ab 384000  -y "/config/data/transcodes/3357e36849152644d8181298cd49e838.mkv"
[2021-01-25 18:09:37.690 -08:00] [WRN] [53] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "192.168.0.41". Time (slow): 0:00:01.1908313. "http://192.168.0.17:8096/Sessions/Playing"
[2021-01-25 18:09:38.636 -08:00] [ERR] [56] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "A task was canceled". URL: "http://192.168.0.17:8096/videos/6e4cf4eb-066b-abe4-86e2-d168bd08956b/stream.mkv?DeviceId=e188939384ba582d&MediaSourceId=6e4cf4eb066babe486e2d168bd08956b&VideoCodec=h264&AudioCodec=ac3,aac,mp3&AudioStreamIndex=1&VideoBitrate=99616000&AudioBitrate=384000&PlaySessionId=e2f58a8f7a0845828e880f036eab759c&CopyTimestamps=true&RequireAvc=false&Tag=9e4c186fbc53fd403fb229a13b29ed2f&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&h264-maxrefframes=4&ac3-audiochannels=6&aac-audiochannels=6&mp3-audiochannels=6&TranscodeReasons=ContainerNotSupported,VideoCodecNotSupported,AudioCodecNotSupported&allowVideoStreamCopy=false&allowAudioStreamCopy=false,false"
[2021-01-25 18:09:38.636 -08:00] [WRN] [56] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 500 to "192.168.0.41". Time (slow): 0:00:02.124891. "http://192.168.0.17:8096/videos/6e4cf4eb-066b-abe4-86e2-d168bd08956b/stream.mkv?DeviceId=e188939384ba582d&MediaSourceId=6e4cf4eb066babe486e2d168bd08956b&VideoCodec=h264&AudioCodec=ac3,aac,mp3&AudioStreamIndex=1&VideoBitrate=99616000&AudioBitrate=384000&PlaySessionId=e2f58a8f7a0845828e880f036eab759c&CopyTimestamps=true&RequireAvc=false&Tag=9e4c186fbc53fd403fb229a13b29ed2f&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&h264-maxrefframes=4&ac3-audiochannels=6&aac-audiochannels=6&mp3-audiochannels=6&TranscodeReasons=ContainerNotSupported,VideoCodecNotSupported,AudioCodecNotSupported&allowVideoStreamCopy=false&allowAudioStreamCopy=false,false"
[2021-01-25 18:09:38.636 -08:00] [INF] [56] MediaBrowser.Api.ApiEntryPoint: Stopping ffmpeg process with q command for "/config/data/transcodes/3357e36849152644d8181298cd49e838.mkv"
[2021-01-25 18:09:39.346 -08:00] [INF] [56] MediaBrowser.Api.Playback.Progressive.VideoService: FFMpeg exited with code 0
[2021-01-25 18:09:39.346 -08:00] [INF] [56] MediaBrowser.Api.ApiEntryPoint: Deleting partial stream file(s) "/config/data/transcodes/3357e36849152644d8181298cd49e838.mkv"
[2021-01-25 18:09:40.161 -08:00] [WRN] [91] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "192.168.0.41". Time (slow): 0:00:01.2359764. "http://192.168.0.17:8096/Users/79816822d4c74f34991592792860cdf2/Items/6e4cf4eb066babe486e2d168bd08956b?format=json"
[2021-01-25 18:09:40.774 -08:00] [WRN] [36] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "192.168.0.66". Time (slow): 0:00:02.0712594. "http://jellyfin:8096/System/ActivityLog/Entries?startIndex=0&limit=4&minDate=2021-01-19T02%3A09%3A38.687Z&hasUserId=false"
[2021-01-25 18:09:40.816 -08:00] [WRN] [58] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "192.168.0.66". Time (slow): 0:00:02.1129893. "http://jellyfin:8096/System/ActivityLog/Entries?startIndex=0&limit=7&minDate=2021-01-25T02%3A09%3A38.671Z&hasUserId=true"
[2021-01-25 18:09:40.858 -08:00] [INF] [56] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "AndroidTV" "0.11.5" playing "Spider-Man: Far from Home". Stopped at "0" ms
[2021-01-25 18:09:40.861 -08:00] [WRN] [139] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "192.168.0.66". Time (slow): 0:00:02.158085. "http://jellyfin:8096/System/ActivityLog/Entries?startIndex=0&limit=7&minDate=2021-01-25T02%3A09%3A38.687Z&hasUserId=true"
[2021-01-25 18:09:42.120 -08:00] [WRN] [58] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "192.168.0.66". Time (slow): 0:00:01.2807572. "http://jellyfin:8096/System/ActivityLog/Entries?startIndex=0&limit=4&minDate=2021-01-19T02%3A09%3A38.687Z&hasUserId=false"
[2021-01-25 18:09:42.420 -08:00] [WRN] [56] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "192.168.0.41". Time (slow): 0:00:04.4532213. "http://192.168.0.17:8096/Sessions/Playing/Stopped"
```

Logs for a 720P stereo tv episode

```
[2021-01-25 18:49:44.534 -08:00] [INF] [22] MediaBrowser.Api.Playback.MediaInfoService: Profile: "Android-Exo", Path: "/data/media/tv/Seinfeld/Season 06/Seinfeld (1989) - S06E18 - The Doorman [-NTb HULU WEBRip-720p][8bit][h264][AAC 2.0]-NTb.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-01-25 18:49:44.534 -08:00] [INF] [22] MediaBrowser.Api.Playback.MediaInfoService: Profile: "Android-Exo", Path: "/data/media/tv/Seinfeld/Season 06/Seinfeld (1989) - S06E18 - The Doorman [-NTb HULU WEBRip-720p][8bit][h264][AAC 2.0]-NTb.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-01-25 18:49:44.535 -08:00] [INF] [22] MediaBrowser.Api.Playback.MediaInfoService: Profile: "Android-Exo", Path: "/data/media/tv/Seinfeld/Season 06/Seinfeld (1989) - S06E18 - The Doorman [-NTb HULU WEBRip-720p][8bit][h264][AAC 2.0]-NTb.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-01-25 18:49:44.685 -08:00] [ERR] [22] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.0.17:8096/Studios/NBC/Images/Primary?EnableImageEnhancers=true&MaxHeight=60"
System.ArgumentException: Invalid type (Parameter 'type')
   at MediaBrowser.Api.BaseApiService.GetItemByName(String name, String type, ILibraryManager libraryManager, DtoOptions dtoOptions)
   at MediaBrowser.Api.Images.ImageService.Get(GetItemByNameImage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2021-01-25 18:49:44.685 -08:00] [ERR] [84] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.0.17:8096/Items/8fe168994eb6e1b559d47862768cad12/Images/Logo?MaxWidth=440&EnableImageEnhancers=true"
MediaBrowser.Common.Extensions.ResourceNotFoundException: Seinfeld does not have an image of type Logo
   at MediaBrowser.Api.Images.ImageService.GetImage(ImageRequest request, Guid itemId, BaseItem item, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2021-01-25 18:49:44.916 -08:00] [ERR] [48] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "The operation was canceled". URL: "http://192.168.0.17:8096/Videos/67772d9c5f4668adfe0c5e8bd22d1662/stream.mkv?DeviceId=e188939384ba582d&MediaSourceId=67772d9c5f4668adfe0c5e8bd22d1662&Tag=5c5946cbf805446ccebfb2e27e70825c&Static=true"
[2021-01-25 18:49:45.309 -08:00] [WRN] [175] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "192.168.0.41". Time (slow): 0:00:00.6272846. "http://192.168.0.17:8096/Sessions/Playing"
[2021-01-25 18:49:45.468 -08:00] [WRN] [84] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 206 to "192.168.0.41". Time (slow): 0:00:00.612013. "http://192.168.0.17:8096/Videos/67772d9c5f4668adfe0c5e8bd22d1662/stream.mkv?DeviceId=e188939384ba582d&MediaSourceId=67772d9c5f4668adfe0c5e8bd22d1662&Tag=5c5946cbf805446ccebfb2e27e70825c&Static=true"
[2021-01-25 18:49:46.246 -08:00] [INF] [86] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "AndroidTV" "0.11.5" playing "The Doorman". Stopped at "0" ms
```

**Screenshots**
None

**System (please complete the following information):**
 - Android TV
 - Device manufacturer: Nvidia
 - Device model: 2019 Shield Pro running on 8.2.2 (recent update)
 - Jellyfin server version: 10.6.4. I have also tried on 10.7-rc3

**Additional context**
Today I saw that logcat was showing the following error:

```
01-25 18:09:36.202  5663  5764 E Volley  : java.text.ParseException: Unparseable date: "0"
  01-25 18:09:36.202  5663  5764 E Volley  :      at java.text.DateFormat.parse(DateFormat.java:362)
  01-25 18:09:36.202  5663  5764 E Volley  :      at com.android.volley.toolbox.HttpHeaderParser.parseDateAsEpoch(HttpHeaderParser.java:135)
  01-25 18:09:36.202  5663  5764 E Volley  :      at com.android.volley.toolbox.HttpHeaderParser.parseCacheHeaders(HttpHeaderParser.java:97)
  01-25 18:09:36.202  5663  5764 E Volley  :      at com.android.volley.toolbox.StringRequest.parseNetworkResponse(StringRequest.java:98)
  01-25 18:09:36.202  5663  5764 E Volley  :      at org.jellyfin.apiclient.interaction.VolleyStringRequest.parseNetworkResponse(VolleyString  Request.java:88)
  01-25 18:09:36.202  5663  5764 E Volley  :      at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:143)
  01-25 18:09:36.202  5663  5764 E Volley  :      at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
  01-25 18:09:36.202  5663  5764 E Volley  :      at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
  01-25 18:09:36.202  5663  5663 I Jellyfin-AndroidTV: Response received from: http://192.168.0.17:8096/Users/79816822d4c74f34991592792860cdf  2/Items/6e4cf4eb066babe486e2d168bd08956b?format=json
  ```

**Comment by afraazali** [comment]
Disabling refresh rate switching in the client allowed me to play all my files. Still have issues with Dolby vision content in mkv, but I believe this is a limitation of the shield.
