### ISSUE TITLE
Unable to connect to server 

### ISSUE THREAD

**Issue by tomaswl1** [jellyfin/jellyfin-androidtv#719]
Hi i have just built the app using studio and im running jellyfin server 10.7.0 Release Candidate 3 but cannot connect to server via app seen some1else mention this elsewere im using Nvidia shield and ive also tried using emulator in studio same results if i use the playstore jellyfin app it connects perfectly

**Comment by nielsvanvelzen** [comment]
Can you explain what goes wrong? Do you see any error message?

**Comment by tomaswl1** [comment]
i enter my ip and port as normal but gives unable to connect to server then volley error defo not internet connection as the jellyfin app from playstore connects straight away my connection was first thing i checked as volley usually means connection also seen someone mention check date and time on device ive triple checked that also its same via shield , emulator via studio and ive just checked firestick same issue

**Comment by tomaswl1** [comment]
Hi i ran in debug mode this is the error it throws when trying to add server via ip and port i changed were my ip is in the error and put MY IP AND PORT


2021-02-03 13:25:37.113 15463-15525/org.jellyfin.androidtv.debug E/Volley: [278] NetworkDispatcher.processRequest: Unhandled exception java.lang.RuntimeException: Bad URL MY IP AND PORT/System/Info/Public?format=json
    java.lang.RuntimeException: Bad URL MY IP AND PORT/System/Info/Public?format=json
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:175)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
     Caused by: java.net.MalformedURLException: no protocol: MY IP AND PORT/System/Info/Public?format=json
        at java.net.URL.<init>(URL.java:601)
        at java.net.URL.<init>(URL.java:498)
        at java.net.URL.<init>(URL.java:447)
        at com.android.volley.toolbox.HurlStack.executeRequest(HurlStack.java:87)
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:123)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131) 
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111) 
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90) 
2021-02-03 13:25:37.115 15463-15463/org.jellyfin.androidtv.debug E/jellyfin-apiclient: VolleyError com.android.volley.VolleyError: java.lang.RuntimeException: Bad URL MY IP AND PORT/System/Info/Public?format=json
    com.android.volley.VolleyError: java.lang.RuntimeException: Bad URL MY IP AND PORT/System/Info/Public?format=json
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:163)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
     Caused by: java.lang.RuntimeException: Bad URL MY IP AND PORT/System/Info/Public?format=json
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:175)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111) 
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90) 
     Caused by: java.net.MalformedURLException: no protocol: MY IP AND PORT/System/Info/Public?format=json
        at java.net.URL.<init>(URL.java:601)
        at java.net.URL.<init>(URL.java:498)
        at java.net.URL.<init>(URL.java:447)
        at com.android.volley.toolbox.HurlStack.executeRequest(HurlStack.java:87)
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:123)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131) 
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111) 
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

**Comment by nielsvanvelzen** [comment]
Include the `http://` or `https://` part in your server address

**Comment by tomaswl1** [comment]
wow feel like a prat now worked straight away thank you on the older app i only ever had to input ip and port never mind thanks again all sorted and great work so far on the app
