### ISSUE TITLE
(master) App crashes while setting background

### ISSUE THREAD

**Issue by linetrimmer** [jellyfin/jellyfin-androidtv#752]
**Describe the bug**
Sometimes the app will crash while it's loading background images. I can't really find a pattern to it, but I've noticed it more when I scroll around fast.

**Logs**
```
2021-03-03 19:33:48.116 15414-15502/org.jellyfin.androidtv.debug E/ACRA: ACRA caught a ExecutionException for org.jellyfin.androidtv.debug
    java.util.concurrent.ExecutionException: com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 root cause:
    com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)
     call GlideException#logRootCauses(String) for more detail
        at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:217)
        at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:130)
        at org.jellyfin.androidtv.data.service.BackgroundService$setBackground$1$backdropDrawables$2$1.invokeSuspend(BackgroundService.kt:161)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 root cause:
    com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)
     call GlideException#logRootCauses(String) for more detail
```

**System (please complete the following information):**
 - Emulator, Fire TV Stick, Sony Android TVs

**Comment by MrChip53** [comment]
Is this on master?

**Comment by linetrimmer** [comment]
Yes this is using the latest master build

**Comment by MrChip53** [comment]
Where are you scrolling? All items view?

**Comment by linetrimmer** [comment]
The home screen latest items row and the all items view.

**Comment by nielsvanvelzen** [comment]
Are you connecting directly or trough a reverse proxy? And if it's a reverse proxy; does it throttle requests?

**Comment by linetrimmer** [comment]
Through a reverse proxy using caddy. I'll check if it defaults to throttle but I haven't set that myself

**Comment by nielsvanvelzen** [comment]
The exception  `com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)` indicated it is some kind of network issue. I don't think the mount matters.

**Comment by linetrimmer** [comment]
I'm connecting to a remote server that's running on a VPS. Caddy for the reverse proxy (Caddyfile included below) and Cloudflare handles DNS. I'll try connecting directly to the IP address
```
{
    order realip first
}
domain.tld {
    tls /etc/ssl/certs/domain.pem /etc/ssl/private/domain.key.pem {
        client_auth {
            trusted_ca_cert_file /etc/ssl/certs/origin-pull-ca.pem
            mode require_and_verify
        }
    }
    reverse_proxy 172.17.0.1:8096 {
        header_up X-Real-IP {http.request.remote.host}
    }
    realip {
        header "X-Forwarded-For"
        from cloudflare
        maxhops 5
    }
}
```

**Comment by linetrimmer** [comment]
Got it again while connecting directly to the IP address over http:
```
2021-03-03 20:59:23.820 20543-20622/org.jellyfin.androidtv.debug E/ACRA: ACRA caught a ExecutionException for org.jellyfin.androidtv.debug
    java.util.concurrent.ExecutionException: com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 root cause:
    com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)
     call GlideException#logRootCauses(String) for more detail
        at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:217)
        at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:130)
        at org.jellyfin.androidtv.data.service.BackgroundService$setBackground$1$backdropDrawables$2$1.invokeSuspend(BackgroundService.kt:161)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 root cause:
    com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)
     call GlideException#logRootCauses(String) for more detail
```

**Comment by nielsvanvelzen** [comment]
I'm still unable to reproduce unfortunately, I'll try again tomorrow. Probably needs a try-catch somewhere.
