### ISSUE TITLE
Server not reachable

### ISSUE THREAD

**Issue by repomaa** [jellyfin/jellyfin-androidtv#930]
My jellyfin server is on a dedicated server on the internet behind a reverse proxy. When I try connecting with it by choosing manual entry and entering `https://mydomain.com` it immediately fails with "Server not reachable". I tried also adding `:443` to the url but that didn't help. I can connect to the web ui without any problems. The kodi plugin also works.

**System:**
 - Android TV version: 7.0
 - Device manufacturer: Sony
 - Device model: KD-55XD8505
 - Jellyfin server version: 10.7.2

**Comment by Miwer** [comment]
I have this issue also.
Strange thing is, that I see no traffic whatsoever on my reverse proxy logs , when trying to connect from the Jellyfin app.
However, when I use a browser on the TV, I can connect the Jellyfin web ui.

Jellyfin client: 0.12.3
Jellyfin server 10.7.7

my TV is same model and version as OP

**Comment by Miwer** [comment]
Did some digging in the logs, and it seems the Jellyfin app is having trouble connecting via HTTPS to the proxy server:

Again - no problem connecting with the TV browser, so there must be a bug in how the Jellyfin app handles HTTPS connections.

```
11-21 14:28:28.901 10198 10198 D ServerRepositoryImpl$addServer: Adding server jellyfin.*****
11-21 14:28:28.932 10198 10198 D ServerRepositoryImpl$addServer: Found 5 candidates
11-21 14:28:28.936 10198 10198 I RecommendedServerDiscov: Requesting public system info for https://jellyfin.*****
11-21 14:28:28.941  2142  2142 V HotPlugDetectionAction: Poll all devices.
11-21 14:28:28.957 10198 10198 I o.j.s.a.c.KtorClient: HttpMethod(value=GET) https://jellyfin.*****/System/Info/Public
11-21 14:28:29.117 10198 10379 D NetworkSecurityConfig: No Network Security Config specified, using platform default
11-21 14:28:29.267  4942  4942 I chromium: [4942:4942:INFO:metrics_stat_logger.cc(55)] Metrics stat for the past 60 secs : total=0
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient: Unknown error occurred!
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient: javax.net.ssl.SSLHandshakeException: Handshake failed
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:429)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:367)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:325)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:197)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:249)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at java.lang.Thread.run(Thread.java:761)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0xa5bbae80: Failure in SSL library, usually a protocol error
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (external/boringssl/src/ssl/s3_pkt.c:610 0x8fcf0b40:0x00000001)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient: error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (external/boringssl/src/ssl/s3_clnt.c:764 0x9f3ff912:0x00000000)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
11-21 14:28:29.278 10198 10198 E o.j.s.a.c.KtorClient:  ... 20 more
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov: Could not retrieve public system info for https://jellyfin.*****
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov: javax.net.ssl.SSLHandshakeException: Handshake failed
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:429)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:367)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:325)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:197)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:249)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at java.lang.Thread.run(Thread.java:761)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0xa5bbae80: Failure in SSL library, usually a protocol error
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (external/boringssl/src/ssl/s3_pkt.c:610 0x8fcf0b40:0x00000001)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov: error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (external/boringssl/src/ssl/s3_clnt.c:764 0x9f3ff912:0x00000000)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
11-21 14:28:29.279 10198 10198 E RecommendedServerDiscov:       ... 20 more
```

**Comment by vonProteus** [comment]
problem still exists 

Jellyfin for Android TV version: 0.15.0
Android TV version: 7.0
Device manufacturer: Sony
Device model: KDL-50W805C
Jellyfin server version: 10.8.8

**Comment by vonProteus** [comment]
@Miwer @repomaa did you find any walkarounds?

**Comment by Festlandtommy** [comment]
I seem to have the same issue. However, connection over http://hostname also does not work.
Odd thing: I cannot see any DNS requests from the Android TV at my local DNS when trying to connect.

I run Jellyfin on a k8s, so there is a traefik proxy between the Android TV and Jellyfin.
Using the IP of the machine gives me a working connection, but the k8s ingress needs the hostname to route to the right application.

Connection works from the browser using http or https://hostname

**Comment by Miwer** [comment]
> @Miwer @repomaa did you find any walkarounds?

I honestly don't remember if I found a good workaround. I was trying to set Jellyfin client up on the inlaw's TV, so it's not a device I have regular access to and can test on.

However I did find this issue, and it could seem to be a general issue with Android 7.0:
https://community.letsencrypt.org/t/android-7-0-cant-establish-ssl-connection/152050
... if you follow the links in the replies, you will eventually get to the issue reported to google:
https://issuetracker.google.com/issues/37122132

I never got around to test it.

It's something about the public key algorithm. Someone posted a workaround, where you could force your certificates to only use the supported key algorithm (prime256v1, instead of the default), it could make it work. But it was also reported to be a short term solution, since the upstream CA authorities would be switching to newer algorithms, and certificate validation would fail anyway. 
Long term solution would be to upgrade to a newer Android version, which I expect Sony to release aaany moment now (NOT!).

My guess is we have no remedy on this one - unless you want to go unprotected (no SSL). :zipper_mouth_face:

**Comment by Miwer** [comment]
Following up on my previous post. I just tested on the TV in question here. It seems I made it work, by using the workaround I mentioned. I had to force my reverse proxy (traefik) to use TLS connections with the only supported key algorithm. Here is the config I had to add in traefik:
```
tls:
  options:
    default:
      sniStrict: true
      minVersion: "VersionTLS12"
      curvePreferences:
        - "secp256r1"
#        - "secp521r1"
#        - "secp384r1"

      cipherSuites:
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
        - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"

      preferServerCipherSuites: false
```

The key line here is the curvePreferences of only "secp256r1" - I believe the default is one of the others, that I included, but commented out. Also it's a good idea to limit the cipherSuites to only the more secure ones. I'm not sure what the defaults are in traefik.

If you are using some other reverse proxy, or jellyfin directly, I'm sorry, I cannot help there. Google is your friend.

This setup works for me. However I do have some other problems with Jellyfin client on this TV. I get player errors when using libVLC player. ExoPlayer works with video/audio, but maybe have some trouble with subtitles. I tried installing VLC and using "external player", but that didn't work at all. It would just throw an error and not play at all.
